### ISSUE TITLE
TLS 1.2 

### ISSUE THREAD

**Issue by swyphcosmo** [lukesampson/scoop#1002]
I've created a manifest for [mpv](https://mpv.srsfckn.biz/), but the site is signed using TLS 1.2 which (at least for me) wasn't enabled by `[Net.ServicePointManager]::SecurityProtocol`.  Have you had this issue with other packages? If so, how do you handle it?

I got it to work by adding `[Net.ServicePointManager]::SecurityProtocol = 'ssl3,tls,tls12'` to my `Microsoft.PowerShell_profile.ps1` and removing the `-noprofile` from my bash alias. So I'm curious if this is the right way to do it, and what the motivation behind the `-noprofile` argument for bash was.  I didn't want to submit a PR to scoop-extras before discussing this.

Thanks

**Comment by lukesampson** [comment]
I haven't encountered that issue before. I checked my `[Net.ServicePointManager]::SecurityProtocol` and it's only `ssl3,tls` too, so I'm guessing this will be a problem for everyone else too.

The way you're handling it by enabling this in your Powershell profile sounds good to me.

Do you mean `-noprofile` is being passed when starting a new Powershell session from an alias that's defined in Bash? I'm a bit confused about what's going on there, is that an msysgitbash thing? Or cmder, or console2? Personally I start Powershell using the default Windows console, and without the `-noprofile` flag, so I haven't encountered this.

To make this a no-brainer install, maybe we could create a package for `enable-tls12` that is just a couple of powershell scripts to add and remove `tls2` to `[Net.ServicePointManager]::SecurityProtocol`, both saved in the user's `$profile` and for the current session.

**Comment by swyphcosmo** [comment]
I have a Bash alias set in `~/.bashrc` that's the same as you have defined [here](https://github.com/lukesampson/scoop/wiki/Can-I-Use-Scoop-In-Bash%3F). 

An `enable-tls12` script sounds like a great idea. I'll work on that, and let you know what I come up with.

**Comment by lukesampson** [comment]
Oh right, thanks—I've updated that page to not include `-noprofile`.

Look forward to the PR 👍

**Comment by darthwalsh** [comment]
I think TLS 1.2 is off by default in .NET because there were websites that break when you use it. (I'm not sure if that's still true in 2016, though.) Maybe the right thing to do is make it an option in the manifest, instead of changing the powershell profile?

**Comment by RenatoUtsch** [comment]
Any update on this? I'm really missing a mpv bucket.

**Comment by r15ch13** [comment]
TLS 1.2 problems were fixed with f731c1b1b3b1b8a0c12fc4bd0295ee41b8985692 and i just added mpv https://github.com/lukesampson/scoop-extras/commit/de20be22c4e2f24283ea1f16c7a1d78c5c5eb785

**Comment by RenatoUtsch** [comment]
Ooh awesome!
