### ISSUE TITLE
Add cleanup command

### ISSUE THREAD

**Issue by gjmveloso** [lukesampson/scoop#1011]
Hi @lukesampson,

I'm trying to find a `brew cleanup` alternative for scoop. Is this currently supported?

I would love to learn more about PowerShell scripting contributing with this feature if it's not implemented yet.

Thanks,
Gustavo

**Comment by lukesampson** [comment]
Hi! We don't have a `scoop cleanup` or similar yet. Is the idea that it would go through and delete old versions of each app? That sounds like a useful addition, and I'd be happy to accept a pull request for this.

We don't have a list of conventions but if you can try to follow the style of the existing code that would be good. Feel free to ask questions. Looking forward to seeing what you come up with!

**Comment by gjmveloso** [comment]
That's the idea, Luke. I'll work on it :)

**Comment by klauern** [comment]
This isn't true anymore, is it?

```ps1
C:\Users\klauer> scoop
Usage: scoop <command> [<args>]

Some useful commands are:

alias      Manage scoop aliases
bucket     Manage Scoop buckets
cache      Show or clear the download cache
checkup    Check for potential problems
cleanup    Cleanup apps by removing old versions
config     Get or set configuration values
create     Create a custom app manifest
depends    List dependencies for an app
export     Exports (an importable) list of installed apps
help       Show help for a command
home       Opens the app homepage
install    Install apps
list       List installed apps
reset      Reset an app to resolve conflicts
search     Search available apps
status     Show status and check for new app versions
uninstall  Uninstall an app
update     Update apps, or Scoop itself
which      Locate a program path


Type 'scoop help <command>' to get help for a specific command.
```

It looks like `cleanup` is there to me.

**Comment by r15ch13** [comment]
Yep, got added recently with #1648
