### ISSUE TITLE
hash check fail on 'scoop install curl'

### ISSUE THREAD

**Issue by mtnrbq** [lukesampson/scoop#1015]
New scoop install, Win10, below repros each time with same hash values

```powershell
>scoop install curl
installing curl (7.50.1)
downloading https://bintray.com/artifact/download/vszakats/generic/curl-7.50.1-win64-mingw.7z...(1.8 MB) done
checking hash...hash check failed for https://bintray.com/artifact/download/vszakats/generic/curl-7.50.1-win64-mingw.7z. 
expected: 904822c0de991903e9c5f4579745615bec8aa7e3c9948d42d217570f4a817e40, 
actual: 7f2c5fa8d90028ef91d45e87f4a356bff99d14f63a620c6198d2c4dd218701c8!
```

**Comment by toolpunk** [comment]
Failing again.
`checking hash...hash check failed for https://bintray.com/artifact/download/vszakats/generic/curl-7.50.1-win64-mingw.7z.
expected: 7f2c5fa8d90028ef91d45e87f4a356bff99d14f63a620c6198d2c4dd218701c8,
actual: b5a1f49112b20584f71367031f04deb338921089a689108952751ddca210355b!`

**Comment by m-lima** [comment]
And for curl 7.52.1 too:
checking hash...hash check failed for https://winampplugins.co.uk/curl/curl_7_52_1_openssl_nghttp2_x64.7z. expected: 4d3f35d71cfde1e10c9f3953af6d6b82e8ac8cfa5a602d97b15bf66d343192a6, actual: 06178b6ae4e0b02b46b393db7bda647fb5b467cb8f0e3152dd5b20285858ac2d!

**Comment by r15ch13** [comment]
Try reinstalling curl. The provider changed with #1303

```
scoop uninstall curl
scoop update
scoop install curl
```

**Comment by ssi-mark-williams** [comment]
PS C:\Users\Mark> scoop uninstall
Uninstalling 'curl' (7.53.1).
'curl' was uninstalled.
PS C:\Users\Mark> scoop update
Updating Scoop...
Scoop was updated successfully!
PS C:\Users\Mark> scoop install curl
Installing 'curl' (7.53.1).
download_file (1.8 MB) [======================================================================================] 100%
Checking hash of download_file... Hash check failed for 'https://bintray.com/vszakats/generic/download_file?file_path=cu
rl-7.53.1-win64-mingw.7z#/dl.7z'.
Expected:
    6ef597340eb267100462b2f0bd2e552f0a46652a420836990956e31c91721a34
Actual:
    d5bf81021239628655182e3778b00aea28f542fe405749976b202fb3f7894ba1

**Comment by r15ch13** [comment]
@ssi-mark-williams Fixed with https://github.com/lukesampson/scoop/commit/ec2d2e0bca17c808d82fa813f10a30d1e10ebf97

**Comment by hallysonh** [comment]
Failing again.
```shell
Installing 'curl' (7.54.0).
download_file (1,8 MB) [=================================================] 100%
Checking hash of download_file... Hash check failed for 'https://bintray.com/vszakats/generic/download_file?file_path=curl-7.54.0-win64-mingw.7z#/dl.7z'.
Expected:
    6888c286231a717f95ec236fc9fb934efbd45999d79874398b988c29325a7fe6
Actual:
    127782b5db3c7cf48ba16a2516e707282babf9b874e81e8ff86786f380b4fca6
```

**Comment by r15ch13** [comment]
@hallysonh Fixed with ade0e6b2f02404920cb050024ed203a2a217a2e7

**Comment by mhobbs07** [comment]
I actually tried to download the latest version, but still got the same has check failure. To fix this I removed the curl.json file and then did a `scoop update`. I then scoop installed a previous version of curl. Like so:
` scoop install curl@7.54.0`. This worked fine for me.

**Comment by rrelmy** [comment]
@mhobbs07 I can't reproduce your issue
Did you run `scoop update` before `scoop install curl`?

```
scoop master $ = $ scoop install curl
Installing 'curl' (7.55.1).
curl-7.55.1-win64-mingw.7z (1.9 MB) [==================================================================================================================================] 100%
Checking hash of curl-7.55.1-win64-mingw.7z... ok.
Extracting... done.
Linking ~\scoop\apps\curl\current => ~\scoop\apps\curl\7.55.1
Creating shim for 'curl'.
'curl' (7.55.1) was installed successfully!
```

**Comment by mhobbs07** [comment]
No, that must have been the issue that I was facing. I had to remove the curl.json file in order to be able to do a `scoop update`. It seems to be working fine with the latest version of curl after doing what you suggested.
