### ISSUE TITLE
Issue install curl

### ISSUE THREAD

**Issue by aa6my** [lukesampson/scoop#1026]
hash check failed for https://bintray.com/artifact/download/vszakats/generic/curl-7.50.2-win64-mingw.7z. expected: ACBBA7A45860136FA4E1B212E5032F9EC40CA96477D0874167D986EA0F1AA8E4, actual: d1d8047f5a41107090b65b9ea115daeaf71503a4fc829a671a82468e749c8b40!

**Comment by lukesampson** [comment]
Fixed #1025
