### ISSUE TITLE
RStudio + git

### ISSUE THREAD

**Issue by ck37** [lukesampson/scoop#1028]
Hi,

This is a note that using RStudio (v. 0.99.903) with a scoop installed git does not seem to function correctly. If I open an RStudio project that has git enabled, there is some sort of windows dialog box that opens & immediately closes constantly until I close the project. I can see in the RStudio settings that it has detected the path to the scoop-installed git correctly.

I was able to resolve the issue by installing git from the normal git-scm.com download and restarting RStudio, which then switched to using that git and the problem went away.

Thanks,
Chris

**Comment by richshaw** [comment]
+1, I came across this today as well

**Comment by deevus** [comment]
Was this resolved?

**Comment by deevus** [comment]
It's probably due to shimming in that it has to start powershell first

**Comment by albersonmiranda** [comment]
> Was this resolved?

Nope.

**Comment by dambach** [comment]
same issue in RStudio Version 1.4.1103

**Comment by qutang** [comment]
I'm able to resolve it by changing the git path in Rstudio to `C:\Users\[username]\scoop\apps\git\current\bin\git.exe` instead of using the shim shortcut.

**Comment by AdamFermier** [comment]
> git path in Rstudio

Thanks @qutang that worked for me today - was driving me crazy - thanks again!
