### ISSUE TITLE
Shortcuts are apparently in a wrong location

### ISSUE THREAD

**Issue by inosik** [lukesampson/scoop#1029]
Currently, Scoop puts shortcuts to apps into `$env:USERPROFILE\Start Menu\Programs\Scoop Apps`, I think this should be `$([System.Environment]::GetFolderPath('StartMenu'))\Programs\Scoop Apps` or `$([System.Environment]::GetFolderPath('Programs'))\Scoop Apps`, at least they both return the same path for me.

The way it is right now, I don't see the "Scoop Apps" directory in my start menu. I still can search for the apps in the start menu, though, but the shortcuts appear in the "Files" category. If I copy the shortcuts from the current location to the second one from above, the "Scoop Apps" directory appears in my start menu. Also, the shortcuts appear in the "Programs" category now.

Please note that I'm using Scoop on my machine at work, so this might be some enterprisey configuration issue and I'm completely wrong.

**Comment by lukesampson** [comment]
I just tried it out on my machine. For me, `$([System.Environment]::GetFolderPath('StartMenu'))\Programs\Scoop Apps` maps to `~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps`.

It looks like there is some magic happening so that when the shortcut is created in `~\Start Menu\Programs\Scoop Apps`, it automatically appears under `~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` as well.

And so it appears to work fine for me.

I'm on Windows 10. What are you using?

@damnhandy, since you added support for shortcuts (see #679), do you have any ideas how to handle this?

**Comment by inosik** [comment]
I'm on Windows 7. These are the paths I get:

| Expr | Path |
| --- | --- |
| `$env:USERPROFILE\Start Menu\Programs\Scoop Apps` | `C:\Users\nosikil\Start Menu\Programs\Scoop Apps` |
| `$([System.Environment]::GetFolderPath('StartMenu'))\Programs\Scoop Apps` | `C:\Users\nosikil\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` |
| `$([System.Environment]::GetFolderPath('Programs'))\Scoop Apps` | `C:\Users\nosikil\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` |

> It looks like there is some magic happening so that when the shortcut is created in `~\Start Menu\Programs\Scoop Apps`, it automatically appears under `~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` as well.

Not for me/on this machine/this OS :smile:

**Comment by inosik** [comment]
If that helps, I can try Scoop on a Win 8.1 and a Win 10 machine later today.

**Comment by lukesampson** [comment]
Thanks. Yes that'd be good if you can try Win 8.1 and 10.

**Comment by inosik** [comment]
Okay, this gets even stranger.

On 8.1 and 10 I get the same paths as on 7. But I don't see any shortcuts for apps installed by Scoop, no matter if they are in `$env:USERPROFILE\Start Menu` or in `[Environment]::GetFolderPath('StartMenu')`. The search doesn't even find them.

Also, according to [ss64](http://ss64.com/nt/syntax-folders.html), `$env:USERPROFILE\Start Menu` seems to be the start menu location on XP.

**Comment by damnhandy** [comment]
It could very well be an enterprise-y thing. I did this at home on a Windows 10 and also with Windows 7 Enterprise. I did recall some minor shenanigans with some of the AD policies applied to the developer works stations. I just don't remember exactly what was set as it was ago and my memory is hazy at the moment.

**Comment by lukesampson** [comment]
Thanks for the info guys. I've just updated scoop to use `[environment]::getfolderpath`. On my system, it seems to work fine and the old `~/Start Menu/Programs/Scoop Apps` folder seems to get updated automagically by Windows. My old shortcuts created before this change were removed correctly on `scoop uninstall` after the change as well.

Does it work for you @inosik, after running `scoop update` to get the new changes?

**Comment by inosik** [comment]
> My old shortcuts created before this change were removed correctly on `scoop uninstall` after the change as well.

There seems to be some black magic involved here indeed, as this didn't happen on my machine. Maybe there is some work needed to move the existing shortcuts to the new location, as this seems to be very different on different machines.

I simply moved the old shortcuts to the new location and now I can observe the expected behavior. Freshly installed apps even get highlighted in the start menu.

**Comment by lukesampson** [comment]
Yes, I'm assuming there are some enterprise settings on your machines that prevent the black magic from happening.

I think it's okay to not automatically fix shortcuts that weren't working to begin with, as long as we don't break the ones that were working. And it should work better for all new installs going forward.

Glad it seems to be working for you now. Are you happy to call this "fixed" and close the issue?
