### ISSUE TITLE
openjdk (1.8.0_102-2) fails to install

### ISSUE THREAD

**Issue by Cyianor** [lukesampson/scoop#1040]
Hi! 

I wanted to install OpenJDK today in the most up-to-date version. When trying to do so the install unfortunately fails and I get the following output from `scoop`

```
~ $ scoop install openjdk
installing openjdk (1.8.0_102-2)
loading https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.102-2/java-1.8.0-openjdk-1.8.0.102-2.b14.ojdkbuild.windows.x86_64.zip from cache...
checking hash...ok
extracting...rm : Cannot remove item C:\Users\*****\AppData\Local\scoop\apps\openjdk\1.8.0_102-2\_scoop_extract\java-1.8.0-openjdk-1.8.0.102-2.b14
.ojdkbuild.windows.x86_64\lib\tools.jar: Access to the path is denied.
At C:\Users\Felix\appdata\local\scoop\apps\scoop\current\lib\install.ps1:264 char:21
+                     rm -r -force "$dir\_scoop_extract" -ea stop
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (tools.jar:FileInfo) [Remove-Item], ArgumentException
    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

I am a little lost here as to what the reason for this could be. I tried to install it with administrator rights but that did not work either. I simply got the same output. Any ideas?

**Comment by lukesampson** [comment]
Do you have anti-virus or something that might have started scanning the temporary extraction folder before it was deleted?

**Comment by Cyianor** [comment]
That did the trick! The recent Windows 10 update came with a new version of Windows Defender which apparently is quite invasive. Thanks for the hint!
