### ISSUE TITLE
scoop won't unzip downloaded file ending with x64

### ISSUE THREAD

**Issue by Congee** [lukesampson/scoop#1052]
The zip file I download from `https://dl.snipaste.com/win-x64` actually has a filename: Snipaste-1.8.3-x64.zip.
And the cached filename is `snipaste#1.8.3#https_dl.snipaste.com_win-x64` which is recognized as a `COM_WIN-X64 File (.com_win-x64)` app if you take a look at its property in Windows File Explorer. Thus, here I guess scoop may not take it as a zip file. That's the problem, it won't be uncompressed.

I think the problem may be caused by this line:
https://github.com/lukesampson/scoop/blob/master/lib/decompress.ps1#L19

Therefore, I suggest we use filemagic, like the `file` command in Unix, rather than file extension to determine if a file is compressed.

**Comment by lukesampson** [comment]
There's a trick — you can add `#/snipaste.zip` to the end of the `url` in the manifest and it will be treated as a zip file and extracted.

**Comment by Congee** [comment]
Tnaks, it works well. :D
