### ISSUE TITLE
Error scoop install php-nts

### ISSUE THREAD

**Issue by fritzdacat** [lukesampson/scoop#1063]
installing php-nts (7.0.8)
downloading http://windows.php.net/downloads/releases/php-7.0.8-nts-Win32-VC14-x64.zip...Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

**Comment by fritzdacat** [comment]
ok if I use "scoop install php" it goes ...

**Comment by rrelmy** [comment]
#1088 fixed that if you really want to use php-nts ;-)

**Comment by rrelmy** [comment]
this can be closed
