### ISSUE TITLE
How can I update without dependencies?

### ISSUE THREAD

**Issue by jinahya** [lukesampson/scoop#1064]
Sorry for the title.
I just uninstalled openjdk which might be something's dependency. Say gradle?
When I do `scoop update *`, scoop tries to install openjdk again.
Is there any way to update installed packages without dependencies?
`scoop update * -i` doesn't work, anyway.

**Comment by lukesampson** [comment]
Thanks for reporting that issue. It should work as you'd expect when you call `scoop update` with `--independent` or `-i` now. Let me know if you have any trouble, otherwise I'll close this issue.

**Comment by jinahya** [comment]
Thank you for such a fast response.
I confirm `scoop update * -i` works differently now.

**Comment by lukesampson** [comment]
Cool, I'll close this.
