### ISSUE TITLE
Cannot install Scoop - Home location not set

### ISSUE THREAD

**Issue by runlevelsix** [lukesampson/scoop#107]
I'm on a Windows 7 machine that is normally part of a domain and the HOME variable is set to U:\. When I am not on the network (working from home), I cannot get Scoop to install. It exits with this error:

```
PS C:\Users\myusername> iex (new-object net.webclient).downloadstring('https://get.s
coop.sh')
initializing...
iex : Cannot retrieve the dynamic parameters for the cmdlet. Home location for
this provider is not set. To set the home location, call "(get-psprovider
'FileSystem').Home = 'path'".
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], Parame
   terBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.PowerShe
   ll.Commands.InvokeExpressionCommand
```

All of my Googling can't seem to find a solution to setting my "Home location" so that scoop will install. Any guidance would be appreciated. Thanks.

**Comment by deevus** [comment]
@runlevelsix Did you end up getting Scoop installed?

**Comment by runlevelsix** [comment]
No, I'm afraid not. And now I've moved over to a Mac.

**Comment by deevus** [comment]
@lukesampson Do we want to keep this issue open?

**Comment by lukesampson** [comment]
@moshfegh's fix seems like a good workaround if it comes up again, so I'll close it.

**Comment by yukihane** [comment]
On Azure Functions (v1) environment, same erorr occurs at [`lib/config.ps1`](https://github.com/lukesampson/scoop/blob/master/lib/config.ps1#L1).

    Resolve-Path ~

returns error message:

> 2018-09-29T12:50:00.140 [Error] Exception while executing function: Functions.TimerTriggerPowerShell1. Microsoft.Azure.WebJobs.Script: PowerShell script error. System.Management.Automation: Home location for this provider is not set. To set the home location, call "(get-psprovider 'FileSystem').Home = 'path'".

### workaround

Put following command before executing Scoop.

    (get-psprovider 'FileSystem').Home = "$env:HOME"

### reference

* [Get-PSProvider](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psprovider?view=powershell-5.1)
