### ISSUE TITLE
The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by g-uru** [lukesampson/scoop#1070]
I installed scoop successfully and had to edit the config.ps1 at line 1 from $cfgpath = "~/.scoop" to $cfgpath = "$/.scoop". After the change it "worked".

Now at work we are using a scaler which at certain webpages e.g. 7zip.com asks for my console login. I need assistance to edit the scoop config file. 

I learned from here : https://stackoverflow.com/questions/16735042/the-remote-server-returned-an-error-403-forbidden

request.UseDefaultCredentials = true;
request.Proxy.Credentials = System.Net.CredentialCache.DefaultCredentials;
HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);
req.UserAgent = "[any words that is more than 5 characters]";

Where do i add these settings in scoop?

**Comment by lukesampson** [comment]
Making changes to scoop .ps1 files isn't ideal — the changes will either be overwritten when you run `scoop update`, or the changes will prevent you from updating.

`"~/.scoop" should get expanded to the .scoop directory in your user home directory (same as `
"$env:userprofile\.scoop"`).

You might find [Using Scoop behind a proxy server](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy) helpful.

**Comment by g-uru** [comment]
replacing ~/.scoop with "$env:userprofile\.scoop" works. 
regarding proxy i tried: scoop config proxy username:password@xxx.xxx.xxx.xxx:port 
i still get forbidden. we use zscaler, ideas?

**Comment by g-uru** [comment]
i tried every single option incl. authentification logon, always forbidden (403)

**Comment by JamesCullum** [comment]
Was there a solution to this?  We use zscaler and I encounter the same issue.

**Comment by ug-akhan** [comment]
People who are still struggling can do this.

$downloader=Get-Downloader
$WebProxy = new-object System.Net.WebProxy("http://proxy_host:proxy_port/",$true);
$downloader.Proxy= $WebProxy;
