### ISSUE TITLE
Remove old app versions

### ISSUE THREAD

**Issue by eugenesvk** [lukesampson/scoop#1072]
When updateing an app via `scoop update app` the old version of that app remains, which for some bigger apps can waste a lot of space. Is there a way to remove the old version and only leave the latest and greatest?

**Comment by asmgf** [comment]
According to #1011, it's not implemented yet.
I think, as a workaround you can uninstall the app and then install its latest version:
 `scoop update && scoop uninstall app && scoop install app`.

**Comment by dsbert** [comment]
I think this can be closed because of #1648
