### ISSUE TITLE
can't install 7zip

### ISSUE THREAD

**Issue by fghhfg** [lukesampson/scoop#1107]
win7 en 64bit

```
scoop install 7zip
installing 7zip (16.04)
loading http://7-zip.org/a/7z1604-x64.msi from cache...
checking hash...ok
extracting...exit code was
failed to extract files from C:\Users\abc\scoop\apps\7zip\16.04\7z1604-x64.msi.
log file: ~\scoop\apps\7zip\16.04\msi.log
```

~\scoop\apps\7zip\16.04\msi.log:
```
=== Logging started: 11/3 16  18:48:54 ===
=== Logging stopped: 11/3 16  18:48:55 ===
```

run by admin doesn't help

**Comment by lukesampson** [comment]
I just tested and the manifest, download URL and hash seems okay.

Try disabling anti-virus if you have it running, then retry with `scoop uninstall 7zip; scoop cache rm 7zip; scoop install 7zip`.

**Comment by fghhfg** [comment]
don't use cmder, use cmd. problem solved.
