### ISSUE TITLE
Command 'scoop update' delete scoop if download fail.

### ISSUE THREAD

**Issue by felipecrp** [lukesampson/scoop#1118]
When you run 'scoop update' it first uninstall scoop app, them it start a whole new install of scoop. If there is a problem in the download, like a proxy error, you get scoop scripts removed.

What do you think about download first, check hash, and them uninstall app?

**Comment by lukesampson** [comment]
Yes, that would be better. Would you like to submit a patch?

**Comment by felipecrp** [comment]
Sure, I will make a pull request.

**Comment by lambdakris** [comment]
Hey guys, I think I just ran into this issue. Any tips on how to recover in the meantime?

**Comment by lambdakris** [comment]
Think I got it. Took a look inside https://github.com/lukesampson/scoop/blob/master/bin/install.ps1 to see if I could emulate the install. I downloaded https://github.com/lukesampson/scoop/archive/master.zip, extracted, renamed to current, and placed under ~\AppData\Local\scoop\apps\scoop. Seems to be working...

**Comment by felipecrp** [comment]
You can also 'git clone' scoop repository and run the 'bin/refresh.ps1'.
