### ISSUE TITLE
Add LTS version of node

### ISSUE THREAD

**Issue by mdekstrand** [lukesampson/scoop#1125]
I believe Scoop used to have a `node-lts` package that installed the LTS version of Node, but this went away about the time that Node 7 was released.

I would very much like to have a `node-lts` package available (or possibly `node-boron`, to point to the 6.x LTS series).

**Comment by mdekstrand** [comment]
@lukesampson thanks! Now just #847 is in my way (which I'm currently working around with a `SCOOP` env var).

**Comment by lukesampson** [comment]
@mdekstrand Ok sure. FYI fresh installs of scoop will use a shorter path (~/scoop instead of ~/appdata/local/scoop) to avoid the problem with long paths used by Node.
