### ISSUE TITLE
apache-php-init.ps1 has old PHP5apache2_4.dll reference

### ISSUE THREAD

**Issue by dpnolte** [lukesampson/scoop#1149]
error: couldn't find C:\Users\derk.nolte\scoop\apps\php\7.0.14\php5apache2_4.dll

When I change it to 'php7apache2_4.dll' the script works again.

Update:
Also need to change LoadModule php5_module '$phpmodule' into  php7_module

Copy paste:
```
write-host "checking..."

# check for apache
$apache = scoop which httpd
if($lastexitcode -ne 0) { 'Apache isn''t installed. run ''scoop install apache'''; return }

# check for php
$php = scoop which php
if($lastexitcode -ne 0) { 'PHP isn''t installed. run ''scoop install php'''; return }

$conf = "$(split-path $apache)/../conf/httpd.conf"

'enabling PHP handler...'
$phpmodule = "$(split-path $php -resolve)\php7apache2_4.dll"
if(test-path $phpmodule) {
	$lines = gc $conf
	$phpmodule = $phpmodule -replace '\\', '/'
	"
  # php setup
	LoadModule php5_module '$phpmodule'
	AddHandler application/x-httpd-php .php
	PHPIniDir `"$(split-path $phpmodule)`"
	" | out-file $conf -append -encoding utf8
} else {
	"error: couldn't find $phpmodule"; return
}

"done"
```

**Comment by koseduhemak** [comment]
I use [this](https://gist.githubusercontent.com/juliomenendez/4cad6cba2642bc2d209b742d2154031f/raw/3a25b5627e66578d37fbfed2052e4eff9a4421fc/apache-php-init.ps1) until it is fixed.

**Comment by mikerockett** [comment]
@koseduhemak - Haha, I created my own before even seeing this.

**Comment by nilkesede** [comment]
I updated the [wiki page](https://github.com/lukesampson/scoop/wiki/Apache-with-PHP). 
Now it should work! 

@lukesampson may update her gist and the wiki later?!

**Comment by lukesampson** [comment]
Thanks for fixing the wiki page @nilkesede. I'm happy keeping your gist on the wiki page.
