### ISSUE TITLE
scoop install nodejs timeout

### ISSUE THREAD

**Issue by bluechang** [lukesampson/scoop#1151]
I want to install the latest nodejs , but it stoped during installation。The following is hint：

$ scoop install nodejs
installing nodejs (7.2.1)
loading https://nodejs.org/dist/v7.2.1/node-v7.2.1-x64.msi from cache...
checking hash...ok
extracting...done
installer added D:\Program Files\Scoop\apps\nodejs\7.2.1\nodejs to path, removing
running post-install script...

**Comment by brianjking** [comment]
Hmm, I'm getting a slightly different issue when attempting to install using Scoop...

````
scoop install nodejs
installing nodejs (7.2.1)
loading https://nodejs.org/dist/v7.2.1/node-v7.2.1-x64.msi from cache...
checking hash...ok
extracting...exit code was 1603
failed to extract files from C:\Users\brian\AppData\Local\scoop\apps\nodejs\7.2.1\node-v7.2.1-x64.msi.
log file: ~\AppData\Local\scoop\apps\nodejs\7.2.1\msi.log
PS C:\Users\brian\smugline> cat  ~\AppData\Local\scoop\apps\nodejs\7.2.1\msi.log
=== Logging started: 13-Dec-16  10:47:33 ===
Error 1320. The specified path is too long: C:\Users\brian\AppData\Local\scoop\apps\nodejs\7.2.1\_scoop_extract\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 13-Dec-16  10:47:42 ===
````

**Comment by rrelmy** [comment]
@bluechang I can not reproduce your error. nodejs is installing without problems for me

@brianjking this is a know problem with node and windows. take a look at #847
[Recently](https://github.com/lukesampson/scoop/issues/847#issuecomment-257467682) the path of scoop was changed to `~/scoop`, you could reinstall scoop then it will work

**Comment by mikhail-tsennykh** [comment]
I just had exact same problem as @brianjking after running `scoop update` and `scoop install nodejs`.

I solved that installing `nodejs` globally in the system via:
```scoop install nodejs --global```

which worked, but seems to be a workaround, rather than a solution

**Comment by lukesampson** [comment]
@mikhail-tsennykh: as @rrelmy wrote above, the solution is described in #847. Unfortunately it involves reinstalling Scoop.
