### ISSUE TITLE
windows service management with srvman or service command !

### ISSUE THREAD

**Issue by deepakSP** [lukesampson/scoop#1154]
if we can have srvman command that will be cool.
http://tools.sysprogs.org/srvman/

we can easily manage nginx , php , mysql or other services easily.

I like to do it myself but its single exe file ! couldn't find documentation.

**Comment by lukesampson** [comment]
That'd be great if you can try to add srcman and submit a pull request.

There's some documentation on creating an "application manifest" on the wiki (installation package) [here](https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest).

**Comment by deepakSP** [comment]
ok will try today

**Comment by deepakSP** [comment]
hey, done with manifest file and its working :) thank you.

like to add pr request to main bucket ? what you think !

**Comment by lukesampson** [comment]
Thanks, closing this (see #1155)
