### ISSUE TITLE
wget alias conflict

### ISSUE THREAD

**Issue by tresf** [lukesampson/scoop#1169]
On Windows Server 2016 Core `wget` seems to be an alias to `Invoke-WebRequest`, which fails on a fresh install.

`scoop install wget` succeeds, but there is no obvious way to explicitly use the scoop `wget` binary by default in PowerShell.

`~\scoop\apps\wget\1.xx\wget.exe http://foo/bar` seems to be a viable workaround.

**Comment by lukesampson** [comment]
I use a plugin for [Pshazz](https://github.com/lukesampson/pshazz) that removes this alias and a couple of others that interfere with real programs (see [here](https://github.com/lukesampson/pshazz/blob/master/plugins/aliases.ps1)).

If you don't want to use Pshazz, does `wget.exe http://foo/bar` work as a shorter workaround?

**Comment by tresf** [comment]
> pshazz [...] wget.exe

Perfect.  Yes, `wget.exe` works perfectly, thank you!

**Comment by johnnyoshika** [comment]
Do this to temporarily remove the `wget` alias in the current PowerShell shell:

```
rm alias:wget
```

To automatically remove it every time you start PowerShell, you'll need to update your profile:
  * Check if PowerShell profile exists: `test-path $profile`
  * Create profile if one doesn't exist: `new-item $profile`
  * Edit the profile: `notepad $profile`
  * Add the following like: `remove-item alias:curl`
  * Apply the new profile: `. $profile`
