### ISSUE TITLE
nodejs dependency for yarn

### ISSUE THREAD

**Issue by Alxandr** [lukesampson/scoop#1170]
I use nvm to install node, and as such when installing yarn I don't want nodejs installed (now I have two). Is there any way to deal with this?

**Comment by deevus** [comment]
I think remove the dependency and add a note saying that an installation of
nodejs is required.

**Comment by tehbilly** [comment]
Pretty sure you can also do: `scoop install -i yarn`. The `-i` will prevent dependency installation.

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/b21b6a2be1bcda439e0b9e5f247d44609efcf16a

**Comment by Alxandr** [comment]
Maybe also add `nvm` to the suggest list?

**Comment by r15ch13** [comment]
Done https://github.com/lukesampson/scoop/commit/f11b6c2b032d7b435cffb7ea2ecf869cbc571d53 👍
