### ISSUE TITLE
PHP configuration directory along versions leads to problems

### ISSUE THREAD

**Issue by rrelmy** [lukesampson/scoop#1185]
The [`PHP_INI_SCAN_DIR`](https://secure.php.net/manual/de/configuration.file.php#configuration.file.scan) env is very useful but the current path leads to problems.
The `conf` directory is placed along with the version directories inside `scoop/apps/php`

Scoop picks `conf` as the latest version and also updates from `conf` to `$latest` even if `$latest` is already installed.

```
$ scoop list
Installed apps:

  php (conf)
```
```
$ scoop update php
updating php (conf -> 7.1.0)
uninstalling php (conf)
installing php (7.1.0)
creating shim for php
creating shim for php-cgi
running post-install script...
php was updated from conf to 7.1.0
```

I would suggest creating a separate directory `conf` along `apps`, `cache`, `shims` for such version independent configurations. For the `php` example it would be `scoop/conf/php/` and the `env_set` would be set to following (or we define a `$config_dir` variable)
```
"env_set": {
    "PHP_INI_SCAN_DIR": "$dir\\..\\..\\..\\conf\\php"
},
```
This will break current `php` installations!

A _dirty_ workaround could be filtering `conf` as version inside the `versions` function from `lib/versions.ps1`

**Comment by lukesampson** [comment]
Yes, I agree `~/scoop/conf/php` would be a better location.

And it would also be good to allow `$conf_dir` in the `env_set`. I prefer `$conf_dir` to `$config_dir` for consistency, and to avoid confusion with `scoop config`.

Maybe we could add a `post_install` script to `php.json` to look for `~/scoop/apps/php/conf`, and move it to `~/scoop/conf/php` if it exists?

Are you happy to submit a PR for all these?

**Comment by rrelmy** [comment]
Yes, I will look into that
