### ISSUE TITLE
Uninstall fails to remove shim if architecture has bin defined

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#1191]
https://github.com/lukesampson/scoop/blob/master/bucket/ghostscript.json contains:
````
    "architecture": {
        "64bit": {
            "bin": [ "bin\\gswin64.exe", "bin\\gswin64c.exe" ]
        },
        "32bit": {
            "bin": [ "bin\\gswin32.exe", "bin\\gswin32c.exe" ]
        }
    },
````
When `scoop uninstall ghostscript` is run, the bin files are left in the `shims` directory. 

Side note: running `gswin32` afterwards fails silently, but does return an ERRORLEVEL of 2.

**Comment by lukesampson** [comment]
Thanks for reporting this. It should be fixed now.
