### ISSUE TITLE
ssh-copy-id tries to locate id_rsa from the home?

### ISSUE THREAD

**Issue by jinahya** [lukesampson/scoop#1203]
When I tried to invoke `ssh-copy-id`, I see,

```
C:\Users\myself>ssh-copy-id myserver.com
C:\Users\myself\scoop\apps\ssh-copy-id\current\ssh-copy-id.ps1 : ERROR: Cannot find path 'C:\Users\myself\id_rsa.pub' because it does not exist.
At line:1 char:1
+ & 'C:\Users\myself\scoop\apps\ssh-copy-id\current\ssh-copy-id.ps1' my ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,ssh-copy-id.ps1
```

Where is the default value for `.ssh` with any ssh related commands?

**Comment by r15ch13** [comment]
`ERROR: Cannot find path 'C:\Users\myself\id_rsa.pub' because it does not exist.` says it all.

Stuff related to ssh keys normally happens in `$HOME/.ssh` or in `%USERPROFILE%\.ssh` on Windows.

**Comment by jinahya** [comment]
That's what I'm asking about. Shouldn't it refer `%USERPROFILE%\.ssh\id_rsa.pub`?

**Comment by r15ch13** [comment]
It doesn't use the .ssh directory, you have to set the path with the -i switch. Look at the examples in the code. https://github.com/deevus/ssh-copy-id-posh/blob/master/ssh-copy-id/ssh-copy-id.ps1
