### ISSUE TITLE
[FR] Add variable substitution to all url fields

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#1213]
It would reduce duplication, and maintenance duties, if we were able to use variables in all `url` (and `extract_dir` and other) fields. For example, [7zip.json](https://github.com/lukesampson/scoop/blob/master/bucket/7zip.json) would become:
````
{
    "homepage": "http://www.7-zip.org/",
    "license": "http://www.7-zip.org/license.txt",
    "version": "16.04",
    "architecture": {
        "64bit": {
            "url": "http://7-zip.org/a/7z$cleanVersion-x64.msi",
            "hash": "b3885b2f090f1e9b5cf2b9f802b07fe88e472d70d60732db9f830209ac296067"
        },
        "32bit": {
            "url": "http://7-zip.org/a/7z$cleanVersion.msi",
            "hash": "d9b62c0ed0eb48d2df86d8b83394048414a2a4e1d64a50adb9abcff643471d20"
        }
    },
    "extract_dir": "Files/7-Zip",
    "bin": "7z.exe",
    "checkver": "Download 7-zip ([^\\ ]+)"
}
````
Thoughts?

**Comment by lukesampson** [comment]
I'm keen to make things easier for maintainers. I wonder...

1. Would we need many special variations of the version to work with other manifests. E.g. for [busybox.json](https://github.com/lukesampson/scoop/blob/master/bucket/busybox.json) doesn't use the version in the URL but some sort of extra hex identifier. I haven't looked through all the manifests, but I would guess there are a lot of special cases.
2. Does the new autoupdate functionality automate most of the tedium of setting versions in the manifest already? Does it make sense to keep maintenance logic there, and keep the manifests more explicit / descriptive?

**Comment by r15ch13** [comment]
3. Create a service which runs autoupdate and commits all changes on a daily(?) basis. (Something similar to https://greenkeeper.io/) Therefore the manifests can stay as they are now.

**Comment by lukesampson** [comment]
What do you think, @rasa? Shall we close this issue and rely on autoupdate to help with maintainability?
