### ISSUE TITLE
Do not use aliases

### ISSUE THREAD

**Issue by Gheoan** [lukesampson/scoop#1222]
In my PowerShell profile I have removed the default `gm` alias because it was interfering with [GraphicsMagick](http://www.graphicsmagick.org/) (which adds `gm.exe` to the `PATH`):
```powershell
Remove-Item Alias:\gm -Force
```
Using the command `scoop install openssh` logs the following:
```
c:\program files\graphicsmagick-1.3.25-q8\gm.exe: Unrecognized command 'member'. Use -help for a usage summary or see manual..
```

This is due to `gm` usage in [lib/install.ps1#L738](https://github.com/lukesampson/scoop/blob/f731c1b1b3b1b8a0c12fc4bd0295ee41b8985692/lib/install.ps1#L738) or [lib/install.ps1#L748](https://github.com/lukesampson/scoop/blob/f731c1b1b3b1b8a0c12fc4bd0295ee41b8985692/lib/install.ps1#L748).

I suggest using the full name `Get-Member` instead of the aliases.

**Comment by lukesampson** [comment]
This change resets the `gm` -> `get-member` alias for the scope of the script, as we do for other common aliases. We might switch to the verbose names eventually.
