### ISSUE TITLE
[maven] add sh version of mvn to bin

### ISSUE THREAD

**Issue by jinahya** [lukesampson/scoop#1237]
Apache Maven works just find.
Is it possible to add `mvn` which has no extension along with `mvn.cmd`?
I tend to use cygwin which is a linux emulation and it's not possible to use `mvn` command.
`alias mvn=mvn.cmd` [doesn't expand in non-interactive shell](http://unix.stackexchange.com/a/1499/8557).

**Comment by inosik** [comment]
I prefer using MINGW most of the time, and noticed the same for Yarn, Gradle and others apps, which don't have an EXE-File.

@jinahya The solution described in the ["Can I use Scoop in bash?" wiki page][wiki-page] works here as well. Just replace `scoop.ps1` with `mvn.ps1`, for example.

  [wiki-page]: https://github.com/lukesampson/scoop/wiki/Can-I-Use-Scoop-In-Bash%3F

**Comment by jinahya** [comment]
FIY, I put `alias mvn="powershell -ex unrestricted mvn.ps1"` into `~/.bashrs` and invoking `mvn` launches a new command console window. Thanks, anyway.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F1237
