### ISSUE TITLE
What's the recommended way of installing PowerShell module using scoop?

### ISSUE THREAD

**Issue by wangzq** [lukesampson/scoop#1246]
For example, https://github.com/pcgeek86/PSGitHub is a PowerShell module that I want to install using Scoop, while I can point url to the https://github.com/pcgeek86/PSGitHub/archive/master.zip to install, and possibly to run a post_install script to import the module, it will not be available when I restart the PowerShell session. I suppose I could modify the PowerShell profile to always import it but it is not clean. 

My current idea is that maybe we could add an additional directory to the environment variable "PSModulePath" which can be used to install those PowerShell modules installed by Scoop. Thoughts?

**Comment by lukesampson** [comment]
Thanks for the idea. I've added support for PowerShell modules now based on your suggestion. 

There is some explanation of how it works [here](https://github.com/lukesampson/scoop/wiki/PowerShell-Modules) on the wiki.

I added [PSGitHub](https://github.com/lukesampson/scoop/blob/master/bucket/psgithub.json) as an example and a test-case in case anyone else wants to install PS modules with Scoop.

It seems to work fine for me, but please try it out with `scoop update; scoop install psgithub` and let me know how it goes. I'm not familiar with PS modules, so let me know if anything could be improved.

**Comment by wangzq** [comment]
Thanks Luke very much. Works great!

**Comment by AceHack** [comment]
I can't find this info
