### ISSUE TITLE
which bucket is recommended to include tools like Everything?

### ISSUE THREAD

**Issue by wangzq** [lukesampson/scoop#1249]
Everything is a GUI tool that searches files on Windows extremely fast: https://www.voidtools.com/, it also has a command line interface (https://www.voidtools.com/es.zip). I have created two manifest files for them, but not sure if it is ok to include them here, or which bucket to use. I am fine to keep them in my own bucket if it is not appropriate to include such GUI tools here.

**Comment by lukesampson** [comment]
I think this would be a good fit for the [extras](https://github.com/lukesampson/scoop-extras) bucket, which is where GUI and less well known tools go. A single manifest would be preferable too.

**Comment by wangzq** [comment]
Thanks, I will send a PR to the extras bucket later with one manifest.
