### ISSUE TITLE
Suggestion: Skip install if already installed but continue

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop#1256]
My suggestion is when installing multiple packages, Scoop should warn if something is installed already but shouldn't exit continuing to install from the command line what isn't already installed.   This is in the same vein as apt-get:

$ scoop install openssh coreutils rsync concfg aria2 adb unzip zip tar gzip grep wget curl mysql jq pshazz
openssh (5.4p1-1) is already installed.
use 'scoop update openssh' to install a new version.
$

In this senario, everything but aria2, adb and grep were installed.   But I have to remove from the package list what is already installed to get scoop to continue.  It'd be nice if it would say "package X is already installed" then continue through the list like apt-get does.

**Comment by lukesampson** [comment]
Yes, that's a great suggestion. Thank you. I will take a look at this tonight.

**Comment by lukesampson** [comment]
This should work now.

**Comment by jwhipp** [comment]
Works well, less wasn't installed and I put it at the end of the list.

$ scoop install openssh coreutils rsync concfg aria2 adb unzip zip tar gzip grep wget curl mysql jq pshazz less
openssh is already installed, skipping
coreutils is already installed, skipping
rsync is already installed, skipping
concfg is already installed, skipping
aria2 is already installed, skipping
adb is already installed, skipping
unzip is already installed, skipping
zip is already installed, skipping
gzip is already installed, skipping
tar is already installed, skipping
grep is already installed, skipping
wget is already installed, skipping
curl is already installed, skipping
mysql is already installed, skipping
jq is already installed, skipping
pshazz is already installed, skipping
installing less (394)
downloading https://sourceforge.net/projects/gnuwin32/files/less/394/less-394-bin.zip...(172.2 KB) done
checking hash...ok
extracting...done
downloading https://sourceforge.net/projects/gnuwin32/files/less/394/less-394-dep.zip...(83.2 KB) done
checking hash...ok
extracting...done
linking ~\scoop\apps\less\current => ~\scoop\apps\less\394
creating shim for less
less (394) was installed successfully!

Thanks! Makes scripted installs way easier.
