### ISSUE TITLE
Upgrade gradle to the lastest

### ISSUE THREAD

**Issue by jinahya** [lukesampson/scoop#1259]
I'm curious is there any specific reason why [gradle.json](https://github.com/lukesampson/scoop/blob/master/bucket/gradle.json) is still targetting 2.14.
Can I just contribute with a PR? How can I test locally?

**Comment by lukesampson** [comment]
No reason—we rely on people like you to submit updates. PR's are appreciated!

Check out [Creating an app manifest](https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest) on the wiki, and the [app manifest reference](https://github.com/lukesampson/scoop/wiki/App-Manifests).

To test locally, please run `scoop install bucket\gradle.json` – assuming you're in the root source directory. Using the file path will ensure your updated version gets used.

If that goes okay, you might also consider adding [auto update](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate) information to the manifest, which can help us keep gradle up to date.
