### ISSUE TITLE
Folders per Version

### ISSUE THREAD

**Issue by valc93** [lukesampson/scoop#126]
I had some issues with updating nodejs and ruby. Both, when updated to the newest version, lost all ruby gems and npm packages. I had to re-install them all. I searched through scoop's file directory and found that my packages are still there but in a folder with the previous version number. Is it possible to make nodejs use a single folder with all its packages and not create a folder per version?

**Comment by deevus** [comment]
Excuse me if I'm simplifying this too much, but why not store data in `scoop/data/app`? This way we don't need to have a concept of travelling directories. In most cases it wouldn't need to be on the path and can be specified in config.

**Comment by lukesampson** [comment]
I guess that would work for some programs, but how would we do the config?
Powershell scripts in post_install? I'm thinking this could get quite
complicated for maintainers, although it might simplify things from our
side. I think the maintainers' experience is more important to simplify.

**Comment by MPLew-is** [comment]
I definitely support having some process for moving data and configuration when updating, even if it's just a `post_update` script that receives the old and new app directories as parameters, and can then do whatever is needed to move data before starting the new services. I can currently kludge together a clone of this by having the `post_install` script look for the previous version of the app and execute the update commands if found, but having some way of making that process easier would certainly be nice.

I think that the app data should be kept locally to the version, since it's entirely possible that an upgrade will seriously break something if not done correctly, and copying the data from one version to another means there will at least be a backup if things go wrong.

**Comment by lukesampson** [comment]
@MPLew-is would you like to claim this and try to implement the [travelling directories](https://github.com/lukesampson/scoop/wiki/Travelling-directories) proposal? There is already a [travel_dir](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L742) function which you can use.

**Comment by MPLew-is** [comment]
Sure, I'll claim it. Looking over the proposal though, I have a few proposed modifications:

1. The addition of "traveling files". I know for PHP, for instance, the `php.ini` is in the root directory, and should travel to the new installation.

2. The addition of a way to force the copying of directories. For example, in the current MySQL app manifest, the MySQL data directory is initialized on installation, but should be overwritten with the new data, as the directory is effectively "empty" when initialized.

    - I don't know what the best way would be to implement this on the manifest, so any input would be appreciated

3. The addition of a `post_update` script that would run after the directories/files have been moved, as a catch-all to handle anything more complex (for instance, upgrading MySQL sometimes requires the running of a script to bring the old data into compliance with the new version of the server).


Those are just the first things that popped into my head as to what more I might need to use this functionality, so please feel free to comment.

**Comment by lukesampson** [comment]
1. The manifest `travel_dir` array could become just `travel` and files could be legal there in addition to directories.
2. The intention was that only sub-directories of a travelling directory that already exist at the destination would be ignored when copying them, but not the travelling directory itself. So if it's `"travel": [ "data" ]`, and a new `data` directory is created empty during the update, it should still be updated with the contents of the old `data` directory. Not sure if the implementation of `travel_dir` supports that, but it looks like it might. Does that sound okay?
3. How about adding a note to say "run path/to/mysql/update.bat to update your data" or whatever? I would like to limit the scope (and complexity) as much as possible at first. But we could definitely revisit adding `post_update` once everything else is working smoothly.
