### ISSUE TITLE
Shim/Link updater when multiple packages provide similar executables

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop#1261]
Use case: 

Since busybox provides a lot of the same utils (granted much reduced functionality) it technically conflicts with any package that provides a similar executable (e.g. coreutils, grep, etc).    As I test, I had coreutils installed then installed busybox which updated existing coreutils binary references to itself.  Once busybox was uninstalled, coreutils links were not restored leaving a state where coreutils is installed but non-functional requiring and uninstall and reinstall.

Couple ways that I can think of to avoid this is have a link update function, similar to update-alternatives allowing you to update links to point to say ls from busybox vs. ls from coreutils.  Second way would be to simply disallow busybox to install when a conflicting binary is already installed from another package and vice versa.  In Linuxes, this has been depreciated in favor using update-alternatives which allows one to use binaries from different packages.

The update link/shim idea would be something like this:

$scoop update-alternative grep
1. grep from busybox
2. grep from coreutils
>_

If only one grep is installed:

scoop update-alternative grep
Using 'grep' from coreutils.
$

All in one:

scoop update-alternative grep coreutils
Using grep from coreutils.
$

Just an idea, not sure how difficult that would be to implement in powershell.   Work around right now is to just not have busybox and another package with the same shims/links installed.

**Comment by lukesampson** [comment]
This isn't an ideal solution, but you can use `scoop reset` to restore an app's functionality when it has been overwritten by a newer install. E.g. `scoop reset coreutils` should get you back to a working state after installing `coreutils` and then `busybox`, and then uninstalling `busybox`.

**Comment by jwhipp** [comment]
I actually had no idea reset was possible, it's a way better work around then what I was thinking.
