### ISSUE TITLE
autoupdate writing updated manifest to wrong location

### ISSUE THREAD

**Issue by tehbilly** [lukesampson/scoop#1273]
Really liking the new `autoupdate`, but had a few minutes of frustration from the output manifest path being set incorrectly when not working on `scoop/bucket`. For instance, I forked scoop-extras to update RapidEE. Using `-dir c:\work\scoop-extras` as argument to `~/scoop/apps/scoop/current/bin/checkver.ps1` read and used `c:\work\scoop-extras\RapidEE.json` just fine, but wrote modified manifest to `~\scoop\apps\scoop\current\lib\..\bucket\RapidEE.json`.

I believe [this line](https://github.com/lukesampson/scoop/blob/master/lib/autoupdate.ps1#L222) should be updated to use `-dir` argument.

**Comment by lukesampson** [comment]
Thanks for tracking down that bug. It should be fixed now—are you able to confirm that it works?

**Comment by tehbilly** [comment]
Confirmed as working now. Thanks for the quick turnaround!

**Comment by lukesampson** [comment]
Great. You're welcome!
