### ISSUE TITLE
Fails if zip file contains a file of the same name as the zip file

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#1276]
For some reason `ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn-x64.zip` contains a `zip300xn-x64.zip` file inside of it, which https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L297 erroneously deletes. Patch to come to fix it.

**Comment by lukesampson** [comment]
I think it's a bit clearer if we fix this by removing the original zip earlier in the process.

**Comment by rasa** [comment]
Agreed.
