### ISSUE TITLE
Features Request: command to cleanup all cache, remove old app version

### ISSUE THREAD

**Issue by jeud** [lukesampson/scoop#1288]
Hi

I would like to request some new features for `scoop`

1. A CLI command to clean up all cache at once e.g. `scoop cache rm --all` or anything appropriate
2. Removing old app version flag when updating to new app version e.g. `scoop update nodejs --overwrite`

I hope, these new features would be considered by you
Thanks for this wonderful CLI app
Cheers

**Comment by deevus** [comment]
1. `scoop cache rm *`
2. Agree this would be useful

**Comment by jeud** [comment]
@lukesampson I just pulled the latest update, good job!!!
thanks

**Comment by jeud** [comment]
@deevus by the way, is it possible to remove previous installed versions ? if so which CLI command to use ? (in the `app` folder)

thanks

**Comment by deevus** [comment]
At the moment the only way I know that removes those is to uninstall each
app.

**Comment by jeud** [comment]
Finally `scoop` remove the old app version before installing new app version
great job !

thanks
