### ISSUE TITLE
Possible search improvements?

### ISSUE THREAD

**Issue by mrkishi** [lukesampson/scoop#1289]
Hello, folks.

I just installed `ripgrep` with scoop and in doing so came across a couple of usability problems (imo). These problems arose because it is actually named `rg` in scoop:

```
> scoop search ripgrep

>
```

1. Searches without results just return to the shell -- it took me a second to realize there wasn't a problem, just no matches.
2. There are no descriptions or alternative names for scoop to search through. Even though it's officially named `ripgrep`, one has to search for `rg`. The same thing happens (coincidentally) to `The Silver Searcher` aka `ag`, for instance.

I can open a PR for the first point if there's no objection.

The second one is a bit trickier, though. I could argue `rg` should be renamed to `ripgrep` providing the `rg` binary (I still think that should probably happen), but I feel like in the long run it's probably a good idea to recommend manifest creators to add a short description field and start also providing search results from that.

**Comment by rasa** [comment]
There is an undocumented [`description`](https://github.com/lukesampson/scoop/blob/master/schema.json#L354) field. We may want to look at (bower)[https://github.com/bower/spec/blob/master/json.md] or similar json based schemas and move towards a similar naming conventions (`description`, `keywords`, `name`, etc.)

**Comment by lukesampson** [comment]
I think renaming `rg` to `ripgrep` would be a good move.

I'm not so sure about the `description` field, because I think you usually either know what you're installing or the `homepage` will do a better job of describing it.

`keywords` could be a good idea, but then manifest creators might feel the need to add descriptive tags like "java text search engine" etc, and I think that sort of broad search-ability is unnecessary because people usually know more precisely what they want to install and they just want to find the manifest name.

I think an `aka` property would be good for the cases you outlined where the program is also known as different things that wouldn't otherwise be matched in a search. And it's more clear that package maintainers don't always need to use it. And as you pointed out, in the case of `rg` being renamed to `ripgrep` but retaining the `rg` shim then it wouldn't even be necessary.

**Comment by talha131** [comment]
> I'm not so sure about the description field, because I think you usually either know what you're installing or the homepage will do a better job of describing it.

> keywords could be a good idea, but then manifest creators might feel the need to add descriptive tags like "java text search engine" etc, and I think that sort of broad search-ability is unnecessary because people usually know more precisely what they want to install and they just want to find the manifest name.

In my case, I use tools like brew and scoop to search for new better tools. These tools are not just installation helper but also serve as curated list of apps.

Google is good but it does not always suggest the best tool for a job. I usually have to scour through forums to find best tool for a job.

Secondly opening homepage for every app is time consuming. I see the name vcredist but I have no idea what its about. I have to open homepage, switch to browser and read through it. Having shortcut description right in front of vcredist in scoop command output is obviously less time consuming.

So I think a description field that is included in search is definitely valuable.

**Comment by gheoan** [comment]
I have noticed this strange behaviour:
```
~ $ scoop bucket rm extras
~ $ scoop search sdk
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'extras'' bucket:
    sdk

~ $ scoop bucket add extras
Checking repo... ok
Cloning into 'C:\Users\*\scoop\buckets\extras'...
remote: Counting objects: 4244, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 4244 (delta 44), reused 63 (delta 22), pack-reused 4146R
Receiving objects: 100% (4244/4244), 1.01 MiB | 419.00 KiB/s, done.
Resolving deltas: 100% (2426/2426), done.
The extras bucket was added successfully.
~ $ scoop search sdk
'extras' bucket:
    eclipse-sdk (4.7.0)
```

Notice the difference between search results.

**Comment by rasa** [comment]
Another thought is letting `scoop search rg` search the `bin` executables, allowing the `rg` package to be renamed to `ripgrep`. Thoughts?

**Comment by lukesampson** [comment]
Scoop [already searches `bin`](https://github.com/lukesampson/scoop/blame/master/libexec/scoop-search.ps1#L15), so it should be safe to rename `rg` to `ripgrep`.

@gheoan thanks for reporting that. Would you mind creating a new issue?

**Comment by gheoan** [comment]
@lukesampson my bad, I thought this is a general issue about the search function. https://github.com/lukesampson/scoop/issues/1612 is the new issue.
