### ISSUE TITLE
'Cannot find path' while installing ruby

### ISSUE THREAD

**Issue by TimHacker** [lukesampson/scoop#129]
I'm getting this output when running `scoop install ruby`:

```
> scoop install ruby
installing 7zip (9.20)
loading http://downloads.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi from cache...
checking hash...ok
extracting...done
creating shim for 7z
7zip (9.20) was installed successfully!
installing ruby (2.0.0-p481)
loading http://dl.bintray.com/oneclick/rubyinstaller/ruby-2.0.0-p481-x64-mingw32.7z?direct#/dl.7z from cache...
checking hash...ok
extracting...done
downloading http://cdn.rubyinstaller.org/archives/devkits/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe#/dl2.7z...done
checking hash...ok
extracting...rm : Cannot find path 'C:\Users\Tim Hacker\appdata\local\scoop\apps\ruby\2.0.0-p481\_scoop_extract' because
 it does
not exist.
At C:\Users\Tim Hacker\appdata\local\scoop\apps\scoop\current\lib\install.ps1:206 char:5
+                 rm -r -force "$dir\_scoop_extract" -ea stop
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Tim Ha...\_scoop_extract:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

I can confirm that the `_scoop_extract` folder doesn't exist.

Could it be related to the spaces in file path issue from this issue?
https://github.com/lukesampson/scoop/issues/128

**Comment by ohare93** [comment]
If you had this happen recently on Windows here is how I fixed it:

1. Open a admin powershell window
2. Add the scoop path permanently with the following command: `setx path "%path%;C:\Users\jmh\scoop\shims"` (replace your user). Open a new tab (to get the new path)
3. Reinstall whatever you need globally: `scoop install -g ruby25`. Refresh window again
    a. Also any dependencies you'll need later, such as `gem install bundler --version 1.17.3` should be done in this admin window too

Open a fresh powershell window (no need for admin now) and all should be fixed permanently 👍 

I hope this takes you less time than it did me 🙏
