### ISSUE TITLE
How to deal with download url from codeplex?

### ISSUE THREAD

**Issue by wangzq** [lukesampson/scoop#1294]
For example, the binary download url from https://httpsysmanager.codeplex.com/releases/view/93261 is https://httpsysmanager.codeplex.com/downloads/get/475350, which downloads a zip file when clicked from browser; but if I directly use the download url in manifest, it will not work. I also tried to put the actual (redirected) download url, while Scoop is able to download it, the file is not having zip extension and hence unable to extract.

**Comment by lukesampson** [comment]
You can use the redirect URL with fragment like `#/dl.zip` on the end to change the downloaded file name.

```
http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=httpsysmanager&DownloadId=475350&FileTime=129902094255270000&Build=21031#/dl.zip
```

**Comment by wangzq** [comment]
Awesome! Thanks for your quick response.
