### ISSUE TITLE
What happened to git-flow?

### ISSUE THREAD

**Issue by moigagoo** [lukesampson/scoop#1315]
I wanted to update git-flow but got this message:

```shell
couldn't find manifest for git-flow
```

Indeed, there's no manifest in main or extras buckets.

Has it been removed? If yes, why? It's a very useful package.

**Comment by mrkishi** [comment]
Huh. It was removed from `scoop-extras` in lukesampson/scoop-extras@5cc5541.

**Comment by deevus** [comment]
If I'm not mistaken in is included in the git package.

**Comment by moigagoo** [comment]
Great, thanks!

**Comment by moigagoo** [comment]
> If I'm not mistaken in is included in the git package.

Not anymore apparently: https://github.com/git-for-windows/git/releases/tag/v2.51.1.windows.1

**Comment by z-Fng** [comment]
> Not anymore apparently: https://github.com/git-for-windows/git/releases/tag/v2.51.1.windows.1

Relates to:
- https://github.com/git-for-windows/build-extra/pull/648
- https://github.com/ScoopInstaller/Versions/pull/2530

**Comment by moigagoo** [comment]
@z-Fng thanks for the info!

**Comment by z-Fng** [comment]
`git-flow-next` (maintained by the team behind [Tower](https://www.git-tower.com/)) has been added to the Scoop [Main bucket](https://github.com/ScoopInstaller/main). See: https://github.com/ScoopInstaller/Main/pull/7683
