### ISSUE TITLE
Separate main bucket from scoop code?

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#1328]
Changes to manifests are for the most part unrelated to changes to the core scoop codebase. To reduce overlap, we could move the `bucket/` directory into its own repository. Thoughts?

**Comment by lukesampson** [comment]
It would be tidier I suppose. Is it causing problems the way it is though? It might even slow `scoop update` down if we have to do two git pulls rather than two. There doesn't seem to be a big benefit to justify changing it just yet.

**Comment by stkb** [comment]
Wondered about this as well. The way it is at the moment, it's cumbersome to run scoop from a working copy of your own fork, since you have to keep pulling in changes manually, just to keep the main bucket up to date.

**Comment by rasa** [comment]
And we could sub-module the bucket directory, if we wanted. We could even design it to allow users to sub-module any other buckets they wanted, eliminating the need for 'scoop bucket add`

**Comment by AntoineTurmel** [comment]
+1 it would be better so if you watch the scoop github repository you don't have notifications about packages, only the app itself ;)

**Comment by Ash258** [comment]
Core extraction should be easy task to do and should not take too long. But there is one big question.

# How to deal with bucket being in other repository?

There are 3 main options. Submodule / Subtree and actual known bucket flow.

1. Known bucket flow would be most familiar to users
    - It would require few code tweaks.
        - Replace hardcoded bucket path
        - scoop update / checkup to reflect change and no need for users to do anything.
        - It would allow user to install from main bucket using `main/manifest` syntax, which is not possible right now
1. Submodule / Subtree
    - Easiest method, with single config file, but I don't know, how would this affect users.

# Extraction process

1. [ ] Postpone Excavator
1. [ ] Binaries
	- Remove default dir parameter
1. [ ] lib
	- All hardcoded path to core repository bucket folder:
		- <https://github.com/lukesampson/scoop/blob/589303facc5284f6f95c1305191e0558c0169691/test/Scoop-Manifest.Tests.ps1#L1>
		- <https://github.com/lukesampson/scoop/blob/589303facc5284f6f95c1305191e0558c0169691/test/Scoop-Manifest.Tests.ps1#L50>
		- <https://github.com/lukesampson/scoop/blob/0029f0b29dda9d82e72e1cf53183231cd8bf79d4/lib/buckets.ps1#L64>
		- <https://github.com/lukesampson/scoop/blob/936cf9cbb0c4dd3a594fbaf5c696ce519e586d8c/libexec/scoop-install.ps1#L7>
        - <https://github.com/lukesampson/scoop/blob/0029f0b29dda9d82e72e1cf53183231cd8bf79d4/lib/buckets.ps1#L11>
	- It should be easy as replace all strings with `bucketsdir 'main'` function call
1. [ ] How to deal with bucket?
	1. Same as other known buckets
		1. [ ] Add first known bucket
			1. [ ] `"main": "ScoopInstaller/MainBucket"`
		1. [ ] On installing add main bucket
		1. [ ] On scoop update # Compatibility check
			1. [ ] Check for already added main bucket
				1. [ ] If it's not added, add
		1. [ ] scoop checkup should check for main bucket
	1. git submodule
	1. git subtree
1. [ ] Extract bucket into custom repository
	1. [ ] Create new repo `ScoopInstaller/MainBucket`
	1. [ ] Extract bucket folder from core repository
		1. [ ] <https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/>
	1. [ ] Binaries
	1. [ ] Readme
	1. [ ] Appveyor
1. [ ] Change excavator config with new repository
1. [ ] Start excavator again
1. [ ] ❓ Rename this bucket into `scoop-core` or something
1. [ ] ❓ Move it to same organization
1. [ ] 🎉🎉 Welcome new era of Scoop with easier maintaining and expanding 🎉🎉
