### ISSUE TITLE
Gittip/OpenCollective

### ISSUE THREAD

**Issue by gerred** [lukesampson/scoop#1330]
This tool has single-handedly (moreso than anything else I've tried) made it reasonable to switch back from MacOS/Linux to Windows, and I'd like to give back and support your development.

Setup a GitTip/OpenCollective account, yo!

**Comment by lukesampson** [comment]
Thanks for your support! Glad you're finding it useful.

There is a fairly well-hidden donation page [here](http://scoop.sh/donate) with Paypal and Gittip (which I'll update to Gratipay).

I've just added a link to the donation page at the bottom of the [readme](https://github.com/lukesampson/scoop/blob/master/README.md) too.
