### ISSUE TITLE
Scoop-y-doo Webproject

### ISSUE THREAD

**Issue by CodeFreezr** [lukesampson/scoop#1336]
Hello Together,

we would create something like the homebrew web page just for searching and reading scoop packages. For this we would enhance all the packages with a one-liner-description. At first we thought about an additional database. But after some discussions we came to the idea to add a new field in the json-manifest like "abstract" or "synopsis", limited to something like 120 Chars. We talked also about using the description field, but this could interfere with existing filled descriptions fields. 

In the end this could make it easier to find and/or distinguish similiar apps, or even offer a better "browse-a-round" experience.

As our contribution we would offer to add to all apps this attribute and value intially.

What do you think about this?

**Comment by lukesampson** [comment]
Individual project websites can do a better job of describing their project than we can, and it's good to leave that responsibility with them. If we can automatically grab and sync a description with autoupdate, then I think this would be a fine idea, and I think `description` is the logical place to put this in manifests.

FYI, `scoop home` is a quick way to open a project's website and find out more about it.

**Comment by CodeFreezr** [comment]
Yes `scoop home` is a nice shortcut. 

On one side we are interested to build a page a bit like braumeister.org just for scoop. On the other side we would like to see a search result like npm offers: `[name]` `[version]` `[abstract]`. So a longer list is faster to scan and to find out where to use `scoop home`.
