### ISSUE TITLE
problem with rsync

### ISSUE THREAD

**Issue by AStupidBear** [lukesampson/scoop#1338]
I installed rsync on Windows 10 using Scoop, and I want to set up password-less SSH. I ran ssh-keygen in the rsync/bin folder to create the keys, and copied the public key to the remote box. But when I try to SSH, I get this:
```
C:\>ssh myuser@myhost
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0660 for '/cygdrive/c/Users/myuser/.ssh/id_dsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /cygdrive/c/Users/myuser/.ssh/id_dsa
```

I know this is not a scoop issue, but do you know how to fix this? I don't want to input password everytime when I use rsync.

**Comment by rrelmy** [comment]
You have to adjust the permissions to the key files.

Take a look at
http://stackoverflow.com/questions/1556119/ssh-private-key-permissions-using-git-gui-or-ssh-keygen-are-too-open
