### ISSUE TITLE
imagemagick 7.0.4-10 installed, but 7.0.4-9 is reported

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#1344]
I ran:
````
scoop status
````
which reported everything was up to date. I then ran
````
scoop update *
````
which upgraded imagemagick from 7.0.4-9 to 7.0.4-10.
When I now run
````
scoop list
````
it shows
````
imagemagick (7.0.4-9)
````
Is this become `1` comes before `9`?

**Comment by lukesampson** [comment]
Version comparison should work better when versions have dashes in them now.

Thanks for reporting this.

**Comment by rasa** [comment]
Confirmed fixed. Thanks for the quick fix!
