### ISSUE TITLE
Error installing apache

### ISSUE THREAD

**Issue by jeud** [lukesampson/scoop#1355]
I have got error during apache installation

![](http://i.cubeupload.com/i6wqEH.png)

P.S. I have retried it twice

Thanks

**Comment by r15ch13** [comment]
Please run `scoop update` and `scoop install apache` again. 😄

**Comment by jeud** [comment]
@r15ch13

![](http://i.cubeupload.com/2XkXFc.png)

I have got this error since yesterday but I forgot to mention about it, I think I still don't get the correct app's manifest including the apache

**Comment by jeud** [comment]
the git command shown below solve my problem on `scoop update`, after that everything is going just fine

problem solved

```bash
cd %UserProfile%\scoop\buckets\versions
git reset --hard FETCH_HEAD
```

**Comment by deevus** [comment]
I had that as well actually. Hmmm

**Comment by r15ch13** [comment]
That's my fault, i messed up the line endings for those files... A hard reset like jeud mentioned or removing and adding the versions bucket should fix it.
