### ISSUE TITLE
postgresql (9.6.2) installation failure

### ISSUE THREAD

**Issue by martin-grofcik** [lukesampson/scoop#1359]
Postgresql 9.4.0 was uninstalled, no postgresql service is running, but postgresql installation fails.

```
PS C:\Users\martin> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

```
PS C:\Users\martin> scoop install postgresql
Installing 'postgresql' (9.6.2).
postgresql-9.6.2-1-windows-x64-binaries.zip (179,5 MB) [======================================================] 100%
Checking hash of postgresql-9.6.2-1-windows-x64-binaries.zip... ok.
Extracting... Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "The process cannot access the
file 'C:\Users\martin\scoop\apps\postgresql\9.6.2\_scoop_extract\pgsql\bin\createuser.exe' because it is being used by a nother process."
```

Could you help me to solve the issue?

**Comment by r15ch13** [comment]
Does the directory `C:\Users\martin\scoop\apps\postgresql` still exists after uninstalling postgresql?
Did you try to remove it manually?
Have you tried turning it off and on again? (aka restarted your pc)

**Comment by martin-grofcik** [comment]
> Does the directory C:\Users\martin\scoop\apps\postgresql still exists after uninstalling postgresql?
> Did you try to remove it manually?
after `scoop uninstall postgresql` directory is correctly removed

> Have you tried turning it off and on again? (aka restarted your pc)
yes.

**Comment by r15ch13** [comment]
Can you remove in manually?

**Comment by martin-grofcik** [comment]
There was nothing to remove after `scoop uninstall postgresql`. There was no postgresql in the app folder.

**Comment by r15ch13** [comment]
What happens if you extract `postgresql-9.6.2-1-windows-x64-binaries.zip` manually somewhere? Does this work? The only thing i can think of is an antivirus tool or something accessing the file while extracting. 😕

**Comment by lukesampson** [comment]
+1 for antivirus—try disabling it before you install. If it does turn out to solve the problem, please let us know which antivirus program you're using. Maybe we can detect it or at least document it for others.

**Comment by martin-grofcik** [comment]
Windows defender was turned **off**. I turned it **on** and installation works now.

**Comment by martin-grofcik** [comment]
Thanks a lot for your prompt support!
