### ISSUE TITLE
Feature request: use environment variable to override cache location

### ISSUE THREAD

**Issue by wangzq** [lukesampson/scoop#1363]
This way I can share the cache on an intranet share for multiple computers.

I can send a PR if you approve.

Thanks

**Comment by lukesampson** [comment]
Yes I would accept a PR for this, but do we know that it will handle concurrent access to the same file if multiple users can access the shared cache?

Will Windows automatically lock a file while it's being cached (i.e. written to disk) and prevent another user from loading it part way through? And will it work for network shares?

**Comment by wangzq** [comment]
Good point regarding locking and concurrent access; I haven't really tested it this but I think whoever is first writing to the cache will lock the file so others will either fail when they try to write to the same cache (if they also detected the cache doesn't exist yet) or they fail to read the cache (when they detected the cache file). To be honest I don't think we should handle such cases, just let them to fail -- after all, I assume whoever using this optional environment variable would know such limitations. 

Anyway, right now I am only trying to add minimum code to override the cache location in function cache_path in install.ps1.

**Comment by lukesampson** [comment]
Okay please go ahead and submit the PR, with a code comment that this is experimental and untested, may cause issues etc.

You probably already worked it out, but the environment variable should be named SCOOP_CACHE.
