### ISSUE TITLE
Update haskell (nested installers)

### ISSUE THREAD

**Issue by rrelmy** [lukesampson/scoop#1368]
I am trying to update haskell to the latest version 8.0.2 but I am running into problems doing so.

Haskell provides an installer, inside this installer are more installers
```
temp/Extralibs-setup.exe
temp/GHC-setup.exe
temp/MSys-setup.exe
temp/stack-1.3.2-windows-i386-installer.exe
```

To get the files we need `GHC-setup.exe` must be extracted as well.

Do we have support for such situations?

---

I am not familiar with haskell, would be great if a haskell user could verify the update in the end.

**Comment by lukesampson** [comment]
There isn't support for nested installers, but would it work to run a `post_install` script to run the nested installers?

**Comment by rrelmy** [comment]
Instead of extracting the hole thing I now just run the installer. Seems a lot easier.

Maybe we should consider breaking up the haskell platform into its parts (ghc, cabal and stack) like the chocolatey guys do.

If some haskell peoples are having problems with the update, please report them :-)

**Comment by mdogadailo** [comment]
Hi @rrelmy latest update for haskell shows UAC popup
