### ISSUE TITLE
Any way to create extra shim without download?

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1375]
I was wanting to create a manifest for the Python IDLE IDE that simply adds another link to the shims pointing to `~/scoop/apps/python/current/Lib/idlelib/idle.bat`.  Is there any way I can add a shim from an extra manifest without a download URL in that manifest, just a dependency (so that it could be installed as `idle` instead of adding it to the `python` manifest)?

**Comment by lukesampson** [comment]
Scoop will prevent you shim'ing outside the install directory as a security precaution.

It's a bit of a hack, but maybe something like this would work?

```json
{
   ...
   "depends": [ "python", "shim" ],
   "post_install": "shim ~/scoop/apps/python/current/Lib/idelib/idle.bat"
   ...
}
```

This uses a different [shim](https://raw.githubusercontent.com/lukesampson/psutils/32355ba5a0/shim.ps1) implementation to what Scoop uses, but it might get the job done.

**Comment by tech4him1** [comment]
That is a bit of a hack.  What would be your "preferred" method of implementing something like the Python IDLE link?  Download the whole Python, then extract the lib only?

**Comment by lukesampson** [comment]
That might work in other cases, but the Python installer exe is a black box that doesn't allow you to extract files. You need to run the full install and then work with the files it outputs.

Another alternative would be to do something like [git-with-openssh](https://github.com/lukesampson/scoop/blob/master/bucket/git-with-openssh.json), e.g. `python-with-idle` where you duplicate the original and add extra bins.

The hack I proposed (if it works) is better in terms of maintenance (no code duplication, no conflicting installs) and bandwidth.

Of course, it's also possible to just add idle as a bin in the existing Python manifest.

**Comment by tech4him1** [comment]
The problem with the `shim` command that you have is that (as far as I can tell) it dosen't let you specify where to put the shim.  That means even if the package is uninstalled, the shim still remains.

Here is a version I made by copying the parts I needed from your shim script (what is the license on that?).  The only "problem" is that a generic icon shows up in the start menu because you are linking to a `cmd` instead of an `exe`.
```json
{
    "version": "0.1",
    "depends": [ "python" ],
    "pre_install": "
        $pythonDir = [System.IO.Path]::GetDirectoryName((scoop which python))
        $idlePath = convert-path \"$pythonDir\\Lib\\idlelib\\idle.bat\"

        \"@`\"$idlePath`\" %*\" | out-file \"$dir\\idle.cmd\" -encoding oem",
    "bin": [
        "idle.cmd"
    ],
    "shortcuts": [
        [
            "idle.cmd",
            "IDLE (Python)"
        ]
    ]
}
```

**Comment by lukesampson** [comment]
Nice!

I've added an MIT [license](https://github.com/lukesampson/psutils/blob/master/LICENSE) for everything in the psutils repo now.

**Comment by tech4him1** [comment]
Is there any way to add a shortcut that links to the built-in (scoop) shims, or do I have to use one that I make?

**Comment by tech4him1** [comment]
OK.  Thanks for your help!

**Comment by tech4him1** [comment]
Just for the record, `post_install` didn't work, only `pre_install`.

**Comment by tech4him1** [comment]
Even though this would work, your docs say that an app should be self contained.  If I were ever to submit it to scoop-extras, what would be your preferred method?

**Comment by lukesampson** [comment]
This would be fine to submit to scoop-extras. Probably even the main bucket.

Self-contained is the ideal that we're aiming for, but we're not too pedantic. The main Python install is already outside this self-contained ideal. We can't really be sure what that installer is doing and it would be much better if we could just extract the files and describe the setup in the manifest—but we have to work with what's available.
