### ISSUE TITLE
Using Pathogen with Scoop installed Vim

### ISSUE THREAD

**Issue by brianjking** [lukesampson/scoop#1376]
Hey @lukesampson -- How would I go about using `Pathogen` with `vim` that I installed using `scoop`?

* [Vim Pathogen](https://github.com/tpope/vim-pathogen)

**Comment by Congee** [comment]
Do you wanna install `Pathogen` via `scoop`?

**Comment by brianjking** [comment]
@Congee I installed `vim` via `scoop`, I don't believe `pathogen` is available in any buckets that I'm aware of.

The issue is that wherever `scoop` installs `vim` leaves me confused as to how to go about installing Pathogen.

Here's the `Pathogen` readme:

## Installation

Install to `~/.vim/autoload/pathogen.vim`.  Or copy and paste:

    mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

If you're using Windows, change all occurrences of `~/.vim` to `~\vimfiles`.

**Comment by lukesampson** [comment]
Scoop installs Vim at `~/scoop/apps/vim/current`, but Vim should still use the config files in your user directory (%userprofile% in CMD, or `~` in PowerShell).

How about this?

```powershell
mkdir ~/vimfiles/autoload > $null
mkdir ~/vimfiles/bundle > $null

scoop install curl # can leave out if you already have it
if(test-path alias:\curl) { rm alias:\curl }

curl -Lo "$env:userprofile/vimfiles/autoload/pathogen.vim" https://tpo.pe/pathogen.vim
```

Scoop should have added a default `.vimrc` for you. You can edit it with...

```powershell
notepad "$env:userprofile/.vimrc"
```

... and add the `execute pathogen#infect()` line there.

**Comment by deevus** [comment]
Just FYI if you have a _vimrc file it will pick that up before .vimrc

On my system I'm using ~/.vimrc and ~/.vim/ without issue

**Comment by llinfeng** [comment]
Just want to reiterate what @brianjking has mentioned. On Windows
* `~/.vim` is NOT sourced by Vim_on_Windows
* `~/vimfiles` is sourced, instead.

Thus, all the following setup/configuration files/folders should go under `~/vimfiles`, as:
```
- vimfiles/
  - autoload/
      - plug.vim
  - ftplugin/
```
