### ISSUE TITLE
Add ability to use custom icons for shortcuts.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1378]
This is necessary if the shortcut points to a script instead of a executable.  It should be fairly simple, just adding an `IconLocation` to the `$wsShell` object before you save it.

Example:
```powershell
function startmenu_shortcut($target, $shortcutName, $icon) {
    ...
    $wsShell.TargetPath = "$target"
    $wsShell.IconLocation = "$icon"
    $wsShell.Save()
}
```

**Comment by tech4him1** [comment]
I found a workaround.  You can simply create a link in your project, then, add a shortcut to the shortcut.

```json
...
    "shortcuts": [
        [
            "program.lnk",
            "Program"
        ]
    ]
...
```

**Comment by lukesampson** [comment]
Nice one!

**Comment by gitolicious** [comment]
It is rather cumbersome, but it works...
```
    "shortcuts": [
        [
            "idea.lnk",
            "IntelliJ IDEA Ultimate"
        ]
    ],
    "pre_install": "
        $wsShell = New-Object -ComObject WScript.Shell
        $wsShell = $wsShell.CreateShortcut(\"$dir\\idea.lnk\")
        $wsShell.TargetPath = \"$dir\\bin\\idea.bat\"
        $wsShell.IconLocation  = \"$dir\\bin\\idea.exe\"
        $wsShell.Save()
    ",
```

> Hint: You need to use `pre_install` here because scoop tries to create the start menu shortcut before the `post_install` step runs, which would fail.

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop/commit/83b823868f5ef5256d3dcfbecff278bb355fefc8
