### ISSUE TITLE
Allow different filenames for autoupdate hash generation.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1380]
Some sites store hashes in separate files based on the basename of the file.  If there is a way to do that, that would be great!

```json
...
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "http://download.example.org/x64-$version.zip"
            },
            "32bit": {
                "url": "http://download.example.org/x86-$version.zip"
            }
        },
        "hash": {
            "mode": "extract",
            "type": "sha1",
            "url": "http://download.example.org/$basename.sha1",  <-------- URL http://download.example.org/$basename.sha1 is not valid
            "find": "([a-z0-9]{40})\\s+(?:$basename)"
        }
    }
...
```

**Comment by r15ch13** [comment]
All version variables from autoupdate feature are available. See [App-Manifest-Autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#reference)

**Comment by tech4him1** [comment]
OK, I see that the `$version` and `$url` variables are available, but here is one example that is still causing me problems.  The hash file url should be `http://download.example.org/x64-$version.zip.sha1`, but in this case, scoop just seems to ignore that the hash section exists.
```json
...
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "http://download.example.org/x64-$version.zip"
            },
            "32bit": {
                "url": "http://download.example.org/x86-$version.zip"
            }
        },
        "hash": {
            "mode": "extract",
            "type": "sha1",
            "url": "$url.sha1",
            "find": "([a-z0-9]{40})\\s+(?:$basename)"
        }
    }
...
```

**Comment by r15ch13** [comment]
Did you try removing the files from scoops cache?

**Comment by tech4him1** [comment]
Yes.  Here is what I get when I run checkver:
```powershell
PS C:\Users\username\scoop\buckets\extras> .\bin\checkver.ps1 appname -u
appname: 3.48.22 (scoop version is 3.48.21) autoupdate available
Autoupdating appname
Download files to compute hashes!
x64-3.48.22.zip (4.4 MB) [=====>                                                                   ]   8%
```

**Comment by r15ch13** [comment]
Then it must be your regex. If it can't find the hash it falls back to downloading and hashing the files locally.
See [autoupdate.ps1#L123](https://github.com/lukesampson/scoop/blob/master/lib/autoupdate.ps1#L123)

**Comment by tech4him1** [comment]
OK, that's it.  Thanks for your help.  Would it be worth adding a message in like `Hash not found in file.` or `File not found.`, so you can know what the actual problem is instead of it just saying `Download files to compute hashes!` like it would if there was not hash section at all?

**Comment by r15ch13** [comment]
Added a warning [autoupdate.ps1#L139](https://github.com/lukesampson/scoop/blob/master/lib/autoupdate.ps1#L139)

**Comment by tech4him1** [comment]
Looks great, as it already gives a `404` error if the URL is wrong.

**Comment by tech4him1** [comment]
Actually, I just noticed one thing: if there is no hash section at all, it still gives the warning.  Do you want it that way, or should you do:
```powershell
if($hash) {
        # got one!
        return $hash
    } elseif($hashfile_url) {
        write-host -f DarkYellow "Could not find hash in $hashfile_url"
    }
```

**Comment by r15ch13** [comment]
Oops, you're right, fixed :smile:
