### ISSUE TITLE
7zip errors out when trying to extract symbolic links.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1384]
7-Zip errors when trying to extract symbolic links because in Windows they must be created as admin:
```
...
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\semver
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\mustache
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\nf
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\which
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\sparkline
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\nopt
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\mkdirp
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\esvalidate
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\esparse
ERROR: Can not create symbolic link : Access is denied. : lib\node_modules\.bin\cdl
ERROR: Can not create symbolic link : Access is denied. : lib\npm\node_modules\.bin\which
ERROR: Can not create symbolic link : Access is denied. : lib\npm\node_modules\.bin\semver
ERROR: Can not create symbolic link : Access is denied. : lib\npm\node_modules\.bin\rimraf
ERROR: Can not create symbolic link : Access is denied. : lib\npm\node_modules\.bin\opener
...
```
I don't know if you will have a fix for this, but if you have an idea of a pre_install step to run `sudo` or something, I can work with that.

**Comment by lukesampson** [comment]
I've never seen this before. What's the file that you're extracting?

**Comment by tech4him1** [comment]
I was trying to update the Heroku script, so that the installer was not necessary.  Either of the Windows files in [this manifest](https://cli-assets.heroku.com/branches/stable/manifest.json) (https://cli-assets.heroku.com/branches/stable/manifest.json) should cause the problem because they are built on Ubuntu. NPM on Ubuntu creates sym-links instead of shims like it does on Windows. To my knowledge, 7-zip tries to extract the relative symbolic links with `mklink`, which, as you know, needs admin privileges to run.

**Comment by lukesampson** [comment]
You can append a URL fragment to the URL, which allows you to specify the filename to be downloaded. You can use this to change the filename to *.7z, which will cause 7zip to extract the installer, if it supports the compression format of the .exe, which in this case it does.

This will allow you to bypass the installer.

e.g.

```json
{
   ...
   "architecture": {
        "32bit": {
            "url": "https://cli-assets.heroku.com/branches/stable/heroku-windows-386.exe#/dl.7z"
        },
        "64bit": {
            "url": "https://cli-assets.heroku.com/branches/stable/heroku-windows-amd64.exe#/dl.7z"
        }
    }
    ...
}
```

**Comment by tech4him1** [comment]
That works for this installer, but the problem still stands, and could come up later. I don;t know of a good fix for it though, so you can close the issue if you want.

**Comment by lukesampson** [comment]
Okay thanks. I'll close this for now, but we can come back to it if it comes up again. 

I don't really want to force an elevation to administrator permissions during a Scoop install in order to handle symbolic links, because it's one of the selling points for Scoop that you shouldn't need to do that.

I'm hoping that most people creating distributions for Windows won't use symbolic links, because they don't really work well (yet).
