### ISSUE TITLE
Installing 7zip Hash check failed

### ISSUE THREAD

**Issue by rickysutton27** [lukesampson/scoop#1391]
When installing 7zip Hash check fails. the hashs do not match. 

Installing '7zip' (16.04).
7z1604-x64.msi (2.7 KB) [=============================================] 100%
Checking hash of 7z1604-x64.msi... Hash check failed for 'http://7-zip.org/a/7z1604-x64.msi'.
Expected:
    b3885b2f090f1e9b5cf2b9f802b07fe88e472d70d60732db9f830209ac296067
Actual:
    84f7f8131cbeca3b55cb0e43f3ce253006f716aa18cd360526e8fd5606d0566e

**Comment by rickysutton27** [comment]
hmm, had the issue on a new machine. tried uninstalling, clearing cache and reinstalling on a machine which had previously worked. It didn't work there either. Any other ideas?

**Comment by r15ch13** [comment]
Try downloading it with your browser and check the hash again (e.g. with [HashCheck](https://github.com/gurnec/HashCheck/releases))

**Comment by rrelmy** [comment]
Works for me 😕

**Comment by rickysutton27** [comment]
thanks, looks like it could be an internal networking issue. IT may have updated our firewalls and interfering with our installs.  I'll post the results if confirmed one way or the other.
