### ISSUE TITLE
Apache is not installing

### ISSUE THREAD

**Issue by Pioruniasty** [lukesampson/scoop#1395]
Hi,

Today I decided to atleast install Apache web server with scoop. After instalation i get an error: 

`checking hash...hash check failed for https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.25-win64-VC14.zip. expected: C4625C3ABD688941FC80548B8C8314E1C5278804A019C14BFFC92DC49A087905, actual: e03a43b53f00320de27d9b7046f5e317d06268795592ef32353ce857d7aa4d76!
`

and i installed it using 

`
scoop install apache
`

also i thought that meybe it's because lack of privilages so i ran CMD using admin acc but still i got same error.

**Comment by inosik** [comment]
Did you run `scoop update` before installing? The hashes in the manifest should be correct ATM.

**Comment by rrelmy** [comment]
The apache download was changed without a version change, as inosik commented running `scoop update` will solve the issue.

**Comment by Pioruniasty** [comment]
Yes, It's working now perfectly, thanks (-:
