### ISSUE TITLE
SSL for https://get.scoop.sh/ is invalid

### ISSUE THREAD

**Issue by r15ch13** [lukesampson/scoop#1400]
Your StartCom SSL certificate for https://get.scoop.sh/ is marked as untrusted by Chrome.
NET::ERR_CERT_AUTHORITY_INVALID

**Comment by lukesampson** [comment]
Thanks. I've moved get.scoop.sh to CloudFront with a new certificate. Does it work for you now?

**Comment by rrelmy** [comment]
Looks good 👍 

_Today is issue closing saturday :-)_
