### ISSUE TITLE
request CouchDB

### ISSUE THREAD

**Issue by nueko** [lukesampson/scoop#1405]
Hi, wonder if couchdb is possible to be installed by scoop.
thanks

**Comment by sdaves** [comment]
Looks like persist landed. Do you feel couchdb would be a good fit now? If so, I'd happily send a PR.

**Comment by r15ch13** [comment]
@sdaves Yes, you can add it to the [extras](https://github.com/lukesampson/scoop-extras) bucket if you like 😄
