### ISSUE TITLE
recreate shortcuts

### ISSUE THREAD

**Issue by AStupidBear** [lukesampson/scoop#1406]
I know that ```scoop uninstall ** && scoop install **``` will recreate shortcuts, but I don't want to do this because I have personal settings installed in the corresponding folder. Is there a command to achieve this while preserving preexisting folders?

**Comment by lukesampson** [comment]
We are working on a way to preserve settings with #1372. For now, it might be best to do `scoop update [app]` for the apps that you want to preserve settings for, that way you can copy the old settings from the old version which you can find under `~/scoop/apps/[app]`.

**Comment by AStupidBear** [comment]
thanks

**Comment by AStupidBear** [comment]
```scoop reset **``` can recreate shims, but not shortcuts. Maybe adding a line like [this](https://github.com/lukesampson/scoop/blob/d2a8f6798f2a9dd3cf3cc8605fdbe3cb2371db63/libexec/scoop-reset.ps1#L31) can solve the problem( I am not familar with powershell)?
