### ISSUE TITLE
PHP doesn't keep session

### ISSUE THREAD

**Issue by Pioruniasty** [lukesampson/scoop#1412]
Hi,

I want to ask what I am doing wrong? I am using PHP installed from scoop and I'm using Laravel framework 5.4. On Ubuntu server I can easly set session variables, authenticate etc. but when I'm developing localy using PHP installed via Scoop it doesn't keep session or sometimes after few requests I get "TokenMismatchException" which means that session has changed.

**Comment by nueko** [comment]
I am Laravel user too, but i just think that's weird.
about `TokenMismatchException`, are you using [passport](https://github.com/laravel/passport)?

**Comment by rrelmy** [comment]
I do local development with a laravel based CMS and never had any session problems.

**Comment by Pioruniasty** [comment]
Hmm .. meybe I will try to reinstall PHP and whole SCOOP. Meybe I did something weird with installation.
