### ISSUE TITLE
dig missing MSVCR110.dll

### ISSUE THREAD

**Issue by e2xistz** [lukesampson/scoop#1416]
On a fresh Windows install, dig won't start scoop install.

Pop up dialog says missing MSVCR110.dll.

**Comment by r15ch13** [comment]
You can now install Microsoft Visual C++ Redistributable Packages via Scoop (https://github.com/lukesampson/scoop-extras/commit/42c230cbf6b9e3314d9d3e9e1771b408dfabf190).
Run `scoop update` and install `scoop install vcredit2012` or `scoop install vcredist` to install all versions from 2008 until 2017
