### ISSUE TITLE
env_add_path seems to be broken

### ISSUE THREAD

**Issue by sakai135** [lukesampson/scoop#1417]
`scoop install python` ended up adding `C:\Users\user\scoop\apps\python\current\C:\Users\user\scoop\apps\scoop\current\bin\scoop.ps1` as one of the entries to the system `PATH` environment variable.

From the manifest and glancing at the code, I'm guessing that it was supposed to add `C:\Users\user\scoop\apps\python\current\scripts` instead.

**Comment by rrelmy** [comment]
Thanks for the report.

The issue has been fixed, please run `scoop update`, uninstall python and install it again.
Unfortunately you have to remove the broken path from `$PATH` manually as it does not get picked up while uninstalling the app.

Sorry for the inconvenience
