### ISSUE TITLE
Error 1320 when extracting package into ~/scoop/apps/

### ISSUE THREAD

**Issue by basedjux** [lukesampson/scoop#1428]
I'm trying to install the nodejs-lts package on Windows 10 x64 v1703 and during the extract phase I get:

```
Extracting... Exit code was 1603.
Failed to extract files from C:\Users\Peak Payment\scoop\apps\nodejs-lts\6.10.2\node-v6.10.2-x64.msi.
Log file:
    ~\scoop\apps\nodejs-lts\6.10.2\msi.log
```

Upon inspection of this log file I find:
```
=== Logging started: 4/11/2017  10:24:48 ===
Error 1320. The specified path is too long: 
C:\Users\Peak Payment\scoop\apps\nodejs-lts\6.10.2\_scoop_extract\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 4/11/2017  10:25:06 ===

```

I did some research on error 1320 and found out that the max path length for MSI installation is 150 characters.  So my question, is there a way to install this package elsewhere so the path is <= 150? Or does scoop install to it's ~/scoop/apps/ directory with no way to change it?

**Comment by r15ch13** [comment]
You can use the environment variable SCOOP to change the default installation path of scoop.
But i recommend reinstalling it, instead of moving it manually.

**Comment by basedjux** [comment]
@r15c13 Awesome! Thanks a bunch! I'll uninstall then reinstall and change the environment path. I'll close this issue.

**Comment by r15ch13** [comment]
Add the environment variable before reinstalling :smile:

**Comment by whench18** [comment]
@basedjux  for any path too long problems, I suggest you should try using the long path tool. this will help you solve all kinds of long path issues. This tool is tried and tested by many people and proven to be good. thanks.
