### ISSUE TITLE
Failed to install diffutils 2.8.7 with a error "Extracting... Exit code was 2."

### ISSUE THREAD

**Issue by ironsand** [lukesampson/scoop#1429]
When I try to install `diffutils` I get this error.

```
$ scoop install diffutils
Installing 'diffutils' (2.8.7).
Loading diffutils-2.8.7.20071206cvs-3-msys-1.0.13-bin.tar.lzma from cache
Loading msysCORE-1.0.18-1-msys-1.0.18-bin.tar.lzma from cache
Loading libintl-0.18.1.1-1-msys-1.0.17-dll-8.tar.lzma from cache
Loading libiconv-1.14-1-msys-1.0.17-dll-2.tar.lzma from cache
Checking hash of diffutils-2.8.7.20071206cvs-3-msys-1.0.13-bin.tar.lzma... ok.
Extracting... Exit code was 2.
```

I run `scoop update` before installing. How can I fix this error?

Thanks.

**Comment by lukesampson** [comment]
It seems to be a problem while 7-zip is extracting the first file. It works fine for me and the hash is right, so it might be something related to your particular setup.

Maybe you could try extracting the file manually with 7-zip. You should be able to find the problem file with `ls ~/scoop/cache/diffutils#2.8.7#*diffutils*`.

You can test extraction with something like:

```powershell
cd ~/scoop/cache
7z x "diffutils#2.8.7#https_sourceforge.net_projects_mingw_files_MSYS_Base_diffutils_diffutils-2.8.7.20071206cvs-3_diffutils-2.8.7.20071206cvs-3-msys-1.0.13-bin.tar.lzma" -o"test"
```

**Comment by ironsand** [comment]
Thanks! there was another `7z` in my environment. After removing it, I could install `diffutils`.
