### ISSUE TITLE
Can't install PHP

### ISSUE THREAD

**Issue by Pioruniasty** [lukesampson/scoop#1430]
After 
```
scoop install php
```
I'm getting 404 (not found)

```
URL http://windows.php.net/downloads/releases/php-7.1.3-Win32-VC14-x64.zip is not valid
```

btw. I'm using Windows 10 Creators Update

**Comment by lukesampson** [comment]
The current PHP version is 7.1.4. You need to run `scoop update` to get the latest manifests then try again.
