### ISSUE TITLE
Docs: Autoupdate `hash` value can be extracted using JSON.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1431]
Right now the `hash` value in an `autoupdate` section can extract a hash via `regex`,  `rdf`, or manually set via download.  It would be nice if we could use JSON as well, maybe like this:
```
...
    "autoupdate": {
        ...
        "hash": {
            "mode": "json",
            "url": "https://example.org/download/manifest.json",
            "json": "builds.$basename.hash"
        }
    }
...
```

https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#hashing-hash

**Comment by tech4him1** [comment]
OK, I see it already is supported (example at [bucket/openssl.json#L31](https://github.com/lukesampson/scoop/blob/5c34ef96d14bc11d83e1d7a1c65f7a3778b46895/bucket/openssl.json#L31)).  If you don't mind, I'll just leave this open until I get a chance to send a PR for the docs, unless you want to.

**Comment by tech4him1** [comment]
Closed by [wiki #750e45](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate/750e455f2934c46dd8e900982c31fb64b42849f6).

**Comment by r15ch13** [comment]
Thanks for adding it to the wiki. Totally forgot to do that 😊

**Comment by tech4him1** [comment]
@r15ch13 You might add some better docs on how to write a `checkver` section as well.

**Comment by r15ch13** [comment]
@tech4him1 I updated the [wiki #fa4e0cd](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate/fa4e0cd286e45dbed6233d70d72249b20475bb68) with information about checkver and improved the hashing part.

**Comment by tech4him1** [comment]
Looks awesome!

**Comment by tech4him1** [comment]
Did a quick typo fix as well [wiki #da63da](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate/da63da283c133d783c3d0d0f42906796156e0acf).

**Comment by r15ch13** [comment]
GG! Thanks xD
