### ISSUE TITLE
Allow architecture specific `hash` extractions.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1433]
Maybe I missed this and it already exists, but it would be nice if you could do architecture specific `hash` extraction patterns.

**Comment by r15ch13** [comment]
This idea crossed my mind while working in #1432 but I think there is no need for that.
Most of the time the variables `$url` (which is either the 32bit or 64bit URL) and `$basename` are enough.
If you indeed found an edge case, I would like to know about it. :smile:

**Comment by tech4him1** [comment]
Here is the hash file I have available:
```json
{
  ...
  "builds": {
    ...
    "windows-386": {
      "url": "example-windows-386.tar.xz",
      "sha256": "a2911959e9b67e50bf5cae6e58f1d62dc3a5245a6e345b4075541d188a95ef33",
      "bytes": 12709680
    },
    "windows-amd64": {
      "url": "example-windows-amd64.tar.xz",
      "sha256": "d8d4d51a4a241eefa4eca327dd542ae622b53fa3f7c1f17f6567d2d968634d83",
      "bytes": 14046292
    }
  }
}
```

**Comment by r15ch13** [comment]
Actually, this is already supported. :smile:
@se35710 pushed a bunch of eclipse tools with hash extraction for each architecture two days ago https://github.com/lukesampson/scoop-extras/pull/379

**Comment by tech4him1** [comment]
Great!  Was a note added to the docs yet?

**Comment by r15ch13** [comment]
Yep added with [#cef08b3](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate/cef08b3a996c1163f46a534c60339541346165b0)
