### ISSUE TITLE
[Q] Offers scoop autocomplete?

### ISSUE THREAD

**Issue by szachara** [lukesampson/scoop#1439]
Offers scoop tab autocomplete for commands?

**Comment by szachara** [comment]
I'm asking, because I remember, that it worked and it doesn't work for me now, but I can mistake.

**Comment by lukesampson** [comment]
Scoop doesn't do tab autocomplete. The [pshazz](https://github.com/lukesampson/pshazz) plugin includes tab autocomplete for Git and Mercurial — is that what you were thinking of?

**Comment by szachara** [comment]
Thx for replay, no i didn't find pshazz, I don't know how to express it in english, but i thought that scoop have autocomplete, but as you wrote it don't. 
I mistake / confuse (  i can't find right word ) with some other sw :)

**Comment by Lockszmith** [comment]
With @liuzijing97 's excellent [scoop-autocomplete](https://github.com/liuzijing97/scoop-completion) solution (which now includes a scoop bucket), would it make sense to add a reference to it in the wiki?

**Comment by silverqx** [comment]
Hmm, the source code looks good after fast look up , I try it later

**Comment by BinToss** [comment]
Moeologist/sccop-completion currently overwrites Powershell's TabExpansion instead of using `Register-ArgumentCompleter`
```
Install-Package: The following commands are already available on this system:'TabExpansion'. This module 'scoop-completion' may override
the existing commands. If you still want to install this module 'scoop-completion', use -AllowClobber parameter.
```
See https://github.com/Moeologist/scoop-completion/issues/22

**Comment by phanirithvij** [comment]
I was using [cmder](https://cmder.net/) which uses [clink](https://github.com/chrisant996/clink) and [clink-completions](https://github.com/vladimir-kotikov/clink-completions).
It provides very thorough completions.
