### ISSUE TITLE
install 7zip failed to extract files

### ISSUE THREAD

**Issue by wfwiggins203** [lukesampson/scoop#1445]
I've searched and found the same issue addressed before, but tried the suggested fixes and am still getting this error.

`PS C:\> sudo scoop install 7zip -a 64bit --global
Installing '7zip' (16.04).
7z1604-x64.msi (1.6 MB) [=========================] 100%
Checking hash of 7z1604-x64.msi... ok.
Extracting... Exit code was .
Failed to extract files from C:\programdata\scoop\apps\7zip\16.04\7z1604-x64.msi.
Log file:
  C:\programdata\scoop\apps\7zip\16.04\msi.log`

No exit code. Nothing in log file. Tried other tricks from previous issues (uninstall, cache rm, install) to no avail. Navigated to folder in Windows Explorer and repaired install manually, but scoop doesn't recognize successfully installed version ('7zip' install failed previously. Please uninstall and try again).

Any thoughts?

**Comment by lukesampson** [comment]
Anti virus maybe?

**Comment by wfwiggins203** [comment]
Didn't work when I turned off MS Security Essentials real-time protection.

**Comment by lukesampson** [comment]
Does `scoop install 7zip` work?

Could it be that you're trying to install a 64-bit version on a 32-bit OS? I ask because Security Essentials sounds old.

If you're not getting anywhere, you could try running `Set-PsDebug -Trace 2` and then running again to see if there is a hidden error happening. (Run `Set-PsDebug -Off` to remove Powershell tracing.)

**Comment by rasa** [comment]
This issue appears to have been resolved. If not, please reopen this ticket, or let us know. Thanks!

**Comment by domadogma** [comment]
Running 'scoop install 7zip' in PS (admin and non-admin) on win10x64

Console output:
```
Installing '7zip' (18.01) [64bit]
Loading 7z1801-x64.msi from cache
Checking hash of 7z1801-x64.msi... ok.
Extracting... Exit code was 1603.
Failed to extract files from C:\Users\tbko\scoop\apps\7zip\18.01\7z1801-x64.msi.
Log file:
  ~\scoop\apps\7zip\18.01\msi.log
```

Excerpt from Debug output with 'Set-PsDebug -Trace 2' applied:
```
DEBUG:  500+          >>>> $proc = start-process $exe -wait -ea stop -passthru @parameters
DEBUG:  511+          >>>> write-host -f darkred $_.exception.tostring()
System.Management.Automation.RuntimeException: Cannot convert value to type System.String. ---> System.Management.Automation.PSInvalidCastException: Cannot convert value to type System.String. ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at System.Diagnostics.Process.ToString()
   at System.Management.Automation.PSObject.ToString(ExecutionContext context, Object obj, String separator, String format, IFormatProvider formatProvider, Boolean recurse, Boolean unravelEnumeratorOnRecurse)
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.ToStringParser(ExecutionContext context, Object obj)
   at System.Management.Automation.ScriptDebugger.TraceVariableSet(String varName, Object value)
   at System.Management.Automation.VariableOps.SetVariableValue(VariablePath variablePath, Object value, ExecutionContext executionContext, AttributeBaseAst[] attributeAsts)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
DEBUG:  512+         return  >>>> $false
DEBUG:  516+  >>>> }
DEBUG:     ! SET $ok = 'False'.
```

Log file is empty,  _tmp directory is empty

**Comment by beppegg** [comment]
I get the same issue with the same stacktrace; please reopen!

**Comment by giuscri** [comment]
in my case, a reboot solved the problem

**Comment by longletian** [comment]
we  same  as   you 
PS C:\WINDOWS\system32> scoop  install   firefox-beta
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing '7zip' (19.00) [64bit]
Starting download with aria2 ...
Download: [#847797 0B/0B CN:1 DL:0B]
Download: [#847797 160KiB/1.6MiB(9%) CN:1 DL:149KiB ETA:10s]
Download: [#847797 752KiB/1.6MiB(44%) CN:1 DL:326KiB ETA:2s]
Download: [#847797 1.2MiB/1.6MiB(72%) CN:1 DL:353KiB ETA:1s]
Download: [#847797 1.5MiB/1.6MiB(91%) CN:1 DL:336KiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 847797|OK  |   344KiB/s|C:/Users/admin/scoop/cache/7zip#19.00#https_7-zip.org_a_7z1900-x64.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... System.InvalidOperationException: 无法完全运行此命令，因为系统找不到所需的全部信息。
   在 System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Failed to extract files from C:\Users\admin\scoop\apps\7zip\19.00\7z1900-x64.msi.
Log file:
  ~\scoop\apps\7zip\19.00\msi.log
