### ISSUE TITLE
[Q] ls command

### ISSUE THREAD

**Issue by silverqx** [lukesampson/scoop#1450]
Is in repo `ls` command, I didn't find it, thx

**Comment by lukesampson** [comment]
`gow`, `busybox`, and  `coreutils` each provide an `ls` command. `scoop search ^ls$` is how to find that.

**Comment by szachara** [comment]
ok, thx

**Comment by szachara** [comment]
I reopened, because I want to ask just one thing, I looked at gow and coreutils and they offer too much commands, would be possible to add only `ls` to scoop repo?

**Comment by atifaziz** [comment]
[msls](https://u-tools.com/msls) would be a nice addition.

**Comment by szachara** [comment]
Looks nice at first look, but strange thing about this is, that it doesn't have any github repo, but it's under gnu licence.

**Comment by atifaziz** [comment]
@szachara True but since when is being on GitHub a measure of utility? And as you noted, [source code is available](http://download.algintech.com/msls315_src.zip) under the [GNU license](https://u-tools.com/download_agree.asp?download_id=650). That means it can be redistributed and mirrored on GitHub under the same license, including [the executable](http://download.algintech.com/msls315_src.zip), and a scoop bucket can be made to point to the mirror.

**Comment by lukesampson** [comment]
You're welcome to submit a pull request for a standalone `ls`, like msls.

**Comment by Congee** [comment]
Hi, I made a manifest for msls. Would not like to make a pull request cuz i don't know how to using git to remove many extra commits.
``` json
{
    "version": "4.7.315",
    "license": "GPL2",
    "url": "http://download.algintech.com/msls315.exe#/msls4.7.315.zip",
    "homepage": "https://u-tools.com/msls",
    "hash": "d09c9a77d767f9284eb8d62febade7011f9c27b404953c9fcb5a1f9a75858dca",
    "bin": "ls.exe",
    "checkver": {
        "url": "https://u-tools.com/download_prod.asp?download%5Fid=600&Agree=1",
        "re": "Version: (?<major>\d.\d.)(?<minor>\d+)"
    },
    "autoupdate": {
        "url": "http://download.algintech.com/msls$minor.exe#/msls4.7.315.zip"
    }
}
```
Having difficulty with with regex of checkver the version string in the url is minor version. So, how to extract minor version number using regex?

**Comment by r15ch13** [comment]
See https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate
Regex should look like this `Version: ([\d.]+)`

**Comment by mykolapolonskyi** [comment]
hello 

> ls -l 
`returns this
 Get-ChildItem : Missing an argument for parameter 'LiteralPath'. Specify a parameter of type 'System.String[]' and try again.
At line:1 char:4
+ ls -l
+    ~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.PowerShell.Commands.GetChildItemCommand
`
ls and ll works fine!

p.s. try this scoop today first time - AWESOME!!!

**Comment by r15ch13** [comment]
@mykolapolonskyi That is not an issue with scoop. `ls` is an alias for `Get-ChildItem` and `-l` is short for [`-LiteralPath`](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.management/get-childitem#-literalpath)

**Comment by rasa** [comment]
This issue appears to have been resolved. If not, please reopen this ticket, or let us know. Thanks!
