### ISSUE TITLE
Scoop update doesn't work behind proxy

### ISSUE THREAD

**Issue by rainyday** [lukesampson/scoop#1454]
Running `scoop update` to update scoop its self fails with `fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to github.com port 443: Timed out`. Updating packages _installed_ with scoop works fine however.

**Comment by lukesampson** [comment]
You probably need to [configure Scoop to use your proxy](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy).

**Comment by rainyday** [comment]
Thanks, that did solve my issue, but considering I already had settings configured in Windows and every other install/update command worked fine off of those settings I think this might still be a bug?

**Comment by lukesampson** [comment]
Ah okay, yes it looks like Scoop might have been forcing Git not to use the proxy that was already configured in Windows. Git is used for `scoop update` but not for updating or installing packages.

Can you please try running `scoop config rm proxy` and then running `scoop update` to see if the problem is fixed?

**Comment by rainyday** [comment]
Tried it and it seems to be working as expected now. Thanks.

**Comment by lukesampson** [comment]
Great! Thanks for reporting this.

**Comment by bkoprivica** [comment]
scoop config

lastUpdate            SCOOP_REPO                              SCOOP_BRANCH proxy
----------            ----------                              ------------ -----
06/08/2022 7:18:39 PM https://github.com/ScoopInstaller/Scoop master       none

scoop config rm proxy
'proxy' has been removed

C:\windows\system32>scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/ScoopInstaller/Scoop/': Failed to connect to xxx.xxx.xxx.xxx port 3128 after 2132 ms: Connection refused
Scoop update failed.

**Comment by rashil2000** [comment]
Are you able to connect to the website normally?
