### ISSUE TITLE
Error when installing php

### ISSUE THREAD

**Issue by szachara** [lukesampson/scoop#1456]
I tried to install php and php-nts and i got this output:

```
PS C:\apache24_php71\bin> scoop install php
Installing 'php' (7.1.4).
php-7.1.4-Win32-VC14-x64.zip (23,4 MB) [=================================================================================================================================================] 100%
Checking hash of php-7.1.4-Win32-VC14-x64.zip... ok.
Extracting... done.
Linking ~\scoop\apps\php\current => ~\scoop\apps\php\7.1.4
Creating shim for 'php'.
Creating shim for 'php-cgi'.
Persisting cli
The syntax of the command is incorrect.
File not found - C:\Users\Silver Zachara\scoop\apps\php\current\cli
Persisting php.ini-production
The syntax of the command is incorrect.
Running post-install script...
gc : Cannot find path 'C:\Users\Silver Zachara\scoop\apps\php\current\cli\php.ini' because it does not exist.
At line:14 char:2
+ (gc "$dir\cli\php.ini") | % { $_ -replace '; extension_dir = "ext"',  ...
+  ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Silver...ent\cli\php.ini:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

'php' (7.1.4) was installed successfully!
'php' suggests installing 'extras/vcredist2017'.
PS C:\apache24_php71\bin> scoop uninstall php
Uninstalling 'php' (7.1.4).
Removing shim for 'php'.
Removing shim for 'php-cgi'.
Unlinking ~\scoop\apps\php\current
'php' was uninstalled.
PS C:\apache24_php71\bin> scoop install php-nts
Installing 'php-nts' (7.1.4).
php-7.1.4-nts-Win32-VC14-x64.zip (23,3 MB) [=============================================================================================================================================] 100%
Checking hash of php-7.1.4-nts-Win32-VC14-x64.zip... ok.
Extracting... done.
Linking ~\scoop\apps\php-nts\current => ~\scoop\apps\php-nts\7.1.4
Creating shim for 'php'.
Creating shim for 'php-cgi'.
Persisting cli
The syntax of the command is incorrect.
File not found - C:\Users\Silver Zachara\scoop\apps\php-nts\current\cli
Persisting php.ini-production
The syntax of the command is incorrect.
Running post-install script...
gc : Cannot find path 'C:\Users\Silver Zachara\scoop\apps\php-nts\current\cli\php.ini' because it does not exist.
At line:14 char:2
+ (gc "$dir\cli\php.ini") | % { $_ -replace '; extension_dir = "ext"',  ...
+  ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Silver...ent\cli\php.ini:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

'php-nts' (7.1.4) was installed successfully!
'php-nts' suggests installing 'extras/vcredist2017'.
```

**Comment by r15ch13** [comment]
Did you run `scoop update` before?
Something went wrong while creating a link from `C:\Users\Silver Zachara\scoop\apps\php\current\cli` to the persistent directory.

**Comment by szachara** [comment]
I tried scoop update, the same problem.

**Comment by lukesampson** [comment]
Are you running Windows XP? I'm guessing it's failing at [this line](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L1019), because `/l` for the [attrib](https://technet.microsoft.com/en-us/library/cc754186(v=ws.11).aspx) command is only supported in Windows Vista and up.

**Comment by szachara** [comment]
Nooo, I'm on latest win10 :-), which line in php-nts.json cause this problem?

**Comment by r15ch13** [comment]
Line 19. It creates a link to the persistent php config. Line 42 fails because line 19 failed.

**Comment by szachara** [comment]
I debugged `lib\install.ps1` and discovered a bug, it's on line https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L1017, because first param in https://github.com/lukesampson/scoop/blob/master/bucket/php-nts.json#L20 is `cli`.

But `cli` dir doesn't exist in `php-nts` package.

So the patch looks like this:
```
            # create link
            if (is_directory $target) {
                if (test-path $source) {
                    cmd /c "mklink /j $source $target" | out-null
                    attrib $source +R /L
                }
            } else {
                cmd /c "mklink /h $source $target" | out-null
            }
```

Can I create PR?

**Comment by szachara** [comment]
The same may happen, when symbolic link for a file will be created, so the patch would be:
```
            # create link
        if (test-path $source) {
            if (is_directory $target) {
                cmd /c "mklink /j $source $target" | out-null
                attrib $source +R /L
            } else {
                cmd /c "mklink /h $source $target" | out-null
            }
        }
```

**Comment by r15ch13** [comment]
The `cli` is intentional. It should create a persistent directory and link it into the PHP directory, so `PHP_INI_SCAN_DIR` can be pointed to it.
What interests me it why it does work on my machine and my scoop testing VM?

Persist directory should look like this:
```
D:\scoop\persist
λ tree
Folder PATH listing for volume Programme
Volume serial number is C0000100 66F0:03E5
D:.
├───php
│   └───cli
│       ├───conf.d
│       └───ext
└───php-nts
    └───cli
        └───conf.d
```
PHP install directory should look like this:
![image](https://cloud.githubusercontent.com/assets/432127/25669429/ccd1ccac-3029-11e7-9fc0-66cea2a689ea.png)

**Comment by szachara** [comment]
And do you know how it should look like? Is the folder structure you pasted above right? I can debug it again, because I think now, that the fix proposed by me is nonsense :]

**Comment by r15ch13** [comment]
Yes after installing PHP it should look like the both examples above.

**Comment by szachara** [comment]
So I catched it, the problem is, that I have space in my profile name, so the fix should look like this:

```
            if (is_directory $target) {
                cmd /c "mklink /j `"$source`" `"$target`"" | out-null
                attrib "$source" +R /L
            } else {
                cmd /c "mklink /h `"$source`" `"$target`"" | out-null
            }
```

**Comment by r15ch13** [comment]
Those pesky whitespaces 😄 
Mind creating a PR?

**Comment by szachara** [comment]
And what about `scoop\persist\php\cli\ext\` dir, you have some ext dir in yours output, my tree looks like:
```
PS C:\Users\Silver Zachara\scoop\persist> tree.com /f
Folder PATH listing for volume windows
Volume serial number is 000000EC C158:7B00
C:.
├───php
│   └───cli
│       │   php.ini
│       │
│       └───conf.d
└───php-nts
    └───cli
        │   php.ini
        │
        └───conf.d
```

**Comment by r15ch13** [comment]
`conf.d` and `ext` are created manually, but maybe we should create with scoop and document them somewhere (`notes` maybe)

**Comment by szachara** [comment]
Yea, I see, that `conf.d` is created in `post_install`, but I don't see any code, which should create the `ext` folder.

I created PR #1458

**Comment by r15ch13** [comment]
`ext` is a leftover from my local testing. :smile: It's not needed at all.
INI files added to `conf.d` will be loaded through the `"PHP_INI_SCAN_DIR": "$dir\\cli;$dir\\cli\\conf.d;"` part.

**Comment by szachara** [comment]
ok, I thought, that it is from you testing ;), so we got it, done :)
