### ISSUE TITLE
KeePass - Hash check failed

### ISSUE THREAD

**Issue by ArminVieweg** [lukesampson/scoop#1457]
Hi,
I've added the extras bucket and tried to install keepass, but I get the following error message:

```
C:\Users\Me>scoop install keepass
Installing 'keepass' (2.35).
KeePass-2.35.zip (68,9 KB) [==================================================================================] 100%
Checking hash of KeePass-2.35.zip... Hash check failed for 'http://downloads.sourceforge.net/project/keepass/KeePass%202.x/2.35/KeePass-2.35.zip'.
Expected:
    5CE675E9B3949A9C0D269233D52602C563C4FD6A4D047DB517AA06BF326CE133
Actual:
    2e12a62ff071b5b2aea56217009615307ae81a00e3a0fdb04d7b9c884f65bf4c
```
I also tried to uninstall, scoop update and install again... but it still does not work.

**Comment by r15ch13** [comment]
5CE675E9B3 is correct. Did you try downloading the file with a browser and check it manually?

**Comment by ArminVieweg** [comment]
When I download the file manually, and check the hashes I get completely different output. Tried md5 and sha1. Which hash algorithm are you using?

I get these values:
- MD5: 15e642262cef0ee583ff40a9e8f49a6f
- SHA1: 914b5e895adb35897d6217fa870af9141eefee61

I've used PHP to fetch the hashes from file contents.

**Comment by r15ch13** [comment]
In this case its sha256
```
    File: KeePass-2.35.zip
  CRC-32: 845314da
   SHA-1: 914b5e895adb35897d6217fa870af9141eefee61
 SHA-256: 5ce675e9b3949a9c0d269233d52602c563c4fd6a4d047db517aa06bf326ce133
 SHA-512: 877825e7cd581140ac555f20044ae7f18471c20caedb439e248559b3af600fda841e811b0841fc94e1fbaf69d02854b1beaa845aa9f38ea412a24cd94d173d42
```

**Comment by ArminVieweg** [comment]
Okay. I get the same value when I use SHA-256. The manually downloaded file fits the given hashes. But apparently the automatically downloaded file, not.

I still get the error message but now with a different hash:

```
Expected:
    5CE675E9B3949A9C0D269233D52602C563C4FD6A4D047DB517AA06BF326CE133
Actual:
    7f7e7afd1a035ac85bdfa0fc31271ab8122419278c83a929badbe47f401bca18
```
Very weird o.O

**Comment by r15ch13** [comment]
Indeed, that's weird. Can upload this file here? I want to know what's inside.

**Comment by ArminVieweg** [comment]
Each download results in a different hash o.O
![2017-05-02_1412](https://cloud.githubusercontent.com/assets/1275298/25617226/88100914-2f41-11e7-82e6-5bcc7c434ba0.png)

**Comment by r15ch13** [comment]
Try to open the zip file an editor. I bet there is HTML in it. 😕

**Comment by r15ch13** [comment]
I changed the URL to the https link with https://github.com/lukesampson/scoop-extras/commit/20fd3d8996633cde31d0f49da5db5c774052f659
Maybe this fixes the problem.

**Comment by ArminVieweg** [comment]
I don't know where scoop caches the downloaded files... So I can't tell you what the files contained. But after an update it works :)

Thanks!

**Comment by r15ch13** [comment]
Cache directory `%userprofile%\scoop\cache`, just for the record. :smile:

**Comment by ArminVieweg** [comment]
I've found the cache directory. But no keepass zip file in it. Does the file get remove, when the hash is not valid?

**Comment by r15ch13** [comment]
Yes ... 😅
