### ISSUE TITLE
Documentation: What are the criteria for the main bucket?

### ISSUE THREAD

**Issue by stakx** [lukesampson/scoop#1459]
The [Wiki page about buckets](https://github.com/lukesampson/scoop/wiki/Buckets) states (with emphasis added by me) that:

> Scoop has a main bucket which is bundled with Scoop and this is always available as the primary source for installing apps. […]
>
> There's an optional extras bucket containing apps **that don't quite fit the criteria of the main bucket**, but are still good to have.

I am looking at submitting some PRs for additional package definitions<sup>(&dagger;)</sup>, but am unsure whether adding them to the main bucket is appropriate, or if my additions wouldn't "fit the criteria".

Therefore I would like to suggest that this Wiki page section is amended with a short list of some of the most important criteria necessary for a package to make it into the main bucket.

----

<sup>(&dagger;)</sup> My specific additions would be package definition files for the .NET decompilation tool ILSpy, and for FAKE (F# MAKE tool).

**Comment by lukesampson** [comment]
Thanks for the suggestion. I've added the main bucket criteria to the wiki [here](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) and also linked it from the [Buckets](https://github.com/lukesampson/scoop/wiki/Buckets) page.

ILSpy and FAKE sound like good candidates for the main bucket, assuming they don't require complicated pre/post install scripts. ILSpy is already in extras (see [here](https://github.com/lukesampson/scoop-extras/blob/master/ilspy.json)), but it would be fine to move to the main bucket. The main bucket used to have stricter requirements, so you'll find some apps in extras that would be fine in main.

**Comment by stakx** [comment]
Awesome, cheers for clarifying it. I'll close this issue then.

Regarding ILSpy, the one in extras is actually more complete than what I was going to submit. But I might do some more work on FAKE and then submit it.

Thanks for your quick response!
