### ISSUE TITLE
Why is there no google-chrome?

### ISSUE THREAD

**Issue by rbnlffl** [lukesampson/scoop#1469]
Is there a reason you can install Firefox via Scoop but not Chrome? If not, I think it'd be pretty cool to have all the major 3rd party browsers (Chrome, Firefox, Opera) or just Chrome installable. This would be sweet for us web developers used to unix.

![screencap](https://cloud.githubusercontent.com/assets/6851646/25942429/1cef30e4-363d-11e7-8a6c-b5ec49caf2ec.png)

Edit: Whoops, I just found the repo for the extras bucket. Closing it here.

**Comment by lukesampson** [comment]
Glad you found it. We'd also accept pull requests for Chrome proper or Opera if you have time to put a [manifest](https://github.com/lukesampson/scoop/wiki/App-Manifests) together. Agree that would pretty sweet for web devs.
