### ISSUE TITLE
Update Lynx to 2.8.8

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1471]
The Lynx browser manifest needs updated to 2.8.8 (from 2.8.3).

**Comment by tech4him1** [comment]
I can work on this too, if you would rather have a PR.

**Comment by lukesampson** [comment]
Yes please, a PR would be great.

**Comment by gliptak** [comment]
Lynx Win32 Installers ftp://invisible-island.net/lynx/

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop/pull/2004
