### ISSUE TITLE
Scoop version of Lynx browser dosen't support HTTPS.

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1472]
Whenever a HTTPS URL is accessed, the request is aborted and `Alert!: This client does not contain support for HTTPS URLs.` is displayed. Lynx can be compiled with `openssl` and `cacerts` support, but it apparently does not recognize the Scoop versions.

Related Lynx Documentation:
http://homes.chass.utoronto.ca/~purslow/lhfb.html#FS
http://lynx.browser.org/lynx_doc/docs/README.ssl
http://lynx.browser.org/lynx_doc/docs/README.sslcerts

**Comment by lukesampson** [comment]
Are you reporting a Lynx bug to Scoop?? 😄  If you're providing supporting evidence for #1471 and we need to update the version — message received, and feel free to close this issue. Any chance of a pull request?

**Comment by tech4him1** [comment]
I'm sorry for the lack of documentation, I was too rushed. I updated the original issue comment with some documentation links and I will look into it as well.

**Comment by tech4him1** [comment]
I think the best way to do this would depend on #1473.

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop/pull/2004
