### ISSUE TITLE
xdebug app

### ISSUE THREAD

**Issue by rubenvincenten** [lukesampson/scoop#1474]
XDebug is a debugging tool for PHP. 

The correct version can be downloaded with this tool: https://xdebug.org/wizard.php

Can anyone write an app manifest for it?

**Comment by r15ch13** [comment]
Working on it

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop-extras/commit/72df84e5b3e8723f825ac0dc7df97771acf688ea and https://github.com/scoopinstaller/versions/commit/782c68e17b6692166111510e62acb53b11ef3de8

**Comment by rrelmy** [comment]
@r15ch13 nice solution. I will try to take the same approach for `php-imagick`.

**Comment by rubenvincenten** [comment]
This is pretty cool! Awesome 🥇
