### ISSUE TITLE
Cannot install 7zip

### ISSUE THREAD

**Issue by morrelinko** [lukesampson/scoop#1476]
On a new scoop installation, trying to run $ scoop install 7zip 
i always get this error 

```
The underlying connection was closed: The connection was closed unexpectedly.
URL http://7-zip.org/a/7z1604-x64.msi is not valid
```

**Comment by r15ch13** [comment]
Are you behind a proxy? See: [Using Scoop behind a proxy](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy)
Is the download working in a browser or is an anti-virus blocking the connection?

**Comment by morrelinko** [comment]
You are right! Removed antivirus and worked perfectly... 
Closing this
Sorry for late reply...
