### ISSUE TITLE
mariadb doesn't have a post_install script like mysql

### ISSUE THREAD

**Issue by Langmans** [lukesampson/scoop#1492]
Like the title says.

Also see https://github.com/lukesampson/scoop/issues/1491

EDIT: There is no default ini file, but you could add a menu so the user can choose what configuration template to use: https://technet.microsoft.com/en-us/library/ff730939.aspx

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F1492
