### ISSUE TITLE
scoop update on my bucket

### ISSUE THREAD

**Issue by nueko** [lukesampson/scoop#1498]
Hi, just created my on [bucket](https://github.com/nueko/php-bucket), but when i tried to update php-redis, it did not update to 3.1.2

am i doing wrong?

and, how to get the php version on the manifest?

**Comment by r15ch13** [comment]
Using Github for `checkver` only works if they use Github's release feature. In this case, they only add version tags.

This should do it 😄 
```
    "checkver": {
        "url": "https://pecl.php.net/package/redis",
        "re": "Release ([\\d.]+)"
    }
```

**Comment by nueko** [comment]
thanks @r15ch13. but how you get the `Release ([\\d.]+)` i can't found it on the https://pecl.php.net/package/redis DOM?

**Comment by r15ch13** [comment]
In the Dependencies table :smile:

**Comment by nueko** [comment]
Thank you

**Comment by r15ch13** [comment]
`redis/([\\d.]+)` would also work. This would use the version links from the `Available Releases` table

**Comment by nueko** [comment]
and about the php version, can you help me?
i want to replace the 7.1 to the current php version.
`http://windows.php.net/downloads/pecl/releases/redis/$version/php_redis-$version-7.1-ts-vc14-x64.zip`

**Comment by r15ch13** [comment]
Hm maybe `redis/([\\d.]+)/windows` is the better solution, to make sure it's a windows release.

**Comment by r15ch13** [comment]
The PHP version has to be changed manually.

**Comment by nueko** [comment]
checking with checkver.ps1
`php-redis: 3.1.2 (scoop version is 3.1.1) autoupdate available`
running `scoop update` and `scoop update php-redis` not updating

**Comment by r15ch13** [comment]
Add `-u`

**Comment by nueko** [comment]
where to add the `-u` ?
i can't find it on `scoop help`

**Comment by r15ch13** [comment]
`checkver.ps1` only performs version checks, to actually update the manifest you need to add the `-u` parameter

`checkver.ps1 php-redis -u`

**Comment by nueko** [comment]
Oh, i see.. thanks alot.

**Comment by r15ch13** [comment]
For more information take a look into https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate

**Comment by nueko** [comment]
`"checkver": {
        "github": "https://github.com/phpredis/phpredis"
    }`

also works if i check with `checkver.ps1 php-redis -u`

**Comment by r15ch13** [comment]
You're right, but using `redis/([\\d.]+)/windows` is safer, because tags are a bit messy sometimes (especially for release candidates). e.g. `3.1.3-RC1` will be matched as `3.1.3` and so the update will always fail until they release it.

**Comment by nueko** [comment]
```json
"checkver": {
        "url": "https://pecl.php.net/package/redis",
        "re": "redis/([\\d.]+)/windows"
    }
````

like this?
or can i doing this?

```json
"homepage": "https://pecl.php.net/package/redis",
"checkver": "redis/([\\d.]+)/windows"
````

**Comment by r15ch13** [comment]
Both work, but the first one makes it more clear.

**Comment by nueko** [comment]
OK, i will use the first, thanks
