### ISSUE TITLE
Maybe Python2 should be added as well?

### ISSUE THREAD

**Issue by veremenko-y** [lukesampson/scoop#1499]

**Comment by lukesampson** [comment]
[Python 2.7](https://github.com/scoopinstaller/versions/blob/master/python27.json) is in the [versions bucket](https://github.com/scoopinstaller/versions/). You can install it by running:

```powershell
scoop bucket add versions
scoop install python27
```

**Comment by veremenko-y** [comment]
I'm sorry, I should have read the wiki. It's been a long time and I don't think it was there when I installed the scoop around a year ago. But it seems a little "hacky" with resets.

**Comment by lukesampson** [comment]
That's okay. The versions bucket was added to keep the main bucket tidy.
