### ISSUE TITLE
Bucket Manifest Inside a Directory

### ISSUE THREAD

**Issue by nueko** [lukesampson/scoop#1503]
Hi, can we put app manifest inside a directory?
I can't find the option on the wiki.

**Comment by lukesampson** [comment]
I'm not sure what you mean. Can you expand on what you want to do?

**Comment by nueko** [comment]
let's tell im working on a bucket for php ext
ensions, i want to put php71-*.json on 7.1 directory not in the root of bucket directory.

**Comment by lukesampson** [comment]
There's not really a way to do that within a bucket, sorry. The `/` is used to target an app in a specific bucket, e.g. `scoop install bucket/app`.

You could make it appear to work like a directory if you made the `php71` directory a separate bucket, e.g. `scoop install php71/example-ext` would work. But you would potentially get confusing behaviour if you had both `php` and `php71` buckets registered and both buckets have PHP extensions with the same name. If a user tried to install `example-ext` and that was present in both buckets, Scoop will just pick the first bucket it finds alphabetically. 

Short answer: using `php71-` prefix is probably the best way to do it.

**Comment by nueko** [comment]
OK, I see.
thanks.
