### ISSUE TITLE
Wrong path in miktex-portable.exe

### ISSUE THREAD

**Issue by SummerSad** [lukesampson/scoop#1508]
It directs to C:\MiktexPortable but it's installed in scoop directory.

**Comment by r15ch13** [comment]
Hm, we need some more information here.
Where is the wrong path and what directs to it?

**Comment by SummerSad** [comment]
in scoop\apps\latex\2.9.6326\miktex-portable.exe have wrong path.
It directs to : "C:\MiKTeX-Portable\texmfs\install\miktex\bin\miktex-taskbar-icon.exe"

**Comment by r15ch13** [comment]
What commands did you use?
What was the output?
What directs to `C:\MiKTeX-Portable`?

Sorry, I can't understand what your problem is. We really need more information.

**Comment by SummerSad** [comment]
Sorry, somehow I can run it normally.
