### ISSUE TITLE
OpenSSH and Git throws error on extraction

### ISSUE THREAD

**Issue by ChantOfAnAnt** [lukesampson/scoop#1509]
Hi. First of all, thank you all for bringing this refreshing homebrew-like vision to Windows! Now, to the point.

**Problem**

On installation of either `git` or `openssh` (or `git-with-openssh`) they return -1 on extraction. Moreover, they still visible as installed (while they are not really).

**Case**

Exemplar sequence of operations:

```
PS C:\projects> scoop list
Installed apps:

  7zip (16.04)
  nodejs (7.10.0)
  yarn (0.24.5)

PS C:\Users\Anthony> scoop install openssh
Installing 'openssh' (5.4p1-1).
Loading openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma from cache
Loading openssh-5.4p1-1-msys-1.0.13-lic.tar.lzma from cache
Loading msysCORE-1.0.13-2-msys-1.0.13-bin.tar.lzma from cache
Loading zlib-1.2.3-2-msys-1.0.13-dll.tar.lzma from cache
Loading libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma from cache
Loading libopenssl-1.0.0-1-msys-1.0.13-dll-100.tar.lzma from cache
Checking hash of openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma... ok.
Extracting... Exit code was -1.

PS C:\Users\Anthony> scoop list
Installed apps:

  7zip (16.04)
  nodejs (7.10.0)
  openssh (5.4p1-1)
  yarn (0.24.5)

PS C:\Users\Anthony> scoop install git
Installing 'git' (2.13.0.windows.1).
Loading PortableGit-2.13.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.13.0-64-bit.7z.exe... ok.
Extracting... Exit code was -1.

PS C:\Users\Anthony> scoop list
Installed apps:

  7zip (16.04)
  git (2.13.0.windows.1)
  nodejs (7.10.0)
  openssh (5.4p1-1)
  yarn (0.24.5)
```

I tried clearing cache, redownloading and checking hashes. Reproduced this issue on two Windows 10 PCs.

**Environment**

```
PS C:\Users\Anthony> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0
```
Updated `scoop` at latest (don't know how to see it from command line though).

**PS**

Can dig this up a little bit, but need guidelines.

**Comment by lukesampson** [comment]
It looks like the problem happens while 7-zip is extracting. Do you see an error in the Windows event log by any chance?

My first guess would be an anti-virus program locking the files so that 7-zip can't extract them.

It might be worth running `scoop uninstall 7zip; scoop install 7zip` just to be sure that 7-zip is okay, but I'd be surprised if that's the problem.

**Comment by ChantOfAnAnt** [comment]
Tried reinstalling 7-zip, no luck there. On anti-virus: first PC has it, but scoop folders in trusted list as scoop suggests, second PC in default state (Windows Defender, no trusting for folders). Can't see anything useful in windows logs.

On the other hand, this is pretty much interesting:

```
PS C:\projects> scoop install 7zip
Installing '7zip' (16.04).
7z1604-x64.msi (1,6 MB) [=======================================================================================================================] 100%
Checking hash of 7z1604-x64.msi... ok.
Extracting... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\16.04
Creating shim for '7z'.
'7zip' (16.04) was installed successfully!

PS C:\projects> 7z
Cannot find file at 'c:\program files\7-zip\7z.exe' (c:\program files\7-zip\7z.exe). This usually indicates a missing or moved file.
```

So, I probably have bad `7z` shimming or something. Reinstalled `7zip` by hand and voila, it worked! Dig that up a little bit and found that `chocolatey` does not remove its programs from Path.

```
C:\projects>where 7z
C:\ProgramData\chocolatey\bin\7z.exe
```

**Solution**

For thous who convert from `chocolatey` to `scoop` it would be better to just remove `C:\ProgramData\chocolatey\bin` from Path environment. In other case, any of *reinstalled* applications may look for wrong executable path.

**Comment by lukesampson** [comment]
Thanks for the detailed info — glad you found the solution. Welcome to the Scoop fam 😄
