### ISSUE TITLE
Request: Option to only have autoupdate as URL

### ISSUE THREAD

**Issue by simonwjackson** [lukesampson/scoop#1522]
It seems that when we have this..
```json
    "checkver": {
        "url": "https://iristech.co/iris/",
        "re": "Iris-([\\d.]+).exe"
    },
    "autoupdate": {
        "url": "https://github.com/danielng01/Iris-Builds/raw/master/Windows/Iris-$version.exe"
    }
```
this feels a bit redundant
```json
    "version": "0.9.0.7",

    "url": [
        "https://github.com/danielng01/Iris-Builds/blob/master/Windows/Iris-0.9.0.7.exe?raw=true#/dl.7z"
    ],
```

can `url` and `version` be optional when an auto update is available?

**Comment by lukesampson** [comment]
I don't think so. `url` and `version` are read directly from the manifest by Scoop when it does an install, without needing to go out to the external source like Auto Update does.

**Comment by simonwjackson** [comment]
That makes sense.

Does it check for the latest version before installing? It would be strange to install v0.1 from `url` & `version` when v6.0 is the latest.

Just a thought

**Comment by lukesampson** [comment]
Scoop doesn't check for a new version before installing, but you wouldn't get that a version that out-of-date for any manifest in main, extras or versions buckets with an `autoupdate` property. @r15ch13 runs auto updates regularly, so if you've run `scoop update` you can be fairly sure you're installing the latest version or very close.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.
