### ISSUE TITLE
Request: --dir <path>

### ISSUE THREAD

**Issue by simonwjackson** [lukesampson/scoop#1527]
First off, thank you for making this. I may be able to scrap some weak code that I wrote to accomplish the same thing.

In order to make it work, it would need install to a given directory. Is this possible in the current version?

**Comment by r15ch13** [comment]
This feature is currently not available. But you can install the complete `scoop` directory somewhere else by creating an environment variable `SCOOP`. You need to reinstall `scoop` for this. See #249

**Comment by simonwjackson** [comment]
`$env:SCOOP` should help me get the job done. Ideally, I would like to install an app outside of the scoop dir, but i realize that complicates things a bit.

Thanks for all the hard work! Glad that I can finally drop `chocolaty` for something better/familiar
