### ISSUE TITLE
Couldn't find manifest for 'tail'

### ISSUE THREAD

**Issue by yemikudaisi** [lukesampson/scoop#1529]
When I execute `scoop install tail`, I get the following error:
> Couldn't find manifest for 'tail'.

Yet, tail is listed as on of the supported applications on the repo home under [What does Scoop do?](https://github.com/lukesampson/scoop#what-does-scoop-do). Although, I've confirmed that the manifest for tail doesn't exist in the main bucket or extras.

**Comment by nueko** [comment]
please try this `scoop search tail` and choose you want to install with the list

**Comment by r15ch13** [comment]
`tail.json` was renamed to `coreutils.json` long time ago 0338f59c9854763b13ccc7263aebda0c4e145865 :smile:
