### ISSUE TITLE
Bug: running sccop without args

### ISSUE THREAD

**Issue by simonwjackson** [lukesampson/scoop#1530]
```powershell
C:\Users\simonwjackson\scoop>scoop
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

**Comment by nueko** [comment]
Can't reproduce the issue

**Comment by r15ch13** [comment]
Can't reproduce the issue

**Comment by ChantOfAnAnt** [comment]
Reproduced. This is a misunderstanding of environment context. If you run `scoop` while in `cmd` inside PowerShell, you will get described error message.

**Comment by r15ch13** [comment]
This is a problem with the scoop shim `scoop.cmd` which is created here: https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L211

When no arguments get provided `%args%` will become: `"='`

**Comment by nueko** [comment]
Why it is closed?

**Comment by r15ch13** [comment]
Autoclose through https://github.com/lukesampson/scoop/commit/a92b76905ed0bb429cc35c4cfe8c1b4de544d5f3

**Comment by nueko** [comment]
sorry I need to update my scoop 👍

**Comment by r15ch13** [comment]
But currently, there is no way to recreate the scoop shim 😢 
So this change has to be made manually if you fancy running scoop without arguments 😁
