### ISSUE TITLE
php_curl.dll requires libssh2.dll to be present in apache/bin folder

### ISSUE THREAD

**Issue by tobiaseichert** [lukesampson/scoop#1535]
In order to enable PHP's cURL extension, you have to copy **libssh2.dll** from scoop's PHP installation from 
```
$env:USERPROFILE\scoop\apps\php\current
```
to
```
$env:USERPROFILE\scoop\apps\apache\current\bin
```

Otherwise the cURL extension won't load, as far as I can tell. Can this be automated in the installation process or simply be included in https://github.com/lukesampson/scoop/wiki/Apache-with-PHP?

**Comment by nueko** [comment]
maybe the solution is included on the wiki or a note on manifest. but i can confirm using nginx or caddy works well

**Comment by nueko** [comment]
Just trying apache using php7.1 on _php bucket_  the cURL extension loaded properly without having to copy the libssh2.dll 
Added to httpd.conf
```ini
AddHandler application/x-httpd-php .php
AddType application/x-httpd-php .php .html
LoadModule php7_module "D:/Applications/Scoop/apps/php7.1/current/php7apache2_4.dll"
PHPIniDir "D:/Applications/Scoop/apps/php7.1/current" 
```

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F1535
