### ISSUE TITLE
Unable to install curl Win64 : Hash check failed

### ISSUE THREAD

**Issue by yemikudaisi** [lukesampson/scoop#1536]
![curl-error](https://cloud.githubusercontent.com/assets/3257276/26678888/9e598b3c-46ca-11e7-9711-26d2d0411904.PNG)

**Comment by r15ch13** [comment]
Was fixed with https://github.com/lukesampson/scoop/commit/9fb4d784e98e4187b48417b18748619ccb84194b
Please run `scoop update` and try again.

**Comment by yemikudaisi** [comment]
That fixed the problem, Thanks.
