### ISSUE TITLE
scoop outdated command

### ISSUE THREAD

**Issue by jkrehm** [lukesampson/scoop#155]
One feature about I love about Mac's Homebrew that I'd love to see in scoop is an `outdated` command that I can run to quickly see which of my packages have updates to install. I don't necessarily want to install them all so `scoop update *` doesn't really fit the bill. Is there anything like this already? Nothing stood out to me when I ran `scoop help`.

If it's not too complex, I think it'd be a useful command to have available.

**Comment by andreyrd** [comment]
Would it be worth aliasing `scoop outdated` to `scoop status` for consistency with `brew`?

**Comment by borekb** [comment]
... and with `npm` and `yarn`. "outdated" is in my muscle memory now :)

**Comment by r15ch13** [comment]
This should do the trick: `scoop alias add outdated 'scoop status'`

**Comment by borekb** [comment]
That didn't work for me:

```
$ scoop alias add outdated 'scoop status'

$ scoop outdated
Usage: scoop <command> [<args>]

Some useful commands are:
...
```

**Comment by r15ch13** [comment]
Hm. Can you check if `~\scoop\shims` contains a `scoop-outdated.ps1` with this content:
```powershell
# Summary: 
scoop status
```

**Comment by borekb** [comment]
The file exists but contains this:

```
﻿# Summary: status
scoop
```

**Comment by r15ch13** [comment]
Maybe the `'` where misinterpreted. Try `scoop alias add outdated "scoop status"`

**Comment by borekb** [comment]
That didn't help either. I usually live in Git Bash so I tried to switch to PowerShell for adding the alias and that worked, so it's shell-related.

I don't have much experience yet with running PowerShell scripts from Git Bash as not many binaries I run are written in this language / technology, so I'll need to explore it more.

**Comment by borekb** [comment]
`scoop` needs to be run via `winpty` to work in Git Bash, all works fine after I've set up this alias in `.bashrc`:

```
alias scoop='winpty scoop.cmd'
```

**Comment by goyalyashpal** [comment]
> for consistency with `brew`?
> ... and with `npm` and `yarn`
> \- @ andreyrd and @ borekb at https://github.com/ScoopInstaller/Scoop/issues/155#issuecomment-327682193

* pacman has `--upgrades`: `pacman -Qu`
* pip too has `--outdated`: `pip list --outdated`

yeah, the status kinda doesn't feel like fitting the description of showing updates very well... though, i don't have any strong opinions on it being outdated.
