### ISSUE TITLE
msys2

### ISSUE THREAD

**Issue by Alxandr** [lukesampson/scoop#1551]
I noticed it was possible to install msys from scoop, but following the links in the config file that seems to be the old version. Could you add msys2 install?

**Comment by AStupidBear** [comment]
```scoop install https://raw.githubusercontent.com/AStupidBear/scoop-bear/master/msys2.json``` works for me.

**Comment by lukesampson** [comment]
@AStupidBear How would you feel about submitting your msys2 manifest to the main bucket?

**Comment by AStupidBear** [comment]
#1566

**Comment by lukesampson** [comment]
Thanks @AStupidBear. @Alxandr you can now run `scoop install msys2` (after running `scoop update`).
