### ISSUE TITLE
scoop update fails

### ISSUE THREAD

**Issue by simonwjackson** [lukesampson/scoop#1553]
```
> scoop update
Updating Scoop...
fatal: Not a git repository (or any of the parent directories): .git
Update failed.
```

Then I tried to force a reinstall

```
> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
```

Catch 22?

**Comment by lukesampson** [comment]
I can't reproduce this.

Have you changed the installation directory or added custom buckets? What do `scoop which scoop` and `scoop bucket list` tell you? And what does `$env:scoop` output?

When you run `scoop status` after the update fails, does it tell you Scoop is up to date? If it does then it could be a bucket update that's failing.

**Comment by mykolapolonskyi** [comment]
catch same issue 
```
 3:51:36 PM ~\scoop
$ scoop update
Updating Scoop...
fatal: Not a git repository (or any of the parent directories): .git
Update failed.
 3:51:41 PM ~\scoop\apps\scoop\current
$ scoop status
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Scoop is up to date.
Everything is ok!
```

I have suggestion that something wrong with git because it can't see my other repos.
IDK what kind of info I get to help more

**Comment by r15ch13** [comment]
@mykolapolonskyi 
Does `$env:scoop` really return `~\scoop\apps\scoop\current`? 😕 
It should be only `~\scoop`

**Comment by mykolapolonskyi** [comment]
"3:58:10 PM ~\scoop\apps\scoop\current" its line with current folder but not return 

![image](https://user-images.githubusercontent.com/7451751/27182742-f61ed6c2-51e4-11e7-8c28-4aa209b5c81b.png)

$env:scoop is empty

**Comment by r15ch13** [comment]
Ah okay, misinterpreted your console output. 😄

**Comment by r15ch13** [comment]
This happens when the `.git` directory is malformed or empty.
Solution: Navigate to `~\scoop\apps\scoop\current` and delete the `.git` directory.
Close all explorer/console windows accessing `~\scoop\apps\scoop\current` and run `scoop update`.
This recreates a working git repository of scoop.

**Comment by mykolapolonskyi** [comment]
![image](https://user-images.githubusercontent.com/7451751/27183418-36fb4fe8-51e7-11e7-810d-7ca0de104ebc.png)

I have another case. Now its seems to be some conflict with WSL

**Comment by r15ch13** [comment]
Are you executing scoop from bash or powershell? I don't have the WSL installed myself so I can't test it.

**Comment by mykolapolonskyi** [comment]
power shell.
I have dropped WSL cos have found scoop :-D 
now will try reinstall

**Comment by simonwjackson** [comment]
Not on this machine, no. I also had to remove and reinstall scoop

**Comment by mykolapolonskyi** [comment]
@simonwjackson BTW - I remember that I have add custom folder into WINODWS10 **path** variable and there was **git.bat** file. It provide additional problems for me. But still it was related to WSL so think is not a case for you. 
But still maybe it will help you. 
Maybe you have additional git installation

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by g-berthiaume** [comment]
I had the same problem.
![image](https://user-images.githubusercontent.com/19377511/106478873-ad851d00-6477-11eb-918b-53586e45a0ca.png)


This solved the issue for me.
```
scoop bucket rm extras 
scoop bucket add extras
scoop update
```

**Comment by danindiana** [comment]
Wondering what is going on here with my scoop? 

PS C:\Users\walter\scoop\apps\scoop\current> scoop bucket rm extras
PS C:\Users\walter\scoop\apps\scoop\current> scoop bucket add extras
Checking repo... ok
The extras bucket was added successfully.
PS C:\Users\walter\scoop\apps\scoop\current>
PS C:\Users\walter\scoop\apps\scoop\current> scoop update
Updating Scoop...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
fatal: not in a git directory
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Update failed.

PS C:\Users\walter\scoop\apps\scoop\current> scoop export
7zip (v:19.00)
aria2 (v:)
cacert (v:2020-01-01) [main]
curl (v:7.68.0)
dark (v:)
gcc (v:8.1.0.0)
git (v:)
go (v:1.13.7)
innounp (v:)
nim (v:1.0.6)
ntop (v:0.3.4)
restic (v:)
rust (v:1.41.0)
wget (v:1.20.3)
wixtoolset (v:)

PS C:\Users\walter\scoop\apps\scoop\current> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\walter\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 3 potential problems.
