### ISSUE TITLE
Autoupdate from page with multiple published versions

### ISSUE THREAD

**Issue by masaeedu** [lukesampson/scoop#1554]
How would I go about specifying the "latest version" extraction mechanism from a page like, say, [this one](https://repo.continuum.io/miniconda/)? It'd be nice if there was some way to hook in some arbitrary executable for extracting the relevant version string (e.g. in the example I linked I'd want to iterate over all matches to a regex and pull out the highest one). If I could do `"checkver": { "exe": "curl ..." }`, that would make things super easy.

Semi-related question: does scoop have any support for simply describing a recipe for installing a given version string, without locking the user to the latest? E.g. `scoop install miniconda@x.y.z`, which would use `checkver`, `autoupdate`, and `hash` to obtain and install the correct artifacts? This way I wouldn't have to maintain a curated manifest that needs to be updated in tandem with the actual publishers of the software.

**Comment by r15ch13** [comment]
In the case of Miniconda a regex like this will be enough: `Miniconda3-([\d.]+)-Windows-x86.exe`. Scoop uses only the first matching result.

`scoop install miniconda@x.y.z` was made possible with #1332. As long as the download URL doesn't change (some developers move older versions to a subdirectory) this will create a custom manifest to install that version.
