### ISSUE TITLE
ffmpeg fails to install when using scoop to install youtube-dl (hash does not match)

### ISSUE THREAD

**Issue by bdriffield** [lukesampson/scoop#1556]
Hi Everyone,

I'm currently unable to install yotube-dl via scoop. When it gets to the ffmpeg install it fails during the hash check. Is there any way I can fix this?, I appreciate any insight or feedback.

PS C:\> scoop install youtube-dl
Installing 'ffmpeg' (20170615-bc40674).
ffmpeg-20170615-bc40674-win64-static.zip (46.1 MB) [===================
Checking hash of ffmpeg-20170615-bc40674-win64-static.zip... Hash check
Expected:
    9b5b664413c62486323472fe81a41e77855599b3afe8af002c7dc501480c8d77
Actual:
    87cefd4f172ffe703d15958fbc63b732b20492b2320af4bf102eb550edd2c7ab

**Comment by lukesampson** [comment]
Looks like FFmpeg patched binaries without bumping the version. Should work now after running `scoop update`.
