### ISSUE TITLE
add scoop root env. variable

### ISSUE THREAD

**Issue by szachara** [lukesampson/scoop#1562]
Can we add `SCOOP_ROOT` system env. variable to `C:\Users\Silver Zachara\scoop\apps` folder? 

I need to use this in config. files, e.g. in php.ini for e.g. `curl.cainfo = "${SCOOP_ROOT}\apps\php-nts\current\cli\extras\cacert.pem"` or `browscap = "${SCOOP_ROOT}\apps\php-nts\current\cli\extras\browscap.ini"`

**Comment by lukesampson** [comment]
How about using `%USERPROFILE%/scoop` which is the default install directory?

There is a `%SCOOP%` environment variable, but that's only intended to be set if you want to change the default install directory.

**Comment by szachara** [comment]
%SCOOP% would be good, if will not be implemented, so this issue could be closed.

**Comment by lukesampson** [comment]
Just to clarify, I'm suggesting you use e.g. `curl.cainfo = "${USERPROFILE}\scoop\apps\php-nts\current\cli\extras\cacert.pem"` in your config, unless you have explicitly set `%SCOOP%`.
