### ISSUE TITLE
Allow choosing 32bit / 64bit app versions

### ISSUE THREAD

**Issue by regystro** [lukesampson/scoop#1567]
Hi!

I find useful the ability to force the installation of a 32bit version of an app in a 64bit Windows.
For instance, current Notepad++ 64bit version lacks a LOT of plugins still available in the 32bit version. I always install the latter.

You could add a switch like
`scoop install notepadplusplus --force32`

Thank you in advance.

**Comment by r15ch13** [comment]
There is already a install switch for that. `-a` or `--arch`

`scoop install notepadplusplus --arch 32bit`
