### ISSUE TITLE
scoop install nvm - nvm not working

### ISSUE THREAD

**Issue by TobiasTimm** [lukesampson/scoop#1576]
I have installed nvm via scoop with
`scoop install nvm`

The installation worked perfectly, after restart of powershell i tried to use

`nvm install node`

but nothing is happening at all. Only a new line in my ps

OS: Windows 10 Pro x64

**Comment by elmosgot** [comment]
I believe you should have installed by the following command:
`scoop install nodejs`

**Comment by TobiasTimm** [comment]
@elmosgot `nodejs` works fine. But I want `nvm `to use different versions of `nodejs`

**Comment by r15ch13** [comment]
Isn't it `nvm install latest`?

**Comment by TobiasTimm** [comment]
It doesn't matter. Nothing is happening at all :(

**Comment by r15ch13** [comment]
Does it work in `cmd`?

**Comment by TobiasTimm** [comment]
@r15ch13 yh. Seems to be a powershell problem

**Comment by TobiasTimm** [comment]
I'm closing this. Bitdefender blocked nvm.exe with powershell. everything works fine now 👍

**Comment by QM1412** [comment]
I have installed nvm via scoop with
scoop install nvm
but the error is 
Couldn't find manifest for 'nvm'.

i don't know how to solve it

**Comment by HUMORCE** [comment]
> I have installed nvm via scoop with scoop install nvm but the error is Couldn't find manifest for 'nvm'.
> 
> i don't know how to solve it

So what is console output when you run scoop update?

**Comment by QM1412** [comment]
now, i run scoop upadte is ok,but runing scoop install nvm,the console display Couldn't find manifest for 'nvm'. what happend?

**Comment by HUMORCE** [comment]
Main bucket is not added or broken.

```
scoop bucket rm main
scoop bucket add main
```
