### ISSUE TITLE
Scoop unable to Find Shim Files

### ISSUE THREAD

**Issue by RGAlexander216** [lukesampson/scoop#1579]
I definitely broke Scoop on my computer and upon trying to reinstall after completely removing I've had no luck resolving this issue.This same error has occurred no matter what I attempt to install. The output received from the error message does not make sense. Specifically, the part that says it can't find the disk drive label of "File not found - C".

"Exception calling "GetUnresolvedProviderPathFromPSPath" with "1"
argument(s): "Cannot find drive. A drive with the name 'File not found -
C' does not exist."

My folder is in the right location (C:/users/myuserid/scoop) my path USERPROFILE variable is set to the folder location correctly. I would think that upon reinstall any variables would have been either replaced in the path or added if they were missing, but that did not occur. 

scoop install chromedriver
Installing 'chromedriver' (2.30).
Loading chromedriver_win32.zip from cache
Checking hash of chromedriver_win32.zip... ok.
Extracting... done.
Linking ~\scoop\apps\chromedriver\current => ~\scoop\apps\chromedriver\2.30 Creating shim for 'chromedriver'.
Exception calling "GetUnresolvedProviderPathFromPSPath" with "1"
argument(s): "Cannot find drive. A drive with the name 'File not found -
C' does not exist."
At C:\Users\Greg\scoop\apps\scoop\current\lib\core.ps1:101 char:5
+     $executionContext.sessionState.path.getUnresolvedProviderPathFrom ... +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationExcept
   ion
    + FullyQualifiedErrorId : DriveNotFoundException

Exception calling "GetUnresolvedProviderPathFromPSPath" with "1"
argument(s): "Cannot find drive. A drive with the name 'File not found -
C' does not exist."
At C:\Users\Greg\scoop\apps\scoop\current\lib\core.ps1:101 char:5
+     $executionContext.sessionState.path.getUnresolvedProviderPathFrom ... +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationExcept
   ion
    + FullyQualifiedErrorId : DriveNotFoundException

Can't shim 'chromedriver.exe': File doesn't exist.

**Comment by lukesampson** [comment]
Are you able to enable PowerShell tracing (`set-psdebug -trace 2`), run the install command again, and post the output?

**Comment by RGAlexander216** [comment]
Yes, but since it's so long I've just saved it in the attached document
[Powershell_Output.txt](https://github.com/lukesampson/scoop/files/1126780/Powershell_Output.txt)

**Comment by lukesampson** [comment]
It looks like there is a problem occurring at [install.ps1 line 729](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L729) calling `cmd /c mklink /j $currentdir $versiondir | out-null`, and then the subsequent `attrib $currentdir +R /L` is outputting an error and that's where the `File not found` is coming from.

This code seems to work fine for most other people. What version of Windows are you using? Or have you overridden `mklink` by any chance?

Can you test by running `cmd /c mklink /j "C:\users\USERID\scoop\apps\chromedriver\current" "C:\users\USERID\scoop\apps\chromedriver\2.30"` and see what you get? Scoop is doing an `| out-null` so that's hiding whatever the error is. Please make sure the "C:\users\USERID\scoop\apps\chromedriver\2.30" directory exists first, or use another directory that you know to exist.

**Comment by RGAlexander216** [comment]
The output is below, but I'm definitely thinking that I may have some issue on my system because while trying to do a "WHERE /R C:\ mklink.*" commmand it completed in under five seconds with a lot more than 10 seconds-worth of files to go through.

That aside, I am using Windows 10 and I don't think that I've overridden mklink since it's providing output, but I don't know how functional it is citing the aforementioned "WHERE ..." command. The current folder did not exist so I created it. The first time I ran the command the current folder did not exist and I received the exact same output.

===============================================================
PS C:\>  cmd /c mklink /j "C:\users\Greg\scoop\apps\chromedriver\current" "C:\users\Greg\scoop\apps\chromedriver\2.30"

DEBUG:    1+   >>>> cmd /c mklink /j
"C:\users\Greg\scoop\apps\chromedriver\current"
"C:\users\Greg\scoop\apps\chromedriver\2.30"
DEBUG:     ! CALL function '<ScriptBlock>'

===============================================================

**Comment by RGAlexander216** [comment]
If you agree you can close this issue. I really appreciate your help.

**Comment by lukesampson** [comment]
That looks like mklink worked okay when you ran it manually. Am I reading that right? I was expecting some sort of error.

It does seem like an issue with your system though. It will probably be a bit hard to debug through GitHub without more info, so I will go ahead and close this for now.

Good luck and feel free to post an update if you can work out what's going wrong.
