### ISSUE TITLE
install solarized fails

### ISSUE THREAD

**Issue by jcollum-cambia** [lukesampson/scoop#1587]
```
>> concfg import solarized
>>
console settings exported to console-backup.json
fatal: Not a git repository (or any of the parent directories): .git
concfg: ERROR: couldn't load settings from solarized 

```

Same for `solarized small`. Your docs need an update? 

This did work though: `concfg import https://raw.github.com/lukesampson/concfg/master/presets/solarized-light.json`

Thanks for making this though! Great library, customizing powershell is too much work.

**Comment by lukesampson** [comment]
There's a separate GitHub project for concfg [here](https://github.com/lukesampson/concfg). Do you mind posting this there instead?

**Comment by jcollum-cambia** [comment]
But it's from the readme for this project. Seems like this project's readme is out of date.

**Comment by jcollum-cambia** [comment]
(this could be the result of our proxy here at the office)

**Comment by lukesampson** [comment]
Sorry, which readme? Can you post the link?

**Comment by jcollum-cambia** [comment]
Sorry not readme, it's the wiki: https://github.com/lukesampson/scoop/wiki/Theming-Powershell . I was running through that when I hit the bug. But after running some basic commands like `concfg help import` and getting errors I suspect it's an issue with the proxy here at the office.

**Comment by lukesampson** [comment]
Okay no worries. Yeah concfg doesn't call git so that error must be coming from somewhere else. I'll close this now — feel free to open a new issue on the concfg project if it there's something I can help with.
