### ISSUE TITLE
Hash Check Fails for Apache

### ISSUE THREAD

**Issue by LauraMakesArt** [lukesampson/scoop#1588]
Attempting to update apache is giving me this error:

Hash check failed for 'https://www.apachelounge.com/download/VC14/binari
es/httpd-2.4.27-win64-VC14.zip'.
Expected:
    D6F7BCDA3FD54FE2BDED89E09B5F75DB40373AF363EB7547E7B899A7D6450842
Actual:
    24475fa957495f5d9847b941349e4a416b8175540041bb1649c453ee07a8a15c

**Comment by r15ch13** [comment]
Fixed, `scoop update` and try again 👍

**Comment by LauraMakesArt** [comment]
Excellent, worked like a charm!
