### ISSUE TITLE
scoop can't install docker

### ISSUE THREAD

**Issue by alexandermomot** [lukesampson/scoop#1589]
Trying to install docker, it looks like file is not exists when scoop tries to rm it. 

```
C:\Users\user\scoop                                                                                                                   
λ scoop install docker    
                                                                                                                       
Installing 'docker' (17.05.0-ce).                                                                                                                
Loading docker-17.05.0-ce.zip from cache                                                                                                         
Checking hash of docker-17.05.0-ce.zip... ok.                                                                                                    
Extracting... rm : Cannot remove item C:\Users\user\scoop\apps\docker\17.05.0-ce\_tmp\docker\docker.exe: Access to the path is denied.
At C:\Users\user\scoop\apps\scoop\current\lib\install.ps1:361 char:21                                                                 
+                     rm -r -force "$dir\_tmp" -ea stop                                                                                          
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                          
    + CategoryInfo          : InvalidArgument: (docker.exe:FileInfo) [Remove-Item], ArgumentException                                            
    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand 
```

**Comment by masaeedu** [comment]
@alexandermomot Did you perhaps install this the first time in an elevated shell?

**Comment by lukesampson** [comment]
It looks like `docker.exe` might have been in use when you tried to uninstall. Once you make sure it's not running, you can usually just run `scoop uninstall [app]` again.

**Comment by alexandermomot** [comment]
@masaeedu truly. It was firstly installed the way you mentioned. 

Don't know why, but docker were installed properly few hours later. 

@lukesampson I was able to perform "uninstall" right after the "install" command fails.

**Comment by lukesampson** [comment]
Sorry I didn't read that carefully. Most of the time this kind of problem is caused by a virus scanner locking the temporary file so that Scoop can't remove it.

There is some [more info on the wiki](https://github.com/lukesampson/scoop/wiki/Antivirus-and-Anti-Malware-Problems).

If you're running Windows Defender on Windows 10, `scoop checkup` should detect the problem and give you the command to run to disable realtime scanning for the Scoop directory.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.
