### ISSUE TITLE
ripgrep (rg) requires vcruntime140 (Visual C++ Redistributable)

### ISSUE THREAD

**Issue by fredjoseph** [lukesampson/scoop#1599]
`rg` doesn't work after installing it, because of a missing dependency "vcruntime140.dll".

**Comment by lukesampson** [comment]
Does `scoop install extras/vscredist` afterwards allow `rg` to work?

**Comment by fredjoseph** [comment]
Yes, it works. In fact, vcredist2015 is enough, no need all versions
