### ISSUE TITLE
Can't install 7zip, 7zip already installed?

### ISSUE THREAD

**Issue by hfaran** [lukesampson/scoop#16]
```
PS C:\Users\redacted> scoop install git
7zip is required to install this app. please run 'scoop install 7zip'
PS C:\Users\redacted> scoop install 7zip
installing 7zip (9.20)
downloading http://downloads.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi...done
checking hash...ok
the MSI package is already installed on this system
PS C:\Users\redacted> scoop install git
7zip is required to install this app. please run 'scoop install 7zip'
PS C:\Users\redacted>
```

Would you know why this happens? Can't exactly use scoop without it knowing about it 7zip.

**Comment by Guard13007** [comment]
@lukesampson Is there a way to install 7-zip using scoop that *does* execute the MSI and specify that they want the explorer integrations? Even if I have to make my own bucket to do that, is there a way it can be done?

**Comment by EnKrypt** [comment]
Here's what I did to install 7zip via scoop and also keep the shell integrations.

First, remove any versions of 7zip installed externally (i.e outside scoop by manually downloading or whatever)  
Now your shell context menu for 7zip and CRC SHA should be gone.

After that, go to your start menu and search for 7zip (it should show you the version installed by scoop)  
OR manually go to Start Menu -> All apllications -> Scoop Apps -> 7zip  
OR go to your scoop install folder. By default: ~/scoop/apps/7zip/current/7zFM.exe

Run it as administrator

Go to Tools -> Options -> 7zip and enable the shell integration

**Comment by rsrini7** [comment]
> I had the same problem and my workaround is this.
> I created the following empty folders under the SCOOP_DIR\apps\7zip\9.20 (where SCOOP_DIR is either the Appdata or the ProgramData folder, depends whether you want to "install" globally or not). Then I created the files 7z.cmd and 7z.ps1 under the SCOOP_DIR\shims folder containing the following lines
> 
> 7z.cmd
> 
> ```
> :: ensure $HOME is set for MSYS programs
> @if "%home%"=="" set home=%homedrive%%homepath%\
> @if "%home%"=="\" set home=%allusersprofile%\
> @"C:\Program Files\7-Zip\7z.exe" %*
> ```
> 7z.ps1
> 
> ```
> # ensure $HOME is set for MSYS programs
> if(!$env:home) { $env:home = "$home\" }
> if($env:home -eq "\") { $env:home = $env:allusersprofile }
> $path = 'C:\Program Files\7-Zip\7z.exe'
> if($myinvocation.expectingInput) { $input | & $path @args } else { & $path @args }
> ```
> So i was thinking, if it is possible to be able to add existing apps to scoop (actually a way of only setting up the right shim file).

I tried this and not succeed. I dont have admin rights to uninistall the prevously installed one. Great, if someone help on this "without uninstall" is there any work arround ?

**Comment by anilvaska** [comment]
Could not find '7-Zip'! (error 16)
At C:\Users\vaskaa\scoop\apps\scoop\current\lib\core.ps1:889 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find '7-Zip'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find '7-Zip'! (error 16) getting this error while installing 7zip
