### ISSUE TITLE
Python executable not referenced in Windows Registry

### ISSUE THREAD

**Issue by moigagoo** [lukesampson/scoop#160]
For Python package installers to be able to locate Python, this record in registry must exist, with the Python installation path as the value: HKEY_CURRENT_USER\Software\Python\PythonCore\3.4\InstallPath

(This is a Python 3 example since that's the version I'm using; should be similar with Python 2.)

Is there a way to add this record on installation automatically? Adding it manually is anything but trivial.

**Comment by ntwb** [comment]
This was fixed in https://github.com/lukesampson/scoop/commit/2ad8316764c4f61d90c6f5366f4459520f582eee

**Comment by lukesampson** [comment]
Thanks @ntwb, I'll close it.

**Comment by gaspan** [comment]
vdfvfd
