### ISSUE TITLE
PHP/Composer issue (missing OpenSSL extension)

### ISSUE THREAD

**Issue by fishnux** [lukesampson/scoop#1609]
I have php-nts and composer installed (both via scoop). This is what happens when I use Composer (composer require):
```
[Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. 
  If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.
```
Looks like the OpenSSL extension is missing. It would be great to have this automatically installed as well. And by the way, does anyone have any tips on how to fix this using best practices?

Links that might be useful:
https://secure.php.net/manual/en/openssl.installation.php

**Comment by rasa** [comment]
Opened is not enabled by default. See https://github.com/php/php-src/blob/master/php.ini-production. Remove the semicolon before `extension=openssl`

**Comment by fishnux** [comment]
Thanks @rasa!

**Comment by zored** [comment]
Does CLI PHP ignore `~/scoop/persist/php/cli/php.ini` by default?
I force it with `php -c path/to/php.ini`.

**Comment by r15ch13** [comment]
@zored Scoop adds `PHP_INI_SCAN_DIR` to the [environment](https://github.com/lukesampson/scoop/blob/master/bucket/php.json#L26-L28) with `~/scoop/persist/php/cli` and `~/scoop/persist/php/cli/conf.d`, so it should load `php.ini` from there.

**Comment by zored** [comment]
@r15ch13 thank you! For some reason it appeared after Windows restart.

**Comment by kenorb** [comment]
### Solution

Run these commands in the terminal:

```
cd %HOMEPATH%\scoop\apps\php\current\cli\conf.d
echo extension=openssl >> openssl.ini
```

**Comment by strom019** [comment]
**Thanks @rasa**
Just started with _**scoop**_ on win10 and _**composer**_ immediately complained about _**'tls'**_. Your answer saved me.

**Comment by abrhambas01** [comment]
> Openssl is not enabled by default. See https://github.com/php/php-src/blob/master/php.ini-production. Remove the semicolon before `extension=openssl`

1. I tried installing a composer module with composer require global ... 
2 But when I change the php.ini and remove the semicolon before 

 ;extension=openssl

it keeps on coming back after i restart my laragon

**Comment by rasa** [comment]
@abrhambas01 try @kenorb’s solution:
```
cd /d “%HOMEDRIVE%\%HOMEPATH%\scoop\apps\php\current\cli\conf.d”
echo extension=openssl >> openssl.ini
```

**Comment by abrhambas01** [comment]
I used laragon in mine. Miraculously, I now got it back, Thank God

**Comment by ilkka** [comment]
fwiw I had to use the absolute path including full filename of php_openssl.dll before it would work.

**Comment by MichaelNeely77** [comment]
Having this issue right now and no solution has worked thus far. Any other suggestions? Running PHP 7.2.23, Composer 1.83, installed with Laragon and cannot run create-project right now. It has worked in the past but just changed the php version since I was unknowingly running on php 5.6.

**Comment by r15ch13** [comment]
Do you use the laragon terminal? It may use the wrong php version.
What is the output of `php --ini`?

**Comment by MichaelNeely77** [comment]
It all began when I ran into problems in a Laravel project and noticed that I was running on php 5.6. I changed the php version my machine was running on to 7.3.19 then noticed that it had issues with Laravel. Last night I changed it to php 7.2.23 and thought that would fix it. It didn't. 

When I ran composer why-not I got a new message:

`Symfony\Component\Console\Exception\RuntimeException Not enough arguments (missing: "package")`

I figured that I was missing some dependency connections from changing the php version from 5.6 to 7.2.23. I got mad, downloaded Composer and reinstalled it manually. 

It worked and I got the project created. Seems to work now.

.

**Comment by web-brandings** [comment]
I reinstalled composer, now it is working like a charm. If you have xampp installed on your windows machine composer copies your C:\xampp\php\php.ini-production File to C:\xampp\php\php.ini. You could also do this step manually. I've been experiencing this issue by upgrading my php version in xampp manually, so the "composer php.ini" was missing imao. Hope this helps someone.

Hee heeee - Shamona!

**Comment by electronicdreamer** [comment]
The echo command worked for me (if anyone has an idea why, I'd like to know).

But I'd also like to know why the initial solution doesn't work? Why is uncommenting extension=openssl not enough?
When I check phpinfo(), I see that extension_dir is set to C:/php/ext, why is that?

**Comment by gya-informatica** [comment]
I have same error.

1) Leave uncommented extension=openssl 
;extension=openssl

2) Add the path to the extension dir:

; Directory in which the loadable extensions (modules) reside.
; http://php.net/extension-dir
;extension_dir = "./"
; On windows:
extension_dir =  "C:/laragon22/bin/php/php-7.4.5-nts-Win32-vc15-x64/ext"

My english is poor. Sorry

**Comment by Eddcapone** [comment]
Try to run composer with sudo, that solved it for me.

**Comment by IVNtech** [comment]
Hi

**Comment by OrjiNuel** [comment]
> Openssl is not enabled by default. See https://github.com/php/php-src/blob/master/php.ini-production. Remove the semicolon before `extension=openssl`

I've tried this but it didn't work for me

**Comment by coding-bunny** [comment]
I've ran into the same problem today where `composer` kept complaining about the OpenSSL extension not being enabled.
Even running the provided commands to generate the openssl.inio file did not resolve the problem.

The only solution was to edit `~\scoop\apps\php\current\cli\php.ini` by hand and ensure that the extension was enabled.

```
cd "~\scoop\apps\php\current\cli\conf.d"
echo extension=openssl >> openssl.ini
```

The above did work on my laptop, but not on my desktop.
Going to chalk this one off on Windows Shenanigans.
