### ISSUE TITLE
radare2 is not avaible

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#1611]
scoop gives error when installing radare2.

```
λ  scoop install radare2
Installing 'radare2' (1.5.0).
Unable to connect to the remote server
URL http://cloud.radare.org/get/1.5.0/radare2-w64-1.5.0.zip is not valid
```

can we add latest version of it (1.6.0) and fix this issue?

thx again for app, efforts and good work!

**Comment by r15ch13** [comment]
Done: https://github.com/lukesampson/scoop/commit/4b8169d88710a38d2cc2c3c733c1be5584de1b98
