### ISSUE TITLE
go, Access is denied.

### ISSUE THREAD

**Issue by onacit** [lukesampson/scoop#1634]
I just installed `go` package. And I got following error from my first command.

```
C:\Users\myname\tmp>go build helloworld.go
package main
        imports runtime: open C:\Users\myname\scoop\apps\go\current\src\runtime\asm_ppc64x.h: Access is denied.
```

Is there any possible reason that I can fix with it? Thanks.

**Comment by stuartellis** [comment]
@onacit  - I have successfully installed Go using scoop and built a "hello, world" (on Windows Server 2016), so this may be something specific to your computer. Perhaps there is something wrong with the permissions on your scoop folder?

**Comment by onacit** [comment]
@stuartellis Indeed, I thought about it, too. I'm gonna dig into it. Thanks.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by SonuPaswan** [comment]
@onacity i am getting the same error. How did you fix this??? Please tell me.

**Comment by onacit** [comment]
@SonuPaswan I'm sorry I don't remember how I did it. I'm not even sure I actually resolved it or not.

**Comment by SonuPaswan** [comment]
How do you use to run programs???
