### ISSUE TITLE
Fails to extract .msi Files on Win7 x64

### ISSUE THREAD

**Issue by Jokler** [lukesampson/scoop#1642]
Console
```
λ scoop install 7zip
Installing '7zip' (16.04).
Loading 7z1604-x64.msi from cache
Checking hash of 7z1604-x64.msi... ok.
Extracting... Exit code was .
Failed to extract files from C:\Users\Jokler\scoop\apps\7zip\16.04\7z1604-x64.msi.
Log file:
  ~\scoop\apps\7zip\16.04\msi.log
```
msi.log
```
=== Logging started: 07.08.2017  19:45:19 ===
=== Logging stopped: 07.08.2017  19:45:19 ===
```
The _tmp folder already contains the extracted files so I have no idea what the problem is.

**Comment by h404bi** [comment]
This issue will appear when you execute `scoop install 7zip` or `scoop install yarn` (any .msi app) inside `cmder`, try to startup a `cmd` to run the command, and problem solved.

Don't know why meet this issue inside cmder.

duplicate #1107 #1445

**Comment by Jokler** [comment]
Well that's annoying because I usually have cmd completely replaced by cmder.

Since the other issue is closed I'd assume there are no plans to fix it?

**Comment by h404bi** [comment]
I have no idea about it. I use cmder, too.
pin: @lukesampson @r15ch13

**Comment by r15ch13** [comment]
I always use `cmder` and never had this problem. 😕
So I can't investigate it 😞

**Comment by r15ch13** [comment]
Which `ConEmu` version is shown in your settings titlebar?
I use the preview version `170305`

**Comment by Jokler** [comment]
I'm on `161206`
I use, these settings in case that makes a difference.

![conemu64_2017-09-11_14-27-52](https://user-images.githubusercontent.com/5204415/30274405-93b9009e-96fd-11e7-82ec-06dfc826abd3.png)

**Comment by r15ch13** [comment]
I reverted back to `161206` and tried it using the now hooked `cmd`/`powershell` and normal `cmder` instances. No problem installing 7zip. 😕

**Comment by Jokler** [comment]
I tried installing 7zip again and it actually works for me too now.
Are cmder updates silent? Because then it might have been a problem on cmders side.

**Comment by Jokler** [comment]
I am assuming this is fixed by updating `cmder` so I will close this issue for now.
