### ISSUE TITLE
chromium is not in the list

### ISSUE THREAD

**Issue by motss** [lukesampson/scoop#1650]

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop-extras/commit/c1fd3fd5cbd8a01ef01f10f2ec9c5c896e4eaa08

**Comment by motss** [comment]
Thanks a lot for adding it into the list. How long does the update perform? The reason I'm asking this  is because Chromium is already v63 but the one from the list is still the older version. Curious to know that.

**Comment by r15ch13** [comment]
If you need the v63 snapshots, I recommend installing the [chrlauncher](https://github.com/lukesampson/scoop-extras/blob/master/chrlauncher.json) and change `ChromiumType` in the `chrlauncher.ini` to `dev-official`. This way you always get the latest build.

Scoop is more intended for delivering relatively stable stuff :smile:

**Comment by motss** [comment]
I see.

> Scoop is more intended for delivering relatively stable stuff

This makes sense to me. Thanks for the clarification.
