### ISSUE TITLE
How to install binary that depends on Windows version ?

### ISSUE THREAD

**Issue by sestegra** [lukesampson/scoop#1653]
For instance, in order to install PowerShell Core, I need to detect Windows version.
https://github.com/PowerShell/PowerShell/releases

**Comment by r15ch13** [comment]
Currently the only way would be to create multiple manifests:
powershell6-win10.json
powershell5-win7.json

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.
