### ISSUE TITLE
wkhtmltopdf installation error

### ISSUE THREAD

**Issue by ruv** [lukesampson/scoop#1659]
The command `scoop install wkhtmltopdf` produces the following error message:

> Installing 'wkhtmltopdf' (0.12.4).
> Unable to connect to the remote server
> URL http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_msvc2015-win64.exe is not valid
> 

It seems that **wkhtmltopdf** binaries are not hosted [on `download.gna.org`](https://github.com/lukesampson/scoop/blob/d6835f236d649389eb06a04ea30660dc470740f6/bucket/wkhtmltopdf.json#L21) anymore, but on GitHub — see [download webpage](https://wkhtmltopdf.org/downloads.html): "All downloads are hosted via GitHub releases".

**Comment by r15ch13** [comment]
Fixed!
