### ISSUE TITLE
Error installing curl

### ISSUE THREAD

**Issue by mattpangaro** [lukesampson/scoop#1661]
Tried updating, then fully removed and cleared cache. I get the following when trying to install curl:

Installing 'curl' (7.55.1).
curl-7.55.1-win64-mingw.7z (1.9 MB) [=========================================================================] 100%
Checking hash of curl-7.55.1-win64-mingw.7z... Hash check failed for 'https://dl.bintray.com/vszakats/generic/curl-7.55.
1-win64-mingw.7z'.
Expected:
    7602ab36358787378514a9aa2e2e065e0c6055c5121efafc6603cb37e4ad07f4
Actual:
    50fc0fda8487b56854884585b27d6453877d4aa2984eb9743a2a581fcb285bbc

Environment:
Window8, 64-bit.

**Comment by r15ch13** [comment]
Fixed with 733767ca21c7716cd51d2af4cda700fbb718e7e9 please run `scoop update` and try again

**Comment by mattpangaro** [comment]
Awesome, thanks. Works perfectly now!
