### ISSUE TITLE
request: hyper-terminal

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#1663]
can you add https://github.com/zeit/hyper to any bucket?

thx.

**Comment by matthewjberger** [comment]
I can make the manifest in the morning if no one beats me to it

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by r15ch13** [comment]
There was something with their installer that kept me from adding it. But I can't remember what it was... 😂

**Comment by matthewjberger** [comment]
I've made the manifest but I can't seem to make a shortcut to the executable because the `post_install` script runs _after_ the `shortcuts` section is run. At the moment a `script` block can't be chained in the `installer` section to run after a regular installer invocation like this:

```
    "installer": {
    	"file": "hyper-setup.exe",
    	"args": "--silent"
    },
```
I'll upload the manifest in a bit.

**Comment by r15ch13** [comment]
Did you try the [hyper-1.3.3-full.nupkg](https://github.com/zeit/hyper/releases/download/1.3.3/hyper-1.3.3-full.nupkg) which is a simple zipfile with the windows stuff in it?

**Comment by matthewjberger** [comment]
No, I didn't realize it was just a zipfile. I'll try that out now!

**Comment by r15ch13** [comment]
This should work 😀 
```json
{
    "version": "1.3.3",
    "license": "MIT",
    "url": "https://github.com/zeit/hyper/releases/download/1.3.3/hyper-1.3.3-full.nupkg#/dl.7z",
    "homepage": "https://hyper.is",
    "hash": "1b51d923e6e2bf03389056bd75d894321dd0db7d5fc365fb038101cc309be767",
    "extract_dir": "lib\\net45",
    "shortcuts": [
        [
            "Hyper.exe",
            "Hyper"
        ]
    ],
    "checkver": {
        "github": "https://github.com/zeit/hyper"
    },
    "autoupdate": {
        "url": "https://github.com/zeit/hyper/releases/download/$version/hyper-$version-full.nupkg#/dl.7z",
        "extract_dir": "lib\\net45"
    }
}
```

**Comment by matthewjberger** [comment]
Brilliant! That worked properly.

**Comment by r15ch13** [comment]
@matthewjberger Awaiting a PR 😄 
I auto generate my GitHub activity via auto-pr.ps1 😁

**Comment by r15ch13** [comment]
Closed with this https://github.com/lukesampson/scoop/pull/1664, but moved it to the extras bucket with https://github.com/lukesampson/scoop-extras/commit/28e84a6007cbea78a753bd0de2505294c8bb54d8
