### ISSUE TITLE
qemu has the wrong url to download

### ISSUE THREAD

**Issue by yulius-fxpal** [lukesampson/scoop#1677]
> % scoop install qemu
> Installing 'qemu' (2.10.0-rc3).
> The remote server returned an error: (404) Not Found.
> URL https://qemu.weilnetz.de/w64/qemu-w64-setup-20170816.exe#/dl.7z is not valid

Url showld be
http://qemu.weilnetz.de/w64/qemu-w64-setup-20170824.exe

See here for a list of files
https://qemu.weilnetz.de/w64/

**Comment by r15ch13** [comment]
Your scoop bucket is out of date, please run `scoop update` and try it again.

**Comment by yulius-fxpal** [comment]
Sorry for the trouble.  Thanks for the help.
