### ISSUE TITLE
Hanbrake & hanbrake-cli inverted architecture on manifest + kitty doesn't install

### ISSUE THREAD

**Issue by pulse-wave** [lukesampson/scoop#1679]
I discoverd scoop since a couple of days and I love it! great piece of software.

I've found a couple of issues with some app manifests though:
- **handbrake** (extras bucket) and **handbrake-cli** (main bucket) 
they have architecture installers inverted, the url for 64bit downloads 32bit installer and vice versa.

Could you please check them?

The second app giving me trouble is: 
- **kitty** (extras bucket) 
trying install it gives me this error:

Installing 'kitty' (0.69.0.2).
The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
URL https://www.fosshub.com/KiTTY.html/kitty_portable.exe is not valid

(not big issue since I got rid of the GUIs and went with openssh, but I thought to advise you, if you want to check that too)

**Comment by r15ch13** [comment]
The kitty problem can be resolved by opening the internet explorer and run the first-launch configuration like the error message says 😁 

The Handbrake problem is resolved now.

**Comment by pulse-wave** [comment]
well I'm dumb :°D sorry about the ie error, I just remembered I deactivated my ie on windows :D that's why :D sorry about that great for the the handbrake update!! thanks!
