### ISSUE TITLE
mpv.com not present in shims for mpv app

### ISSUE THREAD

**Issue by pulse-wave** [lukesampson/scoop#1680]
- mpv (extras bucket) request\issue:

Mpv works great, but it misses the shims\shortcut for the mpv.com (mpv cli), right now it creates the shortcut just for mpv.exe without the chance to use mpv.com too

- mpv.exe from cmd openup the mpv player (already implemented)
- **mpv.com** from cmd gives access to the cli for mpv (**missed**)

Could be useful to create shims for mpv.com (mpv cli)

**Comment by r15ch13** [comment]
The only way to create a shim for `mpv.com` is to manipulate the `mpv.exe` shim.

Could you try this?
- create a copy of the [mpv.json](https://github.com/lukesampson/scoop-extras/blob/master/mpv.json)
- add the following `post_install` script to the manifest
    ```json
    "post_install": "
        (Get-Content \"$(shimdir $global)\\mpv.ps1\").replace('mpv.exe','mpv.com') | Out-File \"$(shimdir $global)\\mpv.ps1\" -encoding utf8
        (Get-Content \"$(shimdir $global)\\mpv.shim\").replace('mpv.exe','mpv.com') | Out-File \"$(shimdir $global)\\mpv.shim\" -encoding utf8
    ",
    ```
- install it via `scoop install .\path\to\mpv.json`

Does this result in the expected behavior for `cmd`/`powershell`?

**Comment by pulse-wave** [comment]
I played around with the code to see if I could manage to have both mpv.exe and mpv.com work from cli, I tried a lot of different combination but it seems that your hack it's the only one that "kind" of works.

I say kind, because right now with your hack here is what happens:

- from **cmd\powershell**: when you run **mpv **or** mpv.exe** it gives you the mpv cli argument list 

like when you run mpv.com with the "regular mpv installation" (not the scoop one), but the possibility to run the gui from cmd\powershell is gone now.

At least it creates mpv.exe (real gui executable) in the user\scoop\apps\mpv\current directory so the user can create a shortcut to that in the desktop or whatever to launch the gui too.

Doing the shortcut trick you have both options now to choose, if that what you tried to achieve yes it works and it's better than have no cli choice.

I was thinking though a more "clean" way to do it and have two separate commands in the cmd\powershell like the "real installation" does

so if you run from cmd\powershell mpv or mpv.exe it opens up the mpv gui and if you run mpv.com it gives you the mpv cli instead + shortcut to mpv.exe like now.

I thought that because the zip file already contains both executables (mpv.exe mpv.com) was just a matter of create:

    "bin": [
        "mpv.exe",
        "mpv.com"
],

but it doesn't work I was expecting something like what ffmpeg does in it's manifest for ffmpeg ffprobe etc.
Am I missing something here?
Or maybe my mistake is that bin expects a list of only *.exe files and doesn't recognize .com is it?
I'm a bit confused.

Indeed if yours is the only hack possible (and it looks to be from all my tests) is better than the original one, at least you can manage to have both things with the shortcut, I think.

Please tell me if I'm not clear enough with what happened

**Comment by r15ch13** [comment]
Yes *.com files are not supported by the [shim()](https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L199) function.

Should I add the `post_install` hack?

**Comment by pulse-wave** [comment]
Yes thanks Richard to me seems the best solution have a shortcut and have the cmd line is it worth it to my humble opinion.

Especially for all the cmd-fu out there!

Thanks!
