### ISSUE TITLE
scoop status fatal: ambiguous argument

### ISSUE THREAD

**Issue by pulse-wave** [lukesampson/scoop#1684]
trying to run scoop status gives me a git warning:

```
PS D:\Users\pulse> scoop status
fatal: ambiguous argument 'HEAD..origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Scoop is up to date.
Everything is ok!
PS D:\Users\pulse>
```

**Comment by r15ch13** [comment]
Did you somehow modify the git repository in `D:\Users\pulse\scoop\apps\scoop\current`?

**Comment by r15ch13** [comment]
Oh, it uses `HEAD..origin/` instead of `HEAD..origin/master`.
Normally the branch will be fetched via `scoop config SCOOP_BRANCH`.
What's the content of the file `%userprofile%/.scoop`?

**Comment by pulse-wave** [comment]
this is the content of .scoop file
```

D:\Users\pulse
λ cat %userprofile%/.scoop
ï»¿{
    "lastupdate":  "\/Date(1504207068440)\/"
}
```

The output of 
`git log "HEAD..origin/master" --oneline`
instead gives me nothing back

```
PS D:\Users\pulse\scoop\apps\scoop\current> git log "HEAD..origin/master" --oneline
PS D:\Users\pulse\scoop\apps\scoop\current>
```

**Comment by r15ch13** [comment]
What is the output of `git branch` and `git remote`?

**Comment by pulse-wave** [comment]
```
> git branch
* master
> git remote
origin
```

**Comment by r15ch13** [comment]
Hm, `scoop update` should add `SCOOP_BRANCH` and `SCOOP_REPO` to the `%userprofile%/.scoop` file.
Does `scoop update` show some weird output?

**Comment by pulse-wave** [comment]
nope update goes smooth I've tried again and everything went good but still scoop status complains about 'HEAD..origin/' and in the .scoop file doesn't appear to be track of SCOOP_BRANCH and SCOOP_REPO:

```
PS D:\Users\pulse> scoop update
Updating Scoop...
Updating 'extras' bucket...
Updating 'versions' bucket...
Scoop was updated successfully!
PS D:\Users\pulse> cat .\.scoop
{
    "lastupdate":  "\/Date(1504340270450)\/"
}
PS D:\Users\pulse> scoop status
fatal: ambiguous argument 'HEAD..origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Scoop is up to date.
Updates are available for:
    youtube-dl: 2017.08.27.1 -> 2017.09.02
Everything is ok!
PS D:\Users\pulse>
```

at least is warning me about new updates as you can see (youtube-dl). I guess I will try to delete\uninstall everything and start again from scratch to see if something change, I'm out of ideas, I will report back if that succedded

**Comment by pulse-wave** [comment]
Ok I have unistalled everything and start up from scratch, the problem is gone.

```
D:\Users\pulse
λ scoop update
Updating Scoop...
Scoop was updated successfully!

D:\Users\pulse
λ scoop status
Scoop is up to date.
Everything is ok!
```

Unfortunately I didn't understood what caused it, maybe something went bad the first installation.
But now everything works, you can close this issue too :)

P.s. I want to go a bit off topic without creating another issue just a fast question:

I would like to contribute to this project creating some manifests and maybe ask for a pull to extras bucket for software like GSmartControl (smartmoontool gui) crystaldisk info, icaros, imageglass etc. etc.

Before creating them I'm wondering though, what about autoupdates of software (I'm not talking about autoupdate manifest funcion, but the real autoupdate of some software, like hanbrake has) 

- what happens when a program will autoupdate itself instead of through scoop update function. Will it conflict with scoop?

- what about *.msi/*.exe#/dl.7z do they change installation directory\modify scoop one?

- what's the policy about that? is that "final user" competence\problem to turn "internal auto updates" off from programs or is it something I have to address inside the manifest? Or does them make no difference to leave them on and does scoop will adjust itself to the changes?

**Comment by r15ch13** [comment]
`#/dl.7z` simply renames the .msi/.exe file to `dl.7z` which then will simply get extracted.

There should be no issues with self-updating programs, they will simply get overwritten a soon `scoop update <app>` is run. Programs just update themselves normally to the `current` directory.

e.g. :

```
λ ls -l
total 12
drwxr-xr-x 1 user 197609  0 Sep  1 13:46 2.1/
lrwxrwxrwx 1 user 197609 26 Sep  1 13:48 current -> /d/scoop/apps/x/2.1/
```

1. version 2.1 updates itself to 2.2
   - directory `scoop\apps\x\2.1` now contains version 2.2
   - `current` links to 2.1 directory
2. version 2.1 is now updated via `scoop update x` to 2.2
   - directory `scoop\apps\x\2.2` gets created
   - `current` links to 2.2 directory
   - directory 2.1 contains also version 2.2

Result:
```
λ ls -l
total 12
drwxr-xr-x 1 user 197609  0 Sep  1 13:46 2.1/
drwxr-xr-x 1 user 197609  0 Sep  1 13:47 2.2/
lrwxrwxrwx 1 user 197609 26 Sep  1 13:48 current -> /d/scoop/apps/x/2.2/
```

**Comment by pulse-wave** [comment]
Ok then I will prepare my manifests and ask for pull in extras then thanks for the clarification

**Comment by andreyrd** [comment]
I'm having the exact same issue, and I'd like to avoid having to reinstall all of scoop.

What should the correct value of `SCOOP_BRANCH` in `.scoop` be? Mine is also missing the value.

**Comment by r15ch13** [comment]
There should be two values:
`SCOOP_BRANCH`: `master`
`SCOOP_REPO`: `https://github.com/lukesampson/scoop`

**Comment by pulse-wave** [comment]
Also be sure not have modified the .scoop file's property in any way. 
I noticed that make the .scoop file hidden (by right click-> properties) in windows "corrupts" the file and presents you the same issue, toggling back the hidden property removes the issue if that the case

**Comment by andreyrd** [comment]
Awesome, thank you!

Changing my `.scoop` file contents from
```
{
    "lastupdate":  "\/Date(1504987945599)\/"
}
```
to
```
{
    "lastupdate":  "\/Date(1504987945599)\/",
	"SCOOP_BRANCH": "master",
	"SCOOP_REPO": "https://github.com/lukesampson/scoop"
}
```
fixed it.

**Comment by r15ch13** [comment]
Should be fixed with https://github.com/lukesampson/scoop/commit/c86c727084949ef4f18b63687c4cf6dea52bf1ac
