### ISSUE TITLE
Feature Request: Add command to re-generate PATH

### ISSUE THREAD

**Issue by tech4him1** [lukesampson/scoop#1685]
Occasionally, an external app installer (or me) will erase my PATH variable (😨), causing all of my `scoop` apps to stop working. It would be nice if I could have scoop re-add all the PATH entries for shims, persisted directories, and other files without having to reinstall each one.

**Comment by r15ch13** [comment]
`scoop reset <app>` should do the trick.

But maybe you should fix the "accidentally erasing the PATH" thing 😁

**Comment by tech4him1** [comment]
Yeah, I know. The problem was that `scoop reset <app>` wasn't actually resetting all the paths (like the ones for persist stores and other areas that aren't standard).

**Comment by Guard13007** [comment]
Scoop only adds one value to your PATH, which is the directory with shims in it. You should not need to run `scoop reset` on anything, just re-add the path to shims. Which, as far as I know, scoop doesn't have a command for.

**Comment by tech4him1** [comment]
Closing this, as I found the problem with `scoop reset` and will be filing separately.
