### ISSUE TITLE
OpenSSH - Trouble setting agent

### ISSUE THREAD

**Issue by NemoStein** [lukesampson/scoop#1686]
I'm not sure if my problem was already discussed in the issues (there are multiple issues openssh related), but I'm having a hard time figuring out how to properly set up my ssh-agent to handle my keys.

If I put a `id_rsa` (and `id_rsa.pub`) into the `.ssh` folder (inside the `scoop/apps`, not in `users/myuser/.ssh`) I can connect to some SSH server (in fact, I'm using Mercurial/Bitbucket), but I always get asked to put my password.  
"_No problem, I'll set the ssh-agent_" I said! But there is something wrong...  
I know that scoop doesn't handle services (and I love this! Thanks for not messing with my system), so I run the ssh-agent, which gives me the `SSH_AUTH_SOCK` and `SSH_AGENT_PID`, but PowerShell doesn't keep those vars, making it impossible to `ssh-add` to connect.
Then, I tried `ssh-agent ssh-add path/to/my/key`, which worked! The key appeared to be successfully loaded and my password is asked, but as soon as I tried to connect to SSH server the ssh-agent crashes (it simply disappears from task manager) and the connection with the server fails.

"The interwebz" doesn't help, most people uses Github's "Git for Windows", PuTTY (as I was, before finding out about scoop last week and changing my whole workspace) or even the git bash... I don't know what else I can try now. =/

Any help is appreciated!

**Comment by r15ch13** [comment]
Did you try [posh-git](https://github.com/dahlbyk/posh-git)?
It has built-in [functions ](https://github.com/dahlbyk/posh-git/wiki/Posh--Git-Module-Functions)to start/stop the ssh-agent: 
Install it via: [powershellgallery.com](https://www.powershellgallery.com/packages/posh-git/)

**Comment by NemoStein** [comment]
As I said, I was using PuTTY before and, if I can't make openssh to work, I rather go back to PuTTY instead of using yet another bundled tool... I don't want to install some SuperTool™+ssh (like git-with-openssh, git bash, posh-git, Git for Windows and such) just because of SSH.

**Comment by r15ch13** [comment]
As long `ssh-agent` doesn't set the environment variables itself, I think you're out of luck getting it to work without other tools.
Maybe [PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases) might work for you. Unfortunately, it's not ready for production use right now.
But I couldn't try it myself, without breaking my current dev setup 😞

**Comment by NemoStein** [comment]
Thanks, @r15ch13, I'll fight PowerShell a bit longer before falling back to PuTTY again...

**Comment by Guard13007** [comment]
`scoop install git-with-openssh`

For some reason unknown to me, that package sets up the ssh-agent to run everytime and be accessible, while installing `openssh` doesn't.

**Comment by avluis** [comment]
@NemoStein Can you check your user env vars and see if you have a `HOME` variable set.
Some of these tools won't be able to find that `.ssh` directory without that variable.

**Comment by NemoStein** [comment]
@avluis, UNBELIEVABLE! Such simple fix for a problem that plagues so many of us (as I said, there are multiple issues related to this problem).
I've just added a `HOME` env var pointing to `c:\users\my.user\`, copied my public/private key to `~/.ssh` folder (don't know if it was necessary) and it just worked...

I'd give you a hug if I could! Thx... ;D

**Comment by avluis** [comment]
@NemoStein I'm glad this has resolved your issue 😻

I don't currently have the time to create a PR, but if the issues you were having can be replicated with a new scoop install and certain packages, then it could be addressed by either having these packages set this variable (not the clean solution) or having scoop set it instead (IMO, the way to go) as part of its install.
