### ISSUE TITLE
Error installing Scoop on Windows 7

### ISSUE THREAD

**Issue by winteryoung** [lukesampson/scoop#1700]
My colleague has an error installing scoop:
```powershell
PS C:\Users\songwen> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
使用“1”个参数调用“DownloadString”时发生异常:“操作超时”
所在位置 行:1 字符: 46
+ iex (new-object net.webclient).downloadstring <<<< ('https://get.scoop.sh')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```
Translation:
* 使用“1”个参数调用“DownloadString”时发生异常:“操作超时” -> Exception invoking "DownloadString" using "1" argument: "Operation timeout"
* "所在位置 行:1 字符: 46" -> "Location Line:1 Char: 46"

**Comment by h404bi** [comment]
`Download install script timeout`, your colleague may be suffering GFW disease. The Scoop bootstrap script is hosting on Amazon CDN (cloudfront.net), try again behind a proxy.

**Comment by winteryoung** [comment]
No, it's not the network problem. He could open the URL.

**Comment by h404bi** [comment]
That exception shows timeout error. Have your colleague tried install scoop with proxy? Doesn't it work? :confused:

**Comment by winteryoung** [comment]
I may be wrong. I'll try it tomorrow. It does seem like the network problem.

**Comment by winteryoung** [comment]
![_15051802054335](https://user-images.githubusercontent.com/2392881/30304683-5129d81c-97a1-11e7-9922-7a1135cde273.png)
OK. Now I am sure it's not network problems. Translation:

Invoke-Expression: Invalid digit constant: 7
Location line:18 char:4

**Comment by h404bi** [comment]
Windows 7 default PowerShell is V2, Scoop require [PowerShell v3](http://lmgtfy.com/?q=windows+7+powershell+3), please upgrade your PowerShell.

duplicate #1524

**Comment by winteryoung** [comment]
OK, thx
