### ISSUE TITLE
Scoop update fails, leaves scoop broken: Windows 10

### ISSUE THREAD

**Issue by jmansion** [lukesampson/scoop#1702]
Scoop installed today.

C:\Users\james>scoop
Usage: scoop <command> [<args>]

Some useful commands are:

alias      Manage scoop aliases
bucket     Manage Scoop buckets
cache      Show or clear the download cache
checkup    Check for potential problems
cleanup    Cleanup apps by removing old versions
config     Get or set configuration values
create     Create a custom app manifest
depends    List dependencies for an app
export     Exports (an importable) list of installed apps
help       Show help for a command
home       Opens the app homepage
install    Install apps
list       List installed apps
reset      Reset an app to resolve conflicts
search     Search available apps
status     Show status and check for new app versions
uninstall  Uninstall an app
update     Update apps, or Scoop itself
which      Locate a program path

Type 'scoop help <command>' to get help for a specific command.

C:\Users\james>scoop update
Updating Scoop...
rm : Cannot remove item C:\Users\james\scoop\apps\scoop\current\supporting\validator\Newtonsoft.Json.dll: Access to the path 'Newtonsoft.Json.dll' is denied.
At C:\Users\james\scoop\apps\scoop\current\libexec\scoop-update.ps1:69 char:9
+         rm -r -force $currentdir -ea stop
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Newtonsoft.Json.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand

C:\Users\james>

**Comment by r15ch13** [comment]
This is related to this recent change: https://github.com/lukesampson/scoop/commit/82ec0fe7a11c1fc0db39cb51b671a5650c1252c8

Can you try reinstalling it, after closing all `powershell` instances?
Maybe this has fixed it. https://github.com/lukesampson/scoop/commit/12c8248439b262974ca22f4fd9394c9d507da6a0
Will try to test this tomorrow.

**Comment by winteryoung** [comment]
I tried to fresh install scoop on another computer of mine yesterday, and encountered this issue. Closing powershell and even rebooting the computer didn't help.

**Comment by winteryoung** [comment]
This has been fixed. I encountered once.
