### ISSUE TITLE
rustup package is broken

### ISSUE THREAD

**Issue by nanbdc** [lukesampson/scoop#1703]
> scoop install rustup
Couldn't find manifest for 'vcredist2015'

Windows 10 Home

**Comment by matthewjberger** [comment]
Run:

```
scoop bucket add extras
```

The `vcredist2015` manifest is in the [extras bucket](https://github.com/lukesampson/scoop-extras)

@r15ch13 Should we move the rustup manifest to the extras bucket?

**Comment by nanbdc** [comment]
Thanks! It seems to me that, at minimum, the error message should point out the need to add the extras bucket (or even do so automatically).

**Comment by r15ch13** [comment]
Fixed the `depends` property for rustup and improved the error message https://github.com/lukesampson/scoop/commit/567a3b926910a343f28fd14a7443c7c9a148fc95

**Comment by comp500** [comment]
This seems to break `scoop status`, as it says that a dependency is required when it is not.

![image](https://user-images.githubusercontent.com/1138417/35748621-930a5458-0846-11e8-8b7b-024fad42c9a1.png)
![image](https://user-images.githubusercontent.com/1138417/35748718-ddf4cc14-0846-11e8-966d-aa603b2b5cf7.png)


It works fine with just `cemu`, but `comp500/cemu` breaks. [core.ps1](https://github.com/lukesampson/scoop/blob/af41fc6efb0fdf65943b8639ca5d44a406445452/lib/core.ps1#L104) and [depends.ps1](https://github.com/lukesampson/scoop/blob/36dc7a880c373ec20b05a0d10308cc061112c5f3/lib/depends.ps1#L45) suggest that `scoop status` only checks whether the given dependency is installed, and doesn't remove the bucket from the depends statement in the manifest before doing this check.

This isn't a problem for my packages as both packages are in the same bucket (does that cause the problem?) so I can just remove the `comp500/`, but this may be a problem for other packages.
