### ISSUE TITLE
SourceTree (2.1.11.0) install is not working

### ISSUE THREAD

**Issue by andiskrauklis** [lukesampson/scoop#1710]
λ scoop install sourcetree
Installing 'sourcetree' (2.1.11.0).
Loading SourceTreeSetup-2.1.11.0.exe from cache
Checking hash of SourceTreeSetup-2.1.11.0.exe... ok.
Extracting... done.
Running pre-install script...

ERROR: The system cannot find the file specified.
C:\Users\user.name\scoop\apps\sourcetree\2.1.11.0\SourceTree-2.1.11.0-full.nupkg

System ERROR:
The system cannot find the file specified.
Linking ~\scoop\apps\sourcetree\current => ~\scoop\apps\sourcetree\2.1.11.0
Creating shim for 'sourcetree'.
Can't shim 'lib/net45/sourcetree.exe': File doesn't exist.

λ pwd
C:\Users\user.name\scoop\apps\sourcetree\2.1.11.0

λ ls -l
total 18509
-rw-r--r-- 1 user.name 1049089       81 Aug 12 00:41 RELEASES
-rw-r--r-- 1 user.name 1049089 17157949 Aug 12 00:39 <b>SourceTree-2.1.11-full.nupkg</b>
-rwxr-xr-x 1 user.name 1049089  1783624 Aug 12 00:41 Update.exe*
-rw-r--r-- 1 user.name 1049089     5397 Apr 12 16:15 background.gif

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/5298d6e1bb0721c4de01b652ec42bf509e6b8525
