### ISSUE TITLE
scoop treat install failing as success

### ISSUE THREAD

**Issue by xialvjun** [lukesampson/scoop#1712]
scoop version: git commit    a7f1847.......

### ~~not use cache~~
**~~behavior~~**:
~~the download function in scoop is very slow, so I use some download tools like `aria2c` etc to download packages and place it into the directory `cache` and then `scoop install <package>`. But scoop still try to download the file as the package manifest even the downloaded file is totally the same as the will be downloaded file.~~

**~~expected behavior~~**:
~~use the cache.~~
Sorry, I forgot to rename the downloaded file to `<package>#<version>#<https://xxxxx>` pattern...

### treat install failing as success
**behavior**:
I have installed `shadowsocks 4.0.4`. I run `scoop update shadowsocks` and scoop made the directory `$HOME/scoop/apps/shadowsocks/${the version will be installed like 4.0.6}` .... And then, network happens wrong and download failed, but scoop treat it has installed `shadowsocks` success...I rerun `scoop update shadowsocks`, but scoop tells me `shadowsocks 4.0.6 has been installed`....I must delete the directory `4.0.6` then rerun `scoop update shadowsocks`.

**expected behavior**:
scoop should download file and extract to a tempdir and then rename the tempdir to `4.0.6`...

**Comment by rasa** [comment]
You need to always uninstall after a failed install. We’re working on fixing this. Thanks for the report.
