### ISSUE TITLE
scoop install windirstat   <- Couldn't find manifest for 'windirstat'.

### ISSUE THREAD

**Issue by keneo** [lukesampson/scoop#1717]

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop-extras/commit/60b269c6afc3c68ccc7cdc6004d6830462dcd51f
Run `scoop bucket add extras` and `scoop install windirstat`
Alternative: [wiztree](https://github.com/lukesampson/scoop-extras/blob/master/wiztree.json)

**Comment by keneo** [comment]
awsome! thx @r15ch13
