### ISSUE TITLE
installation of git and gradle is failing 

### ISSUE THREAD

**Issue by abhilashmental1** [lukesampson/scoop#1721]
Type 'scoop help <command>' to get help for a specific command.
PS C:\Users\CHITTA> scoop install gradle
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'gradle' (4.2).
gradle-4.2-bin.zip (67.8 MB) [=============================================================================
Checking hash of gradle-4.2-bin.zip... ok.
Extracting... done.
Linking ~\scoop\apps\gradle\current => ~\scoop\apps\gradle\4.2
% : The term 'cmd' is not recognized as the name of a cmdlet, function, script file, or operable program. C
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\CHITTA\scoop\apps\scoop\current\libexec\scoop-install.ps1:107 char:9
+ $apps | % { install_app $_ $architecture $global $suggested $use_cache }
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cmd:String) [ForEach-Object], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand

PS C:\Users\CHITTA> scoop install git
Installing '7zip' (16.04).
7z1604-x64.msi (1.6 MB) [==================================================================================
Checking hash of 7z1604-x64.msi... ok.
Extracting... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\16.04
% : The term 'cmd' is not recognized as the name of a cmdlet, function, script file, or operable program. C
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\CHITTA\scoop\apps\scoop\current\libexec\scoop-install.ps1:107 char:9
+ $apps | % { install_app $_ $architecture $global $suggested $use_cache }
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cmd:String) [ForEach-Object], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by abhilashmental1** [comment]
any1 pls reply to this

**Comment by yigitemres** [comment]
@abhilashmental1 can you run `set-ExecutionPolicy Unrestricted` or `set-ExecutionPolicy AllSigned` from elevated command prompt and try again?

**Comment by r15ch13** [comment]
Did you set an alias for `cmd`? https://github.com/lukesampson/scoop/issues/1724 seems to be similar problem with `Set-Alias`

**Comment by huucp** [comment]
@r15ch13 I got this error:
cmd : The term 'cmd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\scoop\apps\scoop\current\lib\install.ps1:739 char:5
+     cmd /c mklink /j $currentdir $versiondir | out-null
+     ~~~
    + CategoryInfo          : ObjectNotFound: (cmd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

attrib : The term 'attrib' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\User\scoop\apps\scoop\current\lib\install.ps1:740 char:5
+     attrib $currentdir +R /L
+     ~~~~~~
    + CategoryInfo          : ObjectNotFound: (attrib:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Can you point me a solution?

**Comment by r15ch13** [comment]
@huucp
Your Powershell can't find `cmd.exe` and `attrib.exe`. Maybe something is wrong with your `%PATH%`.
Maybe related to https://github.com/lukesampson/scoop/issues/1817
`C:\Windows\system32` has to be in your `%PATH%`

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.
