### ISSUE TITLE
failed to install packages using scoop command, what's wrong?

### ISSUE THREAD

**Issue by chapgaga** [lukesampson/scoop#1722]
PS D:\> scoop install curl
Installing '7zip' (16.04).
7z1604.msi (1.2 MB) [=================================================] 100%
Checking hash of 7z1604.msi... Exception calling "Create" with "1" argument(s)
"Operation is not supported on
 this platform."
At C:\Users\chapgaga\scoop\apps\scoop\current\lib\install.ps1:454 char:5
+     $alg = [system.security.cryptography.hashalgorithm]::create($algn ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PlatformNotSupportedException

You cannot call a method on a null-valued expression.
At C:\Users\chapgaga\scoop\apps\scoop\current\lib\install.ps1:461 char:9
+         $alg.dispose()
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\chapgaga\scoop\apps\scoop\current\lib\install.ps1:457 char:9
+         $hexbytes = $alg.computehash($fs) | % { $_.tostring('x2') }
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Hash check failed for 'http://7-zip.org/a/7z1604.msi'.
Expected:
    d9b62c0ed0eb48d2df86d8b83394048414a2a4e1d64a50adb9abcff643471d20
Actual:

**Comment by chapgaga** [comment]
i am using PowerShell-6.0.0-beta.7-win-x86

**Comment by r15ch13** [comment]
@chapgaga can you try if this https://github.com/lukesampson/scoop/pull/1725 works for you?

**Comment by r15ch13** [comment]
Should be fixed now.
