### ISSUE TITLE
Selenium Server and browser drivers

### ISSUE THREAD

**Issue by gigaimage** [lukesampson/scoop#1723]
I would like to add following manifest in bucket. 

- selenium.json (for selenium-server-standalone-x.y.jar), 
- chromedriver.json (chromedriver.exe), 
- geckodriver.json (geckodriver.exe),
- phantonjs.json (phantonjs.exe).
- GetGnuWin32.exe (https://sourceforge.net/projects/getgnuwin32/)

How would I go about it? Is there a manifest generator script?

**Comment by h404bi** [comment]
There is no manifest generator, you can read the wiki pages to learn how to create your manifests, or even build your own bucket.

https://github.com/lukesampson/scoop/wiki/App-Manifests
https://github.com/lukesampson/scoop/wiki/Buckets

**Comment by r15ch13** [comment]
* chromedriver is already available
* phantomjs is already available
* geckodriver has been added https://github.com/lukesampson/scoop/commit/45a6252766e1861705442a62ff54985b16779909
* selenium has been added https://github.com/lukesampson/scoop/commit/0a2c710452e91be9193bc8f6355da3dd7d9c468b

**Comment by gigaimage** [comment]
@r15ch13  Thank you very much for adding selenium and geckodriver.
