### ISSUE TITLE
Bug on install gradle 4.2

### ISSUE THREAD

**Issue by templarfelix** [lukesampson/scoop#1726]
On install return error 

> 
> Checking hash of gradle-4.2-bin.zip... Hash check failed for 'https://services.gradle.org/distributions/gradle-4.2-bin.zip'.
> Expected:
>     515dd63d32e55a9c05667809c5e40a947529de3054444ad274b3b75af5582eae
> Actual:
>     3fd2ecbfb763ae9b699754cd55f0deaa77f7c806403f97a33298b877900ee015

**Comment by r15ch13** [comment]
`515dd63d32e55a9c05667809c5e40a947529de3054444ad274b3b75af5582eae` is the correct hash. Please run `scoop cache rm gradle` and try again.

**Comment by templarfelix** [comment]
resolve with remove cache.
