### ISSUE TITLE
 Couldn't resolve proxy 'none'

### ISSUE THREAD

**Issue by teelicht** [lukesampson/scoop#1728]
I removed the proxy I previously configured in scoop via `scoop config proxy none` as described in the wiki. However, on scoop update I now get the following output:
`Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Couldn't resolve proxy 'none'
Scoop update failed.`

**Comment by teelicht** [comment]
same result :(
i'm on win 10 pro

**Comment by h404bi** [comment]
ah, that's odd, or you can just edit the config file, `$HOME\.scoop`
```
{
    "proxy":  "",
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
```
remove the proxy attribute.

**Comment by r15ch13** [comment]
`scoop config rm proxy` is the right way to delete settings.

**Comment by teelicht** [comment]
`scoop config rm proxy` worked! please update the wiki. thanks for your support!
