### ISSUE TITLE
Can't shim 'MongoDB\Server\3.4\bin\bsondump.exe': File doesn't exist.

### ISSUE THREAD

**Issue by DChandlerP** [lukesampson/scoop#1729]
scoop install mongodb
Installing 'mongodb' (3.4.9).
Linking ~\scoop\apps\mongodb\current => ~\scoop\apps\mongodb\3.4.9
Creating shim for 'bsondump'.
Can't shim 'MongoDv\Server\3.4\bin\bsondump.exe': File doesn't exist.

Copy and paste wasn't working well for me so I typed out those last two lines. Any help is appreciated.

**Comment by r15ch13** [comment]
Maybe some program blocked it (antivirus?). The `bsondump.exe` is definitely available in mongodb 3.4.9
Did you try redownloading it? Remove the cached file with `scoop cache rm mongodb`

**Comment by DChandlerP** [comment]
I don't know... but I did just try uninstalling mongodb then reinstalling it. Now it works so....
Regardless, I plan to donate something to this project when I get home. It's definitely a time saver for me.
