### ISSUE TITLE
openssh install failed

### ISSUE THREAD

**Issue by dmi3mis** [lukesampson/scoop#1732]
C:\>scoop install openssh
Installing 'openssh' (5.4p1-1).
openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma (652 B) [===================================================] 100%
Loading openssh-5.4p1-1-msys-1.0.13-lic.tar.lzma from cache
Loading msysCORE-1.0.13-2-msys-1.0.13-bin.tar.lzma from cache
Loading zlib-1.2.3-2-msys-1.0.13-dll.tar.lzma from cache
Loading libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma from cache
Loading libopenssl-1.0.0-1-msys-1.0.13-dll-100.tar.lzma from cache
Checking hash of openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma... Hash check failed for 'https://sourceforge.net/projects/mingw/files/MSYS/Extension/openssh/openssh-5.4p1-1/openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma'.
Expected:
    8c8e6a030a34c341394bb8b9f1760743468a8cc5e4244efc34f7ab3cd3e67b64
Actual:
    7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf

**Comment by r15ch13** [comment]
`8c8e6a030a34c341394bb8b9f1760743468a8cc5e4244efc34f7ab3cd3e67b64` is correct.
Run `scoop cache rm openssh` and try again.

**Comment by dmi3mis** [comment]
C:\Users\Administrator.ADATUM>scoop install openssh
Updating Scoop...
Scoop was updated successfully!
It looks like a previous installation of openssh failed.
Run 'scoop uninstall openssh' before retrying the install.

C:\>scoop uninstall openssh
Uninstalling 'openssh' (5.4p1-1).
'openssh' was uninstalled.

C:\>scoop cache rm openssh
C:\>scoop install openssh
Installing 'openssh' (5.4p1-1).
Unable to connect to the remote server
URL https://sourceforge.net/projects/mingw/files/MSYS/Extension/openssh/openssh-5.4p1-1/openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma is not valid

**Comment by r15ch13** [comment]
Does the download from a browser? Maybe you got redirected to a broken mirror. 😕

**Comment by orielsy** [comment]
Unable to install openssh. I've struggled with installing Scoop and now OpenSSH. 

Sorry for the lack of details. I'm unsure as to what any of these errors mean. I had to use "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12" to install Scoop today and now OpenSSH is not installing. Not sure if related but worth noting.

PS C:\Users> scoop install openssh
Installing 'openssh' (5.4p1-1) [64bit]
openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma (652 B) [============================================================] 100%
openssh-5.4p1-1-msys-1.0.13-lic.tar.lzma (652 B) [============================================================] 100%
msysCORE-1.0.13-2-msys-1.0.13-bin.tar.lzma (652 B) [==========================================================] 100%
zlib-1.2.3-2-msys-1.0.13-dll.tar.lzma (652 B) [===============================================================] 100%
libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma (652 B) [========================================================] 100%
libopenssl-1.0.0-1-msys-1.0.13-dll-100.tar.lzma (652 B) [=====================================================] 100%
Checking hash of openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma... Hash check failed for 'https://sourceforge.net/projects/mingw/files/MSYS/Extension/openssh/openssh-5.4p1-1/openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma'.
Expected:
    8c8e6a030a34c341394bb8b9f1760743468a8cc5e4244efc34f7ab3cd3e67b64
Actual:
    7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf

**Comment by r15ch13** [comment]
@orielsy Maybe a SourceForge problem (they seem to appear a lot lately 😢), try it again and clear the cache: `scoop cache rm openssh`
