### ISSUE TITLE
mariadb update failed to persist

### ISSUE THREAD

**Issue by nueko** [lukesampson/scoop#1739]
the issue come when i update to mariadb 10.2.9, as `mysql_embedded.exe` not exists on that version.

I think we should use add path environment method as possible

**Comment by gnsngck** [comment]
It seems to me scoop should create shim to change MariaDB and MySQL through `reset`. If you won't install both, you may edit json file in bucket directory, delete creating shim part, and add path then install(I did so).

**Comment by lgraziani2712** [comment]
It happens with mariadb 10.2.10 also. I modified the mariadb.json  locally and removed `mysql_embedded.exe` and `mysql_client_test_embedded.exe` from the `bin` array, and the installation worked OK.

**Comment by nueko** [comment]
@gnsngck  always did after upgrade
