### ISSUE TITLE
scoop status command doesn't work for personnal manifest ?

### ISSUE THREAD

**Issue by mundusnine** [lukesampson/scoop#1742]
I have been trying to implement the autoupdate on an app manifest and when querying scoop update or scoop status my app wasn't considered. I was finally able to when I came accross a post by luke that said that to check you had to do : " ~/scoop/apps/scoop/current/bin/checkver -dir ./ godotengine" and if it returned : "godotengine: 2.1.4 (scoop version is 2.1.3) autoupdate available" you could then do the same command but add the -u parameter to autoupdate.

But what do we do when we want to have it considered in the scoop update and scoop status ? Query to be considered for the main or extras ? 

You can find the manifest in question here : https://github.com/mundusnine/audio-bucket

**Comment by r15ch13** [comment]
Did you add your repo as a bucket?
`scoop bucket add audio https://github.com/mundusnine/audio-bucket`
Now scoop update and status will query your bucket too.

**Comment by mundusnine** [comment]
Hi, 

Thank you for your response.
Yes I added my repo as a bucket before asking this question and status and update still didn't work.

**Comment by mundusnine** [comment]
I updated git(just in case) and rebooted cmd and still got the same thing.

**Comment by r15ch13** [comment]
In your repo godotengine is still on version 2.1.3 (this has to be updated to 2.1.4)

**Comment by mundusnine** [comment]
I know I just did that to test if the status or update would detect with the checkver directive that my version is not up to date. But do you mean that scoop update or status doesn't use checkver only the current installed version and the version in the repo ?

**Comment by r15ch13** [comment]
`scoop status` compares your installed version against the current copy of scoop and bucket repos on your machine. If these are not updated it will output wrong version information.
e.g.
* installed version: 2.1.2
* local scoop version: 2.1.3
* online repo version: 2.1.4
`scoop status` will show version 2.1.3
Running `scoop update` before `scoop status` is recommended (and enforced 3 hours)

`scoop update` just `git pull`s the main scoop repo to `~\scoop\apps\scoop\current` and every configured bucket to `~\scoop\buckets\<name>`

`bin\checkver` is only for maintenance and updating the manifests so they can be commited to the repo.

Example Workflow:
`.\bin\checkver -dir ./ * -u` (updates all manifest in the repo)
`git commit -m "Updated apps"`
`git push`
`scoop update`
`scoop status`
`scoop update <app>`

**Comment by mundusnine** [comment]
Ok thank you for the explanation. I understand now.

**(Enhancement request)** But shouldn't the checkver be checked by scoop automatically(say every 7 days). That way even if someone is not maintaining their repo the app users will still get the updates for the apps. It's not that I don't want to maintain my repo it's more that why need humans when the machine could do it itself. :)

**Comment by r15ch13** [comment]
For this case I use a docker service that runs `bin\auto-pr` every hour: https://github.com/r15ch13/Excavator
I want to create a docker image so anyone with a private scoop repo can run it with minimal setup. Currently it only supports the main, extras and versions bucket.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by mundusnine** [comment]
We should probably add Richard's explanation to the wiki so people can see how to do this easily and learn the workflow when having personal scoop repos

**Comment by rasa** [comment]
@mundusnine thanks!
