### ISSUE TITLE
Can scoop work with a local repo?

### ISSUE THREAD

**Issue by a59** [lukesampson/scoop#1749]
It would be useful to be able to do something like

'scoop bucket add C:\path_to_a_local_repo'

Is that possible?

**Comment by h404bi** [comment]
You can just create a custom bucket under scoop's bucket folder, create your app manifest then install your app from your local bucket.

```sh
$ cd ~\scoop\buckets\
$ mkdir <your_bucket_name>
$ cd <your_bucket_name>
$ New-Item your_app.json
$ scoop install <your_bucket_name>/<your_app>
```

**Comment by r15ch13** [comment]
@a59 yea it works with local repositories. Running `scoop update` just uses `git pull` to update the bucket.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by DrVektor** [comment]
İ didnt understand "New-Item" command. Becoz scoop unrecognize it.

**Comment by rashil2000** [comment]
New-Item is a PowerShell command

**Comment by DrVektor** [comment]
Thank you 😌
