### ISSUE TITLE
Fresh install is breaking.

### ISSUE THREAD

**Issue by bogen** [lukesampson/scoop#1756]
```sh
PS C:\Users\<snipped>\install-scoop> scoop list
Installed apps:

  7zip 16.04
  git 2.14.2.windows.2
  openssh 5.4p1-1

PS C:\Users\<snipped>\install-scoop> scoop install innounp
Updating Scoop...
mv : Access to the path 'C:\Users\<snipped>\scoop\apps\scoop\new' is denied.
At C:\Users\<snipped>\scoop\apps\scoop\current\libexec\scoop-update.ps1:70 char:9
+         mv $newdir $currentdir
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\<snipped>\scoop\apps\scoop\new:DirectoryInfo) [Move-Item], IOExcept
   ion
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

PS C:\Users\<snipped>\install-scoop> scoop list
& : The term 'C:\Users\<snipped>\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\<snipped>\scoop\shims\scoop.ps1:2 char:70
+ ... ion.expectingInput) { $input | & $path @args } else { & $path @args }
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\<snipped>...t\bin\scoop.ps1:String) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException
```

What would cause scoop to break like this? It was working for a couple days last week, then started breaking like that. I uninstalled it this morning (removed my user's scoop directory, as I could not remove via scoop), rebooted and installed again. Tried removing the directory and installing a afresh more than once, but it always starts breaking after a few package installs.
this time I installed openssh first (7zip was installed as a preqeq)
then I installed git and ran the environment command.
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which ssh)), 'USER')

did a scoop list, all was well, then it broke as I showed above.

**Comment by r15ch13** [comment]
It seems to have a problem with updating itself for the first time.
Try installing it. Close the console/powershell window. Run `scoop update`, close it again and then try installing innounp,

**Comment by bogen** [comment]
```powershell
PS C:\Users\<snipped>> scoop list
Installed apps:

  7zip 16.04
  cmder 1.3.2
  gcc 7.1.0
  git 2.14.2.windows.2
  gow 0.8.0
  innounp 0.46
  mercurial 4.3.3
  openssh 5.4p1-1
```
Alright, thanks, getting much further now. I had to install git before I could do a "scoop update"

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.
