### ISSUE TITLE
ERROR: The 'extras' bucket already exists. Use 'scoop bucket rm extras' to remove it.

### ISSUE THREAD

**Issue by IAMtheIAM** [lukesampson/scoop#1764]
Similar to [Issue 1758](https://github.com/lukesampson/scoop/issues/1758), when running `scoop bucket add extras`, once succeeds. If running it again, it exits with error `The 'extras' bucket already exists. Use 'scoop bucket rm extras' to remove it.`

Instead, it should only issue a warning and continue the script execution.

Basically, In my opinion scoop should only exit with an error when an actual error occurs, for any method, and otherwise just issue a warning.

**Comment by IAMtheIAM** [comment]
Hello?

**Comment by r15ch13** [comment]
Fixed

**Comment by IAMtheIAM** [comment]
Thank you!
