### ISSUE TITLE
How to add directory outside the install directory to PATH

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop#1765]
> env_add_path: Add this directory to the user's path (or system path if --global is used). The directory is relative to the install directory and must be inside the install directory.
*[App-Manifests#optional-properties](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties)*

Since `env_add_path` cannot deal with path outside the install directory. And I want to add directory like `%LOCALAPPDATA%\<app_path>` to the PATH, when the installation perform.

Is there any example or not?

**Comment by rasa** [comment]
Untested, but perhaps this would work:

````
"post_install": [
    "[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable]('PATH', 'User') + ';%LOCALAPPDATA%\\<app_path>' , 'User')"
],
````

**Comment by h404bi** [comment]
This looks inreversible when execute uninstallation.

**Comment by h404bi** [comment]
For who want this, you can use built-in function `add_first_in_path`.
