### ISSUE TITLE
How to config install path for global app?

### ISSUE THREAD

**Issue by ChinLong** [lukesampson/scoop#1770]
global app could be installed in ``C:\ProgramData\scoop\apps`` (by default).

how to install global app into ``D:\scoop\apps``?

just like set env `SCOOP` for user.

**Comment by asmgf** [comment]
@ChinLong, try setting `SCOOP_GLOBAL` environment variable.

**Comment by ChinLong** [comment]
@asmgf  it works. thanks :blush:
