### ISSUE TITLE
Why scoop can't install other version of Gradle

### ISSUE THREAD

**Issue by zhouhuacong** [lukesampson/scoop#1780]
I want to install gradle 4.2.1 and 3.3 in my pc, how to do that ?

**Comment by r15ch13** [comment]
You can install gradle 3.3 by running `scoop install gradle@3.3`
To switch between versions use the reset command:

```bash
# resets shims to 4.2.1
scoop reset gradle
# resets shims to 3.3
scoop reset gradle@3.3
```

**Comment by styfle** [comment]
Does that syntax work for all tools? The wiki says that scoop cannot install different versions of a tool in the comparison to Chocolatey.

**Comment by r15ch13** [comment]
@styfle If a program manifest has the `autoupdate` property, then it might work. Some program versions get moved to other directories (php/apache use archive directories) in which case this won't work.
It just replaces the `$version` variable in all `autoupdate` properties and creates a temporary manifest to install it. It may result in 404 errors.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by brama051** [comment]
scoop update gradle@6.1 updated my gradle from 4.9 to 6.2
Interesting behavior but it will do the job.
