### ISSUE TITLE
youtube-dl requires Visual C++ 2010 runtime

### ISSUE THREAD

**Issue by pparidans** [lukesampson/scoop#1793]
Hi,

During the re-installation of my system I had a issue during the setup of youtube-dl.

After a classic `scoop install youtube-dl` nothing happened when I tried to run youtube-dl.exe (no error or warning).

The culprit was Visual C++ 2010 missing from my system.

Maybe `extras/vcredist2010`  should be added as a dependency? Or the runtime's presence should be checked during postinstall?

**Comment by r15ch13** [comment]
I added a suggestion with https://github.com/lukesampson/scoop/commit/9889cb744833c9c7c867e29a13eb46bf5e991026
Most of the times those runtime packages are already installed, so adding it as a dependency causes them to be installed twice. Suggesting it should be enough.

**Comment by pparidans** [comment]
Yes I guess it's the best solution.

Thank you for the (very) quick commit 👍
