### ISSUE TITLE
There is no conda CLI after installing miniconda3

### ISSUE THREAD

**Issue by jeud** [lukesampson/scoop#1800]
Dear all

I just install `miniconda3` using `scoop install miniconda3` successfully so I try to test for CLI

```
#ok
python3 --version

# 'conda' is not recognized as an internal or external command,
conda --version
```

I'm new to both `anaconda` and `miniconda`, but my understanding is that `miniconda` is included with `conda` CLI

If this is a `scoop` issue, please help
Thanks

**Comment by h404bi** [comment]
Don't know what's wrong with that, maybe there is issues about PATH variable. Would you like to use the [bucket that I'm maintaining](https://github.com/h404bi/dorado) to install conda softwares, to see whether it works.

**Comment by jeud** [comment]
`conda` is not kind of CLI installed in the `scoop`'s `shims` folder so in my case, I just need a fresh reboot then everything works just fine, thanks
