### ISSUE TITLE
The system cannot find the path specified. - Windows 10

### ISSUE THREAD

**Issue by jsphkm** [lukesampson/scoop#1807]
I am sometimes getting this error message in windows 10 powershell: 
`The system cannot find the path specified.`

Here is what I've ran into:

```
PS C:\Users\Username> scoop list
Installed apps:

  7zip 16.04
  git 2.15.0.windows.1
  nodejs 9.0.0
  openssh 5.4p1-1

PS C:\Users\Username> scoop which 7zip
'7zip' not found
PS C:\Users\Username> scoop which git
~\scoop\apps\git\current\cmd\git.exe
PS C:\Users\Username> scoop which nodejs
'nodejs' not found
PS C:\Users\Username> scoop which openssh
'openssh' not found

PS C:\Users\Username> scoop checkup
No problems identified!

PS C:\Users\Username> scoop update
Updating Scoop...
The system cannot find the path specified.
Update failed.    
PS C:\Users\Username\scoop\apps\scoop\current>

PS C:\Users\Username> scoop which scoop
~\scoop\apps\scoop\current\bin\scoop.ps1
```

It seems like scoop can't find its packages, and it fails to update scoop itself.  Yet, the packages work fine when I run my scripts, for example: installing and running python and pip packages, and then running python scripts, however I have uninstalled python to reduce variables.

Here are my paths:

```
PS C:\Users\Username> ($env:Path).Replace(';',"`n")
C:\WINDOWS
C:\WINDOWS\system32
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Common Files\Microsoft Shared\Windows Live
C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
c:\Program Files (x86)\Intel\iCLS Client\
c:\Program Files\Intel\iCLS Client\
C:\ProgramData\Oracle\Java\javapath
C:\Program Files (x86)\Windows Live\Shared
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
C:\Users\Username\scoop\apps\nodejs\current\bin
C:\Users\Username\scoop\apps\nodejs\current
C:\Users\Username\scoop\shims
C:\Users\Username\AppData\Local\atom\bin
C:\Users\Username\AppData\Local\Microsoft\WindowsApps
C:\Users\Username\AppData\Local\Microsoft\WindowsApps
```

I've tried reinstalling scoop, and moving paths up and down, but the problem still remains.  I am using the default bucket by scoop.

**Comment by r15ch13** [comment]
`scoop which` does work with the package name, instead it shows the path to the shim/executable. It's based on the `which` command from Linux.

```
λ scoop which 7z
D:\scoop\apps\7zip\current\7z.exe
λ scoop which node
Not a scoop shim.
D:\scoop\apps\nodejs\current\node.exe
λ scoop which npm
Not a scoop shim.
D:\scoop\apps\nodejs\current\bin\npm.cmd
λ scoop which git
D:\scoop\apps\git-with-openssh\current\cmd\git.exe
λ scoop which ssh
D:\scoop\apps\git-with-openssh\current\usr\bin\ssh.exe
```

But I can't figure out where the `The system cannot find the path specified.` can come from while updating...

**Comment by jsphkm** [comment]
gotcha, my results are now the same.  Why does it fail to update scoop?  Do you think it's related to `The system cannot find the path specified.`?

**Comment by r15ch13** [comment]
Is there `.git` directory inside `C:\Users\Username\scoop\apps\scoop\current`?

**Comment by jsphkm** [comment]
yes, there is

![current folder](https://user-images.githubusercontent.com/28643797/32344941-be2ede98-bfc5-11e7-90d4-f4dd8c2847e0.png)

**Comment by r15ch13** [comment]
Can you try running these commands one by one from a new powershell window? This replicates the update process from line 73 to 79 in [scoop-update.ps1](https://github.com/lukesampson/scoop/blob/master/libexec/scoop-update.ps1).
```powershell
> cd ~/scoop/apps/scoop/current
> . .\lib\core.ps1
> . .\lib\git.ps1
> $currentdir = fullpath $(versiondir 'scoop' 'current')
> write-host $currentdir
> pushd $currentdir
> pwd
> git_pull -q
> write-host $lastexitcode
> popd
> pwd
```

**Comment by jsphkm** [comment]
Interesting, I think you're onto something with the git:
```
PS C:\Users\Username\scoop\apps\scoop\current> cd ~/scoop/apps/scoop/current
PS C:\Users\Username\scoop\apps\scoop\current> . .\lib\core.ps1
PS C:\Users\Username\scoop\apps\scoop\current> . .\lib\git.ps1
PS C:\Users\Username\scoop\apps\scoop\current> $currentdir = fullpath $(versiondir 'scoop' 'current')
PS C:\Users\Username\scoop\apps\scoop\current> write-host $currentdir
C:\Users\Username\scoop\apps\scoop\current
PS C:\Users\Username\scoop\apps\scoop\current> pushd $currentdir
PS C:\Users\Username\scoop\apps\scoop\current> pwd

Path
----
C:\Users\Username\scoop\apps\scoop\current


PS C:\Users\Username\scoop\apps\scoop\current> git_pull -q
The system cannot find the path specified.
PS C:\Users\Username\scoop\apps\scoop\current> write-host $lastexitcode
1
PS C:\Users\Username\scoop\apps\scoop\current> popd
PS C:\Users\Username\scoop\apps\scoop\current> pwd

Path
----
C:\Users\Username\scoop\apps\scoop\current
```

**Comment by r15ch13** [comment]
So it's it the `git_pull` method.
What's the result of `cmd /c git pull` when run in `C:\Users\Username\scoop\apps\scoop\current`?

**Comment by jsphkm** [comment]
```
PS C:\Users\Username\scoop\apps\scoop\current> cmd /c git pull
The system cannot find the path specified.
Already up to date.
PS C:\Users\Username\scoop\apps\scoop\current> git pull
Already up to date.
```

**Comment by r15ch13** [comment]
Are you using Cmder? Output of `echo %CMDER_ROOT%`?

**Comment by jsphkm** [comment]
Oh wait a minute, I had installed it before to try it out, but I thought I uninstalled it, it is portable as I recalled.

```
PS C:\Users\samsclub06613\scoop\apps\scoop\current> echo %CMDER_ROOT%
%CMDER_ROOT%
```

**Comment by r15ch13** [comment]
Can you open a powershell and run `cmd` from it, does it show `The system cannot find the path specified.`?

**Comment by jsphkm** [comment]
I have been using powershell all along.  Right now I'm thinking that maybe hidden files from cmder are interferring.

```
PS C:\Users\Username> cmd
Microsoft Windows [Version 10.0.16299.19]
(c) 2017 Microsoft Corporation. All rights reserved.
The system cannot find the path specified.
```

**Comment by r15ch13** [comment]
Ha, there it is. Okay, something is up with your `cmd` profile then. But I really don't know how to solve this now.
I can only remove the `cmd` part from the `git_pull()` function and use powershell instead. (This will not fix the `The system cannot find the path specified.`-problem, but we don't get an exit code 1 anymore 😁)

**Comment by jsphkm** [comment]
I had to clear autorun from the regedit, apparently cmder's modifications still remained.
[https://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified](url)

Now I can update:

```
PS C:\Users\Username> cmd
Microsoft Windows [Version 10.0.16299.19]
(c) 2017 Microsoft Corporation. All rights reserved.

PS C:\Users\Username> scoop update
Updating Scoop...
Scoop was updated successfully!
```

What do you think, is the problem fixed?

**Comment by sTorro** [comment]
I had the same problem (The system cannot find the path specified) but in my case clink was guilty. The issue appears if you use clink autorun and you removes it without doing the following:

`clink autorun uninstall`

I installed clink using scoop.

**Comment by rasa** [comment]
This appears to be resolved. If not, let us know. Thanks.

**Comment by szb9** [comment]
I've got the same error message i.e. `The system cannot find the path specified.` when trying to run an Allure app from PowerShell. The solution for me was to install Scoop and its apps to another path which has no spaces in it.
