### ISSUE TITLE
python app - missing pip shim

### ISSUE THREAD

**Issue by muhlpachr** [lukesampson/scoop#1808]
There is not pip/pip3 shim reference in python app

**Comment by r15ch13** [comment]
The `scripts` directory is added to your PATH on installation, so pip/pip3 should be available.

https://github.com/lukesampson/scoop/blob/2ea5330a5c3064d3bacb303110d7cd212914e773/bucket/python.json#L42-L44

**Comment by muhlpachr** [comment]
Yes. I am not sure what happend, I was not able to execute pip3, but I am not able to reproduce it now :-(
Thank you.

**Comment by vsviridov** [comment]
currently have python 2.7 installed and there's no `pip` shim and running `python -m pip` gives me "there's no module named pip" error, and the Scripts folder has no mention of pip
