### ISSUE TITLE
Nightly Support for Rust (and possible others)

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#181]
Rust is an experimental programming language and as such is iterating very quickly, meaning that the recommended way to consume it on Windows is through the nightly mingw32 downloads. 

This can be seen here: http://www.rust-lang.org/install.html

As far as I can tell there doesn't seem to be anything stopping me from changing the rust manifest to use a nightly version. However the hash will be different every day, which makes setting the hash useless. 

Would there be room for a nightly flag (or some other flag) that would suppress the hash warning?

Here is my updated manifest:
```
{
	"homepage": "http://www.rust-lang.org",
	"version": "nightly",
	"license": "MIT/Apache 2.0",
	"depends": "gcc45",
	"url": "https://static.rust-lang.org/dist/rust-nightly-i686-w64-mingw32.exe",
	"innosetup": true,
	"bin": [
		"bin\\rustc.exe",
		"bin\\rustdoc.exe"
	],
}
```

Suppressing the hash warning might be a simple solution like `"nightly": true` or perhaps a more general solution such as `"hash_suppress_warning": true`

I'd be happy to look at it and make a PR if you'd be willing to go down that path.

**Comment by deevus** [comment]
By adding `--no-cache` option in #308 updating a nightly can be done using `scoop update --no-cache --force rust-nightly` 

I'm happy with this for nightly versions as it keeps it simple.

**Comment by deevus** [comment]
@lukesampson Do you think it would it still be worth looking at some kind of convention for nightlies?

**Comment by lukesampson** [comment]
Yeah absolutely. If you have time to look at it, I think it would be cool.
