### ISSUE TITLE
Scoop Not Properly Handling Spaces In User Path

### ISSUE THREAD

**Issue by BrainBlasted** [lukesampson/scoop#1811]
Heya, when running `D:\Repos\scoop-extras\bin\checkver.ps1 <name> -u` per the App Manifest directions, it would split the directory,causing the fuction to fail with:
```
C:\Users\FirstName : The term 'C:\Users\FirstName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
```

Calling the full path to the checkver executable with `FirstName LastName` in double quotes allowed it to execute.

**Comment by r15ch13** [comment]
What are the complete step you did? Can you post the complete console output? I don't understand the problem.

**Comment by BrainBlasted** [comment]
This is occurring again. Recent example is that scoop tries to install `python` to `C:\Users\Christopher\`rather than `C:\Users\Christopher Davis\`. If you run scoop through an elevated prompt, it will create the new user and dump `python` files there.

**Comment by BrainBlasted** [comment]
This is occurring again. Recent example is that scoop tries to install `python` to `C:\Users\Christopher\`rather than `C:\Users\Christopher Davis\`. If you run scoop through an elevated prompt, it will create the new user and dump `python` files there.

**Comment by BrainBlasted** [comment]
@r15ch13, the issue reported above still stand on a new system - python & python35(from versions) cannot install properly via Scoop.

**Comment by r15ch13** [comment]
Can you try the following python manifest?
I changed `"TargetDir=$dir",` to `"TargetDir=\"$dir\"",`. This should solve the problem.

```json
{
    "homepage": "https://www.python.org/",
    "license": "https://docs.python.org/3/license.html",
    "version": "3.6.4",
    "architecture": {
        "64bit": {
            "url": "https://www.python.org/ftp/python/3.6.4/python-3.6.4-amd64.exe#/py3.exe",
            "hash": "de02d46fe9a6269a7c0792d8be155b0d1fa20a68623a0fad33ab02f92ef58d49"
        },
        "32bit": {
            "url": "https://www.python.org/ftp/python/3.6.4/python-3.6.4.exe#/py3.exe",
            "hash": "f1c783363504c353d4b2478d3af21f72cee0bdd6d4f363a9e0e4fffda3dc9fdf"
        }
    },
    "pre_install": "copy-item $dir\\py3.exe $dir\\uninstall.exe",
    "installer": {
        "args": [
            "/quiet",
            "InstallAllUsers=$(@{$true=1;$false=0}[$global])",
            "TargetDir=\"$dir\"",
            "AssociateFiles=0",
            "Shortcuts=0",
            "InstallLauncherAllUsers=$(@{$true=1;$false=0}[$global])"
        ]
    },
    "uninstaller": {
        "file": "uninstall.exe",
        "args": [
            "/uninstall",
            "/quiet",
            "InstallAllUsers=0"
        ]
    },
    "bin": [
        "python.exe",
        "pythonw.exe",
        [
            "python.exe",
            "python3"
        ]
    ],
    "env_add_path": [
        "scripts"
    ],
    "checkver": "<p>Latest: <a href=\".*\">Python ([\\d.]+)</a> - <a.*>.*</a></p>",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://www.python.org/ftp/python/$version/python-$version-amd64.exe#/py3.exe"
            },
            "32bit": {
                "url": "https://www.python.org/ftp/python/$version/python-$version.exe#/py3.exe"
            }
        }
    }
}
```

**Comment by BrainBlasted** [comment]
Thanks, that worked perfectly.

**Comment by atomicwrites** [comment]
There are other packages with this issue, I ran into it with Calibre from `extra`. The same solution worked, although then I got an error saying the install path had to be less than 59 chars (why would you... never mind.)
