### ISSUE TITLE
Wrong NodeJS version in nodejs bucket?

### ISSUE THREAD

**Issue by nkm8** [lukesampson/scoop#1812]
Somehow this commit made it into master on the @lukesampson copy of this repo:  https://github.com/lukesampson/scoop/commit/7688cc8d71c7b6e3e455b582ef578731de2a49d6#diff-2949fa135935c3b608e0c9dccefd6fd0?w=1

Clicking the pull request link from that commit links to this PR, which was merged into a fork:  https://github.com/robjarsen/scoop/pull/1

I am a bit confused on exactly what happened and how/why this made it into master, but I think it needs to be reverted.  I am not sure about the general community, but I was unaware of the nodejs-lts bucket.  Based on the histories:
https://github.com/lukesampson/scoop/commits/master/bucket/nodejs.json
https://github.com/lukesampson/scoop/commits/master/bucket/nodejs-lts.json

One would argue that nodejs-lts hasn't been kept up-do-date and the nodjs bucket has historically contained the latest stable node version.

I switched to nodejs-lts, but I have a feeling that lots of other users will see the incompatibility issues I did if they upgrade their scoop packages.  This may be an intentional change, but I wanted to get confirmation of which version users should be installing to have the latest stable copy.

**Comment by r15ch13** [comment]
nodejs.json has always the latest version which is now 9.0.0
nodejs-lts.json has always the latest LTS version which is now 8.9.0
This works like intended.

What doesn't work like intended is the PR to https://github.com/robjarsen/scoop/pull/1
The [update service](https://github.com/r15ch13/Excavator) I host should push to @lukesampson's  master branch. I don't know why it pushes to @robjarsen. 😕 Maybe I messed up something. I recreated the docker container, hopefully that fixes this.

**Comment by robjarsen** [comment]
That's strange...

**Comment by nkm8** [comment]
This issue still exists because somehow this commit is on the @lukesampson repo:  https://github.com/lukesampson/scoop/commit/7688cc8d71c7b6e3e455b582ef578731de2a49d6

I think the changes make sense, but a lot of people like me likely weren't expecting scoop to be updated so quickly.  I think the changes should be reverted and a proper pull request should be opened.

**Comment by r15ch13** [comment]
The problem with PR to @robjarsen's repo is solved.

@nkm8 I don't understand the problem nodejs being updated quickly to version 9?

**Comment by nkm8** [comment]
I was having issues with the latest version of node not working with some of the tools I use (angular-cli).  I think the issue is that I installed node (v8.x) at a time when it was fairly stable and was already compatible with most tools with a node dependency.

Moving forward, I should be on the node-lts releases for stability, so I think this issue can be closed.  At first I thought that most other people would be experiencing the same issue, but most are correctly on the lts release instead of the 'latest' release.  Thanks for the help!
