### ISSUE TITLE
scoop install hangs when linking current to version for go

### ISSUE THREAD

**Issue by klauern** [lukesampson/scoop#1817]
I'm not sure what could be going on, but I would like some assistance in figuring out how to debug an installer that seems to just hang at the 'Linking `~/.../current => ...`' step:

```
C:\Users\klauer
λ  scoop install go
Installing 'go' (1.9.2).
Loading go1.9.2.windows-amd64.zip from cache
Checking hash of go1.9.2.windows-amd64.zip... ok.
Extracting... done.
Running installer script...
Linking ~\scoop\apps\go\current => ~\scoop\apps\go\1.9.2
```

No matter what I do, it just doesn't move beyond this.  I'm running this from a **non**-elevated Powershell environment, and I can cleanly `scoop uninstall go` without issue.  The problem I have is I just don't see anything erroring to know how to fix it.

**Comment by klauern** [comment]
I found out that this was due to some weird path issue where `cmd.exe` wasn't the same `cmd` that needed to run, so it wouldn't be able to call into `mklink`, thus it hangs.  I would say it's a complicated, self-inflicted gunshot wound, so I'm closing this issue.

If anyone else finds that it hangs here, check for `which cmd` to see if the `cmd.exe` that you need to make a symbolic link to `current` is the same one as windows.

On a separate note, wouldn't it be more consistent if `scoop` assumed a default path for shell commands instead of inferring what our `%PATH%` was set to is correct?  I know I'm not going to make this mistake again, but i could see it happening elsewhere.

**Comment by r15ch13** [comment]
So it hangs here: https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L736-L739
Maybe we should use the full `cmd.exe` path to prevent this?

**Comment by klauern** [comment]
@r15ch13 , yes, that's correct.  I found those lines and tried to re-create the "Linking current => go..." call, and it hung there all the same.  If that was a fully-qualified path, I'm pretty confident it would have worked.
