### ISSUE TITLE
Update nvm to 1.1.6

### ISSUE THREAD

**Issue by mriehema** [lukesampson/scoop#1825]
First: 
Thanks for your awesome work!

Second: 
nvm is outdated, 1.1.5 is used in this bucket. 1.1.6 released in July 17. This update is important to use npm5.
Could you please update this?

Links:
https://github.com/lukesampson/scoop/blob/master/bucket/nvm.json
https://github.com/coreybutler/nvm-windows/releases/tag/1.1.6

**Comment by mriehema** [comment]
Just used the checkver script for auto update and it didn't work, because 1.1.6 of nvm is offically just a pre release. :( But this is still important for using nvm and nodejs > 8. So maybe you want to update anyhow.

**Comment by r15ch13** [comment]
Disabled autoupdate with https://github.com/lukesampson/scoop/commit/3dc5b23c431eac18c16d614ea4d43a3277720992 to prevent automatic downgrading trough our update service.
