### ISSUE TITLE
Scoop relies on Remove-Item alias "rm"

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#183]
I removed the alias `rm` that points to `Remove-Item`, which breaks scoop install/uninstall/update commands, possibly others. 

I recommend using `Remove-Item` explicitly instead of the `rm` alias, since the scoop scripts rely on the `Remove-Item` implementation, and I want to use `busybox rm` as an alias. This way, scoop always uses the specific command from powershell.

**Comment by darsain** [comment]
Also wanted to replace `rm`, along with a few other commands, and this makes it impossible.

Honestly, you can't put users in a situation where they can't customize *their* aliases because your tool relies on default ones. You've basically broke a PowerShell feature for every scoop user.

Never coded any PS script, but I'd be surprised if using non-aliased commands wasn't a recommended best practice. You really should be using them.

**Comment by blackk18** [comment]
I was trying to install some unix utilities
```powershell
scoop install gow
```
or
```powershell
scoop install busybox
```
These installations create shims like **rm** or **ls**, which can't be used because of powershell's default aliases. If I remove aliases scoop is broken. 

I'd really like to be able to use **rm -rf** or have civilised **ls** output, but because of this "bug" (or feature) I'm stuck with very sad things like **rm -force**...

**Comment by deevus** [comment]
It's safe to remove the `ls` alias. I just put it in my Profile.ps1 file. 

As for the `rm` alias, this is still frustrating for me. I've thought about changing all the alias references myself but if @lukesampson is still against this then it'll just fragment the community.

**Comment by lukesampson** [comment]
For me, the ideal way to fix this would be to set the aliases that scoop needs (maybe in core.ps1) with `-option private` or some other way of limiting the aliases to only apply for scoop (i.e. running `scoop [cmd]`, not running apps that are installed with scoop).

I'm not sure if this is possible. If anyone would like to try creating a script that can set it's own aliases without affecting the user's aliases, or point me to somewhere that shows it's possible, that'd be helpful.

**Comment by deevus** [comment]
@lukesampson I've had a look at this and unfortunately it doesn't work. If you have a AllScope alias (ie rm -> Remove-Item) then you can't create a private/script alias of the same name. It doesn't let you override the globally scoped one.

**Comment by lukesampson** [comment]
Thanks for looking at it. Do you know if function scoped to the script would work? Something like what @kodybrown suggested above?

**Comment by deevus** [comment]
Using a simple function definition with script scoping in core.ps1:

```powershell
function script:rm($path) { 
	Remove-Item $path -R -Force -Ea Stop
}
```

I then removed the arguments from the calls in uninstall.ps1:

```powershell
	$appdir = appdir $app $global
	try {
		rm $appdir
	} catch {
		$errors = $true
		warn "couldn't remove $(friendly_path $appdir): $_.exception"
	}
```

Uninstalling an app would do the following: 

```
scoop master* $ .\bin\scoop.ps1 uninstall cargo-nightly
uninstalling cargo-nightly (nightly)
removing shim for cargo
couldn't remove ~\appdata\local\scoop\apps\cargo-nightly\nightly: it may be in use
```

I'm not a Powershell expert so I could be missing something here, but otherwise I think it's more effort than it's worth.

**Comment by lukesampson** [comment]
That's interesting. So what if you change the rm function in `core.ps1` to just this:

```powershell
function script:rm() { remove-item @args }
```

That way we wouldn't have to re-write all the calls to `rm` to remove the arguments, they'd just get passed to the `remove-item` command. Would that work?

**Comment by deevus** [comment]
Good one! That does work. :)

**Comment by deevus** [comment]
@lukesampson What other aliased commands are used so I can replace those as well?

**Comment by lukesampson** [comment]
Cool, sounds like this might work then, right?

Here are the aliased commands I can find:

* `cp` -> `copy-item`
* `echo` -> `write-host`
* `gc` -> `get-content`
* `gci` -> `get-childitem`
* `gcm` -> `get-command`
* `ls` -> `get-childitem`
* `mkdir` -> `new-item`
* `mv` -> `move-item`
* `rm` - `remove-item`
* `rmdir` -> `remove-item`
* `sc` -> `set-content`
* `select` -> `select-object`
* `sls` -> `select-string`

**Comment by lukesampson** [comment]
One small fix for `mkdir` but apart from that it's looking good. Thanks for this. All good now?

**Comment by deevus** [comment]
Yep all good :)

**Comment by lukesampson** [comment]
:+1:

**Comment by ghostsquad** [comment]
The only aliases that I've been comfortable using in modules and scripts are `?` for `Where-Object`, `%` for `ForEach-Object`, `??` for `Invoke-NullCoalescing` and `?:` for `Invoke-Ternary`. The last two are from Powershell Community Extensions (PSCX).
