### ISSUE TITLE
Feature request - Shim version be updated when running checkver

### ISSUE THREAD

**Issue by mundusnine** [lukesampson/scoop#1845]
Make it so that when we do ~/scoop/apps/scoop/current/bin/checkver -dir ./ myApp -u The version in the shim is updated or that the shim can have $version as an identifier. 

Exemple:
 "bin": [
        "Godot_v$version-stable_win64.exe",
        [
            "Godot_v$version-stable_win64.exe",
            "godot"
        ]
    ]

This currently isn't supported and we have to do it by hand which is kinda of useless.

**Comment by brandon93s** [comment]
The current workaround for this is to use a pre_install script to rename the exe, giving the shortcut a consistent file name to point to. See Godot for a recently implemented example: https://github.com/lukesampson/scoop-extras/blob/master/godot.json

**Comment by mundusnine** [comment]
Ok great ! Thanks for the fast response. Will use this in json

**Comment by rasa** [comment]
Clarified, covered by autoupdate refactor with multiple URLs (#2176)
