### ISSUE TITLE
Unique 32-bit and 64-bit Checkver

### ISSUE THREAD

**Issue by matthewjberger** [lukesampson/scoop#1848]
Is it possible to have a separate checkver for 32-bit and 64-bit versions? I was trying to fix the emacs manifest because the 64-bit version of emacs 25.3 was actually released with a bug that prevents emacs from running. [Emacs 25.3_1 was released as a bugfix version](https://ftp.gnu.org/gnu/emacs/windows/emacs-25.3_1.readme) that corrects the issue in 25.3. However this was only for the 64-bit version, so now the 32-bit version and the 64-bit version are no longer the same. 

Is there a simple way to account for this in a manifest? 

I realize this might make having a single version of the application for the manifest more difficult as well...

**Comment by r15ch13** [comment]
No, currently that's not possible. A workaround for this would be to add the new download link to the manifest, but keeping the version then same. Then just uninstall it, clean cache and reinstall it.
