### ISSUE TITLE
When running git difftool I only get a diff in the console

### ISSUE THREAD

**Issue by mundusnine** [lukesampson/scoop#1860]
I have set the merge and diff tool settings in the config file but when I write the above command I only see the code as  text in the cmd.exe window. 

Proof: file:C:/Users/JSNof/.gitconfig  user.name=mundusnine
file:C:/Users/JSNof/.gitconfig  mergetool.tortoisemerge.path=~\scoop\apps\tortoisemerge\current\tortoisemerge.exe
file:C:/Users/JSNof/.gitconfig  merge.tool=kdiff3
file:C:/Users/JSNof/.gitconfig  diff.tool=kdiff3
file:C:/Users/JSNof/.gitconfig  diff.external=kdiff3
file:C:/Users/JSNof/.gitconfig  diff.guitool=kdiff3
file:C:/Users/JSNof/.gitconfig  gui.recentrepo=C:/goj

I tried using kdiff3 and tortoisemerge but I got the same issue with both. Possibly a git issue but just want to make it isn't first.

**Comment by rasa** [comment]
Closing as this issue is really old. Please reopen if you are still having issues.
