### ISSUE TITLE
Shouldn't vim manifest use the stable release

### ISSUE THREAD

**Issue by Ghasan** [lukesampson/scoop#1871]
I realized that vim installation uses the nightly releases of vim. This is surprising, as normally the default installation normally uses the stable release, while offering the nightly release with a flag, like -pre for choco, and so on.

I am not sure, if scoop support this, but the default should be the stable release.

**Comment by rasa** [comment]
Perhaps we could add a tag, such as `"status": "released"` or `"status": "beta"`, and then you can set scoop to not install beta software, via `scoop config ignore beta`. We could get more fine grained if we wanted, using `rc`, `alpha`, and even `gamma`, if we wanted.

Of course, this would require `scoop install` to visit all previous commits of a package, to find the most recent one that's marked `"status": "released"`.

A similar idea was mentioned in https://github.com/lukesampson/scoop/issues/1552.

**Comment by r15ch13** [comment]
@rasa no it doesn't use the git history. It makes use of the autoupdate feature to create a temporary manifest by replacing `$version` with your requested version.

**Comment by rasa** [comment]
Smart. To ease admin duties, though, I would rather have a single `vim.json`, then `vim.json`, `vim-beta.json`, `vim-rc.json`, `vim-alpha.json`, etc. You?

**Comment by Ghasan** [comment]
@r15ch13  But version numbers themselves don't convey any meaning. So if I want to install the stable version of vim, I would have to google the version number of the stable release, and then use it with '@'.

But the important question is, should manifests by default target release channels, or nightly ones? I think what most would expect is to target the release stable channels, because the one vim manifest currently targets is clearly nightly builds. However, stables ones are provided here: https://ftp.nluug.nl/pub/vim/pc/ which is accessed from: https://vim.sourceforge.io/download.php

**Comment by r15ch13** [comment]
Normally it should provide a stable release. Which vim build is the stable version and is there a way to get it with all the stuff that's in the Github release packages? The releases on https://ftp.nluug.nl/pub/vim/pc/ are missing something.

It's possible to set the `version` property to `nightly`, but this works only with URLs that don't contain a version string and scoop skips checksum verification.

**Comment by Ghasan** [comment]
I am not a heavy user of Vim, and I am not sure if that repo misses something. In this case, maybe we can put a note in the manifest that this is a nightly channel.
