### ISSUE TITLE
Installing Package Error

### ISSUE THREAD

**Issue by justin-nodeboy** [lukesampson/scoop#1885]
Hey

I am working for a major international bank, who are basically a pain in the ass when it comes to trying to do my job. So the promise of Scoop is appealing as a way to get on with things. So thanks, but I am having a slight issue with trying to install packages.

I am running the following and getting the error below:
```
λ scoop install vcredist2017
Installing 'vcredist2017' (14.10.25008).
The remote name could not be resolved: 'http'
URL https://download.microsoft.com/download/6/2/4/62418bd0-eeda-453f-89e5-1da35666df77/vc_redist.x64.exe is not valid
```

Any ideas on what I can do to fix this? I have set my proxy according to the docs.

Thanks

Justin

**Comment by r15ch13** [comment]
Can you download it with a browser or wget/curl?

**Comment by justin-nodeboy** [comment]
@r15ch13 Yeah man, downloads fine if I go direct to the link. It's actually happening for all packages that I try to install :(

**Comment by r15ch13** [comment]
Is the output of `[net.webrequest]::defaultwebproxy` or `[net.webrequest]::defaultwebproxy.credentials` correct? (copy it to powershell and execute it)

**Comment by justin-nodeboy** [comment]
I'll have to do that tomorrow, I'm on GMT and have shed enough blood for one day :)
I'll let you know in the morning my time.
Cheers

**Comment by r15ch13** [comment]
The proxy logic can be found here: https://github.com/lukesampson/scoop/blob/09de922a0da4e76db1c6dab695101c8b3af1c191/lib/config.ps1#L61-L86
Maybe this helps a bit. 😄

**Comment by justin-nodeboy** [comment]
I'll take a look and will let you know if I get any further :), thanks for the assist

**Comment by rasa** [comment]
Let us know if this is still an issue.

**Comment by bendem** [comment]
> The remote name could not be resolved: 'http'

For the future people, I found this problem was caused by setting a full url in the proxy config: `config proxy http://name:port` instead of `config proxy name:port`.

**Comment by mystery4f** [comment]
> > The remote name could not be resolved: 'http'
> 
> For the future people, I found this problem was caused by setting a full url in the proxy config: `config proxy http://name:port` instead of `config proxy name:port`.

I encountered this issue due to the proxy settings in the .gitconfig file.  

```
[https]
	# proxy = http://127.0.0.1:3080

[http]
	# proxy = http://127.0.0.1:3080
```
