### ISSUE TITLE
install OPCache ?

### ISSUE THREAD

**Issue by lotarbo** [lukesampson/scoop#1887]
Hello, how install OPCache via scoop?

**Comment by r15ch13** [comment]
It's included in PHP for Windows.
Create `opcache.ini` in `~\scoop\persist\php\cli\conf.d` and add this:
```ini
zend_extension=php_opcache.dll
opcache.enable=On
opcache.enable_cli=On
```

**Comment by lotarbo** [comment]
thank you) like scoop, it replace chocolaty and babun for me)

**Comment by lotarbo** [comment]
but how install some ext (ex imagick) if no dll in scoop\apps\php\current\ext ?

**Comment by r15ch13** [comment]
You can add this bucket to scoop https://github.com/nueko/php-ext-bucket and install it. But there is still a problem with the ImageMagick version. See: https://github.com/nueko/php-ext-bucket/pull/5 (it's possible to use this file locally to install php-imagick)

**Comment by lotarbo** [comment]
thank you
