### ISSUE TITLE
Multiple lines in post_install script

### ISSUE THREAD

**Issue by saranc91** [lukesampson/scoop#1890]
I am trying to put multiple lines in my post install section like below,

"post_install": [
    "Write-Host \"Configuring Git for...\"",
    "git config --global credential.helper wincred",
    "git config --global core.autocrlf true"
]

It turns out an error "% : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Command'. Specified method is not supported
+ $apps | % { install_app $_ $architecture $global $suggested $use_cach ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.ForEachObjectCommand

Tried with different apps for post_install, but still it is not accepting multiple scripts but if I give only one install script it runs smooth

**Comment by r15ch13** [comment]
`post_install` and `pre_install` only support string. Just use newlines. See [php.json](https://github.com/lukesampson/scoop/blob/master/bucket/php.json)

**Comment by saranc91** [comment]
Thank you, suppose if I have to run multiple lines. Example in above case if I want to configure the gitconfig file with multiple parameters. Is there a way I can do it ?  I was able to do it before but not after updating scoop.

**Comment by r15ch13** [comment]
This should work: 
```json
{
  "post_install": "Write-Host \"Configuring Git for...\"
     git config --global credential.helper wincred
     git config --global core.autocrlf true",
}
```

**Comment by brandon93s** [comment]
FWIW, setting the users credential store and autocrlf settings, which are global, don't seem ideal for an install script if this is for the public bucket(s). This would be odd side effects the user is largely unaware of.

**Comment by saranc91** [comment]
This is not working : {
  "post_install": "Write-Host \"Configuring Git for...\"
     git config --global credential.helper wincred
     git config --global core.autocrlf true",
}

Setting up a autocrlf setting is for private configuration. So I do it as part of Json manifest..Not sure why this feature has stopped working after update.

Is there any way that multplie scripts can be added to post install

**Comment by saranc91** [comment]
Can someone help on it....As it was working before and not now after updating it. Please let me know if I have to make any changes to make it reflect

**Comment by r15ch13** [comment]
What is not working? Did you use the `post_install` script I posted above? Is there a new error message?

**Comment by saranc91** [comment]
When I put the given post_install script, it is not resolving the Json. 

I tried different possibility but still getting the same erro : 

It turns out an error "% : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Command'. Specified method is not supported

$apps | % { install_app $_ $architecture $global

--- I feel that it is not taking the array of values and it is executing only the top one. Strange because it was working before

**Comment by r15ch13** [comment]
Hm, it should never have worked with an array, because it was never supported. Change it to a single string and you're done.

**Comment by stkb** [comment]
Came across this issue too, since [the documentation](https://github.com/lukesampson/scoop/wiki/App-Manifests) says "A string or array of strings of the commands...".
Is there a reason why supporting an array of strings is difficult? (I could otherwise take a look at it)

Strictly, manifests that have multiline scripts are invalid json, since json doesn't allow multiline strings.

**Comment by rasa** [comment]
The schema allows an array of strings, as well. See
https://github.com/lukesampson/scoop/blob/master/schema.json#L411

**Comment by r15ch13** [comment]
Yeah the schema allows it, but it's not implemented. See https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L891

**Comment by rasa** [comment]
Shall I submit a PR, or shall we fix the docs and schema? I would prefer the former.

**Comment by stkb** [comment]
@rasa I would be happy if you fixed it :)

**Comment by rasa** [comment]
My fix is:
````
        if ($pre_install -isnot [String]) {
            $pre_install = $pre_install -Join "`r`n"
        }
````
Does that work?
