### ISSUE TITLE
Add vswhere

### ISSUE THREAD

**Issue by dariusdamalakas** [lukesampson/scoop#1891]
Please add `vswhere` to scoop.

````
PS> scoop install vswhere
Couldn't find manifest for 'vswhere'.
````

`vswhere is designed to be a redistributable, single-file executable that can be used in build or deployment scripts to find where Visual Studio - or other products in the Visual Studio family - is located. `

https://github.com/Microsoft/vswhere

**Comment by rasa** [comment]
Try updating scoop first via `scoop update`, as vswhere is in scoop-extras at https://github.com/lukesampson/scoop-extras/blob/master/vswhere.json

**Comment by dariusdamalakas** [comment]
````
PS > scoop install vswhere
Updating Scoop...
Scoop was updated successfully!
Couldn't find manifest for 'vswhere'.

`````

@rasa  do I need to install scoop-extras manually? 

Ran again:

````
PS > scoop update
Updating Scoop...
Scoop was updated successfully!
PS > scoop install vswhere
Couldn't find manifest for 'vswhere'.
````

Am i missing some steps?

**Comment by r15ch13** [comment]
`scoop bucket add extras`

**Comment by dariusdamalakas** [comment]
All works! thank you all.

**Comment by rasa** [comment]
Sorry, I forgot extras is not enabled by default.

**Comment by dariusdamalakas** [comment]
@rasa  its OK, i did try to look it up in [wiki](https://github.com/lukesampson/scoop/wiki), but could not find any topic about `extra` or `extras`,    Now that i know it is a `bucket`, i could find that under `buckets` section how to install extras : [buckets#Installing from other buckets](https://github.com/lukesampson/scoop/wiki/Buckets#installing-from-other-buckets)

**Comment by rasa** [comment]
Does anyone know why all the built-in buckets aren't enabled by default? Or at least a message saying: hey, we found the app you want in this built-in bucket, please run 'scoop bucket add bucket' to enable it.

**Comment by refack** [comment]
@dariusdamalakas I'm interested in hearing how are you using vswhere this way. I would assume it not that useful without VS2017 installed, while that installs vswhere by default...

**Comment by dariusdamalakas** [comment]
@refack i'm still am looking into this, but we have a set of `gulp` tasks which can compile, run and test our services.  The idea is to use `vswhere` to locate `msbuild`. Not everyone will have VS2017 installed. Nor i think building and running services should rely on having a specific version of IDE installed.  In fact, we might end up not using `scoop`, as that is a new dependency for us to take. `vswhere` can be installed via `nuget` too, this is probably what we will end up using.

**Comment by refack** [comment]
@dariusdamalakas thanks. I forgot about `-legacy`...
