### ISSUE TITLE
Cannot install unzip

### ISSUE THREAD

**Issue by tylerlong** [lukesampson/scoop#1900]
```
scoop install unzip
unzip //  The term 'unzip' is not recognized as the name of a cmdlet ....
scoop uninstall unzip
scoop install unzip
```

The last command cause PowerShell to quit.

**Comment by brandon93s** [comment]
I was able to install: 

![image](https://user-images.githubusercontent.com/4730164/33817745-1e903f22-de0f-11e7-96a4-5ef9c8af2b64.png)

And use:

![image](https://user-images.githubusercontent.com/4730164/33817761-3343fb8e-de0f-11e7-81cb-03d833ae8744.png)


Seems like scoop isn't added to your path. Have you been able to install and use other apps via scoop?

32bit or 64bit?
