### ISSUE TITLE
update app installed from custom bucket will always fallback to main bucket.

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop#1904]
Installed an app from a 3rd-party bucket, when I updating it, it will always fallback to the main bucket  _if there is a same name app manifest in the main bucket_.

How to reproduce? e.g. install miniconda3 from my bucket:

``` sh
$ scoop bucket add dorado https://github.com/h404bi/dorado
$ cd ~/scoop/bucket/dorado
# checkout old commit to install old version of miniconda3 from my bucket
$ git checkout 729b61
# version 4.3.30
$ scoop install dorado/miniconda3
# update bucket
$ scoop update
# now update miniconda3 to 4.3.30.2
$ scoop update miniconda3
```

And it will update miniconda3 using [the manifest in the main bucket](https://github.com/lukesampson/scoop/blob/master/bucket/miniconda3.json), instead of using [the custom bucket one](https://github.com/h404bi/dorado/blob/master/miniconda3.json), though we install it with `scoop install dorado/miniconda3`.

**Comment by r15ch13** [comment]
Should be fixed now with https://github.com/lukesampson/scoop/commit/9e124dae23bffa775262d9c12faeed2f03d22e36
