### ISSUE TITLE
Cannot install the newest version of Gradle correctly (4.4)

### ISSUE THREAD

**Issue by thecheeselover** [lukesampson/scoop#1905]
![image](https://user-images.githubusercontent.com/6900372/33897910-c2b0d546-df34-11e7-8d88-4b9ee3e1e59f.png)

It's in french but I think you can understand that the hash check failed. It worked yesterday on my other computer and now for no reasons it doesn't work on this one. I have the Windows Power Shell version 4.

**Comment by r15ch13** [comment]
Can you post the output of the following three commands?
```
> $PSVersionTable
> Get-Command -Name Get-FileHash
> [system.security.cryptography.hashalgorithm]::create
```

**Comment by thecheeselover** [comment]
Here you go :

![image](https://user-images.githubusercontent.com/6900372/33900713-756520ae-df3d-11e7-97d4-ffd67b3235d1.png)

**Comment by r15ch13** [comment]
Does the file exists in `~\scoop\cache`? Is there an Antivirus program running?

**Comment by thecheeselover** [comment]
There's only the zip file in the folder scoop/cache : gradle#4.3.1#https_services.gradle.org_distributions_gradle-4.3.1-bin.zip

It is a valid zip file because I can open it with 7zip.
![image](https://user-images.githubusercontent.com/6900372/33901153-de51186a-df3e-11e7-9346-43687596ea3e.png)

However, in the folder scoop\apps\gradle\4.4 there's the file gradle-4.4-bin.zip.

I have McAfee running on both computers and it rarely interferes with my programs. The only times it tashed files was when they were suspicious dlls or executables like the game Sonic Adventure 2 Battle or a custom map editor for Warcraft III.

**Comment by r15ch13** [comment]
Can you try running:

```
> . ~\scoop\apps\scoop\current\lib\install.ps1
> compute_hash '~\scoop\cache\gradle#4.4#https_services.gradle.org_distributions_gradle-4.4-bin.zip' 'sha256'
```
The first one imports a part of scoop into the current PowerShell session. The second command uses the function to get the file hash.

**Comment by thecheeselover** [comment]
![image](https://user-images.githubusercontent.com/6900372/33901613-591ceeec-df40-11e7-83f8-fc59ee3e528e.png)

Did I use the wrong directory path or something?

**Comment by r15ch13** [comment]
Change the `~` to the full path 😄

**Comment by thecheeselover** [comment]
Oops! Ahah I thought for a second that it was for the home directory.

![image](https://user-images.githubusercontent.com/6900372/33902048-be2aade6-df41-11e7-9801-ace0e412d66e.png)

By the way, like I said earlier, the file gradle#4.3.1#https_services.gradle.org_distributions_gradle-4.3.1-bin.zip is in the cache whereas the file gradle-4.4-bin.zip is in the folder apps\gradle\4.4\

In other words, it's normal that it doesn't work.

**Comment by r15ch13** [comment]
Does it work now?

**Comment by thecheeselover** [comment]
Nope. Same error as before.

**Comment by r15ch13** [comment]
The `Could not find file` error or the `InputStream` one?

**Comment by thecheeselover** [comment]
![image](https://user-images.githubusercontent.com/6900372/33905368-669c59f2-df4c-11e7-985c-0deeb8d41fa8.png)

The InputStream error. It did the same thing when I downloaded the version 4.3 of gradle a few days ago on my other computer. However, after updating scoop, it worked.

**Comment by r15ch13** [comment]
What about the manual way I wrote above? 

```
> . C:\Users\Portable\scoop\apps\scoop\current\lib\install.ps1
> compute_hash 'C:\Users\Portable\scoop\cache\gradle#4.4#https_services.gradle.org_distributions_gradle-4.4-bin.zip' 'sha256'
```

**Comment by thecheeselover** [comment]
I was about to comment that actually ahah Here's the print screen : 
![image](https://user-images.githubusercontent.com/6900372/33905522-e0ccd74c-df4c-11e7-85eb-5227d5738066.png)

It can't work because gradle v4.4 is never in the cache somehow :/

**Comment by r15ch13** [comment]
Shit ... it gets delete as soon as it can't compute the hash 😁
Try downloading it manually and then run the `compute_hash` function on it. Or just use `compute_hash` on another file 😁

**Comment by thecheeselover** [comment]
![image](https://user-images.githubusercontent.com/6900372/33905911-3a957af8-df4e-11e7-84db-c0862aeefbea.png)

Damn the first propostion doesn't work. I'll just have to completely manually install gradle for now. How much of a priority is this right now, i.e. in about how much time will this be fixed (rough estimate, I'm not a project manager ahah)?

Anyway, thanks for your help! :)

**Comment by r15ch13** [comment]
It's probably related to my last commit https://github.com/lukesampson/scoop/commit/da7d61f3e3589f94ea3e9af3ff6d2670084106da
But I can't figure out why, because the old code used the same function that shows an error for you.

It's difficult to replicate, so I need your help to fix it. 😄 

Does this work?
```
> $fs = [system.io.file]::openread('C:\Users\Portable\scoop\cache\gradle-4.4-bin.zip')
> (Get-FileHash -InputStream $fs -Algorithm 'sha256').Hash
> $fs.dispose()
```

**Comment by thecheeselover** [comment]
By the look of the first command, I need to put back the gradle-4.4-bin.zip file that I had juste downloaded and deleted for the purpose of testing. I'll try the commands and then edit this current comment.

**Comment by r15ch13** [comment]
Okay, so the `-InputStream` parameter is not available for PowerShell 4 but the documentation says it's supported ... crap

**Comment by r15ch13** [comment]
Can you try it without `-InputStream`? Just `(Get-FileHash $fs -Algorithm 'sha256').Hash`

**Comment by thecheeselover** [comment]
![image](https://user-images.githubusercontent.com/6900372/33906956-8ac15f26-df51-11e7-9f3f-c3e3ba28d4b5.png)

It says that System.IO.FileStream doesn't exist.

**Comment by r15ch13** [comment]
Next one: `(Get-FileHash -Path 'C:\Users\Portable\scoop\cache\gradle-4.4-bin.zip' -Algorithm 'sha256').Hash`

**Comment by thecheeselover** [comment]
![image](https://user-images.githubusercontent.com/6900372/33907126-151f996c-df52-11e7-9907-898b42b80671.png)

:wink:

**Comment by r15ch13** [comment]
Run `scoop update` and try installing it again. It should work now 👍

**Comment by thecheeselover** [comment]
Yep! It works like it was before. Thank you very much!

**Comment by r15ch13** [comment]
So much trouble from one line of code 😁
