### ISSUE TITLE
mysql-workbench - No start menu entry

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop#1916]
This is recipe is working to install MySQL Workbench, but a start menu entry never appears.   To run, one must type mysqlworkbench.exe or "MySQLWorkbench" on the command line.

Reproduce Steps:

- scoop install mysql-workbench
- Check the start menu 

Expected:

Should install and place an entry in the start menu.

**Comment by r15ch13** [comment]
Fixed
