### ISSUE TITLE
scoop update * broke tortoisesvn

### ISSUE THREAD

**Issue by sim4life** [lukesampson/scoop#1937]
First, I did:
`PS > scoop update`

then I run:
`PS > scoop update *`

It first broke on 'Ditto' then it asked me to close, Explorer, NetBeans, Internet Explorer etc. I closed these apps but it got hung up at uninstalling ... for 10+ minutes.
Next, I quit the process and ran again:
`PS > scoop update tortoisesvn`
It opens up a dialog that asks: 'Are you sure you want to uninstall this product?'
On pressing 'Yes'
It brings an error dialog: 'This action is valid only for products that are currently installed'

Now, I can neither uninstall, nor install, nor update tortoisesvn, nor reset tortoisesvn.

**Comment by rasa** [comment]
This might explain things: https://github.com/lukesampson/scoop-extras/blob/fc6387d5bd437e13ca28ce04384e166a40e31eba/tortoisesvn.json#L2

**Comment by r15ch13** [comment]
Oh! I didn't update the GUID ... Try uninstalling it from "Programs and Features" and reinstall it with scoop. (don't forget `scoop update`)

**Comment by r15ch13** [comment]
https://github.com/lukesampson/scoop-extras/commit/fef31dd4d901163c6724fb41d5ee755e455f3ac4

**Comment by sim4life** [comment]
I've done `scoop update` and run `scoop reset tortoisesvn`, which worked fine. However, `scoop update tortoisesvn` and `scoop uninstall tortoisesvn` still aren't working.
Any suggestions?

**Comment by r15ch13** [comment]
update/install/uninstall should all show the `UAC`. I had no issues on my machine. All of these commands will fail if any file is currently in use.
Is there some console output or error message you could share (also for the `ditto` problem)?

**Comment by sim4life** [comment]
`PS > scoop update tortoisesvn` and `PS > scoop uninstall tortoisesvn` show:
Running uninstaller...
Dialog box: Are you sure you want to uninstall this product? 'Yes' : 'No'
On 'Yes' --> Error dialog: 'This action is valid only for products that are currently installed'
Moreover, tortoisesvn doesn't show up on Add/Remove programs.

`PS > scoop install tortoisesvn`
WARN  'tortoisesvn' (1.9.5) is already installed.
Use 'scoop update tortoisesvn' to install a new version.
Moreoever, `~\scoop\apps\tortoisesvn` does show directories: 1.9.5 and current.
Mode of 1.9.5 is da----
Mode of current is d-r--l
The content of 1.9.5 is:
Program Files (dir) - this has the tortoisesvn installed files
install.json
manifest.json
msiexex.exe

**Comment by r15ch13** [comment]
Try running the `msi` from scoops cache directory and uninstall it normally.
Remove the tortoise directory from scoops apps directory and try it again.

**Comment by sim4life** [comment]
The msi in scoop cache directory was not an uninstaller but a installer. I removed that plus the tortoisesvn directory in scoop\apps directory. Afterwards, I ran `scoop install tortoisesvn` that ran fine. Now, I have tortoisesvn 1.9.7 installed on my system. Thnx!
