### ISSUE TITLE
scoop cleanup oraclejdk didn't uninstall

### ISSUE THREAD

**Issue by gabrieljones** [lukesampson/scoop#1939]
I wanted to uninstall older versions of oraclejdk.
Ran:
```
PS C:\> scoop cleanup oraclejdk
Removing oraclejdk: 8u131-b11 8u144-b01
```
but they were still visible in `Add Remove Programs`

**Comment by r15ch13** [comment]
To uninstall a program you have to run: `scoop uninstall oraclejdk`
`cleanup` just removes the downloaded setup file from the cache.
