### ISSUE TITLE
Feature request: Pin a version

### ISSUE THREAD

**Issue by dsbert** [lukesampson/scoop#1941]
Add the ability to pin a package to a particular version.

When running `scoop status`, the latest version should be displayed with a note indicating the software is pinned to the current version.

Running `scoop update *` or `scoop update [package]` will not update the pinned package.

**Comment by r15ch13** [comment]
Every installed program has an `install.json`. Adding a property and checking for it should be easy. A new option for `install` or a separate `pin` command could be used to add the property.

**Comment by JaneX8** [comment]
This feature request was closed by a merge of another feature. 

I like the hold/unhold feature but it's not the same as version pinning. See [this Hadolint (a Dockerfile linter) documentation](https://github.com/hadolint/hadolint/wiki/DL3018) for an example of version pinning in Dockerfiles that use Alpine.

Problematic code: `apk --no-cache add foo`
Partial pin glob: `apk --no-cache add foo=~1.2.3`
Exact pin: `apk --no-cache add foo=1.2.3` 

> Pinning exact versions can cause future builds to suddenly fail if that version is no longer available. Use with caution.

According to the [Docker best practices rationale](https://docs.docker.com/build/building/best-practices/#run):

> Version pinning forces the build to retrieve a particular version regardless of what’s in the cache. This technique can also reduce failures due to unanticipated changes in required packages.

I'd really like to see a similar version pinning mechanism for scoop.
