### ISSUE TITLE
scoop checkup could check NTFS-ness

### ISSUE THREAD

**Issue by mdaniel** [lukesampson/scoop#1944]
- Current behavior: `scoop install $thing` fails due to `$env:SCOOP` living on an ExFAT drive

  `scoop checkup` did not verify that `$env:SCOOP` (and presumably its `$env:SCOOP_GLOBAL` friend) resides on an NTFS volume
- Expected behavior: `scoop checkup` would report "Scoop requires an NTFS volume to work" (optionally including ~to work~ "to make use of junction links", if the primary audience is technical folks, since I bet that is the clearest)

I have an SSD for my primary volume, and put development stuff (Maven home, most git checkouts, that kind of thing) on the larger, non-Windows volume. For historical, cross-OS reasons, that volume is ExFAT, not NTFS. So, when I pointed `$env:SCOOP` at `d:\Scoop`, things did not end well.

```
PS D:\> scoop install sudo
Scoop was updated successfully!
Installing 'sudo' (0.2017.03.24) [64bit]
sudo.ps1 (2.0 KB) [===========================================================================================] 100%
Checking hash of sudo.ps1... ok.
Linking D:\Scoop\apps\sudo\current => D:\Scoop\apps\sudo\0.2017.03.24
Local NTFS volumes are required to complete the operation.
Creating shim for 'sudo'.
% : Exception calling "GetUnresolvedProviderPathFromPSPath" with "1" argument(s): "Cannot find drive. A drive with the name 'File not found - D' does not exist."
At D:\Scoop\apps\scoop\current\lib\install.ps1:678 char:34
+     $shims | ?{ $_ -ne $null } | % {
+                                  ~~~
+ CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
+ FullyQualifiedErrorId : DriveNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand
```

**Comment by r15ch13** [comment]
Something like this: https://github.com/lukesampson/scoop/commit/43a02b2a3bd8efd520832d693f0a507bef1f0caf

**Comment by mdaniel** [comment]
You're very kind, thank you for actioning that so quickly!

(As a friendly reminder, you can also [close this issue](https://help.github.com/articles/closing-issues-using-keywords/) with that commit, unless you were expecting more commits to follow)

**Comment by r15ch13** [comment]
@mdaniel Thanks for the friendly reminder. 😉 Just forgot to add it 😄
