### ISSUE TITLE
Unzip fails because of illegal character in path

### ISSUE THREAD

**Issue by BjoernPetersen** [lukesampson/scoop#1946]
I'm trying to create an app manifest for NeoRouter, but scoop throws an error when it unzips the downloaded file.

The name of file in the cache directory doesn't seem to contain any weird characters, so I'm not sure what's going on here.
`neorouter#2.3.2.4450#https_download.neorouter.com_Downloads_NRFree_Update_2.3.2.4450_Windows_NeoRouterPortable-2.3.2.4450-free.zip`
### Used app manifest
In my bucket repo [here](https://github.com/BjoernPetersen/scoop-bucket/blob/master/neorouter.json)

### Scoop output
```
~ $ scoop install neorouter
Installing 'neorouter' (2.3.2.4450) [64bit]
NeoRouterPortable-2.3.2.4450-free.zip (5,8 MB) [==========================================] 100%
Checking hash of NeoRouterPortable-2.3.2.4450-free.zip... ok.
Extracting... Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "Illegal characters in path."
```

**Comment by r15ch13** [comment]
Append `#/dl.7z` to the URL (don't forget the autoupdate URL) to enforce the use of 7zip. This works for me.

**Comment by BjoernPetersen** [comment]
Huh, thanks!
