### ISSUE TITLE
Install/use older versions of ruby

### ISSUE THREAD

**Issue by Hazardius** [lukesampson/scoop#1957]
Recently a new version of ruby for Windows was released by [RubyInstaller](https://github.com/oneclick/rubyinstaller2). Scoop started using it rather fast, but that caused some issues. There are some fat gems that needs to be updated for rails to work fine with new ruby.

With that in mind - I couldn't find a way to use different rubies than "the latest 2.x" and "the latest 1.9.x".
Is there a way to do that now? If not - could it be worth adding?

Examples of issues for various gems:
[nokogiri#1706](https://github.com/sparklemotion/nokogiri/issues/1706), [ffi#598](https://github.com/ffi/ffi/issues/598)

There's an [bundler#6247](https://github.com/bundler/bundler/pull/6247) trying to help with this issue.

Personally - on most of my systems I use [chruby](https://github.com/postmodern/chruby) for rubies management, but didn't try it out yet with scoop - just sticked with it's last version - 2.4.2.

**Comment by asmgf** [comment]
@Hazardius, you can try something like `scoop install ruby@2.4.2-2`.

**Comment by TrumanCai** [comment]
@asmgf it works.

**Comment by Hazardius** [comment]
@asmgf , thank you very much for help.
I'm thinking that maybe this method could be mentioned on the [Switching Ruby and Python Versions page](https://github.com/lukesampson/scoop/wiki/Switching-Ruby-and-Python-Versions). Right now I only found out that scoop "Can't install a specific version of a program." on the [Chocolatey Comparison page](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison).

**Comment by yeikel** [comment]
Latest doc states that "Can't always install a specific version of a program" so it is technically supported

**Comment by Hazardius** [comment]
Thanks @rasa for making a change in the docs and @yeikel for letting me know so I can now close that issue.
