### ISSUE TITLE
Apostrophe in username

### ISSUE THREAD

**Issue by ddamico** [lukesampson/scoop#196]
Hi there scoop contributors! Just found the project but so far it seems great.

Was wondering if you could help me out with an issue. I work in a fairly large organization, and their admins were nice enough to give me a domain username with an apostrophe in it. Which as far as I can tell is a legal windows username, but seems like SUCH a bad idea. Predictably, this is breaking things. I'm just speculating here since I can't tell if this is the *direct* problem or just a symptom of bad interaction between my env variables and other things, but I'm definitely running into problems when running your scripts, since the shims path for example, ends up looking like 'C:\Users\d'amicod\appdata\local\scoop\shims\scoop.ps'.

Fully recognizing that the smart change here would be "don't have a username with an apostrophe in it," I'm wondering if there's any chance of you adding escaping for these paths so that I can get scoop working on my system?

Thanks!

**Comment by deevus** [comment]
@ddamico can you please see if this is fixed for you?

**Comment by ddamico** [comment]
Yup, just gave it a try and the issue seems to be gone. Thanks very much!

**Comment by deevus** [comment]
You're welcome
