### ISSUE TITLE
7zip - Installation doesn't include explorer addons

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop#1962]
When using scoop to install 7zip, the explorer addons (Right Click - 7-zip menu) isn't installed.    

When using the 7-zip installer or MSI package from the 7-zip site, the explorer addons are installed.   Not sure if this is a bug or intended but I've personally become dependent on the 7-zip menu because it's so much faster than using Windows's built in compressed file handling.

**Comment by r15ch13** [comment]
Open the 7-Zip File Manager, go to `Extras` > `Options` > `7-Zip`. There you can configure the context menu elements. (If it doesn't work, try running 7zFM as admin)

**Comment by nirvdrum** [comment]
Please note that the option is now under `Tools` > `Options` > `7-Zip` (tested with 7zip 18.05).

**Comment by nirvdrum** [comment]
Agreed. I just came across this issue while searching for an automated way of doing it with scoop. While running through the manual steps above, I found the menu item had changed. It'd be great if I didn't have to do that at all. But at least this search result ranks highly.

**Comment by wackydude** [comment]
Here is the optimal experience in my opinion:

- $ scoop install 7zip => installs 7-Zip, registers 7-Zip as default Windows decompression app, adds 7-Zip right click context menu option
- Download a zip file via browser => download is displayed near bottom of browser
- Left-click file download  => launches 7-Zip, creates new folder in download directory with same name as zip file (sans .zip extension), extracts to this new folder, opens this new folder (so I can then double click the .exe installer)

**Comment by idbrii** [comment]
If anyone feels up to setting up the .reg, you can copy the scoop changes from https://github.com/ScoopInstaller/Main/pull/846/files

To figure out the .reg, I'd recommend just setting up the context menu with 7z, exporting it from regedit, and inserting the variable names.

**Comment by wlad** [comment]
Solution above does not work for me even when starting 7zip as admin:

![image](https://user-images.githubusercontent.com/64201310/82043004-24d90d80-96ab-11ea-8f34-7217a8c3be09.png)

Worth to note my 7-zip was installed as a dependency of git e.g. `scoop install git`

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F1962

**Comment by idbrii** [comment]
Equivalent issue was opened in Main: ScoopInstaller/Main#813
