### ISSUE TITLE
Adding yasm to Scoop

### ISSUE THREAD

**Issue by Calinou** [lukesampson/scoop#1963]
[Yasm](http://yasm.tortall.net) is a modular assembler used on NASM; it's sometimes required for compiling software such as Godot (since VP8/VP9 make use of it), so it's nice to be able to install it with a single command.

The recommended official download comes as a single executable (it's not an installer). I wrote a `yasm.json` descriptor file, see below:

```
{
    "description": "Modular assembler based on NASM",
    "homepage": "http://yasm.tortall.net/",
    "license": "BSD 3-Clause",
    "version": "1.3.0",
    "architecture": {
        "64bit": {
            "hash": "d160b1d97266f3f28a71b4420a0ad2cd088a7977c2dd3b25af155652d8d8d91f",
            "url": "http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe"
        },
        "32bit": {
            "hash": "db8ef9348ae858354cee4cc2f99e0f36de8a47a121de4cfeea5a16d45dd5ac1b",
            "url": "http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe"
        }
    },
    "pre_install": "Get-Item \"yasm-*.exe\" | Rename-Item -NewName \"yasm.exe\"",
    "bin": [
        "yasm.exe"
    ],
    "checkver": {
        "url": "https://yasm.tortall.net/Download.html",
        "re": "Latest Release: [\\d.]+"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "http://www.tortall.net/projects/yasm/releases/yasm-$version-win64.exe"
            },
            "32bit": {
                "url": "http://www.tortall.net/projects/yasm/releases/yasm-$version-win32.exe"
            }
        }
    }
}
```

However, I cannot get the `pre_install` step to work (which is supposed to rename the binary to `yasm.exe`, regardless of version and architecture); I've tried both `Get-Item` and `Get-ChildItem` in the PowerShell command, which I based on [the pre-install step in `shellcheck.json`](https://github.com/lukesampson/scoop/blob/5f58bdcadc7fe295a146e47c2f47e63cb970be03/bucket/shellcheck.json#L9). See the error log below:

```
Installing 'yasm' (1.3.0) [64bit]
yasm-1.3.0-win64.exe (610.0 KB) [========] 100%
Checking hash of yasm-1.3.0-win64.exe... ok.
Running pre-install script...
Linking ~\scoop\apps\yasm\current => ~\scoop\apps\yasm\1.3.0
Creating shim for 'yasm'.
Can't shim 'yasm.exe': File doesn't exist.
```

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by r15ch13** [comment]
Just append `#/yasm.exe` to all URLs and the renaming is done by scoop. No `pre_install` script needed :+1:

**Comment by Calinou** [comment]
https://github.com/lukesampson/scoop/pull/1964
