### ISSUE TITLE
vagrant: warnings about initialized constants

### ISSUE THREAD

**Issue by AEtherSurfer** [lukesampson/scoop#1970]
See for further discussion https://github.com/hashicorp/vagrant/issues/8782

**Comment by Crx4** [comment]
@AEtherSurfer isn't this warnings related to scoop beacuse I think scoop adds the path entries of the vagrant? the discussion above does not offer any solution they suggest not to use scoop :sur

**Comment by Hazardius** [comment]
I agree with @Crx4 . As annoying as it is - that's more on a vagrant having issues with using soft links. [There's one solution to the issue](https://github.com/hashicorp/vagrant/issues/8782#issuecomment-327981675), but to be honest - it's more like a workaround.

Personally, for now I just ignore the messages.

**Comment by rasa** [comment]
Obsolete
