### ISSUE TITLE
Error with askpass in OpenSSH

### ISSUE THREAD

**Issue by johnnyasantoss** [lukesampson/scoop#1973]
Hello!
I'm having a issue with a executable called *askpass*. I believe that there's a error in its calling script.

The error appears every time I open a new powershell session.

![askpass](https://user-images.githubusercontent.com/14189387/35272465-6bb0c90a-001c-11e8-8460-5c592ccc5c35.png)

```
λ» scoop list
Installed apps:

  pshazz 0.2017.03.22
  sudo 0.2017.03.24
```

**Comment by Deide** [comment]
I use the win32-openssh port instead and it works fine. Install with scoop then run the install script as mentioned [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH).

**Comment by johnnyasantoss** [comment]
I removed pshazz and reinstalled OpenSSH. It is working now, thx!
