### ISSUE TITLE
7zip Beta version

### ISSUE THREAD

**Issue by dsbert** [lukesampson/scoop#1977]
The 7Zip beta version (18.00) has fixes for some security vulnerabilities (https://landave.io/2018/01/7-zip-multiple-memory-corruptions-via-rar-and-zip)

Since 7Zip beta versions tend to stay beta for a long time (17.00 has been beta for 9 months), does it make sense to have a beta package or a beta flag for this?

**Comment by rasa** [comment]
I have it at
https://github.com/rasa/scoops/blob/master/7zip-beta.json
but perhaps we should add a beta bucket, say, https://github.com/lukesampson/scoop-beta ?

**Comment by brandon93s** [comment]
There is currently a "nightlies" bucket, so a "beta" bucket would make sense. Alternatively, consolidate into a single "pre-release" bucket and have separate manifests per channel:

- 7zip-nightly.json
- 7zip-alpha.json
- 7zip-beta.json

**Comment by rasa** [comment]
That works, the less buckets the better. Perhaps we just expand the versions bucket to include not just old versions but alpha/beta/nightlies, as well? There's only 1 app in nightlies, so perhaps we retire that bucket.

**Comment by brandon93s** [comment]
Yep, I like that even better.

**Comment by r15ch13** [comment]
@rasa good idea 👍

**Comment by rasa** [comment]
OK, I'll start off by moving my 7zip-beta to versions.

**Comment by rasa** [comment]
This issue can be closed.

**Comment by r15ch13** [comment]
@rasa why did you close the versions PR?

**Comment by rasa** [comment]
Because production is at 18.01 (https://github.com/lukesampson/scoop/blob/master/bucket/7zip.json) but I reopened.
