### ISSUE TITLE
Error message when updating Scoop

### ISSUE THREAD

**Issue by benplm** [lukesampson/scoop#1978]
I get an error message any time scoop updates, either when I run `scoop update` or when it updates prior to installing a new package. Here's the output:

```
C:\Users\bpoli> scoop install shasum
Updating Scoop...
out-file : Accesso al percorso 'C:\Users\bpoli\.scoop' negato.
In C:\Users\bpoli\scoop\apps\scoop\current\lib\config.ps1:56 car:27
+     convertto-json $cfg | out-file $cfgpath -encoding utf8
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Scoop was updated successfully!
Installing 'shasum' (0.2013.09.29) [64bit]
```
(third line roughly translates to `Access to 'C:\Users\bpoli\.scoop' denied.`)

As you can see, the error message doesn't prevent it to update or installing packages. However, I'm wondering if there's something broken in my scoop installation that can be fixed, to prevent this message to pop-up.

**Comment by benplm** [comment]
So, the cause was that the file .scoop was hidden. This makes it inaccessible by config.ps1 somehow. Also, while this did not prevent me to update scoop, it prevented me to create aliases. Is that expected?

**Comment by stkb** [comment]
Hi, I've created a PR to fix this.

**Comment by benplm** [comment]
It's fixed now. Thanks!
