### ISSUE TITLE
Strip filename components during extraction

### ISSUE THREAD

**Issue by excitoon** [lukesampson/scoop#1987]
Can we have an option to strip leading components from file names on extraction?
It will be useful for extracting files like these where there is the directory on top level:
[ftp://ftp.zlatkovic.com/libxml/](ftp://ftp.zlatkovic.com/libxml/)

**Comment by r15ch13** [comment]
Do you mean [`extract_dir`](https://github.com/lukesampson/scoop/wiki/App-Manifests)? See [aria2.json](https://github.com/lukesampson/scoop/blob/master/bucket/aria2.json) or [casperjs.json](https://github.com/lukesampson/scoop/blob/master/bucket/casperjs.json) for example.

**Comment by excitoon** [comment]
Yeah. I haven't figured it out by myself.

**Comment by excitoon** [comment]
Actually, I did look through the documentation:
> Scoop will extract just the directory specified from it

It says only that Scoop will extract that directory but nothing about that it will place its contents into `$dir` without extra subfolder(s). :)
