### ISSUE TITLE
rustup hash failing

### ISSUE THREAD

**Issue by gdoenlen** [lukesampson/scoop#1988]
Hi the hash of rustup is failing. It looks like the json file was updated 2 days ago, maybe something wasn't updated properly?

Installing 'rustup' (1.10.0) [64bit]                                                                                    C:\ (12.5 MB) [===============================================================================================] 100%    Checking hash of C:\... Hash check failed for 'https://win.rustup.rs/#/rustup-init.exe'.                                Expected:                                                                                                                   4b15001d67e7a695de95bd212505312b471b76f363057db54bb1c042c3e4cc4a                                                    Actual:                                                                                                                     c7911ada606fb863d79280865d89ad97053f2e3359e05c9b47f19af6acd002b1

**Comment by r15ch13** [comment]
Fixed

**Comment by gdoenlen** [comment]
Thanks for being so quick! @r15ch13

**Comment by miarka** [comment]
I have a similar issue now with 1.11 .
Bucket seems to be updated, but hash check is failing.

`Installing 'rustup' (1.11.0) [64bit]
C:\ (4,5 MB) [========================================================] 100%`
`Checking hash of C:\... Hash check failed for 'https://win.rustup.rs/#/rustup-init.exe'.`
`Expected: 9fb54832bc896cd4c0c8027e02ec580a8263dde7831fa3f2d9f7ad61849a77fe`
`Actual: b33a82c54199a427172fec8957760ae7c9a7b7a13b0814bdddb4438e7f88e801`

**Comment by r15ch13** [comment]
@miarka fixed with https://github.com/lukesampson/scoop/commit/87b2b089336ee4ed690c523e1e0fecb85cabfd74
