### ISSUE TITLE
scoop update crashed git and not a git repo errors

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#2001]
i cannot update scoop today and i think that maybe something broken because of my files. after fresh install problem still exist! git is working fine in another folders.

```
PS C:\Users\yigit\scoop\apps\scoop\current> scoop status
WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.
PS C:\Users\yigit\scoop\apps\scoop\current> scoop update
Updating Scoop...
Scoop update failed.
PS C:\Users\yigit\scoop\apps\scoop\current> #git for windows crashed while trying to update scoop
PS C:\Users\yigit\scoop\apps\scoop\current> git status
fatal: Not a git repository (or any of the parent directories): .git
PS C:\Users\yigit\scoop\apps\scoop\current> ls


    Directory: C:\Users\yigit\scoop\apps\scoop\current


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         03-02-18     14:53                bin
d-----         03-02-18     14:53                bucket
d-----         03-02-18     14:53                lib
d-----         03-02-18     14:53                libexec
d-----         03-02-18     14:53                supporting
d-----         03-02-18     14:53                test
-a----         03-02-18     03:00            459 .editorconfig
-a----         03-02-18     03:00            123 .gitattributes
-a----         03-02-18     03:00             87 .gitignore
-a----         03-02-18     03:00            589 appveyor.yml
-a----         03-02-18     03:00            459 buckets.json
-a----         03-02-18     03:00           1235 LICENSE
-a----         03-02-18     03:00           2879 README.md
-a----         03-02-18     03:00          14797 schema.json
-a----         03-02-18     03:00            293 scoop.sublime-project


PS C:\Users\yigit\scoop\apps\scoop\current>

```

**Comment by lfkid** [comment]
Today I also encountered this problem after I update git.
I do not know if this error was caused by git or scoop.
But yesterday there is no such problem.
![image](https://user-images.githubusercontent.com/16191685/35767030-d782c740-091e-11e8-99de-a06777f3889a.png)

![image](https://user-images.githubusercontent.com/16191685/35767069-7b3e61dc-091f-11e8-9631-cbfa98ddb1d4.png)

translate: Git for Windows has stopped working

**Comment by yigitemres** [comment]
@lfkid can you go to "scoop\apps\scoop\current" folder and type "git status"?

**Comment by oltolm** [comment]
I also have this problem.
```
git --version
git version 2.16.1.windows.2
```
If I do a `git pull` in the `scoop` repository then git crashes.

**Comment by lfkid** [comment]
@yigitemres  thanks for the reply.
yeah, this is the result:
 
![image](https://user-images.githubusercontent.com/16191685/35767131-0ccb942a-0921-11e8-8c63-e15d1ed21345.png)

**Comment by yigitemres** [comment]
@oltolm can you go to "~\scoop\apps\scoop\current" folder and type "git status", too?

**Comment by yigitemres** [comment]
@lfkid our problems and possibly @oltolm problems are identical. something broken in current scoop build.

**Comment by oltolm** [comment]
```
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by yigitemres** [comment]
@oltolm thats interesting. mine git status says "its not git repo". another weird thing is that when i trying to pull/fetch upstream local scoop fork, git also crashed.

**Comment by SummerSad** [comment]
May be it was git bug. I try to run git manually (not install from scoop) and get same error. Roll back to 2.16.1.windows.1 version seems work for me.

**Comment by yigitemres** [comment]
@SummerSad cant rollback either.
```
PS C:\Users\yigit\Desktop> scoop install git@2.16.1.windows.1
Scoop uses Git to update itself. Run 'scoop install git' and try again.
WARN  Given version (2.16.1.windows.1) does not match manifest (2.16.1.windows.2)
WARN  Attempting to generate manifest for 'git' (2.16.1.windows.1)
Autoupdating git
Downloading PortableGit-$matchShort-32-bit.7z.exe to compute hashes!
The request was aborted: The connection was closed unexpectedly.
URL https://github.com/git-for-windows/git/releases/download/v$matchVersion/PortableGit-$matchShort-32-bit.7z.exe#/dl.7z is not valid
Could not find hash!
Could not install git@2.16.1.windows.1
```

**Comment by kvnklk** [comment]
What I did:

Download `2.16.1.w.1` manually from here: https://github.com/git-for-windows/git/releases (Direct Link for x64: [click](https://github.com/git-for-windows/git/releases/download/v2.16.1.windows.1/PortableGit-2.16.1-64-bit.7z.exe)

Extract it, copy and overwrite the content to: `C:\Users\USER\scoop\apps\git`
Reopened Powershell (not sure if needed, did it just in case)

```
PS C:\Users\foobar> git --version
git version 2.16.1.windows.1
```

**Comment by r15ch13** [comment]
This is definitely a problem with git (`git-remote-https.exe`)
I downgraded it to version `2.16.1.windows.1` and locked the auto-update. Try reinstalling it.

**Comment by yigitemres** [comment]
@r15ch13 thank you. can you downgrade git-with-openssh repo too?

**Comment by r15ch13** [comment]
@yigitemres done 😁

**Comment by yigitemres** [comment]
@r15ch13 when i ever want something from you, i feel very ashamed because i cant help this wonderful project as much as you guys do. thank you! 🥇

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/pull/2007 and https://github.com/lukesampson/scoop/pull/2008
