### ISSUE TITLE
Support TLS 1.2 - "Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by crazy4cs** [lukesampson/scoop#2040]
- [X] `set-executionpolicy remotesigned -s currentuser` has been ran
- [X] PowerShell 3 or greater is installed
```
PS C:\WINDOWS\system32> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  248
```

```
iex : Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

The scoop directory is created within the user profile folder, as well as the %USERPROFILE%\scoop\apps\scoop\current directory, however, they are both empty.

**Comment by hss-dev** [comment]
My colleague has just tried to install Scoop and also got this problem. I installed it last week and it was fine.

**Comment by r15ch13** [comment]
What's the output of `Get-ExecutionPolicy -List`?

**Comment by hss-dev** [comment]
My colleagues settings were

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine       RemoteSigned

**Comment by andreiodi** [comment]
Hello I'm having the same issue

**Comment by andreiodi** [comment]
`PS C:\Users\chere> [Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls
PS C:\Users\chere>`

**Comment by andreiodi** [comment]
And if I try to install it again it says:

> PS C:\Users\chere> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\chere> scoop update
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
>At line:1 char:1
>+ scoop update
>+ ~~~~~
 >   + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
 >  + FullyQualifiedErrorId : CommandNotFoundException

>PS C:\Users\chere>

**Comment by covertcj** [comment]
I just ran into this as well on a 'fresh' install of Windows 10 (it was installed from a base image provided by the IT dept, for whatever that's worth).  I found that I was able to delete the ~/scoop directory, run the command:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

directly in my prompt, and then re-install with the standard method.  That being said, it seems I need to re-run that command in each new powershell window, or I see a bunch of SSL/TLS errors any time I use scoop.

**Comment by masaeedu** [comment]
You can put `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` in your Powershell profile (`notepad $PROFILE`) as a workaround. It seems like something's changed on github's side so they no longer accept TLSv1, which winhttp uses by default. There's also stuff you can fiddle with in the registry to get winhttp to use TLSv1.2 instead.

**Comment by tresf** [comment]
Just updated Windows 10 today and I'm receiving this.  I've tried the above suggestions without much luck, although the symptoms are the same, my error is a bit different.

```
PS C:\Users\Tres> scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Update failed.
```

I've tried setting the registry flag to force WinHttp to a higher TLS version, but it's not working on my machine or my steps are incorrect.

The suggestion to use `notepad $PROFILE` doesn't seem to work on my installation, I'm not sure what that does.  My scoop version is `ef058e9 Update fnproject to version 0.4.34`.

**Comment by masaeedu** [comment]
@tresf `notepad $PROFILE` doesn't do anything by itself, it's just supposed to open your Powershell profile file for editing. In that file you need to add `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`. Before adding it to your profile file, you can test out whether the incorrect TLS version is causing your issue by just running this command in a powershell session right before `scoop update`.

**Comment by tresf** [comment]
>  you can test out whether the incorrect TLS version is causing your issue by just running this command in a powershell session right before scoop update.

I wasn't able to get either proposal to help... 
* `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`
* `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

I also removed `~/scoop` and reinstalled through the `iex ...` command from scoop.sh to no avail.

> @tresf notepad $PROFILE doesn't do anything by itself, it's just supposed to open your Powershell profile file for editing. 

I understood that much, the command just didn't work.  Thanks for the reply!

**Comment by tresf** [comment]
Apologies... My issue was a botched `git-scm` after the Windows 10 updates.  The fix was to completely purge all git versions and reinstall.  Interestingly enough, the default `git` location changed from `C:\Program Files (x86)\` to `C:\Program Files\` but my system did not reflect it, so this seems to be unrelated to the original bug report and fixed by repairing `git` through some manual steps.

**Comment by jordanbtucker** [comment]
@masaeedu Is there a work around for this when using the command prompt? Having to use scoop exclusively in PowerShell is inconvenient.

**Comment by r15ch13** [comment]
Scoop has these to functions to set enable every available protocol for downloading apps:
https://github.com/lukesampson/scoop/blob/f8f08db7e53f624b4c81f5d61e8d16c8176a13a7/lib/install.ps1#L117-L133

Currently they are only used in `do_dl()`, [checkver.ps1](https://github.com/lukesampson/scoop/blob/f8f08db7e53f624b4c81f5d61e8d16c8176a13a7/bin/checkver.ps1#L46) and [checkurls.ps1](https://github.com/lukesampson/scoop/blob/master/bin/checkurls.ps1#L28)
https://github.com/lukesampson/scoop/blob/f8f08db7e53f624b4c81f5d61e8d16c8176a13a7/lib/install.ps1#L135-L149

Adding them to all other commands that require downloading something could fix it.

**Comment by h404bi** [comment]
https://github.com/blog/2507-weak-cryptographic-standards-removed
Does the change of GitHub affect this issue?

**Comment by r15ch13** [comment]
@h404bi that is the main cause of this issue 😁

**Comment by kvnklk** [comment]
Currently using this in a `.bat` on fresh installed systems:

```
@echo off
COLOR 1F

set filePath="%userprofile%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

IF EXIST $filePath (GOTO appendTLS) else (GOTO newTLS)

:appendTLS
(
echo.
echo [Net.ServicePointManager]::SecurityProtocol = ^"tls12, tls11, tls^"
) >> "%filePath%"

:newTLS
mkdir "%userprofile%\Documents\WindowsPowerShell\"
(
echo [Net.ServicePointManager]::SecurityProtocol = ^"tls12, tls11, tls^"
) > "%filePath%"


@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -InputFormat None -ExecutionPolicy RemoteSigned -Command "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')"
```

But obviously need `Set-ExecutionPolicy RemoteSigned -s cu`

**Comment by tresf** [comment]
> @tresf notepad $PROFILE doesn't do anything by itself, it's just supposed to open your Powershell profile file for editing.

Turns out this command fails on systems without a `~/PowerShell` folder.

I ran into this today with Windows 7 SP1.  Here's a little script that should help.

```ps1
mkdir $PROFILE\..
echo '[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"' >> $PROFILE
& $PROFILE
# thats it
```

**Comment by sharh** [comment]
> Prepare, do this in `PowerShell`:

`set-executionpolicy remotesigned -s currentuser` 

And input `Y` to ensure.

----
Open `https://get.scoop.sh` in your browser to download the shellscript, save as `install.ps1`:
```sh
#requires -v 3

# remote install:
#   iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
$erroractionpreference = 'stop' # quit if anything goes wrong

if(($PSVersionTable.PSVersion.Major) -lt 3) {
    Write-Output "PowerShell 3 or greater is required to run Scoop."
    Write-Output "Upgrade PowerShell: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell"
    break
}

# show notification to change execution policy:
if((get-executionpolicy) -gt 'RemoteSigned') {
    Write-Output "PowerShell requires an execution policy of 'RemoteSigned' to run Scoop."
    Write-Output "To make this change please run:"
    Write-Output "'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'"
    break
}

# get core functions
$core_url = 'https://raw.github.com/lukesampson/scoop/master/lib/core.ps1'
Write-Output 'Initializing...'
Invoke-Expression (new-object net.webclient).downloadstring($core_url)

# prep
if(installed 'scoop') {
    write-host "Scoop is already installed. Run 'scoop update' to get the latest version." -f red
    # don't abort if invoked with iex——that would close the PS session
    if($myinvocation.mycommand.commandtype -eq 'Script') { return } else { exit 1 }
}
$dir = ensure (versiondir 'scoop' 'current')

# download scoop zip
$zipurl = 'https://github.com/lukesampson/scoop/archive/master.zip'
$zipfile = "$dir\scoop.zip"
Write-Output 'Downloading...'
dl $zipurl $zipfile

'Extracting...'
unzip $zipfile "$dir\_tmp"
Copy-Item "$dir\_tmp\scoop-master\*" $dir -r -force
Remove-Item "$dir\_tmp" -r -force
Remove-Item $zipfile

Write-Output 'Creating shim...'
shim "$dir\bin\scoop.ps1" $false

ensure_robocopy_in_path
ensure_scoop_in_path
success 'Scoop was installed successfully!'
Write-Output "Type 'scoop help' for instructions."
```
find `$zipurl`:

> $zipurl = 'https://github.com/lukesampson/scoop/archive/master.zip'

**Find zipurl**: `https://github.com/lukesampson/scoop/archive/master.zip`, download it, and unzip it in the scoop's dir:
`%USERPROFILE%\scoop\apps\scoop\current`

Or you can change the `install.ps1` script, to see where scoop dir is:

```sh
Write-Output 'Downloading...'
# this will print scoop dir
Write-Output '$dir'
```
Then modify the `install.ps1`，it should be below:
```sh
#requires -v 3

# remote install:
#   iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
$erroractionpreference = 'stop' # quit if anything goes wrong

if(($PSVersionTable.PSVersion.Major) -lt 3) {
    Write-Output "PowerShell 3 or greater is required to run Scoop."
    Write-Output "Upgrade PowerShell: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell"
    break
}

# show notification to change execution policy:
if((get-executionpolicy) -gt 'RemoteSigned') {
    Write-Output "PowerShell requires an execution policy of 'RemoteSigned' to run Scoop."
    Write-Output "To make this change please run:"
    Write-Output "'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'"
    break
}

# get core functions
$core_url = 'https://raw.github.com/lukesampson/scoop/master/lib/core.ps1'
Write-Output 'Initializing...'
Invoke-Expression (new-object net.webclient).downloadstring($core_url)

# prep
$dir = ensure (versiondir 'scoop' 'current')
Write-Output "$dir"
# download scoop zip
# $zipurl = 'https://github.com/lukesampson/scoop/archive/master.zip'
$zipfile = "$dir\scoop.zip"
# Write-Output 'Downloading...'
# comment dl command, download zipfile yourself.
# dl $zipurl $zipfile

'Extracting...'
# notice to comment unzip, otherwise there will be an error of unzip. You should unzip with winrar yourself
# the zip file should unzip in $dir\_tmp yourself
# unzip $zipfile "$dir\_tmp"
Copy-Item "$dir\_tmp\scoop-master\*" $dir -r -force
Remove-Item "$dir\_tmp" -r -force
Remove-Item $zipfile

Write-Output 'Creating shim...'
shim "$dir\bin\scoop.ps1" $false

ensure_robocopy_in_path
ensure_scoop_in_path
success 'Scoop was installed successfully!'
Write-Output "Type 'scoop help' for instructions."

```
save `install.ps1`, ** then drag it  **into `PowerShell`, and then press enter, after a moment:
`Scoop was installed successfully!`

**Comment by h404bi** [comment]
One line PowerShell command for new installation, if someone is looking for workaround:

``` powershell
set-executionpolicy remotesigned -s currentuser; [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192 -bor 48; iwr https://get.scoop.sh -UseBasicParsing | iex
```

**Comment by danielgary** [comment]
If I had to guess, the schoop.sh website is probably using a certificate from StartSSL.  As they are no longer a trusted cert authority, the download is failing.  If you browse to https://scoop.sh you'll get a security warning about the certificate.  Should be easy to fix with a new certificate.

**Comment by h404bi** [comment]
@danielgary nope, scoop.sh didn't have ssl, it's a CNAME of scoop's gh-pages. And https://get.scoop.sh redirects to https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1

GitHub drops TLSv1 support cause this issue.

**Comment by r15ch13** [comment]
@danielgary ugh, thanks for pointing this out. I contacted @lukesampson about this.

**Comment by masaeedu** [comment]
@h404bi I don't think the one line solution will work, `scoop` frequently consults the buckets (which are on github), post-install. This means you need to have the TLS settings in every powershell instance you start; i.e. you need to put it in your profile.

**Comment by h404bi** [comment]
@masaeedu I said that's a workaround for fresh installation. Though I have tested on a fresh install windows 10, fresh install scoop with that command, then just install git-with-openssh, every thing seems fine, scoop update, scoop search, scoop status...

The Windows 10 ServicePointManager:
``` powershell
$ [System.Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls
```

Besides, I search that we could modify the registry of ServicePointManager to permanently force to use strong cryptography, but that's inconvenient and it needs elevated privileges, which is worse.[1]

[1]: https://www.johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications

**Comment by tresf** [comment]
> Besides, I search that we could modify the registry of ServicePointManager to permanently force to use strong cryptography, but that's inconvenient and it needs elevated privileges, which is worse.1

Do you mean for all users?  For the current user, https://github.com/lukesampson/scoop/issues/2040#issuecomment-368145842, @covertcj's solution works great.  I've [adapted @r15ch13's proposal to make it permanent for the current user](https://github.com/lukesampson/scoop/issues/2040#issuecomment-368394955) and this technique was tested on Windows 7.

Is the concern that this won't scale for multiple users?  I would propose that the scoop library internally nudges this since it makes no sense to attempt to continue functioning otherwise.

Even the `set-executionpolicy remotesigned -s currentuser`, I don't entirely understand as this is part of the base scoop.sh install, this command should already have been run 100% of the time.

**Comment by jordanbtucker** [comment]
@h404bi While I agree that scoop should *just work*, setting ServicePointManager to only use TLS 1.1 and higher is something you *should* do anyway since SSLv3 and TLSv1.0 are deprecated due to [POODLE](https://en.wikipedia.org/wiki/POODLE).

**Comment by jordanbtucker** [comment]
@r15ch13 As an alternative to `use_any_https_protocol`, scoop could use [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-3.0), which supports TLS 1.1 and 1.2 by default.

**Comment by r15ch13** [comment]
Was not sure if every site supports TLS 1.2 therefore I created a script to checks all the URLs.
Every single hosts supports it, so it's safe to just enable it I guess.

## Script:
<details>
<summary>protocol-test.ps1</summary>

```powershell
param([String]$dir)

. "$psscriptroot\..\lib\core.ps1"
. "$psscriptroot\..\lib\buckets.ps1"
. "$psscriptroot\..\lib\manifest.ps1"
. "$psscriptroot\..\lib\json.ps1"

# https://www.sysadmins.lv/blog-en/test-web-server-ssltls-protocol-support-with-powershell.aspx
function Test-ServerSSLSupport($HostName) {
    $Port = 443
    $RetValue = New-Object psobject -Property @{
        Host = $HostName
        Port = $Port
        SSLv2 = $false
        SSLv3 = $false
        TLSv1_0 = $false
        TLSv1_1 = $false
        TLSv1_2 = $false
        KeyExhange = $null
        HashAlgorithm = $null
    }
    # "ssl2", "ssl3",
    "tls", "tls11", "tls12" | %{
        $TcpClient = New-Object Net.Sockets.TcpClient
        $TcpClient.Connect($RetValue.Host, $RetValue.Port)
        try {
            $SslStream = New-Object Net.Security.SslStream $TcpClient.GetStream()
        }
        catch {
            write-host $_.Message
            return $RetValue
        }
        $SslStream.ReadTimeout = 15000
        $SslStream.WriteTimeout = 15000
        try {
            $SslStream.AuthenticateAsClient($RetValue.Host,$null,$_,$false)
            $RetValue.KeyExhange = $SslStream.KeyExchangeAlgorithm
            $RetValue.HashAlgorithm = $SslStream.HashAlgorithm
            $status = $true
        } catch {
            $status = $false
        }
        switch ($_) {
            "ssl2" {$RetValue.SSLv2 = $status}
            "ssl3" {$RetValue.SSLv3 = $status}
            "tls" {$RetValue.TLSv1_0 = $status}
            "tls11" {$RetValue.TLSv1_1 = $status}
            "tls12" {$RetValue.TLSv1_2 = $status}
        }
        # dispose objects to prevent memory leaks
        $TcpClient.Dispose()
        $SslStream.Dispose()
    }
    return $RetValue
}


if(!$dir) { $dir = "$psscriptroot\..\bucket" }
$dir = resolve-path $dir

$search = "*"
if($app) { $search = $app }

function test-url($url) {
    $url = [System.Uri]$url
    switch ($url.Host) {
        "sourceforge.net" { break }
        "downloads.sourceforge.net" { break }
        "github.com" { break }
        "raw.github.com" { break }
        "raw.githubusercontent.com" { break }
        "dl.bintray.com" { break }
        Default {
            # write-host $url.Host
            if($url.Scheme -ne "https") {
                write-host -f DarkYellow "$($url.Host.PadRight(40, " "))" -NoNewline
                write-host " | http"
                return
            }
            $result = Test-ServerSSLSupport $url.Host
            write-host "$($url.Host.PadRight(40, " ")) | " -NoNewline
            if($result.TLSv1_0) {
                write-host -f DarkGreen "$($result.TLSv1_0.ToString().PadRight(6, " "))" -NoNewline
            } else {
                write-host -f DarkRed "$($result.TLSv1_0.ToString().PadRight(6, " "))" -NoNewline
            }
            write-host " | " -NoNewline
            if($result.TLSv1_1) {
                write-host -f DarkGreen "$($result.TLSv1_1.ToString().PadRight(6, " "))" -NoNewline
            } else {
                write-host -f DarkRed "$($result.TLSv1_1.ToString().PadRight(6, " "))" -NoNewline
            }
            write-host " | " -NoNewline
            if($result.TLSv1_2) {
                write-host -f DarkGreen "$($result.TLSv1_2.ToString().PadRight(6, " "))" -NoNewline
            } else {
                write-host -f DarkRed "$($result.TLSv1_2.ToString().PadRight(6, " "))" -NoNewline
            }
            write-host ""
        }
    }
}

function test-urls($json) {
    if(!$json) {
        return
    }
    if ($json.url -is [System.Array]) {
        $json.url | % {
            test-url $_
        }
    } elseif($json.url) {
        test-url $json.url
    } else {
        $arch_url = @(arch_specific 'url' $manifest $arch)
        if($arch_url -is [System.Array]) {
           $arch_url | % {
                test-url $_
            }
        } else {
            test-url $arch_url
        }
    }
}

# get apps to check
write-host "Host                                     | TLSv10 | TLSv11 | TLSv12"
write-host "-------------------------------------------------------------------"
gci $dir "$search.json" | % {
    $json = parse_json "$dir\$_"
    test-urls($json)
}
```
</details>

## Results:
<details>
<summary>Main Bucket Hosts</summary>

```
Main Bucket Hosts                        | TLSv10 | TLSv11 | TLSv12
-------------------------------------------------------------------
archive.apache.org                       | True   | True   | True
beyondgrep.com                           | True   | True   | True
binaries.cockroachdb.com                 | True   | True   | True
bitbucket.org                            | True   | True   | True
blog.alivate.com.au                      | http
chocolatey.org                           | True   | True   | True
chromedriver.storage.googleapis.com      | True   | True   | True
curl.haxx.se                             | False  | False  | True
cvs.khronos.org                          | True   | True   | True
digi.bib.uni-mannheim.de                 | True   | True   | True
dist.nuget.org                           | True   | True   | True
dl.google.com                            | True   | True   | True
download.jetbrains.com                   | True   | True   | True
download.linuxaudio.org                  | True   | True   | True
download.mono-project.com                | True   | True   | True
download.sysinternals.com                | True   | True   | True
downloads.typesafe.com                   | True   | True   | True
eternallybored.org                       | True   | True   | True
eventstore.org                           | True   | True   | True
excellmedia.dl.sourceforge.net           | True   | True   | True
files.genshin.org                        | http
ftp.gnome.org                            | True   | True   | True
ftp.info-zip.org                         | http
getcomposer.org                          | True   | True   | True
graphviz.gitlab.io                       | True   | True   | True
hashcat.net                              | True   | True   | True
install.elm-lang.org                     | http
miktex.org                               | True   | True   | True
mozjpeg.codelove.de                      | True   | True   | True
nekovm.org                               | False  | True   | True
nginx.org                                | True   | True   | True
nmap.org                                 | True   | True   | True
nssm.cc                                  | True   | True   | True
nuget.org                                | True   | True   | True
nuget.org                                | True   | True   | True
projects.giacomodrago.com                | True   | True   | True
repo1.maven.org                          | True   | True   | True
rtmpdump.mplayerhq.hu                    | True   | True   | True
s3.amazonaws.com                         | True   | True   | True
scholarlymarkdown.com                    | http
selenium-release.storage.googleapis.com  | True   | True   | True
services.gradle.org                      | True   | True   | True
shellcheck.storage.googleapis.com        | True   | True   | True
sonarsource.bintray.com                  | True   | True   | True
static.red-lang.org                      | http
sysprogs.com                             | True   | True   | True
theunarchiver.com                        | True   | True   | True
tukaani.org                              | True   | True   | True
win.rustup.rs                            | False  | True   | True
www-us.apache.org                        | True   | True   | True
www.autoitscript.com                     | True   | True   | True
www.chrysocome.net                       | http
www.cjmweb.net                           | True   | True   | True
www.fossil-scm.org                       | True   | True   | True
www.gnupg.org                            | True   | True   | True
www.guysalias.tk                         | True   | True   | True
www.itefix.net                           | True   | True   | True
www.nano-editor.org                      | True   | True   | True
www.pdflabs.com                          | True   | True   | True
www.rarlab.com                           | True   | True   | True
www.sqlite.org                           | True   | True   | True
www.syncany.org                          | True   | True   | True
yarnpkg.com                              | True   | True   | True
```
</details>

<details>
<summary>Extras Bucket Hosts</summary>

```
Extras Bucket Hosts                      | TLSv10 | TLSv11 | TLSv12
-------------------------------------------------------------------
1.eu.dl.wireshark.org                    | True   | True   | True
apache.mirror.serversaustralia.com.au    | http
api.nuget.org                            | True   | True   | True
app.pc.kakao.com                         | http
armkeil.blob.core.windows.net            | True   | True   | True
artifacts.elastic.co                     | True   | True   | True
azurecliprod.blob.core.windows.net       | True   | True   | True
bit.ly                                   | True   | True   | True
bitbucket.org                            | True   | True   | True
bitbucket.org                            | True   | True   | True
cdn09.foxitsoftware.com                  | True   | True   | True
chocolatey.org                           | True   | True   | True
crawl.develz.org                         | True   | True   | True
dist.torproject.org                      | True   | True   | True
dl.google.com                            | True   | True   | True
dl.sinew.in                              | True   | True   | True
dl.yat.qa                                | True   | True   | True
download.cpuid.com                       | http
download.deluge-torrent.org              | http
download.gimp.org                        | True   | True   | True
download.jetbrains.com                   | True   | True   | True
download.linqpad.net                     | http
download.microsoft.com                   | True   | True   | True
download.mozilla.org                     | True   | True   | True
download.mp3tag.de                       | True   | True   | True
download.netbeans.org                    | http
download.nirsoft.net                     | True   | True   | True
download.nomacs.org                      | http
download.robomongo.org                   | True   | True   | True
download.sysinternals.com                | True   | True   | True
download1.rstudio.org                    | True   | True   | True
download2.mikrotik.com                   | True   | True   | True
downloads.arduino.cc                     | True   | True   | True
fastglacier.com                          | True   | True   | True
files.gpg4win.org                        | True   | True   | True
fossies.org                              | True   | True   | True
ftp.ncftp.com                            | http
ftp.vim.org                              | http
gist.github.com                          | False  | False  | True
gist.githubusercontent.com               | True   | True   | True
go.microsoft.com                         | True   | True   | True
kindlegen.s3.amazonaws.com               | True   | True   | True
lpb.canb.auug.org.au                     | http
mobaxterm.mobatek.net                    | True   | True   | True
mupdf.com                                | True   | True   | True
nimbletext.com                           | http
openhardwaremonitor.org                  | http
openresty.org                            | True   | True   | True
r15ch13.keybase.pub                      | True   | True   | True
reshade.me                               | True   | True   | True
rufus.akeo.ie                            | True   | True   | True
s3.amazonaws.com                         | True   | True   | True
shinjiru.me                              | True   | True   | True
soft.rubypdf.com                         | http
sqlitestudio.pl                          | True   | True   | True
storage.googleapis.com                   | True   | True   | True
swupdate.openvpn.org                     | True   | True   | True
updates.signal.org                       | True   | True   | True
updates.tdesktop.com                     | True   | True   | True
windirstat.net                           | True   | True   | True
www.angusj.com                           | http
www.apache.org                           | True   | True   | True
www.bahraniapps.com                      | http
www.baremetalsoft.com                    | True   | True   | True
www.cockos.com                           | True   | True   | True
www.dhcpserver.de                        | http
www.dotpdn.com                           | True   | True   | True
www.faststonesoft.net                    | http
www.fosshub.com                          | True   | True   | True
www.haskell.org                          | True   | True   | True
www.heidisql.com                         | True   | True   | True
www.iographica.com                       | http
www.libsdl.org                           | True   | True   | True
www.makemkv.com                          | True   | True   | True
www.naturaldocs.org                      | http
www.piriform.com                         | False  | False  | True
www.portablefreeware.com                 | True   | True   | True
www.sourcetreeapp.com                    | True   | True   | True
www.stunnel.org                          | True   | True   | True
www.tt-solutions.com                     | http
www.videohelp.com                        | True   | True   | True
www.xiles.net                            | http
www.xm1math.net                          | http
www.xmedia-recode.de                     | True   | True   | True
```
</details>

<details>
<summary>Version Bucket Hosts</summary>

```
Version Bucket Hosts                     | TLSv10 | TLSv11 | TLSv12
-------------------------------------------------------------------
artifacts.elastic.co                     | True   | True   | True
bitbucket.org                            | True   | True   | True
cocl.us                                  | False  | True   | True
digi.bib.uni-mannheim.de                 | True   | True   | True
dist.nuget.org                           | True   | True   | True
download.elastic.co                      | True   | True   | True
ufpr.dl.sourceforge.net                  | True   | True   | True
windows.php.net                          | http
www.vordweb.co.uk                        | http
```
</details>

**Comment by tresf** [comment]
I'm not sure what's more impressive... the speed in which you valided every script mirror supports TLS12, or the neat GitHub hide huge codeblock trick.

**Comment by r15ch13** [comment]
An easy fix would be to add this neat little line to `core.ps1`.
Mentioned by @masaeedu in https://github.com/lukesampson/scoop/pull/2065#issuecomment-369669048
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
```

**Comment by jordanbtucker** [comment]
@r15ch13 The install oneliner doesn't need to change unless Cloudflare drops support for TLSv1.0 or GitHub drops support for TLSv1.0 on raw.githubusercontent.com.

get.scoop.sh is served from Cloudflare's servers, then redirects to raw.githubusercontent.com. GitHub only [dropped support for TLSv1.0](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/) on github.com and api.github.com.

The install oneliner doesn't have trouble downloading the install script, it just has trouble accessing api.github.com during the install.

That being said, the following oneliner is shorter, but suffers from the same problem.

```powershell
iwr https://get.scoop.sh | iex
```

**Comment by dsbert** [comment]
I didn't see a commit related to this but I am no longer receiving the error after updating scoop.

**Comment by jordanbtucker** [comment]
@dsbert What happens when you run this:

```powershell
scoop search --no-cache
```

**Comment by dsbert** [comment]
@jordanbtucker There it is

**Comment by jordanbtucker** [comment]
This is fixed for me, but I left a [comment](https://github.com/lukesampson/scoop/pull/2074#issuecomment-369822688) about it leaving side effects. It's probably not a big deal though.

**Comment by jatalocks** [comment]
rtgsd

**Comment by wbrewer** [comment]
> @h404bi While I agree that scoop should _just work_, setting ServicePointManager to only use TLS 1.1 and higher is something you _should_ do anyway since SSLv3 and TLSv1.0 are deprecated due to [POODLE](https://en.wikipedia.org/wiki/POODLE). (Although, this could break other .NET applications and libraries.)
> 
> Here's how to do that in PowerShell:
> 
> ```powershell
> # set strong cryptography on 64 bit .Net Framework (version 4 and above)
> Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
> 
> # set strong cryptography on 32 bit .Net Framework (version 4 and above)
> Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord 
> ```
> 
> Plus, this will allow scoop to work in Command Prompt instead of just PowerShell.

This finally let me install boxstarter on windows7 via azure-arm/packer.
