### ISSUE TITLE
cygwin hash is wrong

### ISSUE THREAD

**Issue by andiskrauklis** [lukesampson/scoop#2047]
Installing 'cygwin' (2.889) [64bit]
setup-x86_64.exe (1,1 MB) [=========================================================================================================================================================================================================] 100%
Checking hash of setup-x86_64.exe... Hash check failed for 'https://cygwin.com/setup-x86_64.exe'.
Expected:
    52bcd0cc614df0718f1aabe6709bebabbda6c768696dd0c7efd4efe77b37239d
Actual:
    22d80e6893200d377bdb46a7080d3c60092e027bba51c6e73013969e05c629f9

**Comment by r15ch13** [comment]
Fixed
