### ISSUE TITLE
Invoke-WebRequest Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by kostrse** [lukesampson/scoop#2063]
On my machine `scoop search` fails with error:

```
invoke-webrequest : The request was aborted: Could not create SSL/TLS secure channel.
At C:\Users\sekost\scoop\apps\scoop\current\libexec\scoop-search.ps1:53 char:15
+     $result = invoke-webrequest $url -UseBasicParsing | select -exp c ...
```

It fails to access GitHub API endpoints.

I guess it can be because of this:
[StackOverflow: Powershell Invoke-WebRequest Fails with SSL/TLS Secure Channel](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)

**UPDATE:**

Yes, I added this line into `scoop-seach.ps1` and it solved the problem:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by r15ch13** [comment]
Probably related to https://github.com/lukesampson/scoop/issues/2040
