### ISSUE TITLE
scoop not recognized as a command

### ISSUE THREAD

**Issue by gbursson** [lukesampson/scoop#2069]
I was using scoop successfully yesterday, no hassle (after a bit of trouble following solution to TLS issue). Today, when opened PS I got scoop not found error:

![image](https://user-images.githubusercontent.com/1756600/36833403-273f09d0-1d27-11e8-9088-a1f19e0fb6cc.png)

Scoop is sitting where it should sit, I have it installed in a custom location:
*D:\Programming\_SDK\Scoop*
**$env:SCOOP** is set properly

Can anyone guess what might be the reason? Do I need to put something in PS profile?

**Comment by excitoon** [comment]
Can you check if you have `%UserProfile%\scoop\shims` in `%PATH%`?

**Comment by gbursson** [comment]
Thanks excitoon, that seemed the issue, added the path to $env:PATH and after restart it's working!.
