### ISSUE TITLE
unable to install winscp

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop#2071]
I get the following error:

```
PS > scoop install winscp
Installing 'winscp' (5.13) [64bit]
WinSCP-5.13-Portable.zip (652 B) [================================================================================================================] 100%
Checking hash of WinSCP-5.13-Portable.zip... Hash check failed for 'https://sourceforge.net/projects/winscp/files/WinSCP/5.13/WinSCP-5.13-Portable.zip'.
Expected:
    57c1e425d11b7d50d1f93ab4058ca5da7f473ea7
Actual:
    24c6e9477a83f2e67e3ac6fcd6fec6fbb393b289
```

BTW, after unsuccessful installation I have to uninstall winscp as scoop thinks it has installed it... Is it intended?

**Comment by yigitemres** [comment]
Sourceforge is currently broken.

**Comment by alejandro5042** [comment]
I believe `scoop` is broken, not Sourceforge.

Sourceforge is correctly using HTTP status 302 to redirect the user (in this case, `scoop`) to the location to download the file:

> The HyperText Transfer Protocol (HTTP) 302 Found redirect status response code indicates that the resource requested has been temporarily moved to the URL given by the Location header. ([Source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302))

# Selected output

The first query returns a redirect:

```
curl.exe 'https://sourceforge.net/projects/winscp/files/WinSCP/5.13/WinSCP-5.13-Portable.zip' -v
< HTTP/1.1 302 Found
< Location: https://sourceforge.net/projects/winscp/files/WinSCP/5.13/WinSCP-5.13-Portable.zip/download
```

Then again:

```
curl.exe 'https://sourceforge.net/projects/winscp/files/WinSCP/5.13/WinSCP-5.13-Portable.zip/download' -v
< HTTP/1.1 302 Found
< Location: https://downloads.sourceforge.net/project/winscp/WinSCP/5.13/WinSCP-5.13-Portable.zip?r=&ts=1519923893&use_mirror=phoenixnap
```

Then again:

```
curl.exe 'https://downloads.sourceforge.net/project/winscp/WinSCP/5.13/WinSCP-5.13-Portable.zip?r=&ts=1519923893&use_mirror=phoenixnap' -v
< HTTP/1.1 302 Found
< Location: https://phoenixnap.dl.sourceforge.net/project/winscp/WinSCP/5.13/WinSCP-5.13-Portable.zip
```

Finally, it is able to download:

```
curl.exe 'https://phoenixnap.dl.sourceforge.net/project/winscp/WinSCP/5.13/WinSCP-5.13-Portable.zip' -v
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Content-Length: 7624566
```

# Proposed Solution

`scoop` should follow redirects up to a reasonable maximum, perhaps 10.

**Comment by r15ch13** [comment]
@alejandro5042 scoop does follow the `302` redirects. SourceForge is moving their servers like @yigitemres mentioned and it shows a `404` (without proper HTTP status code) or a maintenance page.
scoop uses [`net.webrequest`](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.maximumautomaticredirections(v=vs.110).aspx) which defaults to 50 auto redirects:
https://github.com/lukesampson/scoop/blob/e9baa5c18938259dfbe2c223fb9bf56828aa5686/lib/install.ps1#L152-L160

**Comment by yigitemres** [comment]
https://twitter.com/sfnet_ops/status/969017161686626304
