### ISSUE TITLE
Can't install 7zip or git with scoop

### ISSUE THREAD

**Issue by femrich** [lukesampson/scoop#2096]
I'm running Windows 7 with all the required Windows packages. Installed scoop recently and worked out some bugs with help here. But now I cannot get scoop to install anything. Here is my screen output:

> PS C:\Users\HP> scoop install 7zip
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing '7zip' (18.01) [64bit]
Loading 7z1801-x64.msi from cache
Checking hash of 7z1801-x64.msi... ok.
Extracting... Exit code was .
Failed to extract files from C:\Users\HP\scoop\apps\7zip\18.01\7z1801-x64.msi.
Log file:
  ~\scoop\apps\7zip\18.01\msi.log
PS C:\Users\HP> scoop uninstall 7zip
Uninstalling '7zip' (18.01).
'7zip' was uninstalled.
PS C:\Users\HP> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing '7zip' (18.01) [64bit]
Loading 7z1801-x64.msi from cache
Checking hash of 7z1801-x64.msi... ok.
Extracting... Exit code was .
Failed to extract files from C:\Users\HP\scoop\apps\7zip\18.01\7z1801-x64.msi.
Log file:
  ~\scoop\apps\7zip\18.01\msi.log
PS C:\Users\HP>

Any suggestions on what might be wrong? Thank you!

**Comment by femrich** [comment]
Using the command to install Curl seems to install 7Zip, but then gets bogged down later. Help with this, please?

> PS C:\Users\HP> scoop install curl
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing '7zip' (18.01) [64bit]
Loading 7z1801-x64.msi from cache
Checking hash of 7z1801-x64.msi... ok.
Extracting... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.01
Creating shim for '7z'.
Creating shortcut for 7zip (7zFM.exe)
'7zip' (18.01) was installed successfully!
Installing 'curl' (7.58.0) [64bit]
curl-7.58.0-win64-mingw.7z (2.0 MB) [=================================] 100%
Checking hash of curl-7.58.0-win64-mingw.7z... ok.
Extracting... done.
Linking ~\scoop\apps\curl\current => ~\scoop\apps\curl\7.58.0
Creating shim for 'curl'.
'curl' (7.58.0) was installed successfully!
'curl' suggests installing 'cacert'.
PS C:\Users\HP> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.16.2.windows.1) [64bit]
PortableGit-2.16.2-64-bit.7z.exe (35.5 MB) [==========================] 100%
Checking hash of PortableGit-2.16.2-64-bit.7z.exe... ok.
Extracting... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.16.2.windows.1
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Running post-install script...
'git' (2.16.2.windows.1) was installed successfully!
Notes
-----
To get Git to recognise OpenSSH, you will need to run

scoop install openssh
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which
ssh)), 'USER')

and then restart powershell.
PS C:\Users\HP>

**Comment by femrich** [comment]
closing this for now. I think I figured it out.

**Comment by rasa** [comment]
Can you post `C:\Users\HP\scoop\apps\7zip\18.01\msi.log` to a public [gist](https://gist.github.com/)?
