### ISSUE TITLE
CheckUrls script doesn't use proxy settings

### ISSUE THREAD

**Issue by abejenaru** [lukesampson/scoop#2100]
Using CheckUrls script behind authentified proxy I get the following error: "The remote server returned an error: (407) Proxy Authentication Required", however CheckVer works fine.

**Comment by r15ch13** [comment]
`checkurls.ps1` no imports `config.ps1` which handles the proxy settings.
Does this fix it?

**Comment by abejenaru** [comment]
Yes, it does :)
