### ISSUE TITLE
Incorrect System Architecture Error When Installing MongoDB

### ISSUE THREAD

**Issue by RGAlexander216** [lukesampson/scoop#2114]
When I attempt to run "scoop install MongoDB" I receive the following:
'mongodb' doesn't support 32bit architecture!

My computer architecture is AMD64 & is set as such in my environment variables

**Comment by r15ch13** [comment]
What is the output of `[intptr]::size` when you execute it in powershell?

**Comment by RGAlexander216** [comment]
4

**Comment by r15ch13** [comment]
Can you take a look at the System properties? (Win-Key, type "System")
What has to show 64-bit Operation System

![image](https://user-images.githubusercontent.com/432127/37255776-808f2d08-2551-11e8-8815-c77646fece7a.png)

If it doesn't then you have installed the wrong Windows Version

**Comment by RGAlexander216** [comment]
![systeminfo](https://user-images.githubusercontent.com/20406603/37256200-6067c930-2525-11e8-8e29-7f6f1040e7dd.JPG)

**Comment by RGAlexander216** [comment]
![systeminfo](https://user-images.githubusercontent.com/20406603/37256240-e5899a62-2525-11e8-81a5-bf38993461b7.JPG)

**Comment by RGAlexander216** [comment]
We Have found the culprit and, to me, it's very odd:
![processorinfo](https://user-images.githubusercontent.com/20406603/37257794-a54c247c-253b-11e8-85d7-c67509403d2e.JPG)

But for you it probably means you can close this unless you have a suggestion on where in the registry I may be able to correct this (if it's even wrong that is).

**Comment by r15ch13** [comment]
That's a really strange problem you got there. 😄 
Scoop uses `[intptr]::size` to determine the architecture. I have no clue how you can fix it.

**Comment by RGAlexander216** [comment]
Thanks for your help. Do you think it may be something wrong with Powershell? I can't find anything about this other than maybe I only have a working 32 bit Powershell and the 64 bit is corrupt (I'm not that savvy with Powershell so forgive me if that's not how this works...).

**Comment by r15ch13** [comment]
Maybe your shortcut points to `%SystemRoot%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe` which is the 32bit version.
It has to be `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`

**Comment by RGAlexander216** [comment]
You're spot on with the origin-type, it was the command prompt that was improperly connected to the SysWOW64 cmd.exe. I really appreciate your help in resolving this user-error on my part. Thank you.
