### ISSUE TITLE
GitHub regex is very opinionated about version string

### ISSUE THREAD

**Issue by andreysaksonov** [lukesampson/scoop#2115]
https://github.com/lukesampson/scoop/blob/79bf99c3c110494d799e147263db7b6f2f921d4e/bin/checkver.ps1#L56

This doesn't work for this repo: https://github.com/spring-projects/spring-boot/releases (because version is not purely numeric).

I workarounded this for particular app manifest using custom regex (https://github.com/andreysaksonov/scoop-bucket/blob/master/springboot.json) and I think this regex is more safe. Should it be used by default for github checkver?

**Comment by r15ch13** [comment]
Using a default regex that allows non numeric characters could lead to automatic update for `1.2.3-alpha1` if they are published as releases.
In the case of sprint-boost I would recommend only matching the RELEASE versions `\/releases\/tag\/(?:v)?([\d.]+)\.RELEASE`

**Comment by andreysaksonov** [comment]
Thanks! Now I got the idea, probably this concept is good candidate to be added to the https://github.com/lukesampson/scoop/wiki/App-Manifests.
