### ISSUE TITLE
Latex (miktex) Error!

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#2129]
┌[⚡ yigit] [21:36]
└[~\Desktop]> scoop install latex
Installing 'latex' (2.9.6621) [64bit]
The remote server returned an error: (302) Found.
URL https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6621.exe#/dl.7z is not valid

**Comment by r15ch13** [comment]
Yeah, this happens because they redirect to mirrors without HTTPS. Retrying it is the only solution. (I hope letsencrypt gets more reach...)
