### ISSUE TITLE
Option/config to disable verbose update logs

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop#2133]
Related commit: https://github.com/lukesampson/scoop/commit/56c35f8f05ed387997ef1a80ec0362adec6e51a5.

1. Default verbose update logs to `false`, provide a arg to `scoop update` command:

**libexec/scoop-update.ps1**:
```
# Options:
#   --global, -g       Update a globally installed app
#   --force, -f        Force update even when there isn't a newer version
#   --no-cache, -k     Don't use the download cache
#   --independent, -i  Don't install dependencies automatically
#   --quiet, -q        Hide extraneous messages
#   --verbose, -v      Show update logs          <------------------------
```

2. Default verbose update logs to `true`, Add a config attribute to disable it:

  **~/.scoop**:
  ```
  {
      "lastupdate":  "\/Date(1521274194904)\/",
      "SCOOP_BRANCH":  "master",
      "show_update_log":  "false",        <------------------------for example
      "SCOOP_REPO":  "https://github.com/lukesampson/scoop"
  }
  ```

Any ideas?

**Comment by h404bi** [comment]
Resolved in https://github.com/lukesampson/scoop/commit/d68cb3ce52acaa9983f278822febd506f54ebe02. But lack of documentation currently. Closed this issue.

**Comment by darthwalsh** [comment]
This config is implemented, but now the way to set it is `scoop config show_update_log false` 

(Don't try using `~\.scoop` in 2023 it doesn't work.)
