### ISSUE TITLE
cmd shims not being created

### ISSUE THREAD

**Issue by atifaziz** [lukesampson/scoop#2140]
I'm having trouble with installing scoop applications on a pretty fresh Windows 10 PC. After installing scoop, I ran `scoop install wget` and here was the output:

```
Installing 'wget' (1.19.4) [64bit]
Loading wget-1.19.4-win64.zip from cache
Checking hash of wget-1.19.4-win64.zip... ok.
Extracting... done.
Linking ~\scoop\apps\wget\current => ~\scoop\apps\wget\1.19.4
Creating shim for 'wget'.
Running post-install script...
```

From the looks of it, one would think the installation went fine but then just running `wget` in the Windows Command Prompt gave the error:

    Access is denied.

When I looked in the sims directory, I noticed that there was not `wget.cmd`:

```
03/19/2018  11:11 AM    <DIR>          .
03/19/2018  11:11 AM    <DIR>          ..
03/19/2018  11:09 AM               102 scoop
03/19/2018  11:09 AM               348 scoop.cmd
03/19/2018  11:09 AM               160 scoop.ps1
03/19/2018  11:11 AM               154 wget.ps1
03/19/2018  11:11 AM                60 wget.shim
               5 File(s)            824 bytes
```

I tried also installing 7zip but got the same results. Installation goes fine…

```
Installing '7zip' (18.01) [64bit]
Loading 7z1801-x64.msi from cache
Checking hash of 7z1801-x64.msi... ok.
Extracting... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.01
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (18.01) was installed successfully!```
```

…but then running `7z` results in an access denial message like for `wget` and when I check the shims directory, there's no `7z.cmd` to be found:

````
03/19/2018  11:18 AM    <DIR>          .
03/19/2018  11:18 AM    <DIR>          ..
03/19/2018  11:18 AM               152 7z.ps1
03/19/2018  11:18 AM                58 7z.shim
03/19/2018  11:09 AM               102 scoop
03/19/2018  11:09 AM               348 scoop.cmd
03/19/2018  11:09 AM               160 scoop.ps1
03/19/2018  11:11 AM               154 wget.ps1
03/19/2018  11:11 AM                60 wget.shim
````

If I start a PowerShell session and type out `wget.ps1` or `7z.sp1` then I can see it finds and runs the apps.

And “yes” to…

![Have you tried turning it off and on again?](https://media.giphy.com/media/ySXfrt0jdcYqQ/giphy.gif)

## `$PSVersionTable`

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.16299.248                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.16299.248                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

**Comment by r15ch13** [comment]
The IT Crowd 😁👍

`*.cmd` files only get created if the program provides a `cmd` file.
Instead, there should be a copy of `~\scoop\apps\scoop\current\supporting\shimexe\bin\shim.exe` named `7z.exe`.
Can you check if the source file exists?
Or maybe you antivirus killed it?

**Comment by rasa** [comment]
To expand on @r15ch13's point. Your `%USERPROFILE%\scoop\shims` folder should look like this:
```
C:\Users\you\scoop\shims>dir 7z.* wget.*
 Volume in drive C is drive_c
 Volume Serial Number is DEAD-BEEF

 Directory of C:\Users\you\scoop\shims

02/20/2018  12:32 PM             7,168 7z.exe
02/20/2018  01:04 PM               152 7z.ps1
02/20/2018  01:04 PM                56 7z.shim

 Directory of C:\Users\you\scoop\shims

02/20/2018  12:32 PM             7,168 wget.exe
02/20/2018  03:53 PM               154 wget.ps1
02/20/2018  03:53 PM                58 wget.shim
               6 File(s)         14,756 bytes
               0 Dir(s)  846,820,319,232 bytes free
```

**Comment by atifaziz** [comment]
@r15ch13 @rasa So it turns out it was the anti-virus after all. In some trials, I noticed that the shim executable was being created but then would disappear soon after, giving an access denial during the times it would appear to exist. I should have read the “[Antivirus and Anti Malware Problems](https://github.com/lukesampson/scoop/wiki/Antivirus-and-Anti-Malware-Problems)” wiki but I didn't suspect the anit-virus because scoop was installing and running perfectly on another box. The new PC had a different anti-virus program that was a tad bit ruder. After white-listing scoop, it was all tickety-boo again. :rainbow: Thanks for dropping in to point me in the right direction and sorry for wasting any of your time.
