### ISSUE TITLE
scoop update stuck on git log

### ISSUE THREAD

**Issue by marknelissen** [lukesampson/scoop#2144]
When running the scoop update command, it goes to the git log view.
![image](https://user-images.githubusercontent.com/10599177/37703892-7bf3a9ba-2cf7-11e8-9f62-75819dee8e6a.png)

 When leaving this view, (press q), the console remains on doing nothing. The only way to leave this state and come back to the prompt is to kill the process.

Here is the git information I see you ask in these type of issues:
![image](https://user-images.githubusercontent.com/10599177/37703965-bc140bb6-2cf7-11e8-835e-927bd1e69b64.png)

It also displays this behaviour when trying to update the installed components, both through * and specific package, preventing updating through scoop.
![image](https://user-images.githubusercontent.com/10599177/37704075-10f3face-2cf8-11e8-9221-82130e47b421.png)

**Comment by h404bi** [comment]
Related: #2133 
temporary workaround: revert commit: https://github.com/lukesampson/scoop/commit/56c35f8f05ed387997ef1a80ec0362adec6e51a5

**Comment by marknelissen** [comment]
Thank you for your quick response.

Is there a reason not to publish the revert of this commit on the central master branch? Does it only occur under specific circumstances?

**Comment by h404bi** [comment]
It only occur when you didn't update scoop for some time, when there is a long commit history.
We want a better solution to deal with update log, discussion at #2133 , instead of just reverting the commit.

**Comment by marknelissen** [comment]
So, after I update scoop, I can revert the revert?

**Comment by marknelissen** [comment]
However, as I understand it, without fundamentally changing the way the update log works, you would run into the same issue as here when enabling the verbose mode proposed by #2133 .

**Comment by r15ch13** [comment]
`git log` pauses if there are too many lines. I disabled the pagination with https://github.com/lukesampson/scoop/commit/cac9975924691fe6e608789218b06be56bb8c658
Updating should continue when you press and hold enter to show more log entries.
Or remove the "lastupdate" value from `%USERPROFILE%/.scoop`

**Comment by rasa** [comment]
This was fixed in https://github.com/lukesampson/scoop/commit/cac9975924691fe6e608789218b06be56bb8c658 , right?

**Comment by marknelissen** [comment]
I confirm, when leaving the history, the update completes now, even if you leave by pressing 'q' (no need to scroll to the ending by enter).  Tested it by setting my last update date far into the past.
