### ISSUE TITLE
curl not found after install

### ISSUE THREAD

**Issue by shyun3** [lukesampson/scoop#2146]
Calling `curl --version` fails after install:
```
curl : The remote name could not be resolved: '--version'
At line:1 char:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

The output from `scoop install curl`:
```
Installing 'curl' (7.59.0) [64bit]
Loading curl-7.59.0-win64-mingw.tar.xz from cache
Checking hash of curl-7.59.0-win64-mingw.tar.xz... ok.
Extracting... done.
Linking ~\scoop\apps\curl\current => ~\scoop\apps\curl\7.59.0
Creating shim for 'curl'.
'curl' (7.59.0) was installed successfully!
```

Seems like the issue is the link to `7.59.0` and not `7.59.0\bin`.

**Comment by shyun3** [comment]
I just realized that running `curl --version` works just fine in cmd but in PowerShell, I have to call it as `curl.exe --version`. None of my other Scoop apps require appending the `.exe` in PowerShell though. Is there a way around this?

**Comment by shyun3** [comment]
After some more looking around, I learned PowerShell already had a `curl` alias. Sorry, false alarm.

**Comment by muhfouad123** [comment]
> I just realized that running `curl --version` works just fine in cmd but in PowerShell, I have to call it as `curl.exe --version`. None of my other Scoop apps require appending the `.exe` in PowerShell though. Is there a way around this?

I was also facing the same issue, until I saw your reply, and also worked for me!

**Comment by niheaven** [comment]
PowerShell has an alias `curl` to `Invoke-WebRequest` before, and now Windows has `curl.exe` under `system32`. So if you want to use Scoop's `curl`, use full path.
