### ISSUE TITLE
Install of openshift-origin-client "Cannot remove item" error

### ISSUE THREAD

**Issue by hctagalong** [lukesampson/scoop#2149]
On fresh scoop install and then install of openshift-origin-client, running into:
`Remove-Item : Cannot remove item <path....\scoop\apps\openshift-origin-client\3.7.2\_tmp\oc.exe: Access to path is denied`

Error is in install.ps1:367 char:21; command executed is `Remove-Item -r -force "$dir\_tmp" -ea stop`

Additional information:
`CategoryInfo : InvalidArgument: (oc.exe:FileInfo) [Remove-Item], ArgumentException
FullQualifiedErrorId: RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand`

Any thoughts on what is causing this error? Was working a few days ago; there are no changes in that application's manifest since I had validated this was working. Manually running `Remove-Item` on that _tmp directory via PowerShell yields removal of that directory.

Checking the permissions on that directory, the user I'm running as appears to have 'full control'.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2149
