### ISSUE TITLE
Scoop Default Path

### ISSUE THREAD

**Issue by Zyphrax** [lukesampson/scoop#2157]
In some of the old issues I read that the path used to be `~/AppData/Local/scoop`
The new path seems to be `~/scoop`

Can I ask why you changed that?

I like to keep my User folder clean, so I was thinking of overriding the scoop environment variable to set it to the old path, but I want to make sure that it won't cause issues 🙂

**Comment by Zyphrax** [comment]
Ah found it in the source:
```
The default directory changed from ~/AppData/Local/scoop to ~/scoop
on 1 Nov, 2016 to work around long paths used by NodeJS.
```

**Comment by h404bi** [comment]
The reason has been explained in [lib/core.ps1#L1-L6](https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L1-L6), and you can override the `$env:SCOOP` (wiki: [here](https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory)) to customize your scoop home, no worry.

**Comment by Zyphrax** [comment]
@h404bi I beat you by 40 seconds 😄. Thanks!

Can I just mark the folder as hidden? Or will that cause issues?

**Comment by h404bi** [comment]
@Zyphrax you can have a try. :)

**Comment by h404bi** [comment]
You may close this issue if you have solved the problem.

**Comment by Zyphrax** [comment]
Ah sorry.

I installed Scoop and got distracted trying to get SSH passphrases to work automatically. I'm a bit spoiled by the keychain integration under MacOS. There doesn't seem to be an easy solution under Windows.

The hidden folder works great! Thank you!

**Comment by h404bi** [comment]
For SSH auto-launching, you could use [`pshazz`](https://github.com/lukesampson/pshazz), which has a ssh plugin [here](https://github.com/lukesampson/pshazz/blob/master/plugins/ssh.ps1), that's useful.
