### ISSUE TITLE
scoop alias command definition

### ISSUE THREAD

**Issue by warthurton** [lukesampson/scoop#2160]
Enhancement:

Enhance the `scoop alias list` so that it includes the definition of the alias.  Alternatively, add another function to dump the definitions.  This will make standardizing installs across machines easier.

**Comment by r15ch13** [comment]
Something like that https://github.com/lukesampson/scoop/commit/b179e1fc8a2e447700c26d45fe3480f4e2e3e011

Example output: 
```
λ scoop alias list

Name    Command          Summary
----    -------          -------
i       scoop install
test    composer install Run composer install in current directory
u       scoop uninstall
upgrade scoop update *
```

**Comment by warthurton** [comment]
That looks great.  That way if I forget to paste into my setup document I can still get the definition without doing a cat %USERPROFILE%/scoop/shims/scoop-*.ps1
