### ISSUE TITLE
packer change hash url

### ISSUE THREAD

**Issue by HWataru** [lukesampson/scoop#2162]
Hi

I installed packer 1.2.2 but an error occurs.

```ps1
Checking hash of packer_1.2.2_windows_amd64.zip... Hash check failed for 'https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_windows_amd64.zip'.
Expected:
    24140831596cd8ce5be3ba8205cdd7fc8ebd6ebffe7dde445249b6ab82ab8bff
Actual:
    9c066bbe463376f9e7991326ecba09672b121776a0f2566c2d8e6ef72d52106e
```

I checked [packer.json](https://github.com/lukesampson/scoop/commit/ca482baa79e96204d970012553b015a8030e62bf) and found sha256 checksum url no longer available.

<https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_SHA256SUMS>

I tried to access from official page then I can see checksum page with additional parameter like this.

<https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_SHA256SUMS?_ga=2.96260122.749924716.1522218073-1548706966.1520686693>

Someone can fix it?

**Comment by r15ch13** [comment]
https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_SHA256SUMS is available now ... and the hash values changed. Seems they have changed the release version.
