### ISSUE TITLE
Error url innoump

### ISSUE THREAD

**Issue by manang** [lukesampson/scoop#2164]
Hi,
when I try to install openssl I have the following error about innoump:
URL https://sourceforge.net/projects/innounp/files/innounp/innounp%200.46/innounp046.rar/ is not valid scoop

Solutions?
Thanks
Angelo

**Comment by r15ch13** [comment]
Moved it to my [keybase public](https://keybase.pub/r15ch13/scoop/innounp/) directory. Please run `scoop update` and try again.

**Comment by manang** [comment]
thank you!
