### ISSUE TITLE
Support no-op installer for shims

### ISSUE THREAD

**Issue by leonyu** [lukesampson/scoop#2170]
Certain packages like `git` is bundled with a lot of tools (coreutils, findutils, openssh, vim, etc), but we only expose `git`-related commands by default when it is installed. In addition, because it is bundled with ssh, we ended up repackage it as `git-with-openssh` for `openssh` integration. 

Alternative solution is to allow no-op installer. In that implementation, we can create packages solely for shimming. For example: 

```json
{
    "homepage": "https://git-for-windows.github.io/",
    "license": "GPL2",
    "depends": "git",
    "##": "no version or architecture",
    "bin": [
        "..\\git\\usr\\bin\\ssh.exe"
    ]
}
```

**Comment by excitoon** [comment]
Can you check out fix in #2072 . I guess you can do it right now with substitutions (`appdir`).

**Comment by excitoon** [comment]
This is a duplicate of #2155 .

**Comment by rasa** [comment]
Thanks for the report, but I'm closing as this is a dup of #2155
