### ISSUE TITLE
PowerShell ISE: Multiple line status update on download

### ISSUE THREAD

**Issue by sim4life** [lukesampson/scoop#2171]
On PowerShell ISE, running 
$ scoop install gradle

causes the download status updates to output multiple lines instead of reporting download status on single line. The download status updates should be reported on the same  single line. Attached find the screenshot for reference:

![powershellise_scoop_install](https://user-images.githubusercontent.com/302743/38186605-44abe4ca-366d-11e8-9264-47261bbde3f1.png)

**Comment by stkb** [comment]
Does this happen with every install in ISE or just sometimes? Also what do you get for the value of `[console]::isoutputredirected` in ISE?

**Comment by sim4life** [comment]
I get this for every install on PS ISE.
The value for `[console]::isoutputredirected` is `False`

**Comment by sim4life** [comment]
Thanks for the update...I'm thinking how do I turn it on?

**Comment by stkb** [comment]
While testing the fix for this it somehow became `False` for me too after running a few scoop commands. Still don't know what's going on there. Anyway I've submitted a patch with an extra check for ISE (#2189).

**Comment by stkb** [comment]
@r15ch13 Thanks for the merge 

@sim4life The issue was auto-closed from the commit but do a `scoop update` and see if the issue has been fixed for you after that.

**Comment by sim4life** [comment]
@stkb thanks.
After the update, the value for `[console]::isoutputredirected` was still `False`. I had to reboot `PowerShell ISE` to make it to `True`.
I also tried installing a new app using scoop and the status is perfectly single-liner.
