### ISSUE TITLE
Hash Check fails on Scoop install Cygwin

### ISSUE THREAD

**Issue by michaelwilson** [lukesampson/scoop#2177]
Installing 'cygwin' (2.891) [64bit]
setup-x86_64.exe (1.1 MB) [===================================================================================] 100%
Checking hash of setup-x86_64.exe... Hash check failed for 'https://cygwin.com/setup-x86_64.exe'.
Expected:
    22d80e6893200d377bdb46a7080d3c60092e027bba51c6e73013969e05c629f9
Actual:
    4084fe6db9ed7518b7f02097210b4d6b1748979556f606fa5c79ee126f07db5f

Scoop uninstall cygwin, followed by scoop install, and of course scoop update, all to no avail. 

Thanks!

**Comment by r15ch13** [comment]
Fixed
