### ISSUE TITLE
cpu-z hash check fails

### ISSUE THREAD

**Issue by mattpangaro** [lukesampson/scoop#2178]
I feel like I should probably know/learn how to contribute a fix, or at least grok it, but when updating cpu-z version last time, I got this:

d:\>scoop install cpu-z
Installing 'cpu-z' (1.84) [64bit]
cpu-z_1.84-en.zip (2.6 MB) [==================================================================================] 100%
Checking hash of cpu-z_1.84-en.zip... Hash check failed for 'http://download.cpuid.com/cpu-z/cpu-z_1.84-en.zip'.
Expected:
    5aebc45df428ac3c1d235517bfd664bf055864ba7c533e2c2eb1425c7172a507
Actual:
    f1cad36910c14c72a62823a2bd5779e75e8f820fcca02821f9e9666918093fbe

**Comment by r15ch13** [comment]
Fixed
