### ISSUE TITLE
scoop update not updating apps

### ISSUE THREAD

**Issue by gbursson** [lukesampson/scoop#2184]
Hi,

I have run **scoop update** and while it updates the list of packages it does not seem to update installed applications. I had to manually run **scoop update youtube-dl** for instance.

Is that an intended behavior? **scoop help** lists *update* command as: "Update apps, or Scoop itself"

**Comment by r15ch13** [comment]
You have to run `scoop update *` to update all apps or manually specify it like you did with youtube-dl

**Comment by gbursson** [comment]
perfect, thanks!! have not thought about a wildcard!
