### ISSUE TITLE
Add Bazel to an official Scoop repository

### ISSUE THREAD

**Issue by excitoon** [lukesampson/scoop#2186]
Hi.

I have a package in my private repository `scoop-user`: https://github.com/excitoon/scoop-user/blob/master/bazel.json and I want to add it to official one.

1. Bazel is fast and correct build system, I guess it should belong to the main bucket (like CMake).
2. Bazel requires latest version of `infozip` (missing, but I can easily add it) and `versions/python27` (we need to solve #1466 for that).

Please, confirm that I can go this way.

**Comment by r15ch13** [comment]
It's already in the extras bucket. https://github.com/lukesampson/scoop-extras/blob/master/bazel.json
Feel free to improve it. Moving it to the main bucket might be a good idea.

**Comment by excitoon** [comment]
Okay, I will stick to that.

**Comment by gbursson** [comment]
Lads,

What is the reasoning behind having extras bucket? Maintainability? 


Greg.

**Comment by r15ch13** [comment]
@gbursson separation between console only programs and GUIs

**Comment by h404bi** [comment]
main bucket should only contains console apps.

**Comment by r15ch13** [comment]
Done: https://github.com/lukesampson/scoop/pull/2187
