### ISSUE TITLE
Multi line note message after app install

### ISSUE THREAD

**Issue by sim4life** [lukesampson/scoop#2190]
I'm using PowerShell ISE with Win10. I just installed a new app...`jetbrains-toolbox` and it printed a note at the end, which is multiline instead of single line:

    Notes
    -----
    Set
    'Install
    Location'
    to
    C:\Users\<username>\scoop\apps\jetbrains-toolbox\current
    to
    persist
    the
    installed
    apps

Secondly, how do I fix for this particular note?

**Comment by stkb** [comment]
Fix should be coming soon. It's a problem with the code that displays all notes, so not a problem with that particular package.
