### ISSUE TITLE
redis source is out of date

### ISSUE THREAD

**Issue by ahmadalli** [lukesampson/scoop#2195]
https://github.com/MicrosoftArchive/redis hasn't been updated for about 2 years

**Comment by tejashah88** [comment]
There's a fork of it here: https://github.com/tporadowski/redis, although the author says that it's very experimental. As of now, the latest release is v4.0.2.2. It might be recommended to add an entry in the versions bucket.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2195
