### ISSUE TITLE
openssh install fails

### ISSUE THREAD

**Issue by azizuysal** [lukesampson/scoop#2197]
When I run `scoop install openssh`, I get this error:
```powershell
PS C:\Windows\System32> scoop install openssh
Installing 'openssh' (5.4p1-1) [64bit]
Loading openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma from cache
Loading openssh-5.4p1-1-msys-1.0.13-lic.tar.lzma from cache
Loading msysCORE-1.0.13-2-msys-1.0.13-bin.tar.lzma from cache
Loading zlib-1.2.3-2-msys-1.0.13-dll.tar.lzma from cache
Loading libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma from cache
The remote server returned an error: (502) Bad Gateway.
URL https://sourceforge.net/projects/mingw/files/MSYS/Extension/openssl/openssl-1.0.0-1/libopenssl-1.0.0-1-msys-1.0.13-dll-10
0.tar.lzma is not valid
```

**Comment by rasa** [comment]
Let’s address this by replacing 5.4 with 6.7 found here:
https://github.com/excitoon/scoop-user/blob/master/openssh.json

**Comment by eyadsibai** [comment]
will this be solved soon? is there a temporary solution?

**Comment by brandon93s** [comment]
The sourceforge URL has been fixed:

![image](https://user-images.githubusercontent.com/4730164/42255590-79bfda36-7f1a-11e8-82d8-4c90be4fd75a.png)

Installation should now succeed. Please let us know if you continue to experience issues.
