### ISSUE TITLE
git hangs on "extracting"

### ISSUE THREAD

**Issue by jayandrewallen** [lukesampson/scoop#220]
This is, sadly, the only thing I can't get to install via scoop. It hangs for hours on "extracting...". Any insights? 

![git extracting hang](https://cloud.githubusercontent.com/assets/6911941/5129290/fc62e25e-7095-11e4-908c-2c0ffaccf55c.jpg)

LMK what files I can send for debugging.

**Comment by deevus** [comment]
@jayandrewallen Did you end up getting past this?

**Comment by Marineau** [comment]
Got the same exact problem, I wait like 30 min and then tried to copy past by right clicking on the shell, it suddenly complete the task. Maybe just a glitch.

**Comment by gnuchu** [comment]
Kept getting this same problem. Solved it by installing 7zip via the regular installer from the 7zip website and then making sure 7z.exe was on the path before trying to run anything via scoop.

**Comment by Ikeoth** [comment]
I was experiencing the same issue, I had 7zip installed and visible and in the system path but it got stuck on "extracting..." I ran it in an administrator Powershell and it worked immediately. I forgot rule #1 read the direction, don't be like me!
