### ISSUE TITLE
msys-gcc_s-1.dll is required after installing diffutils

### ISSUE THREAD

**Issue by ironsand** [lukesampson/scoop#2200]
I installed diffutils to my new Windows 10 home.
Then `msys-gcc_s-1.dll` is required to run the `diff` command.

After installing the DLL manually, it works fine.

The problem is solved for me now, I just want to report the issue.

Thanks.

**Comment by rasa** [comment]
Perhaps it needs http://repo.msys2.org/msys/i686/gcc-libs-6.4.0-3-i686.pkg.tar.xz

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2200
