### ISSUE TITLE
Installing from an exe containing a nupkg

### ISSUE THREAD

**Issue by boxfoot** [lukesampson/scoop#2202]
I'm trying to write a manifest for an app that installs from an exe that contains a nupkg, and I'm not sure how to do it.

`"url": "https://example.com/app-version-blah.exe#/dl.7z"`  downloads the file and extracts it correctly, but I'm left with a `nupkg` archive rather than a working app.

I know that I can run `7z x app-version-blah.nupkg` to extract that file, but I'm not sure where to put that command in the manifest.   If I put it in `post_install`, then I can't use `extract_dir` because the internal folders don't exist yet.  If I put it in `installer: script" then other things go wrong.

Can you explain or point to an example manifest that does this?  Thanks!

**Comment by rasa** [comment]
Try moving the `7z x app-version-blah.nupkg` to the `pre_install` section?

**Comment by boxfoot** [comment]
@r15ch13 Thanks for the suggestion, but I'm pretty sure there aren't nupkg direct downloads for the apps I'm trying to bundle, have been looking hard. 

Will try @rasa's method.

**Comment by Ash258** [comment]
Clarified enough I think. Could be closed.

**Comment by rasa** [comment]
Done
