### ISSUE TITLE
Duplicate gnupg and gpg package

### ISSUE THREAD

**Issue by SummerSad** [lukesampson/scoop#2208]
[gnupg](https://github.com/lukesampson/scoop/blob/master/bucket/gnupg.json)
and
[gpg](https://github.com/lukesampson/scoop/blob/master/bucket/gpg.json)
are exactly the same.
Should remove the duplicate.

**Comment by r15ch13** [comment]
Because it uses `env_add_path` instead of `bin` with every exe-file It's not searchable via `scoop search`, so this acts only as an alias.
