### ISSUE TITLE
Question: Switching between versions

### ISSUE THREAD

**Issue by notlmn** [lukesampson/scoop#2212]
For example, I've installed three versions of node: `9.10.1`, then `9.10.0`, and then `9.11.1` (using regular `scoop install nodejs@version`). Now the `current` directory points to `9.11.1` directory.

Now, is there a way to switch the `current` directory to point to `9.10.1` through scoop?

(I know I should use nvm to manage node versions but this problem is in general with other apps too, node is take just as an example).

**Comment by r15ch13** [comment]
`scoop reset nodejs@9.10.1`
`scoop reset nodejs@9.10.0`
`scoop reset nodejs` > will reset to `9.11.1`

**Comment by notlmn** [comment]
I thought `reset` reinstalled an app.

Thanks @r15ch13!
