### ISSUE TITLE
reuse download function of scoop

### ISSUE THREAD

**Issue by siddarthasagar** [lukesampson/scoop#2213]
i've written a json file for installing apache spark using scoop, as a part of postinstall i need to download winutils.exe from another link. Is there a way i can reuse any of scoops downloads function instead of configuring proxy again for this download call.

[https://github.com/siddarthasagar/scoopbucket/blob/master/apache-spark2.json](https://github.com/siddarthasagar/scoopbucket/blob/master/apache-spark2.json)

**Comment by r15ch13** [comment]
What about creating a separate manifest for `winutils` itself and add it as a dependency?

Also, there is no need to use `textise.net` to extract the version. Just change it to `http://spark.apache.org/downloads.html`

**Comment by siddarthasagar** [comment]
Thank you  for the quick response l'll fix the regex for the version check. I need to copy winutils into the bin folder of the Apache spark directory installation directory thats the reason I'm trying to download the exe as post install step.

But may be I can write a copy command instead by installing winutils as a dependency I'll give it try.

**Comment by siddarthasagar** [comment]
I also wanted ask am I missing anything in hash check in the auto update script ,it always says hash not found

**Comment by r15ch13** [comment]
You could use the [`dl()` function](https://github.com/lukesampson/scoop/blob/1f3757f32827f110b30a6b2bd3db412a319d83a4/lib/install.ps1#L153). Doesn't Apache Spark work when `winutils` is only in the `PATH`?

The hash extraction doesn't work because the file content looks like this:
`spark-2.3.0-bin-hadoop2.7.tgz: AF 45 EE B0 6D C1 BE EE  6D 4C 70 B9 2C 0E 02 37`
Currently, we use the following regex for hash extractions:
https://github.com/lukesampson/scoop/blob/1f3757f32827f110b30a6b2bd3db412a319d83a4/lib/autoupdate.ps1#L60

**Comment by r15ch13** [comment]
Made a small fix https://github.com/lukesampson/scoop/commit/cc9412c0ec646aa8b971fd1fb48a4a96b1d397a8
You can now match the hash like this:
```json
        "hash": {
            "url": "https://archive.apache.org/dist/spark/spark-$version/spark-$version-bin-hadoop2.7.tgz.md5",
            "find": "$basename:\\s+([a-fA-F\\d\\x20]+)"
        }
```

**Comment by r15ch13** [comment]
Improved and working manifest:
- Changed all URLs to HTTPS
- Use `winutils` from https://github.com/steveloughran/winutils
- Added `post_install` script to move `winutils` into `bin`
- Fixed hash extraction
```json
{
    "homepage": "https://spark.apache.org/",
    "version": "2.3.0",
    "extract_dir": "spark-2.3.0-bin-hadoop2.7",
    "url": [
        "https://www.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz#/spark.tar.gz",
        "https://github.com/steveloughran/winutils/raw/master/hadoop-2.7.1/bin/winutils.exe"
    ],
    "hash": [
        "md5:AF45EEB06DC1BEEE6D4C70B92C0E0237",
        "f933bd8d2547f795dc3165d269b3dc26b22059695616523fc06c8d69f6a54736"
    ],
    "post_install": "If(Test-Path(\"$dir\\winutils.exe\")) { Move-Item \"$dir\\winutils.exe\" \"$dir\\bin\\winutils.exe\" }",
    "env_add_path": "bin",
    "env_set": {
        "SPARK_HOME": "$dir",
        "HADOOP_HOME": "$dir"
    },
    "checkver": {
        "url": "https://spark.apache.org/downloads.html",
        "re": "Latest Release \\(Spark ([\\d.]+)\\)"
    },
    "autoupdate": {
        "url": "https://www.apache.org/dist/spark/spark-$version/spark-$version-bin-hadoop2.7.tgz#/spark.tar.gz",
        "extract_dir": "spark-$version-bin-hadoop2.7",
        "hash": {
            "url": "https://archive.apache.org/dist/spark/spark-$version/spark-$version-bin-hadoop2.7.tgz.md5",
            "find": "$basename:\\s+([a-fA-F\\d\\x20]+)"
        }
    }
}
```

**Comment by siddarthasagar** [comment]
Thank you very much richard, the above solution solves all my challenges.

**Comment by siddarthasagar** [comment]
Thank you very much richard, the above solution solves all my challenges.
