### ISSUE TITLE
Update Docker 

### ISSUE THREAD

**Issue by tejashah88** [lukesampson/scoop#2219]
From [docker.json](https://github.com/lukesampson/scoop/blob/master/bucket/docker.json), the listed version is v17.05.0, which was released about a year ago. The latest version is v18.03.0 which was released about a month ago.

**Comment by rasa** [comment]
Is 18.03.0 provided in [docker-nightly](https://github.com/lukesampson/scoop/blob/master/bucket/docker-nightly.json)?

**Comment by rasa** [comment]
Where do we find 18.03? The latest at https://download.docker.com/win/static/edge/x86_64/ is 17.10, which is what Chocolately is using. See https://chocolatey.org/packages/docker/

**Comment by tejashah88** [comment]
@rasa You're right, I tried searching for 18.03, but it's only released for linux and mac. I guess the least that we can ask for is updating to 17.10.

**Comment by tejashah88** [comment]
Closing due to #2235. Thanks @se35710!
