### ISSUE TITLE
Access Denied after installing Scoop on fresh Win10 Home install

### ISSUE THREAD

**Issue by SlvrEagle23** [lukesampson/scoop#2222]
Hello! I just finished setting up my brand new deployment powershell scripts, and in an effort to test it out, I reset/wiped one of my Windows 10 boxes and proceeded to install Scoop.

Immediately after Scoop was installed, further attempts to call `scoop install git` or any other scoop command were met with the following response:

```
ERROR loading ~/.scoop: Index operation failed; the array index evaluated to null.
Get-Content : Access to the path 'C:\Users\silve\.scoop' is denied.
At C:\Users\silve\.scoop\apps\scoop\current\lib\config.ps1:38 char:20
+         hashtable (Get-Content $cfgpath -raw | convertfrom-json -ea s ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\silve\.scoop:String) [Get-Content], UnauthorizedAccessExcept
   ion
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand

```

Here are the details of my Powershell version:

```
Name                           Value
----                           -----
PSVersion                      5.1.16299.15
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.15
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jmsalcido** [comment]
did you try running powershell with admin access or giving access to .scoop in your HOME path?

See website:

Note: if you get an error you might need to change the execution policy (i.e. enable Powershell) with `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`

**Comment by SlvrEagle23** [comment]
@jmsalcido Running PS as admin yields the same error message. I've also verified that the ExecutionPoilcy is more than permissive enough to allow Scoop to operate. The initial installation was attempted with the "Unrestricted" setting, and a retry with the "RemoteSigned" produced the same error.

The folder in question (`~/.scoop`) is owned by my user account and the user account has full permissions to access the folder, so the whole thing is quite confusing to me.

**Comment by rasa** [comment]
Have you turned off Windows Defender, and any other anti-virus/malware software? Rebooted?

**Comment by kenorb** [comment]
Executing `Set-ExecutionPolicy RemoteSigned -scope CurrentUser` worked for me.

**Comment by SlvrEagle23** [comment]
I'm closing this issue as I have been unable to reproduce this issue on subsequent installations of Scoop across multiple machines. The machine that was demonstrating the issue itself even started working after a clean Windows install. I haven't the slightest idea what the problem was.

**Comment by rasa** [comment]
@SlvrEagle23 Thanks for digging into it, and following up.

**Comment by fatihonur** [comment]
I thought sharing this would be useful for other people. I had similar issue and it worked after reboot.

`Remove-Item : Cannot remove item C:\Users\fatonu01\AppData\Local\Temp\7zr.exe: Access to the path
'C:\Users\fatonu01\AppData\Local\Temp\7zr.exe' is denied.
At line:4 char:1
+ Remove-Item "$dir\Uninstall.exe", "$dir\*-arm64.exe", $7zr
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\fatonu...al\Temp\7zr.exe:FileInfo) [Remove-Item], Unauthoriz
   edAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand`
