### ISSUE TITLE
use powershell install scoop,return MethodInvocationException

### ISSUE THREAD

**Issue by blythe104** [lukesampson/scoop#2227]
PS C:\Windows\system32> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')

使用“1”个参数调用“DownloadString”时发生异常:“操作超时” 所在位置 行:1 字符: 1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : WebException

**Comment by h404bi** [comment]
I guess you are suffering network problem, maybe you should try to use proxy while installation.

Tip: use below command to display error message in English.
``` powershell
[Threading.Thread]::CurrentThread.CurrentUICulture = 'en-US'; iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```

**Comment by blythe104** [comment]
yes,you are right,thank you so much
