### ISSUE TITLE
Windows 10 April 2018 Update Removes Scoop Shortcuts from Start Menu

### ISSUE THREAD

**Issue by SlvrEagle23** [lukesampson/scoop#2233]
I just updated my Win10 installation to the newest update (April 2018), and in the process, the shortcuts to my Scoop-installed apps were wiped from the Start menu. Not only is the "Scoop apps" folder missing entirely from the start menu, but the tiles pinned to the right side of the start menu have been removed as well.

Looking at the filesystem, it appears nothing has changed with the `~/scoop/` directory itself. The shims are still there and in place.

I'm not seeing any command that will easily allow me to re-establish these shortcuts, without simply uninstalling and reinstalling every application managed by Scoop.

Further research: Updating an existing application that _does_ have a new version will result in the Start menu link being recreated, but updating apps that _do not_ have new versions will not. The only apparent resolution at this point for the latter group of apps is to uninstall/reinstall them.

**Comment by Stanzilla** [comment]
Windows like to wipe parts of the registry during upgrades, usually it only happens for Insider upgrades for me but here you go https://aka.ms/AA16137

**Comment by SlvrEagle23** [comment]
@rasa Ah, it appears `scoop reset` does re-establish the shortcut if it's missing. I didn't know that was what it did.

**Comment by rasa** [comment]
In fact, `scoop reset *` should restore all the shortcuts.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
didn't happen for me

**Comment by se35710** [comment]
@rasa Maybe there should be a `-g` option for `scoop reset *` which only updates global apps? Not sure if there will be permission errors if running `sudo scoop reset *`, which in fact reset all apps, global or not.

**Comment by rasa** [comment]
`scoop reset *` already handles global apps, so it doesn’t need a `-g` option.

**Comment by rasa** [comment]
The issue appears to be resolved. If not, please reopen.

**Comment by raikesy** [comment]
This just happened to me with the "October" update. `scoop reset *` does seem to fix it, but shouldn't this issue stay open until this stops happening altogether, not just a workaround identified?

**Comment by 2377671184** [comment]
I had the same problem after updating to 1909 , and `scoop reset *` did solve it.

**Comment by walterlv** [comment]
I think this issue should not be fixed manually but be fixed automatically.

I'm a Windows 10 Insider Preview user so my windows update performs every week. If scoop does not fix this automatically, I have to run `scoop reset *` every week and this is not convenient.

**Comment by Stanzilla** [comment]
agree

**Comment by r15ch13** [comment]
I don't understand why Windows removes the `Scoop Apps` directory. I also can't find anything about windows deleting a directory from the start menu. Maybe it requires a registry entry somewhere? If someone would create a Directory manually, would it get deleted too?

**Comment by ferenczy** [comment]
Hey guys! I'm coming from the future. 🙂 Are you sure this issue has been fixed? Apps installed using Scoop are still disappearing from the Start menu on my system. I haven't noticed when exactly it happens, possibly after an update installation, but very often when I need to run an app, it's missing from the Start menu. The command `scoop reset <app>` or `scoop reset *` temporarily fixes it.

Scoop version: 0.5.2
Windows 11 Pro version: 24H2 (Insider edition)
OS build: 26120.4452
