### ISSUE TITLE
Option to install 32-bit architecture on a 64-bit Windows

### ISSUE THREAD

**Issue by garytyler** [lukesampson/scoop#2240]
Thanks for building this much needed tool. It is very nicely done.

Is there a practical way to override the architecture for a specific app install? In my case, I would prefer to use 32-bit versions of Python, even on a 64-bit Windows. I have been through the docs and couldn't find anything.

**Comment by r15ch13** [comment]
`scoop install python -a x86` or `-a 32bit`

**Comment by garytyler** [comment]
Thank you.
