### ISSUE TITLE
scoop no longer creates json files for the installed apps

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [lukesampson/scoop#2246]
all the sudden  scoop installs apps but no longer adds the json manifests for installed apps saying the path is incorrect but the path is fine despite what it says.

![image](https://user-images.githubusercontent.com/36826319/39662581-d8f09be8-5031-11e8-8d15-98e37de5b51f.png)

![image](https://user-images.githubusercontent.com/36826319/39662595-418dd6c0-5032-11e8-8c8e-bf710aac296c.png)

**Comment by r15ch13** [comment]
Godot is only available in the extras bucket but it tries to install it from the main bucket. :confused:
Try installing it, run scoop update and try again.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@r15ch13  i have extras added and it used to work fine before. it started happening recently

**Comment by rasa** [comment]
The fix is in #2243

**Comment by rasa** [comment]
@r15ch13 ok

**Comment by r15ch13** [comment]
@rasa thank you 😽
