### ISSUE TITLE
gcc install failed

### ISSUE THREAD

**Issue by mquarneti** [lukesampson/scoop#2249]
Installing 'gcc' (7.3.0) [64bit]
x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z (746 B) [========================================================] 100%
Checking hash of x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z... Hash check failed for 'https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.3.0/threads-posix/seh/x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z'.
Expected:
    784D25B00E7CF27AA64ABE2363B315400C27526BFCE672FDEE97137F71823D03
Actual:
    251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed

**Comment by r15ch13** [comment]
SourceForge seems to have problems again. Please keep trying.

**Comment by mquarneti** [comment]
Ok, thanks for the reply. It works now
