### ISSUE TITLE
Please revert update of editorconfig

### ISSUE THREAD

**Issue by quincunx** [lukesampson/scoop#2250]
Hi!

Please revert https://github.com/lukesampson/scoop/commit/6af1aa2f306b7d991799a82345081222fd4bdc16 - Version 0.12.2 seems to have been removed (https://sourceforge.net/projects/editorconfig/files/EditorConfig-C-Core/). 

Thanks!

**Comment by r15ch13** [comment]
Done

**Comment by lyuha** [comment]
Why update editorconfig to v0.12.2 at ac56119?
It seems editorconfig v0.12.2 don't exists in [Editorconfig Downlaod](https://sourceforge.net/projects/editorconfig/files/EditorConfig-C-Core/)
