### ISSUE TITLE
Scoop update fails

### ISSUE THREAD

**Issue by dipack95** [lukesampson/scoop#2251]
Scoop update fails:

`$ scoop update
Updating Scoop...
'git' is not recognized as an internal or external command,
operable program or batch file.
Scoop update failed.`

Doing a reinstall also fails:
`$ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.`

I have removed WSL and then tried the steps above, with the same results.

I'm not quite sure what to do next?

**Comment by r15ch13** [comment]
Remove/rename your `~\scoop` directory and try again. Then install `git` via scoop.

**Comment by dipack95** [comment]
Yeah, that seems to have worked.

Thanks!
