### ISSUE TITLE
install previous versions

### ISSUE THREAD

**Issue by pawelkuras** [lukesampson/scoop#2254]
While you can install an app of a particular version using:
`scoop install <app>@<version>`
this will only work if you don't already have a newer version of the app installed.

It would be nice to be able to:
1. install an older version of the app, but maybe not update the current version (or prompt the user).  This is useful for checking if a feature existed in an older version of an app, especially if you tend to use
`scoop cleanup`
a lot.

2.  switch your current version of the app using syntax similar to the version install syntax:
ie. `scoop reset <app>@<version>`
instead of the syntax described [here](https://github.com/lukesampson/scoop/wiki/Switching-Ruby-and-Python-Versions)

I uninstalled idea-ultimate (was on most recent 2018.1.3), and was able to install an old version using `scoop install <app>@<version>`, but now I can't update it to the most recent, see:
```
scoop update idea-ultimate
idea-ultimate: 2017.1.6 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

**Comment by r15ch13** [comment]
Does `scoop update idea-ultimate -f` work?

**Comment by pawelkuras** [comment]
@r15ch13 well that worked at getting me back up to 2018.1.3, thanks.  Are these options documented anywhere?  Coming back to the 2 feature requests; I think they still stand, as it's unfortunate that to install a previous version of an app you need to:
1) uninstall the existing app
2) install the old version of the app
and to bring it back to the new one, you have to use the -f option

**Comment by r15ch13** [comment]
`scoop reset <app>@<version>` is possible. The wiki is lacking this information.

**Comment by pawelkuras** [comment]
cool, good to know.

**Comment by rasa** [comment]
This appears to be resolved. If not, please reopen.

**Comment by jerrygreen** [comment]
Doesn't seem that this issue is resolved. I tried `scoop install nodejs@16`, but I'm getting error:

![image](https://user-images.githubusercontent.com/13215662/161654188-6c9299a6-7689-4fd8-a346-8e3159fe1a53.png)

`scoop install nodejs` works but it installs the latest current version (17), at while I want lts version (16)

**Comment by rashil2000** [comment]
Try `scoop install nodejs@16.9.1`

**Comment by jerrygreen** [comment]
Yeah, I eventually did `scoop install nodejs@16.14.2`, thanks.

Sorry for being unclear, because the mentioned problem "install previous versions", - is indeed resolved. It's another thing... Like for example when you make `npm install ...@16` will try to install the latest under version 16. One might say "using shortcuts for installing previous versions".

**Comment by nothing2314** [comment]
![image](https://user-images.githubusercontent.com/118598570/202845828-e3210a34-b5ad-4b8d-aab8-e937725302cb.png)

**Comment by nothing2314** [comment]
![smoothie](https://user-images.githubusercontent.com/118598570/202845841-3c072f0f-9e34-416c-85b1-b77eaad10710.png)
'smoothie' does not have autoupdate capability
couldn't find manifest for 'smoothie@0.6'

**Comment by rashil2000** [comment]
What's smoothie?

**Comment by nothing2314** [comment]
> What's smoothie
motion blur

**Comment by nothing2314** [comment]
> What's smoothie?

https://github.com/couleur-tweak-tips/Smoothie

**Comment by rashil2000** [comment]
It's not present in any bucket. You need to submit a manifest for that first.

**Comment by rashil2000** [comment]
See
https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests

**Comment by nothing2314** [comment]
I think am too stupid to make this work but thanks for answer
