### ISSUE TITLE
Stop update/installation when exe or directory is in use

### ISSUE THREAD

**Issue by parkovski** [lukesampson/scoop#2265]
If I update scoop when I have a C++ project in vscode open, because it runs a cmake server, I get an access denied message. Scoop continues trying to install, but doesn't write the files because it gets a permission denied, but still records the package as updated. If an access denied is encountered during an update, that package should be skipped and the user should be notified that it couldn't be updated.

Should probably amend this - installation should not be marked successful on any error (just got a different one trying to update vim)

**Comment by h404bi** [comment]
This is a known issue of scoop. The scoop-update sub-command needs to be enhanced in handling with update fails.

**Comment by rasa** [comment]
Implemented in [https://github.com/lukesampson/scoop/pull/3608](https://github.com/lukesampson/scoop/pull/3608)
