### ISSUE TITLE
Pshazz error message after updating Windows 10

### ISSUE THREAD

**Issue by Angeldude** [lukesampson/scoop#2268]
I updated Windows 10 from 1709 to 1803 and now when I run powershell, this message displays:

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at askpass.Program.Main(String[] args)
```

**Comment by Angeldude** [comment]
None, this is coming from pshazz. If I uninstall it, the message never displays. This only displays on startup of powershell.

**Comment by h404bi** [comment]
Maybe related: https://github.com/lukesampson/pshazz/issues/24

**Comment by Angeldude** [comment]
I dunno if the windows update changed something about where askpass searches the windows path but it was working fine in version 1709.

**Comment by h404bi** [comment]
I use 1803, it works fine.

**Comment by Angeldude** [comment]
After doing a huge deep dive into the system,  reading through the pshazz scripts and the askpass source code, I eventually started searching for issues with openssh. It was then that I discovered that windows 10 has an OpenSSH folder in its System32 folder, which I've never noticed before.

Running `scoop which ssh` would print the path to that directory instead of the openssh I had installed via scoop. I renamed theOpenSSH folder in the System32 directory and now they don't conflict anymore and the issue is resolved. However, I learned that that OpenSSH was supposedly also in Win10 1709 so it's strange that the conflict showed up now.

**Comment by Angeldude** [comment]
Yeah, since I didn't know windows 10 came with it. I'd try using it now but I can't figure out how to get it to work without that error.

**Comment by TCB13** [comment]
@Angeldude and @h404bi I only have scoop SSH installed and I'm getting this issue too. Here is the :

```
λ  scoop which ssh
C:\ProgramData\scoop\apps\win32-openssh\current\ssh.exe
```

**Comment by h404bi** [comment]
@TCB13 Do you use Windows 10? If yes, please try to uninstall the openssh you installed with scoop, restart the terminal, and just use the built-in openssh that located at `C:\WINDOWS\System32\OpenSSH\ssh.exe`, to see if the issue is gone.

**Comment by TCB13** [comment]
@h404bi I do use Windows 10 and I would like to keep my current OpenSSH version because of key compatibility issues. Apparently Windows 10 OpenSSH client only has a very small subset of features :(

**Comment by rodericktech** [comment]
Regardless of which SSH I'm using, or whether I uninstall all SSH packages from Scoop and use the one in Win 10, I get this Unhandled Exception as well but only when trying to log in to certain servers.  With others it works.  I'm completely stumped as to why this would consistently happen.  (Prior to the Win 10 update, using pshazz and some OpenSSH all of these connections used to work flawlessly.)

**Comment by daironmichel** [comment]
I had the same problem. After playing around a bit I just `scoop uninstall openssh` and then removed the `ssh` plugin from my custom pshazz theme file. So I'm just using the windows OpenSSH. Only thing is that if you're using `git` with `ssh` it'll ask you for the passphrase every time you interact with the remote (pull, push, fetch, etc). So I would recommend `https` for git remotes.

**Comment by leomwa** [comment]
Worked again after removing the ssh plugin from pshazz as @daironmichel mentions.

**Comment by TCB13** [comment]
Guys, I'm still having this issue. I don't have OpenSSH from Windows installed, but I had in the past, maybe there are some leftovers? My setup was:

```
scoop install sudo
sudo scoop install 7zip git win32-openssh pshazz
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which ssh)), 'USER')
```

At this point the ssh-agent didn't work:

```
ssh-add.exe
Error connecting to agent: No such file or directory
```

I believe this should be a service in my system, however:

```
Get-Service ssh-agent
Get-Service : Cannot find any service with service name 'ssh-agent'.
```

I also tried to run `install-sshd.ps1`, because, well, why not?:

```
cd "C:\Users\TCB13\scoop\apps\win32-openssh\current\"
 sudo .\install-sshd.ps1
**** Warning: Publisher OpenSSH resources could not be found or are not accessible
to the EventLog service account (NT SERVICE\EventLog).

[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and ssh-agent services successfully installed
C:\Users\TCB13\scoop\apps\win32-openssh\current
λ  .\ssh-add.exe
Error connecting to agent: No such file or directory
```

Sill the same issue, so I read somewhere I cloud try `sudo pshazz init`. After this last one it looked like everything was working fine, no more "no such file" errors, however when trying to ssh to a machine:

```
 ssh pdnl478

Excepção não processada: System.IndexOutOfRangeException: Índice fora dos limites da matriz.
   em askpass.Program.Main(String[] args)
```

Why? 

How can I "remove the ssh plugin from pshazz" @leomwa ?

Thank you.
