### ISSUE TITLE
Add https support to scoop.sh

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#2271]
See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by rasa** [comment]
See also https://www.theverge.com/2018/5/17/17365362/google-chrome-secure-indicator-https

**Comment by h404bi** [comment]
And don't forget to change that one in the project description, too.

**Comment by rasa** [comment]
@h404bi I don't see the option. Need Luke to do it.

**Comment by lukesampson** [comment]
I've completed the config for this and [https://scoop.sh](https://scoop.sh) should be working now or very soon as DNS changes propagate. I've checked the box to enforce HTTPS for scoop.sh but GitHub says it may take 24 hours to enable this.
