### ISSUE TITLE
Maybe env_add_path should adjust the paths' order for some shims

### ISSUE THREAD

**Issue by hyrious** [lukesampson/scoop#2275]
### Reproduce
```cmd
scoop install ffmpeg imagemagick
```
```cmd
where ffmpeg
~\scoop\apps\imagemagick\current\ffmpeg.exe
~\scoop\shims\ffmpeg.exe
```
### What was expected
```cmd
where ffmpeg
~\scoop\shims\ffmpeg.exe
~\scoop\apps\imagemagick\current\ffmpeg.exe
```
### Explanation
The ffmpeg's version is 4.0 currently, but the one included in imagemagick is 3.4. Some people might want to use the latest version.

I know nothing about powershell, maybe we should adjust some functions around this
https://github.com/lukesampson/scoop/blob/bcab4710ac821ac9cad95ecbd5b289b0169a7010/lib/install.ps1#L814

**Comment by rasa** [comment]
I would suggest we remove the `env_add_path` field from imagemagick.json
