### ISSUE TITLE
concfg hash expected incorrect value

### ISSUE THREAD

**Issue by W0rks** [lukesampson/scoop#2282]
Value for expected hash for installing concfg in bucket/concfg.json is set to a different hash than expected, which causes a hash check failure on install. Changing the hash to the expected one in the config.json file allows install. However, I want to make sure this is a legitimate version of concfg. Cheer!

**Comment by h404bi** [comment]
[https://www.virustotal.com/#/url/33a1025f7f587f468ec2b923cbb2b990b1f6bbec415b73025d315f48bebca9ae/details](virustotal).

The hash is correct, maybe there is network problem/download interception causing hash incorrect. Please try to clean the cache and reinstall it.
