### ISSUE TITLE
vim and vim of gow

### ISSUE THREAD

**Issue by abicorios** [lukesampson/scoop#2285]
Gow package contains vim. And single vim exists. I install vim and gow, so I can run only vim of gow (it is older). If I install gow, and vim, so I can run only new last single vim. Also, I can run only last installed program. Gow has ls.exe, and PowerShell has ls, so ls is ls of PowerShell and ls.exe is ls of Gow. But... Okay. How can we manage it, if we have two program with equal name?

**Comment by rasa** [comment]
Install gow, then vim. The last installed/updated app will take precedence. Use `scoop reset app` to override.
