### ISSUE TITLE
Hash check failed for innounp

### ISSUE THREAD

**Issue by btvedt-liquidnet** [lukesampson/scoop#2287]
Get a very similar error message any time I attempt to install something which requires Inno Setup.

PS H:\> scoop install xming
Installing 'innounp' (0.46) [64bit]
innounp046.rar (1.3 KB) [=====================================================================================] 100%
Checking hash of innounp046.rar... Hash check failed for 'https://r15ch13.keybase.pub/scoop/innounp/innounp046.rar'.
Expected:
    3c056e2fc46ca9e92405f13ddf1f250cfe4bd66cb83b6647d87c74bc7242b121
Actual:
    28894637152b4bc481a5fa4339185e9b453cbcb4415b2523d980f45501663314

**Comment by rasa** [comment]
3c056e2fc46ca9e92405f13ddf1f250cfe4bd66cb83b6647d87c74bc7242b121 Is correct.
