### ISSUE TITLE
Virtual Box Support

### ISSUE THREAD

**Issue by scottwillmoore** [lukesampson/scoop#229]
I have not used vagrant or virtual box very much before, however, [`virtual-box`](https://www.virtualbox.org/) appears to be a very popular choice for emulation of operating systems within the `vagrant` framework. Would it be possible to add a `virtual-box` app to scoop (It is open source as well).

I would normally add it myself, however after looking at it for a bit, I am not really sure how to include it within scoop. I also am not sure, as it it is such a low level program whether it requires a more specialised installation.

There is a realtively detailed [page](https://www.virtualbox.org/manual/ch02.html#installation_windows/) which explains how you can extract an `msi` from the `exe` using `VirtualBox.exe - extract`. It then also shows how different parameters can be passed to the `msi` in order to alter the installation (including a parameter which installs it locally for the user). However it is my understanding that `scoop` extracts `msi` files rather than actually executing them.

If anyone is more competent with handling `msi` files, would it be possible to implement `virtual-box` as an app within scoop? (also allowing `vagrant` to use it), or is that too complex and should we forget about `virtual-box` and instead should I install it manually.

**Comment by soderlind** [comment]
Any news on this ? Will virtual-box be available trough scoop ?

**Comment by scottwillmoore** [comment]
Hi, I have done some testing and I think this could be possible, the script above I believe works to some degree, however due to time constraints I do not have the time to finish it currently, but if anyone wants the rest of the files to play with I would be happy to post them here. It just consists of a manifest and this script which runs (you can check out `oracle-jdk` in the scoop-extras bucket as it functions in the exact same way; a manifest with a customised installation script).

**Comment by ntwb** [comment]
I tend to agree installing Virtual Box outside of Scoop may be the best solution for now.

And apologies, same boat, not enough time to do all the things....

**Comment by deevus** [comment]
I had looked at this previously and should have a local branch on my PC. I'll have a look when I get home to see how far I got.

**Comment by MrException** [comment]
Were any of you able to make progress with this? I would love to be able to install VirtualBox like this.

**Comment by deevus** [comment]
I'm going to go with this is never going to work. You need to install drivers which requires elevated privileges.
