### ISSUE TITLE
Why does scoop place duplicate exe's in the shim from installed app?

### ISSUE THREAD

**Issue by AddictArts** [lukesampson/scoop#2294]
From the wiki I could not find why there are exe's in the shim directory? They seem to be duplicates of the app bin's or maybe not. Is it an executable that uses it's name to look at the ps1 file and find the real exe? just guessing there.

**Comment by rasa** [comment]
An .exe shim is required so a search in the `%PATH%` for `ex.exe` will work. A shim is required as a simple symlink keeps the .exe from finding .dlls or other related files used by the target .exe The shim .exe sets up the environment correctly so the target .exe can find its .dlls, etc.

**Comment by AddictArts** [comment]
Thanks. Essentially you don't want to pollute the path with a bunch of entries it seems. As well as polluting a common directory like \windows that is already in the path. I see the C# source here for the shim, thanks again.

**Comment by rasa** [comment]
Windows has a hard limit of how long the `%PATH%` can be. Somewhere around 2,048, or 4,096 characters. See https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable
