### ISSUE TITLE
download-url for rsync is incorrect

### ISSUE THREAD

**Issue by hreese** [lukesampson/scoop#2295]
https://www.itefix.net/dl/cwrsync_5.7.2_x86_free.zip only gets the gpg signature instead of the installer executable. I was unable to find/guess the correct url.

**Comment by r15ch13** [comment]
Apparently, they have added a [6$ Download Fee](https://www.itefix.net/download-fee)

**Comment by dsbert** [comment]
Yes... I've had to switch to using rsync from the linux subsystem

**Comment by rasa** [comment]
Should we "disable" broken apps for now? How about renaming them to `bucket/disabled/app.json`?

**Comment by dsbert** [comment]
This is the response I received from the maintainer of cwRsync. Reads like this is a permanent change.

> We don’t offer free versions of our products any longer. We are a company and want to offer high quality and up to date open source installer packages producing a value to our customers. It is not a viable alternative to offer them as free. You can see the same trend in the industry. Everything costs something now. Even to produce an GDPR compliant privacy policy.

**Comment by hannesdorn** [comment]
http://www.aboutmyip.com/AboutMyXApp/DeltaCopyDownloadRaw.jsp seems to be a possible replacement.

**Comment by rasa** [comment]
http://repo.msys2.org/msys/x86_64/rsync-3.1.3-1-x86_64.pkg.tar.xz Is the best alternative

**Comment by rasa** [comment]
Here's a potential solution: https://github.com/rivy/scoop-bucket/blob/master/rsync.json

**Comment by fritzmg** [comment]
May be https://blog.tiger-workshop.com/add-rsync-to-git-bash-for-windows/ is an alternative (http://repo.msys2.org/msys/x86_64/rsync-3.1.2-2-x86_64.pkg.tar.xz).

**Comment by ammgws** [comment]
It looks like it's available as a free download again, though capped at v5.5
https://www.itefix.net/cwrsync-free-edition

**Comment by ZYinMD** [comment]
Although it's not a drop-in replacement, I'd like to mention that Windows has `robocopy`, which does the same thing as rsync.
