### ISSUE TITLE
About LibreOffice...

### ISSUE THREAD

**Issue by angelog0** [lukesampson/scoop#2297]
Just out of curiosity.. Why is LibreOffice not included in `SCOOP`?

Thanks,
 Angelo.

**Comment by Ash258** [comment]
Because its inside [Extras bucket](https://github.com/lukesampson/scoop-extras/).

**Comment by r15ch13** [comment]
https://github.com/lukesampson/scoop-extras/blob/master/libreoffice-fresh.json

**Comment by SharakPL** [comment]
Can this install be customized? There is only x86 version being installed. What about x86_64? Also even though multilingual version is provided it lacks polish translation. Can it be added?
