### ISSUE TITLE
Feature: Parallel and multi-piece downloading to speed up downloads

### ISSUE THREAD

**Issue by jas99** [lukesampson/scoop#2306]
Some of my downloads are very slow and get stuck; maybe because of location or ISP. But when I use download manager they download into multiple pieces, the issues is fixed. So I purpose to use cli tool you like to do multi piece download. It will speed up download in general as well. 

Or at-least allow to set custom command to select downloader.
Thx

**Comment by r15ch13** [comment]
Working on a solution right now 😁

**Comment by jas99** [comment]
@r15ch13 Thats awesome!!!
@rasa I was thinking same 😄

**Comment by r15ch13** [comment]
@jas99 can you test if these changes work for you? #2312

**Comment by jas99** [comment]
@r15ch13 
Did work for me, is thr any othr config I need to set?
```
bin aria2 = $ .\scoop.ps1 config enable_aria2 true
bin aria2 = $ .\scoop.ps1 install godot
Installing 'godot' (3.0.3) [64bit]
Godot_v3.0.3-stable_win64.exe.zip (17.3 MB) [>                                                                      ]   0%
bin aria2 = $
```

**Comment by r15ch13** [comment]
You have to install aria2 via scoop 👍
Scoop will use aria2 by default, so the config flag is only required for disabling it.

**Comment by jas99** [comment]
cool !!

**Comment by jas99** [comment]
Awesome, working for me!!! 👍 
How to increase number of threads?

Thx

**Comment by r15ch13** [comment]
@jas99 currently the values are fixed. Let's discuss this in https://github.com/lukesampson/scoop/pull/2312

**Comment by xeijin** [comment]
Is the aria2c support part of the master yet? When I install using the instructions on scoop.sh, then install aria2c, it doesnt seem to use aria2c for downloads (nor do any of the config variables get set)
