### ISSUE TITLE
Fail to install editorconfig 0.12.2

### ISSUE THREAD

**Issue by lyuha** [lukesampson/scoop#2309]
Fail to download editorconfig 0.12.2. Editorconfig 0.12.2 don't exists in sourceforge repository.

```
PS>scoop install editorconfig
Installing 'editorconfig' (0.12.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://downloads.sourceforge.net/project/editorconfig/EditorConfig-C-Core/0.12.2/binary-Windows/editorconfig-0.12.2-Windows-x86.zip is not valid
```

Seems similar issue(#2250).

**Comment by rasa** [comment]
Confirmed 404: https://downloads.sourceforge.net/project/editorconfig/EditorConfig-C-Core/0.12.2/binary-Windows/editorconfig-0.12.2-Windows-x86.zip

**Comment by r15ch13** [comment]
Reverted to 0.12.1 and changed `checkver` to use the SourceForge folder names
