### ISSUE TITLE
The remote name could not be resolved while installing scoop in PowerShell

### ISSUE THREAD

**Issue by rafitur2** [lukesampson/scoop#2316]
Getting below error while trying to insall scoop:
**Command:**

> iex (new-object net.webclient).downloadstring('https://get.schoop.sh')

**Error:**

> Exception calling "DownloadString" with "1" argument(s): "The remote name could not be resolved: 'get.schoop.sh'"
> At line:1 char:1
> + iex (new-object net.webclient).downloadstring('https://get.schoop.sh')
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : WebException

I tried to use solution from different thread but facing same issue:

**command:**

> `iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1') --proxy genproxy.amdocs.com:8080`

**Error:**

> iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1')
> Exception calling "DownloadString" with "1" argument(s): "The remote name could not be resolved: 'raw.githubusercontent.com'"
> At line:1 char:1
> + iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com ...
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : WebException

**Permission command**
Get-ExecutionPolicy -List

**Results**
Get-ExecutionPolicy -List

  

>         Scope       ExecutionPolicy
>            -----      ---------------
>    MachinePolicy      Undefined
>       UserPolicy      Undefined
>          Process      Undefined
>      CurrentUser      RemoteSigned
>     LocalMachine      Unrestricted

**Comment by rasa** [comment]
s/schoop/scoop
