### ISSUE TITLE
An exception occurs during a WebClient request.

### ISSUE THREAD

**Issue by Mynini** [lukesampson/scoop#2325]
I meet an error  when I install scoop on win10. The Error is as follows. I can,t understand why the error is happen.Hope you can help me
```
error:
使用“1”个参数调用“DownloadString”时发生异常:“在 WebClient 请求期间发生异常。”
所在位置 行:1 字符: 1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by r15ch13** [comment]
What is the output of `$PSVersionTable`?

**Comment by Mynini** [comment]
@r15ch13 
The out put is follow

PS E:\liyulan\AiiageSteamBlocks> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by r15ch13** [comment]
Open the PowerShell and run the following commands:
```
$wc = new-object net.webclient
$str = $wc.downloadstring('https://get.scoop.sh')
iex $str
```

And what is the output of: `[Net.ServicePointManager]::SecurityProtocol`

**Comment by rasa** [comment]
GFW, no author response.
