### ISSUE TITLE
Haskell's installation directory doesn't seem right

### ISSUE THREAD

**Issue by mickmetalholic** [lukesampson/scoop#2328]
When i run
```
scoop install haskell
```
the haskell platform is installed to the default directory which is C:\Program Files\Haskell Platform but not  C:\Users\USER\scoop\apps\haskell\ which remains empty.

Also it lead to the shim fail because files don't exist at the right directory:
```
Can't shim 'bin\ghc.exe': File doesn't exist.
```

**Comment by r15ch13** [comment]
Try to uninstall haskell and try it again. It may install to the last known location because you installed it manually.

**Comment by rasa** [comment]
No, it’s a bug. See https://github.com/haskell/haskell-platform/issues/311

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2328
