### ISSUE TITLE
Shim console window stays open when launching from Start Menu search

### ISSUE THREAD

**Issue by dirvo** [lukesampson/scoop#2332]
When running an installed app via the generated shim exe, a console window stays open in the background. I'd expect that window to not be shown or to be closed immediately after the application is launched.

Steps for reproducing:
- Install an app via scoop, e.g. I installed git and ilspy in the global scope
- In the Windows 10 start menu, type, e.g. "git-bash" or "ilspy" to search for the name of the shim. The search finds a matching result with the shim icon, showing the text "Run command" below the command name.
- Select the search result and press Enter
- A console window with the full path to the shim exe is opened in the background, then the actually launched application appears on top.
- The console window stays open in the background

Notes:
- Another way to repro is to double-click on the shim exe in the scoop\shims folder
- It works as expected if you ~~run the shim exe via Windows > Run (Win+R) or~~ launch the shim from a cmd prompt.

**Comment by r15ch13** [comment]
Is this related to https://github.com/lukesampson/scoop/issues/1606?

**Comment by dirvo** [comment]
Yes, this indeed a dupe of #1606 (didn't find that issue using the search, sorry).
