### ISSUE TITLE
Composer's self-update command clashes with scoop's

### ISSUE THREAD

**Issue by gwenl** [lukesampson/scoop#2341]
When Composer is installed with Scoop, the following command will have scoop update Composer,  instead of running Composer to prompt the user for keys:
````
composer self-update --update-keys
````
This is due to scoop hijacking the command when "self-update" is used, but "self-update" can also be called to pass options that change the meaning of the command. This is also true for other options (see composer self-update --help for the list)

Is it possible to change this behavior so that whenever an argument is passed after "self-update", scoop does not hijack the command ?

**Comment by r15ch13** [comment]
Good point. Done 😄
