### ISSUE TITLE
curl@7.60.0: hash check failed

### ISSUE THREAD

**Issue by Arkadiusz-Czubik** [lukesampson/scoop#2345]
Installing 'curl' (7.60.0) [64bit]
curl-7.60.0-win64-mingw.tar.xz (1.9 MB) [================================================================================================================================================================] 100%
Checking hash of curl-7.60.0-win64-mingw.tar.xz... ERROR Hash check failed!
App:       curl
URL:       https://dl.bintray.com/vszakats/generic/curl-7.60.0-win64-mingw.tar.xz
Expected:  5f3594236dcd3385033d0d754f445b24bdcf93c9a9db17cd4c4fcb8b02e2d0db
Actual:    febfbd5fffdec1ca2d7a187faa01abf38065395894cac995fc9e3a862f7995c4

**Comment by Arkadiusz-Czubik** [comment]
Installing 'curl' (7.60.0) [64bit]
curl-7.60.0-win64-mingw.tar.xz (1.9 MB) [================================================================================================================================================================] 100%
Checking hash of curl-7.60.0-win64-mingw.tar.xz... ERROR Hash check failed!
App:       curl
URL:       https://dl.bintray.com/vszakats/generic/curl-7.60.0-win64-mingw.tar.xz
Expected:  5f3594236dcd3385033d0d754f445b24bdcf93c9a9db17cd4c4fcb8b02e2d0db
Actual:    febfbd5fffdec1ca2d7a187faa01abf38065395894cac995fc9e3a862f7995c4

**Comment by brandon93s** [comment]
![image](https://user-images.githubusercontent.com/4730164/42255327-2be963d2-7f19-11e8-88c6-437f460407a7.png)

No issues on my end. Please try again and let us know if you're still having issues.

**Comment by Arkadiusz-Czubik** [comment]
Still the same. Other packages install without any issues.

![image](https://user-images.githubusercontent.com/12124736/42257756-6a6daade-7f58-11e8-8386-e2adaaf67f0a.png)
