### ISSUE TITLE
Request: Install emsdk

### ISSUE THREAD

**Issue by ankemp** [lukesampson/scoop#2346]
Getting started: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#sdk-download-and-install
Repo: https://github.com/juj/emsdk

**Comment by r15ch13** [comment]
Something like this?

```json
{
    "homepage": "https://kripken.github.io/emscripten-site/",
    "version": "nightly",
    "license": "MIT",
    "url": "https://github.com/juj/emsdk/archive/master.zip",
    "extract_dir": "emsdk-master",
    "bin": [
        "emsdk.ps1",
        "emsdk_env.ps1"
    ]
}
```

It's only useful to install it as a nightly. It installs all dependencies to its root directory. There is no way we can make everything persistent.

**Comment by r15ch13** [comment]
Take a look at: https://github.com/lukesampson/scoop/tree/master/bucket
All programs are defined as JSON files 😄

**Comment by Boscop** [comment]
@ankemp @r15ch13 Yes, please add emscripten SDK to scoop, it would be much more convenient!

**Comment by Boscop** [comment]
@ankemp Did you manage to add emscripten to the bucket? I can't see it here:
https://github.com/ScoopInstaller/Main/tree/master/bucket
Or did you add it to a different bucket?

**Comment by ankemp** [comment]
To be honest, this was two years ago and I don't remember.
