### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by LambdaV5** [lukesampson/scoop#2353]
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz... ERROR Hash check failed!
App:       openssh
URL:       http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
Expected:  892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd
Actual:    bb22a0e9438fb4720c2f6d0dce08ceddc7f4e357fbb83e99b1cc3bedb73c601e

**Comment by rasa** [comment]
$ sha256sum gcc-libs-6.4.0-1-x86_64.pkg.tar.xz 
892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd *gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
