### ISSUE TITLE
'scoop install r' fails - Unpacking innosetup... Failed to unpack innosetup file. See C:\Users\whein\scoop\apps\r\3.5.1\innounp.log

### ISSUE THREAD

**Issue by wheineman** [lukesampson/scoop#2360]
~ $ scoop install r
Installing 'r' (3.5.1) [64bit]
Loading R-3.5.1-win.exe from cache
Checking hash of R-3.5.1-win.exe... ok.
Unpacking innosetup... Failed to unpack innosetup file. See C:\Users\whein\scoop\apps\r\3.5.1\innounp.log
~
And the log file:
~ $ cat C:\Users\whein\scoop\apps\r\3.5.1\innounp.log
; Version detected: 5507 (Unicode)
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
~

**Comment by alexeq** [comment]
Innounp should be updated - see https://github.com/lukesampson/scoop/pull/2347 pull request comments

**Comment by r15ch13** [comment]
Please run `scoop update innounp` and try again.
