### ISSUE TITLE
rustup@1.12.0: hash check failed

### ISSUE THREAD

**Issue by yuguuk** [lukesampson/scoop#2374]
App:       rustup
URL:       https://win.rustup.rs/#/rustup-init.exe
Expected:  b33a82c54199a427172fec8957760ae7c9a7b7a13b0814bdddb4438e7f88e801
Actual:    3fb8f86baf3422e47fef2009697fd7c83226f989008db9e965f75c6d65abace5

**Comment by h404bi** [comment]
`3fb8f86baf3422e47fef2009697fd7c83226f989008db9e965f75c6d65abace5` is correct. [VirusTotal](https://www.virustotal.com/#/url/d7d84d4a87e31ce7e2646a91876145799ae283419b83fe3b195a5ecc2a1d08d2/details)
