### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by daviszhao** [lukesampson/scoop#2375]
Installing 'openssh' (7.6p1) [64bit]
Loading gcc-libs-6.4.0-1-x86_64.pkg.tar.xz from cache
Loading heimdal-1.5.3-9-x86_64.pkg.tar.xz from cache
Loading heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz from cache
Loading icu-59.1-1-x86_64.pkg.tar.xz from cache
Loading libcrypt-2.1-1-x86_64.pkg.tar.xz from cache
libdb-5.3.28-2-x86_64.pkg.tar.xz (656.4 KB) [=================================================================] 100%
libedit-3.1-20170329-x86_64.pkg.tar.xz (96.9 KB) [============================================================] 100%
libopenssl-1.0.2.m-1-x86_64.pkg.tar.xz (1,022.5 KB) [=========================================================] 100%
libreadline-7.0.003-1-x86_64.pkg.tar.xz (266.8 KB) [==========================================================] 100%
libsqlite-3.19.3.0-2-x86_64.pkg.tar.xz (564.3 KB) [===========================================================] 100%
msys2-runtime-2.9.0-2-x86_64.pkg.tar.xz (2.4 MB) [============================================================] 100%
ncurses-6.0.20170708-2-x86_64.pkg.tar.xz (1.1 MB) [===========================================================] 100%
openssh-7.6p1-1-x86_64.pkg.tar.xz (679.9 KB) [================================================================] 100%
zlib-1.2.11-1-x86_64.pkg.tar.xz (55.1 KB) [===================================================================] 100%
bash-4.4.012-1-x86_64.pkg.tar.xz (1.9 MB) [===================================================================] 100%
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz... ok.
Extracting... done.
Checking hash of heimdal-1.5.3-9-x86_64.pkg.tar.xz... ok.
Extracting... done.
Checking hash of heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz... ok.
Extracting... done.
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz... ERROR Hash check failed!
App:       openssh
URL:       http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
Expected:  d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:    d9ec22d11530bdbda52cddab3bf0f39b28fdc6181b173c584eee560b07c113b2

**Comment by rasa** [comment]
Closing as this issue appears to be obsolete.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2375
