### ISSUE TITLE
virtualenv installed with scoop's python cannot make a virtualenv

### ISSUE THREAD

**Issue by sohnryang** [lukesampson/scoop#2383]
I installed python with this command:

```
scoop install python
```

Then, I installed virtualenv:

```
pip install virtualenv
```

I tried to make a virtualenv with this command:

```
virtualenv venv
```

The last command produces this error:

```
Using base prefix 'c:\\programdata\\scoop\\apps\\python\\3.7.0'
New python executable in C:\Users\sohnryang\venv\Scripts\python.exe
ERROR: The executable C:\Users\sohnryang\venv\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is 'c:\\users\\sohnryang' (should be 'c:\\users\\sohnryang\\venv')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```

Even if I install python globally with command `scoop install python --global`, virtualenv produces the same error.

**Comment by pharazone** [comment]
Same problems.

**Comment by pharazone** [comment]
python -m virtualenv venv   

can you do this?add "python -m" in front of your command.

**Comment by sohnryang** [comment]
Tried it. Same error.

I managed to fix this issue by installing anaconda, not the official python interpreter.

**Comment by gdw2** [comment]
I use `python -m virtualenv venv` without problems.  So at least it's not universally reproducible.

**Comment by sohnryang** [comment]
By the way, since I'm familiar to Linux command line, do I have to use `python -m` in order to use python commands like `virtualenv` in Windows command line?

**Comment by copdips** [comment]
@sohnryang 
Please use the recommended way to use the venv:
https://docs.python.org/3/library/venv.html#creating-virtual-environments

`python -m venv myEnvName`
virtualenv is deprecated, you dont even need to run `pip install virtualenv`, venv is embedded already.

**Comment by sohnryang** [comment]
@copdips Thanks!

**Comment by copdips** [comment]
@sohnryang,

if all good for you, please close the issue:)

**Comment by sohnryang** [comment]
Okay. Closing the issue.

**Comment by WqyJh** [comment]
> @sohnryang
> Please use the recommended way to use the venv:
> https://docs.python.org/3/library/venv.html#creating-virtual-environments
> python -m venv myEnvName
> virtualenv is deprecated, you dont even need to run pip install virtualenv, venv is embedded already.

Well, that's indeed a good solution, but what about pipenv?
If we use pipenv for our project, pipenv will invoke virtualenv and got the same error.

**Comment by copdips** [comment]
I retested `pip install virtualenv` and `virtualenv venv` with freshly installed python by scoop, no error thrown.

`pipenv --python 3.7` and `pipenv install [a_package]` are OK too.

**Comment by WqyJh** [comment]
> I retested pip install virtualenv and virtualenv venv with freshly installed python by scoop, no error thrown except for a known warning about the Scripts path, as scoop uses the symbolic link to the current one, so the warning is safe.
> pipenv --python 3.7 and pipenv install [a_package] are OK too.

Well, my `pipenv install` failed which is also an freshly installed python by scoop and people above got the same error.

You don't got this error may because you have installed `vcruntime140.dll` globally. Indeed, to install the missing DLLs could be a good solution. But it's not nice enough. I just created a small patch to `scoop` which solves this problem without any other effort for users. Please see https://github.com/ScoopInstaller/Main/pull/316

**Comment by copdips** [comment]
ok thx for the info.
`vcruntime140.dll` is installed in  C:\Windows\system32 on my computer, but I also find it in the python root folder by scoop python version. And this path is not in the PATH yet.

If `vcruntime140.dll` is the key point, your https://github.com/ScoopInstaller/Main/pull/316 should be approved :)

**Comment by copdips** [comment]
you're right, I just tested by renaming `vcruntime140.dll`, then `pipenv --python 3.7` doesn't work anymore.
