### ISSUE TITLE
fail to install Python 3.7 x86 

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop#2385]
PS> scoop install python -a 32bit
Installing 'python' (3.7.0) [32bit]
Loading python-3.7.0.exe from cache
Checking hash of python-3.7.0.exe... ok.
Running pre-install script...
Running installer... done.
Linking ~\scoop\apps\python\current => ~\scoop\apps\python\3.7.0
Creating shim for 'python'.
Can't shim 'python.exe': File doesn't exist.

Note, I was able to install Python 3.6 32 bit (scoop install python36 -a 32bit) without issue

**Comment by r15ch13** [comment]
Can you try uninstalling it completely and retry it?

**Comment by devhawk** [comment]
That appears to have worked. I was trying to switch from 64bit to 32bit and for reasons I don't know the 3.7 64 bit version was still on the app list. I had to repair and then uninstall, but after that I was able to install 3.7 32 bit w/o issue.
