### ISSUE TITLE
openssh@7.6p1 unable to download

### ISSUE THREAD

**Issue by TangentFoxy** [lukesampson/scoop#2388]
```
Scoop was updated successfully!
Installing 'openssh' (7.6p1) [64bit]
Unable to connect to the remote server
URL http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz is not valid
```

**Comment by r15ch13** [comment]
Please try again. msys2.org has some weird problems lately.

**Comment by Guard13007** [comment]
Same error. :/ I thought for a moment it might have something to with forgetting to do IE's first-time setup, which it turned out I had not done (wasn't there a specific error message for that previously?)

But still not working. I am having a few other strange issues on this PC so I will try again after a reboot.

**Comment by Guard13007** [comment]
Tested again on different network after reboot and updates, still having the same issue. :/

**Comment by r15ch13** [comment]
Whats the output when you run `wget http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz` from PowerShell? Whats the output of `$PSVersionTable`

**Comment by Guard13007** [comment]
```
~ $ wget http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
--2018-07-13 08:29:23--  http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
Resolving repo.msys2.org (repo.msys2.org)... 45.59.69.178
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80... failed: Unknown error.
Retrying.

--2018-07-13 08:29:45--  (try: 2)  http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80... failed: Unknown error.
Retrying.

--2018-07-13 08:30:08--  (try: 3)  http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80... failed: Unknown error.
Retrying.

~ $ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Guard13007** [comment]
(Output from desktop, was initially experiencing error on laptop, but occurs on both.)

**Comment by Guard13007** [comment]
I can get that info from the laptop as well if you want? I imagine it's doing the same thing, just wish I knew what "Unknown error" actually means.

**Comment by r15ch13** [comment]
Does curl work? `curl.exe -v http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz -o bla.tar.xz`
Firewall?
Proxy settings (`netsh winhttp show proxy`)?

That's a strange one...

**Comment by Guard13007** [comment]
@rasa I would be doing that, except for some reason it keeps trying to use the non-existent one from openssh. This problem all started when I tried to update everything and it uninstalled the old version before failing to install the new version. :/

@r15ch13 
```
~ $ curl.exe -v http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz -o bla.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 45.59.69.178...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0* connect to 45.59.69.178 port 80 failed:
Timed out
* Failed to connect to repo.msys2.org port 80: Timed out
* Closing connection 0
curl: (7) Failed to connect to repo.msys2.org port 80: Timed out
```

No proxy, but just to be sure. (Double checked just in case.)

**Comment by rasa** [comment]
Closing as this issue appears to be obsolete.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2388

**Comment by rasa** [comment]
Reopened by accident.
