### ISSUE TITLE
Add text/tags to project to allow searching

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop#2390]
A call to https://api.github.com/search/repositories?q=scoop+bucket&per_page=500 does not return the main bucket, or the versions bucket.

To fix that, let's add the text "Main sccop bucket" to scoop, and "Scoop bucket for beta, and older versions of apps" to versions.

Additionally, let's add the tags `scoop` and `bucket` to both of them.

I would do it, but I don't have the rights to.

**Comment by lukesampson** [comment]
I've added the topics you suggested to both repos, and some text for the versions repo. 

I've left the Scoop project description text as is because it describes the project succinctly and I think the topics were enough to get it to show up in the API search.

**Comment by rasa** [comment]
You’re probably right. Thanks so much for the quick response!

**Comment by Calinou** [comment]
Adding the `scoop-bucket` tag is probably a good idea, as the [bucket](https://github.com/topics/bucket) topic returns many unrelated results.

**Comment by lukesampson** [comment]
OK, I've added `scoop-bucket` as well.

**Comment by r15ch13** [comment]
The [extras bucket](https://github.com/lukesampson/scoop-extras) is missing the tags

**Comment by rasa** [comment]
Yes, we should consistently use, and suggest, the `scoop-bucket` tag. I think we should keep the `scoop` topic. Should we discard using the `bucket` topic, as being too polluted?

**Comment by lukesampson** [comment]
All three repos (main, extras and versions) now have `scoop` and `scoop-bucket` as topics. I tried removing `bucket` from the main repo but the API search for "scoop bucket" no longer returns the main repo in that case. So I've added the `bucket` topic back to the main repo and left it off the others as they continue to match the search without it.
