### ISSUE TITLE
Git stops working after updating openssh

### ISSUE THREAD

**Issue by pitgrap** [lukesampson/scoop#2392]
After updated openssh to 7.6p1 running git stops working.  It could not find ssh anymore. Git is installed via scoop too.

```
...
'openssh' (7.6p1) was installed successfully!

C:\dev\cms
λ git fetch
error: cannot spawn C:\Users\XXX\scoop\apps\openssh\current\bin\ssh.exe: No such file or directory
fatal: unable to fork
```

```
λ scoop list
Installed apps:

  git 2.18.0.windows.1
  openssh 7.6p1
```

**Comment by rasa** [comment]
We’re not getting any reports regarding the [`git-with-openssh`](https://github.com/lukesampson/scoop/blob/master/bucket/git-with-openssh.json) package. To install it, do:
```
scoop install git-with-openssh
scoop uninstall git openssh
scoop reset git-with-openssh
```

**Comment by rasa** [comment]
We could solve this in a few ways:
1. Rename `git-with-openssh.json` to `git.json`, and create a new `git-only.json`
2. Put loud notes in the git and openssh packages, to advise users to install git-with-openssh, if they want inter-operability
3. Make sure that `git.json` and `openssh.json`’s versions are compatible, before pushing updates out

**Comment by r15ch13** [comment]
Just uninstalled `git-with-openssh` to reproduce this, but it works for me.
Had to change the `GIT_SSH` environment variable, which still pointed to the wrong `ssh.exe`, and it works.

I can't reproduce any of these weird `openssh` bugs that appeared in the last few days ... 😢

**Comment by leonyu** [comment]
Try with `win32-openssh`? It is the Microsoft fork of OpenSSH

**Comment by pitgrap** [comment]
@r15ch13 With the openssh 7.6 the folder structure changed.

Before: `bin\ssh.exe`
Now: `usr\bin\ssh.exe`

Ich changed my `GIT_SSH` environment variable and it works now. I will close this ticket. Thanks everyone for your help.
