### ISSUE TITLE
shellcheck@0.5.0: hash check failed

### ISSUE THREAD

**Issue by godeater** [lukesampson/scoop#2393]
Checking hash of shellcheck-v0.5.0.zip... ERROR You cannot call a method on a null-valued expression.
ERROR Hash check failed!
App:         shellcheck
URL:         https://shellcheck.storage.googleapis.com/shellcheck-v0.5.0.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    cbfca919a03f058bc9b31b1d932450f63dbdb92dcfec1a30140e022f7db49bc0
Actual:

**Comment by gbursson** [comment]
it has a correct hash and it is working for me:

D:\Programming\github> scoop install shellcheck
Installing 'shellcheck' (0.5.0) [64bit]
shellcheck-v0.5.0.zip (6.1 MB) 
Checking hash of shellcheck-v0.5.0.zip... ok.
Extracting... done.
Running pre-install script...
Linking P:\Scoop\apps\shellcheck\current => P:\Scoop\apps\shellcheck\0.5.0
Creating shim for 'shellcheck'.
'shellcheck' (0.5.0) was installed successfully!

**Comment by r15ch13** [comment]
@godeater did you try it again? It seems the file got deleted or something before the hash check.

**Comment by godeater** [comment]
I've tried it several times - it fails everytime with the same message:

```
scoop install shellcheck
Updating Scoop...
 * 0c2b3da3 Don't send referer to portableapps.com                       54 minutes ago
 * d2c4b834 ffmpeg-nightly: Update to version 20180716-b8c4d2b           4 hours ago
 * 1141b15e vim: Update to version 8.1.0189                              14 hours ago
 * 7a6218c5 Show message about missing bucket when installing dependen.. 21 hours ago
 * 9103cfe6 cygwin: Update to version 2.892                              24 hours ago
 * 077c8ad8 ffmpeg-nightly: Update to version 20180714-c5329d6           28 hours ago
 * f2e4512c vim: Update to version 8.1.0186                              2 days ago
 * 1f5a41eb cutter: Update to version 1.6                                2 days ago
 * 6ce02e33 radare2: Update to version 2.7.0                             2 days ago
Scoop was updated successfully!
Installing 'shellcheck' (0.5.0) [64bit]
shellcheck-v0.5.0.zip (6.1 MB) [==================================================================================================================] 100%
Checking hash of shellcheck-v0.5.0.zip... ERROR You cannot call a method on a null-valued expression.
ERROR Hash check failed!
App:         shellcheck
URL:         https://shellcheck.storage.googleapis.com/shellcheck-v0.5.0.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    cbfca919a03f058bc9b31b1d932450f63dbdb92dcfec1a30140e022f7db49bc0
Actual:

Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=shellcheck%400.5.0%3a+hash+check+failed`
```

**Comment by r15ch13** [comment]
Does `~\scoop\cache` contain a file called `shellcheck#0.5.0#https_shellcheck.storage.googleapis.com_shellcheck-v0.5.0.zip`?

**Comment by godeater** [comment]
No, that directory is completely empty.

**Comment by godeater** [comment]
I've just installed shellcheck manually, and I'm happy with that.

**Comment by r15ch13** [comment]
Strange. Are you running an Antivirus tool which deletes the file?
Just uploaded it to virustotal and it doesn't show any false positives (https://www.virustotal.com/#/file/cbfca919a03f058bc9b31b1d932450f63dbdb92dcfec1a30140e022f7db49bc0/detection)

**Comment by godeater** [comment]
No, and if I were, I wouldn't be able to install it manually would I? :)

**Comment by r15ch13** [comment]
Can you install other programs without problems using scoop?

**Comment by godeater** [comment]
I've not tried.

I was only using scoop for shellcheck because the shellcheck github page
specifically called it out for windows installs.

Everything else I use chocolatey for.

**Comment by h404bi** [comment]
Let's try this one, perform below command in PowerShell:

``` powershell
cd ~; (new-object net.webclient).downloadfile("https://shellcheck.storage.googleapis.com/shellcheck-v0.5.0.zip", ".\scoop\cache\shellcheck#0.5.0#https_shellcheck.storage.googleapis.com_shellcheck-v0.5.0.zip"); scoop install shellcheck
```

**Comment by godeater** [comment]
Failed again.

The download worked though - I checked the webclient had saved it fine to
~\scoop\cache before calling the 'scoop install shellcheck' again.

**Comment by h404bi** [comment]
So, after the download step, does the file saved to ~\scoop\cache? Or no file named `shellcheck#0.5.0#https_shellcheck.storage.googleapis.com_shellcheck-v0.5.0.zip`.

**Comment by godeater** [comment]
I just had a though, and re-ran this after starting powershell with -noprofile, and that worked.

So *something* weird in my profile is causing it to delete the file after download, but christ knows what. I've got nothing in there that I can think of that would do that.

**Comment by godeater** [comment]
@h404bi - I thought I was clear. The webclient does indeed save that file to my ~/scoop/cache folder.

**Comment by h404bi** [comment]
Ok, so there is something in yout PowerShell profile causing deleting the file. You may check your profile to see what's going on. 🐛

**Comment by godeater** [comment]
Yeah, I think I'm not that bothered to be honest. Just close this and don't worry.
