### ISSUE TITLE
HaskellPlatform 8.4.3 install failed

### ISSUE THREAD

**Issue by xufeng95** [lukesampson/scoop#2396]
> Installing 'haskell' (8.4.3) [64bit]
HaskellPlatform-8.4.3-core-x86_64-setup.exe (266.3 MB) [==========================================================================================================] 100%
Checking hash of HaskellPlatform-8.4.3-core-x86_64-setup.exe... ERROR Hash check failed!
App:       haskell
URL:       https://haskell.org/platform/download/8.4.3/HaskellPlatform-8.4.3-core-x86_64-setup.exe
Expected:  a5eecc051085a535049e18e9ddf7390f16edbdbc2327feada39d62b496f0b79b
Actual:    a8a0eed4c19bed251c46e9d31a1668469275ba592f55261a53da91c306093557

**Comment by r15ch13** [comment]
`a5eecc051085a535049e18e9ddf7390f16edbdbc2327feada39d62b496f0b79b` is the correct checksum. Please it try again.
