### ISSUE TITLE
PowerShell version 3 not enough for normal work

### ISSUE THREAD

**Issue by ustsv** [lukesampson/scoop#2402]
The recommended version of **PowerShell 3 (or later)**. But version 3 has limitations that violate the 'persist' group. For example, `Remove-Item $ dir -Recurse -Force`, sees symlink as a regular folder, and deletes everything recursively, `if ($ null -ne $ file.LinkType)` is always false. 5 version works fine, 4 did not check. Correct the Requirements, please.
Other, some manifests contain references to dependencies, for example in `'post_install': '$ (appdir 'notepadplusplus')`, but if they are global, then the path is incorrect. There should be something like **`$(appdir 'notepadplusplus' $global)`**.

**Comment by kroppt** [comment]
PowerShell 5 is now required, so this is no longer relevant.
https://github.com/lukesampson/scoop/wiki/Quick-Start
