### ISSUE TITLE
scoop update gcc (8.1.0) fails

### ISSUE THREAD

**Issue by iharh** [lukesampson/scoop#2405]
Installing 'gcc' (8.1.0) [64bit]
The remote server returned an error: (404) Not Found.
URL https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v5-rev0.7z is not valid

**Comment by christieb7007** [comment]
I am seeing the same. I think the url needs to be updated to "x86_64-8.1.0-release-posix-seh-rt_v**6**-rev0.7z" from v5
