### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by rampageservices** [lukesampson/scoop#2417]
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd
Actual:      61f5ea570c6b5b171a85ea3263402998887bd46a37a24df02b6989b2e58c2419

**Comment by rasa** [comment]
892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd Is correct
