### ISSUE TITLE
[Request] Add Cocos2d-x

### ISSUE THREAD

**Issue by Shatur95** [lukesampson/scoop#2421]
[Cocos2d-x](https://github.com/cocos2d/cocos2d-x) is a suite of open-source, cross-platform, game-development tools. Cocos2d-x does not have a graphical interface and allows you to create games projects for IDE's on this engine [through console commands](https://github.com/cocos2d/cocos2d-x).

**Comment by h404bi** [comment]
FYI:

```json
{
    "homepage": "http://www.cocos2d-x.org",
    "description": "Cocos2d-x is a suite of open-source, cross-platform, game-development tools used by millions of developers all over the world.",
    "version": "3.17",
    "license": "MIT",
    "url": "http://download.cocos.com/Cocos2D-X/cocos2d-x-3.17.zip",
    "hash": "3cb45f629dda174ab47d083f6818827f58bea194d65c753d60dceed2cbbcedd0",
    "extract_dir": "cocos2d-x-3.17",
    "suggest": {
        "Python2": [
            "versions/python27"
        ]
    },
    "checkver": {
        "url": "http://www.cocos2d-x.org/download",
        "re": ">Download ([\\d.]+)</a>"
    },
    "autoupdate": {
        "url": "http://download.cocos.com/Cocos2D-X/cocos2d-x-$version.zip",
        "extract_dir": "cocos2d-x-$version"
    },
    "notes": "Scoop didn't run setup.py script of cocos2d-x, you have to do it mannually to finish the installation."
}
```

**Comment by Shatur95** [comment]
@h404bi, can you make pull request?

**Comment by h404bi** [comment]
I don't know, just considering this should be in the extras bucket.

**Comment by rasa** [comment]
You’re right, if it’s CLI, it should live in main. Right @r15ch13?

**Comment by Shatur95** [comment]
@h404bi, seems like @r15ch13 confirmed it. I think you should make a pull request.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2421
