### ISSUE TITLE
request to add scrcpy to scoop

### ISSUE THREAD

**Issue by ambhaiji** [lukesampson/scoop#2438]
https://github.com/Genymobile/scrcpy/releases/download/v1.2/scrcpy-win64-v1.2.zip
https://github.com/Genymobile/scrcpy/releases/download/v1.2/scrcpy-win32-v1.2.zip

**Comment by h404bi** [comment]
hmm, looks like it HAS a GUI but startup with command line. Should it been added to extras or main bucket?

**Comment by r15ch13** [comment]
I would add it to the main bucket.

**Comment by ambhaiji** [comment]
The OP adds his own adb.exe which collides with the adb from scoop, person handling this needs to delete adb in that or ask rom1v the most active dev if he can package without adb for scoop and then add adb as a dependency in the shim

**Comment by r15ch13** [comment]
@ambhaiji these issues are already fixed 😁

It depends on scoops `adb` version:
https://github.com/lukesampson/scoop/blob/15622a4181d5115480289e7cad291df4106259f9/bucket/scrcpy.json#L18

and deletes `adb.exe` provided by `scrcpy`
https://github.com/lukesampson/scoop/blob/15622a4181d5115480289e7cad291df4106259f9/bucket/scrcpy.json#L19

**Comment by ambhaiji** [comment]
Wonderful

**Comment by ambhaiji** [comment]
suggestion to change line 19 to
"post_install": "if(Test-Path(\"$dir\\adb.exe\")) { Remove-Item \"$dir\\adb*\" }"

to remove the two dll files in the folder also
