### ISSUE TITLE
gradle@4.9: hash check failed

### ISSUE THREAD

**Issue by metindogancelik** [lukesampson/scoop#2440]
Installing 'gradle' (4.9) [64bit]
gradle-4.9-all.zip (108,2 MB) [===============================>                                                                                               ]  25%
Checking hash of gradle-4.9-all.zip... ERROR Hash check failed!
App:         gradle
URL:         https://services.gradle.org/distributions/gradle-4.9-all.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    39e2d5803bbd5eaf6c8efe07067b0e5a00235e8c71318642b2ed262920b27721
Actual:      c9a1145866d8c1336e550d917b6985db8ebd0bc928958638282032243b379249

**Comment by rasa** [comment]
39e2d5803bbd5eaf6c8efe07067b0e5a00235e8c71318642b2ed262920b27721 Is the correct value, sorry.
