### ISSUE TITLE
[Request] Add VSTS CLI support

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop#2442]
https://docs.microsoft.com/en-us/cli/vsts/install

**Comment by r15ch13** [comment]
Research:
checkver: `https://github.com/Microsoft/vsts-cli`
url: `https://vstscli.blob.core.windows.net/msi/vsts-cli-0.1.1.msi`
extract_dir: `SourceDir\Microsoft SDKs\VSTS\CLI`
bin: `wbin\vsts.bat`
Doesn't depend on python because a suitable version is provided.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2442
