### ISSUE TITLE
[Request] Add support for Ahoy CLI

### ISSUE THREAD

**Issue by tobybellwood** [lukesampson/scoop#2443]
We use Ahoy! for CLI automation (on macs), but the windows build could benefit from some scooping...
https://github.com/ahoy-cli/ahoy/issues/48
https://github.com/ahoy-cli/ahoy/releases/tag/2.0.0

Looks like it shouldn't be too hard to create a json to perform those steps...

Maybe I'll have a crack, but any assistance welcome?

**Comment by r15ch13** [comment]
And done :smile:
Can't run it on my machine. `ahoy -v` or `-h` hangs with 25% cpu usage. Oo

**Comment by enzolutions** [comment]
The install works 

```shell
$ scoop install ahoy
```

But when I try to execute ahoy the application just hang out :'(

![ahoy-halt](https://user-images.githubusercontent.com/907914/44066782-913d4a3e-9fb5-11e8-9c01-437fd3524f83.png)

**Comment by enzolutions** [comment]
@lukesampson could you re-open this issue?

**Comment by r15ch13** [comment]
This issue has to be fixed by ahoy. Calling `ahoy.exe` from `~\scoop\apps\ahoy\2.0.0` doesn't work either.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2443
