### ISSUE TITLE
Flag packages to ignore updates

### ISSUE THREAD

**Issue by brunovieira97** [lukesampson/scoop#2450]
Allow apps to be marked to ignore new versions, unless explicited via `scoop update <app>`. 
Command `scoop update *` would skip apps flagged to ignore updates.

Useful for apps such as **gcc** which might contain custom libraries inside its directories, leading to broken experience under some circumstances.

**Comment by rasa** [comment]
Perhaps to pin/unpin a specific app: `scoop pin app` and `scoop unpin app`.
To pin/unpin all apps: `scoop pin *` and `scoop unpin *`?

**Comment by gdw2** [comment]
This would likely be useful for packages that auto-update themselves, like vscode and chrome.

**Comment by brunovieira97** [comment]
Duplicate of #1941
