### ISSUE TITLE
404 for sourceforge.net URLs when aria2 isn't installed

### ISSUE THREAD

**Issue by nickbudi** [lukesampson/scoop#2474]
When trying to install this [mumble app manifest](https://github.com/nickbudi/scoop-bucket/blob/master/mumble-portable.json) and others like it that use sourceforge, I'm getting a 404 error:

```
Installing 'mumble-portable' (1.2.19_Rev_2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://sourceforge.net/projects/portableapps/files/Mumble%20Portable/MumblePortable_1.2.19_Rev_2.paf.exe/download#/dl.7z is not valid
```

I noticed changes regarding aria2 have been pushed today and after installing aria2 the sourceforge apps that were 404ing installed just fine so the aria2 updates may be related.

**Comment by r15ch13** [comment]
Removing the `/download` part at the end of the URL should work.
Or change the URL to `https://downloads.sourceforge.net/projects/portableapps/Mumble%20Portable/MumblePortable_1.2.19_Rev_2.paf.exe#/dl.7z`
