### ISSUE TITLE
change install directory?

### ISSUE THREAD

**Issue by parisio** [lukesampson/scoop#249]
Hi. Sorry if this explained elsewhere but I couldn't quite find the answer I'm looking for.
Just wondering if I can change the location of pshazz from /scoop/apps and /scoop/shims to something like C:\dev\stuff

If so, what do I have to change (eg. path references)? Do I have to move the whole of scoop (is that even possible with reinstalling)? Do I have to edit the $path variable in /scoop/shims/pshazz.ps1?
I'm a novice, so I'm just throwing out the things I can think of.
I just find the location of scoop in appdata kind of awkward; pshazz gets buried and I end up forgetting about it until I look in my powershell profile.

Any help would be appreciated. Thanks.

**Comment by damnhandy** [comment]
This approach worked for my. Setting the `SCOOP` environment variable to a local path worked as advertised. Scoop is now installing files locally rather on the network drive. We should probably add this to the wiki.

**Comment by deevus** [comment]
No difficulties reported.

**Comment by Zeklandia** [comment]
This no longer seems to work :\

**Comment by lukesampson** [comment]
@Zeklandia that only lasts for the duration of the current PowerShell session.

**Comment by Zeklandia** [comment]
@lukesampson Is that an issue? I was able to use the solution from #427 to install Scoop to a specific folder and it still works out of that folder to this day.

**Comment by lukesampson** [comment]
@Zeklandia If you didn't persist the `SCOOP` environment variable for your user or machine, Scoop itself might be running from a non-default folder, but apps might still be installing under the default folder, `~/scoop`.

Setting `$env:SCOOP = C:\some\path` is not enough, as far as I know. See my first comment above on how to persist the SCOOP variable.

**Comment by Zeklandia** [comment]
@lukesampson Strange, because I don't even have a `~/scoop` and the apps are visible in the path I defined. Although, whenever `scoop` tries to update itself (i.e. `scoop update`) it fails with this error:
```rm : Cannot find path 'C:\Users\Zeklandia\Apps\apps\scoop\current' because it does not exist.
At C:\Users\Zeklandia\Apps\scoop\apps\scoop\current\libexec\scoop-update.ps1:69 char:9
+         rm -r -force $currentdir -ea stop
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Zeklan...s\scoop\current:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand```

`C:\Users\Zeklandia\Apps\scoop` is where I installed it.

**Comment by deepakab03** [comment]
It would be good if this is added to the project wiki, as it's quite often that the default install directory HAS to be changed

**Comment by andreaskundig** [comment]
This is pretty old, but it still works.

**Comment by Pagliacii** [comment]
> You should do this before you install Scoop, so you'll need to run `scoop uninstall scoop` if you've already installed it. If you want to keep what you've already installed, it could get messy but the steps are:
> 
> 1. Copy `~\appdata\local\scoop\` somewhere else
> 2. Run `scoop uninstall scoop`
> 3. Set `$env:SCOOP`
> 4. Re-install scoop with `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`
> 5. Copy your saved scoop folder from step 1 back over the top of the new folder.

For someone who encountered this situation, you can use this command to reset the shims of all installed applications when all steps above have done.

```powershell
@(scoop export).Split() | Where-Object { $_.Trim() -Match "^[^\[\(]" } | ForEach-Object { scoop reset $_ }
```

This command works for me.

**Comment by 2bon** [comment]
[environment]::setEnvironmentVariable('SCOOP','D:\program files\scoop')

**Comment by TWIISTED-STUDIOS** [comment]
i have scoop enviroment set up in the advanced enviroments but then when i try to run 
`iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

i recieve this error, how do i fix this, i cant afford to have scoop on my cdrive its full and i need to move it to another drive. 

`New-Item : Access to the path 'current' is denied.
At line:495 char:9
+         New-Item -Type Directory $SCOOP_APP_DIR | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (E:\Program File...s\scoop\current:String) [New-Item], UnauthorizedAcc
   essException
    + FullyQualifiedErrorId : CreateDirectoryUnauthorizedAccessError,Microsoft.PowerShell.Commands.NewItemCommand`
    
    How do i fix this? windows 10

**Comment by rafaelledo** [comment]
> [environment]::setEnvironmentVariable('SCOOP','D:\program files\scoop') fail@2nd run, u need2change win10 envVar manually

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3#saving-environment-variables-with-setenvironmentvariable

It works with admin privileges and with 3 parameters.

**Comment by Kreijstal** [comment]
> > You should do this before you install Scoop, so you'll need to run `scoop uninstall scoop` if you've already installed it. If you want to keep what you've already installed, it could get messy but the steps are:
> > 
> > 1. Copy `~\appdata\local\scoop\` somewhere else
> > 2. Run `scoop uninstall scoop`
> > 3. Set `$env:SCOOP`
> > 4. Re-install scoop with `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`
> > 5. Copy your saved scoop folder from step 1 back over the top of the new folder.
> 
> For someone who encountered this situation, you can use this command to reset the shims of all installed applications when all steps above have done.
> 
> ```powershell
> @(scoop export).Split() | Where-Object { $_.Trim() -Match "^[^\[\(]" } | ForEach-Object { scoop reset $_ }
> ```
> 
> This command works for me.

instead of this workaround why there is not "scoop move" or something like it?

**Comment by nitincodery** [comment]
Can't I have symlink to already installed scoop setup to somewhere, instead of uninstalling scoop and doing scoop reset on everything? Making a symbolic link would be better and easier on existing scoop setup? No?

**Comment by nitincodery** [comment]
> Can't I have symlink to already installed scoop setup to somewhere, instead of uninstalling scoop and doing scoop reset on everything? Making a symbolic link would be better and easier on existing scoop setup? No?

I tried moving my 30 GB scoop directory to another location, it doesn't copies `junction` on current directories in apps, how to move the folder correctly? does using `scoop reset *` is what solves that? will it work with if I symlinked the whole scoop directory?

**Comment by nitincodery** [comment]
> > Can't I have symlink to already installed scoop setup to somewhere, instead of uninstalling scoop and doing scoop reset on everything? Making a symbolic link would be better and easier on existing scoop setup? No?
> 
> I tried moving my 30 GB scoop directory to another location, it doesn't copies `junction` on current directories in apps, how to move the folder correctly? does using `scoop reset *` is what solves that? will it work with if I symlinked the whole scoop directory?

It worked, steps:

1. Copied `scoop` directory to another location.
2. Restart System in Safe Mode
3. Rename original `scoop` directory to `scoop_old`
4. Made symlink: `mklink /D C:\Users\[Username]\scoop D:\scoop`
5. Run: `scoop reset *`
6. Restart System

Voila!

**Comment by nitincodery** [comment]
> > > Can't I have symlink to already installed scoop setup to somewhere, instead of uninstalling scoop and doing scoop reset on everything? Making a symbolic link would be better and easier on existing scoop setup? No?
> > 
> > 
> > I tried moving my 30 GB scoop directory to another location, it doesn't copies `junction` on current directories in apps, how to move the folder correctly? does using `scoop reset *` is what solves that? will it work with if I symlinked the whole scoop directory?
> 
> It worked, steps:
> 
> 1. Copied `scoop` directory to another location.
> 2. Restart System in Safe Mode
> 3. Rename original `scoop` directory to `scoop_old`
> 4. Made symlink: `mklink /D C:\Users\[Username]\scoop D:\scoop`
> 5. Run: `scoop reset *`
> 6. Restart System
> 
> Voila!

Can be done same for scoop global apps at `C:\ProgramData\scoop` :)
