### ISSUE TITLE
[aria2c] checkver.ps1 does not use aria2c

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2495]
1. [ ] `checkver.ps1` does not support downloading using aria2c

```powershell
###### Normal installation without aria2c
ScoopAsh258 master * = $ scoop install .\TODO\Nox.json
Installing 'Nox' (6.2.1.1) [64bit]
The remote server returned an error: (302) Moved Temporarily.
URL https://www.bignox.com/en/download/fullPackage#/cosi.exe is not valid

# Downloading with aria2 enabled
ScoopAsh258 master * = $ scoop config aria2-enabled true
ScoopAsh258 master * = $ scoop install .\TODO\Nox.json
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'Nox' (6.2.1.1) [64bit]
Starting download with aria2 ...
Download: [#7975c0 0.9MiB/306MiB(0%) CN:5 DL:2.4MiB ETA:2m4s]
Download: [#7975c0 3.2MiB/306MiB(1%) CN:5 DL:2.4MiB ETA:2m6s]
Download: [#7975c0 6.0MiB/306MiB(1%) CN:5 DL:2.5MiB ETA:1m57s]
Download: [#7975c0 8.6MiB/306MiB(2%) CN:5 DL:2.6MiB ETA:1m54s]
Download: [#7975c0 11MiB/306MiB(3%) CN:5 DL:2.6MiB ETA:1m52s]
Download: [#7975c0 13MiB/306MiB(4%) CN:5 DL:2.6MiB ETA:1m51s]
```

~~1. [ ] Scoop basic downloading does not respect redirects~~
[Example manifest](https://github.com/Ash258/scoop-Ash258/blob/master/TODO/Nox.json) **Still in development

When you want to update manifest (`-u` || `-f`) scoop will failed because downloading does not support redirection.

No aria2c download even it's set to true
```powershell
###### Checking for updates
ScoopAsh258 master * = $ .\bin\checkver.ps1 Nox TODO -f # I tweaked that binary little bit
Nox: 6.2.1.1 (scoop version is 6.2.1.1)
Forcing autoupdate!
Autoupdating Nox
Downloading fullPackage to compute hashes!
The remote server returned an error: (302) Moved Temporarily.
URL https://www.bignox.com/en/download/fullPackage#/cosi.exe is not valid
Could not find hash!
ERROR Could not update Nox
```

Curl is working as expected if you pass `-L` argument (`curl https://www.bignox.com/en/download/fullPackage -o foo.exe -L`)

**Comment by r15ch13** [comment]
Does it redirect from https to http? Normally redirects work just fine, but PowerShell doesn't like redirecting to an unsecure connection.

**Comment by Ash258** [comment]
It's from https to http (<https://www.bignox.com/en/download/fullPackage> => <http://res06.bignox.com/full/20180721/fc48166fcf3b4e99a872de2b7926d33a.exe?filename=nox_setup_v6.2.1.1_full_intl.exe>)

**Comment by r15ch13** [comment]
It redirects to `https://res06.bignox...` on my machine. 😕
I didn't want to break the auto-update service, so `checkver.ps1` doesn't support aria2. It still has some flaws. 😁

**Comment by Ash258** [comment]
That redirection is now into HTTPS. Maybe some temporary issue 🤔
