### ISSUE TITLE
curl@7.61.0: hash check failed

### ISSUE THREAD

**Issue by psychsane** [lukesampson/scoop#2501]
> scoop install curl
Installing '7zip' (18.05) [64bit]
7z1805-x64.msi (1.7 MB) [=====================================================================================] 100%
Checking hash of 7z1805-x64.msi ... ok.
Extracting 7z1805-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.05
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (18.05) was installed successfully!
Installing 'curl' (7.61.0) [64bit]
curl-7.61.0-win64-mingw.tar.xz (1.4 KB) [=====================================================================] 100%
Checking hash of curl-7.61.0-win64-mingw.tar.xz ... ERROR Hash check failed!
App:         curl
URL:         https://dl.bintray.com/vszakats/generic/curl-7.61.0-win64-mingw.tar.xz
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    623a06a6815ce17743d457c2168d9ea91900459674e68196b484e8e9079660c4
Actual:      0ca36ecf2ef4909250803b39c943b6c71406924f45c5551f5f518274df071be8

Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=curl%407.61.0%3a+hash+check+failed

**Comment by r15ch13** [comment]
` 623a06a6815ce17743d457c2168d9ea91900459674e68196b484e8e9079660c4` is correct. Please try again.
