### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by zhouguozhao** [lukesampson/scoop#2503]
PS C:\Users\guozhao> scoop install openssh
ERROR It looks like a previous installation of openssh failed.
Run 'scoop uninstall openssh' before retrying the install.
WARN  'openssh' (7.6p1) is already installed.
Use 'scoop update openssh' to install a new version.
PS C:\Users\guozhao> scoop uninstall openssh
Uninstalling 'openssh' (7.6p1).
'openssh' was uninstalled.
PS C:\Users\guozhao> scoop install openssh
Updating Scoop...
Scoop was updated successfully!
Installing 'openssh' (7.6p1) [64bit]
gcc-libs-6.4.0-1-x86_64.pkg.tar.xz (821.9 KB) [====================================>                          ]  58%
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd
Actual:      4ec21c84adae9babf661f49ec162f2fb7243b9a65d4cb300523da8afebcd796a

Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by zhouguozhao** [comment]
ty

**Comment by r15ch13** [comment]
Related to https://github.com/lukesampson/scoop/issues/2414
Please try again. msys2.org has some issues providing the files.
