### ISSUE TITLE
rsync free version is no more

### ISSUE THREAD

**Issue by ambhaiji** [lukesampson/scoop#2506]
Installing 'rsync' (5.7.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://www.itefix.net/dl/cwrsync_5.7.2_x86_free.zip is not valid

i went to their website to look around there is no indication anywhere of a free version anymore, so this needs to be removed or a different mirror of sorts needs to be found if any

**Comment by kenorb** [comment]
Duplicate of #2295
