### ISSUE TITLE
**TYPO** in monero installation

### ISSUE THREAD

**Issue by ambhaiji** [lukesampson/scoop#2507]
Installing 'monero' (0.12.3.0) [64bit]
Loading monero-gui-win-x64-v0.12.3.0.zip from cache
Checking hash of monero-gui-win-x64-v0.12.3.0.zip ... ok.
Extracting monero-gui-win-x64-v0.12.3.0.zip ... done.
Linking ~\scoop\apps\monero\current => ~\scoop\apps\monero\0.12.3.0
Creating shim for 'monerod'.
Creating shim for 'monero-wallet-rpc'.
Creating shim for 'monero-wallet-gui'.
Creating shim for 'monero-wallet-cli'.
Creating shim for 'monero-gen-trusted-multisig'.
Creating shim for 'monero-blockchain-usuage'.
Can't shim 'monero-blockchain-usuage.exe': File doesn't exist.

**Comment by r15ch13** [comment]
Fixed https://github.com/lukesampson/scoop-extras/commit/f3f44af1051dd0c0adf7a0b399c04b3d45277e8b
