### ISSUE TITLE
Package request: LuaJIT

### ISSUE THREAD

**Issue by LER0ever** [lukesampson/scoop#2508]
Is it possible to add luajit to scoop main bucket? There are binaries out there (like from luapower.com etc.)

**Comment by r15ch13** [comment]
Should it download the whole repo? https://github.com/luapower/luapower-all/archive/2018-08-16.zip
Or is the `luajit.exe` enough? https://github.com/luapower/luajit

**Comment by LER0ever** [comment]
@r15ch13 I believe only the luajit Windows 32/64 binaries are necessary. Luapower is a distribution containing luajit binaries and other supporting libraries, and we only need their luajit binaries for the ease of packaging. But single `luajit.exe` is not enough. See [http://luajit.org/install.html](http://luajit.org/install.html)

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2508
