### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by ynzheng** [lukesampson/scoop#2513]
λ scoop install -g openssh
Installing 'openssh' (7.6p1) [64bit]
gcc-libs-6.4.0-1-x86_64.pkg.tar.xz (821.9 KB) 

Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd
Actual:      7775c1b464fbc99248d1449ba37e884ad1a59b689b60d53c47d71c03bbceb4a0

Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by r15ch13** [comment]
Related to https://github.com/lukesampson/scoop/issues/2414
Please try again. msys2.org has some issues providing the files.
