### ISSUE TITLE
go@1.11: hash check failed

### ISSUE THREAD

**Issue by BrendanBurkhart** [lukesampson/scoop#2533]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'go' (1.11) [64bit]
Loading go1.11.windows-amd64.zip from cache.
Checking hash of go1.11.windows-amd64.zip ... ERROR Hash check failed!
App:         go
URL:         https://storage.googleapis.com/golang/go1.11.windows-amd64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    29f9291270f0b303d0b270f993972ead215b1bad3cc674a0b8a09699d978aeb4
Actual:      0ca155b3554a58511c96529d368817adaf5ffa1a84a719f7ca4a16e77b627866

**Comment by r15ch13** [comment]
`29f9291270f0b303d0b270f993972ead215b1bad3cc674a0b8a09699d978aeb4` is correct.
Please try again.

**Comment by BrendanBurkhart** [comment]
All good, it works now.
