### ISSUE TITLE
Pshazz and concfg uninstall should also clean the user's $profile

### ISSUE THREAD

**Issue by sgarfinkel** [lukesampson/scoop#2536]
I don't have time right now to fix this, but this is more a note for a future enhancement.

I know at least these two programs will append some program-specific code to the user's $profile. They do properly verify that the user has these programs installed before running any program-specific code, but this still breaks with the scoop convention of complete uninstalls (and side-effect-free installs).

This could probably be amended to a more general question: Should scoop scripts also remove dotfiles or any other configuration files that the user specifies? It doesn't seem like there's a well-defined best practice either way.

Other than manually cleaning the lines, a patch system for dotfiles would also work. I'm not a PS guru at all, so I'm not sure about feasibility. I know there are patch implementations, but I haven't seen anything that's pure PS.

For reference, the offending lines:
```powershell
try { $null = gcm pshazz -ea stop; pshazz init 'default' } catch { }
try { $null = Get-Command concfg -ea stop; concfg tokencolor -n enable } catch { }
```

**Comment by rasa** [comment]
Offtopic. If this change is still desired and viable, please create issue at https://github.com/lukesampson/pshazz/issues/new
