### ISSUE TITLE
win32-openssh@7.7.2.0p1-Beta + pshazz@0.2018.04.22: = Ignoring Agent + System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by TCB13** [lukesampson/scoop#2537]
Hello,

I'm trying to setup `win32-openssh` and `pshazz` so I can store the passwords of my SSH keys into WindowsCredential Manager. My setup was:

```
scoop install sudo
sudo scoop install 7zip git win32-openssh pshazz
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which ssh)), 'USER')
```

At this point the ssh-agent didn't work:

```
ssh-add.exe
Error connecting to agent: No such file or directory
```

I believe this should be a service in my system, however:

```
Get-Service ssh-agent
Get-Service : Cannot find any service with service name 'ssh-agent'.
```

I also tried to run `install-sshd.ps1`, because, well, why not?:

```
cd "C:\Users\TCB13\scoop\apps\win32-openssh\current\"
 sudo .\install-sshd.ps1
**** Warning: Publisher OpenSSH resources could not be found or are not accessible
to the EventLog service account (NT SERVICE\EventLog).

[SC] SetServiceObjectSecurity SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
sshd and ssh-agent services successfully installed
C:\Users\TCB13\scoop\apps\win32-openssh\current
λ  .\ssh-add.exe
Error connecting to agent: No such file or directory
```

Sill the same issue, so I read somewhere I cloud try `sudo pshazz init`, so I did it, "no such file" errors disappeared, however when trying to ssh to a machine:

```
 ssh pdnl478

Excepção não processada: System.IndexOutOfRangeException: Índice fora dos limites da matriz.
   em askpass.Program.Main(String[] args)
```

Looks like SSH Agent is now a service:

```
λ  Get-Service ssh-agent
Status   Name               DisplayName
Stopped  ssh-agent          OpenSSH Authentication Agent
```

However, I still get the `System.IndexOutOfRangeException` error :(

Why? What's wrong here?

Thank you.

**Comment by TCB13** [comment]
I also unable to use the ssh agent + ssh client without pshazz as I described in https://github.com/PowerShell/Win32-OpenSSH/issues/1133#issuecomment-416504407 and https://github.com/PowerShell/Win32-OpenSSH/issues/1133#issuecomment-416900431. I'm able to add keys to the agent, manually or by using `AddKeysToAgent yes` however, the client always asks for the password.

**Bottom line**: everything is messed up. I tried a fresh VM of Windows 10 Pro and I get the exact same issues.

**Comment by h404bi** [comment]
Please try the steps:

I assume that you're using Windows 10 build 1803 (or above), which has a built-in `OpenSSH` located in `C:\Windows\System32\OpenSSH`.

Leave the `phsazz` installed, if you're not sure, reinstall it first, and make sure its `ssh` plugin is enabled default.

Uninstall apps releated to OpenSSH:
```sh
scoop uninstall win32-openssh // There is a built-in one on Windows 10 build 1803, no need to install it again!
scoop uninstall git-with-openssh // Openssh bundled with git will be ignore because of the built-in one on Windows 10, replace it with git (without openssh)
```

So now you would use the built-in OpenSSH in your machine:
```sh
$ which ssh-add
// C:\WINDOWS\System32\OpenSSH\ssh-add.exe
$ which ssh-agent
// C:\WINDOWS\System32\OpenSSH\ssh-agent.exe
```

You may see an error message similar to `unable to start ssh-agent service, error :1058` When you open a new PowerShell console window.

Now use Win+R, type `services.msc` to open Services Manager, find the service name `OpenSSH Authentication Agent`, change its startup type from disabled to Automatic. (Read the reason here: https://github.com/lukesampson/pshazz/issues/70#issuecomment-395138084)

Close the console window, and open a new one. The above error message would gone, and now the ssh-agent has started up.
```powershell
$ Get-Service ssh-agent
Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          OpenSSH Authentication Agent
```

Execute `ssh git-server` to see if it works.

**Comment by TCB13** [comment]
@h404bi as I said on the first post. **I'm not using Windows built-in OpenSSH**, not installed, never was. I even tried the setup on a fresh VM.

And I don't want to use Windows' OpenSSH because it isn't compatible with some key formats.

**Comment by h404bi** [comment]
Actually, It will always load the built-in OpenSSH first if you're using Windows 10 1803, even if you install another one, unless you delete the built-in OpenSSH (or remove it from system-wide PATH). More actually, `win32-openssh` is the same as the built-in one (they are the same project - [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH), just different version).

**Comment by vertexportus** [comment]
this is still an issue, is there still no solution?

![image](https://user-images.githubusercontent.com/1386617/50565589-7d5a7580-0d17-11e9-828c-0bf6db972184.png)

**Comment by TCB13** [comment]
@vertexportus looks like nobody cares. I'm using the ssh-agent to store my keys. Doesn't crash, works almost a reliable as on linux.

**Comment by vertexportus** [comment]
@TCB13 yeah, getting the feeling that's the case...

**Comment by h404bi** [comment]
The latest pshazz has removed askpass and well support win32-openssh.

**Comment by rasa** [comment]
Offtopic. If this change is still desired and viable, please create issue at https://github.com/lukesampson/pshazz/issues/new
