### ISSUE TITLE
404 on PHP package

### ISSUE THREAD

**Issue by luiscoms** [lukesampson/scoop#254]
I am trying to install php and get 404 error
```shell
$ scoop install php
installing php (5.5.15)
downloading http://windows.php.net/downloads/releases/php-5.5.15-Win32-VC11-x86.zip...The remote server returns an error: (404) Not found.
```

**Comment by ntwb** [comment]
You need to run `scoop update` to update to latest version that includes updated PHP manifests, also to note `scoop install php` will now install PHP 5.6.x, if you explicitly want PHP 5.5.x (5.5.20 is the latest) you should use `scoop install php55`, there is also PHP53 and PHP54 versions if you're after those.

**Comment by luiscoms** [comment]
Nice, that works!

**Comment by luiscoms** [comment]
Once again, 404 error. 
Scoop is updated, but the error still occurs.

```bash
> scoop update
downloading...
extracting...
replacing files...
scoop was updated successfully!
> scoop status
scoop was last updated 3 seconds ago
everything is ok!
> scoop install php
installing php (5.6.4)
downloading http://windows.php.net/downloads/releases/php-5.6.4-Win32-VC11-x86.zip...The remote server returns an error: (404) Not found.
```

**Comment by cava** [comment]
same as above

**Comment by luiscoms** [comment]
I just updated the PHP bucket, if I am right,  this pull request #273 could be accepted

**Comment by lukesampson** [comment]
I've accepted #273 now.

**Comment by luiscoms** [comment]
Your are welcome!

**Comment by crumdidlyumshis** [comment]
PS C:\Users\Administrator> scoop status
scoop is up-to-date.
everything is ok!
PS C:\Users\Administrator> scoop install php
installing php (7.0.7)
downloading http://windows.php.net/downloads/releases/php-7.0.7-Win32-VC14-x64.zip...The remote server returned an error
: (404) Not Found.
PS C:\Users\Administrator>
