### ISSUE TITLE
groovy@2.5.2: hash check failed

### ISSUE THREAD

**Issue by medved-nsk** [lukesampson/scoop#2545]
Installing 'groovy' (2.5.2) [64bit]
apache-groovy-binary-2.5.2.zip (28.2 MB) [==================================================================> ]  98%
Checking hash of apache-groovy-binary-2.5.2.zip ... ERROR Hash check failed!
App:         groovy
URL:         https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.5.2.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    495f96f1be35ef838abb5f1c10fc6f642460cacd94c7095eb3a9f1fbf62b282e
Actual:      e1f2951e7d3f0be9cbde325e40000fb487ea4283d19b11696c07776cad8762dd

**Comment by r15ch13** [comment]
`495f96f1be35ef838abb5f1c10fc6f642460cacd94c7095eb3a9f1fbf62b282e` is correct. Please try again.

**Comment by Ash258** [comment]
From that download screen you can see that file wasn't fully downloaded (98%) Something interupted downloading, which resulted into corrupted file (different hash)

**Comment by medved-nsk** [comment]
Indeed, I tried a couple times but didn't notice that error. Sorry.
Yes, it works fine now. Thanks.
