### ISSUE TITLE
Warning when updating scoop

### ISSUE THREAD

**Issue by BjoernPetersen** [lukesampson/scoop#2565]
Every time I run `scoop update` I get the following warning at the `Updating Scoop...` step:
```
WARN  Overwriting shim to scoop.ps1 installed from
```

Is that intended behavior or is there something wrong with my installation?

**Comment by r15ch13** [comment]
We are on it: https://github.com/lukesampson/scoop/pull/2564

**Comment by BjoernPetersen** [comment]
Ah, that's nice. I only looked for the problem in the issues.
