### ISSUE TITLE
Error when updating scoop (java bucket)

### ISSUE THREAD

**Issue by DesigningKnights** [lukesampson/scoop#2566]
I get the following message when I try to update

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by Ash258** [comment]
Java bucket? I am experiencing same.

**Comment by se35710** [comment]
Yes, I made a mistake a couple of days back, messing up the git history. I thought I fixed it though, but it seems like I did not.

Removing and adding the java bucket should fix it, eg:
```
PS C:> scoop bucket rm java
PS C:> scoop bucket add java
```
I will probably replace the master branch with a new one in a couple of days, when that happens redo the above once more. I will takes steps after that to make sure it won't happen again.

I am very sorry for the inconvenience.

**Comment by Ash258** [comment]
Could be closed.
