### ISSUE TITLE
Register app with associated filetypes

### ISSUE THREAD

**Issue by jas99** [lukesampson/scoop#2567]
Hey @lukesampson 

I installed vlc from extras bucket. The app doesn't get automatically registered with associated extensions i.e double clicking on video won't open the media player.

I recommend that manifest of vlc should have field for associated file types. And maybe when one runs scoop link it should register and override all the associated file types and make vlc as primary for instance.

Along with associated file types field, maybe shortcut for desktop or startup menu; maybe desirable. But file association is critical as is screws up after install experience.

Jaspreet
Thx

**Comment by Calinou** [comment]
> Along with associated file types field, maybe shortcut for desktop or startup menu; maybe desirable. But file association is critical as is screws up after install experience.

Creating Start Menu shortcuts is already supported (see the `shortcuts` property in manifest files). However, due to a bug (https://github.com/lukesampson/scoop/issues/2124), these aren't displayed in search results; they will only be visible if you manually navigate to the Scoop Apps folder in the Start Menu.

**Comment by r15ch13** [comment]
@Calinou is still valid? All programs I installed with scoop show up in the search results. They even get listed as "Recently added".

@jas99 What do you mean by "as is screws up after install experience"?
Messing with associated files is a bit much for scoop I guess. This should be handled by the user him/herself. Also, VLC has this feature in the settings menu.

**Comment by jas99** [comment]
@r15ch13 Well you can prompt user during installations for yes/no to associate if available in manifest. Or maybe manual `scoop link vlc` would associate filetypes.

Its been lil while I ran my windows machine but vlc file association didn't worked for me. So I manually linked it with `open with option`. I selected shim and now along with vlc I get blank cmdline window; generated by shim.

**Comment by r15ch13** [comment]
Use `open with` to select the `vlc.exe` from `~\scoop\apps\vlc\current`.
Try running VLC with admin privileges and then use the settings menu to associate the filetypes. This is required in most cases (MPC-HC, 7zip)

**Comment by jas99** [comment]
@r15ch13 Hey thx for mentioning that; will chk it out and let you know. 

But maybe these additional steps should also be in application manifest as non-default steps that requires admin elevation and run with special subcommand.

**Comment by jas99** [comment]
@r15ch13 Thx things work out.

**Comment by nitrocode** [comment]
@r15ch13 @jas99 I don't think this issue should be closed. If we could define file associations directly from the json manifest instead of manual steps would be a much more polished installation.

Something like the shortcuts key where you can give it a binary and a human readable name

    "associate": {
      ".txt": [
        "notepad.exe",
      ],
      ".yml": [
        "notepad.exe",
      ]
    }

or

    "associate": {
      "notepad.exe": [
        ".txt",
        ".yml",
        ".yaml"
      ]
    }

The above addition should help prevent the scoop-extras bucket from having to run [external reg and powershell scripts for file associations](https://github.com/lukesampson/scoop-extras/tree/master/scripts) (also see https://github.com/lukesampson/scoop-extras/pull/1566)

**Comment by TheRandomLabs** [comment]
A bit late, but I also agree with nitrocode's suggestion. I would also add an option to set the [default icon](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-assign-a-custom-icon-to-a-file-type).

**Comment by Adnn** [comment]
Hi,

  I see this issue is closed, but as far as I can tell scoop is not automatically associating files after installation (for example, 7-zip). Since the issue dates a few years back now, has anything been set in place? (be it automatic, or manual steps)

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Main/blob/master/bucket/7zip.json#L6

**Comment by alecdvor** [comment]
Is there a solution for setting associations through scoop or another terminal command after the scoop install. I'd like to associate file types to multiple programs after a a few installs on a fresh system =.

**Comment by nitrocode** [comment]
@alecdvor  I don't think there is a way to do this natively in scoop. It seems like the maintainers of the json manifests have opted to adding custom `.reg` files per manifest and a `notes` key in each manifest to manually run the association.

For now, you have a couple options after a scoop install of the app you want a file extension associated with.

1. run 2 local windows commands per file assoc https://stackoverflow.com/a/48281280/2965993
1. run SFTA cli per file assoc https://github.com/DanysysTeam/SFTA (not in scoop yet)
1. run another cli tool that is available in scoop
1. use the same reg method in the 7zip manifest for another app, contribute the .reg ( to do the file assoc ) to the bucket repo in a PR

**Comment by alecdvor** [comment]
> @alecdvor I don't think there is a way to do this natively in scoop. It seems like the maintainers of the json manifests have opted to adding custom `.reg` files per manifest and a `notes` key in each manifest to manually run the association.
> 
> For now, you have a couple options after a scoop install of the app you want a file extension associated with.
> 
> 1. run 2 local windows commands per file assoc https://stackoverflow.com/a/48281280/2965993
> 2. run SFTA cli per file assoc https://github.com/DanysysTeam/SFTA (not in scoop yet)
> 3. run another cli tool that is available in scoop
> 4. modify manifest - use the post-install method to run the local file assoc commands
> 5. modify manifest - use the same reg method in the 7zip manifest for another app, contribute the .reg ( to do the file assoc ) to the bucket repo in a PR
> 6. If others feel strongly that scoop should have a native way to do file associations, then proposing a PR would probably be the best way forward as that would be helpful across many manifests.
> 
> The last option would be my favorite. I wish I had the time and skills to contribute. 😄

Option 1 will work well for my use ! thank you for the help ! the others are very interesting as well

**Comment by mid-kid** [comment]
Scoop having a native way to do file associations would be a killer feature. There's many applications in the repository that are made to open and edit various file formats, and are lacking registry files to associate them. Things like gimp, inkscape, kdenlive, and more, become less useful when no file associations are provided.

**Comment by JaneX8** [comment]
I really miss this feature too.
