### ISSUE TITLE
Scoop installed apps not executable from command line

### ISSUE THREAD

**Issue by moracabanas** [lukesampson/scoop#2569]
I can list all apps installed by scoop but there is no scoop apps path on windows environment path so I have to add each of them manually to execute them from CMD

**Comment by Ash258** [comment]
> Doesn't pollute your path. Where possible, Scoop puts your program shims in a single directory and just adds that to your path.

If the manifest have bin property, they are added into `$env:SCOOP\shims`, which is added into path. So no redundant populating path (see: [Properties](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison)). What exactly apps have you tried??

**Comment by moracabanas** [comment]
I have these apps installed: 

-  7zip 18.05
-  git 2.18.0.windows.1
- nvm 1.1.6
-  openssh 7.6p1
-  perl 5.28.0.1
-  yarn 1.9.2

For example if I install **perl** by scoop, I cannot use it unless I find its **bin** folder at **C:\Users\myuser\scoop\apps\perl\5.28.0.1\perl\bin** and add it to the _Path_. (I restart cmd windows before the try)

**Comment by Ash258** [comment]
Perl have it's path set (all bins) https://github.com/lukesampson/scoop/blob/59c2bd538f4ea166a8099db5beeb731d54ffef07/bucket/perl.json#L23

Try `scoop reset perl`

**Comment by moracabanas** [comment]
Done. But no perl.exe on C:\Users\morac\scoop\shims so it doesn't seems to work

**Comment by r15ch13** [comment]
Like @Ash258 mentioned, perl gets added to `PATH`, just restart your console and it should be available.

**Comment by moracabanas** [comment]
You are right. For some reason it wasn't added the first time I installed before I done scoop reset perl.

Thanks you so much
