### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by andrewmiller1** [lukesampson/scoop#2580]
Latest `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`-installed version of scoop.

Prevents scoop from working on Windows 7

See https://github.com/PowerShell/PowerShell/issues/6561#issuecomment-408618729 for a workaround.

<details><summary>Command line details</summary>

```text
PowerShell 6.1.0-rc.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\andrew> scoop install 7zip
Installing '7zip' (18.05) [64bit]
Loading 7z1805-x64.msi from cache
Checking hash of 7z1805-x64.msi ... ok.
Extracting 7z1805-x64.msi ... System.DllNotFoundException: Unable to load DLL 'a
pi-ms-win-core-job-l2-1-0.dll' or one of its dependencies: The specified module
could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.PowerShell.Commands.NativeMethods.CreateJobObject(IntPtr lpJobAt
tributes, String lpName)
   at Microsoft.PowerShell.Commands.ProcessCollection..ctor()
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
Failed to extract files from C:\Users\andrew\scoop\apps\7zip\18.05\7z1805-x64.ms
i.
Log file:
  ~\scoop\apps\7zip\18.05\msi.log
PS C:\Users\andrew>
```

</details><br>

Edit: forgot to include tests

All tests pass [TestResults.xml.txt](https://github.com/lukesampson/scoop/files/2367772/TestResults.xml.txt)

**Comment by leonyu** [comment]
It looks like a missing VC++ Redistributable issue.

Can you provide the `msi.log`  listed in the output?

**Comment by h404bi** [comment]
@leonyu I guess no, this issue occurred to me when I'm installing miniconda3 using `pwsh`(a.k.a PowerShell Core) v6.0.4, and everything works fine if I did it using `powershell` (a.k.a Windows PowerShell) v5.1. The same machine, VC++ Redistributable installed. This maybe an issue caused by PowerShell Core 6.

**Comment by andrewmiller1** [comment]
@leonyu How do I grab that?

**Comment by leonyu** [comment]
Might take a few days before I get a chance to look into this. I will need to spin up a VM, as I am not able to  reproduce this in Windows 10.

**Comment by hpsbranco** [comment]
It's a bug with Start-Process -Wait, exclusive to PowerShell Core running on Windows 7 (PowerShell/PowerShell#6561).

PR #3415 provides a workaround.
