### ISSUE TITLE
is there a way to let pshazz dont change my powershell prompt

### ISSUE THREAD

**Issue by copdips** [lukesampson/scoop#2595]
pshazz is great, but it does much more things than what we need it to do.
is there a switch or a param to ask it not change my powershell prompt ?

**Comment by copdips** [comment]
@h404bi 

thx, but it doesnt work, I load my custom prompt from the powershell profile file.

`$PROFILE | % CurrentUserAllHosts`

with `pshazz use microsoft`, it only restores the default powershell prompt, not my personal one. 

I can reload my custom prompt manually after pshazz has made it's prompt, but it's not cool. I need to have my custom prompt ready from the beginning and automatically.

**Comment by h404bi** [comment]
prompt is a main feature of pshazz.

Below line of code in your `$PROFILE` is the initialization entry of psahzz.
**profile.ps1**
```powershell
try { $null = Get-Command pshazz -ea stop; pshazz init } catch { }
```

Place your custom prompt code after this line of code, I think it should automatically load your prompt after psahzz initialization, when you start up a new Windows Console.

------------------

Another simple way to disable changes is delete this line of code, but the entire pshazz functionality will be removed.

If you really want to keep pshazz without prompt, try to create a customized theme of pshazz, don't add the prompt part. And place it into `$env:USERPROFILE\pshazz\`, then active it.

**default.json**
``` json
{
	"plugins": [ "git", "hg", "ssh", "z", "aliases" ],
	"prompt": [
		[ "cyan",  "", "$dir" ],
		[ "red",   "", " $git_branch" ],
		[ "red",   "", " $git_local_state" ],
		[ "red",   "", " $git_remote_state" ],
		[ "red",   "", " $hg_branch" ],
		[ "",      "", "$hg_bookmark" ],
		[ "red",   "", "$hg_dirty" ],
		[ "green", "", " `$" ]
	],
	"git": {
		"prompt_unstaged": "*",
		"prompt_staged": "+",
		"prompt_stash": "$",
		"prompt_untracked": "%",
		"prompt_remote_push": ">",
		"prompt_remote_pull": "<",
		"prompt_remote_same": "="
	},
	"hg": {
		"prompt_dirty": "*"
	}
}
```

**no-prompt.json**
```json
{
	"plugins": [ "git", "hg", "ssh", "z", "aliases" ],
	"git": {
		"prompt_unstaged": "*",
		"prompt_staged": "+",
		"prompt_stash": "$",
		"prompt_untracked": "%",
		"prompt_remote_push": ">",
		"prompt_remote_pull": "<",
		"prompt_remote_same": "="
	},
	"hg": {
		"prompt_dirty": "*"
	}
}
```

E.g. `$env:USERPROFILE\pshazz\no-prompt.json`, then:
```powershell
pshazz use no-prompt
```

This will not change the prompt but leave other functionality, but you should know that git-prompt and hg-prompt won't work.

**Comment by rasa** [comment]
Offtopic. If this change is still desired and viable, please create issue at https://github.com/lukesampson/pshazz/issues/new
