### ISSUE TITLE
Autocomplete when using command `uninstall`

### ISSUE THREAD

**Issue by XieEDeHeiShou** [lukesampson/scoop#2597]
Can it autocomplete words when using uninstall command?

Something like clicking <kbd>Tab</kbd> to select a file or folder in cmd.

See #1439

**Comment by liuzijing97** [comment]
Tab completion can't work with cmd. I try to implement it in Powershell nowdays. A zsh tab completion is available now(all sub-commands are supported).

**Comment by Elvyria** [comment]
You can check out my completion [script](https://github.com/Elvyria/scoop-clink-completion) for clink wich is by the way distributed with cmder if you use one.

**Comment by liuzijing97** [comment]
My works:
https://github.com/liuzijing97/scoop-auto-completion
all commands (alias included) are supported
