### ISSUE TITLE
Don't know what's this means.

### ISSUE THREAD

**Issue by lygstate** [lukesampson/scoop#260]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\lygstate>@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')"
initializing...
Invoke-Expression : Bad numeric constant: 7.
At line:10 char:4
+ iex <<<<  (new-object net.webclient).downloadstring($core_url)
    + CategoryInfo          : ParserError: (7:String) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : BadNumericConstant,Microsoft.PowerShell.Commands.InvokeExpressionCommand

C:\Users\lygstate> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).downloadstring('https://get.scoop.sh'))"
initializing...
Invoke-Expression : Bad numeric constant: 7.
At line:10 char:4
+ iex <<<<  (new-object net.webclient).downloadstring($core_url)
    + CategoryInfo          : ParserError: (7:String) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : BadNumericConstant,Microsoft.PowerShell.Commands.InvokeExpressionCommand

C:\Users\lygstate> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).downloadstring('https://get.scoop.sh'))"
initializing...
Invoke-Expression : Bad numeric constant: 7.
At line:10 char:4
+ iex <<<<  (new-object net.webclient).downloadstring($core_url)
    + CategoryInfo          : ParserError: (7:String) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : BadNumericConstant,Microsoft.PowerShell.Commands.InvokeExpressionCommand

C:\Users\lygstate>

**Comment by lukesampson** [comment]
Try running `(new-object net.webclient).downloadstring('https://get.scoop.sh')` to see what script you're actually downloading. It might be that there's a proxy server giving you something other than [this script](https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1).

**Comment by richkeenan** [comment]
Hi @lygstate, I had the same issue but realised I only had PS version 2 installed. I installed version 4 and it's all good.

**Comment by lygstate** [comment]
So it's better to lowering down the PS version dependence

**Comment by lygstate** [comment]
Windows PowerShell  2.0 is the latest version that support for XP

**Comment by deevus** [comment]
I'm gonna guess this is likely a wontfix.
