### ISSUE TITLE
How can I install different softwares into different hard drives?

### ISSUE THREAD

**Issue by pharazone** [lukesampson/scoop#2600]
Like Soft A in D:// . and Soft B in E://.
Thanks.

**Comment by r15ch13** [comment]
This is currently not possible and not a planned feature.

**Comment by CryoRenegade** [comment]
What I do is install scoop in the hard drive that is my main storage drive, so whenever I install something like ffmpeg, it does not take space in my boot drive.

**Comment by Ash258** [comment]
@pharazone You could use a little hack way. Using global and local apps. (https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory).

Setting Drive E as local and D as global would solve your problem. (for example)

```powershell
[environment]::setEnvironmentVariable('SCOOP','E:\Scoop','User')
$env:SCOOP='D:\Applications\Scoop'

[environment]::setEnvironmentVariable('SCOOP_GLOBAL','D:\Scoop','Machine')
$env:SCOOP_GLOBAL='F:\GlobalScoopApps'
iex (curl "www.get.scoop.sh")
```
