### ISSUE TITLE
"XYZ is already installed" even if package directory is empty

### ISSUE THREAD

**Issue by MauroCoppola** [lukesampson/scoop#2601]
I tried to install **Gradle** but, because of network issue, the zip archive was not successfully downloaded. When I tried again, Scoop warned that a version of Gradle was already installed (even if I couldn't access to the Gradle commands). After I checked **apps** directory, I found out Scoop successfully created the subfolder for Gradle but didn't delete it after installation error (in fact, removing it manually resolved the problem). Is it normal?

**Comment by Ash258** [comment]
Before that version warning is error message: `ERROR It looks like a previous installation of gradle failed.
Run 'scoop uninstall gradle' before retrying the install.`

**Comment by Ash258** [comment]
Just run `scoop unintall gradle; scoop cache rm gradle*; scoop install gradle` Remove broken zip from cache and then it will be downloaded again

**Comment by MauroCoppola** [comment]
Thank you @Ash258, couldn't it be an improvement to revert changes after installation error?

**Comment by MauroCoppola** [comment]
Ok, it's clear. Thank you for the explanation!
