### ISSUE TITLE
git-lfs@2.5.2: extract_dir error

### ISSUE THREAD

**Issue by epieczko-ice** [lukesampson/scoop#2604]
Looking for source file in the wrong directory... 

WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'git-lfs' (2.5.2) [64bit]
Loading git-lfs-windows-amd64-v2.5.2.zip from cache.
Checking hash of git-lfs-windows-amd64-v2.5.2.zip ... ok.
Extracting git-lfs-windows-amd64-v2.5.2.zip ... DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Tue Sep 18 14:34:38 2018

   Source : C:\SDE\Scoop\apps\git-lfs\2.5.2\_tmp\git-lfs-windows-amd64-v2.5.2\
     Dest : C:\SDE\Scoop\apps\git-lfs\2.5.2\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2018/09/18 14:34:38 ERROR 2 (0x00000002) Accessing Source Directory C:\SDE\Scoop\apps\git-lfs\2.5.2\_tmp\git-lfs-windows-amd64-v2.5.2\
The system cannot find the file specified.

ERROR Could not find 'git-lfs-windows-amd64-v2.5.2'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=git-lfs%402.5.2%3a+extract_dir+error
True

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/0ef4b36e43266ddaeed0a5386ae25c6046c56568
