### ISSUE TITLE
git-lfs@2.5.2: extract_dir error

### ISSUE THREAD

**Issue by sameerhr84** [lukesampson/scoop#2605]
PS C:\Users\sramla> scoop install git-lfs
Installing 'git-lfs' (2.5.2) [64bit]
git-lfs-windows-amd64-v2.5.2.zip (2.8 MB) [===================================================================] 100%
Checking hash of git-lfs-windows-amd64-v2.5.2.zip ... ok.
Extracting git-lfs-windows-amd64-v2.5.2.zip ... DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Tue Sep 18 16:08:08 2018

   Source : C:\SDE\Scoop\apps\git-lfs\2.5.2\_tmp\git-lfs-windows-amd64-v2.5.2\
     Dest : C:\SDE\Scoop\apps\git-lfs\2.5.2\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2018/09/18 16:08:08 ERROR 2 (0x00000002) Accessing Source Directory C:\SDE\Scoop\apps\git-lfs\2.5.2\_tmp\git-lfs-window
-amd64-v2.5.2\
The system cannot find the file specified.

ERROR Could not find 'git-lfs-windows-amd64-v2.5.2'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=git-lfs%402.5.2%3a+extract_dir+error

**Comment by sameerhr84** [comment]
its downloading the file into cache as git-lfs#2.5.2#https_github.com_git-lfs_git-lfs_releases_download_v2.5.2_git-lfs-windows-amd64-v2.5.2.zip.

However install is failing and no installables in app folder

**Comment by r15ch13** [comment]
Fixed

**Comment by sameerhr84** [comment]
Thank you
