### ISSUE TITLE
openssl@1.1.1_5: extract_dir error

### ISSUE THREAD

**Issue by seriousm4x** [lukesampson/scoop#2607]
```
λ scoop install openssl
Installing 'openssl' (1.1.1_5) [64bit]
Loading openssl-1.1.1_5-win64-mingw.tar.xz from cache
Checking hash of openssl-1.1.1_5-win64-mingw.tar.xz ... ok.
Extracting openssl-1.1.1_5-win64-mingw.tar.xz ... DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robustes Dateikopieren für Windows
-------------------------------------------------------------------------------

  Gestartet: Donnerstag, 20. September 2018 15:47:58
   Quelle : C:\Users\maxi\scoop\apps\openssl\1.1.1_5\_tmp\openssl-1.1.1-win64-mingw\
     Ziel : C:\Users\maxi\scoop\apps\openssl\1.1.1_5\

    Dateien : *.*

  Optionen: *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2018/09/20 15:47:58 FEHLER 2 (0x00000002) Zugriff auf Quellverzeichnis C:\Users\maxi\scoop\apps\openssl\1.1.1_5\_tmp\openssl-1.1.1-win64-mingw\ Das System kann die angegebene Datei nicht finden.

ERROR Could not find 'openssl-1.1.1-win64-mingw'! (error 16)
```

**Comment by r15ch13** [comment]
Hm, the extraction works fine on my machine. Please try again.
`scoop uninstall openssl; scoop cache rm openssl; scoop install openssl`

**Comment by seriousm4x** [comment]
nope. still getting this error
```
C:\Users\maxi
λ scoop uninstall openssl
Uninstalling 'openssl' (1.1.1_5).
'openssl' was uninstalled.

C:\Users\maxi
λ scoop update
Updating Scoop...
Updating 'versions' bucket...
Scoop was updated successfully!

C:\Users\maxi
λ scoop cache rm openssl

C:\Users\maxi
λ scoop install openssl
Installing 'openssl' (1.1.1_5) [64bit]
openssl-1.1.1_5-win64-mingw.tar.xz (2,5 MB) [=========================================================================================] 100%
Checking hash of openssl-1.1.1_5-win64-mingw.tar.xz ... ok.
Extracting openssl-1.1.1_5-win64-mingw.tar.xz ... DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robustes Dateikopieren für Windows
-------------------------------------------------------------------------------

  Gestartet: Montag, 24. September 2018 08:56:07
   Quelle : C:\Users\maxi\scoop\apps\openssl\1.1.1_5\_tmp\openssl-1.1.1-win64-mingw\
     Ziel : C:\Users\maxi\scoop\apps\openssl\1.1.1_5\

    Dateien : *.*

  Optionen: *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2018/09/24 08:56:07 FEHLER 2 (0x00000002) Zugriff auf Quellverzeichnis C:\Users\maxi\scoop\apps\openssl\1.1.1_5\_tmp\openssl-1.1.1-win64-mingw\ Das System kann die angegebene Datei nicht finden.

ERROR Could not find 'openssl-1.1.1-win64-mingw'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssl%401.1.1_5%3a+extract_dir+error
True
```

**Comment by r15ch13** [comment]
What it the output of `tree /f C:\Users\maxi\scoop\apps\openssl` after the failed installation?

**Comment by r15ch13** [comment]
What is the content of the `openssl.tar.xz` from `C:\Users\maxi\scoop\cache`?
Does it contain the `openssl-1.1.1-win64-mingw` directory?
Can you try disabling an antivirus, if you have one installed?

Strange that it is an access denied error...

**Comment by seriousm4x** [comment]
i extraced the archive and it does contain the folder you mentioned with the whole openssl packge inside.

only antivirus i have is the default windows defender. I disabled it and tried again, but with the same result.

**Comment by seriousm4x** [comment]
ran powershell as administrator with, again, the same result.

i had anther 7zip version (7-Zip 18.05 (2018-04-30) for Windows) installed on my system. uninstalled it, rebooted, tried angain. same result.

i wiped scoop completely off of my system the other day, just to make sure, but i'm still stuck here. little bit clueless right now.

**Comment by r15ch13** [comment]
Can you try adding `Start-Sleep -Milliseconds 1000` **after** the following line
https://github.com/lukesampson/scoop/blob/a02a53ddc686fd3ff4c97e2e27bbe96e4f8f6849/lib/install.ps1#L582

It's located at `C:\Users\maxi\scoop\apps\scoop\current\lib\install.ps1`.

I have no clue 😭

**Comment by seriousm4x** [comment]
nope. still the same

**Comment by r15ch13** [comment]
Can you add the following
```powershell
debug "`n$path`n$to`n$recurse`n$output`n"
```
**after** this line:
https://github.com/lukesampson/scoop/blob/a02a53ddc686fd3ff4c97e2e27bbe96e4f8f6849/lib/decompress.ps1#L21
and post the output?

**Comment by seriousm4x** [comment]
ohhhh myyyy.. i solved it.
i had an unknown p7zip executable from msys2 lying around which was used. uninstalled it with pacman.
it works now.. thanks for all!

**Comment by r15ch13** [comment]
Woohoo! 🎉
Don't forget to reset the changed scoop files :smile:
Run `git reset --hard` on `C:\Users\maxi\scoop\apps\scoop\current\`
