### ISSUE TITLE
How to install PLSQL licensed and latest version through scoop.

### ISSUE THREAD

**Issue by hareramcse** [lukesampson/scoop#2611]
I Need to install PLSQL version 12.x through scoop. i have license for this software which we can use it while installing PLSQL. can anyone provide me the json file like(plsql.json) to install it.
Question: Can we install any licensed version of software through scoop ?

**Comment by Calinou** [comment]
> Question: Can we install any licensed version of software through scoop ?

You can write manifests to install anything with Scoop :slightly_smiling_face:

However, the main bucket only accepts full versions of software that are available for free (legally). See the [Criteria for including apps in the main bucket](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket). The [scoop-extras](https://github.com/lukesampson/scoop-extras) software includes some software that requires a paid account to use (but not to install), so it is more lenient on that point.

**Comment by hareramcse** [comment]
If i would know exact manifest to install PLSQL i would have installed it :). I have read somewhere that we cant install licensed version of software through Scoop that is why i asked. Any help here would be appreciated.
