### ISSUE TITLE
GroovyServ not found

### ISSUE THREAD

**Issue by f-lima** [lukesampson/scoop#2614]
I tryed:
scoop install groovyserv

But got:
Couldn't find manifest for 'groovyserv'

Homebrew has. Like scoop supposed to be a 'homebrew for windows', I suggest that all applications supported by Homebrew be added to scoop manifest.

Thanks.

**Comment by Ash258** [comment]
None said scoop is "homebrew for windows". It's only inspired by homebrew.

**Comment by Ash258** [comment]
If you want to request some monifest, which you cannot find via `scoop search`, open issue with information abouts it's application.
