### ISSUE TITLE
Scoop uses Git to update itself. Run 'scoop install git' and try again

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#2620]
Will it interfere with already installed Git on Windows?
Should I remove the Git and then install it through scoop as GLOBAL APP?

**Comment by leonyu** [comment]
Just add Git to your path, unless your creating PR, `scoop` should be able to use any git installation that's accessible via PATH.

**Comment by quantuumsnot** [comment]
Ok then, remove already installed Git and reinstalled it through Scoop
