### ISSUE TITLE
Server JRE & JRe links on wiki don't work

### ISSUE THREAD

**Issue by mstevens83** [lukesampson/scoop#2622]
The links to the Oracle "Server JRE" and "JRE" on the wiki (https://github.com/lukesampson/scoop/wiki/Java) do not work.

**Comment by se35710** [comment]
There are no more JRE:s and Server JRE:s offered by Oracle. Java 10 will reach EOL now in september, and Java 8 in January.

https://www.oracle.com/technetwork/es/java/javase/documentation/eol-135779.html

**Comment by mstevens83** [comment]
Wow, that comes as a surprise. So how are end-users supposed to run java software then?
