### ISSUE TITLE
*Enhancement* Spacemacs: installation configuration option for Emacs 

### ISSUE THREAD

**Issue by benhuxham** [lukesampson/scoop#2625]
I spent a substantial time trying to work out why scoop installed emacs wasn't reading my ~/.emacs.d/init.el configuration. Having found it, is it possible to have a parameter to use/install spacemacs?

Or it may be easier to explain where scoop keeps personalised configuration data in the FAQ?

OS: Win10
PoSH: 5.1.17134.228

**Comment by r15ch13** [comment]
Scoop doesn't manage any of emacs' configuration files/directories.
Your personal configuration should be `~/.spacemacs.d/init.el`, if I understand the [quick start](http://spacemacs.org/doc/QUICK_START.html) guide correctly.

**Comment by benhuxham** [comment]
Okay. That was what I initially expected. Thanks. Will have work out what is going on with my setup then.

**Comment by manumc** [comment]
I'm having the same issue also.

OS: Windows 10 Pro (build 17134.590)

If I execute emacs from the shorcut at the start menu folder or even if I execute it from cmd or powershell it always fail with `error "Variable binding depth exceeds max-specpdl-size"` when it tries to read the file `~/.emacs.d/init.el`.

However it works perfectly fine if execute it from Git Bash.

Could be something related with the enviroment variables?

I'm not sure how scoop handle those.

**Comment by benhuxham** [comment]
@codeswish No.

Emacs was reading from a configuration folder in 'Application Data'. Given both Windows & Emacs were generic installs I have no idea why it was set there rather than ~
