### ISSUE TITLE
Is there a way to see available console commands for scoop installed apps

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#2626]
Like writing `scoop list` but for commands.

For example if we have the following apps in scoop:
>Installed apps:
  7zip 18.05
  aria2 1.34.0-1
  concfg 0.2018.5.27
  git 2.19.0.windows.1
  openssh 7.6p1

then if we type `scoop listcmd` to have the following output:
> 7z
7zFM
git
openssh
etc ...

**Comment by h404bi** [comment]
No, but a similar way I think you could get all shims with `ls ~/scoop/shims`.
