### ISSUE TITLE
Some suggestions when an updating or fresh new installing failed

### ISSUE THREAD

**Issue by xiehao** [lukesampson/scoop#2630]
I am a newbie of `scoop`, and my network is often unstable, so when I install or update some software via `scoop`, it usually fails since a broken network connection. However, `scoop` shows me that the software is already installed, and the `info` shows that it has the latest version (but actually not). At this time, I have to `uninstall` and `install` it again and again, from the beginning, if the network is still bad.

I was wondering if:
1. the `info` could show the users the previous successfully installed version, not the new failed one, when an updating failed, or a `Not installed` flag, when a fresh new installing failed.
2. and the user would not have to `uninstall` and `install` it, but could continue downloading from the broken point when typing `update` or `install` command after a failure.

Thanks a lot for making such a stunning tool, and I think `scoop` is a very helpful tool to me.

**Comment by rasa** [comment]
This is a valid issue, which will be fixed eventually.
