### ISSUE TITLE
Cannot bypass the proxy configured in internet options

### ISSUE THREAD

**Issue by gwenl** [lukesampson/scoop#2635]
The documentation states that it should be possible to [bypass the proxy configured in Internet Options](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy#config-examples).

This doesn't seem to work, as when I try to set the proxy to "none", with the following command:
```scoop config proxy none```

I get this error:

```fatal: unable to access 'https://github.com/lukesampson/scoop/': Could not resolve proxy: none```

**Comment by rasa** [comment]
The wiki has been corrected
