### ISSUE TITLE
Mariadb 10.3.10 install fails - can't shim mysqltest.exe

### ISSUE THREAD

**Issue by minorgod** [lukesampson/scoop#2645]
Just tried installing mariadb and get the error:
`Can't shim 'bin\mysqltest.exe': File doesn't exist. `

Here's the log -- I was doing a global install and using sudo, but the same error occurs with non-global install and without sudo:

```
`~ $ sudo scoop install mariadb --global
Installing 'mariadb' (10.3.10) [64bit]
Loading mariadb-10.3.10-winx64.zip from cache
Checking hash of mariadb-10.3.10-winx64.zip ... ok.
Extracting mariadb-10.3.10-winx64.zip ... done.
Linking D:\scoop\apps\mariadb\current => D:\scoop\apps\mariadb\10.3.10
Creating shim for 'aria_chk'.
Creating shim for 'aria_dump_log'.
Creating shim for 'aria_ftdump'.
Creating shim for 'aria_pack'.
Creating shim for 'aria_read_log'.
Creating shim for 'innochecksum'.
Creating shim for 'myisamchk'.
Creating shim for 'myisamlog'.
Creating shim for 'myisampack'.
Creating shim for 'myisam_ftdump'.
Creating shim for 'mysql'.
Creating shim for 'mysqladmin'.
Creating shim for 'mysqlbinlog'.
Creating shim for 'mysqlcheck'.
Creating shim for 'mysqld'.
Creating shim for 'mysqldump'.
Creating shim for 'mysqlimport'.
Creating shim for 'mysqlshow'.
Creating shim for 'mysqlslap'.
Creating shim for 'mysqltest'.
Can't shim 'bin\mysqltest.exe': File doesn't exist.`
```

I just did this install the other day with the previous version of mariadb (guessing it was 10.2.10) and I didn't have this issue, so maybe something changed in the latest release?

**Comment by DesigningKnights** [comment]
Looking in the zip file, there is no bin\mysqltest.exe.  They must have removed it from the release, so the manifest file would need to be fixed to not try to install that shim.

**Comment by DesigningKnights** [comment]
Looking at the manifest and the zip, it looks like MariaDB left out the mysql_client_test.exe as well in this zip release.

**Comment by DesigningKnights** [comment]
You forgot to remove mysql_client_test.exe too.  It is also missing in the new build.  Install still fails with an error

![capture](https://user-images.githubusercontent.com/8666549/46906733-ef9e9380-cf3a-11e8-862a-c36319dbd525.JPG)
