### ISSUE TITLE
Remove aria2 support

### ISSUE THREAD

**Issue by vaguiners** [lukesampson/scoop#2647]
Aria2 (aria2c) is buggy. Sometimes works, sometimes  dont

**Comment by Ash258** [comment]
No one force you to use it. Just uninstall / disable it.

**Comment by vaguiners** [comment]
The aria2c is not just for the scoop. I use it for other things and so I'm forced to manually deactivate aria2c from the scoop because the scoop forces me to use aria2c if aria2c is installed

**Comment by vaguiners** [comment]
And by "i'm", i mean everyone is forced to manually deactivate

**Comment by DesigningKnights** [comment]
@vaguiners , I have to disagree with you. Download managers are still needed in many parts of the world.  Not everyone has high speed stable connections.  I'm in a location where the internet is slow and unstable. Having a download manager has saved me from many wasted hours and precious metered data.  Not everything in scoop is "extremely light".  Some things in scoop can range over 100mb or more.  May seem small to you, but to those of us on a metered connection, 100mb is a lot of data.

**Comment by vaguiners** [comment]
> @vaguiners , I have to disagree with you. Download managers are still needed in many parts of the world. Not everyone has high speed stable connections. I'm in a location where the internet is slow and unstable. Having a download manager has saved me from many wasted hours and precious metered data. Not everything in scoop is "extremely light". Some things in scoop can range over 100mb or more. May seem small to you, but to those of us on a metered connection, 100mb is a lot of data.

I'm sure you're telling the truth, the problem is that it would be totally unfair to force the majority to go through a problem to help a minority.

Most people here have good internet and most have suffered or will suffer from aria2c.
I hope aria2c is at least disabled by default from the scoop, so the user can activate if they want.

**Comment by h404bi** [comment]
This issue should be re-open.

**Comment by wh7** [comment]
I think it would be better if there is a config or flag to control whether or not to use aria2 to download. The frequency that I have to uninstall aria2, install some app that can't be downloaded via aria2 and then reinstall aria2 is very frustrating.

**Comment by DesigningKnights** [comment]
You don't need to uninstall it.  Just run 'scoop config aria2-enabled false' to disable it.  It even says so whenever you download or update something.

**Comment by wuya666** [comment]
> 
> 
> > @vaguiners , I have to disagree with you. Download managers are still needed in many parts of the world. Not everyone has high speed stable connections. I'm in a location where the internet is slow and unstable. Having a download manager has saved me from many wasted hours and precious metered data. Not everything in scoop is "extremely light". Some things in scoop can range over 100mb or more. May seem small to you, but to those of us on a metered connection, 100mb is a lot of data.
> 
> I'm sure you're telling the truth, the problem is that it would be totally unfair to force the majority to go through a problem to help a minority.
> 
> Most people here have good internet and most have suffered or will suffer from aria2c.
> I hope aria2c is at least disabled by default from the scoop, so the user can activate if they want.

I'm not sure how you get the idea about "force the majority to go through a problem to help a minority", also I'm not sure how do you define "good internet". For example, China has around 800 million internet users and India has around 600 million internet users and their connection speed to a lot of the software repos are sub-optimal. 

Personally I have 200Mbps cable connection but it's still a pain to download a 150MB package at times, and I'm already using the best ISP around here, the only way for me to find a better ISP would be to migrate to the US or something...

I do find scoop's integration of aria2 somewhat buggy at times, but to suggest scoop removing aria2 support altogether is kinda ridiculous IMHO. I think it'd help if scoop can optimize its integration of aria2 for better performance somehow, personally I find just optimizing the default retry-wait/split/min-split-size config parameters can make a great difference. 

For those who really don't need aria2 integration, scoop does show the tip on how to disable aria2 if you don't want it EVERY TIME you download a package with aria2 enabled. From what I see, that's just a minor nuisance to a minority while aria2 integration greatly helps the majority IMHO

**Comment by Restia666Ashdoll** [comment]
Kinda off-topic, but is it possible to use wget instead of aria2 ?

**Comment by parasquid** [comment]
Just got here from a google search on how to *enable* aria2c because (surprise surprise) downloading a 1.1g package with slow internet is such a pain :D

I would second the ability to choose between downloaders (and possible options). wget curl and aria2 (plus the default downloader, whatever it was).

**Comment by rsenna** [comment]
This is a non-issue. Only possible action IMHO would be to make `aria2-enabled` default to `false` - and I'm pretty sure that if that ever happens I would always turn it on just after installing scoop.

To complete remove aria2 support would be an excessive, absurd action.

**Comment by shawn-liu-rft** [comment]
agree it's not a issue. aria2 is definitely useful when install some big package like CUDA.

**Comment by rasa** [comment]
While removing aria2 is unnecessary, making `aria2-enabled` default to false is certainly an option. If someone wants to propose that please create a new issue.
