### ISSUE TITLE
Couldn't find manifest for 'bittorrent'.

### ISSUE THREAD

**Issue by navarannan** [lukesampson/scoop#2652]
Hi trying to install bittorrent package using scoop.
xxx@DESKTOP-45TF4RE MINGW64 ~
$ scoop bucket list
bittorrent

xxx@DESKTOP-45TF4RE MINGW64 ~
$ scoop install bittorrent
WARN  Bucket '' not installed. Add it with 'scoop bucket add ' or 'scoop bucket add  <repo>'.
Couldn't find manifest for 'bittorrent'.

Any clue.
Note:- I did a scoop update as well
xxx@DESKTOP-45TF4RE MINGW64 ~
$ scoop update
Updating Scoop...
Updating 'bittorrent' bucket...
Scoop was updated successfully!

xxx@DESKTOP-45TF4RE MINGW64 ~
$ scoop install bittorrent
WARN  Bucket '' not installed. Add it with 'scoop bucket add ' or 'scoop bucket add  <repo>'.
Couldn't find manifest for 'bittorrent'.

**Comment by Ash258** [comment]
What is URL of that "bittorrent" bucket??

**Comment by navarannan** [comment]
> What is URL of that "bittorrent" bucket??

https://github.com/effigies/BitTornado

**Comment by Ash258** [comment]
You totally missed how scoop works. You cant just add some repository with application and expect to use it. Buckets contains manifests. Manifests are files with everything needed to download program. 

Bittornado is some Python library, which could be used by directly calling python script. If you want to add it to scoop request it here and maybe someone who know how this app should look like / work will help you.

**Comment by navarannan** [comment]
Basically I want to use btshowmetainfo 
As specified here Im trying to install the package bittorrent as specified here

https://unix.stackexchange.com/questions/31486/is-there-a-tool-to-view-a-torrent-file

**Comment by Ash258** [comment]
Use aria2

`scoop install aria2` and then https://unix.stackexchange.com/a/197842

**Comment by navarannan** [comment]
> Use aria2

Oh woww. You save a hell lotta time. Thanks a million :-)

**Comment by Ash258** [comment]
Then please run `scoop config aria2-enabled false`. It will cost you less problems.
