### ISSUE TITLE
grep@2.5.4: download via aria2 failed

### ISSUE THREAD

**Issue by sameerhr84** [lukesampson/scoop#2661]
Intermittently grep installation fails. Can you  help us with this. Can this be moved to a different repository?

Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
DEBUG https://downloads.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-bin.zip
    dir=C:\SDE\Scoop\cache
    out=grep#2.5.4#https_sourceforge.net_projects_gnuwin32_files_grep_2.5.4_grep-2.5.4-bin.zip
https://downloads.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-dep.zip
    dir=C:\SDE\Scoop\cache
    out=grep#2.5.4#https_sourceforge.net_projects_gnuwin32_files_grep_2.5.4_grep-2.5.4-dep.zip

DEBUG & 'C:\SDE\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\SDE\Scoop\cache\grep.txt' --user-agent='Scoop/1.0
(+http://scoop.sh/) PowerShell/5.0 (Windows NT 6.1; Win64; x64; )' --allow-overwrite=true --auto-file-renaming=false --
etry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false -
no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3
56 --continue

**Comment by rasa** [comment]
Closing as this issue appears to be obsolete.
