### ISSUE TITLE
[App Addition] Add Ungoogled Chromium to the main bucket

### ISSUE THREAD

**Issue by T145** [lukesampson/scoop#2664]
Repo here: https://github.com/Eloston/ungoogled-chromium
Download links: https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by Ash258** [comment]
Ungoogled cannot be added to main buckets, since it's GUI application. 

It's already in extras bucket.

**Comment by T145** [comment]
Are all GUI apps in the extras bucket?

**Comment by r15ch13** [comment]
Yes
