### ISSUE TITLE
Haxe libs with binaries don't work until haxe path added to PATH

### ISSUE THREAD

**Issue by kevinpeno** [lukesampson/scoop#2678]
Was playing around with Haxe today and noticed that if I installed flixel-tools, which adds the binary `flixel`, to the haxe root that powershell cannot find `flixel`. There's a number of tools like this with haxe that add binaries to the haxe root. Perhaps Haxe should be treated a little more like node in this respect? Don't add a shim and add the `current/haxe` to the path?

If you think it is as simple as that lemme know and I can submit a PR.

**Comment by r15ch13** [comment]
`haxelib` installs it to `~/scoop/apps/haxe/current/lib` because the installation sets the `HAXEPATH` environment variable.
If this variable is not set, it installs to `~\haxelib`.

https://github.com/HaxeFoundation/haxelib/blob/0161c1a1af2adcc51943a2cb006954790b8eb0bd/src/haxelib/client/Main.hx#L1054-L1062

I don't know if `HAXEPATH` is used for something else. The easiest fix right now is to add `"persist": "lib"` to the manifest.

**Comment by kevinpeno** [comment]
@r15ch13 I'm not sure I understand why this issue has been closed. Was this accidental?

Yes haxlib installs to the `HAXEPATH` under the folder `lib` as you describe. However, the binaries that follow the packages also get installed into the root. You don't _have to_ call those binaries directly, it appears as though `haxelib run flicel-tools` runs fine (likely because haxe is using `HAXEPATH` properly). So I'm not certain `"persist": "lib"` would resolve the issue, but I can give it a shot locally if you still think that's the case.

This isn't a huge bug because one can still run the tools as I mention. However most online instructions explain themselves in that manner and any installation that doesn't support that would confuse a new user, as it did me.

**Comment by r15ch13** [comment]
Hm, `haxelib install flixel-tools` doesn't add `flixel.bat/.sh` to the main haxe directory. It's located at `D:\scoop\apps\haxe\current\lib\flixel-tools\1,4,2\bin\flixel.bat` for me.

But `flixel.bat` just calls `haxelib run flixel-tools` though.

`npm` creates a `bin` directory with all available commands, but it seems `haxelib` doesn't work that way. Adding this to the environment would work.
Do you have another example of libs that create binaries?

**Comment by kevinpeno** [comment]
I think this is because another thing haxe libs do is require you run a `setup` command. I suppose this is a way to get the binaries and dependencies of those libs. Try running `haxelib run flixel-tools setup` and see the result. Some other libs I was asked to use in the tutorial I was following were `lime` and `openfl`. I know `lime` required setup to be called as well, but I cannot recall if `openfl` did. In both cases a bin and/or bat/exe file was added to the root.

https://imagebin.ca/v/4JR0UmbXYsBU

**Comment by r15ch13** [comment]
Ah, I see! Will add it to `PATH` 👍
