### ISSUE TITLE
Request App Notify Send

### ISSUE THREAD

**Issue by ekoeryanto** [lukesampson/scoop#2681]
Halo, it is an app request for http://vaskovsky.net/notify-send/

**Comment by ekoeryanto** [comment]
I tried it on windows 10, about 3-4 hours ago and it works

**Comment by Calinou** [comment]
If you want to create notifications on Windows 10, there's a third-party PowerShell module for that: https://github.com/Windos/BurntToast

**Comment by r15ch13** [comment]
*cough* deactivated all notifications on my system *cough*
That's why it didn't work 😁

**Comment by ekoeryanto** [comment]
@Calinou I prefer `notify-send` because it also available on Linux so my `bash` script can work without modification 😄

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2681
