### ISSUE TITLE
Rename docker.json to docker-toolbox.json

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2682]
Main bucket docker manifest is not manifest, which provides docker.

# Docker vs Docker Toolbox

## Toolbox

- > Docker Toolbox provides a way to use Docker on Windows systems that do not meet minimal system requirements for the Docker.
- It does not use Hyper-V, but Virtualbox
- docker bin is only alias for `boot2docker ssh`
- Could be installed under older windows versions
- Delegate docker commands into VM, where docker is running.
- Vagrant like experience with docker

## Docker

- Pure docker experience
- No need for virtualbox and sharing drive using virtualbox driver
- Windows 10 and Hyper-V is needed

[Example of pure docker manifest](https://github.com/Ash258/scoop-Ash258/blob/master/docker.json).

**Comment by bcatubig** [comment]
There should also be a sanity check to check if VirtualBox is installed as well since Docker for Windows requires Hyper-V and can't run alongside VirtualBox.

**Comment by se35710** [comment]
I would suggest creating those manifests in [extras](https://github.com/lukesampson/scoop-extras) and leave the [docker](https://github.com/lukesampson/scoop/blob/master/bucket/docker.json) manifest as it is. The docker cli is not distributed separately.

Or at least rename the existing docker manifest to docker-cli.

For Hyper-V I see no need for a scoop manifest, since Docker will update itself once installed.

**Comment by Ash258** [comment]
@se35710 I dont agree with anything what you wrote. Maybe that move it to extras bucket, but main purpose of this issue is that, it's manifest is misleading and wrong. You expected to install docker, whole docker. Not something, which is dependent on other software, which is not provided by scoop. Completely different software. 

And mainly. You write `scoop install docker` and you see `downloading docker-toolbox`. Which is inappropriately, and could easily / confuse user, which does not care about writing manifest. User only want to install docker == Not happened and you still need to install Virtualbox manually.

> For Hyper-V I see no need for a scoop manifest, since Docker will update itself once installed. 

Scoop is not only for autoupdating or anything. It's for making windows applications installing via command line (usage in CLIs, CIs, VMs, remote sessions, ...). And some of applications in scoop handle updates itself. (firefox for example)

**Comment by h404bi** [comment]
Why not use chocolatey's logic?

https://chocolatey.org/packages/docker
https://chocolatey.org/packages/docker-compose
https://chocolatey.org/packages/docker-for-windows
https://chocolatey.org/packages/docker-toolbox
https://chocolatey.org/packages/docker-machine

**Comment by se35710** [comment]
@Ash258 The official Docker client binary (docker.exe) is not available as a separate download, it is only available through the docker-toolbox package. (Although there is a non official community built docker.exe used by Chocolatey available at https://github.com/StefanScherer/docker-cli-builder).

For all those who do not use Docker daemon locally on their machines or use a virtualized Docker daemon in Linux (without boot2docker) locally the current manifest provides them with all that they need, so please do not remove it, instead rename it to docker-cli if you must.

**Comment by rasa** [comment]
Great discussion. Can this issue be closed? @Ash258?

**Comment by Ash258** [comment]
Nothing was solved. Still waiting for renaming as suggested in https://github.com/lukesampson/scoop/issues/2682#issuecomment-434765825.

Named:

1. docker.json -> docker-toolbox.json
1. www.github.com/StefanScherer/docker-cli-builder/ -> docker.json
1. docker-machine.json -> ✔
1. docker-compose.json -> ✔
1. docker-nightly.json -> Maybe correct. Never heard of it and never used it.
1. docker-for-windows.json -> is pretty complicated and I don't think maintainers want it in this bucket because of not possiblility to change folder, admin requirement.

**Comment by se35710** [comment]
Some comments:

> 1. docker.json -> docker-toolbox.json

docker-toolbox is packaged with Oracle VM VirtualBox, which needs elevated rights to install (see https://github.com/lukesampson/scoop/issues/229). So by renaming it to docker-toolbox, scoop still would not install VirtualBox. The manifest does allow the use of docker-machine to create Docker VM machines in [VMware Workstation](https://github.com/pecigonzalo/docker-machine-vmwareworkstation), Hyper-V, VirtualBox or any other docker-machine [driver](https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md), even provision hosts remote.

> 2. www.github.com/StefanScherer/docker-cli-builder/ -> docker.json

Why use an unofficial build of docker.exe when it's available in the docker-toolbox binary? The main issue seems to be from [the comment](https://github.com/lukesampson/scoop/issues/2682#issuecomment-434758360) above:

> And mainly. You write scoop install docker and you see downloading docker-toolbox. Which is inappropriately, and could easily / confuse user, which does not care about writing manifest. User only want to install docker == Not happened and you still need to install Virtualbox manually.

...then why not just re-add the note removed in commit https://github.com/lukesampson/scoop/commit/ee1d277eae3144525bd60706939ddc48ffb8f77d

Add more cleanup in the post_install step, or don't create shortcuts and shims for everything but docker.exe if needed.

> 5. docker-nightly.json -> Maybe correct. Never heard of it and never used it.

The nightly builds of docker.exe / dockerd.exe can be found [here](https://master.dockerproject.org/), and the local docker daemon can be configured as in the note in [docker-nightly.json](https://github.com/lukesampson/scoop/blob/master/bucket/docker-nightly.json). Unfortunately Docker, Inc. removed the binary release distributions from dockerproject.org and Github, why the manifest are as they are.
