### ISSUE TITLE
[Request] Add MDLR

### ISSUE THREAD

**Issue by BarbzYHOOL** [lukesampson/scoop#2684]
Mdlr is an app to facilitate submodule usage in git

There are binaries for windows directly in the readme (I haven't tested them since I'm on linux but i wanted to share this tool)

https://github.com/exlinc/mdlr

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2684
