### ISSUE TITLE
"The remote server returned an error: (404) Not Found." while the resource is online

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#2694]
PS C:\Users\XXX> scoop install vegeta
Installing 'vegeta' (12.0.0) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/tsenart/vegeta/releases/download/cli%2Fv$version/vegeta-$version-windows-amd64.zip is not valid

This is the result with enabled and disabled aria2 - no success, but the file is there and CAN be downloaded ...

Where's my mistake? This is the code used in my personal bucket for installing vegeta:

`{
    "homepage": "https://github.com/tsenart/vegeta/releases/latest",
    "license": "MIT License",
    "version": "12.0.0",
    "architecture": {
        "64bit": {
            "url": [
                "https://github.com/tsenart/vegeta/releases/download/cli%2Fv$version/vegeta-$version-windows-amd64.zip"
            ],
            "hash": [
                "041e17e5fbe506dc8e652e5de7e5c1b4e4bf9910078ba1c35cf74c40d7483f78"
            ]
        }
    },
    "bin": "vegeta.exe",
    "checkver": "<title>Release ([\\d.]+) · tsenart/vegeta</title>",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/tsenart/vegeta/releases/download/cli%2Fv$version/vegeta-$version-windows-amd64.zip"
            }
        }
    }
}`

**Comment by Ash258** [comment]
YOur manifest is wrong in lots of ways. See [Wiki](https://github.com/lukesampson/scoop/wiki/Creating-an-app-manifest)

Here is correct one:

```json
{
    "version": "12.0.0",
    "homepage": "https://github.com/tsenart/vegeta/",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/tsenart/vegeta/releases/download/cli%2Fv12.0.0/vegeta-12.0.0-windows-amd64.zip",
            "hash": "b425ae4021e0fa47167dae1792def5c0aa0aaedb697deda07b6b20429eb6736b"
        }
    },
    "bin": "vegeta.exe",
    "checkver": {
        "github": "https://github.com/tsenart/vegeta/",
        "regex": "v([\\d\\.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/tsenart/vegeta/releases/download/cli%2Fv$version/vegeta-$version-windows-amd64.zip"
            }
        },
        "hash": {
            "url": "https://github.com/tsenart/vegeta/releases/download/cli%2Fv$version/vegeta-checksums.txt"
        }
    }
}
```

**Comment by quantuumsnot** [comment]
Whoa, thanks! I'll use this as template ... Btw do you like the idea to have a browser based manifest generator for scoop?

**Comment by Ash258** [comment]
What idea? Where was that idea said?

**Comment by quantuumsnot** [comment]
A friend suggested it for easier app manifest creation hence more apps supported in scoop

**Comment by Ash258** [comment]
I really don't care. 

Close the issue.
