### ISSUE TITLE
7zip still searches for 7zG.exe in Program Files

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#2695]
Just made a small test and installed 7zip with scoop, then right-clicked on an archive, selected '7-Zip' and when selected 'Extract here' got the following message popup:

'The system cannot find the file specified'
'C:\Program Files\7-Zip\7zG.exe'

and then another one:
'The system cannot find the file specified'

Also selecting '7-Zip' and then 'Open archive' does nothing. No error or 7-Zip window are shown

7-Zip is 18.05

**Comment by r15ch13** [comment]
Open 7zip as admin, go to options and enable the context menu settings. You still have the old settings active.

**Comment by quantuumsnot** [comment]
It IS enabled by default

**Comment by Ash258** [comment]
Then disable and reenable it. You need to rewrite that old registry values pointing to Program files with that to scoop. (From scoops 7z.exe)

**Comment by quantuumsnot** [comment]
Tried without success

**Comment by Ash258** [comment]
Have you run 7z.exe with admin rights from scoop's directory??

**Comment by quantuumsnot** [comment]
Yes

**Comment by Ash258** [comment]
Then uninstall that old version and do it again. Maybe restart would be usefull for registry would be usefull after unisntalltion.

**Comment by quantuumsnot** [comment]
Did the restart after all steps above. There is still a 'C:\Program Files\7-Zip' folder containing 7-zip.dll which cannot be deleted because 'the file is open in Windows Explorer'

**Comment by Ash258** [comment]
And this message doesn't help you indicate that, the dll is hooked to explorer and cause you this problem?? 

Just use LockHunter or something like that to delete that file.

**Comment by quantuumsnot** [comment]
No, because I UNINSTALLED 7-Zip, restarted and then installed 7-Zip with scoop, and this file popuped right after messing with 'Context menu' options

**Comment by quantuumsnot** [comment]
Booted from another drive with different Windows installation, deleted the file and booted again from the first drive. Now it's ok but next time I'll definitely test Win package managers in virtual machine. Too risky to compromise the host OS
