### ISSUE TITLE
dbeaver 5.2.3 hash check fail

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop#2699]
Checking hash of dbeaver-ce-5.2.3-win32.win32.x86_64.zip ... ERROR Hash check failed!
App:         extras/dbeaver
URL:         https://dbeaver.io/files/5.2.3/dbeaver-ce-5.2.3-win32.win32.x86_64.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    bb1cc11859672c261faeba09a75f4434e86a0c872c119476fe83f3f9a8097e9a
Actual:      a4e9ab0693e8c3e0082a298c808f60e0d942cabd18e0525ac45f30599bcdd5c4

**Comment by rasa** [comment]
Obsolete version.
