### ISSUE TITLE
QUESTION: Why scoop is not available after install?

### ISSUE THREAD

**Issue by EM1L** [lukesampson/scoop#2700]
I am new to scoop and trying to use it to automate server environment setup.

I am installing scoop via [Octopus Deploy](https://octopus.com) on target server. Later when attempting to run `scoop install <app>` it is not available as if not installed...  My script triggers new install, which fails as then it detects that it is already installed...

My Question: How scoop is being "loaded"? What could be the reason it is not being recongised after install? Octopus Deploy is using the same system account to install and run commands later... 

How could I fix this - Can I force scoop load explicitly, if it is powershell module?

Thanks!

**Comment by Ash258** [comment]
Scoop "installer" detect installed scoop via these functions. Basicly only when he found `$env:SCOOP\apps\scoop` folder

https://github.com/lukesampson/scoop/blob/cef103bf469e1494c35703c8411d47c88236db24/bin/install.ps1#L35-L40

https://github.com/lukesampson/scoop/blob/cef103bf469e1494c35703c8411d47c88236db24/lib/core.ps1#L90-L97

Could you share your script??

**Comment by EM1L** [comment]
Thanks for your response. Yes, it detects the installation via the environment variable, however when attempting to call `scoop` it is not available so my question is how does scoop "bootstaps" its self? Is is via PowerShell profile?...

**Comment by Ash258** [comment]
It uses custom shim inside `$env:SCOOP\shims\`. After scoop download all neded file it shim itself and append `shims` folder into path.

https://github.com/lukesampson/scoop/blob/cef103bf469e1494c35703c8411d47c88236db24/bin/install.ps1#L55-L59

**Comment by EM1L** [comment]
That is the confirmation I was looking for - I shall check if the `shims` is properly added to path.

**Comment by EM1L** [comment]
Alternatively, the issue might be because it is being run under system privileged account...
