### ISSUE TITLE
imagemagick@7.0.8-14: hash check failed

### ISSUE THREAD

**Issue by GeraldKaeferle** [lukesampson/scoop#2706]

**Comment by equinox** [comment]
I was able to install the 64 bit version of imagemagick@7.0.8-14 without issue and upon checking the hashes manually for both the 32 bit and 64 bit listed in [imagemagick.json](https://github.com/lukesampson/scoop/blob/master/bucket/imagemagick.json), still found no discrepancy.

Could you please supply what architecture scoop was trying to install, and what the hash was and whether or not you still get the error if you try again now. Thanks.
