### ISSUE TITLE
Different Search Result on PowerShells

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#2707]
![conemu64_2018-10-27_13-27-58](https://user-images.githubusercontent.com/3883354/47602804-6b451980-d9ec-11e8-8ae8-4ed00c9f35ef.png)

What can cause this? I search it but I cannot find it.

(Freshly installed OS. Windows OS Build: 17134.345)

Thank you for your responses.

**Comment by bcatubig** [comment]
Looks like you have the system version of powershell installed (v5) and powershell core installed as well.

**Comment by yigitemres** [comment]
> Looks like you have the system version of powershell installed (v5) and powershell core(6.1) installed as well.

I know that I'm having powershell and powershell core (pwsh). What I don't understand is that, why same search function have different outputs?

**Comment by r15ch13** [comment]
That was caused by a missing `$_.Name` call in `apps_in_bucket()`. PowerShell Core handles the FileInfo-Result from `Get-ChildItem` differently.

**Comment by yigitemres** [comment]
> That was caused by a missing `$_.Name` call in `apps_in_bucket()`. PowerShell Core handles the FileInfo-Result from `Get-ChildItem` differently.

Thank you for fix and response.
