### ISSUE TITLE
Install make failed

### ISSUE THREAD

**Issue by wumo** [lukesampson/scoop#2710]
```
> scoop install make
Installing 'make' (4.2) [64bit]
Unable to connect to the remote server
URL ftp://ftp.equation.com/make/64/make.exe is not valid
```

**Comment by bcatubig** [comment]
I tested both links and they appear to be working again. Can you try installing again?

- ftp://ftp.equation.com/make/32/make.exe
- ftp://ftp.equation.com/make/64/make.exe

**Comment by wumo** [comment]
It seems the my socks5 proxy doesn't work well with the ftp..

**Comment by the-shank** [comment]
@wumo were you able to find a workaround for this?
