### ISSUE TITLE
Luarocks not working

### ISSUE THREAD

**Issue by Fronkan** [lukesampson/scoop#2711]
## Error
After installing the package luarocks seems to not work. Running the command gives the respons:
'"\lua"' is not recognized as an internal or external command,
operable program or batch file.

## More Info on the Problem
Because the shim only calls the luarocks.bat I checked that file out and it uses a variable %LUA_DEV%.  So I solved the problem by adding a envrionment variable to my user called "LUA_DEV" with the path to  ../scoop/apps/lua/current. This solves the path problem but is a bit of a hack and when trying to install anything using the commads it seems to fail the compile phase. 

Not sure if this can be fixed from scoop side or needs to be fixed on the luaforwindows repository. Because from what I can see this variable is set on line 515 in LuaForWindows.iss in that repo. I have not tested installing it directly from repository so not really sure what the root cause of the problem is

**Comment by mrtnpwn** [comment]
I'm having the same problem here. :cry:

**Comment by h404bi** [comment]
@mrtnpwn Doesn't it fixed yet? https://github.com/lukesampson/scoop/pull/2849

**Comment by mrtnpwn** [comment]
Nope, I got the same `'"\lua"' is not recognized as an internal or external command` error everytime.

**Comment by niheaven** [comment]
Please check env vars after install `lua-for-windows`, in my pc, it works.

![default](https://user-images.githubusercontent.com/5832170/53325980-7323b480-391f-11e9-8da2-a62cf417a632.png)

**Comment by hulucc** [comment]
Just restart your pc. The environment variable "LUA_DEV" need the take effect after log out.

**Comment by Fronkan** [comment]
I am not sure about the status of this bug anymore. I tried using it for a game-jam and then forgot about it. Anyone who have tried the suggested solutions and can verify it works?

**Comment by hulucc** [comment]
@Fronkan It works. you can close it.
