### ISSUE TITLE
Install glslang failed

### ISSUE THREAD

**Issue by wumo** [lukesampson/scoop#2716]
```
>scoop install glslang
Installing 'glslang' (Overload400-PrecQual.1817) [64bit]
The remote server returned an error: (401) Unauthorized.
URL https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Windows/glslangValidator.exe is not valid
```
recommand downloading from [git release](https://github.com/KhronosGroup/glslang/releases/latest)

**Comment by r15ch13** [comment]
Which version should be used?
https://github.com/KhronosGroup/glslang/releases/tag/master-tot
or
https://github.com/KhronosGroup/glslang/releases/tag/7.9.2888

**Comment by wumo** [comment]
[master-tot release](https://github.com/KhronosGroup/glslang/releases/tag/master-tot) is recommanded in the README.md of the official github.

**Comment by r15ch13** [comment]
`Those binaries are automatically uploaded by the buildbots after successful testing and they always reflect the current top of the tree of the master branch.` this sounds like we will get hash check errors. Should it be changed to nightly?
