### ISSUE TITLE
Scoop cannot install Tesseract lower than latest version 4.0.0

### ISSUE THREAD

**Issue by AndreiH** [lukesampson/scoop#2728]
Latest Tesseract 4, does not work correctly for my project, but after it was released, now Scoop automatically installs the latest version.

When trying to install the version I need, we get this error:

`scoop install tesseract@3.05.02`

```
WARN  Given version (3.05.02) does not match manifest (4.0.0.20181030)
WARN  Attempting to generate manifest for 'tesseract' (3.05.02)
Autoupdating tesseract
Downloading tesseract-ocr-w32-setup-v3.05.02.exe to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v3.05.02.exe#/dl.7z is not valid
Could not find hash!
Could not install tesseract@3.05.02
```

It seems that the download URL is formed in such a way that you cannot go back to lower versions of Tesseract.
Lower versions do not have ` 32-bit and 64-bit ` added to their setup files names: https://digi.bib.uni-mannheim.de/tesseract/

Thanks in advance !

**Comment by AndreiH** [comment]
I guess the `\scoop\buckets\versions\tesseract4.json` needs to be correctly updated.

**Comment by rasa** [comment]
Fixed in 
https://github.com/scoopinstaller/versions/commit/31c956c3a94d14ea8dc873ba2306f3cfa0f51b8b
Please run:
```
scoop uninstall tesseract
scoop bucket add versions
scoop install tesseract3
```

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/93564fe7083cf3c23593af57fd461980ff0f6ff5

**Comment by r15ch13** [comment]
`TESSDATA_PREFIX` got fixed with https://github.com/lukesampson/scoop/commit/93564fe7083cf3c23593af57fd461980ff0f6ff5

**Comment by AndreiH** [comment]
Thank you very much for the quick response and work ! 👍
