### ISSUE TITLE
'scoop uninstall cygwin' doesn't delete Start Menu entry.

### ISSUE THREAD

**Issue by crocket** [lukesampson/scoop#2730]
I have to delete the following file manually.

```
C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Cygwin\Cygwin64 Terminal.lnk
```

**Comment by r15ch13** [comment]
That's because the cygwin setup creates it. Scoop has nothing to do with Shortcuts outside of `C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps`

**Comment by crocket** [comment]
Can scoop delete it?

**Comment by r15ch13** [comment]
No, because scoop has no information about this Shortcut. You have to remove it manually.

**Comment by crocket** [comment]
Given that it is installed in a fixed path, I think scoop can be programmed to remove it at the fixed path.

**Comment by r15ch13** [comment]
Should be fixed and improved now.

**Comment by crocket** [comment]
I confirmed that this issue has been fixed with the following commands.

```
scoop update
scoop install cygwin
```
