### ISSUE TITLE
Create formal, public and documented module

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2733]
While writing manifests, you could use some scoop's internal functions inside install scripts (`pre_install`, `post_install`, `script`), but they are not documented, use poor parameters, which are booleans (not switches), and you need to go to github, search for name, through it's scoop's code almost everytime to look for parameters, which then look like `extract_7zip $file $path $false` instead of more intuitive way `Scoop-Extract7zip $file $path -Recurse` (with positional parameters, otherwise, some `-Archive $file -Destination $path -Recurse`).

There should be some wrapper module, which would be properly documented (wiki, and ps1 files). All of that functions will only be oneliners with param block and some defaults

or

rewrite scoop's files to match single style (It's code is pretty mess with naming).

Some functions does not return values from functions, some have. Newly added functions are Pascal-Case named, while od ones are named using snake_case.
[Pascal case in lots of snake_cases](https://github.com/lukesampson/scoop/blob/7d35cc1c2737e8b92a0cb1ae7a1caea56a19f910/lib/core.ps1#L30), [Function with return](https://github.com/lukesampson/scoop/blob/7d35cc1c2737e8b92a0cb1ae7a1caea56a19f910/lib/core.ps1#L296-L298), [Function without return](https://github.com/lukesampson/scoop/blob/7d35cc1c2737e8b92a0cb1ae7a1caea56a19f910/lib/core.ps1#L196-L198)

Example:

```ps1
<#
.SYNOPSIS
SOME DESCRIPTION
...
#>
Scoop-Extract7zip {
    param(
        [Parameter(ValueFromPipeline..., Mandatory, ...)]
        [ValidateScript(...)]
        [String] $Archive = $fname
        [Parameter...]
        [ValidateScript(...)]
        [String] $Destination = $dir
        [Switch] Recurse
    )

    process {
        extract_7zip $Archive $Destination $Recurse
    }
}

Scoop-ExtractMsi {...}
```

Also. 
Why is `msi` block Deprecated? Sure, you can extract MSI, but there are some applications, which needs to be installed (initializing some drivers, services, ...) and marking it as deprecated is wrong. It's forcing maintainers to think that support of msiexec will be removed and manifest will be broken. And intead of using supported json properties `file`, `args` you need to write script block with custom call to msiexec.

**Comment by r15ch13** [comment]
Instead of writing wrappers, it would be better to refactor Scoop to use Pascal case. Since it's the preferred style for PowerShell. This will be *a lot of work*, but some changes that have to be added (exception handling and proper state handling for failed app installations) require a complete rewrite anyway.

Adding wrappers might be useful for writing tests and transition to the refactored code.

**Comment by r15ch13** [comment]
Regarding the `msi` property, do you have an example where extracting it isn't enough?

**Comment by Ash258** [comment]
I was just curious. But for example. **[iCue](https://github.com/Ash258/scoop-Ash258/blob/master/TODO/iCue.json)**. it's Corsair's utitlity for peripherals, which is need to be installed due to some services, hooks and registry configurations for proper functionality.

**Comment by r15ch13** [comment]
Guidelines: https://poshcode.gitbooks.io/powershell-practice-and-style/content/

**Comment by linsui** [comment]
Here is example. wireguard must be installed because it need to install wintun.
