### ISSUE TITLE
scoop uninstall scoop shouldn't remove persist data

### ISSUE THREAD

**Issue by ishanarora** [lukesampson/scoop#2746]
Uninstalling scoop deletes all persist data. This is not intuitive given that uninstalling an app won't delete the app's persist data. As you can probably guess, I just lost all all my persist data in an attempt to install scoop from scratch. 🤦‍♂️

**Comment by John3** [comment]
maybe a option would be have "remove" just for delete the app and "uninstall" for delete everything?

**Comment by r15ch13** [comment]
@Ash258 yes, or it just deletes `apps`, `buckets`, `cache`, `modules` and `shims` leaving the `persist` directory.

**Comment by Ash258** [comment]
So basically adding, `purge` parameter, and running `if ($purge) {Get-ChildItem $scoopdir -Exclude 'persist' | Remove-Item -Recurse -Force}` same for global.

**Comment by r15ch13** [comment]
Yep 👍
