### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by jlchoike** [lukesampson/scoop#2770]
```
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      035f888393889077e5396535722d95016d8e4168deb4a0e623ede9037eb044a7
```

**Comment by rasa** [comment]
d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a is the correct hash.

**Comment by jlchoike** [comment]
@rasa I am still seeing this error. Can you think of any reason why this hash check would fail? I am able to install other scoop packages without any problem.

**Comment by rasa** [comment]
No idea, sorry. 
http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz still hashes to d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
