### ISSUE TITLE
openjdk8 is missing

### ISSUE THREAD

**Issue by Lexanius** [lukesampson/scoop#2771]
Hi,

after `oraclejdk-lts` is changed to java 11, i try to install `openjdk8` but it is missing. Maybe it was the `openjdk` package before.

`scoop search jdk` return
```
    openjdk (11.0.1-13)
    openjdk10 (10.0.2-13)
    openjdk11 (11.0.1-13)
    openjdk12 (12-19-ea)
    openjdk7-unofficial (7u80-b32)
    openjdk9 (9.0.4)
```

Will there be a openjdk8 package?

Lexanius

**Comment by h404bi** [comment]
There will no longer have official openjdk8 build, so you may try [`ojdkbuild8`](https://github.com/ojdkbuild/ojdkbuild).

**Comment by Playacem** [comment]
I personally can recommend `adopt8-hotspot`. It is a release build by AdoptOpenJdk.net

**Comment by deeptha-code-breaker** [comment]
> I personally can recommend `adopt8-hotspot`. It is a release build by AdoptOpenJdk.net

AdoptOpenJDK is now Temurin
