### ISSUE TITLE
[Feature Request] scoop fix #for recreating directory junctions 

### ISSUE THREAD

**Issue by Retia-Adolf** [lukesampson/scoop#2772]
Background: I want to use scoop as a portable apps manager. And when copied `scoop` directory, included junctions lost, but there left empty directories instead, nothing else broken.

Intention: So I want a scoop command as described in title, which

1. checks if `current` alias dir is linked
2. checks if every app's persist dirs (as written in their respective `manifest.json` file) is linked
3. links found broken junction points.

Note:
- This's not a problem with scoop, but it's natural and easy for scoop to batch recreate its own junctions, I don't know if there would be a convenient way to solve this problem, without adding feature to scoop.
- Reinstalling apps effectively solves this problem, but I don't think it's a real fix for this problem, in such cases: a lot of apps installed, only a slow Internet connection available; several proxy apps can hardly be downloaded in my area because of censorship.

**Comment by moosad** [comment]
Could you please check if `scoop reset` meets your intentions ? 
I'm pretty sure that it re-links the `current` dir, but unsure about the rest.

**Comment by Retia-Adolf** [comment]
@moosad just repeat a worse much useless one without noticing this...😇
