### ISSUE TITLE
rustup uses msvc build on windows by default

### ISSUE THREAD

**Issue by hanabi1224** [lukesampson/scoop#2775]
Is there any particular reason to force using stable-gnu instead of the default stable(msvc) channel?

**Comment by Calinou** [comment]
Using Rust with the MSVC ABI requires an installation of the Visual C++ Build Tools, which are not available in Scoop. Not only they are quite large (at least 5 GB installed), I'm not sure if it's possible to install those in an unattended manner without administrator privileges.

**Comment by hanabi1224** [comment]
@Calinou  My intuition is that 'scoop install vcredist' will setup all build dependencies on windows, but need to try out

**Comment by Calinou** [comment]
@hanabi1224 `vcredist` only installs the Visual C++ redistributable, not the build tools such as `cl` and `link` which rustc needs to link against the MSVC ABI.

**Comment by hanabi1224** [comment]
@Calinou  Then is it possible to create a rustup-msvc.json?  I use scoop in appveyor ci to install rustup using Visual Studio 2017 image where VC++ build tools are pre-installed. 

https://ci.appveyor.com/project/hanabi1224/rust-radix-trie/builds/20449922/job/h33hr318ca8ar4ll

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2775
