### ISSUE TITLE
Autoupdate and forced update doesn't work

### ISSUE THREAD

**Issue by krokofant** [lukesampson/scoop#2777]
App is installed via a gist and it's manifest is like the following:
```json
{
  "version": "1.3",
  "url": "https://gist.github.com/***/master.zip",
  "extract_dir": "a-master",
  "psmodule": {
    "name": "MyShell"
  },
  "checkver": {
    "url": "https://gist.github.com/krokofant/a",
    "re": "<span class=\"pl-s\"><span class=\"pl-pds\">&quot;</span>version<span class=\"pl-pds\">&quot;</span></span>: <span class=\"pl-s\"><span class=\"pl-pds\">&quot;</span>([\\d.]+)<span class=\"pl-pds\">&quot;</span></span>"
  },
  "autoupdate": {
    "url": "https://gist.github.com/krokofant/a/archive/master.zip"
  }
}
```

Running scoop status won't show an update even though it has autoupdate and checkver fields, and scoop update mymodule won't either.

The only thing that works for checking for a new update is calling:
```powershell
.\checkver.ps1 -dir C:\Users\***\scoop\apps\myshell\current
```
which outputs
```powershell
manifest: 1.3 (scoop version is 1.2) autoupdate available
myshell: 1.3 (scoop version is 1.2) autoupdate available
```

Have I misinterpreted how autoupdate is supposed to work?

Running `scoop update myshell -f` outputs:
```powershell
myshell: 1.2 -> 1.2
Updating one outdated app:
WARN  Bucket '' not installed. Add it with 'scoop bucket add ' or 'scoop bucket add  <repo>'.
Couldn't find manifest for 'myshell'.
```

**Comment by Ash258** [comment]
That's not how it works. 
`scoop update <app>` is updating only updated manifests. If you want to update your manifest you need to clone your gist manifest and update it using something like: `.\checkver.ps1 -dir PATH\To\Your\Clone -u; git commit -m "Update manifest to some verstion" --all; git push` then you can run `scoo update; scoop update *`
