### ISSUE TITLE
mozjpeg bin source offline

### ISSUE THREAD

**Issue by brandon93s** [lukesampson/scoop#2780]
Our source for [mozjpeg](https://github.com/lukesampson/scoop/blob/master/bucket/mozjpeg.json) binaries is offline:

https://github.com/lukesampson/scoop/blob/f4af32ad460e00a8af98915468456582d39fa47a/bucket/mozjpeg.json#L20-L23

```sh
$ curl mozjpeg.codelove.de
curl: (7) Failed to connect to mozjpeg.codelove.de port 80: Connection refused
```

We'll need to find a new binary source and/or consider adding it to [binary-mirror](https://github.com/scoopinstaller/binary-mirror).

**Comment by moosad** [comment]
Why don't we simply use `"checkver": "github"`?

**Comment by r15ch13** [comment]
Was able to compile it, but I don't know if the result matches anything from `mozjpeg_3.1_x86.zip`. Maybe I can provide builds via AppVeyor or something. But C and C++ are definitely not my thing 😁

![image](https://user-images.githubusercontent.com/432127/48706367-55e29a00-ebfc-11e8-9810-39f6b418dad6.png)

**Comment by moosad** [comment]
What about this? :)
https://github.com/garyzyg/mozjpeg-windows
