### ISSUE TITLE
Empty bucket name in bucket suggestion

### ISSUE THREAD

**Issue by gheoan** [lukesampson/scoop#2787]
I have noticed this minor issue:
```
~ $ scoop install texmaker
Updating Scoop...
Scoop was updated successfully!
WARN  Bucket '' not installed. Add it with 'scoop bucket add ' or 'scoop bucket add  <repo>'.
Couldn't find manifest for 'texmaker'.
~ $ scoop bucket add extras
Checking repo... ok
The extras bucket was added successfully.
~ $ scoop install texmaker
Installing 'texmaker' (5.0.3) [64bit]
...
```
Notice how when attempting to install an app that does not exist in the default bucket but is present in the extras bucket there is a suggestion to "add" the bucket. However in this suggestion the bucket name is an empty string. Here is my `$PSVersionTable` output:
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by gheoan** [comment]
I am experiencing this issue on 2 machines. I will try to debug it.

**Comment by rasa** [comment]
Please reopen if you can reproduce it. Thx 4 doing the research!

**Comment by gheoan** [comment]
These are the commands that reproduce the issue for me:
1. `scoop bucket rm extras`
2. `scoop install texmarker`

**Comment by Ash258** [comment]
Could reproduce with games bucket, which i never add as bucket.

![proof](https://i.imgur.com/GYudrmc.png)

![NO](https://i.imgur.com/4D62X9W.png)
