### ISSUE TITLE
qbittorrent 404 error

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop#2790]
Can't update/install qbittorrent:

```
>scoop install qbittorrent
Installing 'qbittorrent' (4.1.4) [64bit]
The remote server returned an error: (404) Not Found.
URL https://downloads.sourceforge.net/project/qbittorrent/qbittorrent-win32/qbittorrent-4.1.4/qbittorrent_4.1.4_x64_setup.exe#/dl.7z is not valid
```

**Comment by Ash258** [comment]
https://github.com/qbittorrent/qBittorrent/issues/9872
https://github.com/qbittorrent/qBittorrent/issues/9865

**Comment by r15ch13** [comment]
Update service downgraded it to 4.1.3 https://github.com/lukesampson/scoop-extras/commit/198828af98d876d7870d069ba294335ccd27d5a8
Should work again after running `scoop update`

**Comment by habamax** [comment]
thx!
