### ISSUE TITLE
slow execution ?

### ISSUE THREAD

**Issue by jorgheymans** [lukesampson/scoop#2792]
Just started using scoop a couple of days ago, thanks for this great tool ! 

I was wondering if the general slowness that i experience on my system can be remedied. For example, `scoop which git` takes about 6-7 seconds to execute. Scoop checkup did not report any problems, nor did i find any previous issues reporting this.

**Comment by JanPokorny** [comment]
There may be too many items on your PATH. Try removing some old stuff, I recommend using Rapid Environment Editor.

**Comment by jorgheymans** [comment]
it's not just the `which` command though, `scoop config proxy` for example is equally slow.

**Comment by Ash258** [comment]
`scoop config proxy` is only reading from file on drive C: (`~/.scoop`). 

How long does it take to execute this command?? `Get-Content "$env:USERPROFILE/.scoop" -Raw | ConvertFrom-Json`

**Comment by jorgheymans** [comment]
> How long does it take to execute this command?? Get-Content "$env:USERPROFILE/.scoop" -Raw | ConvertFrom-Json

couple of milliseconds, getting the output instantly.

**Comment by Ash258** [comment]
And this?

```powershell
function hashtable($obj) {
    $h = @{ }
    $obj.psobject.properties | ForEach-Object {
        $h[$_.name] = hashtable_val $_.value
    }
    return $h
}

function hashtable_val($obj) {
    if($null -eq $obj) { return $null }
    if($obj -is [array]) {
        $arr = @()
        $obj | ForEach-Object {
            $val = hashtable_val $_
            if($val -is [array]) {
                $arr += ,@($val)
            } else {
                $arr += $val
            }
        }
        return ,$arr
    }
    if($obj.gettype().name -eq 'pscustomobject') { # -is is unreliable
        return hashtable $obj
    }
    if($obj -eq [bool]::TrueString -or $obj -eq [bool]::FalseString) {
        $obj = [System.Convert]::ToBoolean($obj)
    }
    return $obj # assume primitive
}

hashtable (Get-Content "$env:USERPROFILE/.scoop" -Raw | ConvertFrom-Json)
```

**Comment by jorgheymans** [comment]
equally fast.

**Comment by Ash258** [comment]
Do you use any specific shell or console?

**Comment by jorgheymans** [comment]
standard windows cmd, but i do have clink activated... could that cause issues ?

**Comment by Calinou** [comment]
> standard windows cmd, but i do have clink activated... could that cause issues ?

I use Scoop with Clink activated, it takes less than a second to react to commands.

**Comment by jorgheymans** [comment]
is there anything i can do here, happy to run a diagnostic build of scoop to dump out some timings or whatever :)

**Comment by Ash258** [comment]
Run scoops command from normal powershell window. Run `scoop config proxy` from pure powershell window and you will see normal behaviour. It's problem on your end. Since @Calinou mention that Clink thing I suppose it's problem with it.

**Comment by jorgheymans** [comment]
So i started a normal dos command prompt without clink, it's still slow.

**Comment by Ash258** [comment]
I tested multiple environments, multiple console hosts, etc and nothing tooke more than 3 seconds.

- You mentioned proxy. Are you under some specific confirutaion?
- scoop.cmd only call powershell with specific command.
    - How long does it take powershell to appear when you run it from start menu / Run / Win+x?

Tested cases
- Windows 7 && Windows 8.1 && Windows 10 All pros and enterprises
    - cmder
    - conemu
    - pure powershell
    - pure cmd
    - pwsh
    - hyperterminal
    - Docker powershell:windowsservercore-1803

**Comment by jorgheymans** [comment]
This is an enterprise environment, McAfee enabled. Could it be the
virusscanner kicking in each time? Note I don't have this slow down with
any other app...

Op do 22 nov. 2018 16:43 schreef Jakub Čábera <notifications@github.com>:

**Comment by Ash258** [comment]
You need to experiment. Disable AV, Add exclusions, test other computers, installations, ...

Ask your IT administrator for help, they should know, what and how they confifured your machine.

**Comment by rasa** [comment]
Gonna close as it sounds system specific. Please reopen if needed. Thx.
