### ISSUE TITLE
How to skip the command line to update scoop

### ISSUE THREAD

**Issue by lcyan** [lukesampson/scoop#2795]
How to skip the command line to update scoop. Instead, it is updated with the git gui tool, because my command line update always reports an error. In fact, scoop has been updated to the latest through gui

![1](https://user-images.githubusercontent.com/3824082/48876316-60897300-ee38-11e8-971a-bced60df667a.png)
![2](https://user-images.githubusercontent.com/3824082/48876320-641cfa00-ee38-11e8-99d3-e4aa5a308138.png)
![3](https://user-images.githubusercontent.com/3824082/48876350-8adb3080-ee38-11e8-95bc-125468754ec6.png)

**Comment by r15ch13** [comment]
You can change `lastupdate` in `%USERPROFILE%\.scoop` to something in the far future as a workaround.
But I would recommend fixing the actual issue 😁
Does running `git pull` on `~\scoop\apps\scoop\current\` from the console show the same errors?

**Comment by lcyan** [comment]
> You can change `lastupdate` in `%USERPROFILE%\.scoop` to something in the far future as a workaround.
> But I would recommend fixing the actual issue 
> Does running `git pull` on `~\scoop\apps\scoop\current\` from the console show the same errors?

Yes。

![20181123094420](https://user-images.githubusercontent.com/3824082/48925993-b7f51500-ef04-11e8-90c1-9e546fc8fa17.png)
