### ISSUE TITLE
Unable to install basic tools (i.e. coreutils, openssh)

### ISSUE THREAD

**Issue by caiorg** [lukesampson/scoop#280]
Hey there!

I'm new to Scoop and I was following [this tutorial](http://outcoldman.com/en/archive/2014/07/20/scoop/) on installing it with other tools.

When I reached the following line to *Install core utils and tools*
```
scoop install 7zip coreutils curl git grep openssh sed wget vim grep
```
I got this message

![image](https://cloud.githubusercontent.com/assets/2515035/6131708/f5b5e8e0-b134-11e4-8857-1c9856bc53c4.png)

So I've tryed installing them one by one, being able to successfully install only `7zip`, `curl` and `git`. The others I got similar **hash check failed** messages.

I can't figure out if I did something wrong or if it's some issue that must be solved.

Thx in advance.

**Comment by lukesampson** [comment]
Thanks for reporting this—it looks like Source Forge have changed the way their download URLs work. These apps should install properly now, once you `scoop uninstall [app]` the ones that failed.

**Comment by caiorg** [comment]
@lukesampson Thanks for the quick fix!
Everything is installed and working like a charm!
