### ISSUE TITLE
The system cannot find the file / path specified when uninstalling a program

### ISSUE THREAD

**Issue by lewisgauss** [lukesampson/scoop#2801]
You may refer to the image below. When installing, it seems fine, I am also able to update the program, however when I am uninstalling something, the error occurs. 

![image](https://user-images.githubusercontent.com/8966669/48944535-1d2b2380-ef62-11e8-870b-939e44178776.png)

**Comment by hsiktas** [comment]
I have the same issue and like you have a user profile with my full name --> there is a space in the path. Could this be the cause of this issue?

**Comment by i-give-up** [comment]
I have a space in my user profile and I'm also seeing the same issue.

This line could be the cause: https://github.com/lukesampson/scoop/blob/b9b48182b4d921aa92e9b3e53ab2d2c376d467d7/lib/install.ps1#L896

**Comment by Ash258** [comment]
Yeah that is reason

![image](https://user-images.githubusercontent.com/13260377/60084100-33d36c00-9737-11e9-84a0-b2f23130f9c0.png)
