### ISSUE TITLE
lame@3.100: hash check failed

### ISSUE THREAD

**Issue by muhlpachr** [lukesampson/scoop#2807]
Installing 'lame' (3.100) [64bit]
Checking hash of lame3.100-64.zip ... ERROR Hash check failed!
App:         lame
URL:         http://www.rarewares.org/files/mp3/lame3.100-64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    8b32ef66beed351b6fbfc73a36f56bf5737ab3b01f40399cdfb02b9d8e86def2
Actual:      c9cddf1650fff0ebe0ba79de794b1fa9b334f43f08e2d365b7a158941ad78fa7

**Comment by rasa** [comment]
Fixed in 
https://github.com/lukesampson/scoop/commit/0a5a6952d5d0d74abe9045d7200218fc3cf02252
