### ISSUE TITLE
Curl SSL certificate problem

### ISSUE THREAD

**Issue by caiorg** [lukesampson/scoop#281]
Hey @lukesampson, sorry if this has been already solved, but I couldn't find any issues (open and closed) here.

I just installed `curl`, went to test it and got the following message:

![image](https://cloud.githubusercontent.com/assets/2515035/6146979/cc54647c-b1d9-11e4-9f34-7fdef303aa07.png)

It feels weird, since on the Scoop demo video you're saying it takes care of the certificates. Also the url showing up on the demo video when installing curl is different than mine (see highlight on the above image).

**Comment by lukesampson** [comment]
Sorry to take so long. I just checked this out using the same steps in your screenshot and I didn't get that error.

There is a CA bundle included when you install curl with scoop, so it should in theory work. Maybe there was a certificate revocation check or something that failed.

Could you try running with the `-v` switch, e.g. `curl -v https://get.scoop.sh`—that might give some more info. Also if there's a possibility that there might be another version of curl installed somewhere on your system you could try running `scoop which curl` to make sure it's pointing to the right one.

**Comment by caiorg** [comment]
Hey @lukesampson ! Certainly you have many other things to look over, so don't be sorry. hehehe

Turns out I had another curl.exe "hidden" inside another directory. As couldn't not find any way to uninstall it, I just renamed it, installed Scoop's version and voilá!

Now I have to excuse for the mess... Sorry!

**Comment by lukesampson** [comment]
No problem—glad you worked it out :)
