### ISSUE TITLE
Can Scoop itself be installed 'globally'?

### ISSUE THREAD

**Issue by vidarkongsli** [lukesampson/scoop#282]
Is there an easy way to install Scoop itself in /ProgramData instead of  ~/AppData/Local?

**Comment by damnhandy** [comment]
See issue #249 

This will allow you to control where Scoop gets installed.

**Comment by vidarkongsli** [comment]
Thanks. I'll give it a go.

**Comment by deevus** [comment]
@vidarkongsli How did you go?
