### ISSUE TITLE
Add option to install all languages for Tesseract

### ISSUE THREAD

**Issue by AndreiH** [lukesampson/scoop#2820]
Homebrew for Mac has the option to install all Traindata languages  for Tesseract:
`brew install tesseract --with-all-languages --with-training-tools --with-serial-num-pack`
See link: https://formulae.brew.sh/formula/tesseract

Can Scoop users have the same kind of joy ? :D 
Thank you !

**Comment by r15ch13** [comment]
The tesseract build from the UB-Mannheim already contains all building tools, so I just added an extra package that installs all languages and the `snum.traindata`.

It will just repurpose the `TESSDATA_PREFIX` to point to `~\scoop\apps\tesseract-languages\current`. No copying or merging of the `tessdata` directory necessary.

**Comment by AndreiH** [comment]
Thank you for the support ! This works great ! 
`scoop install tesseract-languages`
