### ISSUE TITLE
[Request] Add Glances

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop#2831]
> **Glances** is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface.

https://github.com/nicolargo/glances

---

Apparently, [installing it on Windows](https://github.com/nicolargo/glances#windows) is as simple as `pip install glances`. If it's this simple, can it be added to Scoop's main bucket? I prefer installing my packages from Scoop rather than from multiple different package managers.

![glances](https://user-images.githubusercontent.com/10495562/49342728-cb069400-f62c-11e8-9a37-0676ccdfa1bf.PNG)

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2831
