### ISSUE TITLE
qemu@3.1.0-rc3: hash check failed

### ISSUE THREAD

**Issue by jshifrin25** [lukesampson/scoop#2840]
qemu: 3.1.0-rc3 -> 3.1.0-rc3
Updating one outdated app:
Updating 'qemu' (3.1.0-rc3 -> 3.1.0-rc3)
Uninstalling 'qemu' (3.1.0-rc3)
Installing 'qemu' (3.1.0-rc3) [64bit]
qemu-w64-setup-20181128.exe (100.4 MB) [===========================================] 100%
Checking hash of qemu-w64-setup-20181128.exe ... ERROR Hash check failed!
App:         qemu
URL:         https://qemu.weilnetz.de/w64/qemu-w64-setup-20181128.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    7f58c2486ca9d6ab464e9304861b75208031c3e4acc250798fc0fe5312d7e0f2
Actual:      c2286dc73fc1f7f0f274725ab73e713681f7b9eb049e654995dc0879262a409f

**Comment by Ash258** [comment]
Will be fixed with #2838
