### ISSUE TITLE
Auto Update functionality

### ISSUE THREAD

**Issue by sandeepb1** [lukesampson/scoop#2841]
I'm trying to write a manifest for an app but the auto update documentation isn't clear on a couple of things

1) I'm using a JSON API based URL, I have the jsonpath set but can I also use regex to extract the version after the jsonpath has selected the version?

2) Is there any tool available to check if my autoupdate criteria is correct? A way to tell me if scoop has found an update

3) When I run `scoop update` I can see it has retrieved the updated manifest but it doesn't acknowledge the update unless i run `scoop update APP` - is this intended functionality? I assumed the `scoop update` will auto update my app for me as well.

**Comment by sandeepb1** [comment]
1. OK so I'll have to try a different way rather than this?

```
"checkver": {
        "url": "URL TO JSON ARRAY",
        "jp": "$[0].tag_name",
        "re": "v([\\d.]+)"
    }
```

2. OK I'll give that a shot

3. So scoop doesn't work like `brew` where I can run `brew upgrade` or `brew cask upgrade` to upgrade all apps that could be upgraded?

**Comment by Ash258** [comment]
1. Yes. JP and Regex cannot be combined now.
3. Again as in help. Run `scoop update *` for upgrading all applications

**Comment by sandeepb1** [comment]
thanks for point 2, I must've missed that. That solves it for me.

**Comment by r15ch13** [comment]
Jsonpath and regex can be combinded. See https://github.com/lukesampson/scoop/pull/1709

**Comment by Ash258** [comment]
Oh. Sorry for mystification. When i was testing something similar I can't make it working.
