### ISSUE TITLE
couldn't find manifest for ssh

### ISSUE THREAD

**Issue by valtido** [lukesampson/scoop#285]
Can't install SSH

```
~ $ scoop install ssh
couldn't find manifest for ssh
~ $
```

**Comment by ntwb** [comment]
There is no manifest named `ssh`, you'll most likely be looking for `openssh`.

https://github.com/lukesampson/scoop/tree/master/bucket

**Comment by deevus** [comment]
@valtido Use `scoop install openssh` instead.

**Comment by valtido** [comment]
Yes... Sorry my bad, was just following one of the Videos on the website and I came across it...

I figured it out eventually :)

**Comment by deevus** [comment]
No problem!
