### ISSUE TITLE
Validator incorectly validate URI

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2868]
When i was writing manifest for [GameSave Manager](https://github.com/Ash258/scoop-Ash258/blob/master/TODO/GameSaveManager.json) I experienced scoop validator falsly make `https://www.gamesave-manager.com/?s=download&guid={D5312F19-F659-40E1-869A-1C991BB0E95B}&a=dl#/cosi.zip` as error when running tests (generic tests from extras bucket).

Installing (powershell 5, 6.1.1) and downloading via browser work good, but test failed with: 

![Error](https://i.imgur.com/ESaVPi6.png)

![Proof](https://i.imgur.com/1zteDF0.png)

From my testing problems are curly brackets.

**Comment by r15ch13** [comment]
Use URL encoded string:
{ = %7B
} = %7D
