### ISSUE TITLE
It is hard to install JDK

### ISSUE THREAD

**Issue by nick318** [lukesampson/scoop#2875]
I am as a new user of scoop just wanted to install oracle jdk, so I tried:
`scoop install oraclejdk11`
And got:
`Couldn't find manifest for 'openjdk11'.`
And only after looking through bunch of issues I understood what I need to do:
```
scoop bucket add java
scoop install oraclejdk11
```

Can we somehow let user know how to install JDK?

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/wiki/Java
