### ISSUE TITLE
Use Windows binary of openssl over mingw binaries

### ISSUE THREAD

**Issue by r0mflip** [lukesampson/scoop#2877]
Currently a mingw version of openssl and by default it checks for configuration files in `/usr/share/`. When openssl is ran programatically (like in https://www.npmjs.com/package/pem) we might run into "path format" issues.

Instead use a windows binary (https://slproweb.com/products/Win32OpenSSL.html)

**Comment by rasa** [comment]
https://github.com/lukesampson/scoop/blob/master/bucket/openssl-slp.json

**Comment by r0mflip** [comment]
Sorry, thanks.

**Comment by rasa** [comment]
If openssl has issues, perhaps we should rename openssl-slp.json to openssl.json, and rename openssl.json to openssl-mingw.json?

**Comment by r0mflip** [comment]
mingw version of openssl is using UNIX pathnames `/usr/bin/...` and fails immediately (which is a bumer for starters and packages) but the slp version uses the env variable. IDK but the mingw version has any such env features, it's not even much useful in WSL too.

Renaming might break stuff for old users but the slp version is the one everyone should be using.

**Comment by rasa** [comment]
If no one disagrees, I think we should make the switch. I only use the SLP version.

**Comment by r0mflip** [comment]
Can I make a PR then?

**Comment by rasa** [comment]
Sure, thanks!
