### ISSUE TITLE
%MSYS2_ROOT% environment variable for msys2 package and persistent /home directory

### ISSUE THREAD

**Issue by indrakaw** [lukesampson/scoop#2884]
Same as `%CMDER_ROOT%`, `%MSYS2_ROOT%` is pointing the root of MSYS2. This will help lot of works.

**Comment by r15ch13** [comment]
You mean adding `MSYS2_ROOT` to [msys2.json](https://github.com/lukesampson/scoop/blob/master/bucket/msys2.json)?

```json
    "env_set": {
        "MSYS2_ROOT": "$dir"
    },
```

**Comment by indrakaw** [comment]
Yes.

**Comment by indrakaw** [comment]
Updated: request persistent directory for `/home`. Most of user individual config files are there.

**Comment by indrakaw** [comment]
Help. Today we are having msys2 update. Please consider confirm this issue.
