### ISSUE TITLE
Can't shim 'dig.exe': File doesn't exist.

### ISSUE THREAD

**Issue by bunam** [lukesampson/scoop#2888]
```
system32 $ scoop install dig
Installing 'dig' (9.13.5) [64bit]
Loading BIND9.13.5.x64.zip from cache
Checking hash of BIND9.13.5.x64.zip ... ok.
Extracting BIND9.13.5.x64.zip ... done.
Linking ~\scoop\apps\dig\current => ~\scoop\apps\dig\9.13.5
Creating shim for 'dig'.
Can't shim 'dig.exe': File doesn't exist.
```
i have extracted the archive by hand and no dig.exe in it

**Comment by r15ch13** [comment]
It seems they forget to bundle `dig.exe` with this release. `dig.html` is available.
Try installing the previous version via `scoop install dig@9.13.4`

**Comment by bunam** [comment]
it's ok thanks
you should remove 9.13.5 version ?

**Comment by bunam** [comment]
you didn't check the install process before adding a new version ?

**Comment by r15ch13** [comment]
Nope, that is not implemented.
See:
https://github.com/lukesampson/scoop/blob/master/bin/checkver.ps1
https://github.com/lukesampson/scoop/blob/master/bin/auto-pr.ps1
https://github.com/r15ch13/Excavator/blob/master/excavate.sh

**Comment by Ash258** [comment]
Could be implemented as CI pipeline part instead of touching binaries, which could break user isntallation. (#2667; https://github.com/Ash258/GenericBucket/blob/8cc8e65355f895d17a6b1528be65e5010ba86db7/Scoop-Bucket.Tests.ps1#L251)

**Comment by r15ch13** [comment]
@Ash258 this has to be run before `auto-pr.ps1` stages/commits those files or else we will end up with a bunch of broken builds.

**Comment by Ash258** [comment]
Better then nothing. And now if you want to use `auto-pr` you don't need to worry about breaking your current installation of scoop.

If you run these binaries in some server / docker environment using excavator, why not, you could install anything as you want. But when you run `auto-pr` as user who want to fix specific manifest and create PR using it on his machine, he could face lots of use cases, which could block auto update process.

**Comment by Ash258** [comment]
Adding new binary for it would be nice, but don't edit auto-pr directly. Maybe some switch to it.

**Comment by r15ch13** [comment]
#2893 downgrade to stable version was added
