### ISSUE TITLE
Add SQL Developer

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop#2892]
[SQL Developer](https://www.oracle.com/database/technologies/appdev/sql-developer.html) is a proprietary software by Oracle. There's a download link [here](https://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/index.html), but it requires a log-in and to accept a license. I'm not sure if it's possible to do that with Scoop.

It would be possible to change the download URL to bypass the log-in by re-hosting it on IPFS, but it seems like it's not in Scoop's scope to do that.

I hope you're able to find a way to add it to Scoop!

**Comment by Ash258** [comment]
Accepting license is possible with `cookies.oraclelicense = 'accept-sqldev-cookie'`, but downloading, which need login is not possible.

**Comment by NatoBoram** [comment]
Oh, it's good. I've seen it was the same thing for https://github.com/Homebrew/homebrew-cask/issues/16454. Thanks for trying!

**Comment by sitiom** [comment]
- Added in https://github.com/ScoopInstaller/Extras/pull/16524
