### ISSUE TITLE
How to use scoop after reinstalling the system

### ISSUE THREAD

**Issue by jiayaoO3O** [lukesampson/scoop#2894]
If I want to reinstall the system, I should copy the `scoop` directory to a safe place, put it in the `user` directory after reinstalling, and then execute the following command?
`iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`
thanks : )

**Comment by Ash258** [comment]
You need to add system environment paths as you have right now manually, because installier will fail with `Scoop is already installed`

1. You need to Copy scoop's folder when you want it to have.
1. Add location from first step as `$env:SCOOP`
1. Append `$env:SCOOP\shims` to path
1. run `scoop reset *`

**Comment by jiayaoO3O** [comment]
thanks 👍

**Comment by xiehao** [comment]
Thanks for your help, but when I run `scoop reset *`, I got this:

``` bash
Linking Y:\Scoop\apps\7zip\current => Y:\Scoop\apps\7zip\current
Error: Version 'current' is not allowed!
```

**Comment by jiayaoO3O** [comment]
@xiehao Try to used admin powershell

**Comment by xiehao** [comment]
> @xiehao Try to used admin powershell

Actually it is run as admin.

**Comment by xiehao** [comment]
@jiayaoO3O 实际上我就是按照您的这篇文章操作的
https://jiayaoo3o.github.io/2019/03/19/%E9%87%8D%E8%A3%85%E7%B3%BB%E7%BB%9F%E5%90%8E%E5%A6%82%E4%BD%95%E6%81%A2%E5%A4%8D%E4%BD%BF%E7%94%A8scoop/

**Comment by jiayaoO3O** [comment]
那可能是scoop的app中所有软件的current文件夹变成了一个真正的文件夹,而不是一个软链接,你试试双击打开current文件夹看看里面有什么东西,如果没东西,试试把current删了,让scoop自动生成一个新的

**Comment by xiehao** [comment]
@jiayaoO3O 好使了，多谢多谢！

**Comment by lszxyz** [comment]
before i  reinstall the system，the scoop path user/A，and if i copy the file to other pc ， user/B  and scoop reset *，Is it feasible

**Comment by jiayaoO3O** [comment]
@lszxyz Yes, but even if you change your computer, the installation directory of scoop should be **C:\Users\ {your name}\scoop**

**Comment by hoyien** [comment]
It can`t solve,because some soft install need regedit.Example Web page calls app telegram。
