### ISSUE TITLE
Cleanup is not $dir aware

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#2900]
Regression after e4e76d3a32fcc33ca6a0fe6b4d3b99988e6863be 

![proof](https://i.imgur.com/skaPBbX.png)

/cc @h404bi

**Comment by Ash258** [comment]
Since `Get-ChildItem` does not return full path, but only file names. Should be enough to go with `$filepath = Resolve-Path "$dir\$file"`

https://github.com/lukesampson/scoop/blob/0029f0b29dda9d82e72e1cf53183231cd8bf79d4/libexec/scoop-cleanup.ps1#L49

**Comment by h404bi** [comment]
I see, how about `$filepath = fullpath $file`

**Comment by Ash258** [comment]
I don't know. Maybe. This was first untested idea.
Test it and you will see.

**Comment by h404bi** [comment]
I can't reproduce, since `Resolve-Path` works for me. I'll change it to `$filepath = fullpath $file`, but in PR #2897 
https://github.com/lukesampson/scoop/pull/2897/files#diff-c2a7e0e3e8869b7de54b5f172fc77009R1265

**Comment by rasa** [comment]
Should we revert https://github.com/lukesampson/scoop/commit/e4e76d3a32fcc33ca6a0fe6b4d3b99988e6863be until this is sorted out?

**Comment by h404bi** [comment]
@rasa fixed it on https://github.com/lukesampson/scoop/pull/2897/commits/e7f0977db065a24f597df6b2651504a3ac9a6c52, waiting for reviewing and merging.

**Comment by jingyu9575** [comment]
Hi, I hit this bug today. This is a potentially destructive operation; if there is a directory with that name in the current directory (`C:\Windows\System32\data` in the 3rd example), it and its contents will be deleted (`rmdir /s /q`) in my tests. 

`Resolve-Path "$dir\$file"` seems to fix it. I suggest adding an temporary fix before the rewrite, to prevent data loss.
