### ISSUE TITLE
Why was cloc downgraded from 1.80 to 1.70?

### ISSUE THREAD

**Issue by oskar** [lukesampson/scoop#2901]
See commit https://github.com/lukesampson/scoop/commit/781bc072bebbc388a83532d1dbf202e52c6719b0

**Comment by r15ch13** [comment]
1.80 is not marked as the latest release.

The following `checkver` syntax always uses the latest release.
```json
"checkver": {
        "github": "https://github.com/AlDanial/cloc"
},
```
