### ISSUE TITLE
cmake@3.13.2: hash check failed

### ISSUE THREAD

**Issue by b-tach** [lukesampson/scoop#2905]
PS C:\> scoop install cmake
Installing 'cmake' (3.13.2) [64bit]
cmake-3.13.2-win64-x64.zip (306.7 KB) [===============================================] 100%
Checking hash of cmake-3.13.2-win64-x64.zip ... ERROR Hash check failed!
App:         cmake
URL:         https://cmake.org/files/v3.13/cmake-3.13.2-win64-x64.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    6e73a41f51788be757bac547e796c33dc5fd8f6a13eef7c11620ec71812c8333
Actual:      13eccef65333cf41fc353f994410ff9788a25e76224d08bea21b0eb607eded17

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=cmake%403.13.2%3a+hash+check+failed

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
6e73a41f51788be757bac547e796c33dc5fd8f6a13eef7c11620ec71812c8333
