### ISSUE TITLE
busybox@2501-g858091c25: hash check failed

### ISSUE THREAD

**Issue by g1g1** [lukesampson/scoop#2924]
Installing 'busybox' (2501-g858091c25) [64bit]
busybox-w64-FRP-2501-g858091c25.exe (2.6 KB) [==============================================================================================================] 100%
Checking hash of busybox-w64-FRP-2501-g858091c25.exe ... ERROR Hash check failed!
App:         busybox
URL:         https://frippery.org/files/busybox/busybox-w64-FRP-2501-g858091c25.exe#/busybox.exe
First bytes: 0D 0A 0D 0A 0D 0A 0D 0A
Expected:    c4924f8ad87b94f63699544dcbedc9213f6b1ffeef4ebe86a91628d211d4cf6c
Actual:      0e843d5d560ac23bfaff245bdedbc4f8d098167b8f7ee76b396292d7487e9b57

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=busybox%402501-g858091c25%3a+hash+check+failed

**Comment by excitoon** [comment]
> First bytes: 0D 0A 0D 0A 0D 0A 0D 0A

Looks like HTML.

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
c4924f8ad87b94f63699544dcbedc9213f6b1ffeef4ebe86a91628d211d4cf6c
