### ISSUE TITLE
OpenSSH links into infinite loop

### ISSUE THREAD

**Issue by genyx** [lukesampson/scoop#2927]
OpenSSH as installed via scoop has a link directory to the users home dir. Since scoop apps are in the home dir, this becomes an infinite loop.

I noticed it while trying to Windows-Search a file. It was unable to proceed the home directory. So Windows-Search is unusable.

![scoop](https://user-images.githubusercontent.com/17216038/50455284-52ee6e00-094d-11e9-8493-3335205fbcae.PNG)

**Comment by excitoon** [comment]
Haha, looks like @rasa merged my OpenSSH manifest right into main bucket. I just spotted it. Well, I'll fix that. I did that in order OpenSSH to find `~/.ssh` folder. I guess it is better to link just `~/.ssh` skipping everything else.

**Comment by excitoon** [comment]
Second problem of my package is that I did not provide 32-bit package.

**Comment by excitoon** [comment]
This link was painful for me too. I sometimes have a horror dream of `scoop uninstall openssh` deleting my home folder.
