### ISSUE TITLE
Ruby 2.6

### ISSUE THREAD

**Issue by jordanbtucker** [lukesampson/scoop#2935]
Ruby 2.6 was recently released, but the latest version of RubyInstaller is still at 2.5. However, I don't even see Ruby 2.5 in any buckets. Is there a reason the latest version in scoop is still at 2.4, and are there any plans to update it to 2.5 or 2.6?

**Comment by jordanbtucker** [comment]
I just realized that this appears to be an issue with the automatic updating of ruby.json.

Instead of updating ruby.json with the latest version of Ruby, it's getting updated with the *most recent release* of [rubyinstaller2](https://github.com/oneclick/rubyinstaller2), which isn't always the *latest version* of Ruby.

For example, the most recent release of rubyinstaller2 is 2.4.5-1, however the latest version is 2.5.3-1.

Pinging @r15ch13 since it looks like his script is doing the updates.

**Comment by indrakaw** [comment]
I think one or two more versions of Ruby won't hurt. Check this bucket:
https://github.com/scoopinstaller/versions

Also the wiki for how to: https://github.com/lukesampson/scoop/wiki

Having MSYS2 installed is recommended. I just haven't done `ridk install` on multiple versions on Windows. Won't it hurt?

**Comment by r15ch13** [comment]
Added `ruby24` and `ruby25` with https://github.com/scoopinstaller/versions/commit/2e0c06f36cd5857ab8e5d49ca0449e5b08f6bda1

**Comment by jordanbtucker** [comment]
@r15ch13 Does this mean that Ruby 2.4 and 2.5 will never show up in the main bucket again?

The regular expression for [ruby.json](https://github.com/lukesampson/scoop/blob/267681cf70f0217613b3a8db7a5926075797a71e/bucket/ruby.json#L32) is still `/releases/tag/(?:v|RubyInstaller-)?([\\d.]+(?:-[\\d])?)`, so it seems like it will still match the first version listed rather than the latest version. This means that ruby.json might pick up the most recent release (e.g. a security patch for 2.5) rather than the latest 2.6 release.

**Comment by r15ch13** [comment]
`ruby.json` uses `github` as the `checkver` method which only uses the latest release: https://github.com/oneclick/rubyinstaller2/releases/latest
If they set a 2.4 or 2.5 version as the latest release then it would match these.
But the tags are different. The tag for version 2.4/2.5 is written in lowercase (`rubyinstaller-`) and 2.6 in PascalCase (`RubyInstaller-`).
