### ISSUE TITLE
script:mkdir doesn't work when mkdir is aliased in Powershell

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#294]
In Powershell, `mkdir` is not actually an alias. `Remove-Item alias:/mkdir` fails on my system.

Having `Set-Alias mkdir mkdir.ps1` in my profile works such that I can use the `busybox mkdir` command instead of the system command. This overrides the system `mkdir` command, and apparently the `script:mkdir` function as well.

**Comment by deevus** [comment]
I changed my alias to be locally scoped and this fixes the issue with scoop. However this isn't a solution that everyone is going to know. 

```powershell
Set-Alias mkdir mkdir.ps1 -scope local -option private
```

**Comment by lukesampson** [comment]
So any user-defined alias will override the corresponding functions you added in core.ps1?

**Comment by deevus** [comment]
That's possibly the case, although I'd need to do some more investigating. Unfortunately I won't have time this week.
