### ISSUE TITLE
Python installation fails with exit code 1603

### ISSUE THREAD

**Issue by farzadmf** [lukesampson/scoop#2947]
Hi,

I recently tried to update `python`, but I got an error, which has been reported before (the one with shim etc.). I uninstalled python, and also removed all traces of python from Control Panel, now I do this:

```
scoop cache rm python
scoop install python
```

And this is the error I get:
```
Running installer... Exit code was 1603.
Installation aborted. You might need to run 'scoop uninstall python' before trying again.
```

Can I solve this issue somehow?

**Comment by Ash258** [comment]
https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation-e

**Comment by farzadmf** [comment]
@Ash258 actually, the folder isn't there anyway! (it's removed when I do `scoop uninstall python`, which is what I need to do before trying to install the broken `python`)

Also, I'm not sure if it's important or not, but my `$env:SCOOP` is empty. I wouldn't think that's an issue here because everything else is working fine in scoop

Any ideas?

**Comment by Ash258** [comment]
I assume you tried restarting computer after that cleaning and uninstalling, so your problem should be with permissions or that substituted drive thing. Follow resolution steps from microsoft help and you should find solution.

**Comment by farzadmf** [comment]
But why was everything fine before and suddenly it stopped working?

I don't know if the information is useful or not, but I noticed this behavior:

This started to happen on my work computer, so maybe the IT department is doing something to mess it up, but this is what's happening: when I do `scoop install python`, I see the `python` folder is created, then I see it being populated with python installation files, but at some point, the files are deleted and the only remaining file is `py3.exe`, and also the `current` link isn't created inside that directory, and I see the error.

Is there logs I can check?

**Comment by Ash258** [comment]
That's correct behaviour of windows installers.

> If you click OK in the message box, the installation rolls back.

Since you are under some Enterprise environment, are you sure there is no python already installed somewhere else? Go ask your administrator for help. They should know what's happening.

**Comment by farzadmf** [comment]
Actually, there were some traces of python in Control Panel, but I removed them all, and I think my main question is: **why all of a sudden?** because everything was working before :(

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by MOZGIII** [comment]
I have this issue, please reopen

**Comment by devcraftsman** [comment]
I have this issue too, please reopen. 
Try to install bloop, which in turn requires "python" and had exactly the same 1063 error. I tried in default scoop directory as in custom, try with powershell as admin and as normal user. Always got the same error. I have updated scoop also, nothing changed.
I can install anything else (I installed git, aria2, curl and have no issue) but python.

**Comment by MOZGIII** [comment]
The same fix worked for me at the time. So, python installer might require a workaround for this to work properly.

**Comment by Ash258** [comment]
There is alredy rework of python installation, so this should not happening anymore scoopinstaller/scoop-main#6

**Comment by kincaia** [comment]
I too ran into this issue and it was all due to my own noodling. I had installed Python 3.6 on my machine manually via the official installer and when I went to install via Scoop, I would get the same obscure error. I had to formally delete the Python 3.6 installation through the same installer and when I tried the command `scoop install python36` I was back in business! Hope this helps someone else.
