### ISSUE TITLE
Node: add instructions for workaround for broken npm update mechanism

### ISSUE THREAD

**Issue by raikesy** [lukesampson/scoop#2948]
Updating npm using the standard command `npm -g install npm@latest` fails on windows and a workaround is required as outlined here: coreybutler/nvm-windows#13

For a scoop installation the directory is slightly different: C:\Users\jzrai\scoop\persist\nvm\nodejs\[version]

This is not a scoop bug but this workaround is relevant to scoop users and is not clearly documented in any official place (that I have found) so perhaps it would be sensible to add it to the notes in the manifest to prevent confusion.

**Comment by r15ch13** [comment]
Isn't npm updated via `npm -g install npm` instead of `update`?

**Comment by raikesy** [comment]
My mistake. It is `install` and to clarify, the error occurs using `install`

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by raikesy** [comment]
@rasa I've just checked and this is still an issue. By reopen, do you mean create a brand new issue?

**Comment by createdbyjurand** [comment]
I think this is more of a previous **npm** version bug than **nvm** one.

However, to update npm **delete** in `nvm/[node version]` folder (for me it is `v10.15.3`) following files:
```
C:\Users\[user name]\AppData\Roaming\nvm\[node version]\npm
C:\Users\[user name]\AppData\Roaming\nvm\[node version]\npm.cmd
C:\Users\[user name]\AppData\Roaming\nvm\[node version]\npx
C:\Users\[user name]\AppData\Roaming\nvm\[node version]\npx.cmd
```
**Rename** npm folder to npm2
```
C:\Users\[user name]\AppData\Roaming\nvm\[node version]\node_modules\npm2
```
Open any console with admin rights (or even right mouse click on vscode **shortcut**, than right mouse click on **Visual Studio Code** and hit **Run as administrator**) and type commands:
```
cd C:\Users\[user name]\AppData\Roaming\nvm\[node version]\node_modules\npm2\bin
node npm-cli.js i -g npm@latest
```
Done.

Delete `C:\Users\[user name]\AppData\Roaming\nvm\[node version]\node_modules\npm2` folder.
