### ISSUE TITLE
ls in coreutils can't accept parameters. 

### ISSUE THREAD

**Issue by nicekiwi** [lukesampson/scoop#296]
PS C:\> ls -al
    Get-ChildItem : A parameter cannot be found that matches parameter name 'al'.
    At line:1 char:4
    + ls -al
    +    ~~~
        + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParentCont
       ainsErrorRecordException
        + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
       ands.GetChildItemCommand

    PS C:\>

**Comment by deevus** [comment]
You're still using the Powershell alias for Get-ChildItem. You'll need to add `Remove-Item alias:/ls` to your Powershell profile.

**Comment by nicekiwi** [comment]
Ohhhh that's pretty awesome :smile:
