### ISSUE TITLE
mariadb update failed

### ISSUE THREAD

**Issue by aleppos** [lukesampson/scoop#2963]
Installing 'mariadb' (10.3.12) [64bit]
The remote server returned an error: (302) FOUND.
URL https://downloads.mariadb.org/f/mariadb-10.3.12/winx64-packages/mariadb-10.3.12-winx64.zip is not valid

**Comment by rasa** [comment]
https://downloads.mariadb.org/f/mariadb-10.3.12/winx64-packages/mariadb-10.3.12-winx64.zip Is ok: 
3c7c31ddf572455213a0d2ddc2b3a0487af41bdc19588191d99142ad9fb73911
