### ISSUE TITLE
Openssh - 503 Server Unavailable

### ISSUE THREAD

**Issue by huangfang100** [lukesampson/scoop#2966]
Failed to install openssh due to 'URL http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz is not valid'. Needs to update the config for it?

\ $ scoop uninstall openssh
Uninstalling 'openssh' ().
'openssh' was uninstalled.
\ $ scoop install openssh
Installing 'openssh' (7.6p1) [64bit]
The remote server returned an error: (503) Server Unavailable.
URL http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz is not valid
\ $

**Comment by rasa** [comment]
Unable to duplicate. Please try again.
Closing as this issue is stale. Please reopen if this is still an issue.
