### ISSUE TITLE
7zip URL is not valid

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop#2968]
I have tried to update 7zip and face the error:

```
Installing '7zip' (18.06) [64bit]
Unable to connect to the remote server
URL https://7-zip.org/a/7z1806-x64.msi is not valid
```

PS, well it looks like 7-zip.org is down.

**Comment by moosad** [comment]
It was just a temporary issue, I guess, because it's up now.

**Comment by habamax** [comment]
Still unable to connect...

Tried the link in Firefox -- the same, connection timed out. 
Tried with Tor browser -- it is there, no errors.

Looks like it is not accessible from Russia (or from part of it)

**Comment by habamax** [comment]
nevermind, it really is blocked in Russia

http://isitblockedinrussia.com/?host=7-zip.org
