### ISSUE TITLE
Yarn 1.13.0 broken in PowerShell when installed from Scoop

### ISSUE THREAD

**Issue by briman0094** [lukesampson/scoop#2971]
After using Scoop to update my copy of Yarn to 1.13.0, I can no longer run any Yarn-installed binaries. For example, after running `yarn global add ts-node`, any attempts to run `ts-node` result in the following output:

```
At C:\Users\<username>\scoop\apps\yarn\current\bin\ts-node.ps1:5 char:13
+     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
+             ~
Unexpected token ')' in expression or statement.
At C:\Users\<username>\scoop\apps\yarn\current\bin\ts-node.ps1:8 char:3
+ if [ -x "$basedir/pwsh" ]; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\<username>\scoop\apps\yarn\current\bin\ts-node.ps1:8 char:5
+ if [ -x "$basedir/pwsh" ]; then
+     ~
Missing type name after '['.
At C:\Users\<username>\scoop\apps\yarn\current\bin\ts-node.ps1:9 char:20
+ ... edir/pwsh"  "$basedir/../../../../../AppData/Local/Yarn/Data/global/n ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"$basedir/../../../../../AppData/Local/Yarn/Data/global/node_modules/.bin/ts-node.ps1"' in expression or statement.
At C:\Users\<username>\scoop\apps\yarn\current\bin\ts-node.ps1:9 char:107
+ ... ../AppData/Local/Yarn/Data/global/node_modules/.bin/ts-node.ps1" "$@"
+                                                                      ~~~~
Unexpected token '"$@"' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

The contents of `ts-node.ps1` are as follows

```powershell
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/pwsh" ]; then
  "$basedir/pwsh"  "$basedir/../../../../../AppData/Local/Yarn/Data/global/node_modules/.bin/ts-node.ps1" "$@"
  ret=$?
else 
  pwsh  "$basedir/../../../../../AppData/Local/Yarn/Data/global/node_modules/.bin/ts-node.ps1" "$@"
  ret=$?
fi
exit $ret
```

Note the obvious syntax errors, as it appears the `.ps1` file is a bash script instead of a PowerShell script. Installing Yarn from their website works fine.

**Comment by briman0094** [comment]
Actually, this may not be a direct issue with Scoop. It appears when installing with Scoop, the bin entries in the PATH variable are added in a different priority so that Yarn is higher than when installing with Yarn's official installer. I just wiped out all Yarn-related folders/files/configs and reinstalled officially from their website, *manually* reordered the PATH variables so that their bin folder is first, and I'm still getting this issue.

**Comment by briman0094** [comment]
For anyone else that might stumble across this issue after `scoop update yarn`, here's the root cause that I was able to find: yarnpkg/yarn#6902

**Comment by proteus-aholt** [comment]
how are we supposed to downgrade our version of yarn via scoop?  I'm not seeing a yarn1121 within the versions bucket.  are we just out of luck?

**Comment by briman0094** [comment]
Looks like Scoop has rolled back the latest version of Yarn to 1.12.3 so all new installations will use that until a fix is released

I've submitted [two PRs to yarn](/yarnpkg/yarn/issues/created_by/briman0094) to fix the underlying issue here; one is a band-aid for the underlying problem (very non-invasive; most likely to be approved for a patch) and the second fixes the root cause.

**Comment by farzadmf** [comment]
Temporarily, I'm using this PowerShell script to fix the global binaries:

```powershell
function fix_yarn_glob
{
  $global_bin_dir = $( yarn global bin )

  Push-Location $global_bin_dir

  Write-Host 'Removing all files with a "ps1" in their name ...'
  Get-ChildItem *ps1* | Remove-Item -Force

  Write-Host 'Removing all files that do not have a .cmd extension ...'
  Get-ChildItem -Path .\* -File -Exclude *.cmd | Remove-Item -Force

  Get-ChildItem -Path .\* -File | ForEach-Object `
  {
    (Get-Content $_.FullName).Replace('%~dp0\', '') | Set-Content $_.FullName
  }

  Pop-Location
}
```

You need to run this function every time you do an update with `yarn global`

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
