### ISSUE TITLE
[Request] Add Pipenv

### ISSUE THREAD

**Issue by nitrocode** [lukesampson/scoop#2984]
https://pipenv.readthedocs.io/en/latest/

> Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world. Windows is a first-class citizen, in our world.

**Comment by 0x326** [comment]
@nitrocode I don't think Pipenv has standalone binary releases so it might be hard to create an app manifest for it. Pipenv is usually installed with:

```powershell
scoop install python  # If Python is not already installed
pip install pipenv
```

**Comment by pupeno** [comment]
I would have liked if scoop had a pipenv package. I think the desire is coming from the fact that brew has it and that pipenv itself points to how to install it:

https://github.com/pypa/pipenv/issues/996

**Comment by nitrocode** [comment]
@pupeno yes, thank you for mentioning that. That was my original reason and I forgot to state it.
