### ISSUE TITLE
gradle@5.1.1: hash check failed

### ISSUE THREAD

**Issue by roneilc** [lukesampson/scoop#2991]
Checking hash of gradle-5.1.1-all.zip ... ERROR Hash check failed!
App:         gradle
URL:         https://services.gradle.org/distributions/gradle-5.1.1-all.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    53b71812f18cdb2777e9f1b2a0f2038683907c90bdc406bc64d8b400e1fb2c3b
Actual:      0af8eb7dddbf7e5f5000aae478cfd2dba915fe40b8f50d470d8f88c6b9ecdbfb

**Comment by rasa** [comment]
Suppressed, Not relevant anymore
