### ISSUE TITLE
What are the possible configurations for Scoop?

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop#2992]
When I type `scoop config`, I get : 

```powershell
Usage: scoop config [rm] name [value]
```

But... What are the available configurations? How can I configure options for `aria2c` to use more or less connections?

**Comment by r15ch13** [comment]
All available `aria2c` settings are mention in the [Readme](https://github.com/lukesampson/scoop#multi-connection-downloads-with-aria2)

- `proxy` for changing the proxy settings
- `virustotal_api_key` for the `scoop virustotal` command

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by NatoBoram** [comment]
Thanks! I was able to edit my settings.

However, wouldn't it make more sense to add a list of settings in the command, just under the syntax?
