### ISSUE TITLE
Customizing install.ps1

### ISSUE THREAD

**Issue by falkenmire** [lukesampson/scoop#3007]
For various reasons related, we think, to proxying in our environment, aria2-assisted downloads fail with:

`ERROR Download failed! (Error 19) Name resolution failed`

If we disable aria2, the downloads work, but very slowly, so we'd like to keep using aria2. The 'fix' from the aria2 side is to disable `async-dns`, for example by creating a ~/.aria2/aria2.conf and setting async-dns=false. This produces the desired result (scoop uses aria2, aria2 succeeds without DNS errors) but required us to manually edit `scoop\current\lib\install.ps1` and alter the  `dl_with_cache_aria2` function to change the hard coded param `--no-conf=true`, to `false`. This worked for a while (weeks/months), however when we went to do a `scoop update` today, the whole mechanism fell over, presumably because our install.ps1 differed from what your scoop app update was expecting. 

Which, finally, brings us to our question: is `--no-conf=true` necessary in the `dl_with_cache_aria2` function? Our network topology and aria2's fragility are by no means a scoop project concern, but why must scoop hard code a value that says 'ignore any locally stored customizations to a third party binary we are about to rely on'.

If, for whatever reason, this option cannot be removed, another elegant solution from our POV would be to allow us to set `scoop config aria2-async-dns-enabled false` . If either suggestion has merit, we're happy to submit a PR. 

Thanks!

**Comment by r15ch13** [comment]
As soon as aria2 gets installed via scoop, it will be used as the default download method. If aria2 isn't configured correctly, scoop might stop working at that point. So `--no-conf=true` is necessary to prevent unexpected behaviour.

You can however use the `aria2-options` config value to add more parameters. Keep in mind that these options don't get merged with the default parameters.

```powershell
scoop config aria2-options '--aria2-async-dns-enabled=true --some-other=param'
```

`aria2-options` implementation:
https://github.com/lukesampson/scoop/blob/50edae25426771879375dd057dac989c32f5837f/lib/install.ps1#L264-L267

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.

**Comment by Rhilip** [comment]
It seems config key `aria2-options` Not list on README.md or any where except this issue.
Can you update it?
