### ISSUE TITLE
unzip URL is not valid

### ISSUE THREAD

**Issue by Zeroto521** [lukesampson/scoop#3017]
Try to install as `unzip`, but

```powershell
PS C:\Users\Zero> scoop install unzip
Installing 'unzip' (6.00) [64bit]
Unable to connect to the remote server
URL https://r15ch13.keybase.pub/scoop/unzip/unz600xn.exe#/dl.7z is not valid
```

I try to download this link using chrome, it's right.

So, there is any other way to install the app, such as **by hand**.

I try to download link and make the `unzip` **folder and files** like other app but no use. ¯\_(ツ)_/¯
It maybe connect with env.

**Comment by r15ch13** [comment]
Download it, rename it to `unzip#6.00#https_r15ch13.keybase.pub_scoop_unzip_unz600xn.exe_dl.7z` and put in `~\scoop\cache`. This should work.

https://keybase.pub is not always reliable, though.

**Comment by Zeroto521** [comment]
I install `zip` also happens this problem.

Then I try to find scoop cache folder use link to download then install and well done.

When installing `zip`, it fails.

And I also try to rename other names such as `exe_dl.7z`, `unz600xn.exe` or `unz600xn-x64.7z`(refer to `zip` file name), but no use.

**Comment by Zeroto521** [comment]
Well done, it's useful. Rename it to `unzip#6.00#https_r15ch13.keybase.pub_scoop_unzip_unz600xn.exe_dl.7z`

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
