### ISSUE TITLE
Archive older versions into other bucket

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3023]
Because vendors sometimes change their releae process with some renaming, url changing, extract_dir changes, ..., which break scoop's older versions isntalling.

While running excavator on known / widely used buckets, it would be nice if valid working manifests, which provides url with version inside it, would be pushed into versions bucket and adequately renamed (`bucket\<app>_<old_version>.json`). This would enable installing older versions of some manifest more viable.

New workflow for searching this kind of manifest is needed. But it would be just new check for manifest existence (If manifest exists in that version bucket (some github API request), Download it to workspace (No need to force user keep this bucket added to reduce trafic, space, ...), parse) above https://github.com/lukesampson/scoop/blob/2fd271edf5515f85b80a900bacdbb01c353afb24/libexec/scoop-install.ps1#L103

SideNote: To keep versions repository clean and organized it would be nice to structure bucket into subfolders based on manifest name, instead of simple renaming. Something like `REPO\bucket\<APP>\<All available versions>`

```text
REPO\bucket | php  |    | 2.0.json
            | ruby | => | 1.6.json
            | git  |    | 1.5.json
            | ...  |    | 1.4.json
```

**Comment by h404bi** [comment]
> While running excavator on known / widely used buckets, it would be nice if valid working manifests, which provides url with version inside it, would be pushed into versions bucket and adequately renamed (bucket\<app>_<old_version>.json). This would enable installing older versions of some manifest more viable.

> SideNote: To keep versions repository clean and organized it would be nice to structure bucket into subfolders based on manifest name, instead of simple renaming. Something like REPO\bucket\<APP>\<All available versions>

Prefer Homebrew-like definition:
```
boost@1.55.rb
boost@1.57.rb
boost@1.59.rb
boost@1.60.rb
```

There is another problem, some old versions file got deleted or became unavailable. Homebrew uses [bintray](https://bintray.com/) to store binaries or builds app from source, but Scoop can't do that at this moment.
