### ISSUE TITLE
Scoop not added to PSModulePath on PowerShell Core

### ISSUE THREAD

**Issue by krokofant** [lukesampson/scoop#3025]

**Comment by Ash258** [comment]
PowerShell/PowerShell#6850

**Comment by krokofant** [comment]
I was reading [this](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#backwards-compatibility-with-windows-powershell) which mentioned using:
```powershell
Install-Module WindowsPSModulePath -Force
Add-WindowsPSModulePath
```

To add the WindowsPowershell path but that does not include the scoop one.

**Comment by rasa** [comment]
Can this be closed?

**Comment by krokofant** [comment]
I think it would be nice to save this as a reference. Perhaps label as _upstream_? Since this makes it harder to use scoop with powershell core.

**Comment by fv-ian** [comment]
This isn't working as one would expect.  the $env:USERPROFILE\scoop\modules isn't getting added to pwsh module path.  

ie.  
1. Install pwsh via `scoop install pwsh`
2. I installed `scoop install oh-my-posh` using powershell. 
3. Launch `pwsh`
4. `Import-module posh-git` comes back with not found in any module directory.

**Comment by krokofant** [comment]
The fix for PowerShell 7 is now released (since preview.6) so this works in the latest PowerShell 7 rc.1.
