### ISSUE TITLE
What is going on with scoop? Any kind of JDK installation is failed by timeout on download...

### ISSUE THREAD

**Issue by daggerok** [lukesampson/scoop#3032]
Hello,

Cannot install any JDK via scoop...Previously (a weak ago or something) everything worked fine..
Download speed is dramatically slow and in the end installation failed.

![image](https://user-images.githubusercontent.com/2445604/51708702-d4a4ea80-2024-11e9-846c-337390cb6153.png)

Do you know why it's happening? 

----
Regards,
Maksim

**Comment by Calinou** [comment]
Is a direct download from that URL slow too? (Try opening it in a browser or with `curl`/`wget`).

**Comment by daggerok** [comment]
Hello, seems like it was some hosting problems.. As far as I can see, bitbucket or aws wherr archive was downloaded from...
Now everything is back to normal:
![image](https://user-images.githubusercontent.com/2445604/51720476-1dbd6480-204e-11e9-8e6f-a1e3bfc80fb9.png)
I think issue could be closed.
Thanks.

---
Regards,
Maksim
