### ISSUE TITLE
curl@7.63.0: extract_dir error

### ISSUE THREAD

**Issue by Nuzoo** [lukesampson/scoop#3033]
problems during installi Git
console output:
C:\WINDOWS\system32>scoop install -k curl
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'curl' (7.63.0) [64bit]
WARN  Cache is being ignored.
Loading curl-7.63.0-win64-mingw.tar.xz from cache.
Checking hash of curl-7.63.0-win64-mingw.tar.xz ... ok.
Extracting curl-7.63.0-win64-mingw.tar.xz ... 7z : Die Benennung "7z" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In C:\Users\nuzoo\scoop\apps\scoop\current\lib\decompress.ps1:21 Zeichen:15
+     $output = 7z x "$path" -o"$to" -y
+               ~~
    + CategoryInfo          : ObjectNotFound: (7z:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DEBUG
-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robustes Dateikopieren für Windows
-------------------------------------------------------------------------------

  Gestartet: Freitag, 25. Januar 2019 09:40:22
   Quelle : C:\Users\nuzoo\scoop\apps\curl\7.63.0\_tmp\curl-7.63.0-win64-mingw\
     Ziel : C:\Users\nuzoo\scoop\apps\curl\7.63.0\

    Dateien : *.*

  Optionen: *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2019/01/25 09:40:22 FEHLER 2 (0x00000002) Zugriff auf Quellverzeichnis C:\Users\nuzoo\scoop\apps\curl\7.63.0\_tmp\curl-7.63.0-win64-mingw\
Das System kann die angegebene Datei nicht finden.

ERROR Could not find 'curl-7.63.0-win64-mingw'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=curl%407.63.0%3a+extract_dir+error
True

**Comment by h404bi** [comment]
`(7z:String) [], CommandNotFoundException`

Please install 7zip before install curl

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
