### ISSUE TITLE
Bad encoding in Vim

### ISSUE THREAD

**Issue by SharakPL** [lukesampson/scoop#3039]
Vim doesn't show language specific chars properly. I think the encoding should be utf-8. I managed to fix the problem inside Vim by adding this line to __vimrc_ :

```set encoding=utf-8```

but the problem persists when I use i.e. `vim --help`. Here the output still has bad encoding, even after `$PSDefaultParameterValues['*:Encoding'] = 'utf8'`

**Comment by LexSong** [comment]
Do you use vim in Windows terminal?
The Windows terminal is old and can't display unicode very well.
It will *somewhat* work, but it is not as good as in `gvim`.
To display unicode characters on windows terminal, you need your os, the terminal emulator, the shell(cmd.exe) or terminal program, and the font all works properly, which is sometimes quite difficult.

What windows version are you using? The unicode support is much improved in the latest version of Windows 10.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3039
