### ISSUE TITLE
[Request] Add MoonScript

### ISSUE THREAD

**Issue by LagSwitchedVirginity** [lukesampson/scoop#3041]
[MoonScript](https://moonscript.org/) is **"A programmer friendly language that compiles to Lua."**

[MoonScript/releases](https://github.com/leafo/moonscript/releases)

**Comment by NavyCo** [comment]
This is the generated content via `scoop create`
```json
{
    "version":  "win32-v0.5.0",
    "license":  "",
    "extract_dir":  "",
    "url":  "https://github.com/leafo/moonscript/releases/download/win32-v0.5.0/moonscript-187bac54ee5a7450013e9c38e005a0e671b76f45.zip",
    "depends":  "",
    "homepage":  "https://github.com/leafo/moonscript",
    "hash":  "",
    "bin":  "moonc.exe"
}
```

I typed in `scoop install moonscript` after using the `scoop create` command, and it appeared to install correctly.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3041
