### ISSUE TITLE
PHP cgi configuration

### ISSUE THREAD

**Issue by atef201080** [lukesampson/scoop#3064]
I like the way and how easy it is to store the configurations in persist folder, but i have problem with php cgi configuration, idk where to store them for the exe file to read, is there an easy way to store it instead of copying them with every update?
the configuration in the cli folder doesn't effect the cgi exe..

**Comment by armpogart** [comment]
Something is wrong with your installation, or you have added `php.ini` or `php-cgi.ini` file to the php directory. `php-cgi` uses the `php.ini` file in php directory or if it doesn't find it there, it will look for php.ini file in `PHP_INI_SCAN_DIR` which is cli folder in persist dir.

Here is the output of `php-cgi -i`:
![image](https://user-images.githubusercontent.com/785768/52177621-049a7d80-27dd-11e9-9e17-8be404dae124.png)
As you can see correct ini files are loaded.
So my suggestion is, if you have `php.ini` or `php-cgi.ini` files in php directory remove them and `php-cgi` will read `php.ini` file in persist/cli directory. Also check whether `PHP_INI_SCAN_DIR` environment variable is set correctly (you can uninstall php with scoop and install it again to set the env var automatically).

**Comment by rasa** [comment]
Can someone submit a PR?

**Comment by armpogart** [comment]
@rasa Not sure what PR do you mean? I wanted to show OP that everything must work ok.
This issue just needs someone else's confirmation that everything is ok to close.

**Comment by atef201080** [comment]
I had to add `PHP_INI_SCAN_DIR` environment variable in System variables i didn't work in users variables, It's ok to close. thanks
