### ISSUE TITLE
Add scoopup command.

### ISSUE THREAD

**Issue by onacit** [lukesampson/scoop#3072]
Thanks in advance.

Whenever I open my laptop. I always do.

```
> scoop udpate && scoop update * && scoop cleanup *
```

Can you please add a command, say `scoopup`, in `bin\`, so that I simply run it?

**Comment by onacit** [comment]
This is not a good issue, I think. Sorry.

**Comment by Ash258** [comment]
You can add it yourself:
`scoop alias add up 'scoop update; scoop update *; scoop cleanup *'. THen it will be available as `scoop up`
