### ISSUE TITLE
VSCode Portable hash check failed during installation

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#3075]
`Download: (OK):download completed.
Checking hash of stable ... ok.
Checking hash of vscode-install-context.reg ... ERROR Hash check failed!
App:         extras/vscode-portable
URL:         https://raw.github.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
First bytes: 57 69 6E 64 6F 77 73 20
Expected:    73ca2243ce4577a9e0e72664d6d5150d56c1641d1ea4bcd6dd2a37eef1f2587c
Actual:      3673d7767da27418c4c7eea146043fa6a7c59df65199c79850e58367fd66fb56

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=vscode-portable%401.30.2%3a+hash+check+failed`

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/aba41c9f350b6e8cfcb15f484fd15cd59ccddd56
