### ISSUE TITLE
[Request] Add IPFS-Cluster, et al

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop#3076]
Home page : https://cluster.ipfs.io/
Project page : https://github.com/ipfs/ipfs-cluster
Download page : https://dist.ipfs.io/#ipfs-cluster-ctl, https://dist.ipfs.io/#ipfs-cluster-service

IPFS-Cluster consists of two commands, `ipfs-cluster-ctl` and `ipfs-cluster-service`. It helps create and manage IPFS clusters.

The downloaded files are `.zip` archives that contains a stand-alone `.exe` binary.

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3076
