### ISSUE TITLE
[Request] Add dtrx

### ISSUE THREAD

**Issue by stuaxo** [lukesampson/scoop#3077]
Hi,
   Here is a request for dtrx a sane way of using commandline extractors.

S

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3077
