### ISSUE TITLE
[Request] Add Lando

### ISSUE THREAD

**Issue by jimmi-joensson** [lukesampson/scoop#3082]
Would love to see Lando be a part of the package list.
https://docs.devwithlando.io/

**Comment by r15ch13** [comment]
Beta 47 or Release Candidate 5/6?

**Comment by jimmi-joensson** [comment]
The Newest release candidate would be great, v3.0.0-rc.6 :)

**Comment by r15ch13** [comment]
Too bad that they bundle the whole docker installer with it...

**Comment by r15ch13** [comment]
I am just experimenting with the `Docker for Windows Installer`.
Scoop can only download, run it and then the setup file can be removed because it uses a fixed install path to `C:\Program Files\Docker`.
Lando itself is just a simple nodejs build without any other stuff.

**Comment by jimmi-joensson** [comment]
Okay hope it is doable then. I mean you already have docker as a part of scoop or that is maybe not installed from the "Docker for Windos" installer?

**Comment by r15ch13** [comment]
Related issue: https://github.com/lukesampson/scoop/issues/2682

Example `docker-for-windows.json`:
```json
{
    "homepage": "https://hub.docker.com/editions/community/docker-ce-desktop-windows",
    "description": "Downloads and runs the 'Docker for Windows' installer.",
    "license": "https://www.docker.com/legal/docker-software-end-user-license-agreement",
    "version": "2.0.0.2.30215",
    "architecture": {
        "64bit": {
            "url": "https://download.docker.com/win/stable/30215/Docker for Windows Installer.exe#/installer.exe",
            "hash": "9fdebb583c0b64b9fe1b66bbd17e5e0a28e36551587741f6b0188b7e8123a6b7"
        }
    },
    "installer": {
        "file": "installer.exe"
    },
    "checkver": {
        "url": "https://download.docker.com/win/stable/appcast.xml",
        "regex": "<title>(?<version>[\\d.]+)\\s+\\((?<build>[\\d]+)\\)</title>",
        "replace": "${1}.${2}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://download.docker.com/win/stable/$matchBuild/Docker for Windows Installer.exe#/installer.exe"
            }
        }
    },
    "notes": [
        "'Docker for Windows' has been installed to the default location 'C:\\Program Files\\Docker\\Docker'.",
        "You can now remove this package because Scoop can't handle uninstalling or upgrading 'Docker for Windows'."
    ]
}
```


Example `lando.json`:
```json
{
    "homepage": "https://docs.devwithlando.io/",
    "description": "A free, open source, cross-platform, local development environment and DevOps tool built on Docker container technology.",
    "license": "GPL-3.0-or-later",
    "innosetup": true,
    "version": "3.0.0-rc.6",
    "architecture": {
        "64bit": {
            "url": "https://github.com/lando/lando/releases/download/v3.0.0-rc.6/lando-v3.0.0-rc.6.exe",
            "hash": "eb4d187826df5511ceae3c8b9043b346431c9b552bd59857757fdb6c4e53a825"
        }
    },
    "bin": "bin\\lando.exe",
    "installer": {
        "script": [
            "Write-Host \"Running 'Docker for Windows Installer' ...",
            "Write-Host \"It will be installed automatically installed to: 'C:\\Program Files\\Docker\\Docker'",
            "Start-Process \"$dir\\installers\\docker\\docker.exe\" -Wait -ErrorAction Continue"
        ]
    },
    "suggest": {
        "Git": [
            "git",
            "git-with-openssh"
        ],
        "Docker for Windows": [
            "docker-for-windows"
        ]
    },
    "checkver": {
        "url": "https://github.com/lando/lando/releases",
        "regex": "/releases/tag/(?:v)?([\\d\\w.-]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/lando/lando/releases/download/v$version/lando-v$version.exe"
            }
        }
    },
    "notes": [
        "'Docker for Windows' has been installed to the default location 'C:\\Program Files\\Docker\\Docker'.",
        "Scoop can't handle uninstalling or upgrading 'Docker for Windows'!"
    ]
}
```

**Comment by Ash258** [comment]
@r15ch13 You could pass `install` and `--quiet` for installer. (https://github.com/Ash258/scoop-Ash258/blob/a6ce466f35193176a499dfc714c5d58e0608bc22/bucket/docker.json#L32-L44)

**Comment by r15ch13** [comment]
@Ash258 nice! 👍
The problem now: Should we install Docker for Windows while installing Lando or just suggest running `installers\docker\docker.exe` manually or `scoop install docker-for-windows`.

**Comment by Ash258** [comment]
For Lando developers it would be few lines inside theri appveyor build:

https://github.com/lando/lando/blob/58e39101944a9db667ee48177f9ef1e3dcb867d8/appveyor.yml#L44-L49 Edit to use `yarn pkg:cli` and then upload cli artifacts.

**Comment by r15ch13** [comment]
@Ash258 Adding a line to [build-releases-appveyor.ps1](https://github.com/lando/lando/blob/master/scripts/build-releases-appveyor.ps1) should do the trick:

```powershell
Copy-Item "build\cli\lando-win32-x64-v$env:APPVEYOR_REPO_TAG_NAME.exe" -Destination "release\lando-$env:APPVEYOR_REPO_TAG_NAME.exe" -Force
```

**Comment by Ash258** [comment]
Will you open issue on upstream? This could be implemented pretty easily and be shipped in next iteration, if they will agree. 

Maybe they could implement `gci release |% { "$(Get-FileHash $_)  *$_" >> checksums.txt }`

**Comment by rasa** [comment]
Authors do not want this

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3082
