### ISSUE TITLE
Scoop doesn't check if install failed

### ISSUE THREAD

**Issue by stuaxo** [lukesampson/scoop#3089]
I can't install quite a few things from scoop at work.

Scoop still thinks the package installs even if it cannot download the archive.

```
$ scoop install conemu
Installing 'conemu' (19.01.08) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://github.com/Maximus5/ConEmu/releases/download/v19.01.08/ConEmuPack.190108.7z is not valid

A642177@GBDA320331 MINGW64 ~
$ scoop list
Installed apps:

  7zip 18.06
  clink
  cmder
  cmder-full
  conemu
  consolez
  curl 7.63.0
  git
  git-with-openssh
  neovim
  sliksvn 1.9.7
  unzip
```

**Comment by r15ch13** [comment]
This is a known issue. `install.ps1` has to be refactored a lot to fix this.
The current workaround is uninstalling and reinstalling the program.

**Comment by stuaxo** [comment]
Cheers, I shall close this then.

**Comment by Stanzilla** [comment]
@stuaxo @Ash258 @lukesampson please re-open, this is still an issue.
