### ISSUE TITLE
[Request] Add Jack2

### ISSUE THREAD

**Issue by luzpaz** [lukesampson/scoop#3092]
> JACK2 aka jackdmp is a C++ version of the JACK low-latency audio server for multi-processor machines. It is a new implementation of the JACK server core features that aims at removing some limitations of the JACK1 design. The activation system has been changed for a data flow model and lock-free programming techniques for graph access have been used to have a more dynamic and robust system.

https://github.com/jackaudio/jack2/releases/tag/v1.9.12

vcpkg config file: https://github.com/Microsoft/vcpkg/blob/dev/philc/4889/ports/jack2/portfile.cmake

**Comment by rasa** [comment]
Library, out of scope
