### ISSUE TITLE
[Request] Add gdal 

### ISSUE THREAD

**Issue by luzpaz** [lukesampson/scoop#3093]
The Geospatial Data Abstraction Library (GDAL)  
Homepage: http://gdal.org  
Current stable: 2.4.0

vcpkg port: https://github.com/Microsoft/vcpkg/tree/master/ports/gdal

**Comment by luzpaz** [comment]
thanks

**Comment by luzpaz** [comment]
@Calinou I found some binary options:  
See https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries#Windows  
The first link is: http://www.gisinternals.com/release.php  
which leads to http://www.gisinternals.com/release.php

**Comment by rasa** [comment]
Library, out of scope, not valid binaries
