### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by panchoporteno** [lukesampson/scoop#3100]
icu-59.1-1-x86_64.pkg.tar.xz (7.3 MB) [=====>                                                                 ]   9%
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      b2c8b353cbac2fa914f17b07eefec6c10464e5b12ae4b93db3ec017fcff3613f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
