### ISSUE TITLE
'lynx' doesn't support 64bit architecture!

### ISSUE THREAD

**Issue by nancym** [lukesampson/scoop#3105]
I just installed scoop on an up-to-date Windows 10 device and ran this:

```
scoop install lynx
```
which produced this:

```
Installing '7zip' (18.06) [64bit]
7z1806-x64.msi (1.7 MB) [==========================================================================================================================================================] 100%
Checking hash of 7z1806-x64.msi ... ok.
Extracting 7z1806-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.06
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (18.06) was installed successfully!
Installing 'innounp' (0.47) [64bit]
innounp047.rar (137.0 KB) [========================================================================================================================================================] 100%
Checking hash of innounp047.rar ... ok.
Extracting innounp047.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.47
Creating shim for 'innounp'.
'innounp' (0.47) was installed successfully!
Installing 'cacert' (2019-01-23) [64bit]
cacert-2019-01-23.pem (214.4 KB) [=================================================================================================================================================] 100%
Checking hash of cacert-2019-01-23.pem ... ok.
Linking ~\scoop\apps\cacert\current => ~\scoop\apps\cacert\2019-01-23
Running post-install script...
'cacert' (2019-01-23) was installed successfully!
Installing 'openssl' (1.1.1a) [64bit]
Win64OpenSSL-1_1_1a.exe (60.9 MB) [================================================================================================================================================] 100%
Checking hash of Win64OpenSSL-1_1_1a.exe ... ok.
Unpacking innosetup... done.
Linking ~\scoop\apps\openssl\current => ~\scoop\apps\openssl\1.1.1a
Creating shim for 'openssl'.
'openssl' (1.1.1a) was installed successfully!
'lynx' doesn't support 64bit architecture!
```
and then this happened:

```
PS > lynx
lynx : The term 'lynx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ lynx
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lynx:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Do you have any tips for how to run this lynx on my system, e.g., maybe launch PowerShell in 32-bit mode? Is that possible? 

Thanks for any tips!

**Comment by Calinou** [comment]
Try installing lynx using `scoop install -a 32bit lynx` to force installing in 32-bit mode. The [`lynx.json`](https://github.com/lukesampson/scoop/blob/master/bucket/lynx.json) manifest only specifies a download for 32-bit since one of its dependencies (OpenSSL) *must* be installed in 32-bit mode, and installing lynx in 64-bit would install the 64-bit version of OpenSSL, which cannot be used with a 32-bit executable.

**Comment by nancym** [comment]
I discoved and launched Windows PowerShell (x86) and installed lynx - yay 👏. But when I try to run lynx, it says:

```
lynx requires the 32-bit version of openssl to be installed
```

I'm going to keep trying things and am optimistic I'll get this to work, but it would be nice if scoop gave a message at the very beginning of this proces (when I typed `scoop install lynx` at a 64-bit PowerShell prompt) that said something like "it's best if you install this from a 32-bit PowerShell prompt".

**Comment by nancym** [comment]
Thanks for your quick reply @Calinou - I got it to work, thanks to your suggestion! If anyone else has this issue, I did the following to get it to work:

```
scoop uninstall lynx
scoop uninstall openssl
scoop install -a 32bit lynx
```
Next question: After the above it said `'lynx' suggests installing 'extras/vcredist2012'.` How important is this? I did `scoop bucket add extras` and got this:

```
Git is required for buckets. Run 'scoop install git'.
```

I'd rather not install Git if I can help it.

Thank you.

**Comment by Calinou** [comment]
> After the above it said `'lynx' suggests installing 'extras/vcredist2012'.` How important is this?

Some Windows programs require specific versions of the Visual C++ redistributable being installed, but it's possible that you already have it installed thanks to another program. The manifest file could wrongly suggest it too (that should be tested in a fresh Windows VM; install the package and see if it runs without errors).
