### ISSUE TITLE
mysql@8.0.15: hash check failed

### ISSUE THREAD

**Issue by cizirgan** [lukesampson/scoop#3122]
**scoop install mysql@5.7.25**
WARN  Given version (5.7.25) does not match manifest (8.0.15)
WARN  Attempting to generate manifest for 'mysql' (5.7.25)
Autoupdating mysql
Searching hash for mysql-5.7.25-winx64.zip in https://dev.mysql.com/downloads/mysql/
Found: md5:75fd5cd2676209550a8b9bac4fd0a8b6 using Extract Mode
Writing updated mysql manifest
Installing 'mysql' (5.7.25) [64bit]
mysql-5.7.25-winx64.zip (321.1 MB) [==============================================================] 100%
Checking hash of mysql-5.7.25-winx64.zip ... ERROR Hash check failed!
App:         mysql
URL:         https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.25-winx64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    75fd5cd2676209550a8b9bac4fd0a8b6
Actual:      36db4a4c5804eda1f800c18860ad2a16

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=mysql%408.0.15%3a+hash+check+failed

**Comment by niheaven** [comment]
Please use versions/mysql57 instead.

**Comment by cizirgan** [comment]
> Please use versions/mysql57 instead.

Thanks. 

1. `scoop bucket add versions`
2. `scoop install versions/mysql57`
