### ISSUE TITLE
scoop update fails to connect to GitHub

### ISSUE THREAD

**Issue by d2s** [lukesampson/scoop#3124]
No idea why `scoop update` fails. It used to work properly some days ago.
Other command line applications can normally access network.

`scoop update` fails with the following error message:

```
> scoop update

Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to github.com port 443: Bad access
Update failed.
```

### Extra details

```
> scoop checkup

No problems identified!
```

```
> scoop --version

Current Scoop version:
a305535b (HEAD -> master, origin/master, origin/HEAD) core.ps1: Allow SCOOP_DEBUG environment variable in debug() function
```

Not sure if the https://github.com/lukesampson/scoop/commit/a305535b0ec235e3b51ff43c4ca617f96eaba37c commit had anything to do with this issue.

What other details are needed about the issue?

**Comment by Ash258** [comment]
These errors come from git itself. Does something like this work (and resul of them):

```powershell
cd "$env:SCOOP\apps\scoop\current\"
git fetch
git pull
```

**Comment by d2s** [comment]
`scoop` works again on the computer, so closing this GitHub Issue ticket. Most likely the recent Windows update affected the behaviour of the computer, and caused the issue to disappear.

(Previously tried the aforementioned manual git fetch & pull process, and it did not work.
Also, I do not have `$env:SCOOP` set, so could not access the directory via that.
Found my way to it manually, but when I tried `git fetch`, it failed similarly.)

But fortunately `git` and `scoop` work again. Not sure what was the original source of the issue, but closing this issue ticket as the original trouble has gone away.

**Comment by LevT2** [comment]
Please reopen

```
PS C:\Users\Op> cd "$env:SCOOP\apps\scoop\current\"
PS E:\A\SCOOP\apps\scoop\current> git fetch
PS E:\A\SCOOP\apps\scoop\current> git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
PS E:\A\SCOOP\apps\scoop\current> scoop update scoop
Updating Scoop...
Update failed.
```

**Comment by LevT2** [comment]
@lukesampson  @Ash258 

Please reopen
I had scoop working and someday redirected it via $Env:SCOOP

```
PS C:\Users\Op> cd "$env:SCOOP\apps\scoop\current\"
PS E:\A\SCOOP\apps\scoop\current> git fetch
PS E:\A\SCOOP\apps\scoop\current> git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
PS E:\A\SCOOP\apps\scoop\current> scoop update scoop
Updating Scoop...
Update failed.
```

**Comment by GOUKOU007** [comment]
Run this command then you can update your scoop: 
`git config --global http.sslVerify "false"`

**Comment by freshsun** [comment]
> Run this command then you can update your scoop: `git config --global http.sslVerify "false"`

still works on 2024 Jan

**Comment by WTHDonghai** [comment]
run termianl as admin. It's work

**Comment by DrVektor** [comment]
when some programmes are installed as admin, e.g. chromium, e.g. forkgram, even webcord... won't open. It requires administrator rights to open. But if I install as a normal user, there is no problem. Even windows only recognises the programme that way.

**Comment by yusing** [comment]
> Run this command then you can update your scoop: `git config --global http.sslVerify "false"`

do this instead `git config --global http.sslBackend openssl`, disabling ssl verify is not a smart take
