### ISSUE TITLE
Uninstalling app with `_` or `:` in name uninstalls app which matches the part before that character (scoop_ruby_20_to25 => scoop)

### ISSUE THREAD

**Issue by janpio** [lukesampson/scoop#3128]
I have created a manifest `scoop_ruby_20_to_25` via a Gist that contains an older version of the ruby Manifest: https://gist.githubusercontent.com/janpio/40e014d0ae31215b4bab2b5bbe5a69e8/raw/3500373c9484ca8c3c89aac4998cda333451a555/scoop_ruby_20_to_25.json 

I use it to install older Ruby versions, like e.g. `2.4.5`:
```
scoop_ruby_20_to_25 2.4.5-1
```

No I tried to uninstall that app. Look what happens:

```
PS C:\Users\Jan> scoop list
Installed apps:

  7zip 18.06
  ...
  scoop_ruby_20_to_25 2.4.5-1 [https://gist.githubusercontent.com/janpio/40e014d0ae31215b4bab2b5bbe5a69e8/raw/3500373c9484ca8c3c89aac4998cda333451a555/scoop_ruby_20_to_25.json]
  ...
  winscp 5.13.7 [extras]

PS C:\Users\Jan> scoop uninstall scoop_ruby_20_to_25
Uninstalling 'scoop' (current).
Unlinking ~\scoop\apps\scoop\current
The directory is not empty.
'scoop' was uninstalled.
PS C:\Users\Jan> scoop
& : The term 'C:\Users\Jan\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\Jan\scoop\shims\scoop.ps1:3 char:71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Jan\sc...t\bin\scoop.ps1:String) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Jan>
```

So seems that scoop uninstalled itself.

Is something wrong with my manifest?
Is it a bad idea to name stuff beginning with `scoop`?
Or is this a bug with scoop?

Also, how can I uninstall the `scoop_ruby_20_to_25` app now?

**Comment by Ash258** [comment]
Definitely bug. Haven't found cause yet.

There is strange behaviour with underscores overall.

**Comment by Ash258** [comment]
Should be OK when you install using dashes (`scoop-ruby...`) (I guess, since have no time to test it)

**Comment by janpio** [comment]
Hm, what is the best way to get rid of the app anyway? Just delete the folder in `scoop/apps`?

I also tried other routes to deinstall the app, which maybe shows another possible problem:
```
PS C:\Users\Jan> scoop uninstall https://gist.githubusercontent.com/janpio/40e014d0ae31215b4bab2b5bbe5a69e8/raw/3500373c9484ca8c3c89aac4998cda333451a555/scoop_ruby_20_to_25.json
ERROR 'https' isn't installed.
```
I wouldn't have expected this to be cut to `https` as well.

**Comment by h404bi** [comment]
Congrats! You found a bug of Scoop! 🆒 The problem is the `parse_app()` function in [`core.ps1`](https://github.com/lukesampson/scoop/blob/a305535b0ec235e3b51ff43c4ca617f96eaba37c/lib/core.ps1#L613) returns `scoop` as the app name when you pass the app name which contains underscore, `scoop_ruby_20_to_25`.

```powershell
$ 'scoop_ruby_20_to_25' -match '(?:(?<bucket>[a-zA-Z0-9-]+)\/)?(?<app>.*.json$|[a-zA-Z0-9-.]+)(?:@(?<version>.*))?'
True
$ $matches['app'], $matches['bucket'], $matches['version']
scoop
```

To fix this, or to say **support app name that contains underscore**, just add underscore into the regex.

```powershell
$ 'scoop_ruby_20_to_25' -match '(?:(?<bucket>[a-zA-Z0-9-]+)\/)?(?<app>.*.json$|[a-zA-Z0-9-_.]+)(?:@(?<version>.*))?'
True
Desktop tmp
$ $matches['app'], $matches['bucket'], $matches['version']
scoop_ruby_20_to_25
```

I have provided the details about the issue, now you can open a pull request to contribute to scoop and become a contributor! 😄

**Comment by janpio** [comment]
I updated the title of the issue to reflect that new knowledge.

I could get rid of the app by renaming the folder `scoop_ruby_20_to_25` in `C:\Users\Jan\scoop\apps` to `ruby20to25` and then running `scoop uninstall ruby20to25`.

**Comment by janpio** [comment]
Did as you said @h404bi: #3129

**Comment by r15ch13** [comment]
I would also suggest adding an additional check to `scoop-uninstall.ps1`, just in case something diffrent happens. 😁 

https://github.com/lukesampson/scoop/blob/bd5918f7e69272a8411cf2b0bfe8ff50447c56fe/libexec/scoop-uninstall.ps1#L39-L43

After `($app, $global) = $_`
```powershell
    if($app -eq 'scoop') {
        # Skip uninstalling scoop
        continue
    }
```

**Comment by Ash258** [comment]
Safe nets / guards are never enough 😂

**Comment by janpio** [comment]
Well, I though it was kind of impressive that I could use scoop to uninstall scoop...

**Comment by Ash258** [comment]
That's normal feature. When you write `scoop uninstall scoop` all apps will be uninstalled and then scoop will be deleted too.

#2781, <https://github.com/lukesampson/scoop/wiki/Uninstalling-Scoop>

**Comment by janpio** [comment]
Oh ok, so just the "unintentional" uninstall is unwanted.

**Comment by Ash258** [comment]
Add tests, check from https://github.com/lukesampson/scoop/issues/3128#issuecomment-463672334 and it should never happened. This use case should not be reproducible in any state.

**Comment by Ash258** [comment]
It could solve even #2666
