### ISSUE TITLE
curl@7.60.0: hash check failed

### ISSUE THREAD

**Issue by nizhenghua** [lukesampson/scoop#3136]
App:       curl
URL:       https://dl.bintray.com/vszakats/generic/curl-7.60.0-win64-mingw.tar.xz
Expected:  5f3594236dcd3385033d0d754f445b24bdcf93c9a9db17cd4c4fcb8b02e2d0db
Actual:    febfbd5fffdec1ca2d7a187faa01abf38065395894cac995fc9e3a862f7995c4

**Comment by r15ch13** [comment]
Please run `scoop update` first. We moved the curl download URL from `https://dl.bintray.com/vszakats/generic` to `https://curl.haxx.se/windows/` long ago.

**Comment by nizhenghua** [comment]
Oh, thank you very much.
