### ISSUE TITLE
Cannot run 'aws' after install

### ISSUE THREAD

**Issue by glucas** [lukesampson/scoop#3139]
I can no longer install and run the aws cli. Not sure when it stopped working for me, but I've tried uninstalling/reinstalling and I just get this:

    > scoop install aws
    Installing 'aws' (1.16.107) [64bit]
    Loading AWSCLI64PY3-1.16.107.msi from cache
    Checking hash of AWSCLI64PY3-1.16.107.msi ... ok.
    Extracting AWSCLI64PY3-1.16.107.msi ... done.
    Linking ~\scoop\apps\aws\current => ~\scoop\apps\aws\1.16.107
    Creating shim for 'aws'.
    'aws' (1.16.107) was installed successfully!

    >  aws
    failed to create process.`

**Comment by glucas** [comment]
It looks like I can successfully run:

    ~\scoop\apps\aws\current\bincompat\aws.cmd

but cannot run

    ~\scoop\apps\aws\current\bin\aws.exe

**Comment by Ash258** [comment]
Ask @javakhishvili, why he make change from cmd to exe (#3132)

**Comment by glucas** [comment]
Working now, thanks!
