### ISSUE TITLE
503 when installing scoop

### ISSUE THREAD

**Issue by hovissimo** [lukesampson/scoop#3142]
![image](https://user-images.githubusercontent.com/6434414/53046298-95f82980-3444-11e9-86b9-760aabaef627.png)

I haven't tried to use Scoop before, I'm not sure what's going on.

I can get `get.scoop.sh`, so I'm trying each of the URIs in that script.

https://raw.github.com/lukesampson/scoop/master/lib/core.ps1 returns 503 in my browser.

**Comment by r15ch13** [comment]
Fixed, should work now. It seems GitHub disabled `raw.github.com` and allows only `raw.githubusercontent.com` now.

**Comment by hovissimo** [comment]
Confirmed, TYVM!
