### ISSUE TITLE
py throws error 'Can't find default python'

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#315]
```powershell
scoop install python
# python 3.4.x installs
py
Can't find a default Python.
```

Maybe it's a limitation of how `py.exe` works, but it's a shame this doesn't work.

**Comment by lukesampson** [comment]
Setting `$env:PYLAUNCH_DEBUG=1` gives some more info about what's happening.

More info at [Python Launcher For Windows](https://bitbucket.org/vinay.sajip/pylauncher/src/tip/Doc/launcher.rst)

From the `locate_all_pythons` function in [this source file](https://bugs.python.org/file21330/pep-0397-reference.py) it looks like the launcher will only check the registry to discover installed python versions, but scoop doesn't support adding registry entries, 

Maybe it could be done in a post-install with something like:

```powershell
new-item -path HKCU:\Software\Python\PythonCore\3.4 -name InstallPath -value "$appdir" -force
```

... but even adding the registry entries created by the official Python MSI installer doesn't seem to work.

Not sure what the solution is here.

**Comment by deevus** [comment]
I think I've figured this out by adding the following to the `post_install`:

```powershell
sudo cmd /c assoc .py=Python.File
sudo cmd /c ftype Python.File=\"$dir\\py.exe\" \"%1\" %*

$ py
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Is there a clean-up task after uninstalling to unset these if needed?

**Comment by deevus** [comment]
The next problem is that `py.exe` can only find the last version installed (or reset) with scoop.

**Comment by deevus** [comment]
I also just realised that `py.exe` doesn't come with `python27`

**Comment by lukesampson** [comment]
We need to have it work for non-administrator users, and installs should be non-interactive for administrators too—so I don't think the `sudo` calls in `post_install` are going to work.

**Comment by lukesampson** [comment]
I'm thinking this might be a wontfix.

**Comment by deevus** [comment]
Not so fast!

```
new-item -path Registry::HKEY_CURRENT_USER\\Software\\Classes\\.py\\shell\\open\\command -force
new-itemproperty -path `
    Registry::HKEY_CURRENT_USER\\Software\\Classes\\.py\\shell\\open\\command `
    -name \"(Default)\" -value \"`\"$dir\\py.exe`\" `\"%1`\" %*\" -force
```

I'm onto something here.

**Comment by guillermooo** [comment]
Yes, it should be possible to adjust the Registry fort the current user only. Thanks for investigating!

**Comment by guillermooo** [comment]
Maybe this would help in debugging:

1) install regular python
2) install python via scoop
3) modify registry to point to scoop-based installation until it works

And then figure out scoop installation steps required. :)

**Comment by guillermooo** [comment]
More info:

https://docs.python.org/3/using/windows.html#launcher

**Comment by deevus** [comment]
WIP deevus/scoop@7aa85bf5118f38d62de01d289963a84f23bdc8b0

**Comment by deevus** [comment]
I believe this is working now: deevus/scoop@7c8a678e61d7899eee882f46a1e9ebd8c62a062a

Please test on your systems :)

**Comment by guillermooo** [comment]
Excellent! How can I test this? I don't seem to be able to refer to the .json bucket directly.

**Comment by deevus** [comment]
You can just download the json files somewhere and `scoop install ./python.json`

**Comment by guillermooo** [comment]
Awesome! Working great here! :+1: 

Thanks, @deevus !

The last thing to check is whether Python modules distributed as .exes work well too.

**Comment by lukesampson** [comment]
Works for me too.

**Comment by deevus** [comment]
@guillermooo How does that work?

**Comment by guillermooo** [comment]
Nevermind. It seems the Python world has switched to .whl.

**Comment by Haffi921** [comment]
For anyone coming back to this issue, `scoop install python` does not automatically register the installation to the Windows registry. If you're reading this you probably missed the end line of the install that says:

```console
Notes
-----
Allow applications and third-party installers to find python by running: "C:\Users\[Username]\scoop\apps\python\current\install-pep-514.reg"
```

Just run `C:\Users\[Username]\scoop\apps\python\current\install-pep-514.reg` and accept
