### ISSUE TITLE
[Request] sendmail

### ISSUE THREAD

**Issue by fritzmg** [lukesampson/scoop#3159]
For a full (nginx|apache)/(mysql|mariadb)/php setup the [fake sendmail](https://www.glob.com.au/sendmail/) application would be helpful as well. It's not updated anymore - but it would still be convenient to be able to install it via scoop and configure its `.ini` in the persist directory.

**Comment by rasa** [comment]
I use [mailsend](
https://github.com/lukesampson/scoop/blob/master/bucket/mailsend.json)

**Comment by fritzmg** [comment]
@rasa hm can this be used as a drop in replacement for sendmail in PHP and Swiftmailer?

**Comment by rasa** [comment]
@fritzmg No, sorry. I misunderstood your intent.
