### ISSUE TITLE
tree.exe

### ISSUE THREAD

**Issue by mg979** [lukesampson/scoop#3163]
Sorry if it's not the right place to ask this.

I was looking for the linux tree.exe, and I could find it here

http://gnuwin32.sourceforge.net/packages/tree.htm

There is no package in scoop that provides this command, so I downloaded that and added its directory to the PATH. The problem is that Windows has it own TREE.COM command in C:\WINDOWS\system32, and it overrides User path.

Is there a way to override system path for that command? or I might even break Windows by doing that?

**Comment by E3V3A** [comment]
Put the scoop binary PATH **before** all the windows `C:\WINDOWS\system32` PATH?

**Comment by mg979** [comment]
Thanks, I put it in global Scoop shims dir and it worked.
