### ISSUE TITLE
Can't shim 'bin\octave.bat'

### ISSUE THREAD

**Issue by shytikov** [lukesampson/scoop#3172]
It seems to be this bug is related to #2534 

I'm trying to install octave, and here what do I get:

```
scoop install octave
Installing 'octave' (5.1.0) [32bit]
octave-5.1.0-w32.zip (447,1 MB) [=============================================================================] 100%
Checking hash of octave-5.1.0-w32.zip ... ok.
Extracting octave-5.1.0-w32.zip ... done.
Linking ~\scoop\apps\octave\current => ~\scoop\apps\octave\5.1.0
Creating shim for 'octave'.
Can't shim 'bin\octave.bat': File doesn't exist.
```

I assume, as previously they have moved from `bin\octave.exe` to `bin\octave.bat`, now they have moved even further somewhere... Not sure, maybe `bin\octave-cli.exe`.

**Comment by shytikov** [comment]
Introduced by 1e00b5f76148f5e646f5e79d50aac18fe4c9f9ef

**Comment by AntiPhotonz** [comment]
It's moved to mingw32\bin\octave.bat or mingw64\bin\octave.bat now according to post-install.bat

**Comment by shytikov** [comment]
Thanks! I was not sure where to look, but now I can try to create PR for that.
