### ISSUE TITLE
detection "Trojan:PowerShell/Sacepos.C" ?

### ISSUE THREAD

**Issue by jgranduel** [lukesampson/scoop#3175]
Hi, 

when iI've tryed to install scoop on a new system (Win10/1809) with
    ` iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`
, I got a Windows Defender detection alert against Trojan PowerShell/Sacepos.C (https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:PowerShell/Sacepos.C).

What is your point about it?
Thanks

**Comment by rasa** [comment]
This issue appears to be obsolete.
