### ISSUE TITLE
Scoop update self using git (exactly like homebrew)

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#319]
Would this make it easier to know when scoop needs an update? `git status` tells you when you're behind the remote.

**Comment by deevus** [comment]
Is it worth considering any of the commands described in the [homebrew faq](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#faq)?

**Comment by deevus** [comment]
Had a go at this #320

**Comment by lukesampson** [comment]
The git update is really nice. I'll leave it to you to merge when you're ready.

Myself, I wouldn't bother adding new commands just because Homebrew has them—I'd wait until there's a clear need. But if you feel like it's a good thing to do, go ahead—I trust your judgement.

**Comment by deevus** [comment]
Yeah fair enough. We can leave those out until they come up like you said.
