### ISSUE TITLE
git@2.21.0.windows.1: extract_dir error

### ISSUE THREAD

**Issue by soapdog** [lukesampson/scoop#3191]
Receiving this error trying to install git:

~~~~ 
PS C:\Users\andre\scoop\buckets\extras> scoop install git
Installing 'git' (2.21.0.windows.1) [64bit]
Loading PortableGit-2.21.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.21.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... ERROR Exception calling "Start" with "0" argument(s): "The directory name is invalid"

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=git%402.21.0.windows.1%3a+extract_dir+error
~~~~ 

Similar error happened with alacrity as well.

**Comment by Ash258** [comment]
This usually mean that 7z is having some troubles. Could you normally use it in console?

Something like `cd $env:SCOOP\cache; 7z x 'somefile' -o"directory" -y`

**Comment by soapdog** [comment]
I suspect it was a broken download. I erased the cache folder and tried again and it worked. Will close this issue. For a while I thought there was something wrong with the recipe.
