### ISSUE TITLE
php xdebug for 7.3

### ISSUE THREAD

**Issue by silverqx** [lukesampson/scoop#3196]
Hi, php xdebug 2.7.0 for php 7.3 is missing

we have this versions of php and xdebug:
```
C:\Users\Silver Zachara> scoop search xdebug
'extras' bucket:
    php-nts-xdebug (2.7.0-7.2)
    php-xdebug (2.7.0-7.2)

'versions' bucket:
    php55-xdebug (2.5.5-5.5)
    php56-xdebug (2.5.5-5.6)
    php70-xdebug (2.6.1-7.0)
    php71-xdebug (2.7.0-7.1)
    php72-xdebug (2.7.0-7.2)

C:\Users\Silver Zachara> scoop search php
'main' bucket:
    php-nts (7.3.3)
    php (7.3.3)

'extras' bucket:
    appengine-go (1.9.70) --> includes 'php_cli.ps1'
    eclipse-php (2018-12)
    php-nts-xdebug (2.7.0-7.2)
    php-xdebug (2.7.0-7.2)

'versions' bucket:
    php54 (5.4.45)
    php55-xdebug (2.5.5-5.5)
    php55 (5.5.38)
    php56-xdebug (2.5.5-5.6)
    php56 (5.6.40)
    php70-xdebug (2.6.1-7.0)
    php70 (7.0.33)
    php71-xdebug (2.7.0-7.1)
    php71 (7.1.26)
    php72-xdebug (2.7.0-7.2)
    php72 (7.2.15)
    php73 (7.3.2)
```

I think main bucket would be good place for xdebug 2.7 for php 7.3, what do you think? @r15ch13

**Comment by niheaven** [comment]
Just update php-xdebug in extras bucket, see https://github.com/lukesampson/scoop-extras/pull/1823

**Comment by silverqx** [comment]
Yeah, its ok, thank you

**Comment by silverqx** [comment]
Hello, the same problem with xdebug for php 7.4, xdebug ext in main bucket is still for php 7.3, so it's incompatible. @niheaven

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/19b5d5de8f7cd877e21a9ae2d1adf810b566bf09 and https://github.com/ScoopInstaller/Versions/commit/9b4a7e923d34923d459c8f6332d59615e940630b

**Comment by silverqx** [comment]
thx, works fine now @r15ch13
