### ISSUE TITLE
scoop update: Option -m not recognized.

### ISSUE THREAD

**Issue by ebat79** [lukesampson/scoop#3211]
I'm in "git bash" for windows and i use this command:
`scoop update *`

and scoop output this error: "scoop update: Option -m not recognized."

**Comment by h404bi** [comment]
try `scoop update '*'` in `git-bash`

**Comment by ebat79** [comment]
It works! Thank you!

**Comment by Ash258** [comment]
`*` is alias for all files in current directory in bash.

**Comment by Ash258** [comment]
Clarified. Could be closed.
