### ISSUE TITLE
rust@1.33.0: download via aria2 failed

### ISSUE THREAD

**Issue by iXialumy** [lukesampson/scoop#3221]
Title says it.
Command line output:

> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
> Installing 'rust' (1.33.0) [64bit]
> Starting download with aria2 ...
> Download: 03/15 01:34:10 [ERROR] CUID#8 - Download aborted. URI=https://static.rust-lang.org/dist/rust-1.33.0-x86_64-pc-windows-gnu.msi
> Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
> Download: [#8cf0e3 0B/0B CN:0 DL:0B]
> Download: Download Results:
> Download: gid   |stat|avg speed  |path/URI
> Download: ======+====+===========+=======================================================
> Download: 8cf0e3|ERR |       0B/s|C:/Users/Jonas/scoop/cache/rust#1.33.0#https_static.rust-lang.org_dist_rust-1.33.0-x86_64-pc-windows-gnu.msi
> Download: Status Legend:
> Download: (ERR):error occurred.
> Download: aria2 will resume download if the transfer is restarted.
> Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
> ERROR Download failed! (Error 1) An unknown error occurred
> ERROR https://static.rust-lang.org/dist/rust-1.33.0-x86_64-pc-windows-gnu.msi
>     referer=https://static.rust-lang.org/dist/
>     dir=C:\Users\Jonas\scoop\cache
>     out=rust#1.33.0#https_static.rust-lang.org_dist_rust-1.33.0-x86_64-pc-windows-gnu.msi
> 
> ERROR & 'C:\Users\Jonas\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Jonas\scoop\cache\rust.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=15976 --continue

**Comment by iXialumy** [comment]
But it worked with aria2 disabled

**Comment by rasa** [comment]
Suppressed, Not relevant anymore
