### ISSUE TITLE
plex-server: change the url

### ISSUE THREAD

**Issue by cycledetector** [lukesampson/scoop#3224]
Updating to the latest version of plex-server throws "The remote server returned an error: (404) Not Found." since the correct url seems to be the following: https://downloads.plex.tv/plex-media-server-new/1.15.1.791-8bec0f76c/windows/PlexMediaServer-1.15.1.791-8bec0f76c-x86.exe#/installer.exe

**Comment by r15ch13** [comment]
@niheaven

**Comment by niheaven** [comment]
Okay, got it.
