### ISSUE TITLE
Vim errors out on opening the file

### ISSUE THREAD

**Issue by gbursson** [lukesampson/scoop#3228]
Get the following when trying to run vim:
same happens when no file specified.
gvim also errors out.

```
$ vim .\service-worker.js
Program 'vim.exe' failed to run: Access is deniedAt P:\Scoop\shims\vim.ps1:3 char:68
+ ... ion.expectingInput) { $input | & $path @args } else { & $path @args }
+                                                           ~~~~~~~~~~~~~.
At P:\Scoop\shims\vim.ps1:3 char:68
+ ... ion.expectingInput) { $input | & $path @args } else { & $path @args }
+                                                           ~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
+ FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by AndrewSav** [comment]
My bet is that you either have an eager anti-virus or something caused ACL corruption for the file entries affected. I tried to reproduce this and I cannot.

**Comment by gbursson** [comment]
you might be correct, after fresh reinstall, it errored out in a different way, this time pointing out the antivirus as a possible cause, I am closing the Issue
