### ISSUE TITLE
[ Request] add `apt-mark hold` equivalent

### ISSUE THREAD

**Issue by K-mikaZ** [lukesampson/scoop#3232]
> Sorry for my English.

I have some programs installed (without scoop) and when I do `list` (**local**), they detect them anyway.

For example, I would like to make an `apt-mark hold $relevantApp`, to be able to do an `update *`, without scoop supporting these programs (instead of doing` update * --except long list of application`).

I hope I have been clear enough.

**Comment by AndrewSav** [comment]
I'm not sure how is this even possible for scoop to list apps that it did not install. The list command does `Get-ChildItem $dir` on the scoop apps dir. If you did not install your apps into the scoop dir (which you should not) they won't be either listed or updated.
