### ISSUE TITLE
Community: Discord server for Scoop

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop#3240]
IMO, it's better than Gitter in all respects nowadays. And so many open source projects hosts their Discord server, such as [Yarn](https://discord.gg/yarnpkg), [Godot Engine](https://discord.gg/zH7NUgz), and ... [https://discordapp.com/open-source](https://discordapp.com/open-source).

**Comment by r15ch13** [comment]
Which country should the server be in? :smile:

**Comment by h404bi** [comment]
@r15ch13 Yes, it can be changed later. It's ok to use the default `US West` region I think.

**Comment by r15ch13** [comment]
https://discord.gg/Gj5ZtfR

**Comment by h404bi** [comment]
[![Discord Chat](https://img.shields.io/badge/chat-on%20discord-7289DA.svg)](https://discord.gg/Gj5ZtfR)
```
    <a href="https://discord.gg/Gj5ZtfR">
        <img src="https://img.shields.io/badge/chat-on%20discord-7289DA.svg" alt="Discord Chat" />
    </a>
```

Let's add the badge to README.

**Comment by r15ch13** [comment]
@h404bi create a PR :smile:

**Comment by r15ch13** [comment]
When we have agreed on a logo we could add it to https://github.com/discordapp/discord-open-source :smile:

**Comment by h404bi** [comment]
Yeah, strong desire for a logo..
