### ISSUE TITLE
vim: :shell throws executionpolicy error

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#325]
Scoop default setting:

```
set shell=set shell=C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
```

This throws an error.

This seems to fix it:

```
set shell=set shell=C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe\ -executionpolicy\ bypass
```

**Comment by guillermooo** [comment]
The error occurs when you try to use `:shell`, btw.

**Comment by deevus** [comment]
I have noticed this as well. Care to make a PR with the solution?

**Comment by guillermooo** [comment]
Sure. I'll give it a try.

**Comment by lukesampson** [comment]
Do we need to update the vim.json manifest as well to fix this?

**Comment by deevus** [comment]
@lukesampson Ah lol that didn't even register :) 

@guillermooo Please add this to the `vim.json` manifest file as well.
