### ISSUE TITLE
Update the cutter manifest for version 1.8.0

### ISSUE THREAD

**Issue by cycledetector** [lukesampson/scoop#3251]
Cutter was updated to version 1.8.0 and 32-bit binaries support was dropped. 
The new hash is `e7d747d2c088ba5eb6114e386cc82aa8174a2a8296ea6fcd75dce3fa339a9850`.

**Comment by brandon93s** [comment]
Closed in https://github.com/lukesampson/scoop/commit/f56b34af2cfd787bde085feb8d1e4f664b931922
