### ISSUE TITLE
dart: how to check for version against a GET request

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#326]
Dart publishes the current version at a GET endpoint.

In a scoop app manifest, where do I put a script that downloads the Json data to check for the version? I've tried to figure this out, but haven't found any example.

Feel free to assign me to this.

**Comment by deevus** [comment]
It looks like the latest stable version is displayed on their homepage: https://www.dartlang.org/ 

    CURRENT STABLE VERSION OF DART: 1.9.1

Can we just use that?

**Comment by guillermooo** [comment]
I'm afraid not. This is what `invoke-webrequest` returns:

```html
<span class="editor-build-rev-stable">[calculating]</span>
```

**Comment by lukesampson** [comment]
checkver just downloads a URL and uses a regular expression to find the version string, so it works with JSON as well as HTML. There's an extended syntax if you need to check a different URL to the homepage—there's a bit more info [here](https://github.com/lukesampson/scoop/wiki/App-Manifests) under `checkver`.
