### ISSUE TITLE
Multiple PHP versions at the same time?

### ISSUE THREAD

**Issue by borekb** [lukesampson/scoop#3262]
Would Scoop be able to help me with a use case where I need to have multiple versions of PHP installed, and switch between them? For Node.js, I use `nvs` but I'm not sure if this is something that Scoop could do.

**Comment by Ash258** [comment]
You should be able to do something like this: 

```powershell
scoop bucket add versions
scoop install php54
... do something with php 5.4
scoop install php73
... do something with php 7.3
scoop reset php54 # Again use php 5.4
scoop reset php73
...
```

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/wiki/Switching-Ruby-And-Python-Versions

**Comment by borekb** [comment]
Awesome, thank you, I actually visited that wiki page before but didn't realize that the `versions` bucket contained also PHP (and many other things!). Maybe the wiki page should mention that for noobs like me :)

**Comment by karypid** [comment]
Some packages though don't have multiple names perversion. For example:

```
> scoop search maven
'main' bucket:
    maven (3.8.6)
```

I assume that if I want an older version of maven that is impossible to get with scoop?

**Comment by rashil2000** [comment]
You can try `scoop install maven@3.8.5`

**Comment by karypid** [comment]
> You can try `scoop install maven@3.8.5`

Thanks, this worked and is extremely useful.

Is there a command to also list available version? For example I just installed 3.6.3 (which I needed) but am wondering how many versions are available...

**Comment by rashil2000** [comment]
Versions other than current are auto-generated from the latest manifest (by replacing the URLs), they are not listed anywhere. For alternative variants of packages, use the https://github.com/ScoopInstaller/Versions bucket.

**Comment by MahdiAkrami01** [comment]
I made a tutorial on how to have multiple PHP versions at the same time:

https://github.com/MahdiAkrami01/scoop-bucket
