### ISSUE TITLE
Uninstalling scoop

### ISSUE THREAD

**Issue by mghildiy** [lukesampson/scoop#3269]
Hi,

I installed scoop few days back , and installed an application with it, and now I am facing issues.

First, it modified default location of my ssh keys and set it to a totally new location. This broke down my git commands.

So, when I try to uninstall it 'scoop uninstall scoop, I get error:

Get-ChildItem : Cannot find path 'C:\Users\<XXX>\true\shims' because it does not exist.
At C:\Users\<XXX>\scoop\apps\scoop\current\lib\commands.ps1:3 char:12
++ (Get-ChildItem "$scoopdir\shims") `
CategoryInfo          : ObjectNotFound: (C:\Users\<XXX>\true\shims:String) [Get-ChildItem], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

<XXX> is my username.

**Comment by niheaven** [comment]
What app do you install using scoop? Could you try to delete scoop folder and install scoop again and then try uninstall?

**Comment by mghildiy** [comment]
I installed bloop.

https://scalacenter.github.io/bloop/setup

**Comment by niheaven** [comment]
bloop manifest in their bucket (https://github.com/scalacenter/scoop-bloop/blob/master/bloop.json) is a questionable one that change your `$env:HOME` and `$env:SCOOP`... Please delete them or change `$env:SCOOP` to your actual location, then use scoop or try to uninstall it.

**Comment by rasa** [comment]
This is an issue in a third party bucket. Manifest could be added to https://github.com/ScoopInstaller/Main
