### ISSUE TITLE
Can scoop install docker for windows?

### ISSUE THREAD

**Issue by jiayaoO3O** [lukesampson/scoop#3272]
I used `scoop install docker` to install docker, but I don't even know how to start it. I tried to use `docker run hello-world` after installation, but it failed. What should I do before using **Docker Toolbox**? Can scoop install **Docker for Windows** instead of **Docker Toolbox**?

**Comment by Ash258** [comment]
You could use docker from my bucket. (https://github.com/Ash258/scoop-Ash258/blob/master/bucket/docker.json)

There was some discussion with @r15ch13 about docker for windows in extras, bucket but i don't know result of this conversation 😂 

@r15ch13  Do you know, where we talked about docker for windows?

**Comment by jiayaoO3O** [comment]
> 你可以从我的桶里使用docker。（https://github.com/Ash258/scoop-Ash258/blob/master/bucket/docker.json）
> 
> @ r15ch13讨论了关于docker for windows的额外内容，但是我不知道这个对话的结果😂
> 
> @ r15ch13 你知道吗，我们在哪里谈到windows的docker？

thanks,I will try :+1:

**Comment by Ash258** [comment]
@r15ch13 Found it 😃 #3082

**Comment by jiayaoO3O** [comment]
> 你可以从我的桶里使用docker。（https://github.com/Ash258/scoop-Ash258/blob/master/bucket/docker.json）
> 
> @ r15ch13讨论了关于docker for windows的额外内容，但是我不知道这个对话的结果😂
> 
> @ r15ch13 你知道吗，我们在哪里谈到windows的docker？
![image](https://user-images.githubusercontent.com/22891632/55081978-cc783280-50db-11e9-956b-55f3670a3e1b.png)
Installation failed

**Comment by Ash258** [comment]
You need to use raw github url if you want to install it this way.
`scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json`

![image](https://user-images.githubusercontent.com/13260377/55082281-b2b9f980-50a1-11e9-9deb-bce60b142dad.png)

**Comment by jiayaoO3O** [comment]
> You need to use raw github url if you want to install it this way.
> `scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json`
> 
> ![image](https://user-images.githubusercontent.com/13260377/55082281-b2b9f980-50a1-11e9-9deb-bce60b142dad.png)
I installed successfully!!! Thanks
But is this different from double-clicking `Docker for Windows Installer.exe`? Can docker be installed only in `C:\Program Files\Docker\Docker` instead of `C:\Users\jiayao\scoop\apps`?

**Comment by Ash258** [comment]
Unfortunately. As said in notes. There is no possible way how to force docker installation into scoopdir. At least there were before few months. Haven't checked from then.

**Comment by jiayaoO3O** [comment]
ok ,still thanks!

**Comment by kid1412621** [comment]
can install, but cannot recognize by vscode

**Comment by francjpd** [comment]
When i try to install docker  with ``` scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json``` it prompts me to log in with admin rights.

Docker%20for%20Windows%20Installer.exe (834,8 MB) [===========================================================] 100%
Running pre-install script...
Running installer... [15:35:10.186] [InstallHandler] Not run as admin, relaunching with UAC prompt
System.ComponentModel.Win32Exception (0x80004005): El usuario ha cancelado la operación
   en System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   en CommunityInstaller.ProcessEnvironmentDetector.RelaunchAsAdmin(String[] args)
   en CommunityInstaller.Program.Main(String[] args)

**Comment by Ash258** [comment]
And? ... I do not see any issue. Is somewhere in my bucket said it is UAC prompt free?

**Comment by francjpd** [comment]
Well the main page of Scoop says:

> **Say goodbye to permission pop-ups**
> Scoop installs programs to your home directory by default. So you don’t need **admin permissions** to install programs, and you won’t see **UAC popups** every time you need to add or remove a program.

I expected all buckets from scoop to Free from  asking for admin rights. I guess i am wrong.

**Comment by kid1412621** [comment]
what causes this?
![image](https://user-images.githubusercontent.com/26278054/67853119-d3bb5f00-fb48-11e9-8757-76e62b5a864c.png)

**Comment by Ash258** [comment]
I would say you miss innounp.

`scoop install innounp`

**Comment by kid1412621** [comment]
> I would say you miss innounp.
> 
> `scoop install innounp`

I've installed.

**Comment by Ash258** [comment]
Then open new issue using link from screenshot. I cannot test / investigate further right now.

**Comment by kid1412621** [comment]
> I would say you miss innounp.
> 
> `scoop install innounp`

thanks, my bad. scoop said it's installed. but it(innounp) seems broken or previous installation failed.
I reinstalled it, problem solved.

**Comment by kid1412621** [comment]
@Ash258 Could you tell me how to add docker daemon to windows service after installation? Cannot find any relative document.

**Comment by Ash258** [comment]
No

**Comment by aadamsx** [comment]
This URL is invalid: 

```https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json```

**Comment by iamxiaojianzheng** [comment]
> When I run:
> 
> ```
> C:\> scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json
> ```
> 
> I get the following error:
> 
> ```
> WARN  error: The remote name could not be resolved: 'http'
> Couldn't find manifest for 'https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json'.
> ```
> 
> Note I'm on Windows 10

new link: https://raw.githubusercontent.com/Ash258/Shovel-Ash258/main/bucket/docker.yml

**Comment by skysin** [comment]
1. add [apps] bucket in https://github.com/kkzzhizhou/scoop-apps
2. scoop install sudo
3. sudo scoop install docker-desktop

can install docker-desktop in scoop path

note: maybe need change the docker related system path from nightly-20XXXXXX to current

~~~
WARN  Installer added 'C:\Users\XXXXXX\scoop\apps\docker-desktop\nightly-20230605\resources\bin' to system path. You might want to remove this manually (requires admin permission).
~~~
