### ISSUE TITLE
[Request] Multrin

### ISSUE THREAD

**Issue by OzakIOne** [lukesampson/scoop#3286]
https://github.com/sentialx/multrin
https://github.com/sentialx/multrin/releases/tag/v0.3.1

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop-extras/pull/2208

**Comment by rasa** [comment]
Fixed with lukesampson/scoop-extras@ef891b8f0139517c9008c14465b05ccafe0f24ad
