### ISSUE TITLE
7zip: Use github for download or add a switch -source to scoop install or use 7zip installed elsewhere

### ISSUE THREAD

**Issue by copdips** [lukesampson/scoop#3287]
As mentioned in #3230 , 7zip from https://7-zip.org/ or from https://downloads.sourceforge.net/project/sevenzip/7-Zip/  cannot make everyone happy, why just host it on github, as Scoop itself is on github.

Not only https://7-zip.org/ is not allowed in some countries, it is often blocked by some security policies in some entreprises even in countries where https://7-zip.org/ is allowed. (I'm in France) 7zip is deployed by our sysadmins out of Scoop.

Without 7zip, many scoop packages cannot work.
It's not an ordinary external package for Scoop, it's a core package which should make it as available as possible to everyone.

1. If 7zip cannot be hosted on github, is it possible to add a switch to `scoop install 7zip` something like `-source` in order to let users to choose their preferred download source.

1. Or please tell us how to ask Scoop to use the 7zip installed elsewhere which is not installed by Scoop.

**Comment by copdips** [comment]
what about this one ?
https://github.com/scoopinstaller/binary-mirror

**Comment by niheaven** [comment]
You can use 7zip-zstd which is hosted in GitHub, and a config option could be set to determine to use which one. Please wait for these works.

**Comment by copdips** [comment]
thx for your reply, may I know how long it will be released

**Comment by maanur** [comment]
Any updates on this one?

**Comment by niheaven** [comment]
See #3204, waiting for merging.
