### ISSUE TITLE
Should filename of manifest be lowercase?

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3295]
I find almost all filenames are lowercase, is this a rule? And how does scoop name the app directory? :confused:

**Comment by Calinou** [comment]
> And how does scoop name the app directory?

The app directory is located in `%USERPROFILE%/scoop/apps/<app name>` by default, the appdirectory's name matches the name of the manifest file.

**Comment by linsui** [comment]
Thanks :ok_hand:
