### ISSUE TITLE
Local bucket

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3298]
I would like such a bucket which is only a local directory containing some manifest. And it could be updated by `scoop update`. I don't want to checkver and push periodically. Or is there any way to achieve similar results? Thanks.

**Comment by niheaven** [comment]
You can run `.\bin\checkver.ps1 * -u` in this local bucket yourself to make these manifests updated, `scoop update` wouldn't run `checkver` for you.

Or you can hardlink some manifests in `scoop`'s buckets to this local bucket, so as to let `scoop` update these manifests and their hardlinks.

**Comment by linsui** [comment]
Thanks for your answer, but it is not convenient. Scoop ask for a remote repo to pull and now I have to maintain a local repo  which only be used by myself and I need to checkver manually. After update the repo, I have to run `scoop update` to  pull from a local repo. So I wonder if there is any way to track the update more easily by just write a autoupdate manifest.

**Comment by niheaven** [comment]
You can fork `https://github.com/Ash258/GenericBucket` and rename it to something else. `checkver` IS REQUIRED to be run by yourself in this bucket.

You can just put manifests in this bucket, left them untracked by git, `checkver` periodically. Or you can hardlink some manifest from other buckets to this one (but why?)

**Comment by linsui** [comment]
Thanks for your advice, the repo is helpful. :+1:  My purpose is maintaining a bucket locally without a remote repo.  And if I don't need to pull from a remote repo, I don't need a local repo, either. I only need a directory containing some manifest. Maybe I should use a script to checkver before update?
