### ISSUE TITLE
[Clarification] Shortcuts property

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3302]
All manifest properties are named using singular form (cookie, bin, url, ...) even when they could be arrays, but only shortcuts property uses plural form. What's the reason for this plural form?

**Comment by r15ch13** [comment]
It was originally implemented in 2016 with https://github.com/lukesampson/scoop/pull/679 and never changed since then. :smile:
Could be easily changed and be backwards compatible.

**Comment by Ash258** [comment]
Little bit off topic, which does not deserve separate issue.

Why is `extract_to` marked as deprecated?

**Comment by r15ch13** [comment]
I don't know, @rasa changed it with https://github.com/lukesampson/scoop/commit/b5ed0761aef4f3e864533dc0460d110115850ba7 :smile:
