### ISSUE TITLE
Error in nunit-console.json

### ISSUE THREAD

**Issue by hoest** [lukesampson/scoop#3304]
There is an error in the `scoop/bucket/nunit-console.json`

```json
    "url": "https://github.com/nunit/nunit-console/releases/download/v3.10/NUnit.Console-3.10.0.zip",
    "hash": "64f4420a90a3ee12c60a13d7162ac52e32b84b704bfd54b9e9d6d4500313d0ac",
    "bin": "nunit3-console.exe",
```

The `bin` binding is to `nunit3-console.exe`. As from version 3.10, nunit-console has multiple executables in specific directories:

![image](https://user-images.githubusercontent.com/606546/55609165-57ae9380-5780-11e9-896e-bc1adfa5cdae.png)

Hopefully this can be fixed!

Thanks in advance!

**Comment by r15ch13** [comment]
```
This release merges the .NET Standard version of the engine back into the nunit.engine NuGet package and adds a .NET Standard 2.0 version of the engine that re-enables most services and extensions. This deprecates the nunit.engine.netstandard NuGet package. Any test runners using the old .NET Standard version of the engine should switch to this release.
```
Should we link both files or just 2.0 or 3.5?

**Comment by hoest** [comment]
I think the most recent one?



Op ma 8 apr. 2019 om 18:39 schreef Richard Kuhnt <notifications@github.com>
