### ISSUE TITLE
aria2 proxy error and not use aria2 for some app

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3305]
I have to download go through proxy. It works fine when `scoop config aria2-enabled false` but will get `ERROR Download failed! (Error 1) An unknown error occurred` when scoop uses aria2. Maybe there is some error in aria2. Is there any way to config scoop not use aria2 for some app?

**Comment by linsui** [comment]
I solve this problem by `--check-certificate=false` https://github.com/VonSdite/Aria2/issues/1#issuecomment-292798341

**Comment by ltguillaume** [comment]
@linsui 
I see [Aria2-Next](https://github.com/AnInsomniacy/aria2-next/) has fixed the need for `--check-certificate false` with https://github.com/AnInsomniacy/aria2-next/commit/7983e17c2ebf8c64a1b27536ff5bb3d00beacb21#diff-799d44e7ac2c92a49df1de58eb6fdff2f489adf179170c5462847b9a7b2d4806

Considering Aria2 is stale, I'd say it would be good to support Aria2-Next, which is still in active development.

I've made a drop-in replacement manifest https://github.com/ltguillaume/schep/blob/main/bucket/aria2.json to test it and everything works fine now.

**Comment by linsui** [comment]
I have stopped using scoop and windows since years ago. Please open a new issue.
