### ISSUE TITLE
Why is `extract_to` deprecated?

### ISSUE THREAD

**Issue by niheaven** [lukesampson/scoop#3312]
Think about https://github.com/lukesampson/scoop-extras/blob/master/bucket/irfanview.json, https://github.com/scoopinstaller/versions/blob/master/bucket/ruby19.json (two urls with second extract to some dir), or even https://github.com/scoopinstaller/versions/blob/master/bucket/atom-portable.json (wrap into some dir), it's hard to implement with some install scripts, or is not as clarified as `extract_to`. What is the background of deprecating `extract_to`?

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/issues/3302#issuecomment-480820315

**Comment by niheaven** [comment]
I'm trying to deprecate `extract_to` by some install scripts, but it is... too hard... `Move-Item` leads to some error for moving dir cases, and for multi-urls cases, it's too complicated.

**Comment by Ash258** [comment]
I do not see a valid reason to deprecate it. It's nice shortcut for pre_install with `Move-Item * $to`

**Comment by niheaven** [comment]
For example, https://github.com/lukesampson/scoop-extras/blob/master/bucket/hadoop-winutils.json, `extract_to` could be replaced with

```json
"pre_install": [
    "ensure \"$dir\\bin\" | Out-Null",
    "Move-Item \"$dir\\*\" \"$dir\\bin\" -ea Ignore"
],
```

Without `-ea Ignore`, it would give a `MoveDirectoryItemIOError`, and it means move items twice (one for extraction, one for `pre_install` scripts).

`extract_to` shouldn't be deprecated, it's useful for some special cases.

**Comment by Ash258** [comment]
I have to use `extract_to` inside all portable JetBrains manifests, due to update error and this property will save me some `pre_install` blocks and easily copying into multiple manifests.

**Comment by niheaven** [comment]
So, could scoop leave `extract_to` alone without deprecated tag?

**Comment by Ash258** [comment]
In my opinion definitely. But main word has collaborators.

**Comment by r15ch13** [comment]
It's now on active duty again. Wiki needs an update. :smile:

**Comment by niheaven** [comment]
Wiki updated.
