### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by gabaggrey** [lukesampson/scoop#3323]
![openssh issues](https://user-images.githubusercontent.com/12617048/56026035-3b27d380-5d0b-11e9-8749-f730e1a30887.png)
 please help

**Comment by r15ch13** [comment]
Please run `scoop uninstall openssh` and retry again.
The download server `http://repo.msys2.org` is not the most reliable one. 😢
Or try `win32-openssh`, `git-with-openssh` or `mls-software-openssh`

**Comment by gabaggrey** [comment]
lol...at the tabs.

It worked. Thanks.
I did the installed and tried again
