### ISSUE TITLE
Would scoop update its minimum recommended PowerShell version to 5?

### ISSUE THREAD

**Issue by niheaven** [lukesampson/scoop#3325]
https://github.com/lukesampson/scoop/issues/2402, https://github.com/lukesampson/scoop-extras/pull/1993#issuecomment-482459556

Would scoop update to PS 5? Appveyor CI check only check 5 and 6, and 5 has several useful new cmdlet, e.g. `Expand-Archive`.

Windows 7 has PS 2, and 8 has 3, 8.1 has 4, 10 has 5, and I think the major Windows version that user has should be 10 and 7. For Windows 10, no update is needed, for Windows 7, there is no difference to update to 3 or 5.

**Comment by E3V3A** [comment]
That is a good idea, but I'm not sure where you sourced that information. 
Windows 8.1 is using PS 5.1, at least if you're keeping your system updated. 
In addition you can always install a Powershell Core which (AFAIK) will replace Powershell, to up the version to whatever you like. E.g. you can use 6.2 on W8.1. 

And for whoever, is still using W7 and below, it's probably time to move on.
