### ISSUE TITLE
scoop does not detect new java versions

### ISSUE THREAD

**Issue by se35710** [lukesampson/scoop#3329]
```
PS C:> scoop update oraclejdk
Latest versions for all apps are installed! For more information try 'scoop status'
[..]
PS C:> scoop update -f oraclejdk
oraclejdk: 12-33 -> 12.0.1-12 (global)
Updating one outdated app:
[..]
Updating 'oraclejdk' (12-33 -> 12.0.1-12)
Downloading new version
Starting download with aria2 ...
[..]
```

Ref: https://gitter.im/lukesampson/scoop?at=5ca87f711f6e900d5ee9881f

**Comment by Ash258** [comment]
Relates: #2981, #2720

**Comment by niheaven** [comment]
The version number in #2720 is hard to compare. Why `1.1.1_8` is prior to `1.1.1`?

**Comment by se35710** [comment]
We should stop comparing and just check if the manifest version is different from the installed version...

**Comment by niheaven** [comment]
That means more code check and will be done tomorrow.

**Comment by niheaven** [comment]
Done, #3333 just install version in manifest while update.

Just modify one operator in lib/core.ps1#L193

**Comment by se35710** [comment]
If the version dir already exist during "upgrade", for example a rollback of version from upstream maintainer, will the upgrade work or fail?

**Comment by niheaven** [comment]
If the version number is not changed, nothing happened since no update. If version number is rollback, then install prior version and `current` dir will link to this version dir.

**Comment by Ash258** [comment]
Duplicate of #2720
