### ISSUE TITLE
App: oraclejdk8: Manifest removed

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop#3334]
While I've been using scoop for a while, I am not sure what this means:

These app manifests have been removed:
    oraclejdk8

AFAIK, adb from android-sdk still requires Java 1.8, all attempts in the past year I've made with newer java resulting in weird issues.   Was this app removed?

**Comment by se35710** [comment]
Oracle does not distribute Oracle Java 8 anymore. Use one of the alternatives in scoop-java. I would go with AdoptOpenJDK or Zulu.

**Comment by rasa** [comment]
Invalid, Clarified in java bucket
