### ISSUE TITLE
youtube-dl not updating to latest

### ISSUE THREAD

**Issue by knightknight** [lukesampson/scoop#3335]
The current version of youtube-dl with scoop is returning is 2019.04.07. The latest version of [youtube-dl](https://github.com/ytdl-org/youtube-dl/releases/tag/2019.04.17/) is 2019.04.17 and the latest [youtube-dl bucket](https://github.com/lukesampson/scoop/blob/master/bucket/youtube-dl.json) in scoop is also 2019.04.17, but my version is returning 2019.04.07.

I've confirmed this with running [youtube-dl.exe](https://github.com/ytdl-org/youtube-dl/releases/tag/2019.04.17/) downloaded from youtube-dl repo. 

```
~ $ scoop install youtube-dl
Installing 'youtube-dl' (2019.04.17) [64bit]
Loading youtube-dl.exe from cache.
Checking hash of youtube-dl.exe ... ok.
Linking ~\scoop\apps\youtube-dl\current => ~\scoop\apps\youtube-dl\2019.04.17
Creating shim for 'youtube-dl'.
'youtube-dl' (2019.04.17) was installed successfully!

~ $ youtube-dl --version
2019.04.07
```

**Comment by knightknight** [comment]
Not totally sure... but it's working with the 2019-04-17 version now.

Although I uninstalled, ran checkup and deleted any youtube-dl file in the cache folder.

**Comment by knightknight** [comment]
It seems after running into an error with [Spotdl](https://github.com/ritiek/spotify-downloader), I've found there is a conflict with youtube-dl. Spotdl uses youtube-dl but installs via pip `pip3 install youtube-dl -U` which then installs youtube-dl to `C:\Users\user\scoop\apps\python\current\Scripts\`.  When you run `scoop which` it will favour the pip install path which is why I had various versions installed that never seemed to update.

Is there anyway of getting Spotdl as a bucket to overcome this conflict?

**Comment by rasa** [comment]
This issue appears to be obsolete.
