### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by ghost** [lukesampson/scoop#3344]
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/gcc-libs-6.4.0-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    892a8125b41e2c11f26769755bec092b55c8d0c6c78bf8bd2c61d977df7e1fbd
Actual:      a746d0f99e9f1ae90d2023aca8a0241f92b9410702ca0bf2346b642c3ee9de9a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by rasa** [comment]
Obsolete
