### ISSUE TITLE
Extracting package ... Exit code was -1

### ISSUE THREAD

**Issue by Frozzom** [lukesampson/scoop#3346]
Hello there, 
I'm using Windows 10 Version 1803 
when installing certain Packages (mp3tag and thunderbird in my example) with scoop i get the Error code -1 when extracting. 
However, this doesn't happen for every Package as you can see syncthing is working just fine.
Powershell's ```$PSVersionTable.PSVersion``` output is: ```5      1      17134  590```

I already tried reinstalling scoop, removing the package with 'uninstall' and 'cache rm'.

```
PS C:\WINDOWS\system32> scoop install mp3tag
Installing 'mp3tag' (2.95) [64bit]
Loading mp3tagv295setup.exe from cache
Checking hash of mp3tagv295setup.exe ... ok.
Extracting mp3tagv295setup.exe#dl.7z ... Exit code was -1.

PS C:\WINDOWS\system32> scoop install syncthing
Installing 'syncthing' (1.1.1) [64bit]
Loading syncthing-windows-amd64-v1.1.1.zip from cache
Checking hash of syncthing-windows-amd64-v1.1.1.zip ... ok.
Extracting syncthing-windows-amd64-v1.1.1.zip ... done.
Linking E:\Apps\apps\syncthing\current => E:\Apps\apps\syncthing\1.1.1
Creating shim for 'syncthing'.
'syncthing' (1.1.1) was installed successfully!
Notes
-----
To start syncthing automatically, use a method described at
https://github.com/syncthing/docs/blob/master/users/autostart.rst#windows

PS C:\WINDOWS\system32> scoop install thunderbird
Installing 'thunderbird' (60.6.1) [64bit]
thunderbird-setup_x64.7z (34,1 MB) [==========================================================================] 100%
Checking hash of thunderbird-setup_x64.7z ... ok.
Extracting thunderbird-setup_x64.7z ... Exit code was -1.
```

Is this just a configuration problem on my system or an issue?

**Comment by Ash258** [comment]
This is problem with your installation of 7zip.

**Comment by Frozzom** [comment]
Thanks for the answer, however I can't really track down, what's supposedly wrong with the installation.
Nevertheless i uninstalled 7zip and ran the install for mp3tag again.

Even after 7zip automatically reinstalls i end up with the same error message.
```
PS C:\WINDOWS\system32> sudo scoop install mp3tag
Installing '7zip' (19.00) [64bit]
Loading 7z1900-x64.msi from cache
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking E:\Apps\apps\7zip\current => E:\Apps\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'mp3tag' (2.95) [64bit]
Loading mp3tagv295setup.exe from cache
Checking hash of mp3tagv295setup.exe ... ok.
Extracting mp3tagv295setup.exe#dl.7z ... Exit code was -1.
```

**Comment by Ash258** [comment]
What is result when you execute `7z x mp3tagfile` when you execute it manually from cache folder?

**Comment by h404bi** [comment]
Have you installed a system-wide 7zip?

**Comment by Frozzom** [comment]
Thanks to both of you, it's working now.

Running 
```
PS E:\Apps\cache> 7z x .\mp3tag#2.95#https_download.mp3tag.de_mp3tagv295setup.exe_dl.7z
Cannot find file at 'e:\applications\7zip\7z.exe' (e:\applications\7zip\7z.exe). This usually indicates a missing or moved file.
``` 
resulted in the folder 'applications' (which i used before trying scoop).
Indicating what h404bi assumed, it isn't installed globally.
Therefore installing 7zip with the --global flag, and running scoop install mp3tag worked.

Whats a bit confusing to me is still the following:
```
PS E:\apps\apps> scoop list
Installed apps:

  7zip 19.00 *global*
  7zip 19.00
  calibre 3.41.3 [extras]
  calibre 3.41.3 *global* [extras]
```
i installed calibre without the --global tag and it still lists it as *global*, which is why i didn't assume it wasn't installed globally

**Comment by rasa** [comment]
Clarified
