### ISSUE TITLE
Cannot find path 'C:\Users\xxx\scoop\buckets' because it does not exist.

### ISSUE THREAD

**Issue by Summon528** [lukesampson/scoop#3349]
On a clean install scoop
```ps1
> scoop search vim

Get-ChildItem : Cannot find path 'C:\Users\xxx\scoop\buckets' because it does not exist.
At C:\Users\xxx\scoop\apps\scoop\current\lib\buckets.ps1:50 char:13
+     return (Get-ChildItem $bucketsdir).Name
+             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\xxx\scoop\buckets:String) [Get-ChildItem]    , ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 ```

Probably due to the recent change with buckets function. Is there any reason to remove ` if(test-path $bucketsdir)` ?

New Code:
https://github.com/lukesampson/scoop/blob/d0a1d4fe64e4e8194ba51b68b85438030fa2489c/lib/buckets.ps1#L44-L51

Old Code:
https://github.com/lukesampson/scoop/blob/54235efe5999328cf350e1d13ff4d70b3be51f7f/lib/buckets.ps1#L42-L48

**Comment by Ash258** [comment]
I hoped buckets dir is created on installation.

**Comment by Ash258** [comment]
@r15ch13 That check is redundant for working. Is there any reason why all needed directories are not created after installation? buckets, workspace, persist, ...

**Comment by Summon528** [comment]
Even we decieded to modify install script, we still have to add that check back right? Cause it print some unwanted error message for exsiting user who never touch buckets dir.

**Comment by Ash258** [comment]
No. Simply supressing that error is enough.
