### ISSUE TITLE
Invalid JSON in the wiki

### ISSUE THREAD

**Issue by MCOfficer** [lukesampson/scoop#3359]
The wiki has a small typo in one of its codeblocks, the first json [here](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#add-autoupdate-to-a-manifest) has a comma after the `architecture` block.

**Comment by sidletsky** [comment]
fixed in revision [db8b6c3](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate/db8b6c38ef00382583655f50fcfcf2bfe2b0df55)
