### ISSUE TITLE
wget@1.20.3: hash check failed

### ISSUE THREAD

**Issue by miguelpardal** [lukesampson/scoop#3365]
Updating 'wget' (1.20 -> 1.20.3)
Downloading new version
wget-1.20.3-win64.zip (4,7 MB) [==================================================] 100%
Checking hash of wget-1.20.3-win64.zip ... ERROR Hash check failed!
App:         wget
URL:         https://eternallybored.org/misc/wget/releases/wget-1.20.3-win64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9dea6d658ab14a77958233a116a86bc2f5adb1feb425848d58f918d354bdd1ea
Actual:      7ef40a647a153accbfb8cd79b3d9e3bf8ac1bab95b704176e3172589285a13de

**Comment by rasa** [comment]
Bugfixed https://eternallybored.org/misc/wget/
