### ISSUE TITLE
qemu not creating shims for RISC-V and HP/PA

### ISSUE THREAD

**Issue by Arcterus** [lukesampson/scoop#3370]
It seems they are installed as part of the package but are just missing the shims.

**Comment by Arcterus** [comment]
Also I believe there's a newer version of qemu available.

**Comment by r15ch13** [comment]
Fixed with https://github.com/scoopinstaller/scoop-main/commit/c0327aba20bee82d4519f0d001377b22facf1cf6
There is build from 2019-02-18 it has no version number yet.
