### ISSUE TITLE
youtube-dl not updating to latest 2019.04.24

### ISSUE THREAD

**Issue by DukeFox** [lukesampson/scoop#3371]
youtube-dl not updating to latest 2019.04.24

**Comment by niheaven** [comment]
ref: https://github.com/lukesampson/scoop/pull/3060

Please wait for a few days for scoop-core migration. If you like to try `develop` version of scoop, ref: https://github.com/lukesampson/scoop/pull/3367#issuecomment-486597453

**Comment by niheaven** [comment]
Closed by https://github.com/scoopinstaller/scoop-main/commit/d5ff199ea999fdf2f9378919c1775e13052e9c1e
