### ISSUE TITLE
Will scoop-core related PR chang merging target to 'develop' branch?

### ISSUE THREAD

**Issue by niheaven** [lukesampson/scoop#3376]
Or still target to 'master'?

**Comment by Ash258** [comment]
I hope so. After bucket extraction is done we could adopt proper support for #2939. Then all prs will be merged into develop, when it will be tested for few days and then it could be merged into master.

I would propsed this flow:

1. Create PR against `develop`
    1. Review
    1. Merge
1. Wait for early adopters to report some bugs.
1. If there are none / all are fixed
    1. Create PR from `develop` to `master`
1. Merge it to `master` for everyone

1. Repeat with next PR

This will make sure that pr is safe for wider user base, rather then pushing PRs into master directly, so normal user will not experience so much bugs.
