### ISSUE TITLE
scoop cache rm * does not work

### ISSUE THREAD

**Issue by n00d1e5** [lukesampson/scoop#3378]
$ scoop cache show
>...
> 83.4 MB chromium (71.0.3578.98-r599034)  ...p_chromium_releases_download_v71.0.3578.98-r599034-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.109-r612437) ..._chromium_releases_download_v72.0.3626.109-r612437-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.119-r612437) ..._chromium_releases_download_v72.0.3626.119-r612437-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.121-r612437) ..._chromium_releases_download_v72.0.3626.121-r612437-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.103-r625896) ..._chromium_releases_download_v73.0.3683.103-r625896-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.75-r625896)  ...p_chromium_releases_download_v73.0.3683.75-r625896-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.86-r625896)  ...p_chromium_releases_download_v73.0.3683.86-r625896-win64_chromium-sync.zip
>86.0 MB chromium (74.0.3729.108-r638880) ..._chromium_releases_download_v74.0.3729.108-r638880-win64_chromium-sync.zip
>...
>Total: 52 files, 2.9 GB

$ scoop help cache
>Usage: scoop cache show|rm [app]
>
>Scoop caches downloads so you don't need to download the same files
>when you uninstall and re-install the same version of an app.
>
>You can use
>scoop cache show
>to see what's in the cache, and
>    scoop cache rm <app> to remove downloads for a specific app.
>
>To clear everything in your cache, use:
>    scoop cache rm *

$ scoop cache rm *

$ scoop cache show
>...
> 83.4 MB chromium (71.0.3578.98-r599034)  ...p_chromium_releases_download_v71.0.3578.98-r599034-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.109-r612437) ..._chromium_releases_download_v72.0.3626.109-r612437-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.119-r612437) ..._chromium_releases_download_v72.0.3626.119-r612437-win64_chromium-sync.zip
>84.7 MB chromium (72.0.3626.121-r612437) ..._chromium_releases_download_v72.0.3626.121-r612437-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.103-r625896) ..._chromium_releases_download_v73.0.3683.103-r625896-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.75-r625896)  ...p_chromium_releases_download_v73.0.3683.75-r625896-win64_chromium-sync.zip
>85.2 MB chromium (73.0.3683.86-r625896)  ...p_chromium_releases_download_v73.0.3683.86-r625896-win64_chromium-sync.zip
>86.0 MB chromium (74.0.3729.108-r638880) ..._chromium_releases_download_v74.0.3729.108-r638880-win64_chromium-sync.zip
>...
>Total: 52 files, 2.9 GB

If I understand, the last "scoop cache show" should tell me something like "Total: 0 file, 0 GB", right?
In addition, I do used "scoop cleanup chromium".

**Comment by niheaven** [comment]
Please try `scoop cleanup chromium -k` or just `scoop cleanup * -k`. This will cleanup all outdated cache files.

**Comment by n00d1e5** [comment]
Thanks, it works perfectly.
Maybe you should change the description in **scoop help cache**:
>To clear everything in your cache, use:
>scoop cache rm *

Case can be closed.
Tks again.
