### ISSUE TITLE
trid@2.24-19.04.21: hash check failed

### ISSUE THREAD

**Issue by jimhRR** [lukesampson/scoop#3385]
trid: 2.24-19.04.17 -> 2.24-19.04.21
Updating one outdated app:
Updating 'trid' (2.24-19.04.17 -> 2.24-19.04.21)
Downloading new version
triddefs.zip (1.3 MB) [===============================================================================================================================================================================================================] 100%
Checking hash of triddefs.zip ... ERROR Hash check failed!
App:         trid
URL:         http://mark0.net/download/triddefs.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    29f26a88f72f277cdb92220aa6b6af5940788d3f8e3d8fb521b24df7b295ac4b
Actual:      de1857d30c6782b703d8344bef2c36a0a1b431104647c8a7d31e49e4bf1e07f6

**Comment by niheaven** [comment]
ref: https://github.com/lukesampson/scoop/pull/3060

Please wait for a few days for scoop-core migration. If you like to try `develop` version of scoop, ref: https://github.com/lukesampson/scoop/pull/3367#issuecomment-486597453

**Comment by niheaven** [comment]
Closed by https://github.com/scoopinstaller/scoop-main/commit/845020b718253864eb90569ba1aa39c613fc298a
