### ISSUE TITLE
wget@1.20.3: hash check failed

### ISSUE THREAD

**Issue by skysin** [lukesampson/scoop#3395]
just as the title。

here is the output

WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'wget' (1.20.3) [64bit]
Loading wget-1.20.3-win64.zip from cache.
Checking hash of wget-1.20.3-win64.zip ... ERROR Hash check failed!
App:         wget
URL:         https://eternallybored.org/misc/wget/releases/wget-1.20.3-win64.zip
First bytes:
Expected:    9dea6d658ab14a77958233a116a86bc2f5adb1feb425848d58f918d354bdd1ea
Actual:      e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=wget%401.20.3%3a+hash+check+failed

**Comment by rirl** [comment]
I also encountered this problem
