### ISSUE TITLE
Adding the new main bucket fails with Unknown bucket 'main'

### ISSUE THREAD

**Issue by Playacem** [lukesampson/scoop#3397]
Just ran scoop update and received the following response:
```
λ  scoop update
Updating Scoop...
INFO  The main bucket of Scoop has been separated to 'https://github.com/scoopinstaller/scoop-main'
INFO  Adding main bucket...
Unknown bucket 'main'. Try specifying <repo>.
```

The cause appears to be the fact that the main bucket is not in `buckets.json` in the master branch. I have fixed the problem by running `scoop bucket add main https://github.com/scoopinstaller/scoop-main`

**Comment by Ash258** [comment]
Are you on develop branch??

**Comment by Playacem** [comment]
No I am on the master branch.

**Comment by Ash258** [comment]
Then this is not possible. You should never experience this in maaster, since the bucket extraction was not merged and scoop-update command in master do not contain this message.

**Comment by Playacem** [comment]
Well apparently deleting the SCOOP_BRANCH config variable did not reset the branch to master correctly. Can't seem to reproduce the issue.

**Comment by HNUrookie1** [comment]
![image](https://user-images.githubusercontent.com/102892887/232554152-5ef3e6d3-e760-442b-9878-5a3bb0d308b8.png)
Please ask why this is?It's is diffuculity.Thank you!
