### ISSUE TITLE
scoop-status: will show manifests removed before the second time scoop-update

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop#3400]
If you encounter this issue, which is caused by [the main bucket extraction updates](https://github.com/lukesampson/scoop/pull/3399). (ref: https://github.com/lukesampson/scoop/pull/3060)

```
$ scoop status
Scoop is up to date.
These app manifests have been removed:
    7zip
    cacert
    cmder
...
```

Solution:

Run `scoop update` again and it will add the [new main bucket](https://github.com/scoopinstaller/scoop-main) automatically. And congrats! You are now using the new main bucket.

**Comment by Ash258** [comment]
@r15ch13 Pin this please.

**Comment by Ash258** [comment]
Seems like everyone took migration well. Only one issue in discord, which user managed to get it fixed.

I think today or tomorrow bucket folder could be deleted from here and this issue closed (Keep pinned unless new more relevant issue show up)

**Comment by jwhipp** [comment]
Is there somewhere like a news area we can start posting this stuff too? I was able to work through it via double update but it might be handy to broadcast via mailing list or at least some news on a main page somewhere.

**Comment by h404bi** [comment]
@jwhipp PR #3419 will force to add the new main bucket for all users, it's an enough signal I guess.
