### ISSUE TITLE
Deleting SCOOP_BRANCH not switch to master

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3401]
Extracted from #3397 

> Well apparently deleting the SCOOP_BRANCH config variable did not reset the branch to master correctly. Can't seem to reproduce the issue.

Since SCOOP_BRANCH config is default and created always on installation, it is required for functioning. Since we can't forbid users to delete it we need to adjust it in code.

Should be enough to replace `get_config SCOOP_BRANCH` with `get_config SCOOP_BRANCH 'master'` to return default master, when config value do not exists.

**Comment by Ash258** [comment]
We should create some Hashtable with defaults which would be used in codebase.

```powershell
$CONFIG_DEFAULT = @{
    'SCOOP_BRANCH' = 'master'
    '...LESS_MSI' = $false
}
```

So we do not need to duplicate code and could easily change it if needed.

**Comment by niheaven** [comment]
I like the idea. See discussion before: https://github.com/lukesampson/scoop/pull/3242#issuecomment-474013729
