### ISSUE TITLE
[Regression] Expand-* functions which show logs should output fullnames

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3402]
![A](https://i.imgur.com/wdeL0e7.png)

/cc @niheaven

**Comment by r15ch13** [comment]
`extract_inno` should be `unpack_inno`
https://github.com/lukesampson/scoop/blob/c7033e1079e7b3744639a2f72fb79eb12975a1d2/lib/decompress.ps1#L200-L203
See https://github.com/lukesampson/scoop-extras/blob/master/bucket/hxd.json

**Comment by r15ch13** [comment]
If it's a zip it should be extracted before trying to unpack it with `innounp`

**Comment by Ash258** [comment]
I know. This is only for that log file location.

It should be full path so you can easily click it.

**Comment by r15ch13** [comment]
This should show the complete path
https://github.com/lukesampson/scoop/blob/c7033e1079e7b3744639a2f72fb79eb12975a1d2/lib/decompress.ps1#L131

It does it for me at least.
![image](https://user-images.githubusercontent.com/432127/56863206-d4b1df00-69b3-11e9-906d-2dd46c18e667.png)

**Comment by niheaven** [comment]
> 
> 
> `extract_inno` should be `unpack_inno`
> 
> [scoop/lib/decompress.ps1](https://github.com/lukesampson/scoop/blob/c7033e1079e7b3744639a2f72fb79eb12975a1d2/lib/decompress.ps1#L200-L203)
> 
> Lines 200 to 203 in [c7033e1](/lukesampson/scoop/commit/c7033e1079e7b3744639a2f72fb79eb12975a1d2)
>  function extract_inno($path, $to, $removal) { 
>      Show-DeprecationMessage $MyInvocation 'Expand-InnoArchive' 
>      Expand-InnoArchive -Path $path -DestinationPath $to -Removal:$removal 
>  } 
> 
> See [lukesampson/scoop-extras:bucket/hxd.json@`master`](https://github.com/lukesampson/scoop-extras/blob/master/bucket/hxd.json) [](/lukesampson/scoop-extras/blob/HEAD@{2019-04-28T10:10:23Z}/bucket/hxd.json)

https://github.com/lukesampson/scoop-extras/pull/1986

https://github.com/lukesampson/scoop-extras/pull/1987

Except for these two manifests, no `unpack_inno` is used...

**Comment by niheaven** [comment]
> It does it for me at least.

This may caused by PS version diff, see discussion in https://github.com/scoopinstaller/scoop-main/pull/6

**Comment by r15ch13** [comment]
> So I made these PRs, and rename `unpack_inno` to `extract_inno` for consistency。

It should be `unpack_inno` for backward compatibility :smile:
