### ISSUE TITLE
autoupdate hash url should be respected

### ISSUE THREAD

**Issue by krokofant** [lukesampson/scoop#3408]
I'm trying to allow autoupdate for a psmodule which is placed in the same repo as the bucket.

Since I can't use the buckets master.zip to verify the hash I'd like to hash against the psmodule manifest  (*.psd1). The hash url does not seem to be respected when used like this:
```json
{
  "version": "1.2",
  "url": "https://github.com/krokofant/scoop-powershell-bucket/archive/master.zip",
  "hash": "f0ee361a0cc501dbc1932dec46ce25faaa7e53218efc52c68256379f9c285317",
  "extract_dir": "scoop-powershell-bucket-master/modules/PS-Install-If-Missing",
  "psmodule": {
    "name": "PS-Install-If-Missing"
  },
  "checkver": {
    "url": "https://raw.githubusercontent.com/krokofant/scoop-powershell-bucket/master/modules/PS-Install-If-Missing/PS-Install-If-Missing.psd1",
    "re": "ModuleVersion\\s+=\\s+'([\\d.]+)'"
  },
  "autoupdate": {
    "url": "https://github.com/krokofant/scoop-powershell-bucket/archive/master.zip",
    "hash": {
      "url": "https://raw.githubusercontent.com/krokofant/scoop-powershell-bucket/master/modules/PS-Install-If-Missing/PS-Install-If-Missing.psd1"
    }
  }
}
```

This seems to download the autoupdate.url and hash check against that instead of using autoupdate.hash.url. Using the psd1 file as the autoupdate url would overwrite the actual download url.

If autoupdate.hash.url is specificed, should that not be used?

```powershell
Could not find hash in https://raw.githubusercontent.com/krokofant/scoop-powershell-bucket/master/modules/PS-Install-If-Missing/PS-Install-If-Missing.psd1
Downloading master.zip to compute hashes!
Loading master.zip from cache
Computed hash: 0e41359d359f2b87a522d48a54d88365542701044a37b845fcf7f8348289a9e4
```
I expect the fallback `download` option to download the autoupdate.hash.url and not the autoupdate.url.

**Comment by niheaven** [comment]
https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#add-hash-to-autoupdate

`au.hash.url` is URL template for downloading RDF/JSON files or extracting hashes.

**Comment by krokofant** [comment]
@niheaven I see, what I interpreted from the docs was that the `"mode": "download"` would download `au.hash.url` instead of the `au.url`. The other `au.hash.mode` alternatives seem to process the `au.hash.url`.
>  - `mode`:
>    - `extract`: (default, can be omitted) download from `url` and find with the regex
>    - `rdf`: extract from a RDF file. Example: [imagemagick](https://github.com/lukesampson/scoop/blob/master/bucket/imagemagick.json)
>    - `json`: extract from a JSON file. Example: [openssl](https://github.com/lukesampson/scoop/blob/master/bucket/openssl.json)
>    - `download`: (fallback) downloads the file and hash it locally

I know it sort of defeats the purpose of the hash if it could be generated and checked against an arbitrary source but it would be great if there was a way of calculating the hash from a path inside a zip so that one github repository could contain several apps/modules.

**Comment by niheaven** [comment]
It could, by give seperate url in git repo, please check https://github.com/scoopinstaller/scoop-main/blob/master/bucket/psutils.json, and https://github.com/scoopinstaller/scoop-main/blob/master/bucket/ln.json, https://github.com/scoopinstaller/scoop-main/blob/master/bucket/sudo.json. `ln`, `sudo` and several other apps are in `psutils` and also as seperate apps.
