### ISSUE TITLE
[request] Jetty

### ISSUE THREAD

**Issue by JamieMagee** [lukesampson/scoop#3420]
https://www.eclipse.org/jetty/
https://www.eclipse.org/jetty/download.html
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.17.v20190418/jetty-distribution-9.4.17.v20190418.zip

**Comment by gigi206** [comment]
+1

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3420
