### ISSUE TITLE
Can't install scoop

### ISSUE THREAD

**Issue by tinkorbell** [lukesampson/scoop#3421]
Hi,
I'm having an issue with installing scoop. Tried to go through the suggestions from different posts but unfortunately they were unsuccessful. Attaching screenshot
![image](https://user-images.githubusercontent.com/25505204/56957064-e1fad500-6b3d-11e9-81dc-2eadc5d75aea.png)

Tanya

**Comment by r15ch13** [comment]
Hm, something is accessing the files. Antivirus maybe?

**Comment by tinkorbell** [comment]
I don't know. With any other libraries I don't get this error. I'm on a corporate pc, so I can't disable antivirus and test. 
The process is falling at Extracting... What kind of access is required to the file at this stage?

**Comment by r15ch13** [comment]
Simple user privileges for writing files, nothing fancy. Can you check with [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) or [Process Hacker](https://processhacker.sourceforge.io/) which process uses `%USERPROFILE%\scoop`

**Comment by tinkorbell** [comment]
Ok, I haven't done anything, but run the installation command from PowerShell ISE and it worked. Prior to running the command I had to delete the scoop folder.
![image](https://user-images.githubusercontent.com/25505204/56962247-fd6ddc00-6b4d-11e9-908d-9ff161286dd5.png)

Thanks for taking your time helping me.
Tanya

**Comment by kiedtl** [comment]
close?
