### ISSUE TITLE
Request: FabioLB

### ISSUE THREAD

**Issue by PeeZu** [lukesampson/scoop#3422]
https://fabiolb.net/
https://github.com/fabiolb/fabio/releases
dependency: consul

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3422
