### ISSUE TITLE
wget@1.20.3: hash check failed

### ISSUE THREAD

**Issue by enascimento** [lukesampson/scoop#3424]
Hi, 

Note that the *actual* hash value below is different than the *actual ones* reported in other opened issues.

Regards,
Erick

----
App:         wget
URL:         https://eternallybored.org/misc/wget/releases/wget-1.20.3-win64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9dea6d658ab14a77958233a116a86bc2f5adb1feb425848d58f918d354bdd1ea
Actual:      7ef40a647a153accbfb8cd79b3d9e3bf8ac1bab95b704176e3172589285a13de

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=wget%401.20.3%3a+hash+check+failed
----

**Comment by niheaven** [comment]
Please `scoop update` twice and then try again.

**Comment by enascimento** [comment]
It worked. Thanks.
