### ISSUE TITLE
OpenSSL packages broken due to host being down

### ISSUE THREAD

**Issue by timvisee** [lukesampson/scoop#3429]
Currently, the [`openssl`](https://github.com/lukesampson/scoop/blob/master/bucket/openssl.json) package is broken, because the host providing the installers is currently down. I don't know whether this is permanent, or when we can expect to get this host back. The site didn't seem to be updated for a while, and it noted the years `2000-2003` in it's copyright branding, so I fear the worst.

I believe quite a few packages depend on this, thus I think this must be fixed.

Here's one of the hosted files the `openssl` package uses for version `1.1.1b`, which is down:
https://slproweb.com/download/Win64OpenSSL-1_1_1b.exe

This service reports the host as being down (with some history, in case it comes back up):
https://notopening.com/site/slproweb.com

This issue was reported by @sieunhando on a project page of mine here: https://github.com/timvisee/ffsend/issues/50

**Comment by timvisee** [comment]
Found two cached versions on my systems for OpenSSL that were provided through `slproweb.com`, and have mirrored these for now:

- https://u.visee.me/dl/openssl/Win64OpenSSL-1_1_1b.exe
- https://u.visee.me/dl/openssl/Win64OpenSSL_Light-1_1_0j.exe

Would it be useful to temporarily change the [`openssl`](https://github.com/lukesampson/scoop/blob/master/bucket/openssl.json) executable links to this, until the host is back online again?

**Comment by r15ch13** [comment]
Seems to be online again.

**Comment by timvisee** [comment]
Brilliant! Will close in that case.
