### ISSUE TITLE
Question: Who or what runs auto-pr.ps1?

### ISSUE THREAD

**Issue by brad-jones** [lukesampson/scoop#3440]
Just noticed that my app `gomake` has been added here: https://github.com/brad-jones/scoop-bucket/issues/1
Which is great, must have done something right if others think it worth adding here, thanks @Ash258

Anyway I am trying to work out how the updates to the manifest are made, is `auto-pr.ps1` run automatically through the appveyor pipeline? I couldn't see where it runs if it is. Or is it run manually?

The reason I ask is because at the moment the pipeline for `gomake` will automatically update the manifest at https://github.com/brad-jones/scoop-bucket/blob/master/gomake.json for each new release.

It would seem like a step backwards to then rely on someone manually running `auto-pr.ps1` to update the manifest here. Or am I missing something in how scoop's autoupdate functionality works?

**Comment by h404bi** [comment]
Official buckets are autoupdated by https://github.com/ScoopInstaller/Excavator , so if you want some apps being autoupdated, migrate them to one of the official buckets or run an instance of the excavator yourself.

3rd-party/users buckets are controlled by the owner, they have the power to update the manifests or not.

**Comment by Ash258** [comment]
@brad-jones Updates are executed each hour each day by docker service running on @r15ch13's server. You can see logs [here](https://scoop.r15.ch/). There is folder for each bucket.

Only when you decide to change release process (file name, url, whatever) there is need to only change checkver and / or autoupdate URL and within next hour update will be delivered.

**Comment by brad-jones** [comment]
Ok cool. I figured there would be some automated process thanks for pointing it out.
