### ISSUE TITLE
Add openjdk

### ISSUE THREAD

**Issue by aaaweisen** [lukesampson/scoop#3445]
please add redhat openjdk, thks!
address:https://developers.redhat.com/products/openjdk/download

**Comment by x80486** [comment]
I'm surprised Scoop doesn't have any way to install Java :open_mouth:

**Comment by h404bi** [comment]
```
scoop bucket add java; scoop install openjdk
```
https://github.com/scoopinstaller/java

**Comment by se35710** [comment]
RedHat builds are now provided by the AdoptOpenJDK project, and is available in the adopt*-upstream manifests. This issue can be closed.

**Comment by rasa** [comment]
Invalid, Implemented in java bucket
