### ISSUE TITLE
python install issue - failed to extract dark.log

### ISSUE THREAD

**Issue by ambhaiji** [lukesampson/scoop#3454]
scoop install python
Installing 'python' (3.7.3) [64bit]
python-3.7.3-amd64.exe (25.0 MB) [============================================================================] 100%
Checking hash of python-3.7.3-amd64.exe ... ok.
Running installer script...
Failed to extract files from C:\Users\user\scoop\apps\python\3.7.3\_tmp.
Log file:
  ~\scoop\apps\python\3.7.3\dark.log

**Comment by r15ch13** [comment]
Please run `scoop update` and try again
