### ISSUE TITLE
Couldn't find manifest for 'nodejs'.

### ISSUE THREAD

**Issue by deepgray2339** [lukesampson/scoop#3455]
Can't install nodejs

`> scoop install nodejs
`
Couldn't find manifest for 'nodejs'.

**Comment by r15ch13** [comment]
Please try running `scoop update` again. If this doesn't help, try adding the new main bucket with `scoop bucket add main`

**Comment by deepgray2339** [comment]
> Please try running `scoop update` again. If this doesn't help, try adding the new main bucket with `scoop bucket add main`

thanks,it worked.

**Comment by r15ch13** [comment]
Did the `scoop update` fix it or the other command? Just for knowing what was the cause :smile:

**Comment by deepgray2339** [comment]
> Did the `scoop update` fix it or the other command? Just so we know what was the cause 😄

`> scoop bucket rm main`
`> scoop bucket add main`

I don't know why the folder "~/scoop/buckets/main" was empty before.
