### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lcyan** [lukesampson/scoop#3463]
postman: 7.0.9 -> 7.1.0
Updating one outdated app:
Updating 'postman' (7.0.9 -> 7.1.0)
Downloading new version
远程服务器返回错误: (404) 未找到。
At C:\Users\yanleichang\scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : 远程服务器返回错误: (404) 未找到。

PS C:\Windows\system32\WindowsPowerShell\v1.0>

**Comment by r15ch13** [comment]
The URL are valid. Please try it in a browser: https://dl.pstmn.io/download/7.1.0/Postman-win64-7.1.0-full.nupkg#/dl.7z
Or there was a problem with their server.
