### ISSUE TITLE
what to do if a software is not updated in the database?

### ISSUE THREAD

**Issue by xarthurx** [lukesampson/scoop#3464]
Neovim -- now 0.3.5 available, but the one in the database is still 0.3.4.

In general are users suppose to submitted info for software update? 
How are these mechanisms managed?

**Comment by Calinou** [comment]
> In general are users suppose to submitted info for software update?
> How are these mechanisms managed?

It depends, but most apps in official buckets have an [autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate) mechanism which can be triggered by the bucket maintainers or with bots.

**Comment by niheaven** [comment]
Should be closed now.

**Comment by wsdjeg** [comment]
@xarthurx

please checkout this step:

```
scoop bucket add neovim-dev https://github.com/wsdjeg/scoop-neovim-dev.git
scoop install neovim-dev
```
