### ISSUE TITLE
Radare2 autoupdate not working and other observations

### ISSUE THREAD

**Issue by rpinolf** [lukesampson/scoop#3467]
It seems Radare2 has changed the way binaries are distributed and no longer are on the github repo so autoupdate is not detecting the recent releases. Scoop is at 3.2.1 whilst 3.5.1 has been already released (amongst others in between not being detected either).

Also scoop installs this through and inno setup package that is not supressing the installer messagebox, and interesting that in the manifest the innosetup boolean is not set. I've tried editing the manifest but setting that to true effectively unpacks the package but the setup fails at some point (I don't know if there is a way I could see more verbose output during the setup execution...)

Since radare2 distributions are based on .zip again more regularly than .exe sporadic innosetups maybe it would be better to change this package to install from the .zip windows binaries directly (since it seems was the case looking at past manifest commits). However, one thing that would be lost here would be the contextual menu options that are being written in the registry when using the .exe setup. So, is there a way to write registry keys with scoop? Because maybe it would be interesting to have this implemented and ask to the user if we wants that or not (with a timed default option, etc.).

I'm quite new to scoop so excuse me if there is something obvious I've not realized yet.

**Comment by r15ch13** [comment]
Changed it to use the zip file and removed the 32bit support.
Scoop has no option for creating registry keys. You can however create the context menu options manually and export them for later use.

VSCode is the only program in scoop that provides some registry files ready for importing.
See: https://github.com/lukesampson/scoop-extras/blob/master/scripts/vscode-install-context.reg

**Comment by rpinolf** [comment]
Thanks for such a quick resolution.
