### ISSUE TITLE
update and install behind authenticating proxy is broken

### ISSUE THREAD

**Issue by jorgheymans** [lukesampson/scoop#3471]
`scoop update curl` used to work fine, but now i'm getting

```
C:\>scoop update curl
curl: 7.62.0_1 -> 7.64.1_1
Updating one outdated app:
Updating 'curl' (7.62.0_1 -> 7.64.1_1)
Downloading new version
The remote server returned an error: (407) Proxy Authentication Required.
At C:\scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (407) Proxy Authentication Required.
```

Output of `scoop --version`

```
C:\>scoop --version
Current Scoop version:
6141e46d (HEAD -> master, origin/master, origin/HEAD) fix(decompress): Change dark.exe parameter order https://github.com/lukesampson/scoop-
extras/pull/2143 https://github.com/ScoopInstaller/Main/pull/56

'extras' bucket:
14100891 (HEAD -> master, origin/master, origin/HEAD) openresty: Update to version 1.15.8.1

'java' bucket:
f57bbc9 (HEAD -> master, origin/master, origin/HEAD) adopt8-openj9-nightly: Update to version 201905162228

'main' bucket:
a5c2efd2 (HEAD -> master, origin/master, origin/HEAD) duplicacy: Fix au.url and hash (#69)
```

Note that `scoop status` , `scoop update` commands work just fine.

**Comment by AMDG2** [comment]
I can confirm the issue on my side.

**Comment by se35710** [comment]
@r15ch13 I think it maybe have something to do with these lines (`$username` vs `$user` and `$password` vs `$pass`):

https://github.com/lukesampson/scoop/blob/71f504494a682d09f8fc8d16342992bf9cbbbaa3/lib/core.ps1#L102-L103

**Comment by jorgheymans** [comment]
@se35710 confirming this fixes the issue

**Comment by jorgheymans** [comment]
is this going to get merged or will it be fixed in another way ?

**Comment by r15ch13** [comment]
@jorgheymans you made a Pull-Request to your own fork. :smile:
Please create one pointing to `develop` branch.

**Comment by jorgheymans** [comment]
@r15ch13 thanks for bringing this to my attention, i did it in github directly so was not paying attention. https://github.com/lukesampson/scoop/pull/3483 is the new PR.
