### ISSUE TITLE
[Regression][develop] Expand-ZipArchive cannot remove already removed archive

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3473]
![A](https://i.imgur.com/keWXME2.png)

Cause:
https://github.com/lukesampson/scoop/blob/f5fdc275ca27166c7fd862932f4ad2e124708f20/lib/decompress.ps1#L238-L246

If there is `extract_dir` property set, archive is deleted twice.

first in `gci -exclude $ExtractDir | Remove`
then in `if ($Removal)`

/cc @niheaven

**Comment by niheaven** [comment]
Yes, fixed in #3472  :joy:

**Comment by Ash258** [comment]
Why so complicated? You could just add `gci . -Exlude $ExtractDir, $Path` or not?

**Comment by niheaven** [comment]
I try to do so in https://github.com/lukesampson/scoop/pull/3470, and in fact, `gci . -Exclude $ExtractDir, (SplitPath $Path -Leaf)` works.

But this failed when `extract_dir` has sub-dir, i.e. `PFiles\Calibre2` for `calibre-normal`. `-Exclude` will not recognize sub dir, and `Get-ChildItem` or `Remove-Item` will remove `PFiles`.

Then I tried `(Get-ChildItem . -Recurse).FullName -notmath '[Regex]::Escape($DestinationPath\$ExtractDir)|[Regex]::Escape($Path)' | Remove-Item` and this will protect `ExtractDir` and `Path`, but it will remove other files if manifest has multi-url and multi-extract_dir (e.g. pkg-config).

So finanlly I choose to use `_tmp` dir for `Expand-ZipArchive` and `Expand-MsiArchive`.

For PowerShell Core, `Expand-Archive` has param `-PassThru` that return extracted files, and this will be helpful for filtering files, but PS 5 hasn't any output. Maybe [ZipArchive.GetEntry](https://docs.microsoft.com/dotnet/api/system.io.compression.ziparchive.getentry?view=netframework-4.5) and [ZipFileExtensions.ExtractToFile](https://docs.microsoft.com/dotnet/api/system.io.compression.zipfileextensions.extracttofile?view=netframework-4.5) will be helpful for rewriting `Expand-Archive` function with `ExtractDir`.
