### ISSUE TITLE
"The variable '$scoopConfig' cannot be retrieved because it has not been set"

### ISSUE THREAD

**Issue by yooakim** [lukesampson/scoop#3477]
I am trying to install scoop on recent Windows 10 machines but all I get is this error
```powershell
~\> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Invoke-Expression : The variable '$scoopConfig' cannot be retrieved because it has not been set.
At line:32 char:1
```

I have tried to download the install script but the problem remains, so it seems to be in the actual script. My `$PSVersionTable` is as follows:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.113
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.113
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
I have tested on Windows 10 1809 and 1903.

**Comment by h404bi** [comment]
![](https://user-images.githubusercontent.com/5764917/58222623-36623080-7d49-11e9-8941-5f0d78a6daee.png)

Can't reproduce on my Windows 10 VM. If you still encounter the issue, I would like to recommend you to try the new standalone installer - https://github.com/ScoopInstaller/Install, though it's still in beta stage.

**Comment by yooakim** [comment]
Thanks, I'll try the standalone installer. Let's close this for now.
