### ISSUE TITLE
Can't shim 'bin\iawk.cmd': File doesn't exist.

### ISSUE THREAD

**Issue by mikepruett3** [lukesampson/scoop#3482]
Looks like the latest version of gawk (5.0.0) does not upgrade/install correctly...

` {~}> scoop install gawk `
` WARN  Scoop uses 'aria2c' for multi-connection downloads. `
` WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it. `
` Installing 'gawk' (5.0.0) [64bit] `
` Loading gawk-5.0.0-w32-bin.zip from cache. `
` Checking hash of gawk-5.0.0-w32-bin.zip ... ok. `
` Extracting gawk-5.0.0-w32-bin.zip ... done. `
` Linking ~\scoop\apps\gawk\current => ~\scoop\apps\gawk\5.0.0 `
` Creating shim for 'awk'. `
` Creating shim for 'gawk'. `
` Creating shim for 'iawk'. `
` Can't shim 'bin\iawk.cmd': File doesn't exist. `

**Comment by r15ch13** [comment]
My bad. That was a typo. It's fixed now :smile:
