### ISSUE TITLE
`scoop config rm <name>` says 'rm' has been removed instead of <name>

### ISSUE THREAD

**Issue by crheidri** [lukesampson/scoop#3490]
Removing a scoop config prints a statement saying 'rm' has been removed. The config is still removed properly, just a Write-Output bug.
>PS C:\projects\scoop> scoop config debug true
'debug' has been set to 'true'
PS C:\projects\scoop> scoop config rm debug
'rm' has been removed
PS C:\projects\scoop> scoop config debug
'debug' is not set

Easy fix in scoop-config.ps1, Line 40:
`Write-Output "'$name' has been removed"`
to
`Write-Output "'$value' has been removed"`

**Comment by Ash258** [comment]
Fixed in #3462

**Comment by crheidri** [comment]
Oops, didn't see that PR. I'll close this issue.
