### ISSUE TITLE
[Proposal] Alternative versions of manifest

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3493]
It would be nice to support different versions of manifest (beta, alpha, rc, eap, ...) (Types should be under discussion)

Proposed implementation:

```text
bucket/
  ├── nightly/
  │    ├── ffmpeg.json
  │    └── wavebox.json
  ├── beta/
  │    ├── pwsh.json
  │    └── wavebox.json
  ├── alpha/
  │    ├── pwsh.json
  │    └── wavebox.json
  ├── rc/
  │    ├── pwsh.json
  │    └── wavebox.json
  ├── old/ # PHP,
  │    ├── pwsh@6.1.1.json
  │    └── wavebox@4.1.10.json
  ├── ffmpeg.json
  ├── pwsh.json
  └── wavebox.json
```

How could commands look like:

```powershell
scoop install pwsh --beta
scoop install ffmpeg --nightly
scoop install ffmpeg --type nightly
scoop install pwsh --some-universal-pre-release-tag-which-load-other-type-of-manifest # Maybe the latest one if there are more = Higher version will have higher priority
```

It would require small changes:

- `Find-BucketDirectory`, which would accept new parameter `Type` with predefined `ValidateSet` and if this is specified then return nested folder
- `Install.json` New property `"type": "nightly"`
- List command should show type
- Auto-pr. something like `gci $Dir -Directory |% { checkver * -dir $_ -u }; hub commit all`

# Old versions

This could be implementation even for #3023. But this would require new manifest property (`"archive": true`) and then would auto-pr automatically copy older version into `old` directory and commit.

Archive property because some vendors ship only latest version, change URL, have static url, ... (https://github.com/lukesampson/scoop/issues/3023#issuecomment-456785542)

Some cons:

- There would be much more commits (Is it even problem?? 🤔)
- More manifests to maintain (Should not be problem in community driven buckets)
- Pin out other cons

# TODO:

Somehow list what versions are available (`gci -file $bucketdir\old "$manifest@*.json"` 🤔)

Note: _This is just late night thought (when I cannot sleep 😀) and the most easiest implementation which came up on my mind at first. There is possible that it would generate some problems, Which I didn't take into account. I only considered it as Bucket maintainer, and user, not scoop developer_

**Comment by niheaven** [comment]
Just some thought:

We have the `versions` bucket, and an unused `nightly` bucket, so alternative manifests could be putted there.

For selected installation, maybe we should automatically select corresponding one, e.g., `scoop install pwsh` -> `pwsh.json`, `scoop install pwsh --beta` -> `versions\pwsh-beta.json`, `scoop install python --alpha` -> `versions\python-alpha.json`, etc.

And I think `scoop install pwsh@beta` is better then `scoop install pwsh --beta`, using `--beta` as argument is somehow strange  :sweat_smile: There should be some reserved words after `@` such as 'alpha', 'beta', 'rc', 'nightly'. (no app use these words as version number, right?) And looking up `app-ver.json` should be prior when `scoop install app@ver`, locked version manifest should be in `versions` bucket and never checkvered. (e.g. `lynx-283.json`, need to rename existing manifests)
