### ISSUE TITLE
scoop install latex failing

### ISSUE THREAD

**Issue by a59** [lukesampson/scoop#3497]
```
scoop install latex                                                                                                    
Installing 'latex' (2.9.6942) [64bit]                                                                                    
The remote server returned an error: (404) Not Found.                                                                    
URL https://ftp.fau.de/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6942.exe#/dl.7z is not valid      
```

**Comment by DancingQuanta** [comment]
Same here as of 10/06/2019.

**Comment by xerxesb** [comment]
I just dropped a comment in the Main bucket repo for this issue:

https://github.com/ScoopInstaller/Main/issues/102

**Comment by felipecrp** [comment]
The new url is https://ftp.fau.de/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe

But it is an .exe instead of a .zip

**Comment by Cry0nicS** [comment]
This seems to have been solved. At least, with the latest versions it worked for me.
![image](https://user-images.githubusercontent.com/29982205/69903395-2f277980-13a1-11ea-90f4-b5141916de44.png)

**Comment by rasa** [comment]
Obsolete.
