### ISSUE TITLE
Go unistallation fails

### ISSUE THREAD

**Issue by danishabdullah** [lukesampson/scoop#35]
when I issue  "scoop install go"
It goes to googlecode, downloads the zip but crashes while extracting it.
The powershell becomes unresponsive and has to be manually closed through the tast manager.
When I open another powershell, "Go" isn't installed on the system, however scoop thinks that it has already been installed.

**Comment by Whuichenggong** [comment]
thanks for your answers i am respect for yours 
yours chinese

**Comment by Whuichenggong** [comment]
Thank you for your answer, that solved my problem
