### ISSUE TITLE
Request: googler

### ISSUE THREAD

**Issue by kozachynskyi** [lukesampson/scoop#3500]
Hi, can we have this one? [googler](https://github.com/jarun/googler)

**Comment by rasa** [comment]
Exe?

**Comment by kozachynskyi** [comment]
I'm sorry, but the answer is rather short. You propose me to install it by myself?

**Comment by Calinou** [comment]
What @rasa may have meant is that there's no Windows executable distributed on its [releases page](https://github.com/jarun/googler/releases). Therefore, we can't link to a binary release.
