### ISSUE TITLE
List available updates for installed packages

### ISSUE THREAD

**Issue by TheZoker** [lukesampson/scoop#3504]
Hi guys,

I'm searching for a command, that displays or updates all the installed packages, which have updates available. 

With `scoop update` the library gets updated and with `scoop update git`, the git package gets updated. But how do I find out, if a installed package has updates available? And how do I install updates for installed packages?

If this function is not available, this is a feature request.

Thanks!

**Comment by Ash258** [comment]
`scoop help update`

Usage: scoop update <app> [options]

'scoop update' updates Scoop to the latest version.
'scoop update <app>' installs a new version of that app, if there is one.

**You can use '*' in place of <app> to update all apps.**

Options:
  -f, --force               Force update even when there isn't a newer version
  -g, --global              Update a globally installed app
  -i, --independent         Don't install dependencies automatically
  -k, --no-cache            Don't use the download cache
  -s, --skip                Skip hash validation (use with caution!)
  -q, --quiet               Hide extraneous messages

**Comment by Ash258** [comment]
for list just use `scoop status` or `scoop list`

**Comment by TheZoker** [comment]
Ah nice, thank you very much!

**Comment by goyalyashpal** [comment]
> scoop list

scoop list doesn't show the updates available ?

```console
$ scoop list | head -n 7
Installed apps:

Name                       Version                  Source      Updated             Info
----                       -------                  ------      -------             ----
7zip                       23.01                    main        2024-03-22 15:13:59
alacritty                  0.13.1                   extras      2024-03-24 11:05:34
aria2                      1.37.0-1                 main        2024-03-21 22:29:45


```
