### ISSUE TITLE
Short internal function names may clash with aliases defined in a session

### ISSUE THREAD

**Issue by nightroman** [lukesampson/scoop#351]
Original case. A build script for Invoke-Build contains the task *update*:

    task update {
        scoop update
    }

This task fails with an error

    Invoke-BuildExec : Cannot process argument transformation on parameter
    'Command'. Cannot convert the "update" value of type "System.String" to
    type "System.Management.Automation.ScriptBlock".

    At ...\scoop\apps\scoop\current\bin\scoop.ps1:12 char:42
    + elseif ($commands -contains $cmd) { exec $cmd $args }

It fails due to the conflict of `exec` commands. Invoke-Build defines an alias
`exec` for its internal function `Invoke-BuildExec`. On command name resolution
PowerShell searches aliases first. When scoop invokes `exec` then an existing
alias is called, not the internal scoop function `exec`.

Contrived problem case, easy to test right in the PowerShell console:

    function Invoke-Exec {"Invoke-Exec with '$args'"}
    Set-Alias exec Invoke-Exec
    scoop update

It works fine but it outputs

    Invoke-Exec with 'update System.Object[]'

That is scoop calls `Invoke-Exec` via the alias `exec`, not its own function as
it expects.

---

How Invoke-Build deals with the same issue (and got punished...). It uses classic
Verb-PrefixNoun for internal function names and defines short aliases to these
names for actual use. E.g.

    function Invoke-BuildExec ...
    Set-Alias exec Invoke-BuildExec

And then it uses `exec` everywhere. A user may have its own alias `exec`
defined in parent scopes or even globally, conflicts will not happen.

Verb-Noun names will unlikely conflict with user aliases. I know some people
dislike Verb-Noun names. Any names which unlikely suitable for aliases will do.
E.g. scoop internal functions `command_files`, `command_name`, `command_path`
are probably named safely. But functions `commands` and `exec` in the same
script are probably not, such aliases may be defined in a user profile or by
another tool which uses scoop (e.g. Invoke-Build via user tasks).

---

The suggestion for scoop is to review such short function names like `exec`.
Names with non-word characters (underscore, dash) seem to be less likely to
conflict.

scoop may continue to use short names as aliases, so massive renaming is not
necessary. Example, instead of:

    function exec($cmd, $arguments) {
        ...
    }

this may be used

    function exec_command($cmd, $arguments) {
        ...
    }
    Set-Alias exec exec_command
    
Then the rest of scoop code should work not changed. At the same time the
potential conflict with an existing alias `exec` is resolved.

P.S. I also explained this "trap" as [Too-simple-function-names](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Too-simple-function-names). I collect such cases there :)

**Comment by deevus** [comment]
Thanks for explaining this. We ran into a similar problem in #183 

So if the function name is something that will stay unique, it can have a short alias that won't be overwritten by user aliases?

**Comment by deevus** [comment]
For example in Scoop the code relies on aliases for system commands such as `ls` and `rm`. We opted to use script level functions `function script::ls { get-content @args }`. Should we instead be just setting an alias `set-alias ls get-content` instead?

**Comment by lukesampson** [comment]
@deevus were aliases not the first thing you tried for #183?

**Comment by deevus** [comment]
@lukesampson Yeah I thought they were. Perhaps it only works for aliases that aren't AllScope?

**Comment by deevus** [comment]
```
set-alias select select-object
set-alias : Alias is not writeable because alias select is read-only or constant and cannot be written to.
At line:1 char:1
+ set-alias select select-object
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (select:String) [Set-Alias], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : AliasNotWritable,Microsoft.PowerShell.Commands.SetAliasCommand
```

**Comment by nightroman** [comment]
@deevus 

> So if the function name is something that will stay unique, it can have a short alias that won't be overwritten by user aliases?

Yes, unless a user defines some weird aliases like read only for all scopes. But in such a case he knows what he is doing and responsibility is his own.

Function names do not have to be unique. They just should have some names that unlikely used for aliases (user functions in parent scopes with same name is not a problem). This approach is not 100% bulletproof. There is always a way to break things in PowerShell :) But this approach is relatively safe.

**Comment by nightroman** [comment]
@deevus 

> For example in Scoop the code relies on aliases for system commands such as ls and rm. We opted to use script level functions function script::ls { get-content @args }. Should we instead be just setting an alias set-alias ls get-content instead?

This is something different and I cannot answer confidently. I do not have experience because in scripts I do not use aliases of built-in commands.

**Comment by nightroman** [comment]
#360 works fine so far. The original problem case is definitely resolved. I close the issue. Thank you!

**Comment by Bishwas-py** [comment]
You can do this with [powershell alias function with parameters](https://webmatrices.com/d/530-powershell-alias-function-with-parameters), this given help is helpful.
