### ISSUE TITLE
管道元素中的“&”后面的表达式生成无效的对象。

### ISSUE THREAD

**Issue by yyystation** [lukesampson/scoop#3513]
管道元素中的“&”后面的表达式生成无效的对象。该表达式必须生成命令名称、脚本块或 CommandInfo 对象。
所在位置 C:\Users\user\scoop\apps\scoop\current\lib\decompress.ps1:69 字符: 11
+         & (Get-HelperPath -Helper 7zip) x "$Path" -o"$DestinationPath ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : BadExpression

ERROR Could not find 'node-v12.4.0-win-x64'! (error 16)

**Comment by everyx** [comment]
@yyystation  Leave the command should be better to indicate the problem.

**Comment by Ash258** [comment]
#3517

**Comment by rasa** [comment]
Duplicate of #3517
