### ISSUE TITLE
Add Fossil package 

### ISSUE THREAD

**Issue by offray** [lukesampson/scoop#3514]
Hi,

Thanks for Scoop. I have been using Chocolatey so far, for the Windows family and friends, but it doesn't scale well in a classroom setup. One of Scoop big advantages is not relying on admin privileges to install software, so I would like to test it next time with my students in institutional setups where having such privileges is pretty difficult. But I need some particular packages for that to happen.

I would like to have [Fossil](http://fossil-scm.org/).

BTW, just out of curiosity, could scoop in the future support package dependencies?

Cheers,

**Comment by rasa** [comment]
It’s already in scoop [here](https://github.com/ScoopInstaller/Main/blob/master/bucket/fossil.json).

Scoop supports dependencies, via the [depends](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties) keyword.
