### ISSUE TITLE
Long path get truncated!

### ISSUE THREAD

**Issue by hulucc** [lukesampson/scoop#3519]
Step:
  1. scoop install zookeeper
  2. navigate to `%HOME%\scoop\apps\zookeeper\current\zookeeper-server\src\main\java\org\apache\zookeeper\server\`
  3. all the java source code should end with .java, some of the files obviously get truncated.
 
![image](https://user-images.githubusercontent.com/4343900/59767152-40d60280-92d4-11e9-86c5-68e3547abeff.png)

**Comment by Ash258** [comment]
`scoop checkup` check for long paths settings value. 

run cehckup and you should see something like `LongPaths support is not enabled`

**Comment by hulucc** [comment]
![image](https://user-images.githubusercontent.com/4343900/59772476-6a942700-92de-11e9-8144-7a4daeb28e7b.png)

**Comment by Ash258** [comment]
This look like a bug in 7zip.

Try to extract file from scoop cache. (`%HOME%\scoop\cache\zookeeper...`) and you should see same results

**Comment by hulucc** [comment]
Got.
