### ISSUE TITLE
How to handle the relocated manifest

### ISSUE THREAD

**Issue by qcts33** [lukesampson/scoop#3520]
Some apps I have installed from the extra bucket have been moved to the main bucket. So scoop status will report that the manifests have been removed.
Is there a way that I can redirect the apps to the relocated manifests, other than reinstall those apps?

**Comment by linsui** [comment]
You could change the app_dir/current/install.json manully.

**Comment by Ash258** [comment]
Open `install.json` and remove / edit bucket property.

**Comment by qcts33** [comment]
Thanks for the help.
I was hoping for some command to it automatically, but this will do.
