### ISSUE TITLE
Package request: DisplayCAL and ArgyllCMS

### ISSUE THREAD

**Issue by CHerSun** [lukesampson/scoop#3523]
Would it be possible to add DisplayCAL and ArgyllCMS? Both are open source as I know. ArgyllCMS is a requirement for DisplayCAL.

**Comment by bikeatefoucault** [comment]
yes, please. would be a big help over here.

**Comment by rasa** [comment]
Dup of https://github.com/lukesampson/scoop-extras/pull/2173
