### ISSUE TITLE
How to install application (mpv) from extras bucket?

### ISSUE THREAD

**Issue by vedantroy** [lukesampson/scoop#3524]
I did `scoop bucket add extras`, which worked fine. Then I tried to install mpv [0] from the extras bucket with `scoop install extras/mpv`, but that didn't work. Instead, I had to do `scoop install https://raw.githubusercontent.com/lukesampson/scoop-extras/master/bucket/mpv.json`, which did work.

How do I use scoop to install applications from the extras bucket?

[0] https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv.json

**Comment by Skrity** [comment]
Just do `scoop install mpv`. You can also `scoop search mpv` to lookup different version.

**Comment by Ash258** [comment]
![A](https://i.imgur.com/2t07NDH.png)

**Comment by isg32** [comment]
to Install the extras programs, you first gotta install the extras repo in bucket by
`scoop bucket add extras`
then search for your programs
`scoop search [<name>]`
