### ISSUE TITLE
Allow escaping slashes in shortcut names

### ISSUE THREAD

**Issue by MCOfficer** [lukesampson/scoop#3526]
(refs MCOfficer/scoop-nirsoft#3)

When installing this manifest, the shortcut isn't just placed in the `Scoop Apps\NirSoft` folder.

```
{
    "version": "1.00",
    "homepage": "https://www.nirsoft.net/utils/acm.html",
    "url": "https://www.nirsoft.net/utils/acm.zip",
    "bin": "acm.exe",
    "shortcuts": [
        [
            "acm.exe",
            "NirSoft\\ActiveX Compatibility Manager - Disable/enable ActiveX components on IE."
        ]
    ],
    "hash": "f06016105b015a5a3b3e38204cc67cd4e32814cdaaad147cce9ade34313b7bf4",
    "description": "Disable/enable ActiveX components on Internet Explorer browser.",
    "license": "Freeware",
    "notes": "If this application is useful to you, please consider donating to nirsoft.",
    "checkver": {
        "url": "https://www.nirsoft.net/pad/acm.xml",
        "re": "(?:<Program_Version>)(.*)(?:</Program_Version>)"
    },
    "autoupdate": {
        "url": "https://www.nirsoft.net/utils/acm.zip"
    }
}

```

I would expect a path like this

```
[...]\Scoop Apps\NirSoft\ActiveX Compatibility Manager - Disable/enable ActiveX components on IE.
```

Instead, scoop does this..
```
[...]\Scoop Apps\NirSoft\ActiveX Compatibility Manager - Disable\enable ActiveX components on IE.
```
.. which looks just about as good as you'd expect.
![grafik](https://user-images.githubusercontent.com/22377202/59965533-d7dace80-950f-11e9-985c-b2e5af1a98fe.png)

Escaping the slash doesn't help either. I could avoid slashes altogether in my update script, but that doesn't seem particularly elegant. Instead, scoop should ignore slashes or allow escaping them.

**Comment by Ash258** [comment]
You cannot have file with this name in windows

https://github.com/lukesampson/scoop/issues/3337#issuecomment-484915113

**Comment by MCOfficer** [comment]
that's a shame - i thought only backslashes were forbidden, for obvious reasons. Guess i'll have to resort to making all names file-friendly. Thank you

**Comment by Ash258** [comment]
Sidenote, Use xpath for checkver

```json
"checkver": {
    "url": "url",
    "xpath": "/XML_DIZ_INFO/Program_Info/Program_Version"
}
```
