### ISSUE TITLE
Failed to intsall powershell 5.1

### ISSUE THREAD

**Issue by wsdjeg** [lukesampson/scoop#3537]
Just download the ps5.1 from https://www.microsoft.com/en-us/download/details.aspx?id=54616

but when I start to run `Win7AndW2K8R2-KB3191566-x64` I get

![捕获](https://user-images.githubusercontent.com/13142418/60398532-ee29ff80-9b8b-11e9-999d-833c9852a3ed.PNG)

my os is Windows 7 Ultimate.

**Comment by h404bi** [comment]
Make sure your system of Windows 7 has been upgraded to Windows 7 SP1, then follow the [guide](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6#upgrading-existing-windows-powershell). Try PowerShell 6 if you cannot upgrade your Microsoft PowerShell.

**Comment by wsdjeg** [comment]
I do not want to upgrad os to sp1, it is too slow, do you mean I can install powershell 6 without upgrad os?

**Comment by h404bi** [comment]
Microsoft PowerShell 5 requires Windows 7 SP1, I can't help you if you do not satisfy the [prerequisites](https://github.com/lukesampson/scoop#requirements). You may download PowerShell 6 from https://github.com/PowerShell/PowerShell/releases and try to install and use it.

**Comment by Ash258** [comment]
What does this have to do with scoop??
