### ISSUE TITLE
Start Menu Shortcuts on Uninstallation

### ISSUE THREAD

**Issue by omerakgoz34** [lukesampson/scoop#3541]
Removing start menu shortcuts bug on Scoop uninstallation :/

$ scoop uninstall scoop

INFO: Win10 v1903 V1

**Comment by Ash258** [comment]
What bug? What is not working?

**Comment by omerakgoz34** [comment]
I just uninstalled scoop with:
$ scoop uninstall scoop
but the shortcuts still appear in the start menu
