### ISSUE TITLE
GPL-3.0 identifier

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3546]
https://spdx.org/licenses/GPL-3.0-only.html
https://spdx.org/licenses/GPL-3.0-or-later.html
https://opensource.org/licenses/GPL-3.0
https://www.gnu.org/licenses/gpl-3.0-standalone.html

> This license was released: 29 June 2007. This license identifier refers to the choice to use the code under GPL-3.0-only, as distinguished from use of code under GPL-3.0-or-later (i.e., GPL-3.0 or some later version). The license notice (as seen in the Standard License Header field below) states which of these applies to the code in the file. The example in the exhibit to the license shows the license notice for the "or later" approach.

The only difference is in the Standard License Header, which is not included in license. So for most apps not state the Standard License Header, we don't know which one is used. Why don't use `GPL-3.0` for them ? Or we should regard them as `GPL-3.0-only` ?

**Comment by niheaven** [comment]
Most of the licenses is `GPL-3.0-or-later`, except for those explictly said `GPL v3 only`. You can check the license file attached, and look for `or later`.

**Comment by linsui** [comment]
>  If the Program specifies that a certain numbered version of the GNU General Public License "or any later version" applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation.

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. 

I can only find two place. The first one is an assumption. The second one is a template. -only or -or-later need to be state in the Standard License Header. For example, Shadows-libev states -or-later in readme.

**Comment by niheaven** [comment]
No, look for `or later` in license file attached with software, or for GitHub hosted one, check `license` section.

The standard GPLv3 license file has `or later` statement, so `GPL-3.0-or-later`.

**Comment by linsui** [comment]
I can't find such a statement... :confused:

**Comment by niheaven** [comment]
Just example: https://github.com/franko/gsl-shell/blob/master/LICENSE#L640

**Comment by linsui** [comment]
It is after the `END OF TERMS AND CONDITIONS` and in `How to Apply These Terms to Your New Programs` section. As is says before

> To do so, attach the following notices to the program.

I don't think it is a statement.

**Comment by niheaven** [comment]
See L572 in section 14, if not explicitly stated, later version could be applied by default.

**Comment by Calinou** [comment]
> Each version is given a distinguishing version number.  If the
Program specifies that a certain numbered version of the GNU General
Public License "or any later version" applies to it, you have the
option of following the terms and conditions either of that numbered
version or of any later version published by the Free Software
Foundation.  If the Program does not specify a version number of the
GNU General Public License, you may choose any version ever published
by the Free Software Foundation.

If I'm reading it right, if the licensor specifies a version of the license but no explicit "or later" statement, the software is under GPLv3 *only*, not GPLv3 *or later*.

**Comment by linsui** [comment]
> If the Program specifies that a certain numbered version of the GNU General Public License "or any later version" applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation.

I do not understand this clearly until now... In my opinion it means when `the GNU General Public License "or any later version" applies to it` , you can choose other version. As I'm not good at English, this realy make me confused...
