### ISSUE TITLE
proxy settings problems with ss/ssr and v2ray

### ISSUE THREAD

**Issue by skysin** [lukesampson/scoop#3553]
thanks to the beautiful scoop.
and when i use this tool behind proxy, i find a problem that i can use ss/ssr to update apps successfully, but failed with v2ray. both use pac mode.

when using v2ray, the following error appears:

```
fatal: unable to access 'https://github.com/lukesampson/scoop/': Proxy CONNECT aborted
Update failed.
```

i'm wondering why this happens, and want to get an answer or what should i do to avoid this?

best wishes to you dev all.

**Comment by linsui** [comment]
Well, I guess it is related to your proxy config. ss provide socks5 and http proxy on the same port. But v2ray can only provide one proxy on one port. aria2 only support http proxy.

**Comment by skysin** [comment]
well， i think it‘s none of aria2's business, cause i disabled the aria2 recently but the problem still remains

**Comment by kidonng** [comment]
[Consult the docs](https://scoop-docs.now.sh/docs/misc/Using-Scoop-behind-a-proxy.html) first :)
You can also try manually reset the proxy config in Windows settings and turn on the proxy again.

**Comment by linsui** [comment]
It seems that scoop only support http proxy. So if you setup a socks proxy with v2ray, it will not work.

**Comment by kidonng** [comment]
> It seems that scoop only support http proxy. So if you setup a socks proxy with v2ray, it will not work.

Popular V2Ray clients will set up both HTTP and Socks proxy. As said in docs, as long as your *Internet Options* is fine there won't be any problem.
@skysin You can switch to global proxy and try again.

**Comment by skysin** [comment]
@kidonng . First of all, thanks for your enthusiastic answer and i apology for my late reply.

but i'm sorry， global proxy makes no sense. The problems still remains. 

Or show my v2ray config will be helpful? but i don't known what information will be in need.

And what's the most important is that v2ray is not always bad, sometimes it works fine just like ss/ssr.

**Comment by linsui** [comment]
@skysin Yeah, please show your config (after removing your private infomation).

**Comment by skysin** [comment]
```
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": ****,
      "listen": "**********",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "***********",
            "port": ****,
            "users": [
              {
                "id": "**********************",
                "alterId": 16,
                "email": "********",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "******"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/v1",
          "headers": {
            "Host": "******"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}
```


well, this seems to be my config.

**Comment by linsui** [comment]
Try to add a http inbound such as 

```
{
    "port": 8080, 
    "listen": "127.0.0.1", 
    "protocol": "http" 
 }
```

Then run `scoop config proxy 127.0.0.1:8080`

**Comment by skysin** [comment]
I'm afraid i can't change this config file ,cause it is consistent with website subscriptions。

**Comment by linsui** [comment]
Then you can use privoxy to transform a socks proxy to a http proxy... It can be installed by scoop.

**Comment by skysin** [comment]
What‘s confused me is that when i use provixy, the `scoop update *` still not works normally, but `scoop status` works fine.’

**Comment by blue-cloak** [comment]
Are you sure your http proxy port is working? It shouldn't be the problem of v2ray or scoop, cause I'm using both too.

**Comment by l-qq** [comment]
> Try to add a http inbound such as
> 
> ```
> {
>     "port": 8080, 
>     "listen": "127.0.0.1", 
>     "protocol": "http" 
>  }
> ```
> 
> Then run `scoop config proxy 127.0.0.1:8080`

Thank you very much~ I meet the similar problem as this issue, and do it as your method. Then my scoop gets well agian

**Comment by skysin** [comment]
I'm sorry. It's my own fault.

Finally, I solved this problem by using http proxy instead of socks proxy, which at first I didn't realize it.

The v2rayN provides http proxy by its own.

**Comment by BlahDuckling747** [comment]
Maybe it's too late to say this, but I hope it'll help those v2rayN users who searched for ways to use socks5 in scoop.
Run command `scoop config proxy socks5://localhost:<port>` so you can use your v2rayN's socks5 port.
I guessed it when I was trying to configure Git's proxy. It worked on my computer but maybe not others'. Anyway I think it's worth trying.

Plus: Sorry for my poor English.
