### ISSUE TITLE
Why can't I use this command

### ISSUE THREAD

**Issue by KevinAtlans** [lukesampson/scoop#3555]
<img width="679" alt="微信截图_20190712152105" src="https://user-images.githubusercontent.com/2200770/61109988-d8d0a180-a4b8-11e9-8fd9-e52bc0d52700.png">

@Why can't I use this command? Do I need to add related settings to the environment variables?

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/issues/3551

**Comment by Ash258** [comment]
Since you tried to install and there is already some files, you installed it before. I guess installation failed.

Cleanup `Remove-Itme 'C:\SCOOP\apps\scoop\*' -Recurse` and then try to use new installer https://github.com/ScoopInstaller/install

**Comment by rasa** [comment]
No author response
