### ISSUE TITLE
scoop install failed behind a proxy(scoop update fine)

### ISSUE THREAD

**Issue by fcying** [lukesampson/scoop#3556]
after I set scoop proxy, `scoop update` can work, but `scoop install` failed.

```
$ scoop config proxy http://127.0.0.1:4412
'proxy' has been set to 'http://127.0.0.1:4412'

$ scoop update
Scoop was updated successfully!

$ scoop install concfg
Installing 'concfg' (0.2019.03.09) [64bit]
未能解析此远程名称: 'http'
URL https://github.com/lukesampson/concfg/archive/a38c23651458ea48e463f7402bf166c65855759f.zip is not valid
```

**Comment by linsui** [comment]
> scoop config proxy [username:password@]host:port

> By default, Scoop will use the proxy settings from Internet Options, but with anonymous authentication.

>  To use the credentials for the current logged-in user, use currentuser in place of username:password
>  To use the system proxy settings configured in Internet Options, use default in place of host:port
>  An empty or unset value for proxy is equivalent to default (with no username or password)
>  To bypass the system proxy and connect directly, use none (with no username or password)

Try `scoop config proxy 127.0.0.1:4412`

**Comment by fcying** [comment]
> 
> 
> > scoop config proxy [username:password@]host:port
> 
> > By default, Scoop will use the proxy settings from Internet Options, but with anonymous authentication.
> 
> > To use the credentials for the current logged-in user, use currentuser in place of username:password
> > To use the system proxy settings configured in Internet Options, use default in place of host:port
> > An empty or unset value for proxy is equivalent to default (with no username or password)
> > To bypass the system proxy and connect directly, use none (with no username or password)
> 
> Try `scoop config proxy 127.0.0.1:4412`

`scoop config proxy 127.0.0.1:4412` work fine. thanks~~

**Comment by samba2** [comment]
> 

I confirm that leaving out `http` works. So this worked for me as well:`scoop config proxy 127.0.0.1:4412`  (or whatever your proxy is)
