### ISSUE TITLE
scoop couldn't find manifest for 'hugo'.

### ISSUE THREAD

**Issue by Ilooker** [lukesampson/scoop#3560]
At first, I have executed 'scoop update' successfully!

However, when I execute 'scoop install hugo', I get the following error:

scoop couldn't find manifest for 'hugo'

**Comment by Ilooker** [comment]
I also found this problem.

PS C:\Users\Ilooker> scoop search python36
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'versions' bucket:
    bucket/python36

PS C:\Users\Ilooker> scoop install python36
Couldn't find manifest for 'python36'.

**Comment by Ash258** [comment]
What is result of `scoop bucket list` command?

**Comment by Ilooker** [comment]
> What is result of `scoop bucket list` command?

main

**Comment by Ash258** [comment]
Then you should see hugo manifest.

Try `scoop info hugo` and you should see something like this:

![image](https://user-images.githubusercontent.com/13260377/61278536-a8d51700-a7b4-11e9-99f1-3f899e45cb0f.png)

**Comment by Ilooker** [comment]
> Then you should see hugo manifest.
> 
> Try `scoop info hugo` and you should see something like this:
> 
> ![image](https://user-images.githubusercontent.com/13260377/61278536-a8d51700-a7b4-11e9-99f1-3f899e45cb0f.png)
> 
> If no, then i would suggest to do `scoop bucket rm main; scoop bucket add main`

![image](https://user-images.githubusercontent.com/33446977/61278694-3a5d7c80-a7e7-11e9-87fa-c148d78052cb.png)

What should I do next? Just waiting？

**Comment by Ilooker** [comment]
The issue was resolved, thanks for your advice.

**Comment by Ash258** [comment]
I suspect there was some network problem before so git clone cannot be done on previous update.

**Comment by Ilooker** [comment]
Yep, it must be network problem. Since I had interrupted the first command "scoop update"
