### ISSUE TITLE
request for new package: Microsoft Terminal

### ISSUE THREAD

**Issue by copdips** [lukesampson/scoop#3575]
Hello,

Chocolatey just released the version and confirmed by Microsoft, could we make a scoop one ?

https://github.com/microsoft/terminal/issues/1386#issuecomment-516214362

**Comment by Ash258** [comment]
Not possible right now with scoop way. You could import it via native command, but it will be installed into default directory.

**Comment by rasa** [comment]
Fixed with lukesampson/scoop-extras@bbed112913cfdb8fb8c753fa5bad790772a4ba2f
