### ISSUE TITLE
Reinstall scoop without losing apps?

### ISSUE THREAD

**Issue by boxdox** [lukesampson/scoop#3576]
So I was installing openjdk using `scoop install openjdk`, this resulted in `Updating scoop...`, which got stuck for 10 minutes. Finally, giving up, I pressed ctrl+c, and it gave me bunch of errors and confirmations with something related to `C:\Users\username\scoop\apps\scoop\new directory is not empty, remove the file?` and this went on a loop till I close the terminal.

Now when I open terminal and ran `scoop install openjdk`, it gave me this error:

```
& : The term 'C:\Users\username\scoop\apps\scoop\current\bin\scoop.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:3
+ & 'C:\Users\username\scoop\apps\scoop\current\bin\scoop.ps1'   ;exit $la ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\username\...t\bin\scoop.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
``` 

As far as I can infer (and I double checked the directory), scoop is looking in the `new` directory to run its files, but since it was deleted, it throws this error. Also, the `current` directory is empty as well.

I tried installing again, but PS returned `Scoop is already installed, to update, run Scoop update`, which fails too. 

Is there any way to reinstall scoop and avoid downloading all apps again?

**Comment by Ash258** [comment]
Fastest way: 

```powershell
git clone 'https://github.com/lukesampson/scoop.git' 'C:\Users\username\scoop\apps\scoop\current'
```

**Comment by boxdox** [comment]
> Fastest way since you alread have all shims and everyting configured:
> 
> ```powershell
> git clone 'https://github.com/lukesampson/scoop.git' 'C:\Users\username\scoop\apps\scoop\current'
> ```

Looks like it did work. Thanks. Closing this issue.

**Comment by gugegev5** [comment]
> Fastest way since you alread have all shims and everyting configured:
> 
> ```powershell
> git clone 'https://github.com/lukesampson/scoop.git' 'C:\Users\username\scoop\apps\scoop\current'
> ```

when I did this, I got new error:
scoop update
Updating Scoop...
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
fatal: not in a git directory
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Update failed.

**Comment by nadworny** [comment]
@gugegev5 you probably need to change the username in the windows path to your username

**Comment by phpcitizen** [comment]
After git clone 'https://github.com/lukesampson/scoop.git' 'C:\Users\username\scoop\apps\scoop\current'
`scoop list`

Installed apps:

 7zip 19.00 *failed*
 advancedrenamer 3.88.1 *failed*
 aimp 5.00.2338 *failed*
 alldup 4.5.1 *failed*
 antidupl.net 2.3.10 *failed*
...


`scoop status`
These app manifests have been removed:
    advancedrenamer
    aimp
    alldup
    antidupl.net
    astrogrep
    audacity
    autohotkey
    axiom
...

**Comment by neoOpus** [comment]
`scoop update -a -f -g`

**Comment by mike-clark-8192** [comment]
Re: https://github.com/ScoopInstaller/Scoop/issues/3576#issuecomment-516958619 
Copy/pasteable for different shells:

PowerShell:
```ps1
git clone "https://github.com/lukesampson/scoop.git" "${env:USERPROFILE}\scoop\apps\scoop\current"
```
cmd.exe
```bat
git clone "https://github.com/lukesampson/scoop.git" "%USERPROFILE%\scoop\apps\scoop\current"
```

bash (Git for Windows)
```bash
git clone "https://github.com/lukesampson/scoop.git" "$USERPROFILE\\scoop\\apps\\scoop\\current"
```
