### ISSUE TITLE
Install does not rollback on fails

### ISSUE THREAD

**Issue by phh** [lukesampson/scoop#3580]
When I run:

`scoop install php`

The installation fails:
```The remote server returned an error: (404) Not Found.
URL https://windows.php.net/downloads/releases/php-7.3.7-Win32-VC15-x64.zip is not valid
```

But it seems like scoop thinks that it's still installed:

```
scoop install php
ERROR It looks like a previous installation of php failed.
Run 'scoop uninstall php' before retrying the install.
WARN  'php' () is already installed.
Use 'scoop update php' to install a new version.
```

Should the installation not rollback on fails?

![image](https://user-images.githubusercontent.com/1304003/62350070-e00c2d80-b501-11e9-90ef-fdfa217e1f3a.png)

**Comment by Ash258** [comment]
That is correct. This will keep logs from installation for debug purpose. 

You will see `*broken*` next to php in `scoop list php` or `scoop status`
