### ISSUE TITLE
KeeWeb

### ISSUE THREAD

**Issue by GamerClassN7** [lukesampson/scoop#3581]
I have write KeeWeb manifest but i am unable to push it, Can i ask why ?

Or what is correct step by step procedure of adding a new manifest ?

**Comment by Ash258** [comment]
1. Fork [extras bucket](https://github.com/lukesampson/scoop-extras)
1. Add `keeweb.json` into `bucket` folder
1. commit
1. push
1. Go to extras bucket and open new PR

**Comment by Ash258** [comment]
Or simplified way without manually cloning and forking. 

1. Go to https://github.com/lukesampson/scoop-extras/tree/master/bucket
1. Click create new file

**Comment by r15ch13** [comment]
KeeWeb already exists https://github.com/lukesampson/scoop-extras/blob/master/bucket/keeweb.json
