### ISSUE TITLE
request: tsc.exe

### ISSUE THREAD

**Issue by feamsr00** [lukesampson/scoop#3585]
Hi!
Might I suggest adding tsc.exe. It is the standalone compiler for [Typescript.](https://www.nuget.org/packages/Microsoft.TypeScript.Compiler)

I've cobbled together a manifest here:
https://gist.github.com/feamsr00/628c92ce0d1bed7ef58cd2326554a06b

Would it make sense for scoop to accept this?

**Comment by niheaven** [comment]
`tsc` could be installed by `npm` very easily, why add it to scoop?

PS. Current `tsc` version is 3.6.0 (https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild) and running it required `node` (`tsc.js`).

**Comment by feamsr00** [comment]
Hello! Simple this is tsc.**exe**  Is a *lot* easier to handle than anything node-based and [https://www.nuget.org/packages/Microsoft.TypeScript.**Compiler**](https://www.nuget.org/packages/Microsoft.TypeScript.Compiler) is 100% node free and makes it easy to not have to pull in an entire ecosystem just to compile ts files (admins I know were quite pleased at that). *That* said I've just noticed that the Compiler version is lagging. I've inquired upstream. However, I would say the logic for including it stands.

**Comment by rasa** [comment]
Out of scope
