### ISSUE TITLE
Url support dynamic parameter or use a script modify url

### ISSUE THREAD

**Issue by wenmin92** [lukesampson/scoop#3586]
I want to install [Renamer](https://www.den4b.com/products/renamer) using scoop, but it does not have a static url which have a dynamic parameter `key`.

I have write a script to catch the key, but I can't append it to the url.
```powershell
$manifest.url += \"?\" + (Invoke-WebRequest \"https://www.den4b.com/download/renamer/portable\").toString() | sls \"(key=\\w+)\" -list | % {$_.matches.groups[1]}.value
```

How can I do?

**Comment by Deide** [comment]
You can capture the key with a checkver regex. The bigger problem is the lack of a version number in my opinion.

**Comment by wenmin92** [comment]
@Deide No, it can't. The download url is like this: 
```
https://www.den4b.com/download/renamer/portable?key=88745b313c65a3b69d48efe3e93f9659e2c59b58a91d7b69
```
which `key` is dynamic, you must request `https://www.den4b.com/download/renamer/portable/$version` first, then capture the `key` from the response(the response is a html web page). When I'v got the key, I can use the new url to download the zip file.

**Comment by Deide** [comment]
You can set the checkver url to `https://www.den4b.com/download/renamer/portable` and look for the URL with the key, capturing the key with your regex.

But still, I didn't see any good way to determine the version (ie. 7.1).

**Comment by wenmin92** [comment]
Sorry, I just understood what you mean. Well it can't be in the checkver, it should be captured every time before download while the `key` is time-sensitive, although I don't know the exact time.

**Comment by Deide** [comment]
Oh I see what you mean now by dynamic key. It expires.

Might be something Manifest variables in #2609 helps with, though I don't know if any thought has been put into race conditions.

**Comment by niheaven** [comment]
Please see https://github.com/lukesampson/scoop-extras/pull/2585

**Comment by Deide** [comment]
Just for future reference, where does the `scoop` token come from?

**Comment by wenmin92** [comment]
See [Can download url be fixed for Scoop package management? / Discussions / den4b Forum](http://www.den4b.com/forum/viewtopic.php?pid=10932)

**Comment by niheaven** [comment]
Wow, I just use `scoop` as `chocolatey` and it works. Didn't notice the discussion.

**Comment by niheaven** [comment]
Since Chocolatey's install script is

```powershell
$packageName = 'renamer.portable'
$url = 'http://www.den4b.com/download/renamer/portable/7.1?token=chocolatey'
$checksum = '9d0f586c0e1c65f06354a3c0bcc019b187372d167077238e6299246cb3986862'
$checksumType = 'SHA256'

$installDir = Join-Path $(Get-BinRoot) "renamer"

Install-ChocolateyZipPackage "$packageName" "$url" "$installDir" -Checksum $checksum -ChecksumType $checksumType
```

**Comment by wenmin92** [comment]
Thanks for ReNamer's Owner, he make this easy.
