### ISSUE TITLE
Can't download when screen line too short to display progress bar

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3589]

**Comment by issaclin32** [comment]
I tried to reproduce the error by running `scoop install todotxt-net --no-cache` on a terminal with **15 chars of line width**, but it worked fine with both `aria2` enabled and disabled.

Is this problem happening on Windows 7?

(my configuration: Windows 10 version 1903, Powershell version 5.1)

![line_to_short](https://user-images.githubusercontent.com/27724471/62819710-7f2cc700-bb8b-11e9-9e40-7316596d5a4a.png)

**Comment by linsui** [comment]
Thanks :smile: I bumped into this problem when I use ssh from termux. It seems that there is no problem when use powershell on Windows. This is a corner case.
