### ISSUE TITLE
bin/install.ps1 : very strange powershell execution policy check

### ISSUE THREAD

**Issue by copdips** [lukesampson/scoop#3590]
Hello,

https://github.com/lukesampson/scoop/blob/master/bin/install.ps1#L15 says:

```powershell
# show notification to change execution policy:
if((Get-ExecutionPolicy) -gt 'RemoteSigned' -or (Get-ExecutionPolicy) -eq 'ByPass') {
    Write-Output "PowerShell requires an execution policy of 'RemoteSigned' to run Scoop."
    Write-Output "To make this change please run:"
    Write-Output "'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'"
    break
}
```

Which means that any executionpolicy greater than RemoteSigned cannot install scoop.
But Bypass is greater than RemoteSigned that cannot install scoop ?

```powershell
> Get-ExecutionPolicy ; (Get-ExecutionPolicy) -gt 'RemoteSigned'
Bypass
True
```

I managed to install scoop by downloading the file install.ps1 locally and removing the if block.

Could you please check the `if` condition.

**Comment by r15ch13** [comment]
Did the installation with `Bypass` work? Maybe I made a mistake and it should have been 
`-neq 'ByPass'`.

```pwsh
[System.Enum]::GetValues([Microsoft.PowerShell.ExecutionPolicy]) |
Sort-Object -Property @{Expression = {[int]$_}; Descending = $False} |
% { "$([int]$_) => $_" }
```
```
0 => Unrestricted
1 => RemoteSigned
2 => AllSigned
3 => Restricted
4 => Bypass
5 => Undefined
```

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6

**Comment by copdips** [comment]
Yes currently bypass cannot install scoop

**Comment by copdips** [comment]
@r15ch13 

I think your suggestion on `-neq 'ByPass'` should fix the issue.
Or make an explict choose of the execution policy instead of int comparaison. Because it's a little bit strange to set the `ByPass` at 4, nobody outside of powershell team can know why.
