### ISSUE TITLE
"doesn't look like a valid git repository"

### ISSUE THREAD

**Issue by DessertArbiter** [lukesampson/scoop#3591]
i just installed scoop for the first time and it wont let me add any buckets, im not using a proxy and it doesnt even give me an error beyond the not valid part

i tried both the extras and versions buckets

```
tim> scoop bucket add extras
Checking repo... 'https://github.com/lukesampson/scoop-extras' doesn't look like a valid git repository

Error given:
```

also
```
tim> scoop update
Updating Scoop...
Scoop update failed.
```

i can ping github fine and even install packages from the main bucket without issue, so its not a connection issue

**Comment by DessertArbiter** [comment]
i figured it out, it was trying to use the git command from cygwin

i just had to give the git cmd directory in PATH a higher priority than cygwin

**Comment by ReSakura01** [comment]
Thanks，I have the same issue

**Comment by KENNY-hub-vue** [comment]
I want to know if there anybody counts the situation that is not like above. I am using the terminal in Windows to implement "scoop bucket add main", but it just continues printout the repo I use is not valid.

**Comment by ymartin59** [comment]
Same issue here with any bucket I try to add (whereas I use Scoop since long)
It may come from either some Windows updates (powershell, tls certificates?) or Git update to 2.47...
How should we diagnose/investigate what is failing?
