### ISSUE TITLE
Filter git logs on update

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3597]
Sometimes I push only repository changes / not manifests related changes to manifests and I would prefer to not show these inside log on update as they are not relevant for end users. User only care for manifests updates / additions / fixing.

It could work same as in CIs with specific string in title `[hidden]` for example

Also easy to implement with one line change to use `where-object` on git_log

![A](https://i.imgur.com/Uu4kzRB.png)

Thanks @rasa for easy demonstration purpose 😀

**Comment by r15ch13** [comment]
Good idea. 👍

A commit message guideline would make it easier to filter, I guess. It should then be added to #3362.
