### ISSUE TITLE
Error while installing memreduct 3.3.5

### ISSUE THREAD

**Issue by gothicx** [lukesampson/scoop#3598]
Hi,

I got this while installing it. It tries to extract to a not existing directory.

PS C:\WINDOWS\system32> scoop install memreduct
Installing 'memreduct' (3.3.5) [64bit]
Loading memreduct-3.3.5-bin.zip from cache
Checking hash of memreduct-3.3.5-bin.zip ... ok.
Extracting memreduct-3.3.5-bin.zip ... Remove-Item : Cannot find path 'C:\Users\gothi\scoop\apps\memreduct\3.3.5\_tmp\memreduct\32\' because it does not exist.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:411 char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\gothi\...p\memreduct\32\:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by rasa** [comment]
Obsolete.
