### ISSUE TITLE
Does url support dynamic link?

### ISSUE THREAD

**Issue by blue-cloak** [lukesampson/scoop#3599]
- Case: I want to create an app json.
- Problem: The app is downloaded from sourceforge.net, but it seems sourceforge.net doesn't have a static link for the file, instead, it will automatically select a mirror. Here is an example: https://sourceforge.net/projects/orwelldevcpp/files/Portable%20Releases/Dev-Cpp%205.11%20No%20Compiler%20Portable.7z/download

I saw an issue in #3586, but the case is different here. In issue #3586, the url seems to have a pattern to follow while in this case the link is delivered by server.

And after the countdown, it does have a direct link option, but the link was told to be too long.

I think I'm lack of the knowledge on how the browser can download the file while scoop can't do the same thing.

**Comment by h404bi** [comment]
https://github.com/h404bi/dorado/blob/master/bucket/dev-cpp-no-compiler.json#L8
just use the link, Scoop will follow the URL redirection.

**Comment by blue-cloak** [comment]
> https://github.com/h404bi/dorado/blob/master/bucket/dev-cpp-no-compiler.json#L8
> just use the link, Scoop will follow the URL redirection.

Many thanks, seems like I though too much...
