### ISSUE TITLE
function "url_filename" doesn't work as expected

### ISSUE THREAD

**Issue by blue-cloak** [lukesampson/scoop#3602]
## Case
I want to install an app using manifest like this
```json
{
	"homepage": "https://www.bypass.cn",
	"description": "12306 ticket buyer",
	"license": "Freeware",
	"version": "1.13.54",
	"url": "https://www.bypass.cn/api/download?name=Bypass.zip",
	"extract_dir": "Bypass",
	"bin": [ [ "Bypass.exe", "bypass" ] ],
	"checkver": {
		"url": "https://www.bypass.cn/",
		"regex": "Version: ([\\d.]+)"
	}
}
```
## Problem:
It suceessfully download the file in cache, but unable to unzip it properly. It just rename the zip file into "download" and put it in "current" folder.

## My discovery
So I run `Set-PSDebug -Trace 2` in powershell and reinstall the app to see what happenend.
I found it called a function `url_filename` in `core.ps1` to give the return value to a variable `fname`, using which scoop will determine whether it's an archieved file.
`function url_filename` looks like this:
```powershell
function url_filename($url) {
    (split-path $url -leaf).split('?') | Select-Object -First 1
}
```
In my case, the input parameter is `$url = "https://www.bypass.cn/api/download?name=Bypass.zip"`, thus causing `$fname = download`, not `Bypass.zip`, which makes scoop think it's not a zip file.
I'm not familiar with the download link format, but I can see there is another function called `usl_remote_filename` just below this one and succeed finding the true name of the file, why not just use this one instead?

**Comment by Ash258** [comment]
```json
{
	"homepage": "https://www.bypass.cn",
	"description": "12306 ticket buyer",
	"license": "Freeware",
	"version": "1.13.54",
	"url": "https://www.bypass.cn/api/download?name=Bypass.zip#/whatever.zip",
	"extract_dir": "Bypass",
	"bin": [ [ "Bypass.exe", "bypass" ] ],
	"checkver": {
		"url": "https://www.bypass.cn/",
		"regex": "Version: ([\\d.]+)"
	}
}
```

**Comment by blue-cloak** [comment]
@Ash258 Thanks for the quick response, and it works like a charm!
