### ISSUE TITLE
Always prompt 'These app manifests have been removed' when using 'scoop status'

### ISSUE THREAD

**Issue by jovercao** [lukesampson/scoop#3603]
OS: windows 10 pro

```bash
$ scoop status
...
These app manifests have been removed:
googlechrome
pandoc
```

**Comment by linsui** [comment]
See https://github.com/ScoopInstaller/Main/pull/152 ,
https://github.com/lukesampson/scoop-extras/pull/2144

```
scoop uninstall googlechrome pandoc
scoop install googlechrome pandoc
```

should fix it.

**Comment by Ash258** [comment]
No need to uninstall pandoc.

Just open `$env:SCOOP\apps\pandoc\current\install.json` in editor and remove bucket property.

**Comment by jovercao** [comment]
> See [ScoopInstaller/Main#152](https://github.com/ScoopInstaller/Main/pull/152) ,
> [lukesampson/scoop-extras#2144](https://github.com/lukesampson/scoop-extras/pull/2144)
> 
> ```
> scoop uninstall googlechrome pandoc
> scoop install googlechrome pandoc
> ```
> 
> should fix it.

It's OK! thanks!
