### ISSUE TITLE
scoop cache set

### ISSUE THREAD

**Issue by grantcarthew** [lukesampson/scoop#3606]
Feature request:

```powershell
scoop cache import \some\path\on\computer\or\file\server
```

I run classes and plan on using `scoop` for the students to install required software. It's an elegant solution. I love it. Thanks.

Right now the packages I want the students to install total up to 1GB in size. Rather than getting all the students to download 1GB worth of files, it would be great to be able to pre-populate the cache.

I searched for a similar issue and could not find one. Sorry to add to the noise.

**Comment by grantcarthew** [comment]
Reference: https://stackoverflow.com/questions/23574653/running-get-childitem-on-unc-path-works-in-powershell-but-not-in-powershell-run

**Comment by linsui** [comment]
A work around is using a custom bucket. See https://github.com/lukesampson/scoop/wiki/Buckets#creating-your-own-bucket and https://github.com/Ash258/GenericBucket

**Comment by grantcarthew** [comment]
Sorry @linsui, I don't see how creating a custom bucket is going to get the binary files from a network share and copy them to the local scoop cache.

I know there is an environment variable for the cache location however a simple import command would be easier in my opinion.

**Comment by h404bi** [comment]
```
scoop cache import \some\path\on\computer\or\file\server
```

Though I agree with the cache import feature, this is not a good implementation. Scoop caches files based on the URL of the package. You can't simply import a file from a server without specifying its relating app. And Scoop cannot know what app the cache you imported for.

This sounds like a XY-Problem, perhaps you just want to speed up the software downloading progress for your students. As @linsui said, a private bucket containing manifests from the local network/server would be better I guess.

For example, you want your students to install the git software. Let's assume its size is 1GB, and the default manifest of git from Scoop's main bucket is like this:

```
{
    "homepage": "https://git-for-windows.github.io/",
    "version": "2.23.0.windows.1",
    "architecture": {
        "64bit": {
            "url": "https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z",
            "hash": "501d8be861ebb8694df3f47f1f673996b1d1672e12559d4a07fae7a2eca3afc7"
        },
        "32bit": {
            "url": "https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-32-bit.7z.exe#/dl.7z",
            "hash": "33388028d45c685201490b0c621d2dbfde89d902a7257771f18de9bb37ae1b9a"
        }
    },
    "bin": [
        "cmd\\git.exe",
        "cmd\\gitk.exe",
        "cmd\\git-gui.exe",
        "usr\\bin\\tig.exe",
        "git-bash.exe"
    ]
    .....blablabla
}
```

Then you can just download that 1GB binary files to your local server, and modify the manifest to use your local server's `caches`, like this:

```
{
    "homepage": "https://git-for-windows.github.io/",
    "version": "2.23.0.windows.1",
    "architecture": {
        "64bit": {
            "url": "http://yourlocalserver/path/to/the-git-binary-cache-x64.exe#/dl.7z",
            "hash": "501d8be861ebb8694df3f47f1f673996b1d1672e12559d4a07fae7a2eca3afc7"
        },
        "32bit": {
            "url": "http://yourlocalserver/path/to/the-git-binary-cache-x32.exe#/dl.7z",
            "hash": "33388028d45c685201490b0c621d2dbfde89d902a7257771f18de9bb37ae1b9a"
        }
    },
    "bin": [
        "cmd\\git.exe",
        "cmd\\gitk.exe",
        "cmd\\git-gui.exe",
        "usr\\bin\\tig.exe",
        "git-bash.exe"
    ]
    .....blablabla
}
```

Then, you'll need to create a private bucket (a git repo), and put manifests you modified before into the private bucket. Like this:

**classroom** bucket
```
├─.git
├─bucket
└──you-manifest-a.json
└──you-manifest-b.json
└──you-manifest-c.json
└──blablabla
```

Host this bucket from your local network, then tell your students to add the private bucket, and install software from this bucket.

```
scoop add classroom http://localnetwork/path/to/classroom-bucket.git
scoop install classroom/git
```

Now, all your students can download files from the local network/server you provided. And the downloading speed is up to your server's network.

**Comment by Ash258** [comment]
Yuu could try to set `SCOOP_CACHE` environment variable to same UNC location.

`[Environment]::SetEnvironmentVariable('SCOOP_CACHE', '\\some\path\on\computer\or\file\server', 'User')

**Comment by grantcarthew** [comment]
Thanks guys for your suggestions. Much appreciated.

The major benefit of scoop is its simplicity.

A custom bucket seems like a move away from simplicity because you now have to manage updates.

I knew about the `SCOOP_CACHE` environment variable however I thought a command option would be simpler.

How about `scoop cache set \\sever\share\directory`?

That is probably not a lot better than `$env:SCOOP_CACHE=\\server\share\directory`. Cleaner though.

**Comment by Ash258** [comment]
`$env:SCOOP_CACHE=\\server\share\directory` will not be preserved after powershell session exited. You need to use dotnet to bind it into User / machine scope.

**Comment by grantcarthew** [comment]
Hence my suggestion @Ash258, easy config setup with `scoop cache set <path>`.

I'm thinking at the start of a day before the class, on the instructor machine, set the cache and kick of the installs. After the installations have finished and the class has started, get the students to run four commands (or a script to do it):

```powershell
iwr -useb get.scoop.sh | iex
scoop bucket add extras
scoop cache set \\server\share\cache
scoop install <long list of packages>
```

I'm going to close this. You guys don't seem keen and I don't want to add to your cognitive workload.

Feel free to ignore or re-open.

Thanks again for this project. Love it.

**Comment by Ash258** [comment]
You can always create custom commands.

`scoop alias add 'cache-set' '[Environment]...(..$arg,..)'
