### ISSUE TITLE
Update of manifests installed by url fails

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3607]
Reproducible steps:

1. `scoop bucket rm Ash258` in case you already have this bucket added.
1. `scoop install 'https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/RPCS3.json'`
    - RPCS3 is good example as it has frequent updates
1. Wait for update of manifest
1. `scoop update`
1. `scoop status`
    - Status should find out there was update of manifest
1. `scoop update RPCS3`
1. `Could not find manifest for RPCS3`

Same problem with Rider manifest

![image](https://user-images.githubusercontent.com/13260377/63553543-ff174180-c53a-11e9-8f17-48fdb066d230.png)

For debug purpose I suggest to create custom gist and just change version property.

**Comment by Ash258** [comment]
Same for locals 

![A](https://i.imgur.com/m3Kurtw.png)

Manifest is found and read right, but cannot be used for installation

**Comment by SonOfDiablo** [comment]
Is there any news on this issue?
I just started to play around with Scoop a few days ago and today I wanted to try creating some custom manifests, however I'm running into the same issue when trying to update an app installed by a local manifest.
