### ISSUE TITLE
Unable to set application like default OS choice

### ISSUE THREAD

**Issue by GamerClassN7** [lukesampson/scoop#3625]
HI,
i have problem if i install app from scoop Chrome, Atom,... 
they work fine but i am unable to set them like default app even when i set it here:

![image](https://user-images.githubusercontent.com/22167469/64154019-49000180-ce30-11e9-8ab7-9cdbcd74c0b7.png)

it doesn't work,
When i click for example on link in Discord nothing happen. 

Can anybody help me  ?

**Comment by linsui** [comment]
For chrome, maybe you can try to set it as default browser in chrome settings.

**Comment by GamerClassN7** [comment]
Thanks for answer, 
Where i could do that ?

**Comment by GamerClassN7** [comment]
if you ment this, it is default even in chrome 

![image](https://user-images.githubusercontent.com/22167469/64155352-e1978100-ce32-11e9-8420-9597844de77b.png)

**Comment by linsui** [comment]
I can set it as default browser in chrome... Maybe it's a problem about Discord. Does `start https://github.com` work?

**Comment by GamerClassN7** [comment]
nope if i install chorme normal way it work fine but any program i install thru scoop lack this feature

![image](https://user-images.githubusercontent.com/22167469/64166128-cafb2500-ce46-11e9-8fb6-9551ea19b8ad.png)

**Comment by nightscape** [comment]
I had the same problem, but setting Chrome as default browser in the Chrome settings worked:

1. In Chrome, open the three dots at the upper right
2. Settings
3. Standard Browser
4. Click the button

**Comment by rflmota** [comment]
Hello,

I had the same issue but with [Brave browser](https://github.com/ScoopInstaller/Extras/blob/master/bucket/brave.json) , but wasn't able getting it to work even setting it as default.. Any tips?

**Comment by rashil2000** [comment]
Try doing it from System settings
