### ISSUE TITLE
Lost all the shortcuts

### ISSUE THREAD

**Issue by ztj1993** [lukesampson/scoop#3627]
When Windows 10 was updated to the preview version, all shortcuts were lost.

Can it be rebuilt?

Now `C:\Users\{user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` directory is empty.

**Comment by Ash258** [comment]
`scoop reset *`

**Comment by wenmin92** [comment]
you fast 😂

**Comment by ztj1993** [comment]
@Ash258 Thank you

**Comment by ztj1993** [comment]
@Ash258 Resetting miniconda3 found problems:
```
Resetting miniconda3 (4.7.10).
Linking ~\scoop\apps\miniconda3\current => ~\scoop\apps\miniconda3\4.7.10
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
找不到(Can't find) C:\Users\ztj\scoop\apps\miniconda3\4.7.10\Lib\site-packages\setuptools\script
找不到 C:\Users\ztj\(dev).tmpl
找不到 C:\Users\ztj\scoop\apps\miniconda3\4.7.10\Lib\site-packages\setuptools\command\launcher
找不到 C:\Users\ztj\manifest.xml
```

**Comment by Ash258** [comment]
@ztj1993 I am not miniconda user and cannot test right now as I am travelling, so I do not know what could cause this. Try to reinstall and if problem persist open separate issue please.
