### ISSUE TITLE
Installed sudo, but sudo keeps requiring me to use administrator login

### ISSUE THREAD

**Issue by 573** [lukesampson/scoop#3635]
I installed sudo globally using scoop, but actually trying to use it from my non-elevated login keeps asking for administrator login:

>current $ sudo echo 1
sudo: you must be an administrator to run sudo

Is that intended behavior?

**Comment by linsui** [comment]
Yes, it is.

> sudo - An approximation of the Unix sudo command. Shows a UAC popup window unfortunately.

**Comment by 573** [comment]
Thanks for clarifying!
Do I have to configure anything to get the UAC popup window? On my setup I can't get to see any.

**Comment by 573** [comment]
Duplicates https://github.com/lukesampson/psutils/issues/20.
