### ISSUE TITLE
Can't download from fossshub

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop#3638]
It seems that fosshub has removed static download link.

**Comment by Ash258** [comment]
Example? Log? Anything which could help trace this problem down?

Cannot reproduce

![image](https://user-images.githubusercontent.com/13260377/64698694-a7b62280-d4a3-11e9-9517-f4b45e89b300.png)

**Comment by linsui** [comment]
Oh sorry....
I got this

```
scoop install cudatext
Unable to connect to the remote server
URL https://www.fosshub.com/CudaText.html/cudatext-win-x64-1.86.5.0.zip is not valid
ERROR It looks like a previous installation of cudatext failed.
Run 'scoop uninstall cudatext' before retrying the install.
```

**Comment by Ash258** [comment]
I do not have problem in any of my VMs.

You could try to change url to `https://www.fosshub.com/CudaText.html?dwl=cudatext-win-x64-1.86.5.0.zip`, but i think this is your local problem.

**Comment by linsui** [comment]
Yeah, you are right. Thanks!
