### ISSUE TITLE
Moving to scoop's google chrome

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop#3647]
What are the steps to transfer all settings and cache to the scoop's version of Google Chrome? I expect it will be copy/paste and the browser is 64bit version?

**Comment by Ash258** [comment]
None. Chrome is using appdata.

**Comment by quantuumsnot** [comment]
So I can copy because a lot of opened tabs (40-50) are at important scroll positions?

**Comment by grantcarthew** [comment]
Scroll positions? You love your browser state @quantuumsnot.

Have you tried Firefox with the [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/)  ([GitHub](https://github.com/piroor/treestyletab)) extension? You can't get it on Chrome. Some people have tried to make it however it is just too hard on the Chrome API.

You will move over to Firefox just to use that.

`scoop install firefox`

Here are some good reasons to start using Firefox:

* Mozilla's Mission: Keep the internet open and accessible to all.
* [Firefox Quantum](https://blog.mozilla.org/blog/2017/11/14/introducing-firefox-quantum/)
* [Content Blocking](https://support.mozilla.org/en-US/kb/content-blocking)
* [Google Says It Isn't Killing Ad Blockers. Ad Blockers Disagree](https://www.wired.com/story/google-chrome-ad-blockers-extensions-api/)
* [Web Browser Market Share (1996-2019)](https://www.youtube.com/watch?v=es9DNe0l0Qo) - Chrome is becoming the new IE (control).

**Comment by quantuumsnot** [comment]
Yes, usually I'm switching between a lot of info to read and current scroll position is important when trying to remember what's left to be read. And holding a lot of opened tabs while using some tab managing addon gives at least a performance hit and some UX issues which depends of the user's reading style

For the moment performance Firefox is only for testing, they improved the performance a lot but still most of the sites I use for work or testing things are somewhat faster that FF

**Comment by quantuumsnot** [comment]
Ok, backed up the 'User Data' dir, uninstalled Chrome and installed it again with scoop. Now I'm writing from it but found that Chrome reports the following in 'About Google Chrome':

> An error occurred while checking for updates: Update check failed to start (error code 1: 0x80004005).
Learn more
Version 77.0.3865.75 (Official Build) (64-bit)

Is it possible that scoop installs apps in a different dir (in my case I set to be on second RAID drives/Logical D:) and Chrome is secured updating itself in unknown dir? Should I set the dir to be different with `--user-data-dir=D:\scoop\apps\googlechrome\current\User Data\Default`

**Comment by quantuumsnot** [comment]
Seems it's not possible to use 'User Data' as the same name for `user data dir', after closing and starting both Chrome and Chrome Canary created a new one called `User` ... Just rename it, add everything from backed up `User Data` to `User` and have fun :)
