### ISSUE TITLE
hash check fails when installing pshazz

### ISSUE THREAD

**Issue by d3relict** [lukesampson/scoop#365]
checking hash...hash check failed for https://github.com/lukesampson/pshazz/archive/3b7b426320e42718b7ef3b0ebf9bbe06c6ee0430.zip. expected: 775c08d753b33ae53e03d2ef22debe6f352dd5e4abeeb7284441f7194756d0f3, 
actual: b8ee4ccffa719bbe97b47856457592f13ce4103e92b6bb41ff421a00f21bb08a!

**Comment by lukesampson** [comment]
Sorry about that, thanks for letting us know :+1:
