### ISSUE TITLE
Use scoop to discover software

### ISSUE THREAD

**Issue by grantcarthew** [lukesampson/scoop#3658]
# Suggestion

I've been using scoop for the last few weeks and have been thinking about one use for it that does not seem to be in scope yet.

The buckets are far more than just easy ways to install software, they are also a fantastic way to discover software.

As an example, I have been going through the `games` bucket to find games for my kids to play. To do so I have been clicking on all the `json` files in the bucket([using Octotree](https://www.octotree.io/)), copying the URL and reading about the game. So far I am up to some game called `nethack`.

## Discover Software using Scoop

I propose three changes to the project to enable it to facilitate software discovery:
1. Add a required attribute to the bucket manifest being `category`.
   * There could also be a sub-category on analysis. Maybe a major and minor category.
   * The category assigned to a package should be from a fixed and maintained list of categories. Maybe the major category is fixed with the minor being flexible.
1. Add a `scoop category` command that lists all the fixed categories of the software package.
1. Add a `scoop category <some category name>` to list all the packages in a category.

Although the known buckets are a type of category, they don't really help you discover software by using scoop. By making the above changes, I could run a scoop command to find all the available software packages that support `clipboard management` for example.

## Popularity Contest

Similar to how Debian GNU\Linux does, you could add a popularity contest to the scoop project to help with the software discovery.

I'm not sure how you could keep the data for the popularity contest, however here is how the workflow would go:

1. User decides to install scoop and gets prompted if they would like to join the popularity contest. They say yes.
1. When the user installs a package, a POST request goes out to an endpoint of some sort with the name of the package. *Thoughts: how do you stop abuse of the POST endpoint*. This is not a critical feature so if the POST fails, do so silently.
1. When any user does a `scoop search` or `scoop category`, retrieve the package popularity and report it with the details. Rather than total installs, installs per month would be a better metric.

## Summary

By adding software discovery features and a popularity contest, anyone using scoop can discover software of interest without having to open a browser and search the internet.

**Comment by linsui** [comment]
Scoop is an app installer, not an app store. But after https://github.com/lukesampson/scoop/pull/3446 is completed, it will be possible to discover new app in scoop. You can also use https://scoop-docs.now.sh/apps/ for now.

**Comment by grantcarthew** [comment]
Thanks @linsui, I didn't know about the new docs. I can't find a reference to them from the scoop.sh site.

The search there is quite good.

I still think the popularity contest would help.

Thanks anyway.

**Comment by h404bi** [comment]
> Thanks @linsui, I didn't know about the new docs. I can't find a reference to them from the scoop.sh site.

Check the awesome list https://github.com/ScoopInstaller/Awesome

**Comment by grantcarthew** [comment]
Great. Thanks @h404bi
