### ISSUE TITLE
Missing hashes

### ISSUE THREAD

**Issue by SonOfDiablo** [lukesampson/scoop#3663]
I was playing around with Scoop and the [scoop-games](https://github.com/Calinou/scoop-games/tree/master/bucket) bucket and I found a few apps that didn't have a hash in their manifest.

Examples: darkplaces and ioquake3

Is this normal with Scoop apps? 
As far as I can tell the hases is used to check up against VirusTotal and to validate installations, are they used for anything else?

Also is there a way to tell if there is a valid hash or not before installing (other than running the app through VirusTotal or checking the manifest manually)?

**Comment by linsui** [comment]
When the version is `nightly`, the hash is not required.

**Comment by SonOfDiablo** [comment]
Oh that makes some kind of sense.
Thank you very much for the info!

**Comment by rasa** [comment]
Clarified
