### ISSUE TITLE
Install fails when no URL is provided in manifest

### ISSUE THREAD

**Issue by manmademagic** [lukesampson/scoop#3664]
When trying to install a package that has no URL defined in the manifest, scoop throws the following errors:

```
Test-7zipRequirement : Cannot bind argument to parameter 'URL' because it is null.
At C:\Users\manmademagic\scoop\apps\scoop\current\lib\depends.ps1:80 char:78
+ ... elper 7zip) -and (Test-7zipRequirement -URL (url $manifest $arch))) {
+                                                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-7zipRequirement], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-7zipRequirement

Test-LessmsiRequirement : Cannot bind argument to parameter 'URL' because it is null.
At C:\Users\manmademagic\scoop\apps\scoop\current\lib\depends.ps1:83 char:84
+ ... Lessmsi) -and (Test-LessmsiRequirement -URL (url $manifest $arch))) {
+                                                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-LessmsiRequirement], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-LessmsiRequirement

'tzutil' doesn't support 64bit architecture!
```

The [json schema](https://github.com/lukesampson/scoop/blob/master/schema.json#L526) for the manifest files states that 'version' is the only required property.

The following manifest is what I'm currently testing:
```json
{
    "version": "1.0",
    "pre_install": "write-host 'test'"
}
```

The error is coming from [install_deps in /lib/depends.ps1](https://github.com/lukesampson/scoop/blob/3e55a70971c5ff0d035daa54ca5dfab95dfaaa1d/lib/depends.ps1#L80) which is calling [url](https://github.com/lukesampson/scoop/blob/3e55a70971c5ff0d035daa54ca5dfab95dfaaa1d/lib/manifest.ps1#L102) and in turn [arch_specific](https://github.com/lukesampson/scoop/blob/3e55a70971c5ff0d035daa54ca5dfab95dfaaa1d/lib/manifest.ps1#L66) in [/lib/manifest.ps1](https://github.com/lukesampson/scoop/blob/master/lib/manifest.ps1)

**Comment by niheaven** [comment]
Indeed URL is required too... Meta package is not accepted now.

**Comment by Ash258** [comment]
Duplicate of #2155 

See https://github.com/lukesampson/scoop/issues/2155#issuecomment-518469677 for workaround

**Comment by Ash258** [comment]
Just use url with blank txt file (for examle).

**Comment by perixiaowan** [comment]
> Just use url with blank txt file (for examle).

I am a newbie. 
There is a IOS safari bug in my developed Web project. I want to have a try to  install ios-webkit-debug-proxy to debug it.
 After I use this command 'scoop install ios-webkit-debug-proxy' in the PowerShell, it throw the exception the same with top issue. 

I think I get the mean how to solve , but I don't know how to write the command with url or where should I to put this blank txt file. 

I am so ashamed. Sincerely wish to receive your answer. thanks again.

**Comment by Ash258** [comment]
@perixiaowan Your issue has nothing to do with this one.

I do not have problem with application you mentioned.

![image](https://user-images.githubusercontent.com/13260377/66990870-5105bf00-f0c7-11e9-8c32-77856bb3615c.png)

Open separate issue in extras bucket if you encounter issues with specific application.

**Comment by perixiaowan** [comment]
hi,thank you for your reply. 
here is my PowerShell screenshot. 
![scoop](https://user-images.githubusercontent.com/7885334/66992899-3d754b00-f0fd-11e9-8d8a-7dcfd11d8d6e.PNG)
maybe it would be usefull for me to express this problem clearly . 
really appreiciate it that waste your time to relay.

**Comment by linsui** [comment]
ios-webkit-debug-proxy only works on 64bit machine but you are using a 32bit machine...

**Comment by perixiaowan** [comment]
> `scoop install 7zip ios-webkit-debug-proxy`
> 
> If this do not help open separate issue in https://github.com/lukesampson/extras to not populate this discussion with offtopic threads.

thanks very much .  I think I the wrong environment (powershell x86). when I changed to powershell 64bit, it works!
You are soooooooo kind. thanks !!!!

**Comment by perixiaowan** [comment]
> ios-webkit-debug-proxy only works on 64bit machine but you are using a 32bit machine...

thank you very very much . this method solved my problem. ^(oo)^

**Comment by manmademagic** [comment]
> Duplicate of #2155
> 
> See [#2155 (comment)](https://github.com/lukesampson/scoop/issues/2155#issuecomment-518469677) for workaround

Thanks for the link, I did have a search before logging, but couldn't find anything.
