### ISSUE TITLE
About the Download Directory

### ISSUE THREAD

**Issue by git-wanglei** [lukesampson/scoop#3666]
How can I modify the source file path for download and installation?All installation files are now defaulted to the cache folder

**Comment by Ash258** [comment]
This does not make sense at all. What is your problem and what you want to achieve?

> All installation files are now defaulted to the cache folder

You want to change cache folder? You apps are installed under cache folder? Or what?

https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by git-wanglei** [comment]
I can customize the installation source file storage path

**Comment by niheaven** [comment]
Set `$Env:SCOOP_CACHE` to some custom folder, or run `scoop config cachePath some_other_location`.

**Comment by rasa** [comment]
No response received.
