### ISSUE TITLE
add an option to use 7zip as default zip extractor

### ISSUE THREAD

**Issue by 0b11111111** [lukesampson/scoop#3667]
`Expand-Archive` is incredibly slow, check this [issue](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/32), and it tooks about 5 to 10 minutes to extract the golang, while 7zip only use 1 to 2 minutes..

i found that scoop will use `Expand-Archive` in powershell version >= 5, so can you make an option to let us choose the default extractor?

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/pull/3460

**Comment by toburger** [comment]
When will this be released?
