### ISSUE TITLE
krita: 4.2.5 -> 4.2.6 not working

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [lukesampson/scoop#3668]
EDIT: This is an issue both with scoop and Powershell 6+ . This issue is solved by using the bundled Microsoft Powershell. From my limited understanding on the issue it seems Powershell 6+ always returns a 302 redirect (as the standard suggests) but since all HTTP implementations are non standard Mozilla recommended only doing a 302 Found  ONLY on method changes. Also scoop does not follow up the 302 Found with a 303 or 307 as HTTP standard requests. The effect is the connection is terminated upon receiving a 302 Found.

```krita: 4.2.5 -> 4.2.6
Updating one outdated app:
Updating 'krita' (4.2.5 -> 4.2.6)
Downloading new version
The remote server returned an error: (302) Found.
At ...scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], WebException
+ FullyQualifiedErrorId : The remote server returned an error: (302) Found.```

**Comment by linsui** [comment]
The download url is redirected from https to a http mirror. You can try again or download it manully.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@linsui  the only issue with downloading it manually is I will not have the benefit of using scoop to update. I don't understand why it has worked until now but all the sudden no longer works

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
odd. i tried with a different version of powershell and it worked

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
It appears to be an issue between how scoop and Powershell work. 

Though not exactly the same issue as I have reported here there are issues reported on both PS and scoop side https://github.com/lukesampson/scoop/issues/3535 and https://github.com/PowerShell/PowerShell/issues/2896

I did a bit of investigation and I found that PS 6+ appears to work differently with 302 redirects than the Windows bundled PS. 

According to mozilla https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302
> not all user-agents conform here - you can still find this type of bugged software out there. It is therefore recommended to set the 302 code only as a response for GET or HEAD methods and to use 307 Temporary Redirect instead, as the method change is explicitly prohibited in that case.


And from wikipedia 

> Many web browsers implemented this code in a manner that violated this standard, changing the request type of the new request to GET, regardless of the type employed in the original request (e.g. POST).[1] For this reason, HTTP/1.1 (RFC 2616) added the new status codes 303 and 307 to disambiguate between the two behaviours, with 303 mandating the change of request type to GET, and 307 preserving the request type as originally sent.

So what is really going on is the implementation of the HTTP protocol may be non standard but PS 6+ expects a standard and scoop has never follows up with a 303 or 307 redirect when receiving a 302. On MS PS it works because it does the redirect but on PS6+ it returns 302 especting the software scoop to make another redirect.

Anyway please correct me if I am wrong. I am just an end user and I just noticed this issue. I switched back to old MS PS because seems less strict.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I think scoop does follow 302 so it may be a PS specific issue only. I will close this for now because is fixed by using older PS version.
