### ISSUE TITLE
Swapping versions by redirecting the junction folder?

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop#3670]
Unless I'm missing something, there's no easy way to "swap" to a previously installed version with scoop. `scoop reset` doesn't really do that, it just resets the `current` folder to the latest version of the app, at least as far as I have seen.

Since every time we `scoop update` an app a new version folder gets created, and that folder still remains there (unless `scoop cleanup` is run), what prevents the creation of a command to change an app's `current` junction folder destination to a previously installed version?
E.g. user installs `azuredatastudio`, which happens to be version 1.11.0;
days later, a new version (1.12.0) is released; user runs `scoop update`, now he has both version installed (`\scoop\apps\azuredatastudio\1.11.0` and `\scoop\apps\azuredatastudio\1.11.0`), but `current` points to the most recent one (1.12.0);
user finds a bug in the current version that blocks his work, so he runs a `scoop rollback azuredatastudio@1.11.0` command to make the `current` folder point again at the `1.11.0` folder which still contains the previous version.

What would prevent this from being implemented?

**Comment by Ash258** [comment]
`scoop reset azuredatastudio@1.11.0`

![image](https://user-images.githubusercontent.com/13260377/66127868-f9f2eb00-e5ec-11e9-85c1-df367bb58ae7.png)

**Comment by LoZeno** [comment]
Ah, that sidenote is probably what tricked me into thinking that `scoop reset` wasn't doing that. My bad!

**Comment by LoZeno** [comment]
Forgot to close the issue
