### ISSUE TITLE
[Extras] Add Ghidra support

### ISSUE THREAD

**Issue by T145** [lukesampson/scoop#3671]
https://ghidra-sre.org/

**Comment by SonOfDiablo** [comment]
If you want Ghidra as an app you can install from Scoop then you might want to suggest it over on the [Extras Bucket Repo](https://github.com/lukesampson/scoop-extras), make your own bucket or check out this [Bucket](https://github.com/TheCjw/scoop-retools) that is all about Reverse Engineering tools.

**Comment by r15ch13** [comment]
Duplicate of https://github.com/lukesampson/scoop-extras/issues/1814
