### ISSUE TITLE
[optimization]Problems when installing Wirshark

### ISSUE THREAD

**Issue by Soowin** [lukesampson/scoop#3674]
Most of times when installing Wireshark on Windows, it would automatically install winpcap and make it start on boot to enable the npf service. Without winpcap, wireshark counld't work properly alone.
Suggestion: When using "scoop install wireshark", suggest users install winpcap manually, or help them install it automatically.

**Comment by SonOfDiablo** [comment]
@Soowin you might have betterr luck with posting this issue over at https://github.com/lukesampson/scoop-extras/issues since that's the bucket that contains Wireshark and this is the Github Repo for Scoop itself :)

**Comment by Soowin** [comment]
Thank you so much! Best wishes!
