### ISSUE TITLE
Force reinstall an app after a failed update?

### ISSUE THREAD

**Issue by wuya666** [lukesampson/scoop#3679]
Today when I tried to update mysql server with scoop, the installation file is downloaded successfully, but there's not enough space on disk to extract the whole thing, so the update script failed and the mysql app is left in a broken state. However after I clean up some disk space and try update mysql again, it shows the mysql as already updated to the newest version, but the actually mysql server app is currently broken. So is there any way to force scoop to reinstall the mysql server without uninstalling it first (I don't want to uninstall it as there are tons of data stored in the database)?

**Comment by linsui** [comment]
Uninstall won't remove your data, they are stored in persist directory. If you want to remove your data, you can add `-p` option.

```
Usage: scoop uninstall <app> [options]

e.g. scoop uninstall git

Options:
  -g, --global   Uninstall a globally installed app
  -p, --purge    Remove all persistent data
```

**Comment by wuya666** [comment]
I'm kinda afraid to do an uninstall since in the past I've lost settings and configurations to some of the apps (ie. mobaXterm and things) after an uninstall. Anyway I've successfully reinstalled the app with the  `-f` option

> scoop update -f mysql

And that solved all the problems, even using the cached setup file without the need of a redownload, which is really nice :)
