### ISSUE TITLE
Installing varying architecture side by side?

### ISSUE THREAD

**Issue by sprite-1** [lukesampson/scoop#3702]
I need both the 32bit and the 64bit version of `nim` installed but if I already have one architecture type installed and tried to install the other with the appropriate flag, it complains about the package already being installed.

I also need the same for `gcc`

Is this a bug?

**Comment by kraptor** [comment]
Just came here as I have exactly the same issue with llvm...

**Comment by rasa** [comment]
Duplicate of #3265
