### ISSUE TITLE
Couldn't find manifest for 'firefox'

### ISSUE THREAD

**Issue by blankws** [lukesampson/scoop#3703]
I use the command 'scoop install firefox', and the scoop give this response:'Couldn't find manifest for 'firefox'.'
Then I run the command 'scoop update' and run 'scoop install firefox', but it's still 'Couldn't find manifest for 'firefox'.'
what should I do?

**Comment by Ash258** [comment]
What is result of `scoop bucket list`?

**Comment by blankws** [comment]
'main'

**Comment by Ash258** [comment]
Then you need to add extras bucket. 

`scoop bucket add extras` and then you can install firefox.

if you type `scoop search firefox` it should guide you.

**Comment by blankws** [comment]
It works！Thank you so much for your patiently help and makes nice tool!

**Comment by perlisngankam2** [comment]
> Then you need to add extras bucket.
> 
> `scoop bucket add extras` and then you can install firefox.
> 
> if you type `scoop search firefox` it should guide you.

**Comment by linxms** [comment]
I use the command 'scoop install extras/anaconda3', and the scoop give this response: 'Couldn't find manifest for 'anaconda3'.
Then I run the command 'scoop update' and run 'scoop install extras/anaconda3' but it's still 'Couldn't find manifest for 'anaconda3'.' Then I run the 'scoop bucket add extras', but it's response is 'ERROR 'https://github.com/ScoopInstaller/Extras' doesn't look like a valid git repository

Error given:
fatal: unable to access 'https://github.com/ScoopInstaller/Extras/': Failed to connect to github.com port 443 after 21110 ms: Couldn't connect to server'
what should I do?

**Comment by HUMORCE** [comment]
> I use the command 'scoop install extras/anaconda3', and the scoop give this response: 'Couldn't find manifest for 'anaconda3'.
> Then I run the command 'scoop update' and run 'scoop install extras/anaconda3' but it's still 'Couldn't find manifest for 'anaconda3'.' Then I run the 'scoop bucket add extras', but it's response is 'ERROR 'https://github.com/ScoopInstaller/Extras' doesn't look like a valid git repository
> 
> Error given:
> fatal: unable to access 'https://github.com/ScoopInstaller/Extras/': Failed to connect to github.com port 443 after 21110 ms: Couldn't connect to server'
> what should I do?

https://github.com/ScoopInstaller/Scoop/wiki/Using-Scoop-behind-a-proxy

**Comment by Ungotable** [comment]
Updating Scoop...
Updating Buckets...
INFO  Converting 'main' bucket to git repo...
ERROR 'main' bucket not found.
Failed to remove local 'main' bucket.
Couldn't find manifest for 'fzf'.

**Comment by HUMORCE** [comment]
> Updating Scoop... Updating Buckets... INFO Converting 'main' bucket to git repo... ERROR 'main' bucket not found. Failed to remove local 'main' bucket. Couldn't find manifest for 'fzf'.

Scoop has not handled git errors, so:

Make sure that you have installed git, then: `scoop bucket rm main; scoop bucket add main`.

Try clone main bucket manually, if the problem still exists:
```
> cd ~/scoop/buckets # default Scoop installation path
> git clone https://github.com/ScoopInstaller/Main main
```

**Comment by nanoraptor** [comment]
For any of you having issues with installing extras bucket. Try increasing the buffer size and execute the install command again.
-      git config --global http.postBuffer 524288000
-      scoop bucket add extras
After installing reset the buffer size by this command:
-      git config --global --unset http.postBuffer

**Comment by nuf0n** [comment]
> Then you need to add extras bucket.
> 
> `scoop bucket add extras` and then you can install firefox.
> 
> if you type `scoop search firefox` it should guide you.

Thank you! Genuinely surprised this is still a problem in 2026! Need to add _extras_ for another app.
