### ISSUE TITLE
error: You have not concluded your merge (MERGE_HEAD exists).

### ISSUE THREAD

**Issue by nagromc** [lukesampson/scoop#3705]
On a `scoop update *`, I stumble upon the following error:

```shell
$ scoop update *
Updating Scoop...
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
Update failed.
```

I searched in my entire hard drive for a file named `MERGE_HEAD`, but no result.

```shell
$ fd MERGE_HEAD C:/

<empty return>
```

I've `git merge --abort` and `git reset --hard origin/master` every buckets in `~/scoop/buckets`, but I've the same error.

I couldn't find any logs. Any thought?

**Comment by Ash258** [comment]
You had to manipulate with your scoop installation

`cd "$env:SCOOP\apps\scoop\current"; git merge --abort; git reset --hard; git pull`

**Comment by nagromc** [comment]
That's it!
