### ISSUE TITLE
Move git-preview from scoop-extras to scoop

### ISSUE THREAD

**Issue by cng-thg** [lukesampson/scoop#371]
If you need to install git, the git app available in scoop list is git which install msysgit 1.9.5-preview, which I think is a really old version of git.

scoop-extras bucket has a git-preview app which install git for windows 2.4.0, a much for newer version  (the latest git version is 2.4.1).

The only problem I found is that if you wish install git-preview you need add scoop-extras bucket first and you need git for this, so in my case, I need to install git (1.9.5), add scoop-extras, then remove git and install git-preview (2.4.0). 

So I ask you if you could move git-preview app to scoop list instead of scoop-extras bucket, so it will be needed only on install.

**Comment by deevus** [comment]
You're right. 1.9.5-preview is a very old version of git. However for a long time it was the only stable version available. 

We have been testing the newer builds of git under `git-preview` in scoop-extras to make sure it is ready to move to the main bucket. 

Check out our discussion here: https://github.com/lukesampson/scoop-extras/pull/86

**Comment by deevus** [comment]
@lukesampson Does the latest version of `git-preview` solve your issue with ssh-agent?

**Comment by lukesampson** [comment]
No it still doesn't work, unfortunately. I'd be ok with making the preview version the new `git` and moving the current version to `git19` though, if you want?

**Comment by deevus** [comment]
Yeah @lukesampson I'm happy to as well. Would @cng-thg be happy to submit the PRs?

**Comment by deevus** [comment]
Fixed in fc9b7f9308a15f6e2a1334f26e3727e00bd4298b
