### ISSUE TITLE
Version variables in more manifest properties

### ISSUE THREAD

**Issue by abejenaru** [lukesampson/scoop#3712]
Hi,
I tried creating a manifest for an app where the binary and the app archive both contain version information;
_bin_ / _shortcuts_ and _extract_dir_ properties would benefit from having access to version variables.

**Comment by Ash258** [comment]
`extract_dir` is possible to use in autoupdate and is widely used inside manifest in Main / Extras.

For bin you most likely do not want to have version number inside it as will result into calling appilcation from path with ugly executable (`yarn-123.5.7.exe --add something` which is something you do not want). So in manifest there is pre_install / installer scripts with `gci $dir '*' | % { Rename-Item $_.Fullname 'newName' }`

Shortcuts will be possible after refactoring of autoupdate is done as current autoupdate is not capable of doing nested array.

**Comment by rasa** [comment]
Clarified, duplicate
