### ISSUE TITLE
scoop says lynx needs openssl 32bit. openssl is installed. Lynx install also partly broken.

### ISSUE THREAD

**Issue by axtens** [lukesampson/scoop#3714]
```
>scoop install lynx
Updating Scoop...
...
Scoop was updated successfully!
Installing 'lynx' (2.9.0dev.4) [64bit]
lynx-newssl-setup.exe (1.4 MB) [==============================================================================] 100%
Checking hash of lynx-newssl-setup.exe ... ok.
Extracting lynx-newssl-setup.exe ... done.
Running pre-install script...
Linking ~\scoop\apps\lynx\current => ~\scoop\apps\lynx\2.9.0dev.4
Creating shim for 'lynx'.
Persisting $dir/lynx.cfg
The system cannot find the path specified.
Path not found - C:\Users\bugma\scoop\apps\lynx\current\$dir
Running post-install script...
lynx requires the 32-bit version of openssl to be installed

>lynx
(assorted error dialogs appear)

>scoop search openssl
'main' bucket:
    openssl-mingw (1.1.1d_2)
    openssl (1.1.1d)


>scoop install openssl
WARN  'openssl' (1.1.1d) is already installed.
Use 'scoop update openssl' to install a new version.
```
Also something wrong in lynx install itself
```
Persisting $dir/lynx.cfg
The system cannot find the path specified.
Path not found - C:\Users\bugma\scoop\apps\lynx\current\$dir
```

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/issues/3105 . Please try `scoop uninstall openssl; scoop install -a 32bit`

**Comment by axtens** [comment]
worked once I changed the second part to
```
scoop install openssl -a 32bit
```
Will this work with tools that require 64bit openssl or can I also install the 64bit side by side?

**Comment by linsui** [comment]
Unfortunately, Scoop can't install openssl 64bit and 32bit side by side now.

**Comment by linsui** [comment]
Could you have a look at https://github.com/ScoopInstaller/Main/pull/512 ?

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3714
