### ISSUE TITLE
autoupdate conditionally broken with pwsh core 6

### ISSUE THREAD

**Issue by matoro** [lukesampson/scoop#3717]
I am trying to switch to powershell core 6 and I have 2 packages in my bucket where one autoupdate check works and the other fails.  Both work under powershell desktop 5.

This package works under both:  https://github.com/matoro/bucket/blob/master/pcsx2-nightly.json
This package works under 5:  https://github.com/matoro/bucket/blob/master/nvidia-display-driver.json
But when run under 6 it spits out:
```
nvidia-display-driver: An exception occurred during a WebClient request.
URL https://www.nvidia.com/Download/processFind.aspx?psid=95&pfid=694&osid=19&lid=1&whql=&lang=en-us is not valid
```

Edit:  version tables:
```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Ash258** [comment]
Cannot reproduce with powershell 5.1.18362.145, 6.2.3, 7.0.0-preview.5

![5](https://i.imgur.com/pPdkV3g.png)

![6](https://i.imgur.com/ZpfJZW7.png)

![7](https://i.imgur.com/ZqoGp8y.png)

Not even with 6.2.2

![6.2](https://i.imgur.com/6XimlRE.png)

**Comment by matoro** [comment]
Thank you very much for checking.  Would this exception be issued if it were a transient network issue that dropped the request?

**Comment by Ash258** [comment]
Try to mimic code used inside checkver interactively.

https://github.com/lukesampson/scoop/blob/6eb90c9c112c8c6c1790f1bd4e1c9cd67a6e70df/bin/checkver.ps1#L99-L104

https://github.com/lukesampson/scoop/blob/6eb90c9c112c8c6c1790f1bd4e1c9cd67a6e70df/bin/checkver.ps1#L160-L172

Theoritically you could see same result if you do simple `(New-Object Net.WebClient).DownloadString('https://www.nvidia.com/Download/processFind.aspx?psid=95&pfid=694&osid=19&lid=1&whql=&lang=en-us')` It is not async, but this quick test could give you some insight.

**Comment by matoro** [comment]
You're right, I can't reproduce it any more.  Guess that means it was just a one-off issue.  Thank you for taking the time to double-check; it's much appreciated.
