### ISSUE TITLE
Why I have to uninstall twice after installation failed?

### ISSUE THREAD

**Issue by kid1412621** [lukesampson/scoop#3718]
![image](https://user-images.githubusercontent.com/26278054/67658331-40d9c380-f994-11e9-9f28-dabaca688cc5.png)

`scoop i` is alias for `scoop install`
`scoop rm` is alias for `scoop uninstall`

**Comment by niheaven** [comment]
One for removing existed `apps\DIR` while another for removing wrong download cache...

**Comment by kid1412621** [comment]
@niheaven  um...weird, didn't see this case on brew or apt

**Comment by LoZeno** [comment]
I think you can skip one of the two `uninstall` if you do run `scoop cache rm ngrok` in its place

**Comment by kid1412621** [comment]
> I think you can skip one of the two `uninstall` if you do run `scoop cache rm ngrok` in its place

Thanks, but still two steps.

**Comment by linsui** [comment]
You can set a alias.
