### ISSUE TITLE
Why always warning on psmodule update?

### ISSUE THREAD

**Issue by Moeologist** [lukesampson/scoop#3720]
https://github.com/lukesampson/scoop/blob/6eb90c9c112c8c6c1790f1bd4e1c9cd67a6e70df/lib/psmodules.ps1#L25
Expected behavior: no warning on normal update

**Comment by Ash258** [comment]
Because PSModules are not uninstalled on updates. Fixed in #3708

**Comment by Moeologist** [comment]
> Because PSModules are not uninstalled on updates. Fixed in #3708

This PR not unlink junctions in $modulesdir.
scoop on develop emit the same warning:
```powershell
WARN  $modulesdir\[module] already exists. It will be replaced.
```

**Comment by Ash258** [comment]
This change is not in develop yet...

**Comment by Moeologist** [comment]
> This change is not in develop yet...

Sorry...
