### ISSUE TITLE
I can not install scoop 

### ISSUE THREAD

**Issue by bbruceyuan** [lukesampson/scoop#3727]
hello. 

just now, I have installed scoop according to the command listing in website.

while something wrong happened. so I use `ctrl + c` to stop running a command `scoop install git`.
after I using `ctrl + c`, I can not use `scoop ` command. as a result, I uninstall scoop by del scoop dir. 

and I am sure that there is no dir about scoop in my laptop.  ( I find dir key word `scoop` globally and find nothing)

my first command is set remotesigned and I confirm it with Y.
and second command did run correctly. the red box I drawed in Chinese means "there are something exception when using "downloadstring", because it cannot connect the remote server. 

how can I solve this problem? Thanks for taking your time helping me in advance.

![TIM图片20191104151406](https://user-images.githubusercontent.com/16234167/68104461-1a78d280-ff16-11e9-876e-a0c6b492ee51.png)

and I can ping `get.scoop.sh` without any trouble.

**Comment by linsui** [comment]
Could you please try [this](https://github.com/ScoopInstaller/Install) ? Maybe get.scoop.sh is blocked.

**Comment by bbruceyuan** [comment]
I have tried your method. and I found that maybe I am blocked by the Chinese internet. I can not even download the `*.sh`  script. and I will try to find another proxy to download the script.

I will try another mehod and if I succeed in solving this problem, I will give you a reply and close this issue.

**Comment by linsui** [comment]
It's redirected to https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1, you can just replace get.scoop.sh with this url.

**Comment by bbruceyuan** [comment]
and I tried this url (look at the following image) . 
same problem. 
maybe I just need a proxy tool (my old one crash this morning)


![{54A4C65F-916D-439E-82D6-856D7B51BAE4} png](https://user-images.githubusercontent.com/16234167/68107363-988da700-ff1f-11e9-8d79-e0938f827157.jpg)

**Comment by bbruceyuan** [comment]
@linsui thanks. I have solved my problem. It's something wrong about network which is special for Chinese. It can be solved by set proxy in terminal.

**Comment by kerwin58** [comment]
> @linsui thanks. I have solved my problem. It's something wrong about network which is special for Chinese. It can be solved by set proxy in terminal.

你是怎么处理的，我也是这个问题，可以告诉我吗？谢谢。

**Comment by linsui** [comment]
@kerwin58 It seems that Github access is unstable in China nowadays... But I guess you can access GitHub in browser. So just download script from https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1 and run it.

**Comment by kerwin58** [comment]
> @kerwin58 It seems that Github access is unstable in China nowadays... But I guess you can access GitHub in browser. So just download script from https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1 and run it.

Thank you
