### ISSUE TITLE
Can't install elixir: ERROR Exit code was -1073741515!

### ISSUE THREAD

**Issue by julianpoma** [lukesampson/scoop#3731]
Trying to install `elixir` on Windows 1903 throws the following error

```
PS > scoop install elixir
Installing 'erlang' (22.1) [64bit]
Loading otp_win64_22.1.exe from cache
Checking hash of otp_win64_22.1.exe ... ok.
Extracting dl.7z ... done.
Running installer... error.
ERROR Exit code was -1073741515!
Installation aborted. You might need to run 'scoop uninstall erlang' before trying again.
```

I tried running my terminal with admin privilages but did not help

**Comment by linsui** [comment]
```scoop install extras/vcredist2013```

**Comment by julianpoma** [comment]
@linsui Was about to write the same thing. Just figured out! Thanks!

**Comment by wsdjeg** [comment]
@linsui but the install command is blocked at:

```
C:\Users\wsdjeg>scoop install extras/vcredist2013
Installing 'vcredist2013' (12.0.40660) [64bit]
Loading vcredist_x64.exe from cache
Checking hash of vcredist_x64.exe ... ok.
Loading vcredist_x86.exe from cache
Checking hash of vcredist_x86.exe ... ok.
Linking D:\scoop\apps\vcredist2013\current => D:\scoop\apps\vcredist2013\12.0.4
660
Running post-install script...
```

**Comment by thsturm** [comment]
Any news about installing erlang?

    Installing 'erlang' (26.0) [64bit] from main bucket
    otp_win64_26.0.exe (145,2 MB) [===============================================================================] 100%
    Checking hash of otp_win64_26.0.exe ... ok.
    Extracting dl.7z ... done.
    Running installer... error.
    ERROR Exit code was -1073741515!
    Installation aborted. You might need to run 'scoop uninstall erlang' before trying again.

And yes, vcredist2013 is already installed!

    Installed apps matching 'vcredist':
    Name         Version    Source Updated             Info
    ----         -------    ------ -------             ----
    vcredist2013 12.0.40664 extras 2023-05-20 19:28:49
