### ISSUE TITLE
Everything in start menu lost after win10 20H1 build update

### ISSUE THREAD

**Issue by Lips7** [lukesampson/scoop#3732]
![image](https://user-images.githubusercontent.com/51849534/68271756-956bf580-009c-11ea-9ccb-85c38a121af2.png)

**Comment by linsui** [comment]
Please try `scoop reset *`

**Comment by Lips7** [comment]
I pined all apps to start menu, and I execute the 'scoop reset *', nothing happened(there is still no folder named "scoop" in my start menu).
