### ISSUE TITLE
Installation of Notepadplusplus broken

### ISSUE THREAD

**Issue by sburkard** [lukesampson/scoop#3734]
The installation of notepadplusplus with Scoop is broken. 

Error message: The remote server returned an error: (503) Server Unavailable.                                                                                                                      URL https://notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.bin.x64.7z is not valid  

The reason is a DDoS protection by Cloudflare that seems to kick in when the download URL is opened directly. 

![image](https://user-images.githubusercontent.com/6469848/68309306-81c98a80-00ae-11ea-9d85-26e3d0ceefe2.png)

After about 5 seconds the download in a normal browser works. However, I don't know if it would also be sufficient for Scoop to wait some seconds.

**Comment by Ash258** [comment]
Duplicate of lukesampson/scoop-extras#3078

**Comment by ohk2kt3t4** [comment]
FYI: seems to be working at the moment.

**Comment by sburkard** [comment]
Thanks for the hint. Yes, it works again.
