### ISSUE TITLE
After windows restore, some of the shims seem to not work

### ISSUE THREAD

**Issue by tensor-programming** [lukesampson/scoop#3738]
I've noticed this a few times and its popped up in various different manners.  After running a system restore in Windows 10 some of the shims will just not work.  In some instances, the shims will just not display anything and then return to the console and in others they will work perfectly fine.  For instance, my Elixir installation has no `iex` shim anymore after the restore.  Also, `git` didn't work and it caused scoop to throw a ton of errors when I tried to run `scoop update *`.  Is there anyway that I can repopulate the shims without individually reinstalling all of the programs (I have quite a few installed).

**Comment by linsui** [comment]
Please try `scoop reset *`

**Comment by tensor-programming** [comment]
Alright, will give it a shot.
