### ISSUE TITLE
ERROR Hash check failed on "scoop install git"

### ISSUE THREAD

**Issue by 1019588237** [lukesampson/scoop#3743]
C:\Windows\system32>scoop install git
Installing 'git' (2.24.0.windows.2) [64bit]
PortableGit-2.24.0.2-64-bit.7z.exe (41.8 MB) [============================================>                   ]  71%
Checking hash of PortableGit-2.24.0.2-64-bit.7z.exe ... ERROR Hash check failed!
App:         main/git
URL:         https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    353d0e1566d8897cb7afe2f6f9088bac17182ca43416feadec1c16f5c3bb9e0f
Actual:      766cbd195f3d8044b31e6d26ac54e58edf149707252c889f0cec1cb8000820e1

+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Please try again or create a new issue by using the following link and paste your console output:
https:////

**Comment by Ash258** [comment]
> => ] 71%

Incomplete download

**Comment by 1019588237** [comment]
> > => ] 71%
> 
> Incomplete download
> 
> `scoop cache rm git; scoop uninstall git; scoop install git`

thanks you !!!
