### ISSUE TITLE
Cannot install global apps to custom directory

### ISSUE THREAD

**Issue by Cry0nicS** [lukesampson/scoop#3745]
I've been trying to install global apps to Program Files (I installed scoop there too). However, by doing so I'm running into `The '<' operator is reserved for future use.`

See screenshot attached.
![ConEmu64_AtMSgh2tUd](https://user-images.githubusercontent.com/29982205/68864572-0a24dc80-06fa-11ea-8438-7b5f30004d74.png)

**Comment by Ash258** [comment]
What application you are trying to install??

**Comment by Cry0nicS** [comment]
@Ash258 I guess I'm too tired for this :)
I thought I can set up a default directory where all upcoming apps to be installed....

**Comment by Ash258** [comment]
Yes you can. But `scoop install <app>` is nonsence as it is only example with placeholder. If you install anything with `scoop install git -g` (for example), then it will be installed into $env:SCOOP_GLOBAL
