### ISSUE TITLE
Using aria2 not installed by Scoop

### ISSUE THREAD

**Issue by Restia666Ashdoll** [lukesampson/scoop#3754]
Since, Persepolis comes bundled with aria2 and ffmpeg, so I decided to add %SCOOP%\apps\Persepolis\current to path environment variable and use them from command line just fine. But setting `scoop config aria2-enabled true` does not seem to make Scoop recognize aria2. Is there no way around this ?

**Comment by r15ch13** [comment]
Scoop doesn't look for it in the `%PATH%`, so you have to install aria2 via Scoop to use it.
