### ISSUE TITLE
Robocopy is not always in PATH

### ISSUE THREAD

**Issue by deevus** [lukesampson/scoop#376]
Having been a personal advocate of Scoop to several of my friends, I have been told this issue multiple times, even though I haven't experienced this myself.

After installing Scoop and trying to `scoop install` something, Robocopy can't be found. 

I'll see if I can get them to come and give more information in this thread.

**Comment by beaurepair** [comment]
Adding C:\Windows\System32 to the path seems to fix this issue

**Comment by deevus** [comment]
@beaurepair Is Powershell running as Administrator? What OS are you using?

**Comment by deevus** [comment]
@lukesampson It seems odd that `C:\Windows\System32` wouldn't be on the `PATH`. I think in every case `Robocopy.exe` should be there, so perhaps if `gcm robocopy` fails we can address it with an absolute path and `shim` it?

**Comment by lukesampson** [comment]
@deevus Yes that's a great idea.

**Comment by beaurepair** [comment]
@deevus Windows 8.1. Powershell was not run as administrator but I doubt that's relevant.
