### ISSUE TITLE
[feature request] support custom persist file

### ISSUE THREAD

**Issue by fcying** [lukesampson/scoop#3768]
Ex: my clink use a plugin `z`, it need copy `z.cmd` `z.lua` to clink folder. 
after clink update, two files will be removed.

Can I implement a custom persist file?

Ex, add a `persist.ini` to `persist\clink`, ini file recorded the location of 2 files, after `clink` install or update, read `persist.ini` and create the custom persist file or folder.

**Comment by quantuumsnot** [comment]
Not all data is persisted, that's for sure. Two casual ways to fix that:
1. Rewrite some scoop logic to persist ALL files in custom dir
2. Hardlink all scoop files from C: to your preferable drive

The third one is no so casual - ditch some apps from scoop and modify their portable versions to use their own directory (most of portable apps always write something on OS drive)
