### ISSUE TITLE
Scoop Reinstall Software

### ISSUE THREAD

**Issue by TylerHaigh** [lukesampson/scoop#377]
After having an issue with spacemacs, I uninstalled and reinstalled emacs and it worked

It would be a good feature to have a simple script to reinstall something (unlike reset) using `scoop reinstall foo` which calls

```
scoop uninstall foo
scoop install foo
```

Which would be a snap since scoop could then install from cache

**Comment by deevus** [comment]
After thinking about this a bit... I think that it could be solved using user aliases ([like git does aliases](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases)).

### Option 1

Something like `scoop config alias.reinstall "scoop uninstall {0}; scoop install {0}"` which can then be executed using `scoop reinstall foo`

### Option 2 

Create a command `scoop-alias` used like `scoop alias reinstall "scoop uninstall {0}; scoop install {0}"` which creates a user `scoop-alias.ps1` and shims it. 

@lukesampson What do you think about this?

**Comment by deevus** [comment]
As a personal motivation, I always accidentally run things like: 

```
scoop rm <app>
scoop remove <app>
scoop ls
scoop upgrade
```

Which obviously don't work.

**Comment by lukesampson** [comment]
@deevus that sounds good to me. I'm thinking option 2 would be easier, and would allow us to have some command-line help, with examples. What do you think?

**Comment by deevus** [comment]
Yeah no worries I'll have a look :)
