### ISSUE TITLE
"gcloud components install [...]" breaks app directory junction

### ISSUE THREAD

**Issue by J15t98J** [lukesampson/scoop#3773]
When the gcloud CLI is used to install a new component it stages the update in ".../scoop/apps/gcloud/current.Staging", and then writes that folder over the directory junction, breaking Scoop.

My current workaround is to manually move everything back after the update and then run scoop reset to regenerate the directory junction but, as I'm sure you can appreciate, this is a bit of a pain when I'm so used to just letting Scoop deal with everything!

I recognise that this is probably more Google's problem than Scoop's but I'm concerned they may dismiss it as "not a bug" - is there anything you can do?

**Comment by Ash258** [comment]
Would help if instead of:

```txt
apps
   --- gcloud
         --- X.X.X.
         --- current
              -- application files
```

would be this:

```txt
apps
   --- gcloud
         --- X.X.X.
         --- current
              --- folder with gcloud
                      --- application files
```

Then gcloud should stage the `folder with gcloud` folder instead of `current` junction right?

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3773
