### ISSUE TITLE
Is Crystal lang available for install?

### ISSUE THREAD

**Issue by luismateopineda** [lukesampson/scoop#3775]
Chocolatey doesn't seem to have Crystal lang, I was wondering if you guys have it in your repos?
Also, there doesn't seem to be any way to search scoop without installing scoop, maybe a page on the website would be good for people looking for software.

**Comment by linsui** [comment]
See https://scoop-docs.now.sh/apps/

**Comment by LoZeno** [comment]
I don't think that the Crystal compiler runs natively on Windows, last I used it was usable only on the Windows Subsystem for Linux.

Unless there's a windows executable available, I don't think that Scoop can even install it.

**Comment by rasa** [comment]
No native windows binaries

**Comment by rishavs** [comment]
Crystal exe is indeed available and Crystal does works on Windows.
Only networking currently doesn't works. But the language is good for system works and uses cases like game dev.

Please see the details here https://pryp.in/blog/28/running-crystal-natively-on-windows-building-videogame-examples.html

**Comment by rasa** [comment]
I don’t see Windows binaries at https://github.com/crystal-lang/crystal/releases/tag/0.35.1. Can you point out how to pull from the CI?

**Comment by Deide** [comment]
I believe you need to be signed in to Github to grab those artefacts. I don't think it's trivial to generate the link either.

**Comment by rishavs** [comment]
Its only available via CI right now
For example, https://github.com/crystal-lang/crystal/actions/runs/318052553 has the zipped artefact file which contains crystal.exe and the required libs.
