### ISSUE TITLE
autoupdate for github releases - allow "-N" suffix

### ISSUE THREAD

**Issue by pfmoore** [lukesampson/scoop#3783]
I have packaged GNU grep for scoop, and I want the version number to be the "base" GNU grep version number (3.3, currently) plus a suffix indicating my "build number" (I've made a number of changes over time to improve the port). The usual convention for something like this is to number my releases "3.3-1", "3.3-2", etc. In particular I *don't* want to use a dot to separate my build number, as that would cause issues should the FSF release a patch version 3.3.1.

Could the autoupdate for github releases be modified to allow for this style of release number? I think it should just be a relatively simple change to the regex used.

For now, I'll stop using the "github" autoupdate type and manually specify the regex.

**Comment by Ash258** [comment]
What permit you from using combination of github and custom regex?

**Comment by pfmoore** [comment]
Um, I don't know...? Is that possible? I must admit, I struggle to understand the wiki pages for the checkver stuff. I currently have:

```json
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/pfmoore/builder-grep/releases/download/$version/grep-$version.zip"
    }
```

The docs say checkver can have a `re` property, but if it does, how do I say it's github? It seems that checkver can either be a string ("github") or an object (do it all manually).

What I think I can do is:

```json
    "checkver": {
      "url": "https://github.com/pfmoore/builder-vim/releases/latest",
      "re": "/releases/tag/(?:v|V)?([-\d.]+)"
    }
```

but that's what I meant by "manually specifying", as I'm no longer using checkver's built-in github support at all.

Have I misunderstood?

**Comment by pfmoore** [comment]
I just checked, and that `checkver { url, re }` form I showed does indeed work. So I can go with that. It's not *that* difficult, just a bit annoying that I have to repeat my github URL yet another time...

**Comment by niheaven** [comment]
You could use `"github": "https://github.com/pfmoore/builder-grep"` with `"regex": "/releases/tag/(?:v|V)?([-\\d.]+)"`, `github` keyword append `/releases/latest` for you.

**Comment by pfmoore** [comment]
Thanks. I guess there are a couple of perfectly good solutions here, so no need to change anything. Thanks for the advice.
