### ISSUE TITLE
PHP_INI_SCAN_DIR: wrong path?

### ISSUE THREAD

**Issue by fritzmg** [lukesampson/scoop#3786]
All of a sudden, `php` (installed via scoop, either the main bucket or any of the versions from the version bucket) does not take my `custom.ini` within the `persist` folder into account anymore. I noticed that, when installing `php`, the `PHP_INI_SCAN_DIR` will point to: `~/scoop/apps/php/current/cli/conf.d`. But according to https://github.com/lukesampson/scoop/wiki/Custom-PHP-configuration it should point to `~/scoop/persist/php/cli/conf.d` instead. I am not sure what changed - why is the `persist` directory not working for the PHP configuration anymore?

**Comment by r15ch13** [comment]
The `~/scoop/apps/php/current/cli` directory is persisted.
See: https://github.com/ScoopInstaller/Main/blob/f48cf97f6ee07d22aab5019433cacca41bf773e5/bucket/php.json#L22

Setting `PHP_INI_SCAN_DIR` to `~/scoop/apps/php/current/cli/conf.d` or `~/scoop/persist/php/cli/conf.d` shouldn't make a difference.
Forgot to update the Wiki when [I changed it](https://github.com/ScoopInstaller/Main/commit/06b9ce1b848873717b1865f3e216bef036f5aa6f).

**Comment by fritzmg** [comment]
Hm, right, I don't quite understand, how the persisting feature of scoop works. I can only observe, that my `~/scoop/persist/php/cli/conf.d/custom.ini` is not taken into account.

However.. now it works (with the default `PHP_INI_SCAN_DIR` setting) all of a sudden... quite confusing 😁 . Is there any documentation on how `perist` works?

**Comment by fritzmg** [comment]
Oh I see now, it is just a symlink. Never mind.

Must have been some sort of system hick-up while uninstalling and reinstalling `php`.

**Comment by r15ch13** [comment]
Yep, it's just a simple symlink (junction).
I updated the Wiki accordingly :smile:
