### ISSUE TITLE
系统找不到指定路径

### ISSUE THREAD

**Issue by jacksparrowFF2** [lukesampson/scoop#3793]
scoop install dark
Installing 'dark' (3.11.2) [64bit]
dark-3.11.2.zip (3.5 MB) [====================================================================================] 100%
Checking hash of dark-3.11.2.zip ... ok.
Extracting dark-3.11.2.zip ... done.
Linking ~\scoop\apps\dark\current => ~\scoop\apps\dark\3.11.2
系统找不到指定的路径。
Creating shim for 'dark'.
'dark' (3.11.2) was installed successfully!

为什么总是会提示系统找不到指定路径？
Why does it always prompt the system that the specified path cannot be found?

**Comment by rasa** [comment]
Not reproducible
