### ISSUE TITLE
pwsh.exe shim quits if program is in-progress and ctrl-C is entered

### ISSUE THREAD

**Issue by JustinGrote** [lukesampson/scoop#3799]
The pwsh.exe shim causes different behavior than the actual exe.
https://imgur.com/a/3mAnVed

Related issue:
https://github.com/jwilm/alacritty/issues/2775

**Comment by Ash258** [comment]
Duplicate of #1896

Related #3634

**Comment by JustinGrote** [comment]
Agreed, closing in favor of #3634
