### ISSUE TITLE
INSTALL ERROR

### ISSUE THREAD

**Issue by hply** [lukesampson/scoop#3805]
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by linsui** [comment]
I guess you're blocked by GFW... See https://github.com/lukesampson/scoop/issues/3727

**Comment by rasa** [comment]
Classic GFW issue
