### ISSUE TITLE
Update from different bucket

### ISSUE THREAD

**Issue by SonOfDiablo** [lukesampson/scoop#3813]
Hello,

I recently ran into an issue where an app was moved from one bucket to another, which lead to scoop not updating the app.

One app I just uninstalled and re-installed as it didn't really have any configs or anything else that would be lost.

However, the other app I really don't want to uninstall and re-install (the app in question is the Windows-Terminal).
As far as I can tell the app was [moved](https://github.com/Ash258/scoop-Ash258/commit/aee6809402a651de6178ee72185013b7a4228f21) 25 days ago, removed from [Ash258's Bucket](https://github.com/Ash258/scoop-Ash258) and added to the [extras bucket](https://github.com/lukesampson/scoop-extras).

Now I'm wondering if there is a way to tell Scoop to update from the extras bucket or if I actually have to uninstall and re-install the app?

**Comment by Ash258** [comment]
Duplicate of #3810

**Comment by SonOfDiablo** [comment]
@Ash258 oh thanks!
I didn't have (or at least not see) the manifest removed message, so I didn't think of looking for that.
