### ISSUE TITLE
Install Mysql 5.7 Failed 

### ISSUE THREAD

**Issue by lihongjie0209** [lukesampson/scoop#3814]
```
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 5a8827|OK  |   1.1MiB/s|C:/Users/lihongjie/scoop/cache/mysql#5.7.28#https_dev.mysql.com_get_Downloads_MySQL-5.7_mysql-5.7.28-winx64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of mysql-5.7.28-winx64.zip ... ERROR Hash check failed!
App:         mysql
URL:         https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.28-winx64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    3c1fc0bc3368639d968fbe5bf8afa23d
Actual:      7a786218e2d9b95f9647867175766e42

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=mysql%408.0.18%3a+hash+check+failed

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/issues/504#issuecomment-545136160

You have to use `-s` parameter for installation

**Comment by lihongjie0209** [comment]
@Ash258 thx

**Comment by parasomn1a** [comment]
```
C:\Users\Parasomnia>scoop install mysql@5.6.42 -s
WARN  Given version (5.6.42) does not match manifest (8.0.22)
WARN  Attempting to generate manifest for 'mysql' (5.6.42)
Autoupdating mysql
Searching hash for mysql-5.6.42-winx64.zip in https://dev.mysql.com/downloads/mysql/
Found: md5:a78e5da2bb87b51b6df06690977be199 using Extract Mode
Writing updated mysql manifest
Installing 'mysql' (5.6.42) [64bit]
mysql-5.6.42-winx64.zip (334.9 MB) [==========================================================================] 100%
Extracting mysql-5.6.42-winx64.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\mysql\current => ~\scoop\apps\mysql\5.6.42
Creating shim for 'ibd2sdi'.
Can't shim 'bin/ibd2sdi.exe': File doesn't exist.
```

It cannot works now...

**Comment by wangwenqiangGitHub** [comment]
> ```
> C:\Users\Parasomnia>scoop install mysql@5.6.42 -s
> WARN  Given version (5.6.42) does not match manifest (8.0.22)
> WARN  Attempting to generate manifest for 'mysql' (5.6.42)
> Autoupdating mysql
> Searching hash for mysql-5.6.42-winx64.zip in https://dev.mysql.com/downloads/mysql/
> Found: md5:a78e5da2bb87b51b6df06690977be199 using Extract Mode
> Writing updated mysql manifest
> Installing 'mysql' (5.6.42) [64bit]
> mysql-5.6.42-winx64.zip (334.9 MB) [==========================================================================] 100%
> Extracting mysql-5.6.42-winx64.zip ... done.
> Running pre-install script...
> Linking ~\scoop\apps\mysql\current => ~\scoop\apps\mysql\5.6.42
> Creating shim for 'ibd2sdi'.
> Can't shim 'bin/ibd2sdi.exe': File doesn't exist.
> ```
> 
> It cannot works now...

I also meet this qustion , can you solve it ?

**Comment by rashil2000** [comment]
Try installing mysql56 from Versions bucket - https://github.com/ScoopInstaller/Versions

**Comment by wangwenqiangGitHub** [comment]
> Try installing mysql56 from Versions bucket - https://github.com/ScoopInstaller/Versions

still this problem

**Comment by rashil2000** [comment]
The mysql56 manifest does not have ib2sdi bin:
![image](https://user-images.githubusercontent.com/46838874/145940720-f036bcf9-856f-4510-ba6a-d192d532fb7f.png)

Have you correctly added the Versions bucket?

Do `scoop bucket add versions` and then `scoop install mysql56`.

**Comment by wangwenqiangGitHub** [comment]
> The mysql56 manifest does not have ib2sdi bin: ![image](https://user-images.githubusercontent.com/46838874/145940720-f036bcf9-856f-4510-ba6a-d192d532fb7f.png)
> 
> Have you correctly added the Versions bucket?
> 
> Do `scoop bucket add versions` and then `scoop install mysql56`.

Do `scoop bucket add versions` and `scoop search mysql` and install search version ， success, thanks
