### ISSUE TITLE
Shims should pass "raw" arguments, without stripping quotes

### ISSUE THREAD

**Issue by lukesampson** [lukesampson/scoop#382]
See lukesampson/scoop-extras#97 and rust-lang/cargo#1661

**Comment by lukesampson** [comment]
I haven't been able to find a way to invoke the actual `rustc.exe` (not the shim) that handles the `--cfg feature="default"` sort of argument. 

`test.ps1`:
```powershell
$rustc = (gcm rustc).path

$args = "-v --cfg feature=`"default`" test.rs"

$si = new-object diagnostics.processstartinfo $rustc, $args
$si.useshellexecute = $false
$si.createnowindow = $true
$si.redirectstandardoutput = $true
$si.redirectstandarderror = $true


write-host "args: $($si.arguments)"
$p = [diagnostics.process]::start($si)
$p.waitforexit()

$output = $p.standardoutput.readtoend()
$error = $p.standarderror.readtoend()

write-host "output: $output"
write-host "error: $error"
```

`test.rs`
```rust
fn main() { println!("hello!"); }
```

Running `./test.ps1` gives the same error seen in rust-lang/cargo#1661:

```
cfgspec:1:9: 1:16 error: unexpected token: `default`
cfgspec:1 feature=default
                  ^~~~~~~
```

Which is the same error seend when invoking `rustc test.rs --cfg feature="default"` directly.

I'm giving up on this for now—making sure `rustc` is in the path (as it is now) might be the only way.

**Comment by anurse** [comment]
Thanks for taking a look at this!

**Comment by lukesampson** [comment]
It turned out cargo was passing arguments like `--cfg feature=\"default\"` but the shim was turning this into `--cfg feature=default`. Should be fixed now!
