### ISSUE TITLE
How to switch between nodejs and nodejs-lts

### ISSUE THREAD

**Issue by ekc** [lukesampson/scoop#3820]
Hello,
    I currently have both nodejs and nodejs-lts packages installed.
    I am trying to figure out how we may switch between nodejs (13.6.0) and nodejs-lts (12.14.1).
    I tried `scoop reset nodejs-lts` (to mimic the behavior of Ruby and Python from this [Switching Ruby and Python Versions](https://github.com/lukesampson/scoop/wiki/Switching-Ruby-And-Python-Versions) wiki) but it doesn't behave the way I wish
```
C:\dev\git\repos\TypeScriptPatterns\play (play)
λ scoop list nodejs*
Installed apps matching 'nodejs*':

  nodejs 13.6.0 [C:\Users\XXXX\scoop\buckets\main\bucket\nodejs.json]
  nodejs-lts 12.14.1


C:\dev\git\repos\TypeScriptPatterns\play (play)
λ scoop reset nodejs-lts
Resetting nodejs-lts (12.14.1).
Linking ~\scoop\apps\nodejs-lts\current => ~\scoop\apps\nodejs-lts\12.14.1
Persisting bin
Persisting cache

C:\dev\git\repos\TypeScriptPatterns\play (play)
λ node -v
v13.6.0

C:\dev\git\repos\TypeScriptPatterns\play (play)
λ
```

Question
-----
How can I setup nodejs in Scoop so that I can switch between the latest nodejs and its LTS?

**Comment by niheaven** [comment]
You should restart console to switch, since bins in node and node-lts are added through env var.

Or using nvs or nvm?

**Comment by ekc** [comment]
Hello @niheaven ,
    Restarting the console solves the problem.
    Thank you so much
Ek
