### ISSUE TITLE
Installation of ios-webkit-debug-proxy fails: Exception calling "ExtractToFile" with "3" arguments... Access is denied

### ISSUE THREAD

**Issue by petermanlwl** [lukesampson/scoop#3824]
I'm using Windows 10, and I've followed the instructions to install scoop and other prerequisites by opening powershell (with admin rights):

~~~~
set-executionpolicy remotesigned -s CurrentUser
iwr -useb get.scoop.sh | iex
scoop bucket add extras
~~~~

Then I try to install ios-webkit-debug-proxy, using the following command:
`scoop install ios-webkit-debug-proxy`

However, that throws an error. Here's the output (I've replaced my username with "currentuser"):

~~~~
Installing 'ios-webkit-debug-proxy' (1.8.5) [64bit]
Loading ios-webkit-debug-proxy-1.8.5-win64-bin.zip from cache
Checking hash of ios-webkit-debug-proxy-1.8.5-win64-bin.zip ... ok.
Extracting ios-webkit-debug-proxy-1.8.5-win64-bin.zip ... Exception calling "ExtractToFile" with "3" argument(s): "Access to the path
'C:\Users\currentuser\scoop\apps\ios-webkit-debug-proxy\1.8.5\ios_webkit_debug_proxy.exe' is denied."
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1056 char:25
+ ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException
~~~~

Note that I executed all those commands with full admin rights.

ALSO NOTE - i've already created an issue with the ios-webkit-debug-proxy project, but they said that the issue is with Scoop!

**Comment by Ash258** [comment]
> Access to the path
'C:\Users\currentuser\scoop\apps\ios-webkit-debug-proxy\1.8.5\ios_webkit_debug_proxy.exe' is denied."

I suspect antivirus related problem.
You could try to install 7zip (or configure already installed external 7zip `scoop config 7ZIPEXTRACT_USE_EXTERNAL $true`). Then 7zip will be used instead of native windows compression module. But there is low chance it will work.

**Comment by petermanlwl** [comment]
That seemed to have worked!

**Comment by rasa** [comment]
Obsolete.
