### ISSUE TITLE
vim: wrong VIMRUNTIME

### ISSUE THREAD

**Issue by jeffrson** [lukesampson/scoop#3825]
Everytime I start vi or vim, I get this: `Press ENTER or type command to continue`

Now I execute the messages command: `:messages` leading to
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing C:\Users\user\scoop\apps\vim\current\_vimrc:
line   19:
E484: Can't open file C:\Users\user\scoop\apps\vim\current\vim82\defaults.vim
line   50:
E919: Directory not found in 'packpath': "pack/*/opt/matchit"
```

In _vimrc, line 19, the file $VIMRUNTIME/defaults.vim is sourced. However, this file is not located in `...current\vim82` but `...current`. When I set VIMRUNTIME environment variable to this directory I no longer need to press ENTER first when I want to edit a file.

This is with current stable vim.

**Comment by jeffrson** [comment]
Hmmm - now that I uninstalled and reinstalled the bug seems to be gone.

**Comment by Ash258** [comment]
ScoopInstaller/Main#650

**Comment by jeffrson** [comment]
Thanks! I had searched this repo for vim issues...

Will close now.
