### ISSUE TITLE
vlc - impossible to install

### ISSUE THREAD

**Issue by itsmyr4bbit** [lukesampson/scoop#3826]
Hello,

I try to install vlc but an error occur:
`URL https://download.videolan.org/pub/vlc/3.0.8/win64/vlc-3.0.8-win64.7z is not valid`

my computer: windows 10 (64bits), powershell

**Comment by E3V3A** [comment]
It's not an exe file. You need to extract to install, which I believe scoop doesn't do.

**Comment by Calinou** [comment]
@E3V3A Scoop is able to extract archives automatically using 7-zip. 7-zip will be installed using Scoop if it's not present already.

**Comment by itsmyr4bbit** [comment]
tonight, the download is ok and vlc is install correctly. Thanks

**Comment by Boscop** [comment]
I just installed VLC via scoop and then assigned the exe ("C:\Users\me\scoop\apps\vlc\current\vlc.exe") as default program for mp4 files, 
but whenever I open a mp4 file, it opens an empty cmd.exe window before opening VLC.
What am I doing wrong? :)

![image](https://user-images.githubusercontent.com/535593/83276512-fbeb6900-a1d0-11ea-9501-3373922ab6cd.png)

**Comment by linsui** [comment]
I had the same problem and it is fixed. I had installed vlc with installer before I installed it in scoop. I tried deleting some reg items related to the old installation and the problem gone.

**Comment by Boscop** [comment]
@linsui I also had installed VLC without scoop before. Do you know which registry items I have to delete?

**Comment by linsui** [comment]
Sorry, it's a year ago and I can't recall details... You can search vlc in regedit.

**Comment by Boscop** [comment]
@linsui Thanks. I had only removed the VLC folder from `Program Files`. I un-removed it and then executed uninstall.exe, now the issue is gone :)
