### ISSUE TITLE
Exclamation mark in local JSON path in install command is removed

### ISSUE THREAD

**Issue by ktos** [lukesampson/scoop#3827]
I was trying to test out my new JSON file for installing arduino-cli, and I've run the command to install from local source:

```
E:\Marcin\Temp>scoop install "E:\Marcin\!Projekty\scoop\bucket\arduino-cli.json"
```

And I've got:

```
Couldn't find manifest for 'E:\Marcin\Projekty\scoop\bucket\arduino-cli.json'.
```

It seems that `!` sign was silently ignored/removed.

**Comment by Ash258** [comment]
Cannot reproduce in any widely used version of powershell.

![image](https://user-images.githubusercontent.com/13260377/72689370-02761f80-3b11-11ea-87bb-39c954334ec9.png)

![image](https://user-images.githubusercontent.com/13260377/72689380-233e7500-3b11-11ea-80d6-c0440d74d285.png)

Problem is only when executed from cmd.

![image](https://user-images.githubusercontent.com/13260377/72689404-66004d00-3b11-11ea-8d3c-312b6cad6ffb.png)

**Comment by rasa** [comment]
Not reproducible, No author response
