### ISSUE TITLE
Searched a newer version but can't update

### ISSUE THREAD

**Issue by 023Sparrow** [lukesampson/scoop#3831]
![image](https://user-images.githubusercontent.com/30198285/73156332-6ce21d80-4118-11ea-812d-db83e63ad346.png)

My System: Windows 10.0.18363
My PowerShell: PowerShell 7.0.0-rc.2

**Comment by rasa** [comment]
See [https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241](https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241)
