### ISSUE TITLE
How to specify a bucket at install time?

### ISSUE THREAD

**Issue by fluffynuts** [lukesampson/scoop#3834]
In the case where two buckets provide the same package (by name), how can I specify which one I'd like to get the package from?

To elaborate, on Gentoo, I'd have masks and I would typically mask everything not in the main source, and unmask from specific overlays as and when I want stuff, so that if repo A and B both provided package foo, I could mask A's and unmask B's so that `emerge foo` would get `foo::A` (and I think I could also specify the source like that, though I've never tried, ie `emerge foo::A`)

I ask because the aimp package from extras is broken (fails to d/l since the link it has 302's, which it apparently doesn't follow). I'm ok with that, and want to learn how to write my own scoop sources, so I tried adding an aimp manifest to a personal repo, which showed up in a `scoop search aimp`, but I couldn't see a way (via cli help or documentation) to specify that I wanted _my_ aimp, so `scoop install aimp` tries the b0rked manifest, not mine.

For now, I've renamed mine to `aimp-portable`, but I'm sure this is a common enough scenario (or will become so) that there's probably a solution I'm just missing.

**Comment by Ash258** [comment]
`scoop install bucket/manifest`

**Comment by fluffynuts** [comment]
:+1: thanks! super-easy, just not easy to find documentation on it ):

this may not be the best place to ask, but I'll shoot ahead anyway...

after finding how incredibly easy it is to create my own bucket (thanks! great work by scoop makes this easy!), I'd like to contrib some stuff back (probably to scoop-extras, because I'm not sure the stuff I want to contrib would be considered "mainline")

1. AIMP: from scoop-extras, there is a package, but it doesn't work because of a 302 redirect, and doesn't have version info. I don't mind maintaining a package, even doing regular PR's -- just not sure of the process
2. GitHub cli client (similar to (1): not sure of the process, willing to keep updated with version info)

Alternatively, how to get added to the known buckets list to make activation easier for people who want to use these tools (and my personal dotnet utils)
If there's a doc that I've missed outlining this, please just point me at that -- I don't want to waste anyone's time (:

**Comment by Ash258** [comment]
I fixed AIMP with lukesampson/scoop-extras@d2301d879a016e91076013f4c0e566dda8f38b5e
There is no process. Like if you know how to fix issue. Fix it, test it, post PR.

If you want to maintain own bucket, like full bucket with updates and everything just use https://github.com/Ash258/Scoop-GithubActions template. You have excavator, automatic issue and PR handling there.

Known bucket list is located in this repo (https://github.com/lukesampson/scoop/tree/master/buckets.json), with mainly global wide uesr impact. Something like personal bucket with personal configuration is not candidate for known bucket list

**Comment by fluffynuts** [comment]
Thanks for getting back to me -- I have a lot to learn about how scoop works, in particular the autoupdate feature. I see that in your AIMP source -- mine was being specific about versions and I was considering writing client-side code to automate package json updates. I'm still on the fence about that because there's pros either way -- but it's great to have an example of this feature (:

I also have a lot to learn about github actions -- so that's another thing on the list.

With respect to a known bucket:
Mine doesn't have personal configuration in it, but of course there's the debate about how useful it is in general. For example, my `dotnet-utils` are quite useful for tracking down odd dotnet errors (assembly bindings, missing assemblies, find files orphaned from a legacy .csproj, batch file to assist with toggling Fusion Logging on and off) but probably have a smaller audience. On the other hand, the GitHub CLI is probably more generically useful -- I guess I should raise a PR against `scoop-extras`? Or is that tool too niche too?

**Comment by Ash258** [comment]
Github cli is `hub`, which is already in Main bucket.

**Comment by fluffynuts** [comment]
that looks like a different app -- the cli client I'm referring to is https://github.com/cli/cli/ which facilitates doing a bunch of stuff against github like viewing PR status, raising PRs, etc -- stuff you'd usually go through the browser for. Also, I'm quite sure I did `scoop search github` and the only hit was the github desktop client, yet I see mention of "github" in `hub`'s description, so it's odd that I didn't get that as an option (not that it would have helped, considering it's not the tool I was looking for)

**Comment by rasa** [comment]
Fixed in https://github.com/ScoopInstaller/Main/blob/master/bucket/gh.json

**Comment by fluffynuts** [comment]
Thanks! Appreciated.
