### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by tryyoung** [lukesampson/scoop#3835]
I used scoop config rm proxy but when I run scoop update * it still tring to connect through proxy.
Here is my config.json

{
"lastupdate": "2020-02-01T17:24:47.5701123+08:00",
"SCOOP_REPO": "https://github.com/lukesampson/scoop",
"SCOOP_BRANCH": "master",
"aria2-enabled": true
}

**Comment by tryyoung** [comment]
I used scoop config rm proxy  but when I run scoop update * it still tring to connect through proxy.  
Here is my config.json

{
    "lastupdate":  "2020-02-01T17:24:47.5701123+08:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-enabled":  true
}

**Comment by test210820** [comment]
@tryyoung I had the same problem, how did you solve it ？
