### ISSUE TITLE
Delete proxy setting but still connect through proxy

### ISSUE THREAD

**Issue by tryyoung** [lukesampson/scoop#3836]
I used scoop config rm proxy but when I run scoop update * it still tring to connect through proxy.
Here is my config.json

{
"lastupdate": "2020-02-01T17:24:47.5701123+08:00",
"SCOOP_REPO": "https://github.com/lukesampson/scoop",
"SCOOP_BRANCH": "master",
"aria2-enabled": true
}

**Comment by linsui** [comment]
Please reopen powershell and try again.

**Comment by tryyoung** [comment]
Doesn't work. Actually that seems work before but now I tried many times the result is still the same.

fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to 127.0.0.1 port 8080: Connection refused

Is there any log or cache place I can check?

**Comment by MaoKwen** [comment]
Check your .gitconfig file may help.

**Comment by Airkro** [comment]
Run `scoop config proxy ''` may help.

**Comment by street-grease-coder** [comment]
running scoop in admin shell/cmd and running `scoop config rm proxy` solved this issue for me. I guess this actually could classify as a bug / feature?

**Comment by shutaozhenzhen** [comment]
> Check your .gitconfig file may help.

This is my problem. Thanks.

**Comment by tryyoung** [comment]
Yes, the problem is in git config, I have found that earlier, I should close this. Sorry!
