### ISSUE TITLE
jmeter version is not updated

### ISSUE THREAD

**Issue by rahulmr** [lukesampson/scoop#3837]
After installation of jmeter 5.2.1 on top of jmeter 5.1.1
When I launch jmeter from windows run command, it still shows 5.1.1 instead of 5.2.1
Seems like shims are not updated properly.
Please do the needful.

**Comment by issaclin32** [comment]
You can try `scoop reset jmeter` to re-create the shims.
(https://github.com/lukesampson/scoop/wiki/Switching-Ruby-And-Python-Versions)

**Comment by rasa** [comment]
Not reproducible, No author response

**Comment by rahulmr** [comment]
@rasa JMeter is actually updated but somehow the UI still shows the version of the 1st JMeter installation done. Not a big issue but you might want to consider. Thanks!
