### ISSUE TITLE
[Question] Question about bash scripts and custom tap

### ISSUE THREAD

**Issue by AlJohri** [lukesampson/scoop#3839]
My team has multiple public and private tools that we install using a custom homebrew tap. I was hoping to replicate these on scoop to enable Windows users to also use those same tools. The tools are written in either `bash` or `python`.

I had two questions:

1) Can I use `scoop` to install custom public or private tools, similar to a custom private homebrew tap? Or does `scoop` only work with some global list of packages?

2) Can `scoop` allow me to run a tool written using `bash` with the regular `cmd.exe` or `PowerShell`? For example, my team uses this tool (https://github.com/AlJohri/kar) but the core of it is written in bash. Can I create a scoop formula/package, that will allow the user to use this command line tool in PowerShell or `cmd.exe` completely transparent to them which language it is written in?

Thanks! Apologies if there's any silly questions here- I'm trying to re-learn windows.

**Comment by Calinou** [comment]
> Can I use scoop to install custom public or private tools, similar to a custom private homebrew tap? Or does scoop only work with some global list of packages?

Sure, you can either create your own bucket or specify a path to a local or remote JSON manifest and have it installed directly:

```bash
# A bucket is a Git repository with JSON manifests in its root or in a `bucket/` subdirectory.
scoop bucket add <bucket URL>
scoop install <package>

# Or...
scoop install <URL or local file path>
```

**Comment by AlJohri** [comment]
Thank you so much for the detailed response! I will give this a shot.
