### ISSUE TITLE
checkver.ps1 - what am I doing wrong?

### ISSUE THREAD

**Issue by fluffynuts** [lukesampson/scoop#3840]
I have the following manifest:

```json
{
    "version": "0.5.2",
    "description": "The official GitHub command-line client",
    "homepage": "https://github.com/cli/cli",
    "url": "https://github.com/cli/cli/releases/download/v0.5.2/gh_0.5.2_windows_amd64.msi",
    "hash": "fd311a4b964f6dca1ae014f602e8b33816569ecb341ffb9045e63c89b3d7ffcf",
    "bin": "GitHub CLI/gh.exe",
    "checkver": "github",
    "notes": [
        "Changes in this release:",
        "Fix parsing non-GitHub remotes #266",
        "Fix pr create preview in browser flow for Windows #272",
        "Have update notifier and changelog link use the new repo name #264",
        "Minor doc updates #261"
    ]
}
```

when I run `checkver.ps1 -dir path/to/bucket -app gh-cli -u`, the output reports that there's an update:

```
gh-cli: 0.5.3 (scoop version is 0.5.2)
```

but doesn't actually update the manifest. I assume I'm doing something wrong -- any help appreciated.

**Comment by h404bi** [comment]
```
"checkver": "github",
```
this will retrieve the latest release from the release page - https://github.com/cli/cli/releases.

but you didn't provide the `autoupdate` field for auto-updating.

**Comment by fluffynuts** [comment]
thanks -- please add to the wiki / docs? I was following those and being well confused :/

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#adding-autoupdate-to-a-manifest

**Comment by rasa** [comment]
Obsolete.
