### ISSUE TITLE
Is there a way to install manually downloaded app?

### ISSUE THREAD

**Issue by mpro7** [lukesampson/scoop#3842]
Due to
> The remote server returned an error: (403) Forbidden.URL https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.7z is not valid

which I cannot omit, but still would like to keep all apps in one place = scoop <3. Is there a way to omit app download and force app installation from manually downloaded installation file?
Thanks in advance!

**Comment by Ash258** [comment]
1. Download via browser
1. Copy downloaded file to $env:SCOOP\cache
1. Rename the file accordingly: `<NameOfManifest>#<version>#<url>`
	`notepadplusplus#7.8.4#https_github.com_notepad-plus-plus_notepad-plus-plus_releases_download_v7.8.4_npp.7.8.4.bin.x64.7z`

**Comment by mpro7** [comment]
Thanks @Ash258 , I've already tried that however had a typo in URL. After copy/paste above I've got:

> The request was aborted: The connection was closed unexpectedly.
URL https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v$version/npp.$version.bin.x64.7z is not valid

**Comment by Ash258** [comment]
With properly named cached file you should not get into the URL validation phase.

After you should see something like this: 

```
PS C:\SCOOP\apps\pwsh-preview\current> scoop install notepadplusplus
Installing 'notepadplusplus' (7.8.4) [64bit]
Loading npp.7.8.4.bin.x64.7z from cache
Checking hash of npp.7.8.4.bin.x64.7z ... ok.
...
```

**Comment by mpro7** [comment]
Thanks @Ash258 , you're right. I've messed up with manifest file while trying to workaround the issue ;).
