### ISSUE TITLE
Using MinGit instead of Git for scoop buckets update

### ISSUE THREAD

**Issue by nixxo** [lukesampson/scoop#3843]
has the title suggest this is not really an issue but a question.

I uninstalled git and installed mingit (minimal git installation) and scoop seems to work just fine.

Is it possible to suggest the use a this because to update scoop buckets you really don't need the full git but it seems to me that mingit is enough.

The difference is that installing git is 200MB and mingit is 50MB so, installing 150 MB of things that are unnecessary seems not... necessary.
Or maybe I'm just wrong and there are adavanced feature in scoop that require the full git installation?

**Comment by gtusr** [comment]
Why was this closed? 

I didn't find this suggestion on the scoop homepage and I also think that it belongs there.

**Comment by r15ch13** [comment]
Also discussed in https://github.com/ScoopInstaller/Scoop/issues/4881
