### ISSUE TITLE
"Warn on shim overwrite" does not work ?

### ISSUE THREAD

**Issue by alkuzad** [lukesampson/scoop#3847]
I've had shim for xargs from unxutils and it was replaced by shim from findutils

This merge is not working anymore ? 

https://github.com/lukesampson/scoop/pull/2033

**Comment by r15ch13** [comment]
#2033 is working fine, but the [unxutils.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/unxutils.json) doesn't contain any information about the available binaries. It just gets added to the `%PATH%` and just has higher priority if installed last. You could flip the directories in your `PATH` to fix it for now.

The `unxutils` manifest could be changed to include all binaries.

**Comment by alkuzad** [comment]
@r15ch13 oh yeah, this was the case, thank you. I don't know why this feature even exists, scoop shouldn't pollute PATH like this.
