### ISSUE TITLE
Add "Rancher Kubernetes Engine (RKE)"

### ISSUE THREAD

**Issue by david-ecc** [lukesampson/scoop#3857]
Please add support for Rancher Kubernetes Engine (RKE). 

CLI can be found here: https://github.com/rancher/rke/releases

**Comment by issaclin32** [comment]
I have sent a PR to add the manifest.
This issue should be sent to [the Main bucket](https://github.com/ScoopInstaller/Main), not here.

**Comment by issaclin32** [comment]
Implemented in https://github.com/ScoopInstaller/Main/commit/cb93aa1e0f5fcbd7f30b284f668fa78172c1b040

**Comment by rasa** [comment]
Obsolete.
