### ISSUE TITLE
"scoop install ?" triggers unexpected installation

### ISSUE THREAD

**Issue by nightroman** [lukesampson/scoop#386]
Out of curiosity I typed in the PowerShell console

    scoop install -?

The result was an error

    parsing "?:?" - Quantifier {x,y} following nothing.
    At ...\scoop\apps\scoop\current\lib\getopt.ps1:49 char:8
    +                 if($shortopts -match "$letter`:?") {

Fine, this form of getting help is not supported.

The next command I tried was

    scoop install ?
    
In this case scoop started to install things that I did not expect.
It managed to install innounp then failed:

    installing innounp (0.40)
    downloading http://heanet.dl.sourceforge.net/project/innounp/innounp/innounp%200.40/innounp040.rar...done
    checking hash...ok
    extracting...done
    creating shim for innounp
    innounp (0.40) was installed successfully!
    installing ? (3.1.1)
    new-item : Illegal characters in path.
    At ...\scoop\apps\scoop\current\lib\core.ps1:212 char:14
    +     'mkdir' = { new-item -type directory @args }

This is all my fault, I was experimenting with unusual commands, I got unusual
results. I am just wondering if this is really by design, what scoop does in
these cases.

**Comment by deevus** [comment]
This cracked me up. It shouldn't work I don't think.

**Comment by deevus** [comment]
Well this is interesting. It appears that Powershell automatically filters paths with `?` in them such that the `?` matches any character. So, `get-childitem ?.json' from the bucket directory matches `R.json` for me. 

```
get-childitem '.\bucket\??.json'


    Directory: W:\scoop-stuff\scoop\bucket


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        27/06/2015   1:54 PM        605 go.json
-a---        27/06/2015   1:54 PM        412 jq.json
-a---        27/06/2015   1:54 PM        266 ln.json
```
