### ISSUE TITLE
'scoop update *' doesn't work in Git Bash

### ISSUE THREAD

**Issue by haobinliang** [lukesampson/scoop#3865]
When I run 'scoop update *' in Git Bash, it prompts error below:
```
$ scoop update *
scoop update: Option -m not recognized.
```
The command works fine in PowerShell 6.

Versions:
Windows 10.0.18363 Build 18363
Git Bash 2.25.1.windows

**Comment by h404bi** [comment]
wrap * with quotes in Git Bash. duplicate https://github.com/lukesampson/scoop/issues/2800

**Comment by rasa** [comment]
Duplicate of #2800
