### ISSUE TITLE
Scoop is not showing updates for applications with non-standard version numbers

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop#3876]
How to reproduce:
install firefox-developer (from extras bucket) version 75.0b1
run `scoop update`
confirm that the update pulls the following line for the extras `bucket`:
` * 8e6a3162 firefox-developer: Update to version 75.0b2`
run `scoop status`
Get the message: `Everything is ok!`

What should happen (and what was happening until recently):

Scoop should say that an update for `firefox-developer` is available. For the last three updates, though, scoop has been ignoring the version number increase.

**Comment by LoZeno** [comment]
More issues: `scoop cleanup` breaks the junction link in the `/current/` folders if the version number used by the app is non standard.
Example follows:
install firefox-developer@75.0b1, firefox-developer@75.0b2 and firefox-developer@75.0b3, in this order. /current/ will point to 75.0b3
Now run scoop cleanup: only 75.0b1 will be left, but /current/ will still point to a (non-existant) 75.0b3

**Comment by niheaven** [comment]
Waiting for https://github.com/lukesampson/scoop/pull/3721

**Comment by rasa** [comment]
See [https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241](https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241)
