### ISSUE TITLE
Brave Recently Updated - 80.1.5.115 - Broken Install

### ISSUE THREAD

**Issue by everonline** [lukesampson/scoop#3905]
When you update brave (scoop update brave) instead of getting this:

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       21/03/2020     22:03                80.1.5.115
-a----       21/03/2020     22:04        1993360 brave.exe
-a----       21/03/2020     22:04         713872 chrome_proxy.exe

we get this:

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       29/03/2020     21:29                locales
d-----       29/03/2020     21:29                resources
-a----       21/03/2020     20:56        1986048 brave.exe
-a----       21/03/2020     20:03         465915 brave_100_percent.pak
-a----       21/03/2020     20:03         491619 brave_200_percent.pak
-a----       21/03/2020     20:30       41826453 brave_resources.pak
-a----       21/03/2020     20:56        1137286 chrome_100_percent.pak
-a----       21/03/2020     20:56        1565346 chrome_200_percent.pak
-a----       21/03/2020     20:03         863744 chrome_elf.dll
-a----       21/03/2020     19:38       10505952 icudtl.dat
-a----       29/03/2020     21:29             60 install.json
-a----       21/03/2020     19:37          16726 LICENSE
-a----       21/03/2020     21:03        5307983 LICENSES.chromium.html
-a----       29/03/2020     17:53           1489 manifest.json
-a----       21/03/2020     20:56       12389414 resources.pak
-a----       21/03/2020     20:55         559184 v8_context_snapshot.bin
-a----       21/03/2020     19:53             10 version

Of course it doesn't find the needed manifest and assembly and breaks with a side by side error code 33....

Does scoop goes under testing before it does its releases?

Thanks
EVR

**Comment by Calinou** [comment]
> Does scoop goes under testing before it does its releases?

No, updates are generally automated and don't go through any manual testing.

It might be possible to add some kind of integration testing like I did in [scoop-games](https://github.com/Calinou/scoop-games) where every package is installed and uninstalled every week.

**Comment by everonline** [comment]
Thanks Calinou.

Testing would be good otherwise we get broken applications that we feel the need to fix asap.

**Comment by Ash258** [comment]
This will not be covered by pipeline or anything. Installation works as expected. Application do not.

Brave provide portable zip package, which is being downloaded (https://github.com/brave/brave-browser/releases/download/v1.5.115/brave-v1.5.115-win32-x64.zip). This zip contains only the files, which are in the application directory. This  is not related to scoop. Ask vendors to fix it or provide a PR to fix it with other artifact.

**Comment by everonline** [comment]
> This will not be covered by pipeline or anything. Installation works as expected. Application do not.
> 
> Brave provide portable zip package, which is being downloaded (https://github.com/brave/brave-browser/releases/download/v1.5.115/brave-v1.5.115-win32-x64.zip). This zip contains only the files, which are in the application directory. This is not related to scoop. Ask vendors to fix it or provide a PR to fix it with other artifact.
> 
> Next time open issue to proper repository. Manifests installation problems have to be reported to specific bucket.

So if the application is broken you are still going to update the pipeline and consequently the app breaking it to everyone else that use it within scoop instead of holding on due to issues...

I can provide you a PR to fix it but if your method is just a pipeline update and "hope for the best" with no testing it will be a matter of time to happen again...

PS: I apologise for the fact I raised this issue on the wrong bucket, I thought everything would go to main.

**Comment by everonline** [comment]
Thanks.

>  * e5d78a52 brave: Disable checkver                                       2 days ago
>  * 531b79c3 brave: Revert to version 1.4.96                            2 days ago
