### ISSUE TITLE
[Feature request] Add Jekyll package

### ISSUE THREAD

**Issue by Corniel** [lukesampson/scoop#3924]
I've never done a contribution myself (yet), and I'm not sure if adding [Jekyll](https://jekyllrb.com/) is matching the policy (it is not officially supported for Windows), but I found a nice PS1 that shows how it can be done: [FastJekyll.ps1](https://github.com/KeJunMao/fastjekyll)

Obviously installing paths and getting ruby should be done via Scoop.

## Code

``` PS1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Host.UI.RawUI.WindowTitle = "FastJekyll"
$exe = "rubyinstaller-devkit-2.5.1-1-x64"
$url = "https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.1-1/$exe.exe"
$file = "$PSScriptRoot\$exe.exe"
// ..

$fileis = Test-Path $file
 
If (!$fileis){
Write-Host Download $exe ...
Invoke-WebRequest -Uri $url -OutFile $file
Write-Host Download $exe Done!
}

Write-Host Install $exe ...
Write-Progress -Activity "Install Ruby and Gem"| & "./$exe.exe" /silent | Out-Null
Write-Host Install $exe Done!

cd C:\Ruby25-x64\bin
.\ruby.exe -v
.\gem -v

Write-Host Install Jekyll and Bundler ...
Write-Progress -Activity "Install Jekyll and Bundle" | .\gem install bundler jekyll

Write-Progress -Activity "enjoy!" | .\jekyll -v | Out-Null
Write-Host enjoy!
pause
```

**Comment by Calinou** [comment]
Why not just use `scoop install ruby && gem install jekyll`?

**Comment by Corniel** [comment]
@Calinou Might be okay as well. I just recently found out about Jekyll, and as it the default of GitHub pages, I thought it might deserve its own Scoop package. (even if it is just a wrapper for scoop install ruby and gemin install jekyll). But I'm a newbie here, so I thougth, why not just ask. :)

**Comment by rasa** [comment]
Out of scope
