### ISSUE TITLE
Url not recognised as zip

### ISSUE THREAD

**Issue by Shiska** [lukesampson/scoop#3932]
I am trying to download [_jabref_](https://github.com/dodorz/scoop-bucket/blob/master/JabRef.json) (url: "https://www.fosshub.com/JabRef.html?dwl=JabRef-5.0-portable_windows.zip") but [_dl_urls_](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L532) fails to extract it because [_url_filename_](https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L333) cuts off all url arguments and therefore _dl_urls_ treats it is a html file

So is this intended behaviour or a bug?

**Comment by Ash258** [comment]
Unfortunatelly you cannot use classic workaround with file rename like this, due to fosshub: (maybe could be fixed; not sure how painful it would be to fix)

```json
    "url": "https://www.fosshub.com/JabRef.html?dwl=JabRef-5.0-portable_windows.zip#/cosi.zip",
    "hash": "4f410840f7821e25a09a5d1fa6408045df27bc4bcd8684fd8ab273b4933c08b7",
    "extract_dir": "Jabref",
```

Fully working manifest:

7zip is just for speedup and to not handle reanme the HTML to `.zip` to comfort Microsoft expand utility

```json
{
    "version": "5.0",
    "description": "",
    "homepage": "http://www.jabref.org/",
    "license": "MIT",
    "url": "https://www.fosshub.com/JabRef.html?dwl=JabRef-5.0-portable_windows.zip",
    "hash": "4f410840f7821e25a09a5d1fa6408045df27bc4bcd8684fd8ab273b4933c08b7",
    "installer": {
        "script": "Expand-7ZipArchive \"$dir\\$fname\" -ExtractDir 'Jabref' -Removal"
    },
    "bin": "JabRef.exe",
    "shortcuts": [
        [
            "JabRef.exe",
            "JabRef"
        ]
    ],
    "checkver": {
        "github": "https://github.com/JabRef/jabref"
    },
    "autoupdate": {
        "url": "https://www.fosshub.com/JabRef.html?dwl=JabRef-$version-portable_windows.zip"
    }
}

```

**Comment by Shiska** [comment]
Thanks for the working manifest but the main reason for the question was if this behaviour is intended or not, in the second case the code needs a little tweaking. The reason is I can't judge how many other manifest are affected by such a change in the code.
