### ISSUE TITLE
new utility/updated utility feed?

### ISSUE THREAD

**Issue by david-bakin** [lukesampson/scoop#3938]
Is there a way to get a feed of some kind of new and/or updated utilities in main or extras or other buckets?

(Perhaps if there isn't a "native' way there's a webhook way of some kind?)

**Comment by Deide** [comment]
You mean like https://github.com/ScoopInstaller/Main/commits/master ?

**Comment by david-bakin** [comment]
Uh, yeah ......... sry! And thanks!

**Comment by Deide** [comment]
Note that if you want to see this locally/from the command line, go to the (updated) bucket's directory and do `git log`.
If you want it to be a little prettier, you can do something like `git log --pretty=format:"%C(green)  %h%Creset %s".

**Comment by david-bakin** [comment]
I'm happy with these answers.
