### ISSUE TITLE
Losing themes are reload

### ISSUE THREAD

**Issue by jrock2004** [lukesampson/scoop#394]
I have installed and setup the solorized theme but if I close out of powershell and reopen its not showing that theme and I need to re-run the config command

**Comment by lukesampson** [comment]
This is for `concfg` right? Make sure you `sudo concfg import solarized` and choose 'Yes' when it asks

```
overrides in the registry and shortcut files might interfere with your concfg settings.
would you like to find and remove them? (Y/n):
```

The registry and .lnk file that you use to start Powershell can have their own settings so doing it this way should clear them out.

**Comment by deevus** [comment]
@jrock2004 Were you able to resolve this?
