### ISSUE TITLE
Using Symbolic link instead of using shims

### ISSUE THREAD

**Issue by archit9169** [lukesampson/scoop#3943]
The idea to use shims to keep the path from polluting is amazing. However it could be simplified to use symbolic links. In that way we no longer have to keep copying a shim.exe and shim.shim to get the job done.

mklink link target does the job done.
we already use mklink to create junctions and persist data.

Right now the implementation that is used feels like kind of redundant, we need two files for every separate program that is installed. We can simplify this by just having one symlink for every program.

I have already tested this with several installed programs that requires .exe files like 7zip, pwsh, vlc and some others. And it works like expected, no unusual behavior.

**Comment by rasa** [comment]
A symbolic link doesn't work, as the exe that is the symlink's target cannot find its related .dlls, as the "exe's directory" is the directory the symlink is in, not where the target lives.
