### ISSUE TITLE
scoop: The term 'scoop' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by BaronKrause** [lukesampson/scoop#3951]
I just installed scoop and then used it to install "git" and "neofetch" on 2 Windows 10 1909 machines, it seemed to work fine but then right after a reboot, scoop and its installed apps seemed to be missing when ran from powershell, giving the following output:

scoop: The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

or:

neofetch: The term 'neofetch' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I read that sometimes there is a path issue and adding scoop/shims to the user path fixes it. I tried that and it seems like scoop works, but none of the installed apps work (including git, which it says it needs to be installed to run scoop update).

Deleting the scoop folder in your user directory and reinstalling doesn't fix it either, after install it throws the cmdlet not found error as it tries to run it.

1 of the 2 machines was a fresh install that I use just for testing.

**Comment by BaronKrause** [comment]
Error was due to Powershell 7.1
https://github.com/lukesampson/scoop/issues/3952

**Comment by Kreijstal** [comment]
Hm powershell 5.1 here, same issue

**Comment by panmaro** [comment]
Just add the path like "C:\Users\<your account>\scoop\shims" to environment variables.

**Comment by IPlayZed** [comment]
Hi! There is no such directory actually. However scoop is surely installed, because it created `C:\Users\<your account>\scoop\` and when trying to reinstall it, it returns that it is already done so. Thanks for the help!

**Comment by nlhnt** [comment]
> 
> 
> Just add the path like "`C:\Users\<your account>\scoop\shims`" to environment variables.

This only works if you add this to system path.

**Comment by IPlayZed** [comment]
> > Just add the path like "`C:\Users\<your account>\scoop\shims`" to environment variables.
> 
> This only works if you add this to system path.

This seemed to be the problem.

**Comment by Primajin** [comment]
> Just add the path like "`C:\Users\<your account>\scoop\shims`" to environment variables.

Further documentation on how to do that:

1. click Start button and enter "environment"
2. click on "Edit **environment** variables for your account"
3. check if there is a variable called Path under the upper: "User variables for {username}" - if not add it via New...
4. select it and click edit
5. click new and enter `%USERPROFILE%\scoop\shims`
6. *restart* the PowerShell, if you are using the new tabbed terminal app, you have to close the whole app, opening a new tab does not work
7. enter `scoop`

You should see something like
```
Usage: scoop <command> [<args>]

Some useful commands are:

alias       Manage scoop aliases
bucket      Manage Scoop buckets
[...]
```

**Comment by 6f5** [comment]
If the above solutions didn't work.

This can be caused due to an antivirus program.

1. Disable the antivirus and remove the scoop folder which is located on
C:/users/[your username]

2. Install it again with PowerShell in administrator mode.

COMMANDS:
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

# or shorter
iwr -useb get.scoop.sh | iex

3. Now re-enable the antivirus 

It should work now

**Comment by Matr1x-101** [comment]
I had to edit C:\Users\username\scoop\shims\scoop.ps1 and change 

`$path = join-path "$psscriptroot" "..\apps\scoop\current\bin\scoop.ps1"`

to

`$path = join-path "$psscriptroot" "..\apps\scoop\new\bin\scoop.ps1"`

**Comment by AiseKaise** [comment]
> 5\. %USERPROFILE%\scoop\shims

`Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing. `

its showing me this error

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Install#advanced-installation

**Comment by tiagosomda** [comment]
> > 5. %USERPROFILE%\scoop\shims
> 
> `Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing. `
> 
> ```
> scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
> the spelling of the name, or if a path was included, verify that the path is correct and try again.
> ```
> 
> its showing me this error

I used the expanded path instead (`C:\Users\<my user name>\scoop\shims\`) and made sure that it ends with `\` and that worked for me.
- make sure you close and open a new terminal window

-

**Comment by qixinsame** [comment]
> If the above solutions didn't work.
> 
> This can be caused due to an antivirus program.
> 
> 1. Disable the antivirus and remove the scoop folder which is located on
>    C:/users/[your username]
> 2. Install it again with PowerShell in administrator mode.
> 
> COMMANDS: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
> 
> # or shorter
> iwr -useb get.scoop.sh | iex
> 
> 3. Now re-enable the antivirus
> 
> It should work now

Big Thanks! This worked for me

**Comment by BiplobDash** [comment]
'scoop' is not recognized as an internal or external command,
operable program or batch file. I cannot install scoop .Please tell me how to install this.

**Comment by entr0pia** [comment]
goto the path `~\scoop\apps\scoop\current\bin`,  and run `.\scoop.ps1 update`, this fix the problem for me

**Comment by JoseAlz** [comment]
https://learn.microsoft.com/es-es/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

**Comment by JustLolo12** [comment]
The issue of the `scoop` command not being recognized after installation, previously reported in issue #IssueNumber, is still occurring. Despite following the recommended steps for installation and verification, the problem persists.

**Steps to Reproduce:**
1. Open PowerShell.
2. Run the following command to install Scoop:
   ```powershell
   irm get.scoop.sh | iex
   ```
3. After the installation completes successfully, attempt to install packages using:
   ```powershell
   scoop install python ffmpeg-shared git
   ```

**Expected Behavior:**
The `scoop install` command should execute without errors, allowing the installation of the specified packages.

**Actual Behavior:**
The following error is displayed:
```
scoop : The term 'scoop' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ scoop install python ffmpeg-shared git
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [],
   CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Additional Information:**
- PowerShell version: 5.1.22621.3880
- Operating System: Windows 11
- Scoop installation log output:
  ```
  PS C:\Users\%user%> irm get.scoop.sh | iex
  Initializing...
  Downloading...
  Extracting...
  Creating shim...
  Scoop was installed successfully!
  Type 'scoop help' for instructions.
  ```

**Troubleshooting Attempts:**
- Verified that the installation script completed without errors.
- Checked the system PATH to ensure it includes the path to the Scoop executable.

**Comment by qzhang2024** [comment]
> If the above solutions didn't work.
> 
> This can be caused due to an antivirus program.
> 
> 1. Disable the antivirus and remove the scoop folder which is located on
>    C:/users/[your username]
> 2. Install it again with PowerShell in administrator mode.
> 
> COMMANDS: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
> 
> # or shorter
> iwr -useb get.scoop.sh | iex
> 
> 3. Now re-enable the antivirus
> 
> It should work now

Thanks a lot! Works for me. I tried all other solutions.

**Comment by usha-git-hub** [comment]
yaar I added the same path as you wrote, but it's still 
an error..
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scoop
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
