### ISSUE TITLE
Update all installed apps

### ISSUE THREAD

**Issue by saigkill** [lukesampson/scoop#3954]
Currently it is possible with "scoop update appname" to update a specific app. Please implement a extended version, which allows to update all installed app via one command (like apt-get or zypper).

**Comment by Ash258** [comment]
> You can use '*' in place of <app> to update all apps.

```
PS S:\Scoop\apps\pwsh-preview\current> scoop help update                                                                Usage: scoop update <app> [options]

'scoop update' updates Scoop to the latest version.
'scoop update <app>' installs a new version of that app, if there is one.

You can use '*' in place of <app> to update all apps.

Options:
  -f, --force               Force update even when there isn't a newer version
  -g, --global              Update a globally installed app
  -i, --independent         Don't install dependencies automatically
  -k, --no-cache            Don't use the download cache
  -s, --skip                Skip hash validation (use with caution!)
  -q, --quiet               Hide extraneous messages
PS S:\Scoop\apps\pwsh-preview\current>
```

**Comment by saigkill** [comment]
Hi @Ash258. Thanks for that hint. Haven't seen that option.

**Comment by Ganesha2282882** [comment]
There is a method, (note: any version of WSL needs to be installed, and it is command prompt):
scoop list | wsl cut -f3 -d" " | for /f "tokens=1" %i in ('more') do scoop update %i

**Comment by shivamadhavan-ncs** [comment]
`scoop update *`
`scoop update -a`
`scoop update --all`

All of the above work as `scoop update help` suggests.

**Comment by diepvriezer** [comment]
> There is a method, (note: any version of WSL needs to be installed, and it is command prompt):
> 
> ```batchfile
> scoop list | wsl cut -f3 -d" " | for /f "tokens=1" %i in ('more') do scoop update %i
> ```

This doesn't work anymore, but the following does the same in pure powershell:

`scoop list | foreach { scoop update $_.Name }`

If you'd like to exclude global installs, the following should work, though on this PC I don't so this is untested:

`scoop list | where {$_.Info -notcontains 'global' } | foreach { scoop update $_.Name }`

**Comment by mhqb365** [comment]
> > There is a method, (note: any version of WSL needs to be installed, and it is command prompt):
> > ```batchfile
> > scoop list | wsl cut -f3 -d" " | for /f "tokens=1" %i in ('more') do scoop update %i
> > ```
> 
> This doesn't work anymore, but the following does the same in pure powershell:
> 
> `scoop list | foreach { scoop update $_.Name }`
> 
> If you'd like to exclude global installs, the following should work, though on this PC I don't so this is untested:
> 
> `scoop list | where {$_.Info -notcontains 'global' } | foreach { scoop update $_.Name }`

it work for me, tks u much

**Comment by martin-braun** [comment]
@Ash258 I don't have the `-q` flag, but `scoop` won't report that there is nothing to update.

**Comment by neoOpus** [comment]
`scoop update -a -f -g`

**Comment by sleeptightAnsiC** [comment]
Beware `*` is a reserved keyword in POSIX shells.
It expands to all file names from current working directory.
So `*` method will not work in something like `w64devkit` or `git-bash` https://github.com/ScoopInstaller/Scoop/issues/2800

**Comment by sleeptightAnsiC** [comment]
> `scoop update -a -f -g`

This does more way more than needed.
It reinstalls every package (`-f`) and requires admin privileges (`-g`).
`--all` (or `-a`) should be enough
