### ISSUE TITLE
Get list of buckets with github urls

### ISSUE THREAD

**Issue by SonOfDiablo** [lukesampson/scoop#3955]
Hello,

Is it possible to get a list of all added buckets with their repo urls?
`scoop bucket list` only gives the names of the buckets and I can't figure out where scoop saves the actual repo urls for updating, so I can't just get them from there.

I'm trying to copy my scoop installation to another machine and having to look up the buckets feels like it would be a bit of a pain, so if anyone could help me out that would be great!

**Comment by Ash258** [comment]
Scoop does not save it nowhere.

`scoop bucket list | % { pushd $env:SCOOP\buckets\$_; git remote get-url origin; popd }`

**Comment by SonOfDiablo** [comment]
Oh right because it's just a git repo... I feel stupid now.

Thank you for the handy one liner though! :)
