### ISSUE TITLE
Request: Add Ubuntu Multipass to scoop

### ISSUE THREAD

**Issue by pcgeek86** [lukesampson/scoop#3956]
Canonical has created Multipass, a cross-platform tool that enables individuals to easily deploy Ubuntu virtual machines using the native hypervisor capabilities of the operating system (ie. xhyve, Hyper-V, or KVM). I use this tool on Windows with Hyper-V to spin up development systems whenever I need to test something out.

Please consider adding this tool to Scoop. Thank you!

https://multipass.run/
https://www.youtube.com/watch?v=Ap_bAW8i2zY

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F3956
