### ISSUE TITLE
Scoop fails to install

### ISSUE THREAD

**Issue by MrUlmeyda** [lukesampson/scoop#3966]
After running `iwr -useb get.scoop.sh | iex` in PowerShell (version 5.1) the script runs successfully until the line: https://github.com/lukesampson/scoop/blob/48f121e4668ff38fbbad99185244edb19a87f0d3/bin/install.ps1#L47 trips my antivirus software and terminates the connection, causing this error and ending the script:
```
iex : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
Manually downloading `master.zip` doesn't cause any issues and scans clean; the error only occurs when I download the file through PowerShell.

**Comment by Calinou** [comment]
Out of curiosity, which antivirus program are you using?

The script is signed; I don't think we can do anything if the antivirus intercepts the PowerShell download call.

**Comment by MrUlmeyda** [comment]
ESET Internet Security, it's odd that it would happen now because I've installed Scoop before without issue.
I've registered the issue with ESET but if they don't respond and the problem isn't with the script then I'll just have to whitelist the file.

**Comment by Cj-bc** [comment]
Hi there, I'm facing the same issue on Windows 10 with ESET installed.

```powershell
> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Downloading scoop...
iex : "2" 個の引数を指定して "DownloadFile" を呼び出し中に例外が発生しました: "WebClient 要求で例外が発生しました。"
発生場所 行:1 文字:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
(sorry for some Japanese log, I think it's the same as @MrUlmeyda's)
Here I tried different way, but `iwr -useb get.scoop.sh | iex` had the same result.

I've got a message from ESET, saying "Menace 'URL/Urlik.G' was detected while PowerShell tried to access codeload.github.com. So that access denied."

![image](https://user-images.githubusercontent.com/16875061/81420100-60934500-918a-11ea-878c-381e2e4b8d53.png)

**Comment by MrUlmeyda** [comment]
This appears to be the same issue that I had when ESET blocked PowerShell's connection.

**Comment by MrUlmeyda** [comment]
The problem seems to be with PowerShell 5.1, Scoop installs without issue on the newly released PowerShell 7.0.

**Comment by Cj-bc** [comment]
I tried PowerShell 7.0, and succeeded to install !

**Comment by MrUlmeyda** [comment]
I've tested a Scoop on PowerShell 7.0 a bit more and everything seems to work fine so I've added an entry to the Misc section of the Wiki and I'll close the issue.

**Comment by jacques-hoventer** [comment]
Just confirmed on my side - Eset issue resolved when using Powershell 7.1.1

**Comment by egarifs** [comment]
hi everyone, I'm using the latest Powershell 7, and still dint work I can't install the scoop
![fails install](https://user-images.githubusercontent.com/68508709/110227888-67682100-7f2f-11eb-9ce8-e154c3b923a8.png)

**Comment by zeeshan-dxc** [comment]
Hi everyone. 
can anyone help me with that please ?

iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
Downloading scoop...
iex : Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by edy20** [comment]
Hello please help, I'm getting this error

PS C:\WINDOWS\system32> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
Initializing...
mkdir : The device is not ready.
At line:359 char:49
+ ... ion ensure($dir) { if(!(test-path $dir)) { mkdir $dir > $null }; reso ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Applications\Scoop\apps\scoop\current:String) [New-Item], IOException
    + FullyQualifiedErrorId : CreateDirectoryIOError,Microsoft.PowerShell.Commands.NewItemCommand

**Comment by OrnitierPPA** [comment]
I do not use antivirus at all, but I have exactly the same error
```
iex : Исключение при вызове "DownloadFile" с "2" аргументами: "Базовое соединение закрыто: Не удалось установить довери
тельные отношения для защищенного канала SSL/TLS."
строка:1 знак:20
+ irm get.scoop.sh | iex
+                    ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
