### ISSUE TITLE
Question: Parsing output of "scoop list" in Powershell.

### ISSUE THREAD

**Issue by Fooughhy** [lukesampson/scoop#3972]
Hi!

I was just trying to get a very small personal script going to easily check out websites in the scoop buckets.
I basically wanted to (for now) parse the output of `scoop list`, do some regex on the output to only find the application names, then do something with `scoop home` for them.
The problem I am having is that it doesn't seem possible to parse the output of the `scoop list` command.

Doing things like:
>`scoop list | Tee-Object -Variable scoopList`
>`echo $scoopList`

or:
Doing things like 
>`$scoopList = scoop list`
>`echo $scoopList`

doesn't seem to work, as the variables are empty. 
I have barely any knowledge with pwsh scripts, but I believe this is not the "default" behaviour for commands like this.
Anyone have any ideas to help me with this?

**Comment by r15ch13** [comment]
https://github.com/lukesampson/scoop/issues/1543#issuecomment-341551437

**Comment by Fooughhy** [comment]
Thank you! I tried to search for it but was unsuccessful. I have used `scoop export` before, so I should have tried that myself.
