### ISSUE TITLE
[Python] Cannot install Python from scoop.

### ISSUE THREAD

**Issue by oconnor0** [lukesampson/scoop#3973]
Running the following from the Windows Terminal gives the below error:

```
> scoop update
> scoop list
Installed apps:

  7zip 19.00
  clj-kondo 2020.05.09 [scoop-clojure]
  dmd 2.091.1
  elixir 1.10.1
  erlang 22.2
  hugo 0.64.0
  IntelliJ-IDEA 2019.3.4-193.6911.18 [jetbrains]
  leiningen 2.9.3
  rustup 1.21.1
  yarn 1.22.4
  zeal 0.6.1 [extras]
  ziglang 0.6.0
> scoop install python
Installing 'lessmsi' (1.6.91) [64bit]
Loading lessmsi-v1.6.91.zip from cache
Checking hash of lessmsi-v1.6.91.zip ... ok.
Extracting lessmsi-v1.6.91.zip ... done.
Linking ~\scoop\apps\lessmsi\current => ~\scoop\apps\lessmsi\1.6.91
Creating shim for 'lessmsi'.
Creating shortcut for Less MSIérables (lessmsi-gui.exe)
'lessmsi' (1.6.91) was installed successfully!
Installing 'dark' (3.11.2) [64bit]
Loading dark-3.11.2.zip from cache
Checking hash of dark-3.11.2.zip ... ok.
Extracting dark-3.11.2.zip ... done.
Linking ~\scoop\apps\dark\current => ~\scoop\apps\dark\3.11.2
Creating shim for 'dark'.
'dark' (3.11.2) was installed successfully!
Installing 'python' (3.8.2) [64bit]
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [>                                                                                                 ]   0%
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 51.
URL https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/python/uninstall-pep-514.reg is not valid
```

However, if I run it from Command Prompt, Python installs correctly.

**Comment by Deide** [comment]
Same happened to me. I switched to `winpython` which is portable. No problems there.

**Comment by mkvlrn** [comment]
I had the same problem while trying to install using either powershel core or plain old cmd in windows-terminal.

The error message saying something about "console's buffer size" somehow made me think it had something to do with the actual window size. I was trying to install with a small-ish window (80col, 16row), but when I maximized it, the installation completed without issues.

One of the weirdest errors (and equally weird solution) I've encountered in the wild.

**Comment by piotrek-szczygiel** [comment]
Also seems like install-pep-514.reg is empty for some reason, and the python installed is actually 3.8.2 instead of 3.8.3. Did anyone even test this?

**Comment by mkvlrn** [comment]
> Also seems like install-pep-514.reg is empty for some reason, and the python installed is actually 3.8.2 instead of 3.8.3.

Noticed that as well this morning. The update to 3.8.3 was botched, so I had to roll back. Then trying to install python@3.8.2 again gave me the same error message, but it seems to be installed now.

Don't think it was thoroughly tested.

**Comment by graphixillusion** [comment]
I confirm, same error.

**Comment by gquittet** [comment]
Same error here:
![image](https://user-images.githubusercontent.com/11082739/81948944-914c0200-9602-11ea-93cf-ba860958bb2e.png)

**Comment by gquittet** [comment]
https://github.com/ScoopInstaller/Main/issues/1088

**Comment by gquittet** [comment]
The issue is closed, but I still have it.

https://github.com/ScoopInstaller/Main/issues/1094

![image](https://user-images.githubusercontent.com/11082739/82054783-c5d1c380-96bf-11ea-9507-bdcfa00736fc.png)

**Comment by graphixillusion** [comment]
@gquittet try to uninstall then reinstall. i've installed without any problems

**Comment by gquittet** [comment]
Yes it's working now! Thank you 👍
