### ISSUE TITLE
Adding custom files to `persist` folder

### ISSUE THREAD

**Issue by d9d6ka** [lukesampson/scoop#3980]
Hello!

I've read wiki, but I've failed to find the way to add custom file to `persist` folder. I've copied my needed files to the appropriate location, but I don't know how to make scoop create symlinks to them. As i understand only links to files in manifest are created right now.

Is there any way to do this or manual intervention would be needed any time after app updates? Thanks!

**Comment by archit9169** [comment]
You cannot add custom files to persist. All files and folders which are related to persist are listed in manifest file. You will have to make custom manifest file to do so.

**Comment by d9d6ka** [comment]
Thats a pity... It would be useful to have such ability.

**Comment by Deide** [comment]
What are you trying to do exactly?

**Comment by d9d6ka** [comment]
For example, I've installed `mpv` and I'm trying to use [mpv-install](https://github.com/rossy/mpv-install) to create file associations. `mpv-install` should be put near `mpv.exe` and it assigns an icon from .ico file to the associations. I'd like to keep this ico in `persist` folder as well as the script itself to be sure, that they won't be removed during update.

Surely I can make all the links by myself.

If such feature is against the scoop way, well, I can live without it for sure :)

**Comment by Deide** [comment]
Aha, I see what you mean.

Could have some success with forking mpv-install, allowing the locations of `mpv.exe` and the `.ico` to be passed as arguments. Then you could potentially make a manifest for the forked mpv-install.

The other option would be to have it added to the manifest, however, it looks like an mpv-install script is already in the manifest `extras/mpv-git`. Maybe give that a shot?

**Comment by d9d6ka** [comment]
Yay, good news! I'll look at mpv-git for sure.
I'll also try to write manifest for mpv-install.

Thank you a lot!

**Comment by d9d6ka** [comment]
Closing the issue as I realized that it's quite rare demand.

**Comment by d9d6ka** [comment]
Forked and made a manifest. It works :) [manifest](https://github.com/d9d6ka/mpv-install-for-scoop/releases/download/v0.1/mpv-install.json)
