### ISSUE TITLE
Allow user to choose 32-bit or 64-bit when installing apps

### ISSUE THREAD

**Issue by ntcarver0** [lukesampson/scoop#3981]
Apologies if this is already possible and I am just not understanding the situation.

If possible, I would like the ability to choose whether Scoop installs a 32-bit or 64-bit version of an app. This would be useful as I have a particularly temperamental app on my system that needs a 32-bit version of ffmpeg-shared.

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/81907089-86c04700-95c7-11ea-9d45-be58aa5de4bd.png)

**Comment by ntcarver0** [comment]
@Ash258, unfortunately, I can't tell what that picture says; I am totally blind and use a screen reader which can't parse image content. Would it be possible to write out what's in that image as text? Thanks.

**Comment by Ash258** [comment]
`scoop help install | select-string '--arch'`

**Comment by Calinou** [comment]
In other words, use `scoop install --arch 32bit app_name` to force a bit to be installed 32-bit mode.

**Comment by ntcarver0** [comment]
OK, thanks. Glad to know this functionality is already available.
