### ISSUE TITLE
axiom update 404 error(1.8.0.0-alpha -> 1.8.1.0-alpha)

### ISSUE THREAD

**Issue by hago** [lukesampson/scoop#3989]
I got this error, 

> Updating 'axiom' (1.8.0.0-alpha -> 1.8.1.0-alpha)
Downloading new version
远程服务器返回错误: (404) 未找到。
所在位置 C:\Users\suncj\scoop\apps\scoop\current\lib\install.ps1:130 字符: 9
\+         throw $e
\+         ~~~~~~~~
    \+ CategoryInfo          : OperationStopped: (:) [], WebException
    \+ FullyQualifiedErrorId : 远程服务器返回错误: (404) 未找到。

It said http error 404 not found in Chinese because of my locale.

**Comment by StarsbySea** [comment]
It works fine with me, have you tried uninstalling it first and then trying to install it?
`scoop uninstall axiom`
`scoop install axiom`
![2020-05-29 203140](https://user-images.githubusercontent.com/66008060/83259888-71fcc980-a1eb-11ea-86d3-98ba34855a9a.jpg)
If it still doesn't work, maybe reinstalling scoop will fix the problem.

**Comment by rasa** [comment]
Obsolete.
