### ISSUE TITLE
Having installed graalvm, why are npm modules now being stored in its tree?

### ISSUE THREAD

**Issue by axtens** [lukesampson/scoop#3994]
```
>npm install -g @google/clasp
C:\Users\bugma\scoop\apps\graalvm11\current\languages\js\bin\clasp -> C:\Users\bugma\scoop\apps\graalvm11\current\languages\js\bin\node_modules\@google\clasp\src\index.js
npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @google/clasp@2.3.0
added 160 packages from 92 contributors in 43.767s
```
I don't recall asking for this behaviour.

**Comment by slippycheeze** [comment]
FWIW, the answer is: GraalVM has a node implementation that ships with it.  Their `node`, `npm`, et al commands are part of the standard set of binaries exposed.  So ... this is the correct behaviour as far as a GraalVM install is concerned.

Scoop would have to do extra work to make that, uh, not happen.  Which might be the right choice, but I would personally have been surprised to find out that the GraalVM version of node was not put on the path by default.

**Comment by axtens** [comment]
Ok
