### ISSUE TITLE
Neofetch uses $(scoop prefix git) internally.

### ISSUE THREAD

**Issue by Fooughhy** [lukesampson/scoop#4004]
I installed Neofetch using scoop and it seems to internally get the path for git-bash using `$(join-path $(scoop prefix git) 'bin\bash.exe')`. This seems like a very naive way of getting the path, as there is no dependency on scoop-git for it (it didn't install git when I installed neofetch).

I'm installing this on Windows 10 Pro, build 18363.
I have git, version 2.26.2.windows.1 installed from chocolatey (and the command works in cmd/pwsh.

So, to sum up. I get an error when running `neofetch` in pwsh. `scoop install neofetch` finished successfully. The error I get is the following:

> Could not find app path for 'git'.
> Join-Path: C:\Users\fough\scoop\apps\neofetch\current\neofetch.ps1:1
> Line |
> 	1  |  & $(join-path $(scoop prefix git) 'bin\bash.exe') $(join-path $psscri …
>     1   |                ~~~~~~~~~~~~~~~~~~~
>     1   | Cannot bind argument to parameter 'Path' because it is null.
> 
> InvalidOperation: C:\Users\fough\scoop\apps\neofetch\current\neofetch.ps1:1
> Line |
>    1   |  & $(join-path $(scoop prefix git) 'bin\bash.exe') $(join-path $psscri …
>     1   |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     1   | The expression after '&' in a pipeline element produced an object that was not valid. It must result
>     1   | in a command name, a script block, or a CommandInfo object.

**Comment by griveralfie** [comment]
If you didn't install git through scoop then open C:\Users\[USERNAME]\scoop\apps\neofetch\current\neofetch.ps1 in a text editor and change it to:
`& $(join-path $Env:Programfiles 'Git\bin\bash.exe') $(join-path $psscriptroot 'neofetch') @args`

**Comment by Fooughhy** [comment]
I understand that, thanks for the help! But wouldn't it be quite simple to check the location of git in the script itself? It seems like a customized script for scoop, and thus should be easily changeable right?

**Comment by Fooughhy** [comment]
May I ask why this is something which is not worth fixing? It will reappear after each update. I fixed it as I was not getting any further feedback here, but it has reappeared now as it was updated 22 days ago. I KNOW I can reapply the same fix, but it shouldn't be difficult to use the path suggested by @griveralfie as a fallback.

**Comment by thomastay** [comment]
facing the same issue

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F4004
