### ISSUE TITLE
Can't run Calibre

### ISSUE THREAD

**Issue by pasoevi** [lukesampson/scoop#4011]
After installing the latest version of Calibre (4.18.0), it is impossible to run it, the error message says: 
```
Path to Calibre Portable
(C:\Users\myname\scoop\apps\calibre\current\Calibre Portable\) too long. Must be less than 59 characters.
```

Calibre developers refuse to allow Calibre Portable to be run from paths longer than the said characters. Is there any way to get to run Calibre installed through scoop anyway?

**Comment by parasquid** [comment]
I personally have moved all my scoops to D:\ (for a different reason) which would likely solve your issue as well. It's just a workaround though, but it might help.

If you don't have a separate drive you can also try moving scoop to the root of your C: drive.

https://github.com/lukesampson/scoop/issues/52

**Comment by pasoevi** [comment]
@parasquid thanks for the response. I will try that. Apart from that, I am currently running not `calibre-portable.exe`, but `calibre.exe` instead. That seems to work. I do realize though, the Calibre developers have a reason why they restrict the app from being run from a path longer than 59 chars.

I will close the issue for now and will come back to this or other issues on the same topic.

**Comment by parasquid** [comment]
You're welcome. You might want to search around the issue tracker, there are various ways of moving your scoop installation. https://github.com/lukesampson/scoop/issues/249 for example.

**Comment by onbg91** [comment]
Thanks a lot for your help, I was thinking about re-install, but I move the folder and works! Thanks

**Comment by nuno-andre** [comment]
Just replace the `installer.args` in the manifest with

```powershell
"installer": {
    "script": [
        "start \"$dir\\calibre-portable-installer-$version.exe\" @(\"$dir\") -wait",
        "mv \"$dir\\Calibre Portable\\**\" \"$dir\"",
        "rm \"$dir\\Calibre Portable\""
    ]
},
```

and remove all the `Calibre Portable\\` strings, e.g.

`"Calibre Portable\\Calibre\\calibre-customize.exe"` &rarr; `"Calibre\\calibre-customize.exe"`

And that's all as long as installed in the default folder (since the username shouldn't be as long as the 22 characters that are now left over). Otherwise, YMMV.
