### ISSUE TITLE
Can't install openjdk13

### ISSUE THREAD

**Issue by kec2** [lukesampson/scoop#4012]
PS C:\Users\klaus> scoop -v
Current Scoop version:
96de9c14 (HEAD -> master, origin/master, origin/HEAD) hotfix(download): Progress bar on small files

'main' bucket:
3d66a0cc (HEAD -> master, origin/master, origin/HEAD) imagemagick: Update to version 7.0.10-17

PS C:\Users\klaus> scoop install openjdk13
Couldn't find manifest for 'openjdk13'.

**Comment by linsui** [comment]
scoop bucket add java

**Comment by kec2** [comment]
thanks.
