### ISSUE TITLE
Packages with same names across different buckets.

### ISSUE THREAD

**Issue by abhirupdutta0** [lukesampson/scoop#4025]
I have the same package across 2 different buckets. Is there any way to choose which bucket to install the package from, and if not could it be implemented. The reason I can't just remove the first bucket and install it that way is because I need that repo to learn how to write manifests for scoop but I also need to be able to install the applications I need from the 'extras' bucket.
![multiple packages](https://user-images.githubusercontent.com/31652124/84393202-ed617080-ac18-11ea-98c0-465e0cecec06.png)

**Comment by Ash258** [comment]
`scoop install extras/reaper`
