### ISSUE TITLE
Appveyor fails on Powershell 6 matrix

### ISSUE THREAD

**Issue by Faustvii** [lukesampson/scoop#4027]
It seems like the tests are failing for the PowerShell 6 matrix.

This same issue seems to be happening on most buckets as well.

https://ci.appveyor.com/project/lukesampson/scoop

**Comment by iguyking** [comment]
+1

**Comment by TonyZYT2000** [comment]
Similar issue happening in PowerShell 7.

**Comment by rasa** [comment]
@TonyZYT2000 Yes, For some reason, the Powershell 6 [matrix option](https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/appveyor.yml#L17) is running PowerShell 7. See https://ci.appveyor.com/project/lukesampson/scoop/build/job/7vk1ymh3bgp6thvy#L10
