### ISSUE TITLE
Possible collaboration with Zero Install

### ISSUE THREAD

**Issue by bastianeicher** [lukesampson/scoop#4028]
Hi all,

I've noticed that Scoop and [Zero Install](https://0install.net/) have many similarities and shared design goals:

- Installation without admin privileges / UAC popups
- Side-effect free installations
- Manifests listing download URLs and dependencies instead of repackaging
- Auto-select correct binaries for architecture (32bit or 64bit)
- Keeping the `PATH` clean
- Command-line and scripting friendly

The main differences are:

- Scoop describes apps in "JSON manifests", Zero Install uses "XML feeds" (for example: https://apps.0install.net/utils/jq.xml).
- Zero Install works on Linux, Windows and macOS. Feeds are shared across platforms.

I was wondering if you'd be interested in some form of collaboration between the projects. For example, it might be possible to automatically convert Zero Install feeds to Scoop manifests and vice-versa.

Regards
Bastain

**Comment by Calinou** [comment]
I think implementing a converter is something best left to a third-party tool.
