### ISSUE TITLE
install leiningen error

### ISSUE THREAD

**Issue by hero-zhanghao** [lukesampson/scoop#4032]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/technomancy/leiningen/2.9.3/bin/lein.bat
    referer=https://raw.githubusercontent.com/technomancy/leiningen/2.9.3/bin/
    dir=D:\scoop\cache
    out=leiningen#2.9.3#https_raw.githubusercontent.com_technomancy_leiningen_2.9.3_bin_lein.bat

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\leiningen.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19616 --continue

**Comment by rasa** [comment]
Obsolete.
