### ISSUE TITLE
Use where.exe inbuilt in Windows instead of reimplementing it in scoop which

### ISSUE THREAD

**Issue by pratikpc** [lukesampson/scoop#4036]
where.exe is a part of Windows, and is an equivalent of Scoop's which and Linux's which

Also Scoop's which only provides the top level result while [where.exe](https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line) provides all executables present in the path unless we are using wildcards

https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by iguyking** [comment]
@pratikpc It isn't quite equivalent.   The which in scoop actually works like linux's version.   Where is more explicit in how it needs to be called to find a file in a given location.   

Example: 

```
 iguy > where scoop
 iguy > which scoop

Definition
----------
C:\Users\iguy\scoop\shims\scoop.ps1

```

What did you want to happen here?

**Comment by pratikpc** [comment]
Did you run it in Powershell?

If you run it in Powershell, it ends up using Where-Object not where.exe

where.exe should return the same result

**Comment by iguyking** [comment]
@pratikpc Thanks for the clarification.   I did have that default alias in my testing.
