### ISSUE TITLE
Using Already-Installed 7-Zip

### ISSUE THREAD

**Issue by ntcarver0** [lukesampson/scoop#4046]
I already have 7-Zip installed on a machine that I would like to install Scoop on. Is it possible to have Scoop use the version of 7-Zip that I already have installed?

**Comment by Ash258** [comment]
`scoop config 7ZIPEXTRACT_USE_EXTERNAL $true`

**Comment by ntcarver0** [comment]
Thanks. Does it automatically detect the path to 7-Zip, or do I need to supply that as well?

**Comment by zandercodes** [comment]
You must be add 7-Zip install path to system environment path.
