### ISSUE TITLE
Can't shim 'cf.exe': File doesn't exist.

### ISSUE THREAD

**Issue by sansp00** [lukesampson/scoop#4047]
Running "scoop install cloudfoundry-cli"
Installing 'cloudfoundry-cli' (7.0.1) [64bit]
Loading dl.7z from cache.
Checking hash of dl.7z ... ok.
Extracting dl.7z ... done.
Linking E:\Users\AAAAA\scoop\apps\cloudfoundry-cli\current => E:\Users\AAAAA\scoop\apps\cloudfoundry-cli\7.0.1
Creating shim for 'cf'.
Can't shim 'cf.exe': File doesn't exist.

**Comment by rasa** [comment]
Fixed in lukesampson/scoop-extras#4353
