### ISSUE TITLE
scripts for updating manifests

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#405]
I've created a script to update the Dart manifests, see https://gist.github.com/guillermooo/f579fdb84aab4bc488da.

Would it be a good idea to consolidate such scripts in one repo? Could scoop _one day_ update manifests by running such scripts?

**Comment by deevus** [comment]
This is cool. I think this could be generalised to work with every manifest.

**Comment by deevus** [comment]
@guillermooo Any chance you can revisit and possibly generalise this to work with any package?

**Comment by guillermooo** [comment]
I would love to, but I doubt I'll find the time for it any time soon :-/

**Comment by deevus** [comment]
This has been done
