### ISSUE TITLE
Imagemagick broken download link 

### ISSUE THREAD

**Issue by MorphicResonance** [lukesampson/scoop#4055]
When  I try to download ImageMagick from Scoop I see message 
`URL https://www.imagemagick.org/download/binaries/ImageMagick-7.0.10-20-portable-Q16-x64.zip is not valid`
Imagemagick was updated with new version. You need update download link too.

**Comment by adnaanbheda** [comment]
It's updated to a valid link.
https://github.com/ScoopInstaller/Main/blob/master/bucket/imagemagick.json
as you can check here.

@lukesampson you can close this issue.

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
