### ISSUE TITLE
Add Zoxide

### ISSUE THREAD

**Issue by slaughtering** [lukesampson/scoop#4057]
Quick directory jump, z and z.lua alternative, now has windows binary releases:
https://github.com/ajeetdsouza/zoxide/releases

**Comment by slaughtering** [comment]
It's written in rust, assumedly faster than other z implementations.
Could be hooked into pwsh:
https://github.com/ajeetdsouza/zoxide/#powershell

**Comment by chawyehsu** [comment]
Please open request in https://github.com/ScoopInstaller/Main

**Comment by slaughtering** [comment]
> Please open request in https://github.com/ScoopInstaller/Main
Yep, a little mystified by the extra bucket repo url https://github.com/lukesampson/scoop-extras so opened here at the beginning.

**Comment by slaughtering** [comment]
Moved here : https://github.com/ScoopInstaller/Main/issues/1255
