### ISSUE TITLE
Can't shim 'bin\launch.bat': File doesn't exist.

### ISSUE THREAD

**Issue by kotx** [lukesampson/scoop#4069]
PS C:\Users\toast\scoop\apps\pwsh\current> scoop install i2p-zero
Installing 'i2p-zero' (1.17) [64bit]
i2p-zero-win.v1.17.zip (32.2 MB) [============================================================================] 100%
Checking hash of i2p-zero-win.v1.17.zip ... ok.
Extracting i2p-zero-win.v1.17.zip ... done.
Linking ~\scoop\apps\i2p-zero\current => ~\scoop\apps\i2p-zero\1.17
Creating shim for 'i2p-zero'.
Can't shim 'bin\launch.bat': File doesn't exist.

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
