### ISSUE TITLE
Can't shim 'I2Psvc.exe': File doesn't exist.

### ISSUE THREAD

**Issue by kotx** [lukesampson/scoop#4070]
PS C:\Users\toast\scoop\apps\pwsh\current> scoop install i2p
Installing 'i2p' (0.9.46) [64bit]
Loading i2pinstall_0.9.46_windows.exe from cache
Checking hash of i2pinstall_0.9.46_windows.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Command line arguments: -auto
Loaded 1 override(s) from C:\Users\toast\AppData\Local\Temp\I2P\install.defaults
\====================
Installation started
Framework: 5.1.3-84aaf (IzPack)
Platform: windows,version=10.0,arch=x64,symbolicName=WINDOWS_10,javaVersion=14.0.1
Installation finished
Linking ~\scoop\apps\i2p\current => ~\scoop\apps\i2p\0.9.46
Creating shim for 'I2P'.
Creating shim for 'I2Psvc'.
Can't shim 'I2Psvc.exe': File doesn't exist.

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
