### ISSUE TITLE
Installer forcefully exits script if scoop is already installed

### ISSUE THREAD

**Issue by NotWearingPants** [lukesampson/scoop#4074]
In scoop's install script, when scoop is already installed,
there is a check for whether the installer was invoked using `Invoke-Expression`,
in which case instead of exiting using `exit` it simply `return`s.

https://github.com/lukesampson/scoop/blob/6df80c1aeef72a3528ae3a5e37faa3de840318a2/bin/install.ps1#L39

This means that when the scoop installer is ran in a powershell console, and fails, it doesn't close the shell.

The problem is that powershell scripts are of the type `ExternalScript` and not `Script`,
so if you run the scoop installed in a powershell script, which is ran from a console,
the script will stop running, and there is nothing you can do about it (like ignore the error and continue).

The installer should either check for `ExternalScript` as well, or throw an exception instead.
I actually don't see where `exit` is the right choice at all.

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Install

**Comment by NotWearingPants** [comment]
Is it usable by now or does it have bugs? Because it says WIP
