### ISSUE TITLE
ffmpeg 404.3.1 3a+hash check failed

### ISSUE THREAD

**Issue by ni87** [lukesampson/scoop#4078]
C:\Users\niqian>scoop install ffmpeg
Installing 'ffmpeg' (4.3.1) [64bit]
ffmpeg-4.3.1-win64-static.zip (75.8 MB) [=====================================================================] 100%
Checking hash of ffmpeg-4.3.1-win64-static.zip ... ERROR Hash check failed!
App:         main/ffmpeg
URL:         https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    aad816cd86d29f43f25d64094a4b5c23b47d28e9f5bb93720b0368bf331737c6
Actual:      f33a409dc61df9448dcd0505c6d1614a1c161397b3e5ceaebf8f5c0287374108

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ffmpeg%404.3.1%3a+hash+check+failed

C:\Users\niqian>

**Comment by rasa** [comment]
Obsolete.
