### ISSUE TITLE
NFS Client for Windows

### ISSUE THREAD

**Issue by BlueBeN82** [lukesampson/scoop#408]
As i'm really new to all this: Is it possible to integrate the following nfs client into scoop
https://www.cohortfs.com/project/windows-nfs-clients

When trying to install manually i've got problems with the certificate.

**Comment by lukesampson** [comment]
Hi, the closest I can get is this:

```
{
	"homepage": "https://www.cohortfs.com/project/windows-nfs-clients",
	"version": "4.1",
	"architecture": {
		"64bit": {
			"url": "https://www.cohortfs.com/sites/default/files/ms-nfs41-client-setup-x64_0.exe#dl.7z",
			"hash": "md5:11a8f3169728d7983cbce294fd4b047a"
		},
		"32bit": {
			"url": "https://www.cohortfs.com/sites/default/files/ms-nfs41-client-setup-x86_0.exe#dl.7z",
			"hash": "md5:b2ee00c8935cb01d336307b03bf6f023"
		}
	}
}
```

But the file extraction fails, I'm guessing it's something that 7-zip doesn't like about the Nullsoft installer exe.

Scoop doesn't really run install/setup programs by the way. It can be done, but it's not really a good end-user experience.

**Comment by deevus** [comment]
I don't think it will work. You need to install a driver to mount the NFS volumes. That doesn't fit within Scoop's constraints.
