### ISSUE TITLE
When writing a Scoop manifest, how to deal with the installer in a zip file ?

### ISSUE THREAD

**Issue by integzz** [lukesampson/scoop#4080]
Hi, I am writing some manifests. However, I come across a case that I can not deal with, that is, some installers are zipped in .zip files. 
So how to deal with this case?

**Comment by hoilc** [comment]
Just call `Expand-7zipArchive` or `Expand-ZipArchive`  in `pre_install` or `installer` manually.

For example, https://github.com/lukesampson/scoop-extras/tree/master/bucket/vott.json

**Comment by integzz** [comment]
Hi, thank you, I tried the `Expand-7zipArchive` and `Expand-ZipArchive` in `pre_install` and `installer`. However, I have to ask another quesion, how to run the msi installer after unzipping ?
