### ISSUE TITLE
scoop is already installed but cant use

### ISSUE THREAD

**Issue by jinruozai** [lukesampson/scoop#4084]
PS C:\Users\LazyGoo> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')         Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\LazyGoo> scoop update
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
scoop update
~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException


as the above show,when install,print exist,but when use scoop update,not find.

i want to reinstall scoop,but there's no scoop directory in the path "C:\Users\LazyGoo\AppData\Local",how to remove scoop 

what should i do?

**Comment by equinox** [comment]
[> By default, Scoop installs apps just for your user account. Apps are installed under ~\scoop\apps [...]](https://github.com/lukesampson/scoop/wiki/Global-Installs)

By the sounds of it, scoop isn't properly in your PATH. I'd check and make sure there's content in `C:\Users\LazyGoo\scoop\shims`, and if so, add `C:\Users\LazyGoo\scoop\shims` to your PATH. That should get scoop working again for you.

**Comment by equinox** [comment]
@jinruozai Looks like you successfully fixed your issue, you should close this one too if you no longer need it.
