### ISSUE TITLE
[Request] base64 encode/decode command line tool

### ISSUE THREAD

**Issue by fasetto** [lukesampson/scoop#4093]
In linux systems we have *base64* tool, but in windows when I need to encode/decode something I mostly open my browser and get the job done.
I don't know if there is a tool for that, but it would be great to have something like this in **scoop**. 🙂

**Comment by devdanzin** [comment]
You can use:
- `base64.exe` from Cmder or Git Bash;
- `openssl base64` from OpenSSL;
- `python -m base64` from any of the Python distributions;
- ` powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(\"Hello world!\"))"` [ one liner from PowerShell](https://stackoverflow.com/a/37049844)
- `certutils -decode` when all else fails, [but it's quirky](https://www.base64code.com/knowledgebase/base64-example-in-windows-batch/).

But [a dedicated tool](https://www.proxoft.com/base64.aspx), which would work regardless of your other scoop installs, might be worth adding.

**Comment by fasetto** [comment]
I know other tools exists. But that was not the point.
Anyways, closing this.

**Comment by SLOSK** [comment]
"I don't know if there is a tool for that"

"I know other tools exists."
