### ISSUE TITLE
Request: Add Mosquitto to scoop

### ISSUE THREAD

**Issue by zzfnohell** [lukesampson/scoop#4094]
Eclipse Mosquitto is an open source (EPL/EDL licensed) message broker that implements the MQTT protocol versions 5.0, 3.1.1 and 3.1. Mosquitto is lightweight and is suitable for use on all devices from low power single board computers to full servers.

[https://mosquitto.org/](https://mosquitto.org/)
[https://github.com/eclipse/mosquitto](https://github.com/eclipse/mosquitto)

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F4094
