### ISSUE TITLE
Add support for exa

### ISSUE THREAD

**Issue by pBouillon** [lukesampson/scoop#4100]
[Exa](https://github.com/ogham/exa) is a pretty awesome tool which, in my opinion, has its place along with `fd`, `bat` and `ripgrep`. Adding its support would be pretty awesome !

**Comment by pBouillon** [comment]
nvm, I didn't see that the windows support is not yet available

**Comment by Calinou** [comment]
> nvm, I didn't see that the windows support is not yet available

You made me believe exa recently added Windows support until I opened this page :cry:
