### ISSUE TITLE
[Help] Nano highlighting support

### ISSUE THREAD

**Issue by pBouillon** [lukesampson/scoop#4101]
Hi,

I just installed Nano with scoop and, even if I edited the `.nanorc` file, I can't manage to follow those instruction on W10:

```
## === Syntax coloring ===
## For all details, see 'man nanorc', section SYNTAX HIGHLIGHTING.

## To include all existing syntax definitions, you can do:
# include "@PKGDATADIR@/*.nanorc"
```

It seems that `include` is not supported by PowerShell, does it have an equivalent for Windows or is there any tricks to do with scoop ?

Apologies if this has been asked before, I didn't found such issue in the history,
Thanks ! 😄

**Comment by rasa** [comment]
Not related to scoop
