### ISSUE TITLE
Git Credential helper keeps showing

### ISSUE THREAD

**Issue by JorundMartinsen** [lukesampson/scoop#4103]
I've added a bucket from my own repo.

`https://dev.azure.com/company/project/_git/repo`

Every time I run scoop update I am asked to define a credential helper.
I've tried `git config credential.helper store` with and without `--global`
This is a problem as I need to run scoop in an unmanaged script.

git installed with scoop, from main bucket.

**Comment by Ash258** [comment]
Did you use https or SSH url for the repository?

Since the azure repos are mostly private they need to authenticate. And if you use ssh then your keys will be used for git operations

```diff
-scoop bucket add <vv> https://drd-ro@dev.azure.com/<company>/<repo>
+scoop bucket add <vv> git@ssh.dev.azure.com:v3/<company>/<repo>
```

**Comment by JorundMartinsen** [comment]
I'm using https
I've tried using 
`username:password@dev.azure.com/ . . .` also

**Comment by JorundMartinsen** [comment]
Just to clarify, the bucket is added successfully in all cases, after answering the credential helper popup

**Comment by Ash258** [comment]
Use SSH link

`scoop bucket add bucket git@ssh.dev.azure.com:v3/...`

![image](https://user-images.githubusercontent.com/13260377/91812841-0be07200-ec32-11ea-92b8-8fc1978c09e0.png)

**Comment by JorundMartinsen** [comment]
After moving to ssh link, there is no credentials helper popup. However, there is still the issue of manually confirming access.
To get around this, I included some magic in my script. It clones a master ssh key, private and public with a know-hosts file, installs scoop, adds the bucket and then removes the master access. We intend to add a customer specific key later.

Thank you for the tips

**Comment by 29039** [comment]
I am using the command:

`git config --system credential.helper """"`

works with https
