### ISSUE TITLE
ffmpeg failed to install

### ISSUE THREAD

**Issue by huangnauh** [lukesampson/scoop#4105]
% scoop install ffmpeg
Installing 'ffmpeg' (4.3.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip is not valid

**Comment by yanshibin** [comment]
try `scoop install ffmpeg-shared`

**Comment by benallred** [comment]
zeranoe is apparently shutting down. The download URL might need to be updated to https://www.gyan.dev/ffmpeg/builds/.

**Comment by ZYinMD** [comment]
`scoop install ffmpeg-shared` also fails with the exact same message as `scoop install ffmpeg`.

**Comment by KScottDB** [comment]
reproduced.
```
PS C:\Users\KScott> scoop install ffmpeg
Installing 'ffmpeg' (4.3.1) [64bit]
The remote name could not be resolved: 'ffmpeg.zeranoe.com'
URL https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip is not valid
PS C:\Users\KScott> scoop install ffmpeg-shared
Installing 'ffmpeg-shared' (4.3.1) [64bit]
The remote name could not be resolved: 'ffmpeg.zeranoe.com'
URL https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.3.1-win64-shared.zip is not valid
PS C:\Users\KScott>
```

**Comment by MarkKoz** [comment]
While this is broken, is there a way with `scoop update *` to skip ffmpeg, or, more generally, to skip all broken packages? It currently completely halts all updates. Therefore, packages with names that are sorted after "ffmpeg" don't get updated.

**Comment by valentinpi** [comment]
It's already been said, but yea zeranoe recently shut down on the 18th of September: [Reddit post about that](https://www.reddit.com/r/ffmpeg/comments/ikht2k/ffmpegzeranoecom_will_close_on_sep_18_2020/)

**Comment by rasa** [comment]
Obsolete.

**Comment by Kreijstal** [comment]
is this happening again?

**Comment by xTayEx** [comment]
`scoop install ffmpeg-nightly` works
