### ISSUE TITLE
[Advice] Too long environment variables.

### ISSUE THREAD

**Issue by shyakocat** [lukesampson/scoop#4106]
Hi,
I'm fond of scoop and I got a small problem when using it.

As I install a app, scoop will add a path like `C:\Users\<username>\scoop\apps\<appname>\current\bin` to User `Path`. So after I install lots of apps(about 20~30), the environments variable is really large. And there is a limitation on win10 if the length of environments variable over 2047. So I create a `SCOOP_APPS` and move the paths to it and add `%SCOOP_APPS%` to `Path`, which will keep `Path` little and clean. But scoop will restore all paths in `Path`  when executing operation like install or update.

So can I set scoop to maintain the paths to `SCOOP_APPS` rather than `Path`, so that `Path` won't be too long.
Thanks!😊

**Comment by tan-wei** [comment]
Good advice. I met the same issue. Why it is closed?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/1813

**Comment by tan-wei** [comment]
@rashil2000 Thanks for giving me the ticket.
