### ISSUE TITLE
Download from temporary link

### ISSUE THREAD

**Issue by JorundMartinsen** [lukesampson/scoop#4109]
I need to install some software from a sharefile link.

The link shows a dropbox-like interface with a download button. The button creates a temporary link, and points the browser to that link.
I can't give the specific example as it is corporate software with license limitations.

Is there a way to install this with scoop?

**Comment by Calinou** [comment]
Scoop is designed to work with permalinks only. I'm afraid it can't be used to do what you want here.

**Comment by JorundMartinsen** [comment]
Ok, thank you
