### ISSUE TITLE
fio failed to install

### ISSUE THREAD

**Issue by huangnauh** [lukesampson/scoop#4113]
Installing 'fio' (3.20) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://bsdio.com/fio/releases/fio-3.20-x64.zip is not valid

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F4113

**Comment by maver1ck** [comment]
I added:
https://github.com/ScoopInstaller/Main/issues/1598
