### ISSUE TITLE
Optional components

### ISSUE THREAD

**Issue by RadAd** [lukesampson/scoop#4116]
What is the best way to handle optional components?
The app has a main zip which I can handle fine with the current manifest structure.
But it also has extra zip files for optional extras all to be installed in the same directory as the main zip. How is it best to handle this situation?

**Comment by Calinou** [comment]
You can install multiple files using a Scoop manifest. See [scoop-games/bucket/openttd.json](https://github.com/Calinou/scoop-games/blob/master/bucket/openttd.json) for an example.

From an organizational point of view, there are two ways to handle this:

- Offer a single manifest that installs all optional components. I would recommend this approach if the download size is small enough.
- If the download is too large to be reasonably fast for people with slow connections, offer a second manifest with a `-minimal` suffix that only installs required components.
