### ISSUE TITLE
checkver: automatically commit updated manifests with git

### ISSUE THREAD

**Issue by slippycheeze** [lukesampson/scoop#4131]
My workflow for updating personal manifests is simple:
1. run `checkver -update *` or `checkver -update ${app}`
2. run `git commit -m '${app}: update to ${version}'

It'd be kind of nice if `checkver -update` would automatically do that commit for each changed manifest.  Not a big thing, but it'd save a bit of manual work.

**Comment by Ash258** [comment]
[`.\bin\auto-pr.ps1`](https://github.com/lukesampson/scoop/blob/master/bin/auto-pr.ps1)

**Comment by rasa** [comment]
Seems like your question was answered,
