### ISSUE TITLE
nmap(7.91) cannot be installed silently

### ISSUE THREAD

**Issue by S-K-Sami** [lukesampson/scoop#4134]
When trying to install nmap v7.91 using `scoop install nmap` from an elevated command prompt, a dialog box with the following message pops up: 
![image](https://user-images.githubusercontent.com/52957909/95804204-ce3c3200-0d23-11eb-9129-1f5e5ec6475e.png)

`C:\Users\TechRay\Desktop>scoop install nmap`
`Installing 'nmap' (7.91) [64bit]`
`Loading nmap-7.91-setup.exe from cache`
`Checking hash of nmap-7.91-setup.exe ... ok.`
`Running installer... error.`
`ERROR Exit code was 2!`
`Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.`

Same issue after uninstalling and attempting reinstall.

**Comment by rasa** [comment]
Well that sucks. Chocolatey uses [Auto Hotkey scripts](https://github.com/chocolatey-community/chocolatey-coreteampackages/search?l=AutoHotkey&q=ahk) to work around these kind of issues. That’s the only workaround I can think of.

**Comment by wramthun** [comment]
Experienced the same.
