### ISSUE TITLE
New app request : dotnet-sdk-5-preview

### ISSUE THREAD

**Issue by rishavs** [lukesampson/scoop#4144]
Hi

With the new dotnet 5 preview being out, can we have a new app separate from the existing dotnet-sdk?
https://dotnet.microsoft.com/download/dotnet/5.0

This way people who want to try the new sdk, can use both.

**Comment by rasa** [comment]
This issue belongs in the versions bucket. We cannot move this issue, so it is being closed. 
Please create a new issue in the versions bucket via [https://github.com/ScoopInstaller/Versions/issues/new](https://github.com/ScoopInstaller/Versions/issues/new).

**Comment by rishavs** [comment]
Thanks, done. https://github.com/ScoopInstaller/Versions/issues/230
