### ISSUE TITLE
"scoop install openssh" fails, heimdal-7.7.0-1-x86_64.pkg.tar.xz package is not in repository

### ISSUE THREAD

**Issue by Syltty** [lukesampson/scoop#4151]
Hi,

When I run `scoop install openssh`

it tries to download `http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-1-x86_64.pkg.tar.xz` which indeed is not present in http://repo.msys2.org/msys/x86_64/

![image](https://user-images.githubusercontent.com/13706825/97198121-227cf280-17b7-11eb-8938-644aa9c31201.png)

I modified `C:\Users\<hidden>\scoop\buckets\main\bucket\openssh.json` script such as:
architecture/64bit/url[3] = "http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-2-x86_64.pkg.tar.zst" // there is no .tar.xz ?!
architecture/64bit/hash[3] = "e64fcf00ddd4158ac56dc3b282698d616bedeece3466376bc03ff61f09a0c044"

PS C:\Users\<hidden>\scoop\apps\scoop\current\bin> scoop install openssh
```
Installing 'openssh' (8.2p1-1) [64bit]
Loading bash-4.4.023-2-x86_64.pkg.tar.xz from cache
Checking hash of bash-4.4.023-2-x86_64.pkg.tar.xz ... ok.
Loading gcc-libs-9.3.0-1-x86_64.pkg.tar.xz from cache
Checking hash of gcc-libs-9.3.0-1-x86_64.pkg.tar.xz ... ok.
heimdal-7.7.0-2-x86_64.pkg.tar.zst (426.9 KB) [===============================================================] 100%
Checking hash of heimdal-7.7.0-2-x86_64.pkg.tar.zst ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/msys/x86_64/heimdal-libs-7.7.0-1-x86_64.pkg.tar.xz is not valid
```

it stills annoys me with v7.7.0-1...

OK I'll create a PR....

thank you!

**Comment by Syltty** [comment]
https://github.com/ScoopInstaller/Main/pull/1532

**Comment by trallnag** [comment]
Have you managed to fix this issue?
