### ISSUE TITLE
Add a CONTRIBUTE.md

### ISSUE THREAD

**Issue by g-berthiaume** [lukesampson/scoop#4158]
There's a [package](https://github.com/microsoft/PowerToys/releases/tag/v0.25.0) that I want to update from v0.21.0 to v0.25.0.

What is the preferred way to do this?
- Make a PR ?
- Make a github issue? 
- Others?

If it's through a PR:   
What do you use for the hash function for the `.json` file?

To my knowledge, there's no documentation about how to help this project.
A `CONTRIBUTE.md` would help clarify this.

Sorry if it's a beginner's question.
Thanks for making and supporting scoop.

**Comment by Calinou** [comment]
> Make a PR ?

Yes

> What do you use for the hash function for the .json file?

We use SHA-256 unless otherwise specified.

PS: You can infer this from the hash's length:

- MD5 is 32 characters long.
- SHA-1 is 48 characters long.
- SHA-256 is 64 characters long.
- SHA-384 is 96 characters long.
- SHA-512 is 128 characters long.

**Comment by g-berthiaume** [comment]
Thanks for your answer.
Additionally, I just found some documentation: [App-Manifests](https://github.com/lukesampson/scoop/wiki/App-Manifests)
