### ISSUE TITLE
Can't recognize 64bit arm based system

### ISSUE THREAD

**Issue by zhmushan** [lukesampson/scoop#4160]
I use scoop on Surface Pro X

```
PS C:\Users\MuShan> scoop install deno

Test-LessmsiRequirement : Cannot bind argument to parameter 'URL' because it is null.
At C:\Users\MuShan\scoop\apps\scoop\current\lib\depends.ps1:83 char:84
+ ... Lessmsi) -and (Test-LessmsiRequirement -URL (url $manifest $arch))) {
+                                                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-LessmsiRequirement], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-LessmsiRequirement

'deno' doesn't support 32bit architecture!
```

scoop should get 64-bit software, not 32-bit

**Comment by Calinou** [comment]
Scoop doesn't support ARM-based systems in general. Its 64-bit and 32-bit entries are only for x86-based CPUs.

**Comment by zhmushan** [comment]
@Calinou Don't worry about this, Microsoft helped the software to adapt, and x86 software can be run, we should change the fallback mechanism to download 64-bit software instead of 32-bit

**Comment by zhmushan** [comment]
I understand, I can only run 32-bit software, scoop processing is correct. Thanks you @Calinou
