### ISSUE TITLE
How can I run 2 scoop comand in one line?

### ISSUE THREAD

**Issue by visualwind** [lukesampson/scoop#4161]
When I try to run  
scoop cache rm * && scoop cleanup *
it cant work, can I run it in one line?

**Comment by Deide** [comment]
Instead of using `&&`, use `;`

**Comment by rasa** [comment]
In Windows:
  `cmd a && cmd b`
means run `cmd b` only if `cmd a` returned an %errorlevel% of 0 (exited without error).

If you want to run `cmd b` regardless of `cmd a`‘s %errorlevel%, use a single `&`:
  `cmd a & cmd b`
This will always run `cmd b` 

An finally,
  `cmd a || cmd b`
means run `cmd b` only if `cmd a` returned an %errorlevel% other than zero (exited with an error).

In Linux:
`&&` is the same as in Windows.
 `;` is the same as `&` in Windows. 
A single `&` at the end of a command means run the command in the background
`||` is the same as Windows.

**Comment by rasa** [comment]
Also, depending on your shell, you many need to quote an asterisk:

```batch
scoop cache rm ‘*’ & scoop cleanup ‘*’
```
