### ISSUE TITLE
[Question] Can't watch Netflix on googlechrome installed from scoop

### ISSUE THREAD

**Issue by seigt** [lukesampson/scoop#4172]
I can't watch Netflix on Google Chrome from scoop (error code: m7121-1331), but can from Google official site. Chrome portable version is also worked correctly. Please tell me why I can't watch it, and how can I watch it on googlechrome from scoop.

**Comment by Bibz87** [comment]
@seigt I have the same issue. Were you able to fix it?

**Comment by Bibz87** [comment]
Looks like the issue was also filed in the Extras bucket: https://github.com/ScoopInstaller/Extras/issues/5742

**Comment by pete-debiase** [comment]
Howdy there, not OP but spent a while looking into this and found several workarounds/solutions. Rabbit hole begins over on https://github.com/ScoopInstaller/Versions/issues/738#issuecomment-1298806335.
