### ISSUE TITLE
Invalid JSON primitive during scoop search

### ISSUE THREAD

**Issue by Tyrubias** [lukesampson/scoop#4186]
I found today whenever I tried to search for a package on Scoop the following error would be produced.

```
convertfrom-json : Invalid JSON primitive: .
At C:\Users\VictorSong\scoop\apps\scoop\current\lib\manifest.ps1:10 char:45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

Is there any way I can diagnose this issue?

**Comment by ompadu** [comment]
Same here

**Comment by eecarus** [comment]
Hi Luke.  First poster here, so bear with me.   I had the same issue and found that the file 'C:\Users\<username>\scoop\buckets\extras\bucket\deepgit.json'  had an extra comma at the end of line 26.  Opening the file in VSCode showed it as improperly coded JSON.   Not sure if that's the same issue people are having.  I only started noticing it yesterday.

See https://github.com/lukesampson/scoop-extras/blob/master/bucket/deepgit.json

BTW, thanks for all the work on Scoop!

**Comment by pcrama** [comment]
This is the same as #5201/#5202.  If you retry, it should be OK now.

**Comment by eecarus** [comment]
@pcrama ,  Thank you.   Confirmed the fix made by the deepgit team is working.  The error is no longer showing when doing scoop operations.
