### ISSUE TITLE
Nmap scan showing all port open

### ISSUE THREAD

**Issue by devansh3008** [lukesampson/scoop#4188]
When trying to scan any domain,nmap shows all ports open always

![Screenshot from 2020-11-30 15-52-51](https://user-images.githubusercontent.com/30910269/
![Screenshot from 2020-11-30 15-53-04](https://user-images.githubusercontent.com/30910269/100598056-3969b400-3324-11eb-84c3-49de65513378.png)
100598022-2fe04c00-3324-11eb-8f53-04abeec31d06.png)
![Screenshot from 2020-11-30 15-53-00](https://user-images.githubusercontent.com/30910269/100598044-37075a00-3324-11eb-92f7-3631bdca51b2.png)

**Comment by Calinou** [comment]
Wrong repository? Scoop is a Windows-only utility.

**Comment by rasa** [comment]
This does not appear to be a scoop issue.
