### ISSUE TITLE
Cleanliness (and Security)

### ISSUE THREAD

**Issue by VladPutinEu** [lukesampson/scoop#4209]
I am looking for a Windows package manager that is clean (when I uninstall an app it is completely or almost completely removed) and one that is secure (apps are contained and have minimal permissions). Should I choose Chocolatey or Scoop?

Please try to be unbiased, I want your honest answer.

**Comment by VladPutinEu** [comment]
Honestly, I really want a clean package manager for my PC. Cleanliness is one reason I'm looking for a package manager. It's very important to me.

**Comment by Calinou** [comment]
> I am looking for a Windows package manager that is clean (when I uninstall an app it is completely or almost completely removed) and one that is secure (apps are contained and have minimal permissions). Should I choose Chocolatey or Scoop?

Neither Chocolatey nor Scoop perform automatic app sandboxing. In fact, not even Microsoft's WinGet does :slightly_smiling_face:

**Comment by VladPutinEu** [comment]
But the problem with Scoop is that if I'm installing some add-ons or something. The add-on won't be able to locate the application, as it won't be in the usual location. So it can definitely cause some issues.

How about cleanliness, is there really a difference?

**Comment by Calinou** [comment]
> How about cleanliness, is there really a difference?

Scoop doesn't attempt to clean up registry entries when using `scoop uninstall`, so it's not ideal in that regard. That said, I don't think it's that much of an issue for most applications.

**Comment by VladPutinEu** [comment]
Does Scoop attempt to remove all the application's folders?

How about Chocolatey, does it attempt to remove all the application's folders and registry entries?

**Comment by Calinou** [comment]
> Does Scoop attempt to remove all the application's folders?

No, it only removes the application folder, not the user data folder.

**Comment by CrendKing** [comment]
Most Scoop supported apps have portable installation option. All Scoop does is extract the apps in the portable way and let the apps do the rest. If the app does not provide portability, you most likely won't find it in Scoop other than explicit non-portable buckets. The benefit of such restriction is that all file system changes would be cleaned once you remove the app directory. Registry of course is not touched, but if the app supports portability, it should not touch registry to begin with.

One way for Scoop to expand the repository to more apps that always write to user directory (`${USERPROFILE}\<app>`) is symbolic link or junction the profile directory to persist. I don't know why Scoop doesn't do this already, but worth mentioning.

**Comment by ltGuillaume** [comment]
> One way for Scoop to expand the repository to more apps that always write to user directory (${USERPROFILE}\<app>) is symbolic link or junction the profile directory to persist. I don't know why Scoop doesn't do this already, but worth mentioning.

@CrendKing I suppose the main reason for this is that in order to create symbolic links, you need administrator rights... I still think it's a good idea to at least support it, though.
