### ISSUE TITLE
install potplayer failed and get a error

### ISSUE THREAD

**Issue by zengjiapei3000** [lukesampson/scoop#4223]
![scoop](https://user-images.githubusercontent.com/41148275/104198580-5d5f0000-5461-11eb-9293-7165429f280d.PNG)

I find the scoop config has a **shovel** but wiki and doc aren't have anything about shovel. And searching `scoop config shovel` at bing was getted all spam about the real shovel...

**Comment by zengjiapei3000** [comment]
@Ash258 maybe `scoop config shovel` is mean your scoop impliment named _shovel_.

**Comment by HUMORCE** [comment]
Have you switched the scoop_repo to [shovel](https://github.com/Ash258/Scoop-Core)?

check it:
`scoop config scoop_repo`

**Comment by zengjiapei3000** [comment]
Thanks for your reply! This question is solved now. I tried to download again when I changed the `scoop_repo` config brefore 1 minute, and it's successfully :+1:~ 
![scoop0126](https://user-images.githubusercontent.com/41148275/105837180-44ca1a80-6009-11eb-82fa-9a4e60abe1a7.PNG)
![scoop0126_02](https://user-images.githubusercontent.com/41148275/105837281-7642e600-6009-11eb-9f3f-f3bd53f12519.PNG)
