### ISSUE TITLE
Failed to install: Exception Calling "DownloadFile" with "2" arguments

### ISSUE THREAD

**Issue by Braunson** [lukesampson/scoop#4245]
PowerShell: 5.1.18362.1171
Windows: 10 Home

Following the steps on https://scoop.sh/

`Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')`

Gives me this error:

```
PS C:\WINDOWS\system32> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')      Initializing...
Downloading scoop...
Invoke-Expression : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient
request."
At line:1 char:1
+ Invoke-Expression (New-Object System.Net.WebClient).DownloadString('h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

```

I've confirmed that Scoop is not available in AppData anywhere. I tried running the command without and with Administrative privileges in Powershell. 

Any ideas?

**Comment by HUMORCE** [comment]
are you logged in as administrator?

**Comment by Braunson** [comment]
@HUMORCE Yes and even ran as administrator.

**Comment by HUMORCE** [comment]
scoop is recommended to be used in non-administrative privileges.

Network problems encountered when downloading scoop core:

https://github.com/lukesampson/scoop/blob/227de6cfb8433a86ac0f0a279e691327ae04554c/bin/install.ps1#L30-L33

make sure you can visit github services normally without VPN/PROXY, and check DNS servers you seted.

**Comment by Braunson** [comment]
I even tried without administrative privileges. Can also confirm I have no VPN/Proxy running and DNS servers are correctly working.

**Comment by HUMORCE** [comment]
I was wrong.

`Invoke-Expression : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient
request."`

https://github.com/lukesampson/scoop/blob/227de6cfb8433a86ac0f0a279e691327ae04554c/bin/install.ps1#L35-L47

insert `write-host $dir` to line 42, then run and check the permission of the path.

**Comment by mdymel** [comment]
I had the same problem. It turned out it was caused by Eset Antivirus. 
As suggested here: https://github.com/lukesampson/scoop/issues/3966
I have upgraded Powershell to v7 and it worked fine from there.

**Comment by Braunson** [comment]
@HUMORCE @mdymel Seems I did have PowerShell 7.x installed but it was serving 5.1. Tried running on 7.x and this is what happens

```
PS C:\Users\Braunson\Documents\GitHub\prepagent> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\Braunson\Documents\GitHub\prepagent> scoop update
scoop: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I've looked for a scoop folder in C:\ProgramData but it's not there. How is it recognizing that it's "installed" when it isnt?
