### ISSUE TITLE
Scoop manifest.ps1 after removing a bucket

### ISSUE THREAD

**Issue by umbellipher** [lukesampson/scoop#4247]
I removed the dodorz bucket because it seems to be no longer available on Github.

Scoop updates fine, but then I get this error, repeated 5 times in all:

----

Get-ChildItem: C:\Users\xxxxx\scoop\apps\scoop\current\lib\manifest.ps1:103
Line |
 103 |      $file = Get-ChildItem -LiteralPath $buc -Filter "$name.*"
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\xxxxx\scoop\buckets\dodorz' because it does not exist.

----

How might I resolve this, please?

**Comment by HUMORCE** [comment]
which way did you remove the bucket,
delete scoop\bucket\dodorz folder or scoop bucket rm dodorz?

**Comment by umbellipher** [comment]
The latter, rm, method.

**Comment by HUMORCE** [comment]
dodorz still in `scoop bucket list` ?

**Comment by umbellipher** [comment]
dodorz/scoop-bucket gives a 404, and has been closed, it seems. dodorz has a new bucket at https://github.com/dodorz/scoop. I've added that bucket, and my issue seems to have resolved. So, closing, with thanks.
