### ISSUE TITLE
Add openapi-generator

### ISSUE THREAD

**Issue by MartinDelille** [lukesampson/scoop#4257]
This would be nice to have a recipe for this awesome tool: https://github.com/OpenAPITools/openapi-generator

**Comment by HUMORCE** [comment]
app requests should be posted to the bucket repo.

https://github.com/lukesampson/scoop/wiki/Buckets

**Comment by MartinDelille** [comment]
Done: https://github.com/ScoopInstaller/Main/issues/1822
