### ISSUE TITLE
shell extensions / install for all users?

### ISSUE THREAD

**Issue by mralusw** [lukesampson/scoop#4261]
I noticed that Scoop installs 7-zip anyway when installing nano, so I tried to replace the default 7-zip installation with Scoop. I uninstalled 7-zip from the Windows 10 Apps&Features, changed $Env:Scoop to C:\Programs\Scoop (which should be accesible systemwide), and reinstalled scoop & nano

I got a 7-zip item in the Start menu, but of course shell extensions (right-click context menu) are not available. I suppose they can be re-created somehow... Is this a good way to go? Can I use scoop as a global package manager for all users?

**Comment by mralusw** [comment]
I should note that after `scoop install nano`, 7-zip is installed under C:\Programs\Scoop, and also appears in my user Start Menu, but does not appear in other users' Start Menu. Other users can run the executables, but don't have shortcuts installed in their Start Menu

**Comment by mralusw** [comment]
... and I found a workaround by moving my Scoop directory from `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs` to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Scoop Apps` and symlinking it back. Seems to work fine, all users get access to Scoop Start Menu entries.

**Comment by HUMORCE** [comment]
if you want use external 7-zip:
```
scoop config 7ZIPEXTRACT_USE_EXTERNAL $true
```

help for global install:
```
Usage: scoop install <apps> [options]

Install apps

e.g. The usual way to install an app (uses your local 'buckets'):
  scoop install git
  scoop install extras/googlechrome

To install an app from a manifest at a URL:
  scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/runat.json

To install an app from a manifest on your computer
  scoop install \path\to\app.json

Options:
  -h, --help                Show help for this command.
  -g, --global              Install the app globally.
  -i, --independent         Don't install dependencies automatically.
  -k, --no-cache            Don't use the download cache.
  -s, --skip                Skip hash validation (use with caution!).
  -a, --arch <32bit|64bit>  Use the specified architecture, if the app supports it.
```

7zip shell context menu:
![screenshot_20210222191126](https://user-images.githubusercontent.com/4353480/108757517-d6ae4000-7541-11eb-938f-5824b5efc7d1.png)

**Comment by mralusw** [comment]
Thanks. I guess integration has to be configured separately, assuming the app has a menu to create filetype associations / shell extensions (like 7zip and IrfanView do)

So, `install -g` would add the app to the global `\Program Data\...\Start Menu\Programs\ScoopApps`  (as opposed to somewhere under the user's `%APPDATA%`)?

**Comment by HUMORCE** [comment]
https://github.com/lukesampson/scoop/wiki/Global-Installs

**Comment by mralusw** [comment]
That pretty much explains everything
