### ISSUE TITLE
Any body has ideas about this error ?

### ISSUE THREAD

**Issue by NBSOD** [lukesampson/scoop#4269]
When i use "scoop update" i got this error....and "scoop checkup" got "No problems identified!" . So what's wrong with my scoop ? 

Windows 10 Perfessional 20H2 
#############################
λ ~\..\..\..\current git: master ≣ scoop update
Updating Scoop...
Updating 'extras' bucket...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: cannot lock ref 'refs/remotes/origin/master': unable to resolve reference 'refs/remotes/origin/master': reference broken
fatal: ambiguous argument 'HEAD..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Updating 'main' bucket...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: bad signature 0x00000000
fatal: index file corrupt
fatal: ambiguous argument 'HEAD..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Updating 'nerd-fonts' bucket...
Updating 'nirsoft' bucket...
Updating 'nonportable' bucket...
Scoop was updated successfully!
#############################

**Comment by NBSOD** [comment]
OK...i had resolved this error. Delete all buckets (include 'main') and then add them,Then 'scoop update' turn right.

**Comment by t3dium** [comment]
i also got the same error today, deleting all buckets and re-adding fixed it however
