### ISSUE TITLE
Scoop won't install

### ISSUE THREAD

**Issue by ReadyP1** [lukesampson/scoop#428]
When I try running the command given to install ```scoop```, PowerShell tosses me the following (sorry for bad image quality):

![error](http://techieboy45.tk/error.jpg)

What's up here? I already ran the ```set-executionpolicy``` (which, by the way, needs ```cu``` to be changed to ```currentuser``` or else it gives a fatal error) command.

**Comment by deevus** [comment]
@ReadyP1 It looks like you're using Powershell 2. If you can, upgrade to Powershell 3.

If not, there is a version of Scoop for Powershell 2, but it's not what you would call stable.

**Comment by ReadyP1** [comment]
@deevus I tried to download WMF 3, but for some reason, it doesn't download. Trying again doesn't help. Is there some sort of direct download link I can get? I'm running Win7 SP1.

**Comment by ReadyP1** [comment]
@deevus Never mind that download thing. Got it working.

**Comment by deevus** [comment]
No worries.
