### ISSUE TITLE
Scoop apps doesn't appear in windows search

### ISSUE THREAD

**Issue by halikular** [lukesampson/scoop#4281]
If I type in a search query for a any scoop installed app (except for mpv which seems to have its own solution for creating shortcuts and file associations) windows search will either return the shortcut of the same app that's been installed via an .exe installer and later uninstalled leaving behind an icon which doesn't do anything when you left/right click on it. The suggested solution was to remove the remaining shortcuts of the uninstalled apps from the following directories:

- `%APPDATA%\Microsoft\Windows\Start Menu\Programs`
- `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`

however I didn't have any remaining shortcuts in any of the directories above. Further research lead me to a thread from 2018 that due to Cortana having a database of windows search on its own you should delete the contents of `%LOCALAPPDATA%\Packages\Microsoft.Cortana_*` it seems like this directory is gone or is just not present on Windows installs outside the US which doesn't ship with Cortana. I have also tried reindexing basic search and confirmed that the shortcuts from scoop are present in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Scoop Apps\` and working properly. I have also tried `scoop reset *` to restore the shortcuts but it didn't make any difference. Apps installed with scoop that has never been installed before doesn't even appear in search at all. After searching for a solution on the internet for hours I gave up and couldn't find anything relevant in helping me fix my of my issues. Scoop apps launched from the shell via path works fine so there's no problem with CLI apps. I'm using Windows 20H2 build 19042.844. My installed apps are:

- 7zip 19.00 [main]
- adoptopenjdk-hotspot 15.0.2-7 [java]
- blender 2.92.0 [extras]
- dark 3.11.2 [main]
- ffmpeg 4.3.2-160 [main]
- gimp 2.10.20-1 [extras]
- git 2.30.1.windows.1 [main]
- godot 3.2.3 [extras]
- inkscape 1.0.1 [extras]
- innounp 0.50 [main]
- krita 4.4.2 [extras]
- mpv-git 20210228 [extras]
- qbittorrent 4.3.3 [extras]
- sudo 0.2020.01.26 [main]
- youtube-dl 2021.03.03 [main]

This seems to be an issue specific to my windows installation on my desktop computer as I don't have the same issue with my laptop install. It feels like one of those annoying Windows problems that just can't be solved without a  full reinstallation sigh.

**Comment by raycheung** [comment]
I ended up fixing this issue with: https://superuser.com/a/960489/1321177
