### ISSUE TITLE
Scoop won't add itself (or apps) to PATH when running on PowerShell 7 from Microsoft Store

### ISSUE THREAD

**Issue by brunovieira97** [lukesampson/scoop#4282]
When running on PowerShell 7 installed via Microsoft Store, Scoop won't add itself to PATH reliably. The same will happen to any app that requires PATH presence where Shims won't do the job alone.

Actually, Scoop will do the same it does when running on other PowerShell versions, calling the correct functions for changing the value. The PATH will, however, only contain the new apps (or Scoop's) paths for the current session.

Examples of apps that won't work correctly:
 - gpg
 - nodejs (`npm` and `npx`)

## Important!

After a nice monologue on ScoopInstaller/Main#1890, I realized this is PowerShell's fault. The issue will only affect MS Store installations, so removing it and installing from good old MSI won't be much of a hassle.

I find it important to register this issue here, even though it's not Scoop's fault. This way, other user's might find the answer to this problem while PowerShell team hasn't fixed it.

I've opened PowerShell/PowerShell#14957 to track this with the PowerShell team ;)

**Comment by tysonclugg** [comment]
1. Is `scoop checkup` able to detect and resolve this issue?
2. Should `scoop (update|install|uninstall|...)` refuse to run if the PATH can't be updated correctly?

**Comment by brunovieira97** [comment]
The thing is probably Scoop can't identify this issue. It's caused by PowerShell 7's sandboxing when installed through the Windows Store, apparently.

For Scoop, Windows Terminal and PowerShell itself, everything seems fine: the Path can be changed and the value can be fetched. The problem lies on launching a new instance later, and checking the value wasn't properly changed due to the use of Virtualized Resources.

**Comment by tysonclugg** [comment]
I think Scoop can probably identify the issue by doing the following:

1. During the final phase of installation, run scoop via PowerShell (eg: `scoop finalise_scoop_install`) to add Scoop PATH entries (eg: `C:\ProgramData\scoop\shims`).

2. If `scoop (update|install|uninstall|...)` doesn't find the PATH entries that should have been added via `scoop finalise_scoop_install`, then complain loudly/stop.

**Comment by tysonclugg** [comment]
Actually, right after [step 1](https://github.com/lukesampson/scoop/issues/4282#issuecomment-826488275), perhaps the installer could check if the PATH has been updated correctly?

**Comment by brunovieira97** [comment]
Well, my whole point before (even though I didn't quite made it clear) is that Scoop shouldn't bother with this. It's basically a bug, that should be fixed by PowerShell team. Scoop is not the only affected here, it's way deeper than that.

**Comment by rashil2000** [comment]
I had been facing the same issue with PS 7 installed from the Store. Glad to see it has already been logged. The PowerShell folks said they fixed it in a [preview release](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6). Has anybody tested it? I'm afraid to switch to a preview build.

**Comment by brunovieira97** [comment]
Totally forgot to close this issue.

As PowerShell/PowerShell#14957 is closed, the fix is currently on preview and should roll out on 7.2.0.
