### ISSUE TITLE
How to recreate all current "symlink" folders

### ISSUE THREAD

**Issue by cmoisei** [lukesampson/scoop#4286]
I moved the scoop folder from a drive to another via  zip and of course I lost all my current folders - is there a way to create them back ?

**Comment by HUMORCE** [comment]
try:
`scoop reset *`

**Comment by cmoisei** [comment]
that seems to do the trick however, the reset could be updated to detect if
"current" is a folder - if it is should remove it. I experiences this when
moved the apps folder from one drive to another.

**Comment by HUMORCE** [comment]
when you must to be 🤣🤣🤣
but if you have to do it, you may not need my mind anymore

**Comment by HUMORCE** [comment]
In fact, need to reinstall first. 
env variables is important for the scoop.

ifthere are no other problems then you should be close this thread.

**Comment by cmoisei** [comment]
Thanks. Closings it.
