### ISSUE TITLE
Add Scoop back to User variables

### ISSUE THREAD

**Issue by Amarounek** [lukesampson/scoop#4293]
By my stupidity, I've deleted my User environment variables. The scoop commands are missing now. 
Is there some easy way how to put it back to my path? I have python 37 and python39 installation there. I don't want it to reinstall all my distribution and packages.

**Comment by HUMORCE** [comment]
reinstall the scoop, then exec `scoop reset *`.

**Comment by Amarounek** [comment]
Okey

I've solved it
Putting this to user variables:
`C:\Users\your_user_name\scoop\shims`
