### ISSUE TITLE
how can i backup and recovery?

### ISSUE THREAD

**Issue by lin0kin** [lukesampson/scoop#4311]
i buy a new laptop , how can i bcakup all software installed by scoop and all config?
and how can i recover all to my new laptop?
really thx for u help

**Comment by HUMORCE** [comment]
install scoop, and copy these dir from old device:
```
scoop\apps\*
scoop\persist\*
```
then exec `scoop reset *`

**add or copy buckets used.**
**config files are not necessarily stored by scoop.**

**Comment by lin0kin** [comment]
@HUMORCE thx ,it works
