### ISSUE TITLE
Invalid hash for python package

### ISSUE THREAD

**Issue by HLevering** [lukesampson/scoop#4314]
Hello,

I want to install python package with:
```scoop install python```

However, I get the following error. It seems like the hash is invalid:

Checking hash of python-3.9.4-amd64.exe ... ERROR Hash check failed!
81App: main/python
82URL: https://www.python.org/ftp/python/3.9.4/python-3.9.4-amd64.exe#/setup.exe
83First bytes: 4D 5A 90 00 03 00 00 00
84Expected: 1a1412dd7c18aa0c7c7e55b00a244844
85Actual: ebc65aaa142b1d6de450ce241c50e61c
86Please try again or create a new issue by using the following link and paste your console output:

This command worked until yesterday.
Can anyone solve this?
Many thanks in advance.

**Comment by uploadhub** [comment]
I just updated the python package and the same problem as yours occurred

**Comment by floooh** [comment]
Exact same problem here, same hash values too.

**Comment by mjvankampen** [comment]
From python.org the hash should indeed be ebc65aaa142b1d6de450ce241c50e61c. Ref. https://www.python.org/downloads/release/python-394/

**Comment by mjvankampen** [comment]
Ref. https://github.com/ScoopInstaller/Main/issues/2054

**Comment by rasa** [comment]
Fixed in https://github.com/ScoopInstaller/Main/pull/2031
