### ISSUE TITLE
Scoop Update: BUG (fork bomb) 

### ISSUE THREAD

**Issue by stephenpatten** [lukesampson/scoop#4323]
Hello,

Scoop was working fine yesterday and today I issued the command scoop reset * to get all the apps back after windows insider update, then tried to issued the command scoop update and am receiving this error.

PS C:\Users\spatten\repos> scoop update
Updating Scoop...
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
Update failed.
PS C:\Users\spatten\repos>

PS C:\Users\spatten\repos> scoop which scoop
~\scoop\apps\scoop\current\bin\scoop.ps1

PS C:\Users\spatten\repos> scoop status
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
BUG (fork bomb): C:\Users\spatten\scoop\apps\git\2.31.1.windows.1\bin\git.exe
Scoop is up to date.
Updates are available for:
    gradle: 6.8.3 -> 7.0
Everything is ok!

PS C:\Users\spatten\repos> scoop bucket list
Ash258
cologler
extras
java
jetbrains
main
nerd-fonts
nirsoft
nonportable

PS C:\Users\spatten\repos> scoop list
Installed apps:

  7zip 19.00 [main]
  adopt11-hotspot 11.0.10-9 [java]
  adopt16-hotspot 16-36 [java]
  adopt8-hotspot 8u282-b08 [java]
  curl 7.76.0 [main]
  dark 3.11.2 [main]
  git 2.31.1.windows.1 [main]
  gradle 6.8.3 [main]
  innounp 0.50 [main]
  JetBrains-Toolbox 1.20.7940 [extras]
  keystore-explorer 5.4.4 [extras]
  lessmsi 1.8.1 [main]
  logexpert 1.8.7 [extras]
  maven 3.8.1 [main]
  meld 3.20.3 [extras]
  mitmproxy 6.0.2 [extras]
  mkcert 1.4.3 [extras]
  nodejs 15.14.0 [main]
  openssl 1.1.1k [main]
  postman 8.2.1 [extras]
  powertoys 0.21.1 [extras]
  putty 0.74 [extras]
  pwsh 7.1.3 [main]
  px 0.4.0 [main]
  python 3.9.4 [main]
  ripgrep 12.1.1 [main]
  scoop-backup 1.2.1 [cologler]
  smartgit 20.2.4 [extras]
  soapui 5.6.0 [extras]
  sudo 0.2020.01.26 [main]
  sysinternals 2021.March.23 [extras]
  telnet msys-inetutils-1.7-1 [main]
  vscode 1.55.1 [extras]
  windows-terminal 1.6.10571.0 [extras]

This laptop is a work issued laptop and I have local admin permissions, but god knows what I've done or the powers to be have pushed down from the GPO.

What more is needed to troubleshoot this issue that I can provide, I'm very attached to scoop :) and this is killing me.

Thank you in advance,
Stephen

**Comment by HUMORCE** [comment]
i had the same problem a long time ago.

try to delete all bucket dir ( $env:SCOOP\buckets\*) and manually clone them. (keep the dir name)

**Comment by stephenpatten** [comment]
Thank you @HUMORCE ! 

The number of times of the fork error does correlate to the the number of  buckets I have, so it was either re-install GIT or try to recreate each one of the buckets by hand... I chose re-install git  and that fixed this error.

FYI. There was also an older copy of Git, by one release that I removed before I used scoop to uninstall Git and install it.

Closing this now.
