### ISSUE TITLE
PG::ConnectionBad error for Postgresql installation with Scoop

### ISSUE THREAD

**Issue by chidumaga** [lukesampson/scoop#433]
I used Scoop to install Postgresql on my Windows 7 machine. When I try to start up the Rails app for which Postgres was installed I get the following error:

```could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?```

I gather that this error could come from settings in the postgresql.conf file that comes with a Postgres install but I can neither find this file nor pg_hba.conf in the directory where Scoop installs Postgres (on my machine this is `C:/Users/<Username>/AppData/Local/scoop/apps` and thus cannot tweak accordingly. What else might be causing this error?

**Comment by lukesampson** [comment]
Scoop doesn't automatically create a Postgres data directory, so you need to do this yourself. And you also need to start the postgres database manually from the command line. It should be pretty easy to do though...

```powershell
# powershell
initdb /pgsql # init the directory where data files and config will be stored
postgres -d /pgsql # start the database server
```

`initdb` creates a `postgresql.conf` for you—in this case it will be at `\pgsql\postgresql.conf`.

If you want to go further and run PostgreSQL as a windows service, try this:

```powershell
scoop install sudo # if you haven't already installed sudo
sudo pg_ctl register -N PostgreSQL -D /pgsql # registers postgres to start automatically on Windows startup
sudo start-process PostgreSQL # start the process now
```

**Comment by chidumaga** [comment]
Thanks for your answer. Do you mind briefly explaining why the database needs to be started manually? Just installing and configuring Postgres seemed to have done the trick.

**Comment by lukesampson** [comment]
If you install Postgres with Scoop it just puts the executable files (like `postgres.exe`) in your path — it doesn't configure anything for you, register a Postgres server service, or start the database running for you. That's why I assumed you would need to create a data directory and start the server program manually.

If you install Postgres with their official GUI installer it will do this stuff for you automatically. Is that what you've done? If that's the case then you don't need to install Postgres with Scoop as well.

**Comment by chidumaga** [comment]
Thanks for your response @lukesampson. I did install with Scoop initially but did not do all the configuration that you mentioned and that's why I was running into those problems. After installing the GUI and editing the `postgres.conf` file everything worked perfectly. 

Doing a GUI-only installation means you can't use postgres in the command line doesn't it? That's why I did it both ways; one the one hand I can open up the postgres console in the command line and on the other hand I have all these postgres settings automatically configured. Seemed like a win-win. Do I understand this correctly?

Thanks for your help.

**Comment by deevus** [comment]
@chidumaga Not sure in regards to Postgres, however many GUI installers will package the command line binaries but just wrap them in a GUI.

**Comment by anji7686** [comment]
Remove pid file
`rm /usr/local/var/postgres/postmaster.pid

`
