### ISSUE TITLE
Command to update all packages?

### ISSUE THREAD

**Issue by Brin-o** [lukesampson/scoop#4364]
Hey,
is there a command to update everything that is installed? I find that running scoop update does not update the programs but kind of acts like apt update does in linux. Yet the there is no way for me to know if one of my scoop packages needs an update and I can kind of blind guess that they do and run "scoop update screentogif" to update screentogif. 

This is obviously bad UX tho so I'm wondering if I'm missing an obvious command here or if this is not implemented.

If its not I would purpose a scoop upgrade, scoop upgrade --list or something of sorts to be able to see what packages can be updated.

**Comment by pixiekat** [comment]
`scoop status` will show you a list of all packages that can be updated.

`scoop update *` will update all items

**Comment by Brin-o** [comment]
thank you!

**Comment by WhiteCanvas6** [comment]
you should close this issue
