### ISSUE TITLE
request: 7zip with zstd and lz4 compression support

### ISSUE THREAD

**Issue by street-grease-coder** [lukesampson/scoop#4378]
Could be as simple as adding the codecs to the install directory. I would make it a pull request if I knew more about how scoop works (and sorry in advance if this is the wrong place to post..)
https://github.com/mcmilk/7-Zip-zstd

**Comment by HUMORCE** [comment]
the complete of 7zip-zstd is already in the main bucket.

`scoop info 7zip-zstd`

**Comment by street-grease-coder** [comment]
I missed this sorry. closed
