### ISSUE TITLE
Lots of missing scoop-manifest.json apps

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [lukesampson/scoop#4389]
Check it out:

![image](https://user-images.githubusercontent.com/3938423/122406183-edf5bb00-cf80-11eb-8170-914a7a828da4.png)

I've got a lot of them. And all of these *failed* are missing the scoop-manifest.json and scoop-install.json files. That's because at my company our C:\User\XYZ isn't actually on C:\ but on a netdrive `\\company\AD\user\XYZ` which has either NO mountpoint or is mounted to P:\ (= `\\company\AD\user\XYZ`)

How to resolve this problem?

**Comment by HUMORCE** [comment]
https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by Unrepentant-Atheist** [comment]
Already done, I install it to c:\myapps\scoop .

**Comment by HUMORCE** [comment]
the shortcut will point to the correct path.

![screenshot_20210618065917](https://user-images.githubusercontent.com/4353480/122520082-b7f91b00-d002-11eb-9ea8-e106d5673cbe.png)
