### ISSUE TITLE
Extract password-protected zip file

### ISSUE THREAD

**Issue by hwuhsi** [lukesampson/scoop#4390]
I'm writing a scoop bucket for [procdot](https://www.procdot.com/downloadprocdotbinaries.htm)
But they are using password-protected zips to distribute their software.
![image](https://user-images.githubusercontent.com/58682507/122592070-6ac68900-d096-11eb-83ef-4fdb01bfd85f.png)
I notice that scoop will extract the file first, before the pre_install script. This leads to infinite waiting.

**Comment by HUMORCE** [comment]
```
{
    "homepage": "https://www.procdot.com",
    "description": "-",
    "version": "1.22-57",
    "license": "Unknown",
    "url": "https://www.procdot.com/download/procdot/binaries/procdot_1_22_57_windows.zip#dl.zip_",
    "hash": "927cd36dbb4dc0be94afb6021ca7f747dd3f17aad383583bc71aa6e36a762849",
    "architecture": {
        "64bit": {
            "pre_install": [
                "$zip=(Get-ChildItem $dir\\procdot*).Name",
                "7z x $dir\\$zip -pprocdot $('-o' + $dir) | Out-Null",
                "Move-Item $dir\\win64\\* $dir"
            ]
        },
        "32bit": {
            "pre_install": [
                "$zip=(Get-ChildItem $dir\\procdot*).Name",
                "7z x $dir\\$zip -pprocdot $('-o' + $dir) | Out-Null",
                "Move-Item $dir\\win32\\* $dir"
            ]
        }
    },
    "post_install": [
        "Remove-Item $dir\\*dl.zip_ -Force",
        "Remove-Item $dir\\win?? -Force -Recurse"
    ],
    "bin": "procmon2dot.exe",
    "shortcuts": [
        [
            "procdot.exe",
            "ProcDOT"
        ]
    ]
}
```

works one.

**Comment by hwuhsi** [comment]
> ```
> {
>     "homepage": "https://www.procdot.com",
>     "description": "-",
>     "version": "1.22-57",
>     "license": "Unknown",
>     "url": "https://www.procdot.com/download/procdot/binaries/procdot_1_22_57_windows.zip#dl.zip_",
>     "hash": "927cd36dbb4dc0be94afb6021ca7f747dd3f17aad383583bc71aa6e36a762849",
>     "architecture": {
>         "64bit": {
>             "pre_install": [
>                 "$zip=(Get-ChildItem $dir\\procdot*).Name",
>                 "7z x $dir\\$zip -pprocdot $('-o' + $dir) | Out-Null",
>                 "Move-Item $dir\\win64\\* $dir"
>             ]
>         },
>         "32bit": {
>             "pre_install": [
>                 "$zip=(Get-ChildItem $dir\\procdot*).Name",
>                 "7z x $dir\\$zip -pprocdot $('-o' + $dir) | Out-Null",
>                 "Move-Item $dir\\win32\\* $dir"
>             ]
>         }
>     },
>     "post_install": [
>         "Remove-Item $dir\\*dl.zip_ -Force",
>         "Remove-Item $dir\\win?? -Force -Recurse"
>     ],
>     "bin": "procmon2dot.exe",
>     "shortcuts": [
>         [
>             "procdot.exe",
>             "ProcDOT"
>         ]
>     ]
> }
> ```
> 
> works one.

Thank you! I think it will be much more convenient if scoop itself provide an option for it.

**Comment by JourneyOver** [comment]
Does this no longer work? I've tried multiple different things of trying to set it to install / pre_install and neither seem to actually work, looking at task manager it seems that it's not actually calling 7-zip at all with the password and instead just defaulting to trying to extract the file without the password at all.

does `extract_dir` or `extract_to` support password any? as looking at https://scoop-docs.vercel.app/docs/concepts/App-Manifests.html#a-simple-example doesn't seem to show an example with password protect files at all.

**Comment by niheaven** [comment]
Use `Expand-7zipArchive` and pass arguments, sorry the password has not been supported in manifest.

**Comment by JourneyOver** [comment]
So I actually figured out the situation, whenever the `url` ends in either .zip/.rar or any other rared typed of extension, it'll always throw the default extraction method, no matter the `pre_install` or `installer stuff.. solution is just to append random bit at end that isn't .zip/.rar or other rar type of extensions and then it'll extract the file correctly with the installer or pre_install bits.

**Comment by niheaven** [comment]
> So I actually figured out the situation, whenever the `url` ends in either .zip/.rar or any other rared typed of extension, it'll always throw the default extraction method, no matter the `pre_install` or `installer stuff.. solution is just to append random bit at end that isn't .zip/.rar or other rar type of extensions and then it'll extract the file correctly with the installer or pre_install bits.

Yes, that's right.
