### ISSUE TITLE
scoop cleanup --cache cleans also installed applications

### ISSUE THREAD

**Issue by tukanos** [lukesampson/scoop#4399]
I tried to remove keepassxc from scoop's cache **only**:

`scoop cleanup --cache keepassxc`

To my surprise it also uninstalled all the previous versions I had:

`Removing keepassxc: _backup_2.6.4 2.5.4 2.6.1 2.6.2 2.6.4`

What I would expect is that when entering the `--cache` parameter only files in cache are removed.

**Comment by dwettstein** [comment]
The idea of the `--cache` parameter from the `cleanup` command is to **additionally** (not only) remove the outdated download cache.

To only remove the download cache, use the command `cache` (see `scoop help cache`).

**Comment by tukanos** [comment]
@dwettstein I see. I have tried the `scoop cache rm <app>`.   This cleans all the downloaded versions.

 Is there a way to cleanup only the older versions but **keep** the **newest version only**?

**Comment by dwettstein** [comment]
@tukanos, with `scoop` I think not. But you can just delete the old files in path `$SCOOP\cache\` manually as a workaround.

**Comment by tukanos** [comment]
@dwettstein I see.  Yes I did that manually and I wanted to update my workflow :).  I guess it has to wait till `scoop` will support it.
