### ISSUE TITLE
Bypass requirements for scoop installation

### ISSUE THREAD

**Issue by Pedro1234-code** [lukesampson/scoop#4403]
Hi. It is not impossible to install scoop on a Windows 8.1 pc in powershell 4. I installed it on my pc, using Powershell core 7, and the pre-installed powershell was 4, and it's working. I installed sudo, 7zip and others using scoop under these conditions (I used powershell core 7 only for installation, I run it on ps 4).

I think the requirements are fake (like Windows 11, with TPM 2.0).

**Comment by Jogai** [comment]
It says Windows 7+ with Powershell 5+. What's fake about that? You confirmed it works on Windows8.1 with powershell 7.

**Comment by Pedro1234-code** [comment]
> It says Windows 7+ with Powershell 5+. What's fake about that? You confirmed it works on Windows8.1 with powershell 7.

But I confirmed it can run in powershell 4

**Comment by Jogai** [comment]
Powershell 7 is maybe in your path. If you need to install it with PS5+ then that is a requirerement, no matter how it runs.

**Comment by Pedro1234-code** [comment]
@Jogai Powershell 7 is not in my PATH, but ok, thank you.
