### ISSUE TITLE
Scoop update all but one

### ISSUE THREAD

**Issue by ManuelNeubergerWN** [lukesampson/scoop#4407]
Hello is there a possibility to update all programs, except one? When I call the "scoop update *" command it fails ones it has reached cygwin. I do not really need the update to cygwin but I do not want to update all other programs manually. So something like scoop update * -except cygwin would be great.

**Comment by HUMORCE** [comment]
scoop hold cygwin

**Comment by ManuelNeubergerWN** [comment]
Ah thanks a lot
