### ISSUE TITLE
fail to install git

### ISSUE THREAD

**Issue by wzy461143268** [lukesampson/scoop#4409]
```
PS C:\Users\wy461> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.32.0.windows.2) [64bit]
The SSL connection could not be established, see inner exception.
URL https://gh.haval.gq/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-64-bit.7z.exe#/dl.7z is not valid
PS `C:\Users\wy461>
```
and I try to download this package through chrome failed too. The report is “ERR_SSL_VERSION_OR_CIPHER_MISMATCH”

**Comment by HUMORCE** [comment]
the manifest of git from 3rd bucket, and the mirror `https://gh.haval.gq/` is down or outdated right now.

install following manifest of main bucket : `scoop install main/git`
