### ISSUE TITLE
BUG: When the update fails, it cannot be updated again

### ISSUE THREAD

**Issue by yxom-alt** [lukesampson/scoop#4414]
PS C:\Users\OP> scoop update * ; scoop status
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
Scoop update failed.
WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.
PS C:\Users\OP> scoop update * ; scoop status
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
error: 5895 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
The main bucket was added successfully.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!
Latest versions for all apps are installed! For more information try 'scoop status'
fatal: unable to access 'https://github.com/lukesampson/scoop/': OpenSSL SSL_connect: Connection was reset in connection to github.com:443
Scoop is up to date.
These app manifests have been removed:
    7zip
    aria2
    git
PS C:\Users\OP> scoop update * ; scoop status
Latest versions for all apps are installed! For more information try 'scoop status'
Scoop is up to date.
These app manifests have been removed:
    7zip
    aria2
    git
PS C:\Users\OP>scoop install go
Couldn't find manifest for 'go'.
PS C:\Users\CNM>

What should I do?

**Comment by HUMORCE** [comment]
```powershell
remove-item "$env:SCOOP\buckets\main" -recurse
git clone https://github.com/ScoopInstaller/Main.git "$env:SCOOP\buckets\main"
```

you can also do this with scoop(`$env:SCOOP\apps\scoop\current`)
