### ISSUE TITLE
I cant install ffmpeg through scoop

### ISSUE THREAD

**Issue by sppidy** [lukesampson/scoop#4419]
![image](https://user-images.githubusercontent.com/68327188/127967562-de6961e6-2626-4a1f-9a1f-0ea19490d76a.png)

**Comment by HUMORCE** [comment]
ffmpeg build 2021-07-19-12-36 has been removed from repo BtbN/ffmpeg-Builds.

execute `scoop update` before `scoop install`

**Comment by sppidy** [comment]
Yup it worked Thanks for Helping
