### ISSUE TITLE
Can't install blender

### ISSUE THREAD

**Issue by andreypudov** [lukesampson/scoop#4423]
scoop install blender
Installing 'blender' (2.93.2) [64bit]
Loading blender-2.93.2-windows-x64.zip from cache
Checking hash of blender-2.93.2-windows-x64.zip ... ok.
Extracting blender-2.93.2-windows-x64.zip ... Exception: C:\Users\apu\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'blender-2.93.2-windows64'! (error 16)

**Comment by HUMORCE** [comment]
```
PS C:\Users\humorce> scoop install blender
Installing 'blender' (2.93.2) [64bit]
Loading blender-2.93.2-windows-x64.zip from cache
Checking hash of blender-2.93.2-windows-x64.zip ... ok.
Extracting blender-2.93.2-windows-x64.zip ... done.
Linking ~\scoop\apps\blender\current => ~\scoop\apps\blender\2.93.2
Creating shim for 'blender'.
Creating shortcut for Blender (blender.exe)
'blender' (2.93.2) was installed successfully!
```

cannot reproduce.
