### ISSUE TITLE
mingw windres

### ISSUE THREAD

**Issue by Akuli** [lukesampson/scoop#4427]
I have done `scoop install gcc` (with this fix applied https://github.com/lukesampson/scoop/issues/4235#issuecomment-766168326 ), and running `windres` on command prompt or powershell gives `The term 'windres' is not recognized ...` error, even though `gcc` works.

How am I supposed to install windres? I have tried:
- `scoop install windres`
- `scoop search windres`
- `scoop search mingw`
- `scoop install codeblocks-mingw`
- Googling `"scoop" "windres"`

**Comment by HUMORCE** [comment]
cannot produce.

```
> (Get-Command windres).Path
C:\Users\HUMORCE\scoop\apps\gcc\current\bin\windres.exe
> windres -V
GNU windres (GNU Binutils) 2.35.1
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

`MSYS2` is recommended to you.

**Comment by Akuli** [comment]
This problem is mentioned in https://github.com/lukesampson/scoop/issues/4235#issuecomment-766168326 : "scoop does not seem to handle .zst decompression"
