### ISSUE TITLE
Feature Issues: Add global  config replace default download url with configed url to improve download speed

### ISSUE THREAD

**Issue by chouxiaozi** [lukesampson/scoop#4429]

**Comment by HUMORCE** [comment]
which person/organization can provide mirrors for each service?

**Comment by chouxiaozi** [comment]
[FastGit ](https://doc.fastgit.org/en-gb/) **FastGit is an open source mirror speeder for GitHub.com.** 
[jsDelivr](https://www.jsdelivr.com/) **A free CDN for Open Source  fast, reliable, and automated**

The idea is to take advantage of cdn's abilities.

**Comment by HUMORCE** [comment]
yeah, but these mirrors/cdns for github content only. NOT all apps are distributed through github.

the project is related to your idea: https://gitee.com/squallliu/scoop

**Comment by chouxiaozi** [comment]
yes it's github cdn.but it can use in this way:


[https://github.com/appbaseio/abc/releases/download/1.0.0-beta.2/abc-windows.zip](https://github.com/appbaseio/abc/releases/download/1.0.0-beta.2/abc-windows.zip)
can be transform to
[https://hub.fastgit.org/appbaseio/abc/releases/download/1.0.0-beta.2/abc-windows.zip
](https://hub.fastgit.org/appbaseio/abc/releases/download/1.0.0-beta.2/abc-windows.zip
)by  replace "https://github.com" to "https://hub.fastgit.org"


[https://7-zip.org/a/7z1900-x64.msi](https://7-zip.org/a/7z1900-x64.msi)
can be transform to 
[https://my.domain/nexus/raw/7z/7z1900-x64.msi
](https://my.domain/nexus/raw/7z/7z1900-x64.msi
)by replace "https://7-zip.org/a/" to "https://my.domain/nexus/raw/7z/"

**Comment by HUMORCE** [comment]
emmm, you took the question back to my first reply.

github action is good for replacing them.

**Comment by chouxiaozi** [comment]
ok.
I misunderstood.
Thanks for your reply.
