### ISSUE TITLE
Cmake can't find CMAKE_CXX_COMPILER after install llvm with scoop

### ISSUE THREAD

**Issue by ellipticaldoor** [lukesampson/scoop#4457]
So I installed clang++ using scoop with the command `scoop install llvm`

Now when running cmake I get the following error:
```sh
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

How I can setup this env variables? It looks like scoop installed clang++ correctly in my path, so, is there any utility in scoop to set this enviroment variables?

**Comment by HUMORCE** [comment]
`scoop info direnv`

**Comment by ellipticaldoor** [comment]
ah thank you
