### ISSUE TITLE
Can't output result of 'scoop list' command to file

### ISSUE THREAD

**Issue by PeterKW** [lukesampson/scoop#4463]
I have been trying to work out how to make a PowerShell command that outputs the list of scoop packages to be saved in a text file. The applications are listed on the screen in powershell but don't get to be saved in the file. Is this something to do with scoop taking a few seconds to output the results? 
Scoop is really good and it would be useful to have a backup of packages installed.

```
PS C:\Documents> scoop list > ScoopInstalledPrograms-PS-$env:username@$env:computername.txt

Installed apps:

  7zip 19.00 [main]
  adb 31.0.3 [main]
  archwsl 20.11.25.0 [extras]
  aria2 1.35.0-1 [main]
  git 2.33.0.windows.2 [main]
  neofetch 7.1.0 [main]
  scrcpy 1.18 [main]
```

**Comment by HUMORCE** [comment]
scoop export > installed_pkgs.txt

**Comment by PeterKW** [comment]
Thank you very much @HUMORCE !
That's exactly what I was trying to find
