### ISSUE TITLE
New git doesn't save ssh passphrase

### ISSUE THREAD

**Issue by nkm8** [lukesampson/scoop#447]
It looks like the fix was here:  https://github.com/lukesampson/scoop-extras/pull/88

However, after git was updated here: https://github.com/lukesampson/scoop/issues/371 the functionality to save the ssh key passphrase is no longer working correctly.  Is there an alternative fix or does the above change need to be merged into the `scoop` repo?

EDIT: Confirmed that this is not an issue with git19 and I also tried `scoop reset openssh` as mentioned here:  https://github.com/lukesampson/scoop-extras/pull/86

**Comment by deevus** [comment]
The problem I have with that fix is that it will replace the user installed shims for `ssh*`. It would be better if it could work with the users version of `openssh`

**Comment by deevus** [comment]
I've had another look at this. It seems that the newer version of git prefers it's local `ssh` over any in the path. I was able to override this by setting `$env:GIT_SSH = resolve-path $(scoop which ssh)`, which works!

**Comment by deevus** [comment]
@lukesampson If we make git depend on `openssh` we could set this in the `post_install`

**Comment by lukesampson** [comment]
OK that sounds like a good compromise if that works. It's strange that the old git could check if there was already an `ssh-agent` process running, but the new one can't.

**Comment by nkm8** [comment]
Fix confirmed; thanks for the quick resolution.
