### ISSUE TITLE
Some package files have a date way in the past like Jan 31 1980

### ISSUE THREAD

**Issue by stepht** [lukesampson/scoop#4479]
I see that in a few pkgs some files are way in the past:

C:\pt\scoop\apps>fd --changed-before 30years | sbperl0 -lnE "s{\\.*$}{}; our %h; $h{$_}++; END{ say qq[$_ => $h{$_}] for keys %h }"
jbang => 10
gcloud => 20595
kotlin => 108
kotlin-native => 1864
gradle => 11013
, 

I wonder what can trigger that. All pkgs are java-related

Anybody see that?
thanks

**Comment by HUMORCE** [comment]
this means they are missing the timestamp.

**Comment by stepht** [comment]
Yes that is what I think happens. Yet whats surprises me is how and why.
If I package some project with some tool like tar o 7z, it not easy to fiddle with the timestamp except if somehow the tool cannot read the timestamp and decides to put for all those files with unreadable timestamps an epoch tiemstamp or whatever is the version of the epoch is for the tool.

Another possibility is that somehow the tool used for extraction by scoop cannot read some timestamps and thus spits out his version of the "epoch".

kotlin-native ships 2 o 3 times per year. don't you find it weird that an active project have such timestamps...

I hope you don't find me too peaky. I love scoop! :) 
I will investigate a bit more...
hth
