### ISSUE TITLE
How to uninstall scoop?

### ISSUE THREAD

**Issue by loostro** [lukesampson/scoop#448]
I'd like to uninstall scoop and cleaup any changes it made. How to do this?

**Comment by lukesampson** [comment]
The command is `scoop uninstall scoop`—this will remove any programs you installed with Scoop, and Scoop itself.

**Comment by loostro** [comment]
@lukesampson Thanks.

**Comment by coombsj** [comment]
The scoop application seems to have gotten corrupted on my system, I can't run the scoop command to uninstall itself and when I attempt to re-install, an error displays on the command line and the powershell window closes before I can read what it says.

Is there a more manual way of uninstalling scoop itself?

**Comment by lukesampson** [comment]
If you delete ~/appdata/local/scoop you should be able to reinstall.

**Comment by crazy54** [comment]
should add this to the uninstall page - took me a while to google this answer.

**Comment by zakarumych** [comment]
I didn't find `scoop` in `~/appdata/local/scoop`, but simply at `~/scoop`. After removing it I was able to re-install.

**Comment by inspector71** [comment]
`scoop uninstall scoop`

... did not clean up after itself, in my experience, leaves behind 

`~/scoop/*`

Thanks for tyring to improve the ease of use of Windows BTW.

**Comment by brokedarius** [comment]
It still leaves the env. variables on windows, would be nice if it could remove them at the same time as well as the persist folder, the config folder and the startup folder.

**Comment by hungpham3112** [comment]
> It still leaves the env. variables on windows, would be nice if it could remove them at the same time as well as the persist folder, the config folder and the startup folder.

I have the same problems.

**Comment by rashil2000** [comment]
If auto-uninstall is not working:
- remove ~/scoop folder
- remove env vars that have /scoop/ in them

**Comment by hungpham3112** [comment]
> If auto-uninstall is not working:
> 
> * remove ~/scoop folder
> * remove env vars that have /scoop/ in them

How to make a new feature for scoop instead of do it by hand? Auto-uninstall and cleaning Path after uninstalling. It's quite helpful.

**Comment by rashil2000** [comment]
`scoop uninstall scoop --purge`

**Comment by hungpham3112** [comment]
![image](https://user-images.githubusercontent.com/75968004/154639534-fd657d59-357a-4c20-a548-e98ad17a62a0.png)

**Comment by rashil2000** [comment]
Hmm, looks like a bug in bin/uninstall.ps1

**Comment by zionnewbie** [comment]
> The command is `scoop uninstall scoop`—this will remove any programs you installed with Scoop, and Scoop itself.
That's an interesting way ! . tbh at first i thought this might be a joke .but no it actually work's . idk how but scoop can uninstalll it'self
