### ISSUE TITLE
Apache install results in 404 error

### ISSUE THREAD

**Issue by beejasaurus** [lukesampson/scoop#458]
I tried installing apache, but it gave me the following error:
```
scoop install apache
installing apache (2.4.12)
downloading http://www.apachelounge.com/download/VC11/binaries/httpd-2.4.12-win32-VC11.zip..The remote server returned an error: (404) Not Found.
```

It appears the path needs to go to either: 
- https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.16-win64-VC14.zip
- https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.16-win32-VC14.zip

**Comment by deevus** [comment]
Fixed in #468
