### ISSUE TITLE
how to list 'package' contents (e. g. all tools included in pstools)

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#46]
``` powershell
$ scoop bucket add extras
$ scoop install pstools
$ scoop list
$ # [...] lists only 'pstools'
```

(By memory, might be the wrong commands I've listed above.)

Is it possible to list the contents of a _package_ (for lack of a better name).

**Comment by adamency** [comment]
@lukesampson @rashil2000 @niheaven 

I would like to reopen this issue. This feature is very much needed for a well-made and reliable package manager and I have had a big hope for years for `scoop` to be the only tool on Windows that can compare with Linux package managers with regards to their transparency and reliability.

It's been 10 years this issue was raised, I believe it is relevant to put it back on the table. What do you maintainers think ?

**Comment by niheaven** [comment]
@adamency `scoop info xxx` will do the job.

**Comment by darthwalsh** [comment]
@guillermooo  @adamency  have you tried `scoop cat`?

I'm not familiar with the scoop manifest so it looks the answer about installed binaries will be scattered across `.architecture`, `.bin`, or maybe `.shortcuts`

```command
$ scoop bucket add sysinternals
Checking repo... OK
The sysinternals bucket was added successfully.

$ scoop cat pstools | head -n 20
{
    "version": "2.51",
    "description": "Command-line utilities for listing the processes running on local or remote computers, running processes, rebooting computers, and more.",
    "homepage": "https://learn.microsoft.com/sysinternals/downloads/pstools",
    "license": {
        "identifier": "Freeware",
        "url": "https://learn.microsoft.com/sysinternals/license-terms"
    },
    "url": "https://download.sysinternals.com/files/PSTools.zip",
    "hash": "a9ca77dfe03ce15004157727bb43ba66f00ceb215362c9b3d199f000edaa8d61",
    "architecture": {
        "64bit": {
            "bin": [
                [
                    "PsExec64.exe",
                    "PsExec"
                ],
                [
                    "psfile64.exe",
                    "psfile"

$ scoop cat pstools | jq '.architecture["64bit"].bin[] | .[0]' -r
PsExec64.exe
psfile64.exe
PsGetsid64.exe
PsInfo64.exe
pskill64.exe
pslist64.exe
PsLoggedon64.exe
psloglist64.exe
pspasswd64.exe
psping64.exe
PsService64.exe
psshutdown64.exe
pssuspend64.exe

$ scoop cat 7zip | jq '.bin[]' -r
7z.exe
7zFM.exe
7zG.exe

$ scoop cat obsidian | jq '.shortcuts[] | .[0]' -r
Obsidian.exe
```

**Comment by HUMORCE** [comment]
@darthwalsh I think what the OP wants is just to list all the files of package, like `brew list <installed_package>` and `dpkg -L <installed_package>`.

```
> $app = "7zip"

# A
> Get-ChildItem -Path (scoop prefix $app) -Name -Recurse
## with filter
> Get-ChildItem -Path (scoop prefix $app) -Name -Recurse -Include '*.exe'

# B
> scoop install tre-command
> tre (scoop prefix $app)
## with filter
> tre (scoop prefix $app) | Select-String '\.exe'
```

Scoop does not track files that stored at out of Scoop managed directory, so we can list root dir of app installation only.

**Comment by adamency** [comment]
@HUMORCE Yep that's right, @niheaven & @darthwalsh `scoop info` and `scoop cat` are not solutions to this issue. `scoop cat` only lists executables and `scoop info` isn't even remotely relevant to this issue.

So as you can see, no workaround is a proper equivalent to package managers listing like `dpkg -L`, `pacman -Ql` or `brew list`. @HUMORCE is it technically impossible to implement this feature in scoop ?
