### ISSUE TITLE
OpenSSH update

### ISSUE THREAD

**Issue by Stanzilla** [lukesampson/scoop#461]
Scoop's OpenSSH is pretty out of date, any chance of getting version 7 in? https://github.com/openssh/openssh-portable/releases/tag/V_7_0_P1

http://ftp.hostserver.de/pub/OpenBSD/OpenSSH/portable/openssh-7.0p1.tar.gz

**Comment by ntwb** [comment]
Went looking for this, the latest Windows binary available is openssh-5.4p1-1 from our current source:
http://sourceforge.net/projects/mingw/files/MSYS/Extension/openssh/

The 7.0 portable package also doesn't include any Windows binaries from:
https://github.com/openssh/openssh-portable/releases/tag/V_7_0_P1

Any other suggestions?

**Comment by Stanzilla** [comment]
I think one has to compile it with MSYS2 now, that would be https://github.com/Alexpux/MSYS2-packages/tree/master/openssh but that is also old :/

**Comment by Stanzilla** [comment]
7.1 https://github.com/openssh/openssh-portable/releases/tag/V_7_1_P1

**Comment by Stanzilla** [comment]
Requested an update here https://github.com/Alexpux/MSYS2-packages/issues/332

**Comment by Stanzilla** [comment]
Since https://github.com/Alexpux/MSYS2-packages/commit/6389198ecb90a784c0df8af5b8e7e546827534a6 7.1p1 is available here http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/openssh-7.1p1-1-x86_64.pkg.tar.xz/download

**Comment by Stanzilla** [comment]
Also might wanna update the OpenSSL version that is in OpenSSH's json.

**Comment by Stanzilla** [comment]
Hey @lukesampson any news here?

**Comment by deevus** [comment]
@Stanzilla The team is a bit busy at the moment. If you're happy to make a PR i'll merge it in. Otherwise it will may need to wait a while longer.

**Comment by deevus** [comment]
@Stanzilla After playing around with this for about 30 minutes, it seems as though we can't install that version of OpenSSH without MSYS2. 

As far as I can see, MSYS2 uses an installer from which I was unable to extract anything from without running it.

**Comment by madbub** [comment]
Doesn't #635 solve this problem? Can this issue be closed?

**Comment by Stanzilla** [comment]
@deevus @lukesampson can we get an up to date OpenSSH out of the Git package? https://github.com/git-for-windows/MSYS2-packages/commit/633933b5131ff5f45195e41fe46e6f607d176c34

**Comment by HLFH** [comment]
Yes, it would be great to be able to use OpenSSH_7.3p1

**Comment by lukesampson** [comment]
How about using [git-with-openssh](https://github.com/lukesampson/scoop/blob/master/bucket/git-with-openssh.json) as a temporary fix? That gives you ssh.exe and sshd.exe, I'm not sure which version it is though. I haven't been able to find another recent SSH that doesn't crash.

There are new updates for [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status) coming in a few days. That looks like the best hope long-term for SSH on Windows, but that might be a while off.

If you have time to investigate and submit a pull request with a manifest for a good version of OpenSSH that would be much appreciated.
