### ISSUE TITLE
feature request for the android adb tool

### ISSUE THREAD

**Issue by devoncarew** [lukesampson/scoop#471]
Like what the title says :)

**Comment by deevus** [comment]
@devoncarew Doesn't adb require a driver?

**Comment by devoncarew** [comment]
No, as far as I know it just talks regular usb to the android device.

**Comment by deevus** [comment]
Can you provide a link to the best place to get it, and I'll look at getting it in?

**Comment by devoncarew** [comment]
Here's one potential place:

    https://dl-ssl.google.com/android/repository/platform-tools_r23-windows.zip

Though I don't know if that is the canonical download location...

**Comment by deevus** [comment]
Added in b8ad4c13cb17fa7bc93888b775808763a63fdca2
