### ISSUE TITLE
Scoop PHP 5.6.12 malware flag

### ISSUE THREAD

**Issue by sunnywalker** [lukesampson/scoop#474]
I don't know if this is a scoop issue or not, but after I used `scoop update php`, Windows Defender is claiming that there is a **Trojan:win32/Peals.F!plock** malware detected in `C:\Users\{username}\AppData\Local\scoop\apps\php\5.6.12\_scoop_extract\ext\php_fileinfo.dll`. I'm hoping it's just a false positive.

**Comment by ntwb** [comment]
I just installed PHP via `scoop install php` and Windows Defender didn't pop up anything whilst installing, and a full scan of my `C:\Users\{username}\AppData\Local\scoop` folder returned no issues.

I scanned the PHP 5.6.12 at VirusTotal:

`php_fileinfo.dll` https://www.virustotal.com/en/file/17a9a3750e799d7b9349c329ac66cee22524360f6bdd33edda743f6e0e5a1870/analysis/1440540548/

URL `http://windows.php.net/downloads/releases/php-5.6.12-Win32-VC11-x86.zip`
https://www.virustotal.com/en/url/ea2dd628cbc172a181a52b351dfefe29c69a5d821468ebc2cf1e8f0eb73cc8a0/analysis/1440540304/

File `php#5.6.12#http_windows.php.net_downloads_releases_php-5.6.12-Win32-VC11-x86.zip`
https://www.virustotal.com/en/file/919fe272ae7b89d4a2082a438d8c3bf4814559f327cf39ff43f8af1b6bd4c5f6/analysis/

The full zip archive upload analysis shows `Bkav` reporting `VEX2819.Webshell`, though I think this is a false positive based on a quick read of links via https://www.google.com.au/search?hl=en&q=VEX2819.Webshell

**Comment by sunnywalker** [comment]
Thank you. I'll assume it's an issue on my side then.

**Comment by ntwb** [comment]
Cool, it's always worth double checking here, I'd hate to find we shipped a package full of Malware or a Virus.
