### ISSUE TITLE
Can't uninstall nodejs; larger problem afoot

### ISSUE THREAD

**Issue by mikemimik** [lukesampson/scoop#478]
When trying to uninstall nodejs with scoop I get the error
>`couldn't remove ~\appdata\local\scoop\app\nodejs\0.12.7: it may be in use`

I made sure that the node process was not in use anywhere, and no program had a hook into it or anything. Tried again and nothing.

I used the command `scoop uninstall scoop` to remove scoop and any application it had installed (would is only nodejs, basically my workaround for the above not working). I got the error message:

>`cound't remove ~\appdata\local\scoop: The specified path, file name, or both are too long. The fully qualified file name must be less that 260 characters, and the directory name must be less than 248 characters.`

What's going on here?

**Comment by ntwb** [comment]
Windows cannot handle long paths, this includes Windows 10 and is pretty lame Microsoft still have not fixed this :disappointed: 

The workaround I use when this happens is to rename some `node_modules` folders to short names or numbers.

So previously you may have had something like:
`\appdata\local\scoop\app\nodejs\0.12.7\app1\node_modules\anotherapp\node_modules\moreapps\node_modules`

And I'll rename these folders to something like:
`\appdata\local\scoop\app\nodejs\0.12.7\app1\1\anotherapp\2\moreapps\3`

I keep renaming and trying to manually delete the folders in Explorer until they are gone. ¯\_(ツ)_/¯

**Comment by mikemimik** [comment]
@ntwb thanks for this workaround. It did the trick for me, it let me run the command `scoop uninstall scoop`

I was really just using scoop for nodejs, I thought it was be nice having a package manager deal with it. I use the git-bash shell though so having a package manager to install tools isn't necessary for me because the git-installer comes with some useful ones.

**Comment by deevus** [comment]
@mikemimik Glad you got your issue sorted

**Comment by maoizm** [comment]
actually Windows supports very long file paths for so long  using the following syntax:

`\\?\c:\documents\some-really-super-long-folder-name-scheme\`

[http://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx](url)

**Comment by iamfaqeehhokyky** [comment]
This works for me `scoop uninstall nodejs-lts`
