### ISSUE TITLE
[Bug] scoop in docker shims seem broken

### ISSUE THREAD

**Issue by mjvankampen** [lukesampson/scoop#4792]
#### Current Behavior
install scoop in a docker container
install a scoop package (such as git)
use scoop package in a subsequent RUN command results in:
```
Could not create process with command '"C:\Users\ContainerAdministrator\scoop\apps\git\current\cmd\git.exe"  clone -q https://github.com/samuelcolvin/pydantic.git C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-xmwtmaol\pydantic_4641e039e3774955b81c25db0d639f23'.
```

#### Expected Behavior
Can use installed programs

#### Possible Solution
https://github.com/ScoopInstaller/Scoop/tree/2021-12-26 does work

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

I will try to add more config details asap, but maybe someone already has an idea?

**Comment by niheaven** [comment]
What if using shim? i.e., `<scoopdir>\shims\git.exe` to run the command.

**Comment by rashil2000** [comment]
Additionally, can you remove the double quotes in `<scoopdir>\shims\git.shim` file and try again? I have a feeling this regression is due to the double quotes, again

**Comment by hboomsma** [comment]
@rashil2000 @mjvankampen 
Found a broken link of some sort:
![image](https://user-images.githubusercontent.com/1465009/157492080-f3f247a9-9c25-422b-99b2-9bcc2db417d1.png)

From the version directory it seems to work:
![image](https://user-images.githubusercontent.com/1465009/157492192-6267fee4-6a92-47ec-af83-802bd5943836.png)

**Comment by niheaven** [comment]
So the `current` dir is broken or not linked?

**Comment by hboomsma** [comment]
Looks like it to me, but I'm not familiar with windows links:
![image](https://user-images.githubusercontent.com/1465009/157496782-f0a8c65e-445e-497e-9847-480f68d630dc.png)

**Comment by pd-kcarrasco** [comment]
We're being affected by the same issue as well. all Junctions created with `New-Item -ItemType Junction` are broken.
I think we need to revert [this commit](https://github.com/ScoopInstaller/Scoop/commit/98ea7a5e823960a41b86ae6c4fce9c413e63e107). junctions created with `mklink` work:

After building a container, run it and you can see junctions crated with `new-item` are missing their target:
```
# empty target from junction created with New-Item
PS C:\Users\ContainerAdministrator\scoop\apps\python37\3.7.9> (gi .\scripts_new-item\).Target

# target is present in junction created with mklink
PS C:\Users\ContainerAdministrator\scoop\apps\python37\3.7.9> (gi .\scripts_mklink\).Target
C:\Users\ContainerAdministrator\scoop\persist\python37\Scripts

```

**Comment by charliedaveputh** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by kingster** [comment]
Not sure if this is a PowerShell issue. This used to work with the same PowerShell version till scoop-[2021-12-26](https://github.com/ScoopInstaller/Scoop/tree/2021-12-26), I would also agree with @pd-kcarrasco that probably https://github.com/ScoopInstaller/Scoop/commit/98ea7a5e823960a41b86ae6c4fce9c413e63e107 broke this

**Comment by rashil2000** [comment]
It seems to affect only docker containers, that's why I asked if there's a report of it somewhere upstream

**Comment by kingster** [comment]
https://github.com/docker/for-win/issues/12240 Found this bug report, but seems like this was not fixed

**Comment by rashil2000** [comment]
Is there a way to recognize docker context (with help of an environment variable or something)? We can write a wrapper function for it as a workaround

**Comment by kingster** [comment]
Not exactly docker context, but surely possible for containers (docker build should behave this same)  https://stackoverflow.com/a/46810471

**Comment by kingster** [comment]
Have attempted the fix in #4837. With that fix I was able to install it successfully inside a `Dockerfile`

**Comment by rashil2000** [comment]
Yes, we should probably create a small patch release for the recent bug fixes.
/cc @niheaven

**Comment by niheaven** [comment]
Of cause, in a few days, maybe.

**Comment by skeptic-monkey** [comment]
If we have to wait for couple of days, what would be the instruction to install the scoop from the develop branch ?
This is blocking the CI/CD of my company, as I can't rebuid my containers.

**Comment by rashil2000** [comment]
scoop config SCOOP_BRANCH develop
scoop update

**Comment by rashil2000** [comment]
@niheaven could you please draft a patch release? It's been 4 weeks 😅
