### ISSUE TITLE
`scoop update`, being one-pass, may leave the project in an inconsistent state

### ISSUE THREAD

**Issue by rivy** [lukesampson/scoop#480]
Updating `scoop` by using `scoop update` is currently implemented as a one-pass, self-modifying process. This update process overwrites the currently executing version with the newest available code. But, if the "update code" itself is modified by the `scoop update` command, it is possible to leave the executable in an inconsistent/"half-complete" state. At least one execution of the new "update code" would be needed to restore consistency.

For example, if the code generating the scoop shim is changed during an update, the shim artifact that is generated will have been generated by the *original code*. This may be inconsistent or incorrect when executed in the context of the newly updated, now current code.

To correct this, `scoop update` should be re-executed if modifications to the "update code" are detected.

It is, of course, possible that additional code modification to the "update code" could again occur if a repository modification occurs during the restart. But that likelihood is estimated to be much lower than the likelihood of a logic error causing uncontrolled looping. So, the number of restarts is capped at N=1. If the likelihood of a change in the source repository occurring during a `scoop update` becomes significant, then, by increasing the number of restarts allowed, the percentages of each likelihood can be manipulated so that correct/full execution probability is maximized.

NOTE: "update code" is purposefully used within quotes here because subdividing the code base into partitions of "update-stable"/"update-volatile" is really an NP-complete problem. Theoretically, *any* change to the code base could cause an inconsistency. If that is estimated to be a concern of real significance, arbitrarily re-executing the code for any noted change is also reasonable (again, up to a maximum of N times, for the above reasons).

**Comment by lukesampson** [comment]
I think this also only applies to people running in DOS mode, and the remote possibility of a failure is acceptable in order to keep things simple.

**Comment by rivy** [comment]
Actually, no, since the main scoop script runs via an intermediary shim for both shells (`scoop.CMD` for CMD and `scoop.ps1` for PowerShell), it applies equally to both CMD/DOS shell users and PowerShell shell users.

**Comment by lukesampson** [comment]
Oh sorry, I confused this with your other pull request. However this adds a fair amount of complexity to solve a problem that I think we're unlikely to encounter. In the shim example you mentioned, we'd expect a shim generated by old or new methods to have the same results i.e. execute the program. So it doesn't really matter if, during the course of an update, the old shim function was used even though the new code will use a new method from then on.
