### ISSUE TITLE
[Bug] zenity package uninstall

### ISSUE THREAD

**Issue by ncruces** [lukesampson/scoop#4901]
## Bug Report

I created a [manifest](https://github.com/ncruces/scoop/blob/main/zenity.json) for my [`zenity`](github.com/ncruces/zenity) Windows *“port”*.

The zip unpacks into a single `zenity.exe` file, but I also need a [wrapper script](https://raw.github.com/wiki/ncruces/zenity/cygshim) for Cygwin, MSYS2, Git Bash.

But install fine, but on uninstall I get an error message. It seems `scoop` is trying to delete `zenity.exe` twice.

#### Current Behavior

```
$ scoop install https://ncruces.github.io/scoop/zenity.json
Installing 'zenity' (0.8.5) [64bit]
Loading zenity_win64.zip from cache
Checking hash of zenity_win64.zip ... ok.
Loading zenity from cache
Checking hash of zenity ... ok.
Extracting zenity_win64.zip ... done.
Linking D:\Apps\Scoop\apps\zenity\current => D:\Apps\Scoop\apps\zenity\0.8.5
Creating shim for 'zenity'.
Creating shim for 'zenity'.
'zenity' (0.8.5) was installed successfully!
```

```
$ scoop uninstall zenity
Uninstalling 'zenity' (0.8.5).
Removing shim 'zenity'.
Removing shim 'zenity.shim'.
Removing shim 'zenity.exe'.
Remove-Item : Cannot find path 'D:\Apps\Scoop\shims\zenity.exe' because it does not exist.
At D:\Apps\Scoop\apps\scoop\current\lib\install.ps1:907 char:21
+                     Remove-Item -Path "$shimdir\$name.exe"
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Apps\Scoop\shims\zenity.exe:String) [Remove-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Removing shim 'zenity.cmd'.
Removing shim 'zenity'.
Unlinking D:\Apps\Scoop\apps\zenity\current
'zenity' was uninstalled.
```

### System details

**Windows version:** 10
**OS architecture:** 64bit
**PowerShell version:** 5.1.19041.1645

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-05-05T15:31:01.8605543+01:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
You can't create a shim with same basename twice. You would need to use `env_add_path` to keep both script and binary useful. Have a look at gsudo's manifest: https://github.com/ScoopInstaller/Main/blob/master/bucket/gsudo.json
