### ISSUE TITLE
nodejs install hash check fails

### ISSUE THREAD

**Issue by orhanveli** [lukesampson/scoop#491]
hash check failed for http://nodejs.org/dist/v0.12.7/x64/node-v0.12.7-x64.msi. expected: 05cfffda323563c42ff2e461a8e98ee984ad15d1, actual: c6bee9b445464c51caa04951c8b7425917cc3c1b!

**Comment by deevus** [comment]
Looks like their servers are having issues at the moment. If it is still broken after their issues have been resolved, we can probably just update to v4.0.0

**Comment by deevus** [comment]
Resolved with update to v4.0.0
