### ISSUE TITLE
How can I use a different theme than Solarized?

### ISSUE THREAD

**Issue by aloisdg** [lukesampson/scoop#506]
Hello,

I begin to use scoop and I achieve to install the theme Solarized thanks to the doc.
Now, I would love to switch to another theme.
Is there a list of theme? How can I switch to another one?

Thank you

**Comment by lukesampson** [comment]
Check out the list of [presets](https://github.com/lukesampson/concfg/tree/master/presets) for [concfg](https://github.com/lukesampson/concfg).

For example, you can switch to Monokai using `concfg import monokai`.

**Comment by aloisdg** [comment]
Ok thank you.
