### ISSUE TITLE
Not so important: relative shim paths

### ISSUE THREAD

**Issue by ErnWong** [lukesampson/scoop#507]
I was lurking through the issue tracker for this beautiful program, when I noticed that my shim's paths are absolute despite https://github.com/lukesampson/scoop/pull/443... Sorry if this is a non-problem: was the relative-shim-path-feature removed intentionally or accidentally? (Or worse, was my mind at the wrong end of the universe and I misunderstood the whole thing? :smile: )

https://github.com/lukesampson/scoop/commit/5d097a7c7882828fedfc09b5b63ee54e10fe29f2#diff-f0957a994e6c95d903caeb55bf700101L123

**Comment by deevus** [comment]
I think this was removed accidentally. Good pickup.

**Comment by lukesampson** [comment]
Relative paths should be restored by 291f6caf80806ea9f1ba8daee5678f28905b6bf7.
