### ISSUE TITLE
Start as service feature

### ISSUE THREAD

**Issue by jonasgeiregat** [lukesampson/scoop#513]
For some soop buckets it might be usefull to have the ability to start them as a service.

For example it would be useful if it where possible to enable mariadb as a service.

Would the post post_install fit these kind of tasks ? 

You will most likely need Administrator rights to create new services, that would probably be an issue ?

**Comment by deevus** [comment]
It is the ideology of scoop to mess with your system as little as possible. So keeping with this ideology I think installing services as part of installing an app is out. 

And also, yes you would probably need administrator access which is also out.

That's not to say that you couldn't create your own bucket with these kind of manifests that in general require administrator access.
