### ISSUE TITLE
[Bug] The github-actions bot is not auto updating the app manifests in MyScoop bucket.

### ISSUE THREAD

**Issue by kris3713** [lukesampson/scoop#5174]
#### Current Behavior

In my [scoop bucket](https://github.com/Zliced13/MyScoop), the **github-actions** bot is not auto updating my manifests. What am I doing wrong?

#### Expected Behavior

The **github-actions** bot should autoupdate my app manifests.

### System details

**Windows version:** [e.g. 7, 8, 10] 
10

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-10-07T08:30:08.1345008-06:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-warning-enabled":  false,
    "aria2-enabled":  true
}
```

**Comment by Zliced13** [comment]
Can anyone help me please? I will literally take anyone's help for this issue.

**Comment by rashil2000** [comment]
Have you manually enabled the Excavator workflow on Actions page?
