### ISSUE TITLE
Change scoop installation dir

### ISSUE THREAD

**Issue by Anachron** [lukesampson/scoop#52]
For everyone who wanna know, this is how I did it:
https://gist.github.com/Anachron/8152658

Could be quite handy when you need some choice.

**Comment by yinyee** [comment]
Have the same constraint on my work machine as dennislloydjr and tried following the directions given by lukesampson but it didn't work for me :( Unfortunately will have to give scoop a miss, although it seems really good!

**Comment by espre05** [comment]
Most users of scoop come from linux background.  Usually want to keep C: drive just for OS, and put rest in D:.  I store additional softwares like maven-repo, dev tools, appservers etc in D:.

SCOOP_GLOBAL didn't work. 

scoop & curl were installing neatly. However ends up in C:  that has very less space. For now abandoning.

**Comment by r15ch13** [comment]
@espre05 `SCOOP_GLOBAL` is only for globally installed apps. You have to set the `SCOOP` environment variable to `D:\scoop` before installing it.

**Comment by r15ch13** [comment]
@itslog Setting `SCOOP_GLOBAL` on the `MACHINE` makes more sense. 👍
