### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aman-bahl** [lukesampson/scoop#5274]
#### Current Behavior

When I'm trying to install to install Scoop, it shows the output in the screenshot given below.

![image](https://user-images.githubusercontent.com/85411047/205678133-c343e56e-b57d-415f-a931-9d284b13c334.png)

### __System details__

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.3.0

**Comment by rashil2000** [comment]
This seems to be an internet connection issue. What's the output of `irm google.com`?
