### ISSUE TITLE
[Bug] Unclear Documentation: scoop update before update * ?

### ISSUE THREAD

**Issue by falco467** [lukesampson/scoop#5289]
#### Current Behavior
The documentation is not absolutely clear if `scoop update *` will be enough to keep all my apps (including scoop) up to date, or if I regularly have to run `scoop update` too.

#### Expected Behavior
I would like for `scoop update *` to be everything I need to run regularly. Or if this is not enough maybe an argument which will execute the additional steps of `scoop update` before `update *` if needed.

#### Additional context/output
I've read in multiple discussions people being unsure if `scoop update *` is enough. So the documentation should be absolutely clear if/when `scoop update` is additionally needed.

#### Possible Solution
Best solution `scoop update *` is enough and amend the documentation to clearly state this.
If there is a reason this should not be the default, maybe provide an argument like `scoop update * --update-scoop` so we have a single command.

If this is also not possible at least amend the documentation with a clear warning about `update *` not updating scoop and `scoop update` always being needed additionally.

**Comment by rashil2000** [comment]
Running `scoop update *` should be enough. 

Could you point out where the documentation is unclear?
