### ISSUE TITLE
scoop install maven failed (3.3.3)

### ISSUE THREAD

**Issue by mathieucarbou** [lukesampson/scoop#530]
```
PS C:\Users\mathieu> scoop uninstall maven
uninstalling maven (3.3.3)
maven was uninstalled
PS C:\Users\mathieu> scoop install maven
installing maven (3.3.3)
downloading http://mirror.rackcentral.com.au/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.zip...Unable to
connect to the remote server
```

**Comment by tomahawk69** [comment]
I get "404 error https://www.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip is not valid" when trying to install maven - url is obviously wrong.

**Comment by linsui** [comment]
@tomahawk69 It's an upstream problem. Maven is updated to 3.6.2 and 3.6.1 is removed, but the version on homepage is still 3.6.1.

**Comment by tomahawk69** [comment]
> @tomahawk69 It's an upstream problem. Maven is updated to 3.6.2 and 3.6.1 is removed, but the version on homepage is still 3.6.1.

Yeah, I see, the same problem with their download page (https://maven.apache.org/download.cgi).
It's slightly confused the maven is in the list of installed application in Scoop, I supposed the download error should stop the installation, isn't?

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/issues/3580 . You need to uninstall it manully before reinstall.
