### ISSUE TITLE
Install specific version

### ISSUE THREAD

**Issue by vpratfr** [lukesampson/scoop#538]
Hi,

I ran `scoop install rsync` which install version 3.1.1. On my servers running under Debian stable, I have rsync 3.0.9 (latest available there) which has a compatibility issue with 3.1.1. 

How can I install 3.0.9 on my local computer ? Is there something like `scoop install rsync@3.0.9`?

**Comment by deevus** [comment]
Hi @vpratfr 

There is not currently any way to install a specific version of a manifest in scoop. The current closest solution is to have a manifest specifically for that version. E.g. manifests for `git` and `git19`

You could create a `rsync30` manifest in this case to solve your problem

**Comment by deevus** [comment]
@vpratfr Did you end up resolving your issue?

**Comment by vpratfr** [comment]
I did that manually. I still think there should be a way to specify a version number for a package, this would be helpful to solve cases like that.
