### ISSUE TITLE
Replace "~" with "$env:USERPROFILE"

### ISSUE THREAD

**Issue by jlchoike** [lukesampson/scoop#545]
The Active Directory policy for my user account automatically sets my user home to a network drive; so scoop installs to the network drive instead of my local user home. Is it possible to use $env:USERPROFILE instead of ~ core.ps1 when setting scoopdir?

Please let me know so I can use scoop at work, because this package installer will be a great help to my team. Thanks!

**Comment by lukesampson** [comment]
You can set `$env:SCOOP` to change the install directory to something other than `~/appdata/local/scoop`. To make the change persist beyond the current session, use:

```powershell
[environment]::setEnvironmentVariable('SCOOP','C:\custom\path\scoop','User')
```

See also #427 and #249.

**Comment by jlchoike** [comment]
Wow. Thanks for the prompt reply and suggestion!

**Comment by lukesampson** [comment]
You're welcome :smile:
