### ISSUE TITLE
Trouble installing scoop

### ISSUE THREAD

**Issue by nicohvi** [lukesampson/scoop#549]
Whenever I try to run the installer this happens:

![scoop](https://cloud.githubusercontent.com/assets/430875/10882507/9d35b198-816b-11e5-9033-f2f1182543e0.png)

But when I try to run `scoop` it isn't recognised.

![scoop2](https://cloud.githubusercontent.com/assets/430875/10882520/beb5595e-816b-11e5-9825-ef4402d01ea2.png)

Any idea of how to fix this?

**Comment by lukesampson** [comment]
If you remove the scoop directory you should be able to reinstall: `rm -r -fo ~/appdata/local/scoop`.

**Comment by nicohvi** [comment]
That did the trick, thanks! :+1:
