### ISSUE TITLE
git hash check failed (hence, can't update scoop)

### ISSUE THREAD

**Issue by gxcodes** [lukesampson/scoop#558]
λ scoop install git
installing git (2.6.1.windows.1)
downloading https://github.com/git-for-windows/git/releases/download/v2.6.1.windows.1/PortableGit-2.6.1-64-bit.7z.exe#/dl.7z...done
checking hash...hash check failed for https://github.com/git-for-windows/git/releases/download/v2.6.1.windows.1/PortableGit-2.6.1-64-bit.7z.exe#/dl.7z. expected: 4e1d75f04d080cba8e798806f0c01f80a5c421445ab9d10c517e5f6dae702543, actual: 5118b86924fd586caa1f31ebda2d71ed4f7c18ba6c0df4a71f06b90d625837e8!

**Comment by Cyianor** [comment]
This is not relevant anymore. Could be closed.

**Comment by lukesampson** [comment]
Thanks @Cyianor, closing.
