### ISSUE TITLE
[BUG] Downloads via aria2 continue to fail

### ISSUE THREAD

**Issue by alliter8** [lukesampson/scoop#5584]
I receive the following error no matter what I try to install; installing without aria2 enabled works.

```
NativeCommandExitException: Program "aria2c.exe" ended with non-zero exit code: 1.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/ScoopInstaller/Binary/master/unzip/unz600xn.exe#/dl.7z
    referer=https://raw.githubusercontent.com/ScoopInstaller/Binary/master/unzip/unz600xn.exe#/
    dir=C:\Users\%USERNAME%/scoop\cache
    out=unzip#6.00#https_raw.githubusercontent.com_ScoopInstaller_Binary_master_unzip_unz600xn.exe_dl.7z

ERROR & 'C:\Users\%USERNAME%/scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\%USERNAME%\scoop\cache\unzip.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10264 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=unzip%406.00%3a+download+via+aria2+failed
```

I have tried 10 random installations this morning, and have tried at least 2 a day for the past 3 weeks. I have reviewed the past issues, but none of the recommendations has changed the result--except disabling aria, of course.

**Comment by mwisnicki** [comment]
I keep having this randomly.

**Comment by vladimir-light** [comment]
For several days, I could'n update/install some apps. Apparently it was an expired GitHub token.
Run `scoop config` and look for `gh_token`
I generated a new one (github -> settings -> developer settings -> personal access tokens -> fine grained tokens) and set it up.

`scoop config gh_token <new_token>`

**Comment by mwisnicki** [comment]
I don't have it set as scoop installation instructions do not mention it

**Comment by HUMORCE** [comment]
> I don't have it set as scoop installation instructions do not mention it

You don't need to set it, just turn off aria2 for Scoop: `scoop config aria2-enabled false`
