### ISSUE TITLE
[Bug] scoop install/update breaks on a cosmetic error message (gsudo)

### ISSUE THREAD

**Issue by yonizaf** [lukesampson/scoop#5597]
## Bug Report
While installing or updating gsudo as global install, an error message is shown:
`Installing PowerShell modules globally is not implemented!`
This is fine. it's a cosmetic message (or should be) and does not affect the use of gsudo.
However, the scoop install script dies at this point, leaving a partial 'failed' install, and does not continue to install/update further packages (requested by the same command).

**_This is not a gsudo-specific issue._** I opened an issue in the main bucket repo (https://github.com/ScoopInstaller/Main/issues/4989), it was closed and I was directed to open one here.

#### Current Behavior
Run `scoop install -g gsudo something somethingelse`. 
gsudo is installed correctly, however scoop lists it as failed install.
furthermore, scoop does not try to install `something` and  `somethingelse`. The install script simply dies silently.

#### Expected Behavior
1. Ignore unimportant error messages and finalize install of gsudo.
2. move forward to update the next package even if one package update failed.

#### Additional context/output

```
> scoop status
Scoop is up to date.

Name           Installed Version Latest Version Missing Dependencies Info
----           ----------------- -------------- -------------------- ----
gsudo          2.0.4             2.3.0
mingit-busybox 2.39.1.windows.1  2.41.0.3

> scoop update -g *
gsudo: 2.0.4 -> 2.3.0 (global)
mingit-busybox: 2.39.1.windows.1 -> 2.41.0.3 (global)
Updating 2 outdated apps:
Updating 'gsudo' (2.0.4 -> 2.3.0)
Downloading new version
gsudo.setup.x64.msi (2.2 MB) [================================================================================] 100%
Checking hash of gsudo.setup.x64.msi ... ok.
Uninstalling 'gsudo' (2.0.4)
Removing shim 'sudo.shim'.
Removing shim 'sudo.exe'.
Unlinking C:\ProgramData\scoop\apps\gsudo\current
Installing 'gsudo' (2.3.0) [64bit] from main bucket
Loading gsudo.setup.x64.msi from cache
Extracting gsudo.setup.x64.msi ... done.
Linking C:\ProgramData\scoop\apps\gsudo\current => C:\ProgramData\scoop\apps\gsudo\2.3.0
Creating shim for 'sudo'.
Installing PowerShell modules globally is not implemented!

> scoop status
Scoop is up to date.

Name           Installed Version Latest Version Missing Dependencies Info
----           ----------------- -------------- -------------------- ----
gsudo          2.0.4             2.3.0
mingit-busybox 2.39.1.windows.1  2.41.0.3

> gsudo -V
gsudo v2.3.0 (Branch.tags-v2.3.0.Sha.c7c3c9380a70bd004c4a3bebe9f54b86d836afbd)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
```

### System details

**Windows version:** 10, 11 (tested on both)

**OS architecture:** 64bit

**PowerShell version:** 7.2.13

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2023-07-27T12:38:48.0797343+03:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by Lutra-Fs** [comment]
Maybe #4135 could help on the issue that updates has been blocked?

**Comment by rashil2000** [comment]
Installing global PSModules is tracked here: #5601 
Continuing after a failed installation is tracked here: #4135
