### ISSUE TITLE
Remove powershell alias in curl package

### ISSUE THREAD

**Issue by chaliy** [lukesampson/scoop#56]
When install `curl` on powershell4, `curl` will be still aliased to `Invoke-WebRequest`. To overcome this curl package should probably remove alias after installation, something like this:

```
rm alias:curl 
```

**Comment by johnnyoshika** [comment]
To automatically remove the `curl` alias every time PowerShell starts, you'll need to update your profile:
  * Check if PowerShell profile exists: `test-path $profile`
  * Create profile if one doesn't exist: `new-item $profile`
  * Edit the profile: `notepad $profile`
  * Add the following like: `remove-item alias:curl`
  * Apply the new profile: `. $profile`

**Comment by earik87** [comment]
> `new-item $profile` did not work for me. 
This one worked instead; `New-Item –Path $Profile –Type File –Force`
