### ISSUE TITLE
Bucket priorities

### ISSUE THREAD

**Issue by eugenesvk** [lukesampson/scoop#565]
Is it possible to prioritize my own bucket over the default one?
The default bucket didn't have the latest version of the app that I needed (some useful function was introduced, so I wanted to update), so I've copied that `app.json` from default bucket to my own, changed the installation url, version and hash.
However, when I try to `scoop install app` only the default bucket is used, not mine.
Ideally scoop should alert me of a conflict (like it shows that an app is available in several buckets on `scoop search app`) and let me choose.
I know I can install the app directly by `scoop install /path/to/app.json`, but it's not as convenient and also I only managed to find it out by accident when searching whether someone had a similar issue :).
Thanks

**Comment by lukesampson** [comment]
There's no bucket prioritisation.

The idea is to encourage people to contribute improved manifests back to the main bucket. If you don't want to contribute, you can name your manifest something else like `my-app.json` instead of `app.json`.

**Comment by eugenesvk** [comment]
I'm fine with contributing, just didn't know how to do it (new to github). Will try to click around to see how it works.
Renaming manifest isn't great since it also renames the app installation folder (it doesn't matter much since I can always `scoop list` to see which apps have changed names, but it's a bit inconvenient).
