### ISSUE TITLE
Ansible support

### ISSUE THREAD

**Issue by mmarodin** [lukesampson/scoop#583]
Anyone is able to run Ansible from scoop?
I've tried many ways but it doesn't work :(

File "c:\Users\******\AppData\Local\scoop\apps\python27\2.7.10\Scripts
\ansible.py", line 36, in <module>
ImportError: No module named runner

Please let me know, thanks

**Comment by kodybrown** [comment]
As far as I know, Ansible does not support _running_ from Windows machines. Only targeting them. See [here][1] for more details.

[1] http://docs.ansible.com/ansible/intro_windows.html#windows-how-does-it-work

**Comment by kodybrown** [comment]
As a side note, I really like how Ansible is designed. I really wish it did allow managing from Windows...

**Comment by mmarodin** [comment]
Yes, I know it. And yes, me too, I really like Ansible.
But the error seems to be the same than other users having it in some Linux cases ... so ... let's try again!
Have you ever try to install it via Scoop (python and pip)?

**Comment by kodybrown** [comment]
I have installed Python and pip many times via Scoop. I actually have multiple versions of Python installed at the same time, all via Scoop. I haven't experienced any issues..

**Comment by mmarodin** [comment]
If you have time could you try to test Ansible yourself? :)

**Comment by kodybrown** [comment]
It says it installed successfully, but **it will not work** on Windows (http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements)...

> As a side note: The Ansible program is _not_ needed in order to manage a Windows machine. The Ansible program is only needed on the control machine - and that is not supported by Ansible. The Ansible server, when run from a Linux machine, uses PowerShell to remotely manage Windows computers. Nothing is required on those Windows machines.


The `pwd` component is not supported on Windows. There are some hacks out there, but nothing that I've found gets an Ansible control machine to work on Windows.

I used a clean environment for the install.

    >scoop install python27
    >set "PYTHONHOME=C:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10"
    >set "PYTHONPATH=C:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\Lib"
    >set "PYTHONSCRIPTS=C:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\Scripts"
    
    >python --version
    Python 2.7.10
    
    >pip --version
    pip 7.0.1 from C:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\lib\site-packages (python 2.7)
    
    >easy_install http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py2.7.exe
    Downloading http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py2.7.exe
    Processing pycrypto-2.6.1.win32-py2.7.exe
    creating 'c:\users\kodyb\appdata\local\temp\easy_install-si9gky\pycrypto-2.6.1-py2.7-win-amd64.egg' and adding 'c:\users\kodyb\appdata\local\temp\easy_install-si9gky\pycrypto-2.6.1-py2.7-win-amd64.egg.tmp' to it
    Moving pycrypto-2.6.1-py2.7-win-amd64.egg to c:\users\kodyb\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages
    Adding pycrypto 2.6.1 to easy-install.pth file
    
    Installed c:\users\kodyb\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages\pycrypto-2.6.1-py2.7-win-amd64.egg
    Processing dependencies for pycrypto==2.6.1
    Finished processing dependencies for pycrypto==2.6.1
    
    >pip install ansible
    Collecting ansible
      Downloading ansible-1.9.4.tar.gz (937kB)
        100% |################################| 937kB 288kB/s
    Collecting paramiko (from ansible)
      Downloading paramiko-1.16.0-py2.py3-none-any.whl (169kB)
        100% |################################| 172kB 871kB/s
    Collecting jinja2 (from ansible)
      Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
        100% |################################| 266kB 409kB/s
    Collecting PyYAML (from ansible)
      Downloading PyYAML-3.11.tar.gz (248kB)
        100% |################################| 249kB 322kB/s
    Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\users\kodyb\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages (from ansible)
    Collecting pycrypto>=2.6 (from ansible)
      Downloading pycrypto-2.6.1.tar.gz (446kB)
        100% |################################| 446kB 512kB/s
    Collecting ecdsa>=0.11 (from paramiko->ansible)
      Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
        100% |################################| 90kB 1.4MB/s
    Collecting MarkupSafe (from jinja2->ansible)
      Downloading MarkupSafe-0.23.tar.gz
    Installing collected packages: paramiko, MarkupSafe, jinja2, PyYAML, ansible
      Running setup.py install for MarkupSafe
      Running setup.py install for PyYAML
      Running setup.py install for ansible
    Successfully installed MarkupSafe-0.23 PyYAML-3.11 ansible-1.9.4 jinja2-2.8 paramiko-1.16.0
    
    >python "c:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\Scripts\ansible"
    Traceback (most recent call last):
      File "c:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\Scripts\ansible", line 36, in <module>
        from ansible.runner import Runner
      File "C:\Users\kodyb\AppData\Local\scoop\apps\python27\2.7.10\lib\site-packages\ansible\runner\__init__.py", line 21, in <module>
        import pwd
    ImportError: No module named pwd

**Comment by kodybrown** [comment]
If you really have to have Ansible on Windows, I suggest a virtual machine using VMware or VirtualBox. You could probably also find a Docker image for Ansible, but I haven't played with Docker yet, so I can't help you with that.

**Comment by mohamadathaider** [comment]
> I have installed Python and pip many times via Scoop. I actually have multiple versions of Python installed at the same time, all via Scoop. I haven't experienced any issues..

Hi maybe too too late '' Did you used venv pythonx-venv?
I think the problems and issues will show up after time, thats why venv
