### ISSUE TITLE
Vim with Python Support

### ISSUE THREAD

**Issue by zQueal** [lukesampson/scoop#591]
I was really excited to find scoop, but when I installed Vim, I realized that the binary is compiled _without_ Python 2 or 3 support. That's a little unusual considering all the best plugins require Python support.

Is there any way to get a binary which supports Python?

**Comment by lukesampson** [comment]
If you know where to download a vim binary that supports Python we could use that. Scoop doesn't compile anything as part of the install process.

**Comment by zQueal** [comment]
I do have a good binary which is very up-to-date, but unfortunately it's 64-bit and doesn't seem to want to play nicely with Python. It can be [found here](https://bintray.com/veegee/generic/vim_x64/view). I'll update once I find a more trusted version of the 32-bit client.

**Comment by deevus** [comment]
@zQueal Have you had any luck finding a working binary with Python support?

**Comment by zQueal** [comment]
Yes, I have actually. It was a __huge__ pain in the ass to be perfectly honest. Most of the precompiled binaries out there are either insanely out of date or for whatever reason didn't want to work. In the end I ended up installing 32-bit Python 2.7, manually adding `PYTHONHOME` to my python install directory (`C:\Python27`), and then [this 32-bit build](http://wyw.dcweb.cn/#download) of Vim 7.4.

All in all, after getting everything working with Ruby support, and [plug-vim](junegunn/vim-plug), I couldn't be happier. I just wish the setup was quite a bit easier.

**Comment by deevus** [comment]
Do you know if Python27 in Scoop would work for that version of vim? Could we do it in a manifest?

**Comment by zQueal** [comment]
I'm not sure -- but I'll test it tomorrow afternoon and get back to you if you're interested. I'm almost positive it'll work if you add `C:\Users\{user}\AppData\Local\scoop\shims\python27\whatever` to `$PATH` as `PYTHONHOME`.

**Comment by zQueal** [comment]
Took forever, but it's tested and working out of the box. `PYTHONHOME` needs to be set as an environment variable to the scoop app location for Vim to recognize it as installed, however.

**Comment by zQueal** [comment]
> Do you know if Python27 in Scoop would work for that version of vim? Could we do it in a manifest?

I did have this working at one point. `PYTHON_HOME` needs to be set to the `/app` directory for Python. However, for whatever reason you __cannot__ use the current version of Python 2.7 (`2.7.11`). It doesn't play well with Vim for some reason. Vim will reply that Python is installed and configured, but none of the plugins will work correct. To fix this, you __must__ install Python 2.7.10.

**Comment by deevus** [comment]
We can add Python2710 to the versions bucket. Would that work?

**Comment by zQueal** [comment]
It certainly would! That and a Vim x86 and x64 with built in Python support and I'll be a happy camper!

**Comment by deevus** [comment]
If you can do the PR I'll happily merge it in. Does the Vim with Python support function without Python? 

I suppose the question is can we replace the vim manifest in the main bucket with it, and not lose anything for those who don't care about using Python?

**Comment by zQueal** [comment]
> Does the Vim with Python support function without Python?

Yup! The Vim binary just has to be compiled with Python support to work with installed versions of Python. If compiled without Python support, like the one currently being served by Scoop, obviously it won't. So really only positive changes -- the only thing I can think of that would be a negative is a marginally larger filesize. Maybe a couple KB.

I'll do a PR as soon as I can.

**Comment by leafgarland** [comment]
Regarding vim build sources, I've been happily using builds from [here](https://tuxproject.de/projects/vim/). 32bit and 64bit builds that are updated automatically.

**Comment by zQueal** [comment]
@leafgarland those look great! Thanks!

**Comment by leafgarland** [comment]
And now there are 'official' nightly vim builds too

https://github.com/vim/vim-win32-installer/releases
