### ISSUE TITLE
PHP install not registering

### ISSUE THREAD

**Issue by wrokred** [lukesampson/scoop#594]
On a fresh install of windows 10 pro installing any version of php with scoop creates an alias for php but doesn't have any output.

For instance calling php -version just goes to the next line. Before install php will error.

Tried the 64 and 32. 7 and 5.6 versions. Run scoop update, removed scoop and reinstalled each app.

**Comment by ntwb** [comment]
Do the the shims get created in `C:\Users\%username%\AppData\Local\scoop\shims`?

You should be seeing two files relating to PHP: `php.exe` and `php.ps1`

Also whats the results of `scoop which php`?

Both `scoop install php56` and `scoop install php` work fine for me, you should also use `php -v` or `php --version` to list PHP's version.

**Comment by wrokred** [comment]
Yeah, I have both the files in the shims folder.

'''scoop which php''' '''~\appdata\local\scoop\apps\php56\5.6.16\php.exe'''

It's damned confusing.

**Comment by wrokred** [comment]
Fresh install was the clue, first time installing scoop on a new install. Opening command prompt instead of powershell and running ```php``` showed the error.
```MSVCR110.dll is missing from your computer```

http://www.microsoft.com/en-us/download/details.aspx?id=30679 to install Visual C++ Redistributable for Visual Studio 2012 Update 4 fixed that.

Silly thing to over look but I'll close the issue and keep the solution just in case.

**Comment by ntwb** [comment]
:+1 Glad your sorted
