### ISSUE TITLE
App manifest depends wildcard?

### ISSUE THREAD

**Issue by wrokred** [lukesampson/scoop#597]
Currently building a bucket for php package managers and CLIs, composer and the like.
The install of composer requires php, but doesn't care which version.

Depends `php` will try to install php 7 even if 56 is installed.
Depends `php56` with try to install php56 even if 7 is installed.
Or other situations were you require any version of X app.

Is there a wildcard or depends X or Y?
"depends": ["php*"]
"depends": ["php[0-2]"]
"depends": ["php => 56"]
"depends": [["php","php56"]]

**Comment by deevus** [comment]
There isn't, but you can use the `pre_install` field in the manifest to achieve the same thing. Use straight powershell to check if any versions are installed with scoop.
