### ISSUE TITLE
Question mark (?) in download URL

### ISSUE THREAD

**Issue by Cyianor** [lukesampson/scoop#603]
I wanted to create a manifest for the [DLC](http://dlcplayer.jimdo.com/) command line music player. The download link for this app is

    https://dl.dropbox.com/s/9p5sja609mkw8vs/dlcplayer-win_0.0.3.7z?dl=1

when running the manifest with this URL I get

    downloading https://dl.dropbox.com/s/9p5sja609mkw8vs/dlcplayer-win_0.0.3.7z?dl=1...done
    cp : Illegal characters in path.
    At C:\Users\Name\appdata\local\scoop\apps\scoop\current\lib\install.ps1:108 char:5
    +    cp $cached $to
    +     ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], ArgumentException
    + FullyQualifiedErrorId :    
            System.ArgumentException,Microsoft.PowerShell.Commands.CopyItemCommand

If I look inte scoop's cache folder there is no downloaded file at all. So my guess is that the problem is not necessarily the copying but that scoop does not download the file at all. 

This is the manifest file I am using right now.

```json
{
    "homepage": "http://dlcplayer.jimdo.com/",
    "version": "0.0.3",
    "url": "https://dl.dropbox.com/s/9p5sja609mkw8vs/dlcplayer-win_0.0.3.7z?dl=1",
    "hash": "154d7dd38f4cece1fef3585f80b21ee584d5377bc172aaa9e12d8f6dbcfe6413",
    "bin": "dlc.exe"
}
```

Weirdly enough if I ran the dl_progress function on its own it works great.

**Comment by Cyianor** [comment]
No wait... I am wrong. The `?` does get replaced. Weirdly enough it still doesn't download the file though...

**Comment by Cyianor** [comment]
Found it! The line

```powershell
$fname = (split-path $url -leaf)
```

in `install.ps1` in the `dl_urls` function extracts `dlcplayer-win_0.0.3.7z?dl=1` instead of `dlcplayer-win_0.0.3.7z`. To make it work I changed this line to

```powershell
$fname = (split-path $url -leaf).split('?')[0]
```

Is this a feasible solution?

**Comment by lukesampson** [comment]
Cool, yes that sounds like it would work—are you able to submit a pull request?

If so, can you please test as many manifests as possible to make sure there aren't unexpected side effects? There are some manifests that add URL fragments like `#/dl.7z` (e.g. [git](https://github.com/lukesampson/scoop/blob/master/bucket/git.json)) to force a different filename when the URL is downloaded.

**Comment by deevus** [comment]
@Cyianor Are you making a PR for this?

**Comment by rivy** [comment]
@deevus I think that using `[System.URI]` here (in the PR) is a better future-proof solution.
