### ISSUE TITLE
Failing automated testing (fixed by PR#604)

### ISSUE THREAD

**Issue by rivy** [lukesampson/scoop#605]
I noticed that you had some failing automated AppVeyor builds.

There was a regression in `pester` (see [pester@3.3.12 ~ `mock` regression?](https://github.com/pester/Pester/issues/436)) which is being fixed and pushed. But, in the meantime, builds using the usual method of testing are failing.

I've fixed it in my fork and created a PR (see [PR#604](https://github.com/lukesampson/scoop/pull/604)) to help fix it here... Instructions for use are in the commit message.

**Comment by lukesampson** [comment]
Looks like that worked—thanks Roy :+1:
