### ISSUE TITLE
Attempting re-install breaks the installation

### ISSUE THREAD

**Issue by pe8ter** [lukesampson/scoop#609]
Tried reinstalling Scoop by executing the first-time install command. Doing this makes Scoop unavailable to use.

```powershell
PS C:\> iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
initializing...
scoop is already installed. run 'scoop update' to get the latest version.

PS C:\> scoop help
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, ...
```

Manually deleting Scoop and from `appdata\local` allows me to reinstall using `iex` again, but using Scoop remains unavailable.

**Comment by deevus** [comment]
@pe8ter Have you been able to resolve this? Seems like it could be a `PATH` issue

**Comment by pe8ter** [comment]
I didn't know there was issues with Scoop and how some businesses configure their machines. Tried installing off of my work network, which led to a new error, which led to [this ticket](https://github.com/lukesampson/scoop/issues/107), which fixed my issue!

**Comment by pe8ter** [comment]
Apps are getting installed to my C drive, but still getting issues with Scoop trying to hit the U drive, but looks like that's on me to fix.

Feel free to close.

**Comment by deevus** [comment]
Ok @pe8ter. Thanks
