### ISSUE TITLE
这个环境变量太长的问题准备怎么解决

### ISSUE THREAD

**Issue by zcg** [lukesampson/scoop#6100]
![Clip_2024-08-13_14-43-58](https://github.com/user-attachments/assets/15365432-87b2-41fb-b1b4-2af5fa33e01b)

**Comment by HUMORCE** [comment]
Execute `scoop checkup`, it contains a LongPaths support check, and workaround attached there.

https://github.com/ScoopInstaller/Scoop/blob/859d1db51bcc840903d5280567846ae2f7207ca2/lib/diagnostic.ps1#L40-L55
