### ISSUE TITLE
After scoop install failing it needs to uninstall the package

### ISSUE THREAD

**Issue by fremail** [lukesampson/scoop#629]
Hi!

I tried the example from the doc:
```scoop install apache```
but got an error (404). Then I tried to install it again, but got another error: ... try scoop uninstall apache. It will be better no need to uninstall the package after failed installing.

Also, scoop can't install apache :(

The screenshot: 
https://yadi.sk/i/PGut8znRmp2Vw

**Comment by saildata** [comment]
@fremail We've all had this happen before, bad ref, checksum, etc. To keep I/O to a minimum Scoop uses a cache folder. From the [Scoop wiki](https://github.com/lukesampson/scoop/wiki/Commands):
* `scoop help cache` -> overview of the cache syntax

* `scoop cache show` ->cache disk usage 

* `scoop cache rm <app>` -> delete a single app

* `scoop cache rm *` -> clear the cache (Arguably you wouldn't use a glob by itself - safer to just use Explorer and delete *just in case* the ps1 script ever changes. I don't think the glob/wildcard is documented in Scoop, @lukesampson feel correct me if it is officially supported or if I've just been lucky all this time :stuck_out_tongue_winking_eye:

**Comment by fremail** [comment]
@saildata So I removed the apache from scoop's cache and tried to install the apache again, but got an 404 error.
```PS C:\Users\antond> scoop cache show

  1.6 MB 7zip (15.10)                                                               http_www.7-zip.org_a_7z1510-x64.msi
     0 B apache (2.4.17)              ...w.apachelounge.com_download_VC11_binaries_httpd-2.4.17-win32-VC11.zip.download
  3.9 MB curl (7.45.0)                                           http_www.confusedbycode.com_curl_curl-7.45.0-win64.zip
441.2 KB grep (2.5.4)                       http_ufpr.dl.sourceforge.net_project_gnuwin32_grep_2.5.4_grep-2.5.4-bin.zip
877.2 KB grep (2.5.4)                       http_ufpr.dl.sourceforge.net_project_gnuwin32_grep_2.5.4_grep-2.5.4-dep.zip
610.1 KB openssh (5.4p1-1)            ...w_MSYS_Base_msys-core_msys-1.0.13-2_msysCORE-1.0.13-2-msys-1.0.13-bin.tar.lzma
 11.4 KB openssh (5.4p1-1)            ...xtension_minires_minires-1.02_1-2_libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma
274.7 KB openssh (5.4p1-1)            ...SYS_Extension_openssh_openssh-5.4p1-1_openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma
  4.8 KB openssh (5.4p1-1)            ...SYS_Extension_openssh_openssh-5.4p1-1_openssh-5.4p1-1-msys-1.0.13-lic.tar.lzma
654.9 KB openssh (5.4p1-1)            ...ension_openssl_openssl-1.0.0-1_libopenssl-1.0.0-1-msys-1.0.13-dll-100.tar.lzma
 36.7 KB openssh (5.4p1-1)            ...t_mingw_MSYS_Extension_zlib_zlib-1.2.3-2_zlib-1.2.3-2-msys-1.0.13-dll.tar.lzma
 22.7 MB php (7.0.1)                               http_windows.php.net_downloads_releases_php-7.0.1-Win32-VC14-x64.zip
 16.4 MB php53 (5.3.29)                   http_windows.php.net_downloads_releases_archives_php-5.3.29-Win32-VC9-x86.zip
 18.9 MB php55 (5.5.30)                           http_windows.php.net_downloads_releases_php-5.5.30-Win32-VC11-x86.zip
 21.7 MB php56 (5.6.16)                           http_windows.php.net_downloads_releases_php-5.6.16-Win32-VC11-x64.zip


total: 15 files, 88.0 MB
PS C:\Users\antond> scoop cache rm apache
PS C:\Users\antond> scoop install apache
installing apache (2.4.17)
downloading https://www.apachelounge.com/download/VC11/binaries/httpd-2.4.17-win32-VC11.zip...The remote server returned an error: (404) Not Found.```

Did I do something wrong?

**Comment by fremail** [comment]
Oh! I needed to update the scoop before. So, the apache was installed.
@saildata, thank you.

**Comment by saildata** [comment]
@fremail - glad it worked out. Out of (sheer) laziness I have scoop aliased to `s` so when I boot up I `s update` ;`su` would have felt wrong.. This project is just about the only thing that makes working in Windows bearable for a Linux user :trophy: @lukesampson

**Comment by fremail** [comment]
@lukesampson scoop is a cool app, but I think it should store data about packages on github for example. Then it would be faster to update it (don't need to update scoop on each computer). 
Though it would be more better to parse download links automatically, but it can cause other bugs.
