### ISSUE TITLE
infinite loop when searching for notepad++

### ISSUE THREAD

**Issue by saildata** [lukesampson/scoop#634]
```
parsing "notepad++" - Nested quantifier +.
At scoop\apps\scoop\current\libexec\scoop-search.ps1:22 char:12
+         if($alias -match $query) { return $alias }
+            ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
```
You can also invoke the loop with `scoop search ++` for obvious reasons but oddly not `s search --`

It looks like the `-match` operator is used in several user commands in **[scoop](https://github.com/lukesampson/scoop/search?utf8=%E2%9C%93&q=match)**

Maybe a edge case since npp is literally the only returned app with plus in the name. The standard `CTRL + c` (lowercase only) issues a break signal in case someone blindly types this in...

**Comment by lukesampson** [comment]
I could have escaped the search term, but I think it's kind of cool if people can use regex to search. So instead I decided to pre-parse the regular expression and show one error, rather than have an error each time it searches an app's name.

```powershell
$ scoop search notepad++
invalid regular expression: parsing "notepad++" - Nested quantifier +.
$ scoop search notepad\+\+
extras bucket:
  notepadplusplus (6.6.9) --> includes 'notepad++.exe'
```
