### ISSUE TITLE
New OpenSSH 7.1p1 does not work in PowerShell

### ISSUE THREAD

**Issue by thomaskonrad** [lukesampson/scoop#638]
Hi,

I just upgraded OpenSSH because of the latest vulnerability. On my machine, SSH now does not work any more in PowerShell. When I try to open a connection, it just quits without any output:

```
~ $ ssh myserver.local
~ $
```

However, SSH works in the old `cmd.exe` command shell. Does anybody experience the same thing? I'm using Windows 10.

Thanks
Thomas

**Comment by lukesampson** [comment]
I've moved openssh back to the old 5.4p1-1 version for now. You'll need to run `scoop uninstall openssh; scoop update; scoop install openssh` to go back because `scoop update openssh` won't work for an older version than the one you have installed.

**Comment by r2qokk** [comment]
I would love to use ssh with ed25519 rather than rsa for better security and faster generation speed, but ssh begins to support this type of key since v6.4.
I tried `scoop uninstall openssh; scoop update; scoop install openssh` as suggested, but I still got old 5.4p1-1.
Any other suggestion?

**Comment by lukesampson** [comment]
You might want to try `scoop install git-with-openssh`. I'm not sure about ed25519 support, but it's a much newer version of OpenSSH.

```powershell
$ ssh -V
OpenSSH_7.3p1, OpenSSL 1.0.2h  3 May 2016
```

**Comment by r2qokk** [comment]
Thanks. I have ``ssh`` with version number 7.3p1 and ed25519 key working.
But there is no ``ssh-add``, and other friends for me.

```powershell
installing git-with-openssh (2.10.0.windows.1)
downloading https://github.com/git-for-windows/git/releases/download/v2.10.0.windows.1/PortableGit-2.10.0-64-bit.7z.exe#/dl.7z...(29.4 MB) done
checking hash...ok
extracting...done
creating shim for git
creating shim for gitk
creating shim for git-gui
creating shim for ssh
creating shim for sshd
creating shim for scp
creating shim for sftp
creating shim for slogin
can't shim usr\bin\slogin.exe: file doesn't exist
```

Is there any other information I need to provide?

**Comment by lukesampson** [comment]
That missing slogin.exe was causing `ssh-add` etc not to be linked in correctly. I've fixed that now.

You need to run `scoop update;scoop uninstall git-with-openssh;scoop install git-with-openssh` to get the fix.

**Comment by r2qokk** [comment]
Still failed.
How can I make sure I have got the latest ``scoop`` bucket file?

```powershell
~ $ scoop update;scoop uninstall git-with-openssh;scoop install git-with-openssh
updating scoop...
scoop was updated successfully!
uninstalling git-with-openssh (2.10.0.windows.1)
git-with-openssh was uninstalled
installing git-with-openssh (2.10.0.windows.1)
loading https://github.com/git-for-windows/git/releases/download/v2.10.0.windows.1/PortableGit-2.10.0-64-bit.7z.exe#/dl.7z from cache...
checking hash...ok
extracting...done
creating shim for git
creating shim for gitk
creating shim for git-gui
creating shim for ssh
creating shim for sshd
creating shim for scp
creating shim for sftp
creating shim for slogin
can't shim usr\bin\slogin.exe: file doesn't exist
```

**Comment by deevus** [comment]
`scoop update`

**Comment by lukesampson** [comment]
If you've updated, the manifest should be at `~/appdata/local/scoop/apps/scoop/current/bucket/git-with-openssh.json`, and it shouldn't mention slogin.exe.

**Comment by r2qokk** [comment]
Works now.
Thanks for the lighting-fast response.

**Comment by rasa** [comment]
This issue appears to have been resolved. If not, please reopen this ticket, or let us know. Thanks!
