### ISSUE TITLE
Install php<7 (5.6.15, 5.6.16)

### ISSUE THREAD

**Issue by WRedMedia** [lukesampson/scoop#641]
downloading http://windows.php.net/downloads/releases/php-5.6.15-nts-Win32-VC11-x64.zip...Удаленный сервер возвратил ошибку: (404) Не найден.

**Comment by zQueal** [comment]
`5.6.15` has been replaced by `5.6.17`

    http://windows.php.net/downloads/releases/php-5.6.17-Win32-VC11-x86.zip
    http://windows.php.net/downloads/releases/php-5.6.17-Win32-VC11-x64.zip

But `5.6.15` can still be found in `releases/archives/`

    http://windows.php.net/downloads/releases/archives/php-5.6.15-Win32-VC11-x86.zip
    http://windows.php.net/downloads/releases/archives/php-5.6.15-Win32-VC11-x64.zip

**Comment by MPLew-is** [comment]
I realize this is an an old thread, but the previous minor releases of PHP (5.4, 5.5, 5.6 currently) are available in the [versions bucket](https://github.com/scoopinstaller/versions), which you can add to scoop with: `scoop bucket add versions`. You'll then be able to install `php54`, `php55`, and `php56` (as well as `php70` if you're interested in using 7.0 long-term). Those apps will always be updated to the newest patch releases, but they provide support for installing older versions.
