### ISSUE TITLE
Apache / Apachex64 Returns Error 404.

### ISSUE THREAD

**Issue by zQueal** [lukesampson/scoop#660]
λ scoop install apache
    installing apache (2.4.17)
    downloading https://www.apachelounge.com/download/VC11/binaries/httpd-2.4.17-win32-VC11.zip...The remote server returned an error: (404) Not Found.

and

    λ scoop install apache64bit
    installing apache64bit (2.4.9)
    downloading http://www.apachelounge.com/download/VC11/binaries/httpd-2.4.9-win64-VC11.zip...The remote server returned an error: (404) Not Found.

**Comment by lukesampson** [comment]
Fixed by lukesampson/scoop-extras#171.
