### ISSUE TITLE
ssh doesn't seem to offer public key

### ISSUE THREAD

**Issue by cardonator** [lukesampson/scoop#682]
I've been trying to get public key auth working with Scoop for several weeks and I can't get it working. I have the public key added to the authorized_hosts on the remote system correctly, but when I run ssh -v test@test.com I don't see any offers of the public key that exist in my ~/.ssh folder. I even tried adding it to the agent and nothing.

Also, I have yet to have pshazz automatically add my key to the agent when PS starts.

**Comment by uiltondutra** [comment]
What is your Windows and OpenSSH versions? Do you install it through `openssh` or `git-with-openssh`?

**Comment by cardonator** [comment]
Sorry I didn't reply on this. I never got a good chance to retest it out.
