### ISSUE TITLE
Scoop seems to assume location of `AppData` directory

### ISSUE THREAD

**Issue by alapala** [lukesampson/scoop#685]
Not sure if this is a recently introduced bug or an issue with my configuration. Scoop had been working fine just a few weeks ago, but it now crashes because it seems to think that my `AppData` directory is in another location. My `AppData` is in a non-standard location (i.e., `C:\temp\USERNAME\AppData` as opposed to `C:\Users\USERNAME\AppData`). Is the location of `AppData` now hard-coded?

Console transcript:

    PS C:\temp\USERNAME> scoop update
    gci : Cannot find path 'C:\Users\USERNAME\AppData\Local\scoop\shims' because it does not exist.
    At C:\temp\USERNAME\appdata\local\scoop\apps\scoop\current\lib\commands.ps1:3 char:12
    +         + (gci "$scoopdir\shims") `
    +            ~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\AppData\Local\scoop\shims:String) [Get-ChildItem], ItemNotFoundException
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
    
    updating scoop...
    gci : Cannot find path 'C:\Users\USERNAME\AppData\Local\scoop\shims' because it does not exist.
    At C:\temp\USERNAME\appdata\local\scoop\apps\scoop\current\lib\commands.ps1:3 char:12
    +         + (gci "$scoopdir\shims") `
    +            ~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\AppData\Local\scoop\shims:String) [Get-ChildItem], ItemNotFoundException
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
    
    gci : Cannot find path 'C:\Users\USERNAME\AppData\Local\scoop\shims' because it does not exist.
    At C:\temp\USERNAME\appdata\local\scoop\apps\scoop\current\lib\commands.ps1:3 char:12
    +         + (gci "$scoopdir\shims") `
    +            ~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\AppData\Local\scoop\shims:String) [Get-ChildItem], ItemNotFoundException
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
    
    rm : Cannot find path 'C:\Users\USERNAME\AppData\Local\scoop\apps\scoop\current' because it does not exist.
    At C:\temp\USERNAME\appdata\local\scoop\apps\scoop\current\libexec\scoop-update.ps1:54 char:9
    +         rm -r -force $currentdir -ea stop
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\...s\scoop\current:String) [Remove-Item], ItemNotFoundException
        + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by lukesampson** [comment]
There was a change to this on February 1st (see #667). Scoop now uses `$env:LOCALAPPDATA\scoop` rather than `~/appdata/local/scoop`.

So to get it working you should modify and run these two commands:

```powershell
# to save the LOCALAPPDATA environment variable
[environment]::setenvironmentvariable('LOCALAPPDATA', 'C:\your\path\to\AppData', 'USER')

# optional, so you don't have to restart powershell
$env:localappdata = 'C:\your\path\to\AppData'
```

Does that work?

**Comment by alapala** [comment]
Yes, that it. Thanks!
