### ISSUE TITLE
python27 app manifest removed?

### ISSUE THREAD

**Issue by mmcalli** [lukesampson/scoop#697]
Hi

Just did a scoop status, and received the following message:-

```
scoop is up-to-date.
these app manifests have been removed:
    python27
```

I assume this means it was removed from the buckets in the repo. Is there a reason for that? I have a particular script that only works when I use python27 rather than python 3.5.1.

Regards

Mike

**Comment by deevus** [comment]
Hi Mike

It's been moved to the versions bucket. You just need to add it using `scoop bucket add versions`

**Comment by mmcalli** [comment]
Thanks so much, appreciate it!
