### ISSUE TITLE
slproweb.com mirror down, affects OpenSSL

### ISSUE THREAD

**Issue by robyrobrob** [lukesampson/scoop#710]
This affects updating / installing the OpenSSL binaries using Scoop.

[https://github.com/lukesampson/scoop/blob/master/bucket/openssl.json](https://github.com/lukesampson/scoop/blob/master/bucket/openssl.json)

**Comment by lukesampson** [comment]
I think @berwyn fixed this in #746.

**Comment by berwyn** [comment]
I know slproweb occasionally removes versions, openssl might just need updating. I can look into it today.

**Comment by lukesampson** [comment]
I think it's okay--this is 3 months old.

**Comment by berwyn** [comment]
Fair call! I didn't notice the date. I'll just leave it be then!
