### ISSUE TITLE
Installing Perl crashes PowerShell

### ISSUE THREAD

**Issue by HiroshimaCC** [lukesampson/scoop#721]
Installing Perl (5.22.1.2) makes PowerShell crash during the download of the Strawberry Perl portable package (x64).
`scoop status` then indicate:
> these apps failed to install:
>     perl

OS: Win10 Pro 64 bits

**Comment by william-ellis** [comment]
I have the same problem (Win10 Home 64 bit).
Managed to work around it by redirecting the output when installing (e.g. `scoop install perl > output.txt`). Looks like this avoids the crash thanks to [this line](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L118).

**Comment by nightroman** [comment]
I had similar problems on downloading ModgoDB and Git recently. PowerShell crashed during downloading. May it something to do with some timeouts? I saw this problem only when downloading just released versions. I assume many people were downloading at the same time and the servers were busy. Is there anything to tune in the scoop download procedures?

**Comment by rivy** [comment]
I've also had this randomly occur during the download with multiple different apps. It generally works to completion if I just immediately re-run the same command.

I'm betting it has something to do with the callbacks used during the download process.

**Comment by mrkishi** [comment]
While it usually works on the second time for me as well, I couldn't install Erlang at all. The longer download made it impossible to reach 100% before the inconsistent "powershell has stopped working." Sometimes it happens immediately, but it managed to get up to 60%+ at times.

@william-ellis's suggestion works, thankfully!

**Comment by lukesampson** [comment]
I've disabled the percentage complete display, which seemed to be causing the problems.

**Comment by nightroman** [comment]
Is `$wc.dispose()` needed only with percentage complete?

**Comment by lukesampson** [comment]
It seems to work okay. I'm assuming powershell's garbage collection cleans up when it goes out of scope.
