### ISSUE TITLE
nodejs - specified path is too long

### ISSUE THREAD

**Issue by stphnlwlsh** [lukesampson/scoop#737]
I tried to install nodejs with:

    scoop install nodejs

and got this error in my log file:

    === Logging started: 2016-03-11  23:36:53 ===
    Error 1320. The specified path is too long: C:\Users\StephenWalsh\AppData\Local\scoop\apps\nodejs\5.7.0\_scoop_extract\nodejs\node_modules\npm\node_modules\node-gyp\node_modules\npmlog\node_modules\gauge\node_modules\lodash.padright\node_modules\lodash._createpadding\node_modules\lodash.repeat
    === Logging stopped: 2016-03-11  23:37:06 ===

Any thoughts on how to resolve?

**Comment by neoeinstein** [comment]
This is because `node` uses nested dependency folders. That makes Windows sad if the dependency tree is too deep because Windows has a max path length of 260 characters.

You can set the cache location to be somewhere closer to the root by using:
```
npm config set cache /SOMEWHERE/ELSE
```
But that does limit the usefulness of having had the cache inside your `AppData` folder.

**Comment by stphnlwlsh** [comment]
I figured out how to resolve but it probably wasn't the ideal way. I did through the cached until I found the install file and just ran it through the GUI. Since then one of my .NET projects threw back the same error, so as you noted about the character limit, this isn't Scoop specific.

**Comment by dragon1211** [comment]
Nice to meet you.
I have problem similar with this error.
I tried to installl node v14.5.0, but the error occured.

### C://program files/nodejs is too long path.

**Comment by rashil2000** [comment]
What command have you used to install Node?

**Comment by dragon1211** [comment]
Thanks for you reply.
I checked this error just now.
I think this problem's reason was cache problem, so that I deleted C:\Users\DRAGON\AppData\Local\npm-cache.
After then, I used `nvm install 14.5.0`.
the operation is succeed.

**Comment by dragon1211** [comment]
By the way, as I am a full-stack developer and freelancer, I am looking for good team for developing.
can you introduce it?

**Comment by rashil2000** [comment]
Sorry, I'm not sure I understand the question. Are you looking to use Scoop in your team for development? 

If so, you can find a brief introduction on the website https://scoop.sh and the [Readme](https://github.com/ScoopInstaller/Scoop). For detailed information, you can refer to the Scoop [Wiki](https://github.com/ScoopInstaller/Scoop/wiki).
