### ISSUE TITLE
Install --arch flag silently fails

### ISSUE THREAD

**Issue by MPLew-is** [lukesampson/scoop#750]
When trying to install packages of different architectures, only `-a 32bit/64bit` works, contrary to the documentation provided by `scoop help install`, which states that `--arch` should work (I even tried `--architecture`, as mentioned in #235).

The `--arch` flag is not rejected like the `--architecture` flag is, but the file installed is the default for your system, rather than the architecture specified after the flag. This is certainly a minor issue with a workaround, but it's slightly confusing due to the silent failure.

**Comment by lukesampson** [comment]
Sorry yeah that was a mistake when I mentioned `--architecture`. I think the info in `scoop help install` is correct.

I do get an error when I run
```
$ scoop install test --architecture 32bits
scoop install: option --architecture not recognized
```
And
```
$ scoop install test -architecture 64bit
scoop install: option -a requires an argument
```

So I'm not sure what's going on there...

**Comment by lukesampson** [comment]
Sorry, I should also mention that `--arch` did work for me.

**Comment by lukesampson** [comment]
Do you have `getopt` installed on your path? It could be overriding scoop's implementation.

**Comment by MPLew-is** [comment]
Hmm. Did it install the correct version when you used `--arch`? I'm not receiving any errors, but this is my output for various commands:

Using `--arch` (incorrect):
```
$ scoop install --arch 32bit mysql
installing mysql (5.7.11)
loading https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.11-winx64.zip from cache...
```

Using `-a` (correct):
```
$ scoop install -a 32bit mysql
installing mysql (5.7.11)
loading https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.11-win32.zip from cache...
```

So it's not so much an error, as it just doesn't seem to actually obey `--arch`, and goes with the system default.


And, at least according to `get-command getopt`, I don't have `getopt` installed on my path.

**Comment by MPLew-is** [comment]
Also, I can confirm that using the architecture flag after the app name (as in, `scoop install mysql --arch 32bit`) has the same effect.

**Comment by lukesampson** [comment]
Should be fixed now. Thanks for patiently reporting this!

**Comment by MPLew-is** [comment]
Not a problem. Glad I could help!
