### ISSUE TITLE
PHP 7.0.4 requires Visual C++ Redistributable for Visual Studio 2015

### ISSUE THREAD

**Issue by zQueal** [lukesampson/scoop#763]
Using `scoop` with `scoop install php` on a newly formatted machine brings an error;

    The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem.

Simple research shows that PHP VC17 requires the `Visual C++ Redistributable for Visual Studio 2015` package to be installed. Perhaps `scoop` should automatically check and warn of this upon install? [Link to download](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by lukesampson** [comment]
Oh right. That was supposed to be fixed in #756. I'm assuming you just installed scoop today or ran `scoop update` recently, is that right?

See also #755 for context—we tried installing this automatically, but the admin elevation prompt isn't great.

If you can work out some powershell to check if the dependency is installed, we could show a warning in the "post_install". Happy to accept a pull request if you can work it out. Or maybe @MPLew-is has thoughts?

**Comment by zQueal** [comment]
> I'm assuming you just installed scoop today or ran scoop update recently, is that right?

Probably 4-5 minutes before installing PHP. Correct. 

> If you can work out some powershell to check if the dependency is installed, we could show a warning in the "post_install". Happy to accept a pull request if you can work it out.

I opened this issue because I couldn't find anything too similar and to simply track the issue--but apparently that's not the case. The installer is `MSI` so it should be relatively trivial to implement. I'll take a look into it soon.

**Comment by MPLew-is** [comment]
Hmm, can you verify that there is a `vcruntime140.dll` file in the directory that contains the result of `scoop which php`? Scoop should be downloading the needed DLLs when you run `scoop install php`, and every version of PHP and Windows I've been able to test successfully found the DLLs and ran correctly, even when all Visual C++ Redistributables were uninstalled from the computer.

If that DLL is present and PHP still isn't finding it, then we might have to go back to the installer method.

**Comment by MPLew-is** [comment]
I've gone ahead and made a pull request (#766) so that PHP will work. If we can't find a solution that uses the DLLs directly, or just want to restore functionality until the problem can be investigated further, the pull request will get everything back up and running, even if it does involve administrator prompts.

**Comment by lukesampson** [comment]
Thanks @MPLew-is. Let us know how you go @zQueal.

**Comment by zQueal** [comment]
@MPLew-is 

> Hmm, can you verify that there is a vcruntime140.dll file in the directory that contains [...]

I was unable to find `vcruntime140.dll` in `~\AppData\Local\scoop\apps\php\7.0.4\`. After installing VCR everything works perfectly. As far as I can tell, the dll did not come bundled with `scoop install php` for whatever reason.

**Comment by MPLew-is** [comment]
Are you by any chance running a 32-bit version of Windows? I was unable to locate the DLLs that 32-bit PHP was using on a 64-bit system and thus did not include them as a download, but 32-bit PHP on a 32-bit system might work differently.

**Comment by MPLew-is** [comment]
To clarify, 32-bit PHP on a 64-bit system seems to not require any Visual C++ DLLs at all. I'm not entirely sure why that is, but after uninstalling all Visual C++ Redistributables and combing my registry and system path for any of the `vcruntime` DLLs, I still was not able to find one that caused PHP to fail to start up. 64-bit PHP, on the other hand, gives the exact same error message as you reported when the DLL is missing and not available anywhere in the system.

**Comment by zQueal** [comment]
No, I am running x64 on both Windows and PHP. 

    phpinfo()
    PHP Version => 7.0.4

    System => Windows NT ZQUEAL-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
    Build Date => Mar  2 2016 14:38:13
    Compiler => MSVC14 (Visual C++ 2015)
    Architecture => x64

**Comment by MPLew-is** [comment]
Huh, that's quite strange. I'm running almost exactly the same setup, and I'm not running into any issues with this. What worries me most is that you don't have the DLL, which should have been downloaded when you installed PHP. If you have a minute, could you do the following steps/commands for me?

1. Uninstall Visual C++ 2015 Redistributable from Control Panel

2. `scoop update`

3. `scoop install https://raw.githubusercontent.com/MPLew-is/scoop-experimental/master/php-with-dlls.json`

4. Run `php.exe` in the directory containing the result of `scoop which php` (this directory should have the string `php-with-dlls` in it)

5. Let me know if you still get the same error message. If so, please show me the result of running the `dir` command in the `scoop which php` directory.


Once you're done, you can reset everything to normal with:

1. `scoop uninstall php-with-dlls`

2. `scoop reset php`

3. Re-installing the Visual C++ Redistributable


Thanks for helping me track this down!

**Comment by zQueal** [comment]
After following your steps, it seems to be running fine and `vcruntime140.dll` is included in the working directory.

    Mode                LastWriteTime     Length Name
    ----                -------------     ------ ----
    d----         3/29/2016   4:00 AM            dev
    d----         3/29/2016   4:00 AM            ext
    d----         3/29/2016   4:00 AM            extras
    d----         3/29/2016   4:00 AM            lib
    d----         3/29/2016   4:00 AM            sasl2
    -a---          3/2/2016   3:12 PM     115200 deplister.exe
    -a---          3/2/2016   3:13 PM    1360384 glib-2.dll
    -a---          3/2/2016   3:13 PM      18432 gmodule-2.dll
    -a---          3/2/2016   3:13 PM   25048064 icudt56.dll
    -a---          3/2/2016   3:13 PM    2086912 icuin56.dll
    -a---          3/2/2016   3:13 PM      52224 icuio56.dll
    -a---          3/2/2016   3:13 PM     274432 icule56.dll
    -a---          3/2/2016   3:13 PM    1410560 icuuc56.dll
    -a---         3/29/2016   4:00 AM        282 install.json
    -a---          3/2/2016   3:12 PM      79407 install.txt
    -a---          3/2/2016   3:12 PM    2255360 libeay32.dll
    -a---          3/2/2016   3:12 PM      47616 libenchant.dll
    -a---          3/2/2016   3:13 PM     164352 libpq.dll
    -a---          3/2/2016   3:12 PM     102400 libsasl.dll
    -a---          3/2/2016   3:12 PM     291328 libssh2.dll
    -a---          3/2/2016   3:12 PM       3286 license.txt
    -a---         3/29/2016   4:00 AM       3218 manifest.json
    -a---          3/2/2016   3:12 PM      48108 news.txt
    -a---          3/2/2016   3:21 PM         43 phar.phar.bat
    -a---          3/2/2016   3:21 PM      53242 pharcommand.phar
    -a---          3/2/2016   3:12 PM      66048 php-cgi.exe
    -a---          3/2/2016   3:12 PM      36864 php-win.exe
    -a---          3/2/2016   3:12 PM     122368 php.exe
    -a---          3/2/2016   3:12 PM       2523 php.gif
    -a---         3/29/2016   4:00 AM      70782 php.ini
    -a---          3/2/2016   3:12 PM      70752 php.ini-development
    -a---          3/2/2016   3:12 PM      70784 php.ini-production
    -a---          3/2/2016   3:12 PM      35840 php7apache2_4.dll
    -a---          3/2/2016   3:12 PM     866536 php7embed.lib
    -a---          3/2/2016   3:12 PM     273920 php7phpdbg.dll
    -a---          3/2/2016   3:12 PM    8522240 php7ts.dll
    -a---          3/2/2016   3:12 PM     294400 phpdbg.exe
    -a---          3/2/2016   3:12 PM      21360 readme-redist-bins.txt
    -a---          3/2/2016   3:12 PM      12587 snapshot.txt
    -a---          3/2/2016   3:12 PM     353280 ssleay32.dll
    -a---         3/29/2016   3:58 AM      88752 vcruntime140.dll

    PS C:\Users\zqueal\AppData\Local\scoop\apps\php-with-dlls\7.0.4> php --version
    PHP 7.0.4 (cli) (built: Mar  2 2016 14:42:25) ( ZTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

Additionally, reinstalling works fine, too.

    PS C:\Users\zqueal\AppData\Local\scoop\apps> scoop install php
    installing vc-redist14 (2015)
    loading https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe from cache...
    checking hash...ok
    running installer...done
    vc-redist14 (2015) was installed successfully!
    installing php (7.0.4)
    loading http://windows.php.net/downloads/releases/php-7.0.4-Win32-VC14-x64.zip from cache...
    checking hash...ok
    extracting...done
    creating shim for php
    running post-install script...
    php (7.0.4) was installed successfully!

    PS C:\Users\zqueal\AppData\Local\scoop\apps> php --version
    PHP 7.0.4 (cli) (built: Mar  2 2016 14:42:25) ( ZTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

Really weird! :)

**Comment by MPLew-is** [comment]
Hmm... approximately when did you install scoop on this machine? Everything's resolved now, which means the only explanation I can think of is that somehow scoop installed a version of app that didn't include the DLL or the Visual C++ installer (I made those changes in #755 and #756 because I was running into the same problem as you).

@lukesampson, care to weigh in? I'm not sure what's going on with this.

**Comment by zQueal** [comment]
I recently reformatted prompting a reinstallation of scoop. I believe it was Wednesday.

**Comment by MPLew-is** [comment]
Ah, that may have been it. If `scoop update` wasn't run between then and now, the recent changes to the PHP manifest probably didn't end up getting synced with your computer, and, when you went to install PHP, Visual C++ didn't get downloaded, leading to the same issue that prompted those two pull requests.

Since we know that the DLL version works, I'll go ahead and make a pull request to revert the one made to fix this issue. Thanks for the help!
