### ISSUE TITLE
ffmpeg install fails: access to ffplay.exe fails

### ISSUE THREAD

**Issue by adicarlo** [lukesampson/scoop#773]
On a fresh install of scoop on Windows 10, I'm getting an error installing ffmpeg:

PS C:\Users\Asus_001> scoop install ffmpeg
installing ffmpeg (2016-03-30)
loading https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20160330-git-be746ae-win64-static.7z from cache...
checking hash...ok
extracting...rm : Cannot remove item C:\Users\Asus_001\AppData\Local\scoop\apps\ffmpeg\2016-03-30\_scoop_extract\ffmpeg
20160330-git
-be746ae-win64-static\bin\ffplay.exe: Access to the path 'ffplay.exe' is denied.
At C:\Users\Asus_001\AppData\Local\scoop\apps\scoop\current\lib\install.ps1:246 char:21
+                     rm -r -force "$dir\_scoop_extract" -ea stop
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (ffplay.exe:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by adicarlo** [comment]
A little research shows this has happened before, cf https://github.com/lukesampson/scoop/issues/278

Looks like it wasn't resolved before.  Here's my psversiontable:

Name                           Value
----                           -----
PSVersion                      5.0.10586.122
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.122
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lukesampson** [comment]
It looks like something is putting a file lock on the .exe. Maybe a virus scanner?

**Comment by adicarlo** [comment]
Luke, I'm sure you're right.  McAfee is running but I can't see any settings or knobs related to file permissions.

I managed to get ffmpeg installed by booting into safe mode, then installing again, then meeting again in normal mode.

Is it worthwhile making a note of this somewhere in the documentation?   Or pursuing what is actually causing the problem?  I'm more of a linux guy than a Windows guy but feel free to ask me any questions or followup.

Another option is to just close the ticket and carry on?  Although I feel that other users will hit this...

**Comment by lukesampson** [comment]
I've made it so that installation will continue in this case. The temporary files from the install will be left over but I think that's better than just crashing.
