### ISSUE TITLE
Scoop skipping steps, not raising an error

### ISSUE THREAD

**Issue by damnhandy** [lukesampson/scoop#774]
We have a version of Scoop running internally for a small work group. The only modifications we've made are changing the install script and modifying the manifests to point to files hosted in our environment. Other than that, it is stock Scoop code. 

For the most part, everything works. However, for a small percentage of users, some manifests are not working and it appears scoop is skipping steps but continuing as it the step was successful. For example, here is what it the output looks like when someone is installing git:

    PS C:\> scoop install git
    installing git (2.7.4.windows.1)
    creating shim for git
    can't shim cmd\git.exe: file doesn't exist

In a successful scenario, you see the URL being downloaded, checking the hash, and extracting the archive. In the case of git, it's also skipping the 7zip download as well. I should also note that this is a clean install of scoop and nothing is cached here. The execution policy appears to be working as the installation of scoop works without issue. In my case, the Git manifest also has a dependency on some internal certificates, and those download and install without issue. 

As far as software and OS: we're running Windows 7 Enterprise and PowerShell 4.0. Any insights would be appreciated.

**Comment by lukesampson** [comment]
What do the `url`s look like in your manifests? Are they network paths or URLs? If you can post the manifest that might help.

**Comment by damnhandy** [comment]
The paths are standards HTTPS URLs. We have an Artifactory host set up and are mirroring the files there. The SSL certs are signed by an internal CA, but all of the hosts have the root certs installed.

Here's a variant of the git manifest that is failing:

	{
	  "homepage": "https://git-for-windows.github.io/",
	  "license": "GPL2",
	  "version": "2.7.4.windows.1.internal.5",
	  "architecture": {
		"64bit": {
		  "url": [
			"https://internalhost/scoop/git/PortableGit-2.7.4-64-bit.7z.exe#/dl.7z",
			"https://internalhost/scoop/git/global-1.0.0.gitignore"
		  ],
		  "hash": [
			"d32918f10812b4e60ecbf0524960cff00c8b20d1f0464dab1506d67dbaf8d6cf",
			"84e8c959df8c5a15029f84356d4e70d4d5b70a07c61b07776f3629a6c57a92bb"
		  ]
		}
	  },
	  "depends": "internal-certs",
	  "bin": [
		"cmd\\git.exe",
		"cmd\\gitk.exe",
		"cmd\\git-gui.exe"
	  ],
	  "post_install": [
		"Write-Host \"Configuring Git...\"",
		"git config --global credential.helper wincred",
		"git config --global http.sslCAInfo $env:CERTS_PATH",
		"git config --global http.proxy http://proxy:8888",
		"git config --global http.https://internal.git.host.sslCAInfo $env:CERTS_PATH",
		"git config --global http.https://internal.git.host.proxy NOPROXY",
		"Copy-Item -force $dir\\global-1.0.0.gitignore $env:HOME\\.gitignore_global",
		"git config --global core.excludesfile $env:HOME\\.gitignore_global",
		"git config --global core.autocrlf true",
		"(Get-Content $env:home\\.gitconfig).replace('NOPROXY', ' ') | Set-Content $env:home\\.gitconfig"
	  ],
	  "notes": "To get Git to recognise OpenSSH, you will need to run\n\nscoop install openssh\n[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which ssh)), 'USER')\n\nand then restart powershell.",
	  "checkver": {
		"url": "http://git-scm.com/download/win",
		"re": "\\<a href=\"https://github.com/git-for-windows/git/releases/download/v([^/]+)/"
	  }
	}

I've stripped out the actual internal host name as I can't post it, but it's a standard hostname with nothing fancy. Again, this issue only affects a small port of the of the group. The files can be downloaded by manually on the affected machines via PowerShelll calling `Invoke-WebRequest` or by calling `new-object net.webclient.downloadFile` and that is successful. 

What I have observed is the it appears to jump from line 33 in [`install.ps1`](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L33) directly to line 40 and skips everything in between. There is no indication that lines 34-39 even get called. The call to `create_shims` appears to be called as if the other lines had been successful. I had even tried wrapping that block in a try/catch and added more debug logging and nothing is being logged. It's very, very odd.

**Comment by damnhandy** [comment]
And while I am doing a lot in the post-install steps, that isn't even being called yet. Unless of course, the extra lines are somehow getting in the way.

**Comment by lukesampson** [comment]
That's strange. The manifest looks fine. Have you tried running `set-psdebug -trace 2` to see what happens at each line? I would expect it to give you an error rather than just skip.

**Comment by damnhandy** [comment]
Since I'm still relatively new to PowerShell, I didn't know about that. I'll have these folks give that a whirl tomorrow and hopefully that will yield something useful. Thanks for the tip!

**Comment by damnhandy** [comment]
I've attached a log file from one of the affected users here:

[user_01_debug.txt](https://github.com/lukesampson/scoop/files/204735/user_01_debug.txt)

It's been scrubbed to remove the username and some internal URLs and files, but that's it. The Git manifest we have has a dependency on a ZIP file with some root certificates. That installs fine, but seems to skip the install of 7zip.

**Comment by lukesampson** [comment]
This machine is detected as 32-bit, and there aren't any 32-bit urls in the manifest.

You can force a 64-bit install by using `scoop install [app] -a 64bit`. But if the URLs will work on 64 or 32 bit machines, you should remove the `architecture/64bit` part of the manifest e.g:

```json
...
"version": "2.7.4.windows.1.internal.5",
"url": [
    "https://internalhost/scoop/git/PortableGit-2.7.4-64-bit.7z.exe#/dl.7z",
    "https://internalhost/scoop/git/global-1.0.0.gitignore"
],
"hash": [
   "d32918f10812b4e60ecbf0524960cff00c8b20d1f0464dab1506d67dbaf8d6cf",
   "84e8c959df8c5a15029f84356d4e70d4d5b70a07c61b07776f3629a6c57a92bb"
],
"depends": "internal-certs",
...
```

**Comment by lukesampson** [comment]
This machine is detected as 32-bit, and there aren't any 32-bit urls in the manifest.

You can force a 64-bit install by using `scoop install [app] -a 64bit`. But if the URLs will work on 64 or 32 bit machines, you should remove the `architecture/64bit` part of the manifest e.g:

```json
...
"version": "2.7.4.windows.1.internal.5",
"url": [
    "https://internalhost/scoop/git/PortableGit-2.7.4-64-bit.7z.exe#/dl.7z",
    "https://internalhost/scoop/git/global-1.0.0.gitignore"
],
"hash": [
   "d32918f10812b4e60ecbf0524960cff00c8b20d1f0464dab1506d67dbaf8d6cf",
   "84e8c959df8c5a15029f84356d4e70d4d5b70a07c61b07776f3629a6c57a92bb"
],
"depends": "internal-certs",
...
```

**Comment by damnhandy** [comment]
Yep, we just figured this out while watching one the developers consciously select the 32-bit PowerShell (x86) console. All our machines are 64-bit, so we didn't think to bother to 32-bit. I didn't even consider that folks could select a 32-bit console. Now I know!

I'll take your advice and remove the architecture options. Thanks again! I'll close this out then.
