### ISSUE TITLE
Support for NVM Windows

### ISSUE THREAD

**Issue by jahead** [lukesampson/scoop#783]
I wasn't sure on what the process was for requesting package support but. 

Has there been any thought into adding nvm for windows.
https://github.com/coreybutler/nvm-windows

They have a noinstall version. I maybe able to try and add it if it's something that this project would like.

**Comment by lukesampson** [comment]
I think that'd be great if you want to have a go at adding it.

**Comment by jahead** [comment]
Sweet, I'll do it tomorrow.

**Comment by jahead** [comment]
Just an update. 

I tried to no success. 

```json
{
    "version": "1.1",
    "url": "https://github.com/coreybutler/nvm-windows/releases/download/1.1.0/nvm-noinstall.zip",
    "bin": ["nvm.exe", "elevate.vbs", "elevate.cmd"],
    "env_set": {
        "NVM_HOME": "$dir",
        "NVM_SYMLINK": "c:\\Program Files\\nodejs"
    },
   "post_install": '"root: $dir`npath: C:\\Program Files\\nodejs`narch: 64`nproxy: none" | Out-File $dir\\settings.txt'
}
```
and 
``` json
{
    "version": "1.1",
    "url": "https://github.com/coreybutler/nvm-windows/releases/download/1.1.0/nvm-noinstall.zip",
    "bin": ["nvm.exe"],
    "env_add_path": "\\",
    "env_set": {
        "NVM_HOME": "$dir",
        "NVM_SYMLINK": "c:\\Program Files\\nodejs"
    },
   "post_install": ""root: $dir`npath: C:\\Program Files\\nodejs`narch: 64`nproxy: none" | Out-File $dir\\settings.txt'
}
```

But I ran into an error with their "nvm use 5.10.1" I get "exec: "\\elevate.cmd": file does not exist:" 
which is silly, because I know it's in the PATH. After I have a another look, I may post an issue upstream. 

I will have another crack at it when I have time again. 

Also, I need a way to do a different post_install based on the arch. The settings.txt file needs 32 on 32bit, and 64 on 64bit. I tried nesting post_install in the architecture objects it doesn't seem supported.

**Comment by Cyianor** [comment]
What about checking the architecture in the post-install with the help of
`if ([intptr]::size -eq 8) { ... } else { ... }`?

That's what I did in the `pre_install` of the `r` bucket if you want to take a look.

**Comment by jahead** [comment]
Oh, nice. I tried looking through some examples. Must of missed it. I will try again tonight. >:) 

Is this something that would be a good feature though? Should I make an issue for the feature of nesting post_install in an arch? I might be able to contribute to it, though my available time is a bit short.

**Comment by lukesampson** [comment]
It should work now to put `post_install` under `32bit` or `64bit`. @Cyianor this should work for your `pre_install` too.

**Comment by Cyianor** [comment]
Awesome, @lukesampson ! Then users can finally choose whether to install the 32bit or 64bit version of R! Thanks for adding this feature. I'll give it a try right now.

**Comment by jahead** [comment]
Hey, So I have it all working, except that they have two files that need to be added into

**Comment by jahead** [comment]
Sorry about the Random close... fat fingers... ha. So there's a working copy. I don't really understand how checkver meant to be utilised, I can have a go again later. But yay! You can close this when you merge.

**Comment by lukesampson** [comment]
No worries – thanks for that. `checkver` isn't necessary. It's just a regex used by `bin/checkver` to work out if there's a new version available. There is some more info on `checkver` [here](https://github.com/lukesampson/scoop/wiki/App-Manifests) – but no problem if you don't want to add it.
