### ISSUE TITLE
Not able to install any packages on fresh installed scoop

### ISSUE THREAD

**Issue by JuanNitaelDuque** [lukesampson/scoop#785]
On newly scoop installation i am not being able to install any package, it always throws an error when attempting to download the remote installer. 

![captura](https://cloud.githubusercontent.com/assets/16740089/14484123/6b9fe0ae-0113-11e6-9313-7042537f4e52.JPG)

I can bypass this issue by manually downloading the installers, renaming them and putting them into the `/cache` folder

**Comment by lukesampson** [comment]
Sorry about that. Does it work now?

**Comment by JuanNitaelDuque** [comment]
Yep, it's working now. Thanks
