### ISSUE TITLE
Update binaries apache

### ISSUE THREAD

**Issue by eBaeza** [lukesampson/scoop#787]
I try to install apache but i get an error 404 when try to dowload the binaries so, i check in https://www.apachelounge.com/download and I realized that the binaries are updated to version 2.4.20.

**Comment by Cyianor** [comment]
You should check out https://github.com/lukesampson/scoop/wiki/App-Manifests and the PowerShell command `Get-FileHash`. This way you can fix problems like this yourself next time. 

It is really quite simple :)

**Comment by eBaeza** [comment]
thanks @Cyianor for the next time i'll do what you shared

**Comment by Cyianor** [comment]
@eBaeza great! :)

I guess this can be closed then?
