### ISSUE TITLE
scoop install ant failed

### ISSUE THREAD

**Issue by victorabraham** [lukesampson/scoop#805]
installing ant (1.9.6)
downloading http://mirror.ventraip.net.au/apache//ant/binaries/apache-ant-1.9.6-bin.zip...Exception calling "DownloadFil
e" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Users\victo\AppData\Local\scoop\apps\scoop\current\lib\install.ps1:119 char:5
+     $wc.downloadfile($url, $to)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by victorabraham** [comment]
hash check failed for http://mirror.ventraip.net.au/apache//ant/binaries/apache-ant-1.9.6-bin.zip. expected: 9ff91e8babf
c022b2101884b7981bfb4708390d56df57a7c25c9dc36e2606717, actual: !

**Comment by lukesampson** [comment]
I think this is fixed now, with version 1.9.7. You'll just need to run `scoop update` to get the latest manifest.
