### ISSUE TITLE
Python27 manifest doesn't exist

### ISSUE THREAD

**Issue by hoverbird** [lukesampson/scoop#829]
In several places in your docs, I see `scoop install python27` as a way to install an older version of python, and `scoop reset` as a way to switch to that.  However, I only see a manifest called `python` at present, which is a 3.x version. What's up?

**Comment by deevus** [comment]
You are correct, `python27` is not in the main bucket. It got moved to https://github.com/scoopinstaller/versions

First run `scoop bucket add versions` then try again.

**Comment by hoverbird** [comment]
Awesome, thanks for pointing me towards that. I was really banging my head against the wall for awhile there. Cheers.

**Comment by eranhirs** [comment]
Thanks!
I was getting confused when reading [this](https://github.com/lukesampson/scoop/wiki/Switching-Ruby-And-Python-Versions), you might want to update the documentation.

**Comment by lukesampson** [comment]
Documentation updated. Thanks @eranhirs

**Comment by masaeedu** [comment]
@lukesampson Missed a spot: https://github.com/lukesampson/scoop/wiki/Switching-Ruby-and-Python-Versions

**Comment by lukesampson** [comment]
Thanks @masaeedu 👍
