### ISSUE TITLE
Many versions of ImageMagick

### ISSUE THREAD

**Issue by monotykamary** [lukesampson/scoop#832]
While I was checking out ImageMagick on whether it needed to be updated, I found several versions.

Site | Version
----|----
http://www.imagemagick.org/download/www/binary-releases.html | 6.9.3.8
http://legacy.imagemagick.org/script/binary-releases.php | 6.9.3-10
http://www.imagemagick.org/script/binary-releases.php | 7.0.1-2

The repository follows the first link and it seems like it's a deprecated site for the legacy version of the program. I was wondering if this needs to be updated to the latest legacy version or the latest modern version.

**Comment by lukesampson** [comment]
I would go for version 7 link, since that's what their main website points users to.
