### ISSUE TITLE
Issue adding extras

### ISSUE THREAD

**Issue by dlzharris** [lukesampson/scoop#842]
After installing scoop on Windows 7 and successfully installing several apps, running `scoop bucket add extras` returns the following error:
`'https://github.com/lukesampson/scoop-extras.git' doesn't look like a valid git repository`

Any ideas?

**Comment by deevus** [comment]
Is it possible you had an intermittent connection when you last tried? I was able to run the exact command here (on Windows 10) without issue.

**Comment by dlzharris** [comment]
Strange. I need to connect through a proxy server so it could be something to do with that. I've configured the proxy in scoop, but might need a bit more digging around.

**Comment by deevus** [comment]
Do any of the buckets work? Try `scoop bucket add versions`

**Comment by deevus** [comment]
You may need to configure git to use the proxy as well. It doesn't currently pass that information along
