### ISSUE TITLE
concfg JSON error (need updated manifest)

### ISSUE THREAD

**Issue by saildata** [lukesampson/scoop#844]
@lukesampson thank you for the quick fix on the concfg issue! lukesampson/concfg#19
After `scoop update;scoop update concfg` I realized that the manifest for concfg is still pointing to version 0.2016.01.25

**Comment by lukesampson** [comment]
Sorry, fixed now: 86fdd05

**Comment by saildata** [comment]
Thanks! I literally was just about to push to my updated manifest & issue PR. You've got to publish your templates! Way to fast :sleepy:
