### ISSUE TITLE
Install nodejs > Error 1304

### ISSUE THREAD

**Issue by szcze** [lukesampson/scoop#847]
First off, I'm new to Windows and really thankful for scoop, great work Luke!

Unfortunately on running `$ scoop install nodejs` I get the following:

```
failed to extract files from C:\Users\user\AppData\Local\scoop\apps\node
js\6.1.0\node-v6.1.0-x64.msi.
```

**The log-file says:** 
Error 1304. Error writing to file: C:\Users\user\AppData\Local\scoop\apps\nodejs\6.1.0_scoop_extract\nodejs\node_modules\npm\node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol\node_modules\es5-ext\node_modules\es6-iterator\test\is-iterable.js.  Verify that you have access to that directory.

Disabled Kaspersky > same thing
Run cmd.exe as Admin > same thing

I'm running Windows 7 Pro + SP1

Hope someone can help!

**Comment by monotykamary** [comment]
Try running `$PSVersionTable.PSVersion` in Powershell and see what version you have.

If it's a permissions problem, try to run Powershell as Admin. Uninstall nodejs with `scoop uninstall nodejs` and remove the download cache for nodejs with `scoop cache rm nodejs`. Then run `scoop install nodejs` and see what happens.

In terms of prior experience with Error 1304, I've only ever seen with Guest Users on Windows or with Bitdefender Free Edition. There was even a case where I was testing game connections with the Bitdefender on and disabling didn't help. After I clean removed it and stuck with MSE, I had no problems. If the above doesn't help, it might be a setting particular to Kaspersky.

**Comment by lukesampson** [comment]
Another possibility is a path length longer than the Windows limit of 260 characters. If your username is more than 13 characters long that might put you over the limit for the file you're getting the error on. If that's the case you might need to set the $env:SCOOP environment variable so that programs install to a shorter path.

`[environment]::setEnvironmentVariable('SCOOP','C:\Users\user\scoop','User')` might be enough. You would need to restart powershell and re-install Scoop for that to work.

See [here](https://github.com/lukesampson/scoop/issues/249) for more info, and some steps to keep your existing installation.

**Comment by szcze** [comment]
thanks for your input. I think luke might be on the right track since, I've experienced the "filename is too long" problem several times now. I'll give some feedback after I try setting an environment variable like you suggest luke :)

**Comment by lukesampson** [comment]
Any luck, @szcze? Is it okay to close this?

**Comment by jarlestabell** [comment]
I had the same problem as @szcze, also when having enabled long paths in Win 10. The file it wanted to write had 261 characters.
It worked when setting the SCOOP env-variable :), but it feels like a temporary/accidentally win, that the next time nodejs upgrades, it may have added even deeper recursive dependencies, making the current workaround perhaps not possible in the future.
Longer term, the extractor tool needs to support long paths.

**Comment by lukesampson** [comment]
@jarlestabell I agree it feels like a temporary fix. Still, I don't know of a better fix than changing the SCOOP environment variable for people with long usernames.

The NodeJS install uses an MSI, so it's extracted with `msiexec` which doesn't support long paths. I have tested enabling the "Enable Win32 long paths" setting in Group Policy for Windows 10, but `msiexec` doesn't seem to change its behaviour. I've tried also using the `\\?\` prefix for the `targetdir=` switch to nudge `msiexec` to use long paths, but that doesn't work either.

**Comment by zatchgordon** [comment]
I ran the commands
copy `~\appdata\local\scoop\ `elsewhere
`scoop uninstall scoop`
`powershell`
`[environment]::setEnvironmentVariable('SCOOP','C:\Users\Zac Gordon\scoop','User')`
`iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`
moved old scoop folder
asked what to do with similar file names: said to skip them
`scoop uninstall nodejs`
`scoop install nodejs`

Still getting the
```
failed to extract files from C:\Users\Zac Gordon\AppData\Local\scoop\apps\nodejs\6.7.0\node-v6.7.0-x64.msi.
log file: ~\AppData\Local\scoop\apps\nodejs\6.7.0\msi.log
```
looking at the log file 
`Error 1304. Error writing to file: C:\Users\Zac Gordon\AppData\Local\scoop\apps\nodejs\6.7.0\_scoop_extract\nodejs\node_modules\npm\node_modules\node-gyp\node_modules\path-array\node_modules\array-index\node_modules\es6-symbol\node_modules\es5-ext\node_modules\es6-iterator\test\valid-iterable.js.  Verify that you have access to that directory.`

**Comment by lukesampson** [comment]
@zatchgordon the missing step is to start a new powershell session after changing the `SCOOP` environment variable.

**Comment by tneward** [comment]
NodeJS 7 is definitely failing with a "path too long" error; from the nodejs\7.0.0\msi.log:

> === Logging started: 10/31/2016  16:17:12 ===
Error 1320. The specified path is too long: C:\Users\tneward\AppData\Local\scoop
\apps\nodejs\7.0.0\_scoop_extract\nodejs\node_modules\npm\node_modules\npm-regis
try-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node
_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 10/31/2016  16:17:16 ===

It would be nice if there were a Scoop-defined standard way to put the Scoop directory someplace other than AppData. I realize that certain aspects of Scoop might be lost, but right now I don't see that there's an easy way around this, and it means that NodeJS 7 + Scoop + Windows is a non-starter until one of the following happens:

- NodeJS 7 flattens its installation directory structure, or
- Windows extends its path limits

... and I don't see either of those things happening any time soon. :-/

Scoop loses a great deal of its appeal if this becomes more common.

**Comment by lukesampson** [comment]
Yes, I agree @tneward.

I've switched new installs of Scoop to use `~/scoop` rather than `~/appdata/local/scoop` (see fc54b2fd58b6f8da0930cfe5dd7b7a000d24036c).

That will allow an extra 14 characters for NodeJS paths, while still avoiding needing admin permissions to install.

Existing installations should continue to use the old path.

**Comment by felipecrp** [comment]
Have you tried extract with lessmsi?
