### ISSUE TITLE
Python installation fails with `can't shim python.exe: file doesn't exist` after `creating shim for python`

### ISSUE THREAD

**Issue by moigagoo** [lukesampson/scoop#856]
In `scoop/apps/python/3.5.1/` there's just `uninstall.exe`.

Full console output:
```
scoop install python
installing python (3.5.1)
loading https://www.python.org/ftp/python/3.5.1/python-3.5.1-amd64.exe#/py351.exe from cache...
checking hash...ok
running pre-install script...
running installer...done
creating shim for python
can't shim python.exe: file doesn't exist
```

**Comment by monotykamary** [comment]
I wonder if it's a permissions issue. Try to run `scoop cache rm python` and `scoop install python` as admin.

**Comment by moigagoo** [comment]
@monotykamary Nope, doesn't work.

**Comment by moigagoo** [comment]
I noticed that Python was listed installed in Control Panel. I restored it via the regular installer, then cleanly uninstalled it, and reinstalled with scoop. All went well. Sorry for the fuzz.

**Comment by klauern** [comment]
I had this same issue.  Perhaps there's an issue in the `scoop uninstall python` that should be looked up?

**Comment by minvedacat** [comment]
I have encountered the same issue. Warning like `You may have to repair and uninstall broken python installer from control panel, 'scoop uninstall python' then try 'scoop install python' again`

Otherwise, when a `scoop install` failed, user should not be forced to run `scoop uninstall` manually as the failed `scoop install` process actually polluted the environment.

**Comment by rootex-** [comment]
> I noticed that Python was listed installed in Control Panel. I restored it via the regular installer, then cleanly uninstalled it, and reinstalled with scoop. All went well. Sorry for the fuzz.

3 years have passed and the issue still exists

**Comment by rootex-** [comment]
> I have encountered the same issue. Warning like `You may have to repair and uninstall broken python installer from control panel, 'scoop uninstall python' then try 'scoop install python' again` will be helpful
> 
> Otherwise, when a `scoop install` failed, user should not be forced to run `scoop uninstall` manually as the failed `scoop install` process actually polluted the environment.

does not work
This worked for me:
1. restore and remove via control pannel
2. double-check scoop:
```scoop uninstall python
scoop cache rm python
scoop install python
```
