### ISSUE TITLE
unable to access remote server, but success message received on cli

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#874]
~ $ scoop update
	updating scoop...
	fatal: unable to access 'http://github.com/lukesampson/scoop/': Failed connect to github.com:80; No error updating extras bucket...
	fatal: unable to access 'https://github.com/lukesampson/scoop-extras.git/': Failed connect to github.com:443; No error
	updating nightlies bucket...
	fatal: unable to access 'https://github.com/scoopinstaller/nightlies/': Failed connect to github.com:443; No error
	scoop was updated successfully!
	~ $ [net.webrequest]::DefaultWebProxy.Credentials = new-object net.networkcredential 'correct', 'credentials'
	~ $ scoop update
	updating scoop...
	fatal: unable to access 'http://github.com/lukesampson/scoop/': Failed connect to github.com:80; No error updating extras bucket...
	fatal: unable to access 'https://github.com/lukesampson/scoop-extras.git/': Failed connect to github.com:443; No error
	updating nightlies bucket...
	fatal: unable to access 'https://github.com/scoopinstaller/nightlies/': Failed connect to github.com:443; No error
	scoop was updated successfully!
    ~ $

**Comment by guillermooo** [comment]
Not sure, but Fiddler isn't showing any network activity (by contrast, `iwr https://github.com` is) so maybe there's some blacklisting going on. Anyway, the issue still applies :)

**Comment by lukesampson** [comment]
Can you try running `scoop config proxy [username:password@]host:port` to set your proxy details for scoop? The `scoop update` happens through a `git pull` so that would be why it's not seeing the other credentials you set. There's more info on how the proxy config works [here](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy).

**Comment by guillermooo** [comment]
Awesome, that worked! Thanks @lukesampson !
