### ISSUE TITLE
Wrong hash for mercurial 3.8.1

### ISSUE THREAD

**Issue by igor87z** [lukesampson/scoop#875]
~ $ scoop.cmd install mercurial
installing mercurial (3.8.1)
downloading http://mercurial.selenic.com/release/windows/Mercurial-3.8.1.exe...done
checking hash...hash check failed for http://mercurial.selenic.com/release/windows/Mercurial-3.8.1.exe. expected: 1629e8171461bd2fad09466f5c1beca7a7f3de3d55ebd8eca647a8a3e76c9c6e, actual: b0378236f03ca72c69d265b7d0651cf81fce158eba08f5e0a5ece8160f1b5991!

**Comment by monotykamary** [comment]
That's probably my bad. Although, I remembered that I tested this in my bucket. The file might have actually changed since then. Added PR for Mercurial 3.8.2.

**Comment by lukesampson** [comment]
Should be fixed now. Please run `scoop update`.
