### ISSUE TITLE
MariaDB 10.0.10 Stable General Availability

### ISSUE THREAD

**Issue by ntwb** [lukesampson/scoop#88]
MariaDB 10.0.10 is out (Previous release was v5.5.36)

>  https://mariadb.com/kb/en/what-is-mariadb-100/
>  MariaDB 10.0 is the development version of MariaDB. It is built on the MariaDB 5.5 series with backported features from MySQL 5.6 and entirely new features not found anywhere else.
> 
> Blog posts with details of the reasoning behind calling this version MariaDB 10:
> http://blog.mariadb.org/mariadb-10-0-and-mysql-5-6/
> http://blog.mariadb.org/what-comes-in-between-mariadb-now-and-mysql-5-6/
> http://blog.mariadb.org/explanation-on-mariadb-10-0/

I'm looking at migrating my 'installed' MySQL environment to a scoop MariaDB setup.

More than happy to take a look at this over the coming days though I plan on building on/out Luke's [apache-php-init.ps1](https://gist.github.com/lukesampson/6546858) script so that upgrading MariaDB and similar apps that I use everyday (PHP/Nginx etc) that require 'portable' configs to work for me seamlessly when there is an update available eg. `scoop update mariadb`

In theory this is all possible now, it is just that I haven't actually tried it and would want to update my primary `.profile.ps1` to include said customisations.

If anyone else of the 32 watchers of this repo have some thoughts on how you are currently doing this or suggested ideas that would be awesome if you could share them here :smile:

**Comment by deevus** [comment]
@ntwb What is the status of this?

**Comment by ntwb** [comment]
Pretty much the same, per your comment https://github.com/lukesampson/scoop/issues/126#issuecomment-128665592 might be the way to go, put and store the data elsewhere.

**Comment by r15ch13** [comment]
Implemented with https://github.com/lukesampson/scoop/pull/1410
