### ISSUE TITLE
Running `scoop which` under LocalSystem account

### ISSUE THREAD

**Issue by espenekvang** [lukesampson/scoop#889]
When running `scoop which <installed package>` under LocalSystem account in Windows we get back a string like this:
```
C:~\programdata~\scoop~\apps~\
```

Running the same command under a regular account with Administrator privileges returns the following string:
```
C:\programdata\scoop\apps\
```

As you can see the `~` is present several times in the string causing it to not resolve properly when we are using it inside a script.

Any suggestions to why this is and how we can work around it?

**Comment by lukesampson** [comment]
Did that last commit fix it, once you run `scoop update`?

**Comment by espenekvang** [comment]
No, sorry. Now it returns only `\`

**Comment by lukesampson** [comment]
Sorry, dumb mistake. Should work now.

**Comment by espenekvang** [comment]
Perfect - works now.
