### ISSUE TITLE
[Question/Idea] Is it possible to install programs similar to homebrew-cask?

### ISSUE THREAD

**Issue by SirWindfield** [lukesampson/scoop#892]
You probably already heard of homebrew-cask, a formula that adds regular programs to homebrew like Google Chrome, Firefox, Steam and many many more. Is it possible to do the same with scoop? Not sure if scoop has a similar concept of "formulas".

**Comment by lukesampson** [comment]
I'm not overly familiar with Homebrew, but I think the Scoop equivalent of formulas are "[manifests](https://github.com/lukesampson/scoop/wiki/App-Manifests)" – these are JSON files that declare how to install a program.

Scoop has an [extras bucket](https://github.com/lukesampson/scoop-extras) for GUI programs like [Firefox](https://github.com/lukesampson/scoop-extras/blob/master/firefox.json). For GUI programs there is an option to add Start Menu shortcuts – see [Atom](https://github.com/lukesampson/scoop-extras/blob/master/atom.json) for an example.

To install apps from the extras bucket you need to explicitly add it with `scoop bucket add extras`.
