### ISSUE TITLE
Question: What is the difference between git-with-openssh and git plus openssh 

### ISSUE THREAD

**Issue by StefanHub** [lukesampson/scoop#893]
With the latest git (2.8.2.windows.1) and openssh (5.4p1-1) packages I become an error when cloning a git repo:

```
git clone ssh://git@stash............
Cloning into '...............
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x71690000, RegionSize 0x240000, State 0x10000
C:\Users\User\AppData\Local\scoop\apps\openssh\5.4p1-1\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So, I uninstalled both and tried git-with-openssh (2.8.2.windows.1) and than I get:

```
git clone ssh://git@stash............
Cloning into '...........
error: cannot spawn C:\Users\User\AppData\Local\scoop\apps\openssh\5.4p1-1\bin\ssh.exe: No such file or directory
fatal: unable to fork
```

Hmm, I didn't expect that. Any idea?

I am using Win 10.

I also tried to find a solution for the first problem but the "solution" was to rebase a DLL. Here I stopped and started to try git-with-openssh.

**Comment by uiltondutra** [comment]
Today I tried to install `openssh` on Windows 10 and I had the same issue. But OpenSSH is working fine installing through `git-with-openssh`. The current version (2.9.0) is more recent than the version you tried.

**Comment by nilkesede** [comment]
I'm having the same problem. `git-with-openssh` works like charm

**Comment by rasa** [comment]
Git 2.16 has issues with openssh 5.4. If you need to use them together, install git-with-openssh, and not each of them individually.
