### ISSUE TITLE
scoop.cmd gets UTF-8 BOM on recent updates

### ISSUE THREAD

**Issue by nightroman** [lukesampson/scoop#896]
On some of my machines after updating scoop `scoop.cmd` is encoded as UTF-8 with BOM. Cmd.exe does not treat such files well, it tries to process BOM literally (i.e. unknown command).

**Comment by nightroman** [comment]
I think it is

````
commit 68da60c2c95ac4477bdc2030bbf477505b0ef2d5
Author:	Luke Sampson <me@lukesampson.com>  Fri Jun  3 09:00:40 2016
Committer:	Luke Sampson <me@lukesampson.com>  Fri Jun  3 09:00:40 2016

use UTF8 encoding for shims for better handling of usernames containing special characters (fixes #572)
````

and the culprit line is

````
        "@`"$(resolve-path $path)`" $arg %*" | out-file $shim_cmd -encoding utf8
````

I believe, cmd/bat files should be ASCII.

And a related note. `Out-File` in this scenario is not safe when it is used without `-Width`. The output may be wrapped (i.e. the default width 80 is quite possible). `Set-Content` is better/safer, IMHO.

**Comment by nightroman** [comment]
scoop.cmd is back to ASCII.

Caveat 1. Not sure about the problem #572.

Caveat 2. scoop should be updated twice because the first update presumably uses not yet fixed code.

**Comment by lukesampson** [comment]
Re: Caveat 1 – I don't think this will be a problem anymore, because although #572 fixed special characters in usernames, the problem should also be handled by using relative paths in shims (#507), and the relative path won't contain the username.
