### ISSUE TITLE
Add option to update all packages

### ISSUE THREAD

**Issue by beruic** [lukesampson/scoop#897]
I don't understand why I cannot update all my packages in one go.

I suggest `scoop update --all` or alternatively `scoop update -a`, which should maybe start by updating scoop it self, but I realize this can lead to issues.

**Comment by deevus** [comment]
You can. Use `scoop update *`

**Comment by cenobitedk** [comment]
`scoop update *` doesn't work in Git Bash. The `*` makes scoop look at the contents of the current folder.

E.g.:
```
$ scoop update *
ERROR 'Factory' isn't installed.
ERROR 'Infrastructure' isn't installed.
ERROR 'node' isn't installed.
ERROR 'Site' isn't installed.
ERROR 'Sitecore' isn't installed.
ERROR 'Tooling' isn't installed.
ERROR 'Upgrade' isn't installed.
```

**Comment by Calinou** [comment]
Does it work if you escape the `*` character like this?

```bash
scoop update '*'
# Or
scoop update "*"
```

**Comment by cenobitedk** [comment]
Yes, both works as expected :)

**Comment by rasa** [comment]
`scoop update \*` also works.

**Comment by pedzed** [comment]
> @cenobitedk Does it work if you escape the `*` character like this?
> 
> ```shell
> scoop update '*'
> # Or:
> scoop update "*"
> ```

Using Git Bash (Windows 10 64-Bit), this works. Does it really have to be this cryptic? Do people seriously need to guess and/or search online how to update everything?

I suggest reopening the issue and adding a proper solution to this. I like the idea of `-A -a --all`, but what would be better in my opinion is:
```
scoop update # fetch new version information
scoop upgrade scoop # upgrade Scoop itself (or any other given package)
scoop upgrade # upgrade all packages including Scoop
```
On pretty much every package manager, "update" is not understood as really upgrading a package, but rather fetching package information. Is it an option to change to this behavior next major release?

Awesome project by the way. I love it.

**Comment by h404bi** [comment]
@pedzed 

```
λ scoop alias add upgrade "scoop update *"
λ scoop update
λ scoop upgrade
```

So not everyone uses `--all` or `*`, I can see someone uses `all` in https://github.com/lukesampson/scoop/issues/1745, we can't satisfy all people, thus the `alias` feature is what you need.

**Comment by pedzed** [comment]
@h404bi the thing is that it just doesn't work properly, as the people above me mention. You need to escape the asterisk, which is just bad: an asterisk in a CLI should be avoided.

**Comment by h404bi** [comment]
![20190610092640](https://user-images.githubusercontent.com/5764917/59167060-ea452780-8b61-11e9-96df-91bdc154223e.png)

I can't reproduce what you said `doesn't work properly`. Just add an alias, please have a try.

**Comment by Calinou** [comment]
What about `scoop alias add upgrade "scoop update '*'"`?

**Comment by kid1412621** [comment]
why cannot I just use `scoop update` ?

**Comment by heelrayner** [comment]
> `scoop update *` doesn't work in Git Bash. The `*` makes scoop look at the contents of the current folder.
> 
> E.g.:
> 
> ```
> $ scoop update *
> ERROR 'Factory' isn't installed.
> ERROR 'Infrastructure' isn't installed.
> ERROR 'node' isn't installed.
> ERROR 'Site' isn't installed.
> ERROR 'Sitecore' isn't installed.
> ERROR 'Tooling' isn't installed.
> ERROR 'Upgrade' isn't installed.
> ```

I would recommend using Windows Terminal these days

**Comment by rashil2000** [comment]
Windows Terminal has nothing to do with it. They're talking about the shell, which is bash.

**Comment by heelrayner** [comment]
I should have said power shell. Which would be the shell ;-) `PS C:\Users\heelr> scoop update *
Updating Scoop...
Updating 'extras' bucket...
 * 2dcd5f2ee lazarus: Don't hardcode path to fpcmkcfg.exe in post-inst.. 2 hours ago
 * 530f8e96b kate: Update to version 21.08.3-1467                        3 hours ago
Updating 'games' bucket...
Updating 'main' bucket...
 * e3438923d neovim-nightly: Update to version 0.6.0-dev-570-g14def4d22  3 hours ago
 * fb1e7996a crc: Update to version 1.35.0-4.9.5                         3 hours ago
Scoop was updated successfully!
etcher: 1.5.121 -> 1.7.0
ferdi: 5.6.2 -> 5.6.3
gimp: 2.10.20-1 -> 2.10.28
git: 2.33.0.windows.2 -> 2.33.1.windows.1
github: 2.9.3 -> 2.9.4
hugo: 0.88.1 -> 0.89.2
obs-studio: 27.0.1 -> 27.1.3
opera: 80.0.4170.16 -> 81.0.4196.37
qbittorrent: 4.3.7 -> 4.3.9
retroarch: 1.9.8 -> 1.9.13
rufus: 3.15 -> 3.17
speedtest-cli: 1.0.0 -> 1.1.0
telegram: 3.0.0 -> 3.1.8
ventoy: 1.0.51 -> 1.0.59
vivaldi: 4.1.2369.16 -> 4.3.2439.65
winscp: 5.19.2 -> 5.19.4
Updating 16 outdated apps:`

**Comment by qm3ster** [comment]
It's really weird to use a shell expansion character for this, considering scoop doesn't actually use wildcards.
![image](https://user-images.githubusercontent.com/10551234/141289630-2483d248-645b-473f-876a-214e2f70a2c2.png)
I feel like adding a `--all` flag (and maybe deprecating `*` specifier) would be healthy, bringing the behavior of
`scoop update` and `winget upgrade` closer.

Also `scoop update <packagename> *` upgrades everything, while `winget upgrade <packagename> --all` only upgrades `<packagename>`, but let's be fair, no one should write either of those :v

Again, my preference lays in separating `update` (update repository) from `upgrade` (install packages), but that's clearly not the way it's going to happen on Windows, so this is the next best thing.

If nothing is planned for `scoop upgrade` consider making it an alias to `scoop update` as well.
