### ISSUE TITLE
scoop install fails with 400 Bad Request

### ISSUE THREAD

**Issue by nwykes** [lukesampson/scoop#906]
When attempting to install a few apps like pshazz and concfg I receive a 400 bad request error.

```
PS C:\> scoop install pshazz
installing pshazz (0.2016.03.24.1)
downloading https://github.com/lukesampson/pshazz/archive/4791a84d2e4e5358c64934197ad27804374425c7.zip...
The remote server returned an error: (400) Bad Request.
```

Installing other apps like 7z, openssh, git work fine.

**Comment by lukesampson** [comment]
Thanks for reporting that error. It should be fixed now. Does it work for you?

**Comment by nwykes** [comment]
Working great!  Thanks!
