### ISSUE TITLE
[Help/Suggestion Wanted] Attempt at updating the ghostscript bucket

### ISSUE THREAD

**Issue by MindTooth** [lukesampson/scoop#911]
Hi,

Needed ghostscript for opening .esp-files in Inkscape.  But the app were lacking a bit.  I tried adding a `"bin"` line for both 32/64 bit, and added the `lib` folder under envs.  As that is required by Inkscape.

```json
{
    "homepage": "http://www.ghostscript.com",
    "version": "9.19",
    "license": "http://www.gnu.org/licenses/agpl-3.0.html",
    "architecture": {
        "64bit": {
            "url": "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs919/gs919w64.exe#/dl.7z",
            "hash": "272fbe49981935f9393b829045756b5cfd5946d7acc88753250ab678816a57fc"
        },
        "32bit": {
            "url": "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs919/gs919w32.exe#/dl.7z",
            "hash": "36fd0d44cd8a978254bba597881313f31ddf4ea83470c10c7858ced00620c3e1"
        }
    },
    "bin": if ( test-path( $dir\bin\gswin32.exe ) ) {
      "bin\\gswin32.exe"
    }
    else {
      "bin\\gswin64.exe"
    },
    "env_add_path": [
      "bin",
      "lib"
    ]
}
```

Obviusly I don't know jack s**t about JSON, but I had to try :-P  Can this be achieved somehow?  Also, maybe it's easier to use archive condition?

**Comment by lukesampson** [comment]
I've added those changes c56e687a1b11b373f068a548e94f45e1a9f093c5, following an update to allow architecture-specific `bin`s. Can you run `scoop update` and let me know if it works now?

**Comment by MindTooth** [comment]
Works like a boss! 👍 You're the man..

Also, there is `gsw64c.exe` as the CLI tool.  You'll update, or shall I submit a PR?

**Comment by lukesampson** [comment]
Done! Feel free to submit PRs too if you notice app updates that need to be made.

**Comment by MindTooth** [comment]
Thanks :-)
