### ISSUE TITLE
Integrate GOW into scoop

### ISSUE THREAD

**Issue by gjmveloso** [lukesampson/scoop#915]
Scoop is awesome and I start thinking on a way that we can integrate [GOW](https://github.com/bmatzelle/gow) or probably a more mature and well-maintained "GNU on Windows" solution - like [MinGW](http://mingw.org/) - into scoop. 

I know that some commands like ```grep``` and ```sed``` are in place but we may want to expand this further.

I'm open to try to do this from my own and send the corresponding PR later but I would like to get some guidance before start, if possible :smile: 

Thanks,
Gustavo

**Comment by lukesampson** [comment]
Hi Gustavo. As well as the few standalone unix tools, we also have manifests for [GOW](https://github.com/lukesampson/scoop/blob/master/bucket/gow.json) and the lightweight [busybox](https://github.com/lukesampson/scoop/blob/master/bucket/busybox.json).

And then there's [msys](https://github.com/lukesampson/scoop/blob/master/bucket/msys.json) which I found to be the easiest way to use the MinGW tools. But if you know a better way to do it I'd be happy to merge your PR.

**Comment by gjmveloso** [comment]
My apologies @lukesampson, I didn't saw this in the first time.

Thanks and I'll give busybox a try
Gustavo
