### ISSUE TITLE
ssh-keygen failing to create key pair

### ISSUE THREAD

**Issue by nikolasd** [lukesampson/scoop#916]
**Expected behaviour**
```
PS C:\Users\username\> ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/username/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in C:\Users\username\.ssh\id_rsa.
Your public key has been saved in C:\Users\username\.ssh\id_rsa.pub.
The key fingerprint is:

The key's randomart image is:
```

**Actual Behaviour**
```
PS C:\Users\username\.ssh> ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (//.ssh/id_rsa):
Could not create directory '//.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
open //.ssh/id_rsa failed: No such host or network path.
Saving the key failed: //.ssh/id_rsa.
```

There is a workaround on this issue, ssh-keygen -f c:\users\username\.ssh\id_rsa

it seems that ssh-keygen is not getting the correct $HOME env variable.

**Comment by lukesampson** [comment]
Thanks for the report. Are you using the `ssh-keygen` from `git-with-openssh`? Or `openssh`?

**Comment by nikolasd** [comment]
from `openssh`

**Comment by lukesampson** [comment]
I've updated openssh to set `$HOME` now when it installs. You would need to run `scoop update;scoop uninstall openssh;scoop install openssh` to try the new install.

**Comment by nikolasd** [comment]
That updat did the trick. Now, it works as expected.

**Comment by g-uru** [comment]
how to manually set the homevariable, i have the same issue
