### ISSUE TITLE
Openssh install timing out

### ISSUE THREAD

**Issue by dahendel** [lukesampson/scoop#917]
I tried installing openssh and the download times out. I also tried to visit the page via the browser with the same result. 

![capture](https://cloud.githubusercontent.com/assets/11720061/16490894/1d875732-3ea1-11e6-96b8-9ccbbcee4bcf.PNG)

**Comment by lukesampson** [comment]
It might be a problem with the sourceforge mirror not responding to your location. I'm not sure if we can do anything about that. It seems to work fine for me.

Would it work to use `git-with-openssh` instead?
