### ISSUE TITLE
Install script should not exit PowerShell

### ISSUE THREAD

**Issue by TeaDrivenDev** [lukesampson/scoop#980]
When running the install script again while Scoop is already installed, it prints out "scoop is already installed. run 'scoop update' to get the latest version." and then exits PowerShell.

I see https://github.com/lukesampson/scoop/blob/master/bin/install.ps1#L16 intends to prevent that, but that does not seem to work.

**Comment by lukesampson** [comment]
Thanks for spotting this. I think it's fixed now.

**Comment by TeaDrivenDev** [comment]
Yes, it is. Thanks on behalf of less confused future users. :-)
