### ISSUE TITLE
Install without dependencies?

### ISSUE THREAD

**Issue by DeltaWhy** [lukesampson/scoop#985]
Is there an option to install a package without its dependencies? Specifically I want to install ant and maven, but let them use my system's JVM instead of pulling in an outdated OpenJDK 7 (ref #633 ).

Even better would be something like apt's virtual packages, where ant and maven could depend on a virtual JDK package that could be provided by either openjdk, extras/oraclejdk, or externally by a system-installed version. But I don't know if that would be useful for anything other than Java.

**Comment by lukesampson** [comment]
You can do this now using the `-i` or `--independent` switch, e.g. `scoop install ant -i`. Let me know how you go.

**Comment by DeltaWhy** [comment]
Works great! Thanks for all your work on this project!
